h2oai/h2o-3

h2o-py/docs/connection.rst
h2o-py/docs/frame.rst
h2o-py/docs/h2o.h2o.rst
h2o-py/docs/index.rst
h2o-py/docs/other.rst
h2o-py/h2o/__init__.py
h2o-py/h2o/h2o.py

I try to improve python api documentation and add some example in order to help to understand.

Add some documentation and examples for python API

---

h2o-scala/src/main/scala/water/fvec/H2OFrame.scala

Add functions "colToEnum" and "rename" in H2OFrame

Add functions "colToEnum" and "rename" in H2OFrame - AXA DIL

---

h2o-r/README.md

I think these badges would be helpful for visualizing the popularity of h2o R package.

added useful badges for h2o R package

---

h2o-core/src/main/java/water/nbhm/NonBlockingHashMap.java
h2o-core/src/main/java/water/parser/BufferedString.java

Plus BufferedString.hashCode caches
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/h2oai/h2o-3/44)

Smarter NBHM.toArray

---

h2o-docs/src/product/tutorials/random hyperparmeter search and roadmap.md

improve word choice
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/h2oai/h2o-3/45)

beings -> begins

---

h2o-core/src/main/java/water/fvec/NewChunk.java
h2o-core/src/test/java/water/parser/ParserTest.java

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/h2oai/h2o-3/46)

rare FP roundoff bug in parser

---

.gitignore
git_private_jenkins.sh
h2o-core/src/main/java/water/fvec/Frame.java
h2o-test-accuracy/testng.xml

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/h2oai/h2o-3/50)

ignore auto-test-gen file

---

h2o-core/src/main/java/water/parser/ParseTime.java

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/h2oai/h2o-3/52)

Allow both micros and nanos on times

---

h2o-core/src/main/java/water/fvec/Frame.java

Easier debugging when comparing lots of small frames
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/h2oai/h2o-3/56)

Allow a no-rollups version of Frame .toString

---

h2o-docs/src/product/flow/packs/test-small/impute.flow
h2o-docs/src/product/flow/packs/test-small/index.list

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/h2oai/h2o-3/62)

Added Impute Unit Test for Flow

---

h2o-docs/src/product/flow/packs/test-small/index.list

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/h2oai/h2o-3/65)

Remove impute.flow from index.list

---

h2o-r/h2o-package/R/models.R

Add note about behavior with models using balance_classes.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/h2oai/h2o-3/66)

Update h2o.performance documentation.

---

h2o-core/src/main/java/water/H2O.java
h2o-core/src/main/java/water/util/NetworkUtils.java
h2o-persist-s3/src/main/java/water/persist/PersistS3.java

Summary: Make it configurable via system variable.
Test Plan: manual
Reviewers: pasha, arno
Differential Revision: https://test-4btqyg52txp2.phacility.com/D5
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/h2oai/h2o-3/69)

[HOTFIX] :fire: Remove HTTP protocol restriction from S3 configuration.

---

h2o-core/src/main/java/water/rapids/ast/AstRoot.java
h2o-core/src/main/java/water/rapids/ast/prims/advmath/AstHist.java
h2o-core/src/main/java/water/rapids/ast/prims/advmath/AstKurtosis.java
h2o-py/h2o/frame.py
h2o-r/h2o-package/R/frame.R
h2o-r/tests/testdir_docexamples/runit_Rdoc_kurtosis.R

Adding a kurtosis calculation to H2O. See https://en.wikipedia.org/wiki/Kurtosis.
Not sure about stability, but this has been doing well on most datasets I have tested.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/h2oai/h2o-3/72)

PUBDEV-3008: Implement kurtosis calculation for H2O Frames

---

gradle/scala.gradle

Testing PR
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/h2oai/h2o-3/73)

[BUILD] comments updated

---

h2o-algos/src/main/java/hex/glm/GLM.java
h2o-algos/src/main/java/hex/util/LinearAlgebraUtils.java
h2o-algos/src/test/java/hex/deeplearning/DeepLearningReproducibilityTest.java
h2o-algos/src/test/java/hex/deeplearning/DeepLearningTest.java
h2o-core/src/main/java/hex/ModelBuilder.java
h2o-core/src/main/java/water/fvec/Chunk.java
h2o-core/src/main/java/water/fvec/Frame.java
h2o-core/src/main/java/water/fvec/FrameCreator.java
h2o-core/src/main/java/water/util/FrameUtils.java
h2o-core/src/test/java/water/OOMTest.java
h2o-core/src/test/java/water/TestUtil.java
h2o-core/src/test/java/water/fvec/ExportTest.java
h2o-core/src/test/java/water/fvec/FrameTest.java
h2o-core/src/test/java/water/fvec/RebalanceDatasetTest.java
h2o-core/src/test/java/water/parser/ParseCompressedAndXLSTest.java
h2o-core/src/test/java/water/parser/ParseFolderTest.java
h2o-core/src/test/java/water/parser/ParseFolderTestBig.java
h2o-core/src/test/java/water/parser/ParserTestARFF.java
h2o-core/src/test/java/water/util/FrameUtilsTest.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/h2oai/h2o-3/75)

Fix PUBDEV-3207, PUBDEV-3208, PUBDEV-3211 and a rollup cache bug

---

h2o-r/h2o-package/R/deeplearning.R
h2o-r/tests/testdir_algos/deeplearning/runit_deeplearning_categorical.R

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/h2oai/h2o-3/81)

PUBDEV-3116: Add categorical_encoding for DL in R API

---

h2o-algos/src/main/java/hex/glm/GLM.java

https://0xdata.atlassian.net/browse/PUBDEV-3194
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/h2oai/h2o-3/68)

GLM datainfo imputeMissing and missingBucket parameters were swapped

---

h2o-py/h2o/backend/server.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/h2oai/h2o-3/78)

Fix wrong java path on windows. Fixes PUBDEV-3219

---

h2o-py/h2o/utils/progressbar.py

Progressbar: if we detect that the terminal is too narrow, then attempt to split the progress bar widget into 2 lines, or otherwise switch to file mode. This ensures we won't see repeated partially-overwritten progress bar artifacts in the terminal. Fixes PUBDEV-3217
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/h2oai/h2o-3/80)

Progressbar

---

h2o-py/h2o/backend/connection.py
h2o-py/h2o/backend/server.py
h2o-py/h2o/estimators/estimator_base.py
h2o-py/h2o/exceptions.py
h2o-py/h2o/expr.py
h2o-py/h2o/frame.py
h2o-py/h2o/grid/grid_search.py
h2o-py/h2o/group_by.py
h2o-py/h2o/h2o.py
h2o-py/h2o/utils/progressbar.py
h2o-py/h2o/utils/shared_utils.py
h2o-py/h2o/utils/typechecks.py
h2o-py/tests/testdir_misc/pyunit_typechecks.py

New features in typechecks.py, and improved documentation.
Please take a look if you haven't seen the `typechecks` module before.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/h2oai/h2o-3/95)

Pasha typechecks

---

h2o-core/src/main/java/water/parser/ParseDataset.java

Parsing large amount of small files is inefficient in H2O. This is caused
by the chunk distribution function. Chunks with the same indices are always
stored on the same node. If we have many small files, we will end-up with
most of the chunks on first few nodes of the cluster (regardles of the size
of the cluster). This change tries to even out the amount of work each node
of the cluster does by disabling parallel parse of small files and relying
on distributing the work more uniformly using the keys of the files.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/h2oai/h2o-3/92)

Disable parallel parse if input is large amount of small files

---

h2o-docs/src/product/starting-h2o.rst
h2o-docs/src/product/welcome.rst

PUBDEV-2922 - Adding topic for GLRM in the Algorithms section. This change includes adding the new topic, adding an image to the /images folder, and updating the data-science.rst file to include this new topic.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/h2oai/h2o-3/83)

Angela jenkins

---

h2o-py/h2o/exceptions.py
h2o-py/h2o/grid/grid_search.py
h2o-py/h2o/model/binomial.py
h2o-py/h2o/model/metrics_base.py
h2o-py/h2o/model/model_base.py
h2o-py/h2o/utils/debugging.py
h2o-py/tests/pyunit_utils/utilsPY.py
h2o-py/tests/testdir_algos/gbm/pyunit_NOPASS_cars_checkpointGBM.py
h2o-py/tests/testdir_algos/rf/pyunit_NOPASS_cars_checkpointRF.py
h2o-py/tests/testdir_jira/pyunit_NOPASS_pubdev_1829_gbm_checkpoint.py
h2o-py/tests/testdir_misc/pyunit_metric_accessors.py
h2o-py/tests/testdir_misc/pyunit_plot.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/h2oai/h2o-3/105)

Pasha cleanup

---

h2o-py/tests/testdir_misc/pyunit_std_coef_plot.py
h2o-py/tests/testdir_misc/pyunit_varimp_plot.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/h2oai/h2o-3/106)

changed pyunit tests so that they don't launch the GUI

---

h2o-py/dynamic_tests/testdir_algos/deeplearning/pyunit_deeplearning_gridsearch_over_all_params_large.py
h2o-py/dynamic_tests/testdir_algos/gbm/pyunit_gbm_gridsearch_over_all_params_large.py
h2o-py/dynamic_tests/testdir_algos/glm/pyunit_glm_gridsearch_over_all_params_large.py
h2o-py/dynamic_tests/testdir_algos/glrm/pyunit_glrm_gridsearch_over_all_params_large.py
h2o-py/dynamic_tests/testdir_algos/kmeans/pyunit_kmeans_gridsearch_over_all_params_large.py
h2o-py/dynamic_tests/testdir_algos/rf/pyunit_rf_gridsearch_over_all_params_large.py
h2o-py/dynamic_tests/testdir_algos/rf/pyunit_rf_gridsearch_sorting_metrics.py
h2o-py/h2o/grid/grid_search.py
h2o-py/h2o/model/clustering.py
h2o-py/h2o/model/dim_reduction.py
h2o-py/h2o/model/metrics_base.py
h2o-py/h2o/two_dim_table.py
h2o-py/tests/testdir_misc/pyunit_twodimtable.py

Fixes PUBDEV-3229
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/h2oai/h2o-3/107)

Added pyunit for H2OTwoDimTable and improved (slightly) its functionality. 

---

h2o-core/src/main/java/water/rapids/ast/params/AstStrList.java
h2o-py/h2o/frame.py
h2o-py/h2o/utils/typechecks.py

Prevent server from dying when encountering a list of strings; prevent client from ever sending it in the first place (hopefully)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/h2oai/h2o-3/116)

PUBDEV-3267  

---

h2o-py/h2o/h2o.py
h2o-py/tests/testdir_misc/pyunit_export_file.py
h2o-py/tests/testdir_misc/pyunit_export_file_multi.py

The pull request brings the Python API up to date with the R API, it completes jira PUBDEV-3201.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/h2oai/h2o-3/120)

PUBDEV-3201: Adds support to export to multiple part files to Python API

---

h2o-py/h2o/backend/server.py
h2o-py/h2o/h2o.py
h2o-py/h2o/utils/debugging.py
h2o-py/tests/testdir_jira/h2o.init_test_HOQE-16.py

Make h2o.init() understand max_mem_size/min_mem_size parameters of the form '10g' or '123M'
Added a test for that too.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/h2oai/h2o-3/131)

PUBDEV-2040

---

h2o-algos/src/main/java/hex/tree/CompressedTree.java
h2o-algos/src/main/java/hex/tree/DHistogram.java
h2o-algos/src/main/java/hex/tree/DTree.java
h2o-algos/src/main/java/hex/tree/TreeJCodeGen.java
h2o-algos/src/main/java/hex/tree/TreeVisitor.java

In DHistogram.NASplitDir assign an explicit integer value to each enum constant, so that it can be serialized/deserialized more reliably (including across packages).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/h2oai/h2o-3/127)

DHistogram.NASplitDir 

---

h2o-docs/src/product/data-science/gbm.rst

Added “laplace” and “quantile” to list of distribution options. Removed
duplicated options in the bulleted list of distribution options.
Updated FAQ for the algorithm to use when the dataset has a large
number of columns.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/h2oai/h2o-3/119)

PUBDEV-3274 - Updates to GBM section in User Guide

---

h2o-py/h2o/estimators/estimator_base.py
h2o-py/tests/testdir_javapredict/pyunit_NOPASS_javapredict_dynamic_data_paramsDL.py
h2o-py/tests/testdir_javapredict/pyunit_javapredict_dynamic_data_paramsDRF.py

allow parameter x in model.train() to be empty
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/h2oai/h2o-3/137)

PUBDEV-3295

---

h2o-r/h2o-package/R/gbm.R
h2o-r/h2o-package/R/randomforest.R

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/h2oai/h2o-3/139)

Updated missing default GBM & RF argument values in R client

---

h2o-r/h2o-package/R/models.R

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/h2oai/h2o-3/142)

PUBDEV-3301: Added missing graphics imports in R package

---

h2o-docs/src/product/security.rst

Kerberos authentication documentation added to Security docs page
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/h2oai/h2o-3/143)

Added Kerberos documentation to Security docs

---

h2o-docs/src/product/data-science/gbm.rst

Added more detail to a GBM faq.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/h2oai/h2o-3/145)

PUBDEV-3294: Added detail to GBM FAQ

---

h2o-core/src/main/java/water/parser/ParseTime.java
h2o-core/src/test/java/water/parser/ParseTimeTest.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/h2oai/h2o-3/149)

Fix time parse with trailing blank

---

h2o-docs/src/product/data-science/glm.rst

a small PR to improve the text of the GLM docs
[JIRA PUBDEV-3311](https://0xdata.atlassian.net/browse/PUBDEV-3311)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/h2oai/h2o-3/152)

rgument --> argument

---

h2o-core/src/main/java/water/api/RequestServer.java
h2o-core/src/main/java/water/init/NetworkInit.java
h2o-parsers/h2o-orc-parser/build.gradle

The fix cleanup dependencies of h2o-orc-parser to avoid test failure: "No IP found".
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/h2oai/h2o-3/153)

 Minor buid fixes

---

h2o-docs/src/product/data-science/deep-learning.rst
h2o-docs/src/product/data-science/gbm.rst

updated gbm and deeplearning reference guides. @angela0xdata pls check 👯
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/h2oai/h2o-3/157)

added quick start sections

---

h2o-docs/src/product/data-science/deep-learning.rst
h2o-docs/src/product/data-science/drf.rst
h2o-docs/src/product/data-science/gbm.rst
h2o-docs/src/product/data-science/glm.rst
h2o-docs/src/product/faq.rst

Added Arno’s changes from commit
20f5bae25513fda1b472b246e9e93d553574f5cf.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/h2oai/h2o-3/156)

PUBDEV-3313

---

h2o-algos/src/main/java/hex/tree/CompressedTree.java
h2o-algos/src/main/java/hex/tree/SharedTreeModel.java
h2o-algos/src/main/java/hex/tree/gbm/GBMModel.java
h2o-core/src/main/java/hex/Distribution.java
h2o-core/src/main/java/hex/Model.java
h2o-core/src/main/java/water/api/ModelsHandler.java
h2o-genmodel/build.gradle
h2o-genmodel/src/main/java/hex/genmodel/GenModel.java
h2o-genmodel/src/main/java/hex/genmodel/RawModel.java
h2o-genmodel/src/main/java/hex/genmodel/algos/DrfRawModel.java
h2o-genmodel/src/main/java/hex/genmodel/algos/GbmRawModel.java
h2o-genmodel/src/main/java/hex/genmodel/algos/TreeBasedModel.java
h2o-genmodel/src/main/java/hex/genmodel/utils/GenmodelBitSet.java
h2o-py/h2o/estimators/glm.py
h2o-py/h2o/estimators/kmeans.py
h2o-py/h2o/h2o.py
h2o-py/tests/pyunit_utils/utilsPY.py
h2o-py/tests/testdir_javapredict/pyunit_zipped_model.py

Make sure DrfRawModel keeps the trees in memory after loading them; improve the pyunit test so that it explicitly measures scoring time and compares new zipped model format with POJOs
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/h2oai/h2o-3/158)

POJOs (cont.)

---

h2o-core/src/main/java/water/api/schemas3/TwoDimTableV3.java

null checks for empty table
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/h2oai/h2o-3/163)

allow for an empty table

---

h2o-bindings/bin/gen_python.py
h2o-py/h2o/estimators/aggregator.py
h2o-py/h2o/estimators/deeplearning.py
h2o-py/h2o/estimators/estimator_base.py
h2o-py/h2o/estimators/gbm.py
h2o-py/h2o/estimators/glm.py
h2o-py/h2o/estimators/glrm.py
h2o-py/h2o/estimators/kmeans.py
h2o-py/h2o/estimators/naive_bayes.py
h2o-py/h2o/estimators/pca.py
h2o-py/h2o/estimators/random_forest.py
h2o-py/h2o/estimators/svd.py
h2o-py/h2o/transforms/decomposition.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/h2oai/h2o-3/171)

[PUBDEV-3312] (Py) Implement changes necessary for all algos to instantiate properly

---

h2o-algos/src/main/java/hex/tree/SharedTreeModel.java
h2o-core/src/main/java/hex/grid/GridSearch.java
h2o-core/src/main/java/water/DKV.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/h2oai/h2o-3/169)

Do not check whether key == null in DKV.get

---

h2o-core/src/main/java/water/fvec/Vec.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/h2oai/h2o-3/174)

Add convenience helper to print a Vec to string (via TwoDimTable).

---

gradle.properties
h2o-bindings/bin/gen_all.py
h2o-core/src/main/java/hex/Model.java
h2o-core/src/main/java/water/Keyed.java
h2o-core/src/main/java/water/api/SchemaServer.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/h2oai/h2o-3/176)

some minor changes to base H2O which are necessary for the automl project

---

h2o-algos/src/main/java/hex/schemas/GBMV3.java
h2o-algos/src/main/java/hex/tree/gbm/GBM.java
h2o-algos/src/main/java/hex/tree/gbm/GBMModel.java
h2o-py/h2o/estimators/gbm.py
h2o-py/tests/testdir_algos/gbm/pyunit_ecology_gbm_random_noise.py
h2o-r/h2o-package/R/gbm.R
h2o-r/tests/testdir_algos/gbm/runit_GBM_ecology_random_noise.R

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/h2oai/h2o-3/168)

Add random multiplicate noise for tree contributions PUBDEV-3326

---

h2o-py/tests/testdir_misc/pyunit_hist.py
h2o-r/h2o-package/R/frame.R
h2o-r/tests/testdir_munging/runit_hist.R

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/h2oai/h2o-3/184)

Fix h2o.hist() in R - wasn't honoring the breaks. PUBDEV-3374

---

h2o-dist/buildinfo.json
h2o-hadoop/h2o-cdh5.8-assembly/build.gradle
h2o-hadoop/h2o-cdh5.8/build.gradle
make-dist.sh
settings.gradle

Please review changes and run a ./gradlew dist to verify the new build.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/h2oai/h2o-3/182)

Adding support for CDH 5.8

---

h2o-py/h2o/job.py
h2o-py/h2o/utils/progressbar.py
h2o-py/tests/testdir_javapredict/pyunit_zipped_model.py

PUBDEV-3381
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/h2oai/h2o-3/190)

Allow to hide progress bar using h2o.no_progress()

---

h2o-core/src/main/java/water/fvec/Frame.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/h2oai/h2o-3/195)

[PUBDEV-3283] Do not produce error when trying to download a dataset with 0 rows

---

h2o-core/src/main/java/water/rapids/ast/AstRoot.java
h2o-core/src/main/java/water/rapids/ast/prims/timeseries/AstDiffLag1.java
h2o-py/h2o/frame.py
h2o-py/tests/testdir_munging/pyunit_difflag1.py
h2o-r/h2o-package/R/frame.R
h2o-r/tests/testdir_munging/runit_difflag1.R

This PR conducts a difference on a numeric column in an H2OFrame.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/h2oai/h2o-3/188)

PUBDEV-2707: Diff operation on column in H2O Frame

---

h2o-docs/src/booklets/v2_2015/source/GBMBooklet.tex
h2o-docs/src/booklets/v2_2015/source/RBooklet.tex
h2o-docs/src/product/data-science/gbm.rst
h2o-py/h2o/estimators/gbm.py
h2o-r/h2o-package/R/gbm.R

Updated GBM text to refer to GBM as Gradient Boosting Machine. This
should now be consistent across all documentation.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/h2oai/h2o-3/197)

PUBDEV-3388

---

h2o-py/tests/testdir_javapredict/helper_model_generator.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/h2oai/h2o-3/191)

Made a script for generating many 'raw' models for testing purposes

---

h2o-r/h2o-package/R/frame.R

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/h2oai/h2o-3/202)

PUBDEV-3387: Add argument to H2OFrame.print in R to specify number of rows

---

h2o-algos/src/main/java/hex/aggregator/ModelMetricsAggregator.java
h2o-algos/src/main/java/hex/deeplearning/DeepLearning.java
h2o-algos/src/main/java/hex/deeplearning/DeepLearningModel.java
h2o-algos/src/main/java/hex/glm/GLM.java
h2o-algos/src/main/java/hex/glm/GLMMetricBuilder.java
h2o-algos/src/main/java/hex/glrm/ModelMetricsGLRM.java
h2o-algos/src/main/java/hex/pca/ModelMetricsPCA.java
h2o-algos/src/main/java/hex/svd/SVDModel.java
h2o-algos/src/main/java/hex/tree/SharedTree.java
h2o-algos/src/test/java/hex/XValPredictionsCheck.java
h2o-core/src/main/java/hex/Model.java
h2o-core/src/main/java/hex/ModelBuilder.java
h2o-core/src/main/java/hex/ModelMetricsAutoEncoder.java
h2o-core/src/main/java/hex/ModelMetricsBinomial.java
h2o-core/src/main/java/hex/ModelMetricsMultinomial.java
h2o-core/src/main/java/hex/ModelMetricsRegression.java
h2o-core/src/main/java/water/Atomic.java
h2o-scala/src/test/scala/water/fvec/FrameOpsTest.scala

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/h2oai/h2o-3/203)

Fix CV model metrics lifetime management by making it consistent with DKV

---

h2o-core/src/test/java/water/TestUtil.java
h2o-parsers/h2o-parquet-parser/src/main/java/water/parser/parquet/ChunkConverter.java
h2o-parsers/h2o-parquet-parser/src/main/java/water/parser/parquet/ParquetParser.java
h2o-parsers/h2o-parquet-parser/src/test/java/water/parser/parquet/ParseTestParquet.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/h2oai/h2o-3/199)

Improvements in Parquet support (Timestamp type + tests)

---

h2o-core/src/main/java/water/api/FramesHandler.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/h2oai/h2o-3/204)

Fix NPE - client's getFrames would fail.

---

h2o-py/h2o/frame.py

Fixed bug in `structure()`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/h2oai/h2o-3/207)

PUBDEV-3409: Python Structure() Breaks When Applied to Entire Dataframe

---

h2o-docs/src/product/glossary.rst

Updated the description of “epoch” in the UG glossary. Will update
“batch size” and “iteration” if required.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/h2oai/h2o-3/208)

Updated epoch description

---

h2o-algos/src/main/java/hex/tree/SharedTreeModel.java
h2o-algos/src/main/java/hex/tree/drf/DRFModel.java
h2o-algos/src/main/java/hex/tree/gbm/GBMModel.java
h2o-core/src/main/java/hex/Model.java
h2o-core/src/main/java/water/api/ModelsHandler.java
h2o-core/src/main/java/water/api/RegisterV3Api.java
h2o-core/src/main/java/water/api/RequestServer.java
h2o-genmodel/src/main/java/hex/genmodel/MojoModel.java
h2o-genmodel/src/main/java/hex/genmodel/algos/DrfModel.java
h2o-genmodel/src/main/java/hex/genmodel/algos/GbmModel.java
h2o-genmodel/src/main/java/hex/genmodel/algos/TreeBasedModel.java
h2o-genmodel/src/main/java/hex/genmodel/tools/PredictCsv.java
h2o-py/tests/testdir_javapredict/pyunit_mojo.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/h2oai/h2o-3/209)

[PUBDEV-3417] Update all mentions of Raw / Zipped models to the official name: MOJO

---

h2o-py/h2o/h2o.py
h2o-py/h2o/model/model_base.py
h2o-py/tests/testdir_javapredict/pyunit_mojo.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/h2oai/h2o-3/213)

[PUBDEV-3364] Python bindings for the new MOJO models

---

h2o-docs/src/product/data-science/gbm.rst

Added “huber” to list of GBM distribution options. (Note that
huber_alpha was previously added.)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/h2oai/h2o-3/215)

Add huber distribution option

---

h2o-py/h2o/frame.py
h2o-py/h2o/utils/typechecks.py
h2o-py/tests/testdir_munging/binop/pyunit_intdiv.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/h2oai/h2o-3/205)

[PUBDEV-3411] In H2OFrame make all binary operations check the type / dimension compatibility of their arguments before executing

---

h2o-genmodel/src/main/java/hex/genmodel/MojoModel.java
h2o-genmodel/src/main/java/hex/genmodel/algos/DrfModel.java
h2o-genmodel/src/main/java/hex/genmodel/algos/GbmModel.java
h2o-genmodel/src/main/java/hex/genmodel/algos/TreeBasedModel.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/h2oai/h2o-3/216)

[PUBDEV-3427] Provide a way for users to supply custom MojoReader in MojoModel.load()

---

gradle/s3sync.gradle
h2o-core/src/test/java/water/TestUtil.java
h2o-parsers/h2o-orc-parser/src/test/java/water/parser/ParseTestMultiFileOrc.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/h2oai/h2o-3/217)

Hot fix of s3 sync

---

h2o-r/h2o-package/R/kvstore.R
h2o-r/tests/testdir_misc/runit_mojo.R

This PR provides an R binding for the new MOJO models. Simple runit is applied with this PR, as well.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/h2oai/h2o-3/219)

PUBDEV-3363: R binding for MOJO

---

h2o-persist-s3/src/main/java/water/persist/PersistS3.java

The method `#uriToKey` listed content of bucket instead of getting a single file reference.
Note: this does not fix REST API
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/h2oai/h2o-3/223)

[PUBDEV-3384] PersistS3 API imported more than 1 file if a single file was requested

---

h2o-py/h2o/frame.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/h2oai/h2o-3/224)

PUBDEV-3441: .structure() encounters list index out of bounds when nan is encountered in column

---

h2o-r/h2o-package/R/kvstore.R
h2o-r/tests/testdir_misc/runit_pojo.R

Add typechecking for h2o.download_pojo and a runit for this functionality
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/h2oai/h2o-3/225)

PUBDEV-3445: Add type checking to h2o.download_pojo

---

h2o-r/h2o-package/R/frame.R

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/h2oai/h2o-3/230)

PUBDEV-3444: Ensure functions have `h2o.*` alias in R API

---

README.md
h2o-algos/src/main/java/hex/grep/Grep.java
h2o-algos/src/test/java/hex/grep/GrepTest.java
h2o-core/src/main/java/water/DKV.java
h2o-core/src/test/java/water/TestUtil.java

- Grep does not recompile the pattern, does it just once
- GrepTest checks some data
- Removed unnecessary .toString() in DKV
- Fixed TestUtil: it was using Java assert, instead of JUnit Assert.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/h2oai/h2o-3/222)

Some small changes:

---

h2o-py/h2o/expr.py
h2o-py/h2o/frame.py
h2o-py/h2o/schemas/error.py
h2o-py/tests/testdir_javapredict/pyunit_javapredict_dynamic_data_paramsGLM.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/h2oai/h2o-3/220)

[PUBDEV-3278] [PUBDEV-3277] [PUBDEV-3430] [PUBDEV-3440] Changes to H2OFrame setter

---

h2o-core/src/main/java/water/parser/ParseSetup.java
h2o-parsers/h2o-parquet-parser/src/main/java/org/apache/parquet/hadoop/VecParquetReader.java
h2o-parsers/h2o-parquet-parser/src/main/java/water/parser/parquet/ParquetParser.java
h2o-parsers/h2o-parquet-parser/src/main/java/water/parser/parquet/ParquetParserProvider.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/h2oai/h2o-3/233)

Improvement of Parquet parser - metadata don't need to be repeatedly read from Vec

---

h2o-py/dynamic_tests/testdir_algos/gbm/pyunit_gbm_gridsearch_over_all_params_large.py
h2o-py/dynamic_tests/testdir_algos/glm/pyunit_glm_gaussian_large.py
h2o-py/dynamic_tests/testdir_algos/glm/pyunit_glm_gridsearch_over_all_params_large.py
h2o-py/dynamic_tests/testdir_algos/glrm/pyunit_glrm_gridsearch_over_all_params_large.py
h2o-py/dynamic_tests/testdir_algos/kmeans/pyunit_kmeans_gridsearch_over_all_params_large.py
h2o-py/dynamic_tests/testdir_algos/naivebayes/pyunit_naivebayes_gridsearch_over_all_params_large.py
h2o-py/dynamic_tests/testdir_algos/pca/pyunit_pca_gridsearch_over_all_params_large.py
h2o-py/dynamic_tests/testdir_algos/rf/pyunit_rf_gridsearch_over_all_params_large.py
h2o-py/dynamic_tests/testdir_algos/rf/pyunit_rf_gridsearch_sorting_metrics.py

Fixed test due to recent API changes.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/h2oai/h2o-3/243)

Dynamic test.  Replaced deprecated function calls.

---

h2o-r/h2o-package/R/frame.R

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/h2oai/h2o-3/241)

Fix docstrings and parameters for h2o.str() and h2o.as_date()

---

h2o-core/src/main/java/water/rapids/Rapids.java
h2o-core/src/main/java/water/rapids/Session.java
h2o-core/src/main/java/water/rapids/ast/AstRoot.java
h2o-core/src/main/java/water/rapids/ast/prims/assign/AstAssign.java
h2o-core/src/main/java/water/rapids/ast/prims/assign/AstRectangleAssign.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/h2oai/h2o-3/244)

Minor Rapids fixes

---

h2o-core/src/main/java/water/parser/ParseTime.java

Allow others to use H2O's time parser to try and pick out valid times on
a bewildering array of formats.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/h2oai/h2o-3/250)

Make parse attempt public

---

h2o-py/h2o/backend/server.py
h2o-py/h2o/h2o.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/h2oai/h2o-3/249)

[PUBDEV-3475] [PUBDEV-3233] fix Java search on Windows and remove JDK requirement

---

h2o-algos/src/main/java/hex/deeplearning/DeepLearningModel.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/h2oai/h2o-3/232)

[PUBDEV-3434] Possible fix

---

h2o-r/h2o-package/R/frame.R

Reverts h2oai/h2o-3#232
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/h2oai/h2o-3/255)

Revert "[PUBDEV-3434] Possible fix"

---

gradle.properties

Forgot to remove in last rebase.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/h2oai/h2o-3/256)

[MINOR] By default SSL tests shouldn't run, should run in separate builds

---

h2o-algos/src/main/java/hex/schemas/DRFV3.java
h2o-algos/src/main/java/hex/schemas/GBMV3.java
h2o-algos/src/main/java/hex/tree/SharedTree.java
h2o-algos/src/main/java/hex/tree/SharedTreeModel.java
h2o-algos/src/test/java/hex/tree/gbm/GBMTest.java
h2o-core/src/main/java/hex/Model.java
h2o-core/src/main/java/hex/ModelBuilder.java
h2o-core/src/main/java/water/util/FrameUtils.java
h2o-py/h2o/estimators/gbm.py
h2o-py/h2o/estimators/random_forest.py
h2o-r/h2o-package/R/gbm.R
h2o-r/h2o-package/R/randomforest.R

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/h2oai/h2o-3/248)

Add categorical encoding scheme to tree algos (DRF/GBM).

---

h2o-py/h2o/display.py
h2o-py/h2o/h2o.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/h2oai/h2o-3/240)

[PUBDEV-2350] H2OFrames are not displaying in ipython terminal

---

h2o-r/h2o-package/R/classes.R

This PR will give a better print statement for PCA in regards to it NOT having model metrics.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/h2oai/h2o-3/270)

PUBDEV-3461: Printed PCA model metrics in R is missing

---

h2o-algos/build.gradle
h2o-algos/src/main/java/hex/deepwater/backends/TensorflowBackend.java
h2o-algos/src/test/java/hex/deepwater/DeepWaterAbstractIntegrationTest.java
h2o-algos/src/test/java/hex/deepwater/DeepWaterMXNetIntegrationTest.java
h2o-algos/src/test/java/hex/deepwater/DeepWaterTensorflowIntegrationTest.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/h2oai/h2o-3/263)

Add tensorflow integration to deepwater branch

---

h2o-r/h2o-package/R/import.R
h2o-r/h2o-package/R/parse.R

just links between manual pages, works nice in pdf and html versions
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/h2oai/h2o-3/231)

importFile link in man, closes PUBDEV-1796

---

h2o-r/h2o-package/R/kvstore.R

This PR will do the following:
1. Print the POJO file name if `path != ""` otherwise it will pretty print the POJO.
2. Print the MOJO file name ,i.e., `GBM1234.zip`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/h2oai/h2o-3/269)

PUBDEV-3465: Sync up functionality of download_mojo and download_pojo in R & Py

---

h2o-algos/src/main/java/hex/kmeans/KMeans.java
h2o-algos/src/main/java/hex/kmeans/KMeansModel.java
h2o-algos/src/main/java/hex/schemas/KMeansV3.java
h2o-algos/src/test/java/hex/kmeans/KMeansRandomTest.java
h2o-algos/src/test/java/hex/kmeans/KMeansTest.java
h2o-core/src/main/java/hex/ClusteringModel.java
h2o-core/src/main/java/hex/ClusteringModelBuilder.java
h2o-core/src/main/java/water/api/schemas3/ClusteringModelParametersSchemaV3.java
h2o-core/src/main/java/water/util/ArrayUtils.java
h2o-py/h2o/estimators/kmeans.py
h2o-r/h2o-package/R/kmeans.R

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/h2oai/h2o-3/254)

Implement Lee's modified K-means algorithm to estimate K

---

h2o-algos/testMultiNode.sh
h2o-core/src/test/java/water/TestUtil.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/h2oai/h2o-3/273)

Let the user set the min required cloud size via -DcloudSize=XX.

---

h2o-algos/src/main/java/hex/kmeans/KMeans.java
h2o-algos/src/main/java/hex/kmeans/KMeansModel.java
h2o-algos/src/test/java/hex/kmeans/KMeansRandomTest.java
h2o-algos/src/test/java/hex/kmeans/KMeansTest.java
h2o-py/h2o/estimators/kmeans.py
h2o-r/h2o-package/R/kmeans.R
h2o-r/tests/testdir_golden/runit_km2_2_golden.R

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/h2oai/h2o-3/277)

Improve K-Means further

---

h2o-py/h2o/frame.py
h2o-py/h2o/utils/shared_utils.py
h2o-py/tests/testdir_jira/pyunit_pubdev_2891.py
h2o-py/tests/testdir_misc/pyunit_frame_from_pandas.py
h2o-py/tests/testdir_misc/pyunit_frame_show.py

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/h2oai/h2o-3/268)

[PUBDEV-3268] [PUBDEV-3489] fix conversion of pandas DataFrame into H2OFrame: handle column names correctly

---

h2o-algos/testSSL.sh

The tshark output is too big for awk...
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/h2oai/h2o-3/257)

[MINOR] Change awk -> sed in ssl test script, awk segfaults our Jenkins

---

h2o-core/src/main/java/water/rapids/ast/params/AstNumList.java
h2o-core/src/main/java/water/rapids/ast/prims/assign/AstRectangleAssign.java
h2o-core/src/main/java/water/util/ArrayUtils.java
h2o-core/src/test/java/water/rapids/ast/prims/assign/AstRectangleAssignTest.java
h2o-r/tests/testdir_misc/runit_assignSlice_large.R
h2o-r/tests/testdir_munging/slice/runit_sliceAssign.R

needs more tests
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/h2oai/h2o-3/261)

PUBDEV-3416: Implements assignment to a sliced frame

---

h2o-algos/src/main/java/hex/DataInfo.java
h2o-algos/src/main/java/hex/glrm/GLRM.java
h2o-algos/src/main/java/hex/glrm/GLRMModel.java
h2o-algos/src/main/java/hex/glrm/GlrmLoss.java
h2o-algos/src/main/java/hex/pca/PCA.java
h2o-algos/src/main/java/hex/schemas/GLRMV3.java
h2o-algos/src/test/java/hex/glrm/GLRMCategoricalTest.java
h2o-algos/src/test/java/hex/glrm/GLRMGridTest.java
h2o-algos/src/test/java/hex/glrm/GLRMTest.java
h2o-core/src/main/java/hex/ModelBuilder.java
h2o-core/src/main/java/water/H2O.java
h2o-core/src/main/java/water/Iced.java
h2o-core/src/main/java/water/api/ModelBuilderHandler.java
h2o-core/src/main/java/water/api/ModelCacheManager.java
h2o-core/src/main/java/water/api/ModelMetricsHandler.java

* Split out GlrmLoss into a separate class (in preparation for Mojos);
* Fix multiple warnings and normalized whitespace in GLRM / GLRMModel;
* Removed `H2O.getMCM()` method because it tried to instantiate a utility class `ModelCacheManager`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/h2oai/h2o-3/285)

Glrm refactoring

---

h2o-py/h2o/__init__.py
h2o-py/h2o/demos.py
h2o-py/h2o/h2o.py
h2o-py/h2o/h2o_data/iris.csv

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/h2oai/h2o-3/276)

Make h2o.data_file() more convenient to use

---

h2o-py/h2o/backend/connection.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/h2oai/h2o-3/294)

Make h2o.api(..., save_to=...) understand user home directory ('~')

---

h2o-algos/src/main/java/hex/tree/SharedTreeModel.java
h2o-algos/src/main/java/hex/tree/gbm/GBMModel.java
h2o-core/src/main/java/hex/Model.java
h2o-genmodel/src/main/java/hex/genmodel/algos/GbmModel.java
h2o-genmodel/src/main/java/hex/genmodel/utils/ParseUtils.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/h2oai/h2o-3/303)

Minor tweaks to MOJO.

---

h2o-docs/src/product/data-science/k-means.rst
h2o-docs/src/product/flow.rst
h2o-docs/src/product/grid-search.rst

Added estimate_k to the list of options in the Kmeans section, in Flow (under the list of options), and in the grid-search topic.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/h2oai/h2o-3/290)

PUBDEV-3506: new Kmeans option

---

h2o-py/h2o/backend/connection.py
h2o-py/h2o/h2o.py
h2o-py/h2o/utils/config.py
h2o-r/h2o-package/R/classes.R
h2o-r/h2o-package/R/communication.R
h2o-r/h2o-package/R/connection.R

@st-pasha @ledell @navdeep-G
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/h2oai/h2o-3/286)

ability to add cookies to requests made by r/py clients

---

h2o-docs/src/product/security.rst

Added SSL Internode Security section to the Security topic in the User Guide. Also fixed case for headings.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/h2oai/h2o-3/258)

PUBDEV-3134

---

h2o-docs/src/product/faq.rst

Added information about diagnosing and debugging memory issues in H2O. This is related to a google stream topic:
https://groups.google.com/forum/#!searchin/h2ostream/gcviewer|sort:relev
ance/h2ostream/Dc6l4xzwkaU/n-w2p02mBwAJ
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/h2oai/h2o-3/312)

Add memory troubleshooting tips

---

h2o-core/src/main/java/hex/Model.java
h2o-genmodel/src/main/java/hex/genmodel/utils/ParseUtils.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/h2oai/h2o-3/309)

Minor fixes for POJO scoring error count and for MOJO init file parsing.

---

h2o-algos/src/main/java/hex/deeplearning/DeepLearningModel.java
h2o-algos/src/main/java/hex/schemas/DeepLearningV3.java
h2o-core/src/main/java/water/util/FrameUtils.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/h2oai/h2o-3/316)

Minor cleanup

---

h2o-docs/src/booklets/v2_2015/source/DeepLearningBooklet.tex

Fixed the link for the Deep Learning Performance Tuning Guide.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/h2oai/h2o-3/317)

Deep Learning booklet fix

---

h2o-app/src/main/java/water/H2OApp.java
h2o-core/src/main/java/water/H2O.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/h2oai/h2o-3/310)

PUBDEV-3527 Check that Java version is 1.6-1.8 and exit otherwise

---

h2o-algos/src/main/java/hex/deeplearning/DeepLearningModel.java
h2o-algos/src/main/java/hex/glm/GLMModel.java
h2o-algos/src/main/java/hex/kmeans/KMeansModel.java
h2o-algos/src/main/java/hex/naivebayes/NaiveBayesModel.java
h2o-algos/src/main/java/hex/pca/PCAModel.java
h2o-algos/src/main/java/hex/svd/SVDModel.java
h2o-algos/src/main/java/hex/tree/SharedTreeModel.java
h2o-algos/src/test/java/hex/example/WorkFlowTest.java
h2o-algos/src/test/java/hex/tree/gbm/GBMTest.java
h2o-core/src/main/java/hex/Model.java
h2o-core/src/main/java/hex/ModelMetricsMultinomial.java
h2o-core/src/main/java/hex/ScoringInfo.java
h2o-core/src/main/java/water/parser/ParseSetup.java
h2o-core/src/main/java/water/util/ArrayUtils.java
h2o-core/src/main/java/water/util/MRUtils.java
h2o-core/src/main/java/water/util/RandomUtils.java
h2o-core/src/main/java/water/util/StringUtils.java
h2o-core/src/test/java/water/TestUtil.java
h2o-genmodel/src/main/java/hex/genmodel/GenModel.java
h2o-genmodel/src/main/java/hex/genmodel/MojoModel.java
h2o-py/h2o/model/model_base.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/h2oai/h2o-3/318)

Cleanup of various utilities, MOJO, scoring, etc.

---

h2o-dist/buildinfo.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/h2oai/h2o-3/324)

[MINOR] Fix links for download h2o on hadoop

---

h2o-py/h2o/frame.py

https://0xdata.atlassian.net/browse/PUBDEV-3539
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/h2oai/h2o-3/322)

py: reference correct name in frame_id setter

---

h2o-r/h2o-package/R/communication.R

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/h2oai/h2o-3/321)

add stacktrace to output when job fails

---

h2o-core/src/main/java/hex/Model.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/h2oai/h2o-3/335)

Add support for passing a string to the RowData for POJO/MOJO scoring.

---

h2o-py/h2o/demos.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/h2oai/h2o-3/331)

[PUBDEV-2290] Use frame.describe() instead of frame.summary() in demos

---

h2o-docs/src/product/data-science/gbm-params/balance_classes.rst
h2o-docs/src/product/data-science/gbm-params/class_sampling_factors.rst
h2o-docs/src/product/data-science/gbm-params/max_after_balance_size.rst
h2o-docs/src/product/data-science/gbm-params/max_hit_ratio_k.rst
h2o-docs/src/product/data-science/gbm-params/nbins.rst
h2o-docs/src/product/data-science/gbm-params/nbins_cats.rst
h2o-docs/src/product/data-science/gbm-params/nbins_top_level.rst

code examples for the first set of detailed GBM parameters found in the user guide, second commit is just a simple reordering or sections
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/h2oai/h2o-3/340)

Pubdev 3548

---

h2o-core/src/main/java/hex/ModelBuilder.java

The `_toDelete` map should e accessed only from driver.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/h2oai/h2o-3/341)

[HOTFIX] Make `_toDelete` field transient

---

h2o-core/src/main/java/hex/GainsLift.java
h2o-core/src/main/java/hex/MeanResidualDeviance.java
h2o-core/src/main/java/water/MRTask.java
h2o-core/src/main/java/water/fvec/Vec.java
h2o-core/src/main/java/water/util/Tabulate.java

+ adding a small function to `Vec` class to cast the vec into "Time" type.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/h2oai/h2o-3/343)

Fixing multiple bugs in MRTask

---

h2o-core/src/main/java/hex/Model.java
h2o-genmodel/src/main/java/hex/genmodel/easy/EasyPredictModelWrapper.java

In particular, report the correct number of mispredicted rows; report each row only once; make easy to compare between the expected and actual rows; do not ignore Prediction exceptions
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/h2oai/h2o-3/336)

Model.java: improve error checking and reporting in testJavaScoring()

---

h2o-algos/src/main/java/hex/deepwater/DeepWater.java
h2o-algos/src/main/java/hex/deepwater/DeepWaterModel.java
h2o-algos/src/main/java/hex/deepwater/DeepWaterModelInfo.java
h2o-algos/src/main/java/hex/deepwater/DeepWaterModelMojo.java
h2o-algos/src/main/java/hex/deepwater/DeepWaterParameters.java
h2o-algos/src/main/java/hex/deepwater/DeepWaterTask.java
h2o-algos/src/main/java/hex/schemas/DeepWaterV3.java
h2o-algos/src/test/java/hex/deepwater/DeepWaterAbstractIntegrationTest.java
h2o-py/h2o/estimators/deepwater.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/h2oai/h2o-3/351)

Add problem_type to the client APIs.

---

h2o-core/src/main/java/water/rapids/ast/AstRoot.java
h2o-core/src/main/java/water/rapids/ast/prims/mungers/AstGetrow.java
h2o-core/src/main/java/water/rapids/ast/prims/mungers/AstNrow.java
h2o-core/src/test/java/water/rapids/ast/prims/mungers/AstGetrowTest.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/h2oai/h2o-3/354)

Add (getrow frame) rapids call, to convert a single-row frame into a ValRow

---

h2o-algos/src/main/java/hex/deeplearning/DeepLearningModelInfo.java
h2o-algos/src/main/java/hex/deepwater/DeepWater.java
h2o-algos/src/main/java/hex/deepwater/DeepWaterModel.java
h2o-algos/src/main/java/hex/deepwater/DeepWaterModelInfo.java
h2o-algos/src/main/java/hex/deepwater/DeepWaterParameters.java
h2o-algos/src/main/java/hex/deepwater/DeepWaterTask.java
h2o-algos/src/main/java/hex/deepwater/DeepwaterMojoWriter.java
h2o-algos/src/main/java/hex/schemas/DeepWaterV3.java
h2o-algos/src/test/java/hex/deeplearning/DeepLearningTest.java
h2o-algos/src/test/java/hex/deepwater/DeepWaterAbstractIntegrationTest.java
h2o-algos/src/test/java/hex/deepwater/DeepWaterMXNetIntegrationTest.java
h2o-core/src/main/java/hex/Model.java
h2o-core/src/main/java/water/fvec/Vec.java
h2o-core/src/main/java/water/util/FrameUtils.java
h2o-genmodel/src/main/java/hex/genmodel/algos/deepwater/DeepwaterMojoModel.java
h2o-genmodel/src/main/java/hex/genmodel/easy/EasyPredictModelWrapper.java
h2o-py/h2o/estimators/deepwater.py

* Fix exception handling for DeepWater - let clients know about exceptions.
* Abort training when the model is unstable (predicts NaN), point to TN-4
* Add a flag for unstable models, and disallow MOJO creation to avoid misuse
* Print out more information (# input neurons, cardinality of top factor columns)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/h2oai/h2o-3/353)

Multiple improvements for Deep Water

---

h2o-core/src/main/java/water/fvec/Chunk.java
h2o-core/src/main/java/water/fvec/Frame.java
h2o-core/src/main/java/water/fvec/Vec.java
h2o-core/src/main/java/water/util/PrettyPrint.java
h2o-core/src/test/java/water/fvec/NewChunkTest.java

Some renamings: checkCompatible was kind of awkwards
Added a method for formatting an UUID (using an existing one)
Added a uuid setter in Chunk and Vec
In Chunk, improved the reaction to bad typing.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/h2oai/h2o-3/355)

Renamed a couple of methods; added UUID functionality.

---

h2o-algos/src/main/java/hex/deepwater/DeepWaterParameters.java
h2o-algos/src/main/java/hex/schemas/DeepWaterV3.java
h2o-py/h2o/estimators/deepwater.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/h2oai/h2o-3/356)

Make device_id an array, in preparation for multi-GPU training.

---

h2o-py/tests/testdir_javapredict/pyunit_mojo.py

Also add 1 more step of scoring 1 row, to cancel any 'cold start' variations
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/h2oai/h2o-3/371)

[PUBDEV-3575] clean up files after pyunit_mojo. 

---

h2o-algos/src/main/java/hex/deepwater/DeepWaterModelInfo.java
h2o-algos/src/main/java/hex/deepwater/DeepWaterParameters.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/h2oai/h2o-3/374)

Minor cleanup for auto-detection of network type.

---

h2o-py/demos/H2O_tutorial_breast_cancer_classification.ipynb

Just swapped a URL to point to one of our public S3 buckets instead of a berkeley URL.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/h2oai/h2o-3/377)

Updated data URL in a python demo

---

h2o-r/h2o-package/R/parse.R
h2o-r/tests/testdir_jira/runit_pubdev_3401.R

This pull request is closely related to PR #211 
Adding @ledell to review because of changes in h2o.parseSetup API.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/h2oai/h2o-3/214)

Unit test for PUBDEV-3401 & fixes in R function h2o.parseSetup

---

h2o-r/h2o-package/R/frame.R
h2o-r/tests/testdir_jira/runit_pub_2702_primitive.R

* Update h2o.* primitives to account for na.rm. 
* Also, remove if() clauses in h2o.* primitives as they are not needed since these methods are base primitives for h2o. These wrapper ,i.e. h2o.*, are merely here for completeness and consistency.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/h2oai/h2o-3/370)

PUBDEV-3568: h2o.max returns NaN even when na.rf condition is set to TRUE

---

h2o-core/src/main/java/water/rapids/ast/prims/mungers/AstDdply.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/h2oai/h2o-3/381)

Fix leak of a temporary frame in AstDdply

---

h2o-r/h2o-package/R/frame.R
h2o-r/tests/testdir_docexamples/runit_Rdoc_set_time_zone.R
h2o-r/tests/testdir_jira/runit_hex_1841_asdate_datemanipulation.R

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/h2oai/h2o-3/380)

PUBDEV-3546: h2o.year() method does not return year

---

h2o-algos/src/main/java/hex/kmeans/KMeans.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/h2oai/h2o-3/383)

PUBDEV-3585: Optimize logic for finding optimal K for K-Means.

---

h2o-algos/src/main/java/hex/deepwater/DeepWaterModelInfo.java
h2o-genmodel/build.gradle
h2o-genmodel/src/main/java/hex/genmodel/algos/deepwater/DeepwaterMojoReader.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/h2oai/h2o-3/386)

Add exception to MOJO backend instantiation

---

h2o-core/src/main/java/water/api/ParseHandler.java
h2o-py/h2o/frame.py
h2o-py/h2o/utils/typechecks.py
h2o-py/tests/testdir_parser/pyunit_load_sparse.py

(scipy.sparse) to H2O in svmlight format
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/h2oai/h2o-3/361)

[PUBDEV-3564] add functionality to upload sparse matrices 

---

h2o-algos/src/main/java/hex/deepwater/DeepWaterModelInfo.java
h2o-algos/src/main/java/hex/deepwater/DeepWaterParameters.java
h2o-algos/src/test/java/hex/deepwater/DeepWaterAbstractIntegrationTest.java
h2o-algos/src/test/java/hex/deepwater/DeepWaterMXNetIntegrationTest.java
h2o-genmodel/build.gradle
h2o-genmodel/src/main/java/hex/genmodel/algos/deepwater/DeepwaterMojoModel.java
h2o-genmodel/src/main/java/hex/genmodel/algos/deepwater/DeepwaterMojoReader.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/h2oai/h2o-3/387)

Upgrade to DeepWater 1.0.2 API.

---

h2o-py/h2o/frame.py
h2o-py/tests/testdir_jira/pyunit_pubdev_3589.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/h2oai/h2o-3/385)

[PUBDEV-3589] Pasha frame unicode

---

h2o-py/h2o/grid/grid_search.py
h2o-py/tests/testdir_algos/deeplearning/pyunit_iris_grid_deeplearning.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/h2oai/h2o-3/395)

[PUBDEV-3592] fixing h2o.get_grid

---

h2o-core/src/main/java/water/util/TwoDimTable.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/h2oai/h2o-3/396)

Fix PUBDEV-3593 TwoDimTable array entries

---

h2o-py/tests/testdir_algos/deeplearning/pyunit_iris_grid_deeplearning.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/h2oai/h2o-3/397)

[PUBDEV-3592] Fixing test iris_grid_deeplearning, so that it prints correct grid results

---

h2o-docs/src/product/index.rst
h2o-docs/src/product/save-and-load-model.rst

Added a topic describing how to save and load models in Flow, R, and Python. Also added this topic to the User Guide index.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/h2oai/h2o-3/388)

PUBDEV-3586 save and load models

---

h2o-r/h2o-package/R/frame.R
h2o-r/tests/testdir_misc/runit_as.h2o_sparse.R

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/h2oai/h2o-3/376)

PUBDEV-3526: Adds support for sparse matrices in as.h2o() in R

---

h2o-docs/src/product/aws.rst

H2O version 3.10.0.8 introduced Minio S3 support. Added documentation to the EC2/S3 section about connecting to a Minio server.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/h2oai/h2o-3/328)

PUBDEV-3536

---

h2o-py/clean.sh
h2o-py/conda/h2o/meta.yaml
h2o-py/package_upload_steps.txt

…
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/h2oai/h2o-3/400)

Add min pkg versions to the conda recipe; and retrieve package version automatically

---

h2o-algos/src/main/java/hex/glrm/GLRM.java

Remove the log.Info statements that somehow get into master.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/h2oai/h2o-3/405)

PUBDEV-3435: GLRM stall.  Remove log.info statements.

---

h2o-core/src/main/java/hex/Model.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/h2oai/h2o-3/415)

[HEXDEV-652] do not assert that file should be delete, warn instead

---

h2o-py/h2o/frame.py
h2o-py/h2o/h2o.py
h2o-py/tests/testdir_misc/pyunit_as_data_frame.py

@st-pasha @ledell @navdeep-G
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/h2oai/h2o-3/406)

add header option to as_list to control column names being returned

---

h2o-algos/src/test/java/hex/splitframe/ShuffleSplitFrameTest.java
h2o-core/src/main/java/water/fvec/NewChunk.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/h2oai/h2o-3/418)

Fixes incorrect behavior of NewChunk.addUUID - the "chunk-local" version

---

h2o-scala/build.gradle
h2o-scala/src/test/scala/hex/glm/GLM_Test.scala
h2o-scala/src/test/scala/water/TestBase.scala
h2o-scala/src/test/scala/water/TestWithCloud.scala

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/h2oai/h2o-3/365)

Added a scala version of GlmTest - and the required classes

---

h2o-py/tests/pyunit_utils/utilsPY.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/h2oai/h2o-3/409)

os.makedirs() ≻ os.mkdir()

---

h2o-algos/src/test/java/hex/deeplearning/DeepLearningProstateTest.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/h2oai/h2o-3/426)

[🔥] fixing invalid Rapids expression in DeepLearningProstateTest

---

h2o-core/src/main/java/water/H2O.java
h2o-core/src/main/java/water/HeartBeat.java
h2o-core/src/main/java/water/HeartBeatThread.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/h2oai/h2o-3/427)

PUBDEV-3620: Increase the max. number of threads from 255 to 32767.

---

h2o-py/h2o/expr.py
h2o-py/h2o/utils/compatibility.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/h2oai/h2o-3/423)

[🔥] correctly serialize strings with escape chars in python

---

h2o-py/h2o/estimators/estimator_base.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/h2oai/h2o-3/438)

[PUBDEV-3537] fix model.start()

---

h2o-py/h2o/estimators/estimator_base.py
h2o-py/tests/testdir_algos/deeplearning/pyunit_cv_cars_deeplearning_medium.py
h2o-py/tests/testdir_algos/deepwater/pyunit_cv_cars_deepwater.py
h2o-py/tests/testdir_algos/glm/pyunit_glm_seed.py
h2o-py/tests/testdir_algos/naivebayes/pyunit_irisNB_cv.py
h2o-py/tests/testdir_jira/pyunit_pubdev_2118.py
h2o-py/tests/testdir_misc/pyunit_make_metrics.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/h2oai/h2o-3/437)

[PUBDEV-3545] do not allow bogus parameters in model.train() in python

---

h2o-py/h2o/utils/debugging.py

https://0xdata.atlassian.net/browse/PUBDEV-3415
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/h2oai/h2o-3/436)

[PUBDEV-3415] replace deprecated inspect.getargspec in python

---

h2o-py/h2o/expr.py
h2o-py/h2o/frame.py
h2o-py/tests/testdir_misc/pyunit_showtime.py

https://0xdata.atlassian.net/browse/PUBDEV-3626
https://0xdata.atlassian.net/browse/PUBDEV-2291
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/h2oai/h2o-3/432)

⏱ [PUBDEV-3626] [PUBDEV-2291] correctly display time column in python

---

h2o-core/src/main/java/water/api/schemas3/FrameV3.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/h2oai/h2o-3/433)

⏱ [PUBDEV-3627] make sure time columns are always returned with type='time'

---

h2o-py/h2o/model/model_base.py
h2o-r/h2o-package/R/kvstore.R

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/h2oai/h2o-3/446)

[HEXDEV-657] [PUBDEV-3263] Allow to download GLRM / DeepWater mojos from Python and R

---

h2o-core/src/main/java/water/rapids/Rapids.java
h2o-core/src/main/java/water/util/ArrayUtils.java
h2o-core/src/main/java/water/util/CollectionUtils.java
h2o-core/src/main/java/water/util/StringUtils.java
h2o-core/src/test/java/water/rapids/RapidsTest.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/h2oai/h2o-3/431)

[PUBDEV-3623] properly parse string escape sequences in Rapids

---

h2o-core/src/main/java/water/rapids/ast/prims/advmath/AstCorrelation.java
h2o-core/src/main/java/water/util/ArrayUtils.java
h2o-r/h2o-package/R/frame.R
h2o-r/tests/testdir_munging/unop/runit_cor_matrix.R

- Modify correlation matrix: Now omit NA rows when called before calculating sigma. This way we only really need one method to get the covariance.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/h2oai/h2o-3/424)

Modify correlation matrix

---

h2o-core/src/main/java/water/rapids/ast/prims/advmath/AstCorrelation.java
h2o-core/src/main/java/water/util/ArrayUtils.java
h2o-r/h2o-package/R/frame.R
h2o-r/tests/testdir_munging/unop/runit_cor_matrix.R

Reverts h2oai/h2o-3#424
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/h2oai/h2o-3/458)

Revert "Modify correlation matrix"

---

h2o-r/ensemble/h2oEnsemble-package/DESCRIPTION
h2o-r/ensemble/h2oEnsemble-package/NAMESPACE
h2o-r/ensemble/h2oEnsemble-package/man/h2o.ensemble.Rd
h2o-r/ensemble/h2oEnsemble-package/man/h2o.load_ensemble.Rd
h2o-r/ensemble/h2oEnsemble-package/man/h2o.metalearn.Rd
h2o-r/ensemble/h2oEnsemble-package/man/h2o.save_ensemble.Rd
h2o-r/ensemble/h2oEnsemble-package/man/h2o.stack.Rd
h2o-r/ensemble/h2oEnsemble-package/man/h2oEnsemble-package.Rd
h2o-r/ensemble/h2oEnsemble-package/tests/testthat.R

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/h2oai/h2o-3/373)

fix h2oEnsemble check notes, closes PUBDEV-3574

---

h2o-r/h2o-package/R/frame.R

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/h2oai/h2o-3/464)

[HOTFIX] Add in params missing in docstring for h2o.cor and h2o.isax

---

h2o-r/h2o-package/R/frame.R

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/h2oai/h2o-3/444)

PUBDEV-3629: Avoid confusing error message when column name is not found.

---

h2o-r/tests/testdir_munging/runit_isax.R

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/h2oai/h2o-3/465)

Add runit for isax

---

README.md

Added information about citing H2O to the H2O readme in github.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/h2oai/h2o-3/410)

PUBDEV-3346 - Citing H2O

---

h2o-algos/src/main/java/hex/aggregator/AggregatorModel.java
h2o-core/src/main/java/water/util/FrameUtils.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/h2oai/h2o-3/461)

HEXDEV-645: Also shrink the domains of the examplar member frames.

---

h2o-core/src/main/java/water/api/RapidsHandler.java
h2o-core/src/main/java/water/rapids/Env.java
h2o-core/src/main/java/water/rapids/Session.java
h2o-core/src/main/java/water/rapids/ast/prims/assign/AstRm.java
h2o-core/src/main/java/water/rapids/ast/prims/assign/AstTmpAssign.java
h2o-core/src/main/java/water/rapids/ast/prims/mungers/AstRename.java
h2o-core/src/test/java/water/rapids/ast/prims/assign/AstTmpAssignTest.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/h2oai/h2o-3/421)

[PUBDEV-3609] Recognize session-scoped $-ids in Rapids.

---

h2o-core/src/main/java/water/rapids/ast/params/AstNumList.java
h2o-py/h2o/expr.py
h2o-py/h2o/frame.py
h2o-py/h2o/utils/shared_utils.py
h2o-py/tests/testdir_munging/slice/pyunit_frame_slicing2.py
h2o-py/tests/testdir_munging/slice/pyunit_frame_slicing3.py
h2o-py/tests/testdir_munging/slice/pyunit_multi_dim_slicing.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/h2oai/h2o-3/435)

[PUBDEV-3472] [PUBDEV-3473] support negative indices and strides in row selection in python

---

h2o-py/h2o/backend/connection.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/h2oai/h2o-3/470)

Check the version of the requests library, and warn the user if it is out-of-date

---

h2o-algos/src/main/java/hex/aggregator/Aggregator.java
h2o-algos/src/main/java/hex/aggregator/AggregatorModel.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/h2oai/h2o-3/491)

Fix PUBDEV-3682: NPE in Aggregation of tiny frame.

---

h2o-docs/src/front/index.html

Added a link to the Open Tour Dallas Videos on docs.h2o.ai.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/h2oai/h2o-3/494)

Link for H2O Dallas Videos

---

h2o-algos/src/main/java/hex/glrm/GLRM.java
h2o-genmodel/src/main/java/hex/genmodel/algos/glrm/GlrmLoss.java

Pasha:
I removed the repeated memory allocations.  Performance profiling is being conducted as we speak. 
Thanks,
Wendy
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/h2oai/h2o-3/467)

PUBDEV-3560:GRLM efficiency improvement.  

---

h2o-algos/src/main/java/hex/deeplearning/DeepLearningModel.java
h2o-algos/src/main/java/hex/deepwater/DeepWater.java
h2o-algos/src/main/java/hex/deepwater/DeepWaterImageIterator.java
h2o-algos/src/main/java/hex/deepwater/DeepWaterModel.java
h2o-algos/src/main/java/hex/util/LinearAlgebraUtils.java
h2o-algos/src/test/java/hex/DataInfoTestAdapt.java
h2o-algos/src/test/java/hex/deeplearning/DeepLearningTest.java
h2o-algos/src/test/java/hex/deepwater/DeepWaterAbstractIntegrationTest.java
h2o-algos/src/test/java/hex/glm/GLMBasicTestBinomial.java
h2o-algos/src/test/java/hex/glm/GLMBasicTestRegression.java
h2o-algos/testMultiNode.sh
h2o-core/src/main/java/hex/Model.java
h2o-core/src/main/java/hex/ModelBuilder.java
h2o-core/src/main/java/hex/ModelMetricsBinomial.java
h2o-core/src/main/java/hex/ModelMetricsMultinomial.java
h2o-core/src/main/java/water/util/FrameUtils.java
h2o-core/src/test/java/hex/ModelAdaptTest.java
h2o-r/tests/testdir_algos/deeplearning/runit_deeplearning_categorical.R

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/h2oai/h2o-3/482)

Fixes for categorical encoding and Deep Water

---

h2o-hadoop/assemblyjar.gradle

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/h2oai/h2o-3/492)

[PUBDEV-3686] Add persist S3 layer into Hadoop assemblies

---

h2o-core/src/main/java/water/parser/CsvParser.java
h2o-core/src/test/java/water/parser/ParserTest.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/h2oai/h2o-3/505)

PUBDEV-3691: Fixes parser to honor user's column specification

---

h2o-core/src/main/java/water/api/RequestServer.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/h2oai/h2o-3/510)

add svg mime type

---

h2o-py/h2o/model/model_base.py
h2o-py/tests/testdir_misc/pyunit_partial_plots.py
h2o-r/H2O_Load.R

Refer to runit_partial_plots for test of numerical accuracy.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/h2oai/h2o-3/511)

PUBDEV-3634 added partial_plots

---

h2o-algos/src/main/java/hex/glrm/GLRM.java

Tomas:
Add checkMemoryFootPrint for GLRM.  I now feel better to know when we will hit our limit for GLRM since we store the Archetype in 2-D double array.
Thanks,
Wendy
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/h2oai/h2o-3/501)

PUBDEV-3692: add GLRM memory check.  Added checkMemoryFootPrint to GLRM.

---

h2o-r/README.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/h2oai/h2o-3/429)

simplify install string, partially closes PUBDEV-2963

---

h2o-docs/src/front/assets/stylesheets/style.css
h2o-docs/src/front/index.html

- Added a section for Deep Water documentation
- Adjusted CSS in order to fit 5 boxes in the Getting Started section of the page without any line wrapping.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/h2oai/h2o-3/530)

Updates to documentation site

---

h2o-py/h2o/model/model_base.py
h2o-py/tests/testdir_misc/pyunit_model_summary.py

* This PR returns a model summary object (TwoDimTable) in the Python API.
* This will allow a user to manipulate model summaries and get metrics of interest much like what we allow in our R API.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/h2oai/h2o-3/522)

Return model summary instead of just printing to screen

---

h2o-genmodel/src/main/java/hex/genmodel/algos/deepwater/DeepwaterMojoReader.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/h2oai/h2o-3/507)

Fix putting the mean_image_file into the MOJO.

---

h2o-algos/src/main/java/hex/tree/SharedTree.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/h2oai/h2o-3/536)

PUBDEV-3704: No longer complain if score_tree_interval > ntrees.

---

h2o-algos/src/main/java/hex/deeplearning/DeepLearningModel.java
h2o-algos/src/test/java/hex/deeplearning/DeepLearningGradientCheck.java
h2o-algos/src/test/java/hex/deeplearning/DeepLearningProstateTest.java
h2o-algos/src/test/java/hex/tree/gbm/GBMTest.java
h2o-core/src/main/java/hex/ModelBuilder.java
h2o-genmodel/src/main/java/hex/genmodel/utils/DistributionFamily.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/h2oai/h2o-3/535)

Forbid building models with modified_huber distribution

---

h2o-core/src/main/java/water/fvec/Chunk.java
h2o-core/src/main/java/water/nbhm/NonBlockingHashMap.java

Also improved NBHM comment
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/h2oai/h2o-3/542)

Enable setting String values in ChunkStr

---

h2o-r/tests/testdir_munging/unop/runit_mean_axis.R

* This PR adds a proper seed to `runit_mean_axis.R`. Should help runs in CI
* Also, this PR adds print statements where relevant
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/h2oai/h2o-3/539)

Add seed to runit_mean_axis.R 

---

h2o-core/src/main/java/hex/ConfusionMatrix.java
h2o-core/src/main/java/hex/CreateFrame.java
h2o-core/src/main/java/hex/Model.java
h2o-core/src/main/java/hex/ModelMetricsMultinomial.java
h2o-core/src/main/java/water/util/ArrayUtils.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/h2oai/h2o-3/521)

Allow more classes (1000 -> 2^20), but won't show the CM if too many. HEXDEV-658

---

h2o-core/src/main/java/hex/createframe/columns/BinaryColumnCfcm.java
h2o-core/src/main/java/hex/createframe/columns/CategoricalColumnCfcm.java
h2o-core/src/main/java/hex/createframe/columns/IntegerColumnCfcm.java
h2o-core/src/main/java/hex/createframe/columns/RealColumnCfcm.java
h2o-core/src/main/java/hex/createframe/columns/StringColumnCfcm.java
h2o-core/src/main/java/hex/createframe/columns/TimeColumnCfcm.java
h2o-core/src/main/java/hex/createframe/postprocess/MissingInserterCfps.java
h2o-core/src/main/java/hex/createframe/postprocess/ShuffleColumnsCfps.java
h2o-core/src/test/java/hex/CreateFrameTest.java

Java serialization tried to serialized Java ArrayList, but hold objects which did not have default constructor. Hence Java serialization was not able to create a  prototype instance.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/h2oai/h2o-3/547)

[HOTFIX] Missing default ctor.

---

h2o-genmodel/src/main/java/hex/genmodel/GenModel.java
h2o-genmodel/src/main/java/water/genmodel/IGeneratedModel.java

(as discussed with @tomk)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/h2oai/h2o-3/520)

Disabling deprecated functions in GenModel

---

h2o-algos/src/test/java/hex/AAA_PreCloudLock.java
h2o-core/src/test/java/water/AAA_PreCloudLock.java
h2o-core/src/test/java/water/TestUtil.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/h2oai/h2o-3/559)

[BUILD] Fixing PR failures

---

h2o-core/src/test/java/water/rapids/ast/prims/mungers/AstNaOmitTest.java

Added NA OMIT junk test from Nidhi.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/h2oai/h2o-3/533)

Adding na omit junit tests by Nidhi.

---

h2o-core/src/main/java/water/ChunkSplitter.java
h2o-core/src/main/java/water/fvec/CStrChunk.java
h2o-core/src/main/java/water/fvec/NewChunk.java
h2o-core/src/main/java/water/util/UnsafeUtils.java
h2o-core/src/test/java/hex/FrameSplitterTest.java
h2o-core/src/test/java/water/fvec/CStrChunkTest.java

Fix bugs with sparse CStrChunk handling.  Was not tracking which rows had NAs vs Strings on the initial create.  Bug with NewChunk.addStr including the trailing zero.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/h2oai/h2o-3/564)

Cliffc sparsestr

---

h2o-algos/src/main/java/hex/glm/ComputationState.java
h2o-algos/src/main/java/hex/glm/GLM.java
h2o-algos/src/main/java/hex/glm/GLMModel.java
h2o-algos/src/main/java/hex/optimization/OptimizationUtils.java

Couple of GLM fixes addressing issues Nidhi hit when running her AutoML loop (PUBDEV-3761,PUBDEV-3766).

Tomas glm fixes

---

h2o-docs/src/product/data-science/glm.rst

Added links to the parameters section. Fixed bad links in the References section.

GLM Documentation updates

---

h2o-r/tests/testdir_misc/runit_h2oconfig.R

* This PR changes the directory in which this unit tests sends temp files.
* Also, a bit of clean up for the test to keep debugging a bit cleaner.

Update unit test for h2oconfig

---

h2o-r/h2o-DESCRIPTION.template
h2o-r/h2o-package/R/frame.R
h2o-r/h2o-package/R/import.R
h2o-r/tests/testdir_jira/runit_pubdev_2844.R

This will fail in CI due to missing data.table, fix to CI is in #524
rebased to recent master

use data.table fread-fwrite for faster io, closes PUBDEV-2844

---

h2o-core/src/main/java/water/fvec/Chunk.java
h2o-core/src/test/java/water/parser/ParseExceptionTest.java

Fixing comments that went out of sync with the actual code.

Fix JavaDoc in Chunk class

---

h2o-py/h2o/expr.py

* This PR will return type `None` in `summary()` if the column is of type `enum` as described in PUBDEV-3291.

PUBDEV-3291: Summary() doesn't update stats values when asfactor() is applied

---

h2o-docs/src/product/faq.rst

Added an FAQ describing how to start a multi-node H2O cluster on a
SLURM system (in R).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/h2oai/h2o-3/551)

PUBDEV-3676 - FAQ for creating H2O cluster on SLURM system

---

h2o-docs/src/product/howto/MOJO_QuickStart.md
h2o-docs/src/product/pojo-quick-start.rst
h2o-genmodel/src/main/java/overview.html

Added GLM to list of algorithms that are supported for MOJOs.

PUBDEV-3695

---

h2o-r/h2o-DESCRIPTION.template

this is subset of #580, just to have it included in next release

R desc file urls upgrade

---

scripts/validate_r_cmd_check_output.R

@abal5 this needs to be tested by edit in CI config to call this script.
this could be safely merged, as script is called from jenkins scripts, not from h2o

parser for R CMD check output, better handling NOTEs, closes PUBDEV-3302

---

h2o-docs/src/product/data-science/algo-params/alpha.rst
h2o-docs/src/product/data-science/algo-params/beta_epsilon.rst
h2o-docs/src/product/data-science/algo-params/compute_p_values.rst
h2o-docs/src/product/data-science/algo-params/early_stopping.rst
h2o-docs/src/product/data-science/algo-params/gradient_epsilon.rst
h2o-docs/src/product/data-science/algo-params/lambda.rst
h2o-docs/src/product/data-science/algo-params/lambda_min_ratio.rst
h2o-docs/src/product/data-science/algo-params/lambda_search.rst
h2o-docs/src/product/data-science/algo-params/max_active_predictors.rst
h2o-docs/src/product/data-science/algo-params/max_iterations.rst
h2o-docs/src/product/data-science/algo-params/non_negative.rst
h2o-docs/src/product/data-science/algo-params/objective_epsilon.rst
h2o-docs/src/product/data-science/algo-params/tweedie_link_power.rst
h2o-docs/src/product/data-science/algo-params/tweedie_variance_power.rst
h2o-docs/src/product/parameters.rst

Checking in 2nd set of GLM parameters with improved descriptions and examples. Also removed the `seed` option from the first set of parameters.

PUBDEV-3702 - Second set of GLM parameters

---

h2o-algos/src/main/java/hex/tree/DHistogram.java
h2o-algos/src/main/java/hex/tree/DTree.java
h2o-algos/src/main/java/hex/tree/ScoreBuildHistogram.java
h2o-algos/src/main/java/hex/tree/ScoreBuildHistogram2.java
h2o-algos/src/main/java/hex/tree/SharedTree.java
h2o-algos/src/main/java/hex/tree/SharedTreeModel.java
h2o-algos/src/main/java/hex/tree/SharedTreeMojoWriter.java
h2o-algos/src/main/java/hex/tree/TreeJCodeGen.java
h2o-algos/src/main/java/hex/tree/TreeVisitor.java
h2o-algos/src/main/java/hex/tree/drf/DrfMojoWriter.java
h2o-algos/src/main/java/hex/tree/gbm/GBM.java
h2o-algos/src/main/java/hex/tree/gbm/GbmMojoWriter.java
h2o-algos/src/test/java/hex/tree/drf/DRFTest.java
h2o-algos/src/test/java/hex/tree/gbm/GBMTest.java
h2o-core/src/main/java/water/fvec/C8DVolatileChunk.java
h2o-core/src/main/java/water/fvec/Frame.java
h2o-core/src/main/java/water/fvec/RollupStats.java
h2o-core/src/main/java/water/util/IcedBitSet.java
h2o-core/src/main/java/water/util/MathUtils.java
h2o-core/src/test/java/water/util/IcedBitSetTest.java
h2o-genmodel/src/main/java/hex/genmodel/GenModel.java
h2o-genmodel/src/main/java/hex/genmodel/algos/tree/SharedTreeMojoModel.java
h2o-genmodel/src/main/java/hex/genmodel/algos/tree/SharedTreeMojoReader.java
h2o-genmodel/src/main/java/hex/genmodel/algos/tree/SharedTreeNode.java
h2o-genmodel/src/main/java/hex/genmodel/algos/tree/SharedTreeSubgraph.java
h2o-genmodel/src/main/java/hex/genmodel/utils/ByteBufferWrapper.java
h2o-genmodel/src/main/java/hex/genmodel/utils/GenmodelBitSet.java
h2o-r/h2o-package/R/gbm.R
h2o-r/h2o-package/R/randomforest.R
h2o-r/tests/testdir_algos/gbm/runit_GBM_partial_domains.R

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/h2oai/h2o-3/567)

Fix wrong/inconsistent/empty categorical splits PUBDEV-3758

---

h2o-algos/testMultiNode.sh
h2o-core/testMultiNode.sh

Revert "Changed the signal sent to end a cluster from a SIGKILL to a SIGTERM …"

---

h2o-dist/buildinfo.json
h2o-hadoop/h2o-hdp2.5-assembly/build.gradle
h2o-hadoop/h2o-hdp2.5/build.gradle
make-dist.sh
settings.gradle

adding support for HDP 2.5

---

h2o-r/h2o-package/R/communication.R
h2o-r/h2o-package/R/kvstore.R

This reverts commit ef2fac6015a34f0ddf0fb46bc8d23f7201be5389.

Revert "PUBDEV-3799: Use safe GET calls in MOJO/POJO downloads (#606)"

---

h2o-docs/src/product/data-science/algo-params/max_iterations.rst
h2o-docs/src/product/data-science/algo-params/standardize.rst
h2o-docs/src/product/data-science/k-means.rst

Provided more info about K-Means to the main K-Means topic.
Added links to parameters in the Appendix.
Driveby fix: Added K-Means to list of algorithms that can be used with the standardize parameter.

PUBDEV-3257: Start of K-Means parameter updates

---

h2o-3-DESCRIPTION.template
h2o-r/build.gradle
h2o-r/scripts/package_version_check_update.R

renamed branch of https://github.com/h2oai/h2o-3/pull/524
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/h2oai/h2o-3/566)

syncRPackages internals now use R repos to sync pkgs

---

h2o-core/src/main/java/water/MemoryManager.java

Add a check to prevent this particular message from getting output more than once a minute.

HEXDEV-681: OOM messages are spamming the logs preventing debugging.

---

h2o-core/src/main/java/water/fvec/Vec.java
h2o-core/src/main/java/water/udf/ColumnBase.java

Vec.isCompatibleWith is public, so can use it in udf.

---

h2o-docs/src/front/assets/stylesheets/style.css
h2o-docs/src/front/index.html

Added link to Deep Water open source license. The box was too small, though, causing the text on that line to wrap. Adjusted some settings to make it fit on one line.

PUBDEV-3880

---

h2o-core/src/main/java/water/H2O.java
h2o-hadoop/h2o-mapreduce-generic/src/main/java/water/hadoop/h2odriver.java

* Adds the context path as a param to h2odriver
* Adds the context_path to the help command line prompt for both H2O and the driver
Need this for Steam.

[MINOR] New parameter in h2odriver and simple prompt update

---

h2o-core/src/main/java/water/rapids/ast/prims/search/AstMatch.java
h2o-core/src/test/java/water/fvec/TestFrameBuilder.java
h2o-core/src/test/java/water/rapids/ast/prims/search/AstMatchTest.java
h2o-r/demos/rdemo.word2vec.craigslistjobtitles.R

this PR also fixes a bug in TestFrameBuilder

Rapids improvement: AstMatch works on String columns

---

h2o-core/src/main/java/water/init/NodePersistentStorage.java
h2o-core/src/main/java/water/persist/Persist.java
h2o-core/src/main/java/water/persist/PersistManager.java
h2o-docs/src/product/data-sources.rst
h2o-docs/src/product/index.rst
h2o-persist-hdfs/src/main/java/water/persist/PersistHdfs.java

To try with Alluxio FS:
1. Include Alluxio client library to H2O launcher:
```
java -cp alluxio-core-client-1.3.0-jar-with-dependencies.jar:build/h2o.jar water.H2OApp
```
2. Access alluxio URI: `alluxio://localhost:19998/iris.csv`

[PUBDEV-3876] Experimental generic support for HDFS-like filesystems

---

examples/deeplearning/notebooks/deeplearning_ensemble_boston_housing_R.ipynb

A simple demo showing how to stack `Deep Water`, `GBM` and `DRF` regression models using Erin's `h2oEnsemble`

Ensemble demo using GBM, DRF and Deep Water

---

h2o-core/src/main/java/water/rapids/Env.java
h2o-core/src/main/java/water/rapids/ast/prims/string/AstGrep.java
h2o-core/src/test/java/water/rapids/ast/prims/string/AstGrepTest.java
h2o-r/demos/rdemo.word2vec.craigslistjobtitles.R
h2o-r/h2o-package/R/frame.R
h2o-r/tests/testdir_misc/runit_string_grep.R

Implements h2o.grep, use in word2vec demo

h2o.grep, searching string columns for R

---

h2o-web/bower.json

includes fixes for font-rendering when using tls and context paths when using tls and passing mixed case values
fonts https://github.com/h2oai/h2o-flow/pull/26
context path https://github.com/h2oai/h2o-flow/pull/25

update Flow to version 0.5.1

---

h2o-py/h2o/frame.py
h2o-py/tests/testdir_munging/slice/pyunit_frame_slicing3.py

https://0xdata.atlassian.net/browse/PUBDEV-2464

[PUBDEV-2464] fix row slice assignment to a frame in python

---

h2o-algos/src/main/java/hex/tree/CompressedTree.java
h2o-algos/src/main/java/hex/tree/DTree.java
h2o-algos/src/main/java/hex/tree/SharedTreeModel.java
h2o-algos/src/main/java/hex/tree/TreeJCodeGen.java
h2o-algos/src/main/java/hex/tree/drf/DrfMojoWriter.java
h2o-algos/src/main/java/hex/tree/gbm/GbmMojoWriter.java
h2o-algos/src/test/java/hex/tree/drf/DRFTest.java
h2o-algos/src/test/java/hex/tree/gbm/GBMTest.java
h2o-core/src/main/java/hex/Model.java
h2o-core/src/main/java/water/util/IcedBitSet.java
h2o-genmodel/src/main/java/hex/genmodel/GenModel.java
h2o-genmodel/src/main/java/hex/genmodel/algos/tree/SharedTreeMojoModel.java
h2o-genmodel/src/main/java/hex/genmodel/tools/PredictCsv.java
h2o-genmodel/src/main/java/hex/genmodel/utils/GenmodelBitSet.java
h2o-r/tests/testdir_javapredict/runit_DRF_javapredict_30kcat.R

https://0xdata.atlassian.net/browse/PUBDEV-3865?filter=-3

Fix handling of unseen categorical levels PUBDEV-3865

---

h2o-docs/src/product/data-science/algo-params/balance_classes.rst
h2o-docs/src/product/data-science/algo-params/class_sampling_factors.rst
h2o-docs/src/product/data-science/algo-params/fold_assignment.rst
h2o-docs/src/product/data-science/algo-params/fold_column.rst
h2o-docs/src/product/data-science/algo-params/max_after_balance_size.rst
h2o-docs/src/product/data-science/algo-params/max_hit_ratio_k.rst
h2o-docs/src/product/data-science/algo-params/nfolds.rst
h2o-docs/src/product/data-science/algo-params/validation_frame.rst

Added Naïve Bayes to the “Available in” section for several parameters. This had been incorrectly left out.

PUBDEV-3946 - fixes for naive bayes

---

h2o-docs/src/product/data-science/gbm-faq/missing_values.rst

Minor updates/clarifications based on feedback.

PUBDEV-3942 - Overview of Missing Values Handling

---

h2o-docs/src/product/azure.rst

Minor updates to fix typos and hanging phrases.

Azure documentation updates

---

h2o-r/h2o-package/R/frame.R
h2o-r/tests/testdir_munging/slice/runit_indexing.R

* This PR fix's negative indexing in the R API.
* A unit test has also been added to check each type of indexing a user might do.

PUBDEV-3883: Negative indexing for H2OFrame is buggy in R API

---

h2o-docs/src/product/azure.rst

Indicate that this is currently a Beta version.

Minor documentation update for H2O with Azure

---

h2o-py/h2o/backend/__init__.py
h2o-py/h2o/backend/connection.py
h2o-py/h2o/h2o.py
h2o-py/tests/testdir_misc/pyunit_h2oconnectionconf.py
h2o-r/h2o-package/R/classes.R
h2o-r/h2o-package/R/communication.R
h2o-r/h2o-package/R/connection.R

- Py h2o.connect() supports connection parameter
- Encapsulates connection parameters in H2OConnectionConf
- R h2o.init() supports context_path as well

[PUBDEV-3912] Connection configuration object to support steam API

---

h2o-algos/src/main/java/hex/DataInfo.java
h2o-algos/src/main/java/hex/glm/ComputationState.java
h2o-algos/src/main/java/hex/glm/GLMModel.java
h2o-algos/src/main/java/hex/glm/GLMTask.java
h2o-algos/src/test/java/hex/DataInfoTestAdapt.java
h2o-r/tests/testdir_algos/glm/runit_GLM_reg_path.R

Fixes makeGLMModel issue, computation of explained deviance for individual submodels

Tomas pubdev 3966

---

h2o-algos/src/main/java/hex/schemas/KMeansV3.java
h2o-bindings/bin/gen_R.py
h2o-bindings/bin/gen_python.py
h2o-py/h2o/estimators/kmeans.py
h2o-r/h2o-package/R/kmeans.R
h2o-r/tests/testdir_algos/kmeans/runit_kmeans_converge.R
h2o-r/tests/testdir_algos/kmeans/runit_kmeans_emptyclus.R
h2o-r/tests/testdir_algos/kmeans/runit_kmeans_grid_iris_negative.R
h2o-r/tests/testdir_algos/kmeans/runit_kmeans_init_err_cases.R
h2o-r/tests/testdir_algos/kmeans/runit_kmeans_iris_h2o_vs_r.R
h2o-r/tests/testdir_golden/runit_km2_1_golden.R
h2o-r/tests/testdir_golden/runit_km2_2_golden.R
h2o-r/tests/testdir_golden/runit_km2_3_golden.R
h2o-r/tests/testdir_golden/runit_km2_4_golden.R
h2o-r/tests/testdir_hdfs/runit_INTERNAL_HDFS_kmeans_converge_large.R

Reverts h2oai/h2o-3#697
Issue with gradle build

Revert "PUBDEV-3885: fixed bug so user_points parameter could be passed, incl…"

---

h2o-docs/src/product/welcome.rst

Removed or replaced outdated links in the Welcome section of the user guide.

Documentation: Fixing outdated links

---

h2o-core/src/main/java/water/parser/ParseDataset.java

Moreover, the missing error messages where then sent as NULLs to the client, which the client was not handling properly...

[PUBDEV-3965] Fix bugs in ParseSetup where an error message may be gobbled if there are several errors with same message on the line

---

h2o-core/src/main/java/water/udf/fp/FP.java

Seems like it was not compiling under some conditions.

Explicitly specifying the type of None

---

h2o-core/build.gradle
h2o-core/src/main/java/water/api/RequestServer.java
h2o-core/src/test/java/water/api/CustomHttpFilterTest.java

- for easier testing, use Mockito (new dependency) to mock HttpServlet params

expose a way to add custom http logging filters

---

h2o-docs/src/product/data-science/algo-params/k.rst
h2o-docs/src/product/data-science/gbm-faq/missing_values.rst
h2o-docs/src/product/data-science/k-means.rst

Described the steps that K-Means uses when estimating K. Also added a reference to Hartigan’s “Clustering Algorithms” book.

PUBDEV-3986

---

h2o-core/src/main/java/water/rapids/ast/prims/advmath/AstUnique.java
h2o-py/tests/testdir_munging/pyunit_unique.py

[PUBDEV-3980] Preserve type of the column in AstUnique op

---

h2o-docs/src/product/data-science/deep-learning.rst
h2o-docs/src/product/data-science/drf.rst
h2o-docs/src/product/data-science/glm.rst
h2o-docs/src/product/flow.rst

Added links that point to more information about ROC curves.
Driveby fix: Updated the Interpreting a Model section in DRF, GLM, and
Deep Learning to match what appears in the Flow tutorials.

PUBDEV-3992: Documentation - added ROC curve info links

---

h2o-r/h2o-package/R/frame.R

* This PR organizes frame.R into several sections: 
- Private/Internal Functions
- Frame Operations
- Time & Date
- Overload base R methods
- Assignment Operations
- Summarizing Operations
- Overloading of `h2o.*` onto functions
- Casting Operations
- Merging Operations
- *ply methods
-Added proper examples to functions that require them. Most functions have example blocks or are quite straight forward in their description.
* Other changes will come in separate PR's

Update/organize R docs for H2OFrame methods in R API

---

h2o-r/demos/rdemo.word2vec.craigslistjobtitles.R

Changed lenghts to lengths in demo.

Fixed minor typo in craiglistjobtitles demo

---

h2o-web/bower.json
h2o-web/build.gradle
scripts/run.py

This PR updates Flow to remove the duplicate Google Analytics script and fix the broken `headless.coffee` phantomJS test. 
cc @abal5 @justinloyola 
related commits and PRs:
https://github.com/h2oai/h2o-flow/commit/2976e81cba7f8c57f6b2d8802566a62565ad12ed
https://github.com/h2oai/h2o-flow/commit/82e48f3c779120c2e3a1bc45359bcefd4bd50aa9
https://github.com/micahstubbs/drift/pull/124

Update flow remove duplicate Google Analytics script HEXDEV-686

---

h2o-algos/src/main/java/hex/kmeans/KMeans.java
h2o-algos/src/main/java/hex/util/ClusteringUtils.java
h2o-core/src/main/java/hex/ModelMetricsClustering.java
h2o-r/tests/testdir_algos/kmeans/runit_kmeans_scoring.R

- User specified fold now works.
- Cross validated models can now materialize with Get Model call.
- Total sum of squares calculation adjusted to use appropriate number of row for cross validated models.

PUBDEV-4005 AIOOB Exception with fold_column set with kmeans

---

h2o-py/tests/testdir_algos/gbm/pyunit_imbalanced_gbm.py

Set the seed for pyunit_imbalanced_gbm.py to make it pass.

Found seed that will work for pyunit_imbalanced_gbm.py.

---

h2o-assemblies/py2o/build.gradle
h2o-grpc/src/main/java/ai/h2o/api/GrpcExtension.java
h2o-grpc/src/main/java/ai/h2o/api/GrpcUtils.java
h2o-grpc/src/main/java/ai/h2o/api/proto/core/JobService.java
h2o-grpc/src/main/proto/common.proto
h2o-grpc/src/main/proto/job.proto

(avoid accidentally throwing an exception when handling another exception).

Fix minor bugs in handling grpc errors on the server side

---

h2o-docs/src/product/azure.rst

Updates based on feedback received today.

Documentation updates for Azure - Feb 22

---

h2o-algos/src/main/java/hex/api/Word2VecHandler.java
h2o-algos/src/main/java/hex/schemas/Word2VecTransformV3.java
h2o-algos/src/main/java/hex/word2vec/Word2VecModel.java
h2o-algos/src/test/java/hex/word2vec/Word2VecTest.java
h2o-r/demos/rdemo.word2vec.craigslistjobtitles.R
h2o-r/h2o-package/R/w2vutils.R
h2o-r/tests/testdir_algos/word2vec/runit_text8_test_large.R

This PR adds support for "sentence/paragraph vector embedding" by averaging the words of the input sequence.
This can be further extended in the future by weighting using TF-IDF.

word2vec, transform sentences to vectors by averaging the word-vectors

---

h2o-docs/src/product/azure.rst

Adding “Azure” to the H2O Artificial Intelligence for HDInsight subheadings. Updated text with this change where appropriate.

Azure documentation updates for Feb 23

---

h2o-algos/src/test/java/water/ModelSerializationTest.java
h2o-core/src/main/java/water/AutoBuffer.java
h2o-core/src/main/java/water/api/ModelsHandler.java

AutoBuffer mysteriously fails while reading stuff. Added more information to figure out what exactly is going on.

AutoBuffer - better error logging

---

h2o-py/h2o/h2o.py
h2o-r/h2o-package/R/connection.R

Changes in client API for Steam R/Py clients

Pubdev 4059

---

h2o-core/src/main/java/hex/PartialDependence.java
h2o-py/h2o/model/model_base.py
h2o-r/h2o-package/R/models.R

In addition to the mean response per feature value, we want to show the standard deviation as well. This will allow to see if the model's predictions are getting less confident at a certain point

PUBDEV-4038 Add stddev to PDP twodimtable.

---

h2o-docs/src/product/data-munging.rst
h2o-docs/src/product/data-munging/importing-data.rst
h2o-docs/src/product/data-munging/importing-files.rst
h2o-docs/src/product/data-munging/uploading-data.rst

- Added a data manipulation topic describing how to import multiple files using importFolder (R)/import_file (Python).

PUBDEV-3852: Documentation for importing multiple files of the same type

---

h2o-core/src/main/java/water/AutoBuffer.java
h2o-core/src/test/java/water/AutoBufferTest.java

Michal, pls take a look. I believe this reporting will help resolve some mysteries.

Vlad better autobuffer class error reporting

---

h2o-docs/src/product/data-science/gbm.rst

This section is out of date, so removing it. Users can review the Histograms and Binning FAQ for specific information:
http://docs.h2o.ai/h2o/latest-stable/h2o-docs/data-science/gbm-faq/histo
grams_and_binning.html

Documentation: Remove "Binning In GBM" section

---

h2o-py/tests/testdir_algos/pca/pyunit_pubdev_3916_pca_hangs.py
h2o-r/tests/testdir_algos/pca/runit_pubdev_3916_pca_hangs.R

increase time out time from 1 second to 1 min

Increase time out duration for pca_hang in RUNITs and Pyunits.

---

h2o-docs/src/front/index.html

Added word2vec demo to the “Use Case Examples” section

Documentation: Update doc site

---

h2o-py/h2o/estimators/stackedensemble.py

The docstring code example was not correct and produced an error.

PUBDEV-4041: Fixed broken Py docstring for Stacked Ensemble

---

h2o-algos/src/test/java/hex/tree/gbm/GBMTest.java
h2o-core/src/main/java/water/util/Java7.java
h2o-core/src/main/java/water/util/Pair.java
h2o-core/src/main/java/water/util/Triple.java

So we are moving into the bright Future Perfect.

Enriched Pair and Triple classes

---

h2o-core/src/main/java/water/H2O.java
h2o-core/src/main/java/water/H2ONode.java
h2o-core/src/main/java/water/HeartBeatThread.java
h2o-core/src/main/java/water/parser/BufferedString.java
h2o-core/src/main/java/water/parser/Categorical.java
h2o-core/src/main/java/water/parser/CsvParser.java
h2o-core/src/test/java/water/OOMTest.java
h2o-core/src/test/java/water/fvec/CStrChunkTest.java
h2o-core/src/test/java/water/parser/BufferedStringTest.java
h2o-core/src/test/java/water/rapids/ast/prims/timeseries/TimeSeriesTests.java
h2o-persist-s3/src/main/java/water/persist/PersistS3.java

A BufferedString cannot be equal to a java String, since this breaks (super)symmetry.

Fixed equality in BufferedString.

---

h2o-py/h2o/frame.py
h2o-py/tests/testdir_misc/pyunit_factoring.py

Also, frame.asfactor() fixed, so
a) more than one column is factored and the result type set
b) column type checked before passing to the server

Test for factoring operations.

---

h2o-core/src/main/java/water/fvec/CBSChunk.java
h2o-core/src/main/java/water/fvec/ChunkVisitor.java
h2o-core/src/test/java/water/fvec/CBSChunkTest.java
h2o-core/src/test/java/water/fvec/SparseTest.java

Fixed intermittent test issues.

fixed chunk issues

---

h2o-algos/src/main/java/hex/glm/GLM.java
h2o-algos/src/test/java/hex/glm/GLMBasicTestMultinomial.java

PUBDEV-4144 Fixed unexpected link function error in GLM.

---

h2o-docs/src/product/data-science.rst
h2o-docs/src/product/data-science/algo-params/model_id.rst
h2o-docs/src/product/data-science/algo-params/training_frame.rst
h2o-docs/src/product/data-science/word2vec.rst

Initial checkin of wor2vec files for the user guide.

Documentation for Word2vec - WIP

---

h2o-core/src/test/java/water/OOMTest.java
h2o-py/tests/testdir_algos/deeplearning/pyunit_checkpoint_new_category_in_predictorDL.py
scripts/run.py

Blocked OOMTest, for good
run.py reports errors in more details.

OOMTest blocked, run.py better report

---

h2o-algos/src/test/java/hex/glm/GLMTest.java
h2o-core/src/main/java/hex/AUC2.java
h2o-core/src/main/java/water/udf/FoldingColumn.java
h2o-core/src/main/java/water/udf/Fun2Column.java
h2o-core/src/main/java/water/udf/Fun3Column.java
h2o-core/src/main/java/water/udf/FunColumn.java
h2o-core/src/main/java/water/udf/UnfoldingColumn.java
h2o-core/src/main/java/water/udf/fp/Functions.java
h2o-core/src/test/java/water/udf/fp/FunctionsTest.java
h2o-py/tests/testdir_algos/gbm/pyunit_PUBDEV_4090_grid_model_seeds.py
scripts/run.py

Removed two obsolete methods in Functions (using Java7.Objects)
Implemented auc for arbitrary parameterized curves.

Implemented PR_AUC.

---

h2o-web/bower.json

This PR adds: 
+ 🐛  **fix:** error messages & stacktraces from the *h2o-3* backend render in the Flow UI [#134](https://github.com/micahstubbs/drift/pull/134)
+ 🐛  **fix:** model output now renders for custom algos [#136](https://github.com/micahstubbs/drift/pull/136)
+ a new [roomscale](https://support.steampowered.com/kb_article.php?ref=2001-UXCM-4439) scatterplot data visualization ✨   
+ a new top-level Plot menu

update flow to version 0.6.1

---

h2o-docs/src/product/ibm-dsx.rst

Added links to more information for using H2O with R.

PUBDEV-4118: Adding helpful links

---

h2o-py/h2o/frame.py

Need to return an object for data extraction after running frame summary.
R already returns a table that can be accessed field wise

PUBDEV-4123 Python frame summary returns dictionary

---

h2o-core/src/main/java/water/rapids/ast/prims/mungers/AstPivot.java
h2o-core/src/test/java/water/rapids/ast/prims/mungers/AstPivotTest.java

PUBDEV-2535 hotfix

---

h2o-core/src/main/java/water/MemoryManager.java
h2o-core/src/main/java/water/fvec/CStrChunk.java
h2o-core/src/main/java/water/parser/BufferedString.java
h2o-core/src/main/java/water/util/SetOfBytes.java
h2o-core/src/test/java/water/TestUtil.java
h2o-core/src/test/java/water/fvec/CStrChunkTest.java
h2o-core/src/test/java/water/util/SetOfBytesTest.java

Merged with Tomas' updates in CStrChunk.

Restored the branch from approved PR 692

---

h2o-algos/src/main/java/hex/word2vec/Word2VecModel.java
h2o-algos/src/test/java/hex/word2vec/Word2VecTest.java

NA at the end of a Chunk should no longer cause an issue to the word2vec aggregator.

PUBDEV-4162: h2o.transform can produce incorrect aggregated sentence embeddings

---

h2o-core/src/main/java/water/AutoBuffer.java
h2o-core/src/test/java/water/udf/UdfTest.java
h2o-scala/src/main/scala/water/udf/MoreColumns.scala
h2o-scala/src/test/scala/water/udf/ScalaUdfTest.scala

A small tweak in AutoBuffer to allow better debugging.

ScalaUdfTest fixed.

---

h2o-core/src/main/java/water/H2O.java

Fixed incorrect parsing of input parameters.
(cherry picked from commit 83513054c4461379f6f92d1ee696f342c3f9d62a)

[PUBDEV-4171] Check for empty system property

---

h2o-core/src/main/java/water/rapids/ast/prims/mungers/AstPivot.java
h2o-py/h2o/frame.py
h2o-r/h2o-package/R/frame.R

Speeding up pivot command by removing unnecessary mrtasks. Added more explanation in docs for aggregating cases

Pubdev 2535 perf fixes

---

h2o-algos/src/test/java/hex/deepwater/DeepWaterCaffeIntegrationTest.java
h2o-genmodel/src/main/java/hex/genmodel/algos/deepwater/caffe/DeepwaterCaffeBackend.java
h2o-genmodel/src/main/java/hex/genmodel/algos/deepwater/caffe/DeepwaterCaffeModel.java
h2o-genmodel/src/main/java/hex/genmodel/algos/deepwater/caffe/nano/Deepwater.java

h2o-caffe changes to make unit tests work

bring new caffe changes into h2o-3

---

h2o-algos/src/main/java/hex/StackedEnsembleModel.java
h2o-algos/src/main/java/hex/deeplearning/DeepLearningModel.java
h2o-algos/src/main/java/hex/deepwater/DeepWaterModel.java
h2o-algos/src/main/java/hex/glm/GLMModel.java
h2o-algos/src/test/java/hex/glm/GLMTest.java
h2o-core/src/main/java/hex/Model.java
h2o-core/src/main/java/hex/ModelBuilder.java
h2o-core/src/main/java/water/fvec/Chunk.java
h2o-core/src/main/java/water/fvec/Frame.java
h2o-core/src/main/java/water/fvec/Vec.java
h2o-core/src/main/java/water/util/FrameUtils.java
h2o-core/src/test/java/hex/ModelAdaptTest.java

For testability
So that one won't need to look through 400 files
to see who sets column names

Introduced a couple of setters

---

h2o-algos/src/test/java/hex/splitframe/ShuffleSplitFrameTest.java
h2o-core/src/main/java/water/fvec/Frame.java
h2o-core/src/main/java/water/fvec/Vec.java
h2o-core/src/main/java/water/parser/BufferedString.java
h2o-core/src/test/java/hex/FrameSplitterTest.java
h2o-core/src/test/java/water/fvec/EmptyChunkTest.java

WordCountTaskTest did not run in PR, failed in master.

---

h2o-core/src/main/java/water/fvec/CStrChunk.java
h2o-core/src/main/java/water/fvec/NewChunk.java
h2o-core/src/main/java/water/parser/ParseDataset.java
h2o-parsers/h2o-orc-parser/src/main/java/water/parser/orc/OrcParser.java

that's during tests on Master, randomly.
Tracing it was challenging. So added asserts to check that we never pass a negative length.

We have bad length in string buffers initialization,

---

h2o-algos/testSingleNodeOneProc.sh

increase RAM for testSingleNodeOneProc testing

---

h2o-r/h2o-package/R/models.R

Exports the `polygon` function from the `graphics` package in `models.R`.

PUBDEV-4215: Fixes a CRAN note in R package

---

h2o-docs/src/product/data-munging.rst
h2o-docs/src/product/data-munging/groupby.rst

Adding group_by to the Data Manipulation topic.

PUBDEV 4078 - Documentation for group_by

---

h2o-docs/src/product/data-science/algo-params/compute_metrics.rst
h2o-docs/src/product/data-science/algo-params/eps_prob.rst
h2o-docs/src/product/data-science/algo-params/eps_sdev.rst
h2o-docs/src/product/data-science/algo-params/laplace.rst
h2o-docs/src/product/data-science/algo-params/min_prob.rst
h2o-docs/src/product/data-science/algo-params/min_sdev.rst
h2o-docs/src/product/data-science/naive-bayes.rst
h2o-docs/src/product/parameters.rst

Checking in initial descriptions examples

PUBDEV-3944 - Documentation: Naive Bayes parameter descriptions

---

h2o-core/src/main/java/water/rapids/ast/prims/advmath/AstStratifiedSplit.java

Note: right now, the split pulling all row indexes locally and needs to be improved.
This commit little bit improves api to be available for external packages.

[PUBDEV-3995][MINOR] stratified split slightly modified

---

h2o-algos/src/main/java/hex/gram/Gram.java

GLM hot fix, fix simple AIIOB in Cholesky solver.

PUBDEV-4261

---

h2o-docs/src/product/data-munging.rst
h2o-docs/src/product/data-munging/combining-rows.rst
h2o-docs/src/product/data-munging/importing-data.rst
h2o-docs/src/product/data-munging/importing-files.rst
h2o-docs/src/product/data-munging/imputing-data.rst
h2o-docs/src/product/data-munging/replacing-values.rst
h2o-docs/src/product/data-munging/slicing-columns.rst
h2o-docs/src/product/data-munging/slicing-rows.rst
h2o-docs/src/product/data-munging/uploading-data.rst
h2o-docs/src/product/data-science.rst
h2o-docs/src/product/data-science/deep-learning.rst
h2o-docs/src/product/data-science/drf.rst
h2o-docs/src/product/data-science/gbm.rst
h2o-docs/src/product/data-science/glm.rst
h2o-docs/src/product/data-science/glrm.rst
h2o-docs/src/product/data-science/k-means.rst
h2o-docs/src/product/data-science/naive-bayes.rst
h2o-docs/src/product/data-science/pca.rst
h2o-docs/src/product/downloading.rst
h2o-docs/src/product/parameters.rst

- Added a small section about installing H2O R from CRAN.
- Removed ./gradlew syncSmallData from everywhere except in the “Importing Multiple Files” data munging topic.
- All data munging topics use either inputted data or data pulled from s3.

PUBDEV-4201 - continue updates

---

h2o-py/tests/testdir_misc/pyunit_pivot_medium.py

This is a better test. Validates the output of pivot is the same as the pandas version

PUBDEV-2535 test pivot against pandas pivot

---

h2o-dist/buildinfo.json
h2o-hadoop/h2o-hdp2.6-assembly/build.gradle
h2o-hadoop/h2o-hdp2.6/build.gradle
make-dist.sh
settings.gradle

PUBDEV-4251 add support for hdp 2.6

---

h2o-docs/src/product/data-science/algo-params/missing_values_handling.rst
h2o-docs/src/product/data-science/glm.rst

Update the GLM FAQ regarding missing values during training, testing, and scoring.

PUBDEV-4287: Updated GLM FAQ

---

h2o-docs/src/product/starting-h2o.rst

Adding this directly into the branch rather than master. There are too many other documentation changes in master for the 3.10.5.1 release.

PUBDEV-4244: Adding ignore_config flag to rel-ueno release

---

h2o-py/h2o/grid/grid_search.py
h2o-r/h2o-package/R/models.R

Added more details about coef() and coef_norm() to the python and r docs.

PUBDEV-4182: Update documentation for coef() and coef_norm()

---

h2o-py/h2o/frame.py
h2o-py/tests/testdir_munging/unop/pyunit_neg.py

Jira: [PUBDEV-4326](https://0xdata.atlassian.net/browse/PUBDEV-4326)

[PUBDEV-4326] Make sure that logical operators set their results as boolean

---

h2o-algos/src/main/java/hex/glm/GLMModel.java
h2o-algos/src/test/java/hex/glm/GLMTest.java

Non-logit link for quasibinomial family will correctly throw IAE instead of killing the cluster.

PUBDEV-4330 Fixed glm parameter validation.

---

h2o-docs/src/product/faq.rst
h2o-docs/src/product/faq/flow.rst
h2o-docs/src/product/faq/general.rst
h2o-docs/src/product/flow.rst

- Created a new Flow subsection under the FAQs
- Moved a couple of Flow-specific items from the General FAQ to the new Flow FAQ
- Added an FAQ for calling Rapids expression from flow.
Driveby fix: Added a link to H2O Stack Overflow in the Flow > Requesting Help topic.

PUBDEV-2864: Added FAQ for calling Rapids expression from Flow

---

h2o-r/H2O_Load.R
h2o-r/h2o-package/R/parse.R

Added support for parse of schema inputted as vec with format to col.name = col.type. User will not need to supply all col types or in any specific order

PUBDEV-4369

---

h2o-algos/src/main/java/hex/pca/PCA.java
h2o-algos/src/main/java/hex/svd/SVD.java
h2o-algos/src/main/java/hex/util/DimensionReductionUtils.java
h2o-algos/src/test/java/hex/pca/PCATest.java
h2o-core/src/main/java/water/fvec/Frame.java
h2o-py/tests/testdir_algos/pca/pyunit_pubdev_3500_max_k_large.py

Two changes:
1.  PCA now allow user to set _k to be 0 or less to set it to be maximum number of columns.
2. added Pyunit test to make sure it is implemented correctly.

PUBDEV-3500: max cols.  Added Pyunit test.

---

h2o-docs/src/booklets/v2_2015/source/DeepWaterBookletErrata.md

Adding a markdown file for maintaining known issues related to the Deep Water booklet.

PUBDEV-4384: Documentation for new Deep Water Booklet Errata

---

h2o-core/src/main/java/water/parser/BufferedString.java
h2o-core/src/main/java/water/parser/PackedDomains.java
h2o-core/src/main/java/water/parser/ParseDataset.java
h2o-core/src/main/java/water/util/ArrayUtils.java
h2o-core/src/main/java/water/util/StringUtils.java
h2o-core/src/test/java/water/fvec/NewChunkTest.java
h2o-core/src/test/java/water/parser/PackedDomainsTest.java
h2o-core/src/test/java/water/util/ArrayUtilsTest.java
h2o-py/tests/testdir_parser/pyunit_performance_airline_05p_large.py

Doing it in an assert, so if you turn off asserts, no extra calculations.

[PUBDEV-4221] Checking domain structure validity.

---

h2o-docs/src/product/data-science/k-means.rst

Fixed documentation that described the  calculation of “PRE” when estimating k in k-means.

PUBDEV-4401: Documentation fix for K-means

---

h2o-algos/src/main/java/hex/deepwater/DeepWaterDatasetIterator.java
h2o-algos/src/main/java/hex/deepwater/DeepWaterImageIterator.java
h2o-algos/src/main/java/hex/deepwater/DeepWaterParameters.java
h2o-algos/src/main/java/hex/deepwater/DeepWaterTextIterator.java
h2o-algos/src/main/java/hex/schemas/DeepWaterV3.java
h2o-py/h2o/estimators/deepwater.py
h2o-r/h2o-package/R/deepwater.R

* Let the user choose not to cache data in memory for DW model training.
* Don't store the unnecessary mem field for DW KV store data

Reduces DW model training memory footprint

---

h2o-automl/src/main/java/ai/h2o/automl/EckoClient.java
h2o-automl/src/main/java/ai/h2o/automl/Leaderboard.java
h2o-py/tests/testdir_algos/automl/binomial/pyunit_automl_prostate.py
h2o-py/tests/testdir_algos/automl/multinomial/pyunit_automl_iris.py
h2o-py/tests/testdir_algos/automl/regression/pyunit_automl_australia.py
h2o-r/tests/testdir_algos/automl/runit_automl_leaderboard.R

* This PR adds rmse, mae, and rmsle to the leaderboard for regression runs in AutoML and logloss for binomial runs in AutoML

PUBDEV-4413: Add rmse, mae, and rmsle for regression and logloss for binomial in automl leaderboard

---

build.gradle
gradle.properties
gradle/components/visDataServer.gradle
h2o-assemblies/main/build.gradle

To build h2o.jar with VisDataServer:
```
./gradlew -PwithVisDataServer=true -PvisDataServerVersion=3.14.0 :h2o-assemblies:main:projects
```

[PUBDEV-4412] Optional component in H2O main assembly

---

h2o-algos/src/main/java/hex/klime/KLimeModel.java
h2o-algos/src/main/java/hex/schemas/KLimeV3.java
h2o-core/src/main/java/hex/Model.java
h2o-core/src/main/java/hex/schemas/GridSchemaV99.java
h2o-r/tests/testdir_algos/klime/runit_klime_titanic_grid.R

Only "k" parameter is griddable.

PUBDEV-3922: Add support for grid search to k-LIME

---

h2o-docs/src/product/howto/MOJO_QuickStart.md
h2o-docs/src/product/pojo-quick-start.rst
h2o-docs/src/product/productionizing.rst
h2o-genmodel/src/main/java/overview.html

K-Means models can now be exported as MOJOs.

PUBDEV-4095: Document MOJO support for K-Means models

---

h2o-docs/src/product/faq/python.rst

Added an FAQ describing how to use third-party plotting libraries to generate plots outside of Flow.

PUBDEV-4218: FAQ for plotting in Python

---

h2o-r/tests/testdir_misc/runit_save_load_model_all_algos.R

PUBDEV-1578: fixed runit_save_load_model_all_algos.R using h2o.glm now.

PUBDEV-1578: fixed runit_save_load_model_all_algos.R using h2o.glm now.

---

h2o-core/src/main/java/water/fvec/CStrChunk.java
h2o-core/src/main/java/water/fvec/Vec.java
h2o-core/src/main/java/water/rapids/ast/prims/assign/AstAppend.java

* Currently, running the following:
`Python: h2o['col'] = 'string value' `
throws unimplemented. 
* However, this can be fixed by utilizing `CStrChunk` in the `makeCon` implementation.

PUBDEV-4429: Append constant string to frame

---

h2o-py/h2o/__init__.py
h2o-py/h2o/h2o.py
h2o-r/h2o-package/R/connection.R

* This PR adds the ability to open up Flow from the R/Py API's.

PUBDEV-4425: Add h2o.flow() function to open up a Flow window from R and Python

---

h2o-core/src/main/java/water/H2O.java
h2o-core/src/main/java/water/Job.java
h2o-core/src/main/java/water/api/RegisterV3Api.java
h2o-core/src/main/java/water/api/RemoveAllHandler.java
h2o-core/src/main/java/water/api/RemoveHandler.java
h2o-core/src/main/java/water/api/SteamMetricsHandler.java
h2o-core/src/main/java/water/api/schemas3/SteamMetricsV3.java
h2o-core/src/main/java/water/rapids/Rapids.java

Add /3/SteamMetrics REST API for Steam to ask H2O questions.
The first metric added is the number of milliseconds the H2O cluster has been idle.

[PUBDEV-4332]  steam metrics

---

h2o-docs/src/product/data-munging/slicing-rows.rst
h2o-docs/src/product/getting-data-into-h2o.rst

Added documentation indicating that remote files (stored on internet) can be imported into H2O.
Driveby fix: Fixed the formatting of the R code snippet in the slicing rows data munging topic.

PUBDEV-4444: Added Remote File as an acceptable data source

---

h2o-docs/src/product/cloud-integration.rst
h2o-docs/src/product/index.rst
h2o-docs/src/product/welcome.rst

Move Cloud Integration topic from within the Welcome section to its own main section.

PUBDEV-4453: Move Cloud Integration topic outside of Welcome

---

h2o-algos/src/main/java/hex/DataInfo.java
h2o-algos/src/main/java/hex/glm/GLM.java
h2o-algos/src/main/java/hex/glm/GLMModel.java
h2o-algos/src/main/java/hex/glm/GLMTask.java
h2o-algos/src/main/java/hex/glrm/GLRM.java
h2o-algos/src/test/java/hex/glm/GLMTest.java
h2o-py/h2o/frame.py

This contains cherry-picked commits for 3.10.4.8 release

On the way to 3.10.4.8 release

---

h2o-docs/src/product/security.rst

Adding PAM Authentication to the security.rst file.
Driveby fix: Added lines between each Embedded Web Port section.

PUBDEV-4206: Documentation for PAM Authentication

---

h2o-web/bower.json

b5331e0 [PUBDEV-4431] Change flow to use ip:port for identifying node as part of LogHandler
96eb45a Add fold/weights column params to AutoML.

[PUBDEV-4482] Upgrade flow to 0.6.8

---

h2o-web/bower.json

012d18b Added Gen jar download button

[PUBDEV-4483] Upgrade flow to 0.6.9

---

h2o-algos/src/main/java/hex/StackedEnsembleModel.java
h2o-py/tests/testdir_algos/stackedensemble/pyunit_stackedensemble_binary.py
h2o-r/tests/testdir_algos/stackedensemble/runit_stackedensemble_binary.R

* Adds support for saving and loading binary Stacked Ensemble models.

PUBDEV-3970: StackedEnsemble: Support saving & loading binary models

---

h2o-web/bower.json

d11ff92 Use info log as default

[PUBDEV-4498] Update flow to 0.7.0

---

h2o-r/h2o-package/R/automl.R
h2o-r/h2o-package/R/classes.R

https://0xdata.atlassian.net/browse/PUBDEV-4458

PUBDEV-4458: Add early stopping arguments to h2o.automl R API

---

h2o-dist/index.html

This simplifies the steps needed to install the h2o R package on the download pages as documented in [PUBDEV-2963](https://0xdata.atlassian.net/browse/PUBDEV-2963).

PUBDEV-2963: Simplify R download page

---

h2o-r/h2o-package/R/deepwater.R

Was missing in this PR: https://github.com/h2oai/h2o-3/pull/1190

[HOTFIX] PUBDEV-4499: checking in deepwater.R

---

h2o-hadoop/h2o-mapreduce-generic/src/main/java/water/hadoop/h2omapper.java

Repair null arguments in a Hadoop environment.
Add printing of complete stack trace in the case where main encounters an exception.

HEXDEV-693: Repair null arguments in a Hadoop environment.

---

h2o-r/tests/testdir_algos/automl/runit_automl_args.R

- Add proper runits for AutoML R API
- https://0xdata.atlassian.net/browse/PUBDEV-4407

PUBDEV-4407: Add proper runits for AutoML R API

---

h2o-core/src/main/java/water/H2O.java

First of the bugs in the logging.
This one prevented us from obtaining logs using the new `ipport` variant from the local node

[PUBDEV-4495] Fix problem when collecting logs from the local node

---

h2o-core/src/main/java/water/H2O.java

Explicitly check if the `port` and `baseport` is within allowed port range. I accidentally assigned it different number and it failed with error which wasn't that clear. This makes it obvious.

[PUBDEV-4540] Check if port is within allowed range

---

h2o-docs/src/product/security.rst
h2o-hadoop/h2o-mapreduce-generic/src/main/java/water/hadoop/h2odriver.java

Unifies the internal_security and internal_security_conf parameters, fixes the docs

[PUBDEV-4141] SSL parameter unification/doc fix.

---

h2o-bindings/bin/gen_R.py
h2o-r/h2o-package/R/deeplearning.R
h2o-r/h2o-package/R/deepwater.R
h2o-r/h2o-package/R/gbm.R
h2o-r/h2o-package/R/glm.R
h2o-r/h2o-package/R/glrm.R
h2o-r/h2o-package/R/kmeans.R
h2o-r/h2o-package/R/naivebayes.R
h2o-r/h2o-package/R/pca.R
h2o-r/h2o-package/R/randomforest.R
h2o-r/h2o-package/R/stackedensemble.R
h2o-r/h2o-package/R/svd.R
h2o-r/h2o-package/R/word2vec.R
h2o-r/tests/testdir_algos/stackedensemble/runit_stackedensemble_base_models.R

Add support for passing in models in addition to model ids in `h2o.stackedEnsemble()` in R.

PUBDEV-3850: Pass in models directly to base_models in Stacked Ensemble in R

---

h2o-scala/testMultiNode.sh

The test was too was, locking cloud with size <5, later slow node
tried to join, but was rejected leading to test failure.

[HOTFIX] Size of cloud was not passed to test runner.

---

h2o-dist/buildinfo.json
h2o-docs/src/product/howto/FAQ.md
h2o-hadoop/h2o-cdh5.2-assembly/build.gradle
h2o-hadoop/h2o-cdh5.2/build.gradle
h2o-hadoop/h2o-cdh5.3-assembly/build.gradle
h2o-hadoop/h2o-cdh5.3/build.gradle
h2o-hadoop/h2o-hdp2.1-assembly/build.gradle
h2o-hadoop/h2o-hdp2.1/build.gradle
make-dist.sh
settings.gradle

[PUBDEV-4454] Remove CDH5.2, CDH5.3 and HDP2.1 from build chain

---

h2o-core/src/main/java/water/rapids/Env.java
h2o-core/src/main/java/water/rapids/ast/prims/mungers/AstFillNA.java
h2o-core/src/test/java/water/rapids/ast/prims/advmath/AstFillNATest.java
h2o-py/h2o/frame.py
h2o-py/tests/testdir_misc/pyunit_fillna_medium.py
h2o-r/h2o-package/R/frame.R
h2o-r/tests/testdir_munging/runit_fillna.R

PUBDEV-4251 first working version with test
PUBDEV-4251 junit test
PUBDEV-4151 wip bug fixes
PUBDEV-4151 wip bug fixes
PUBDEV-4151 fixed bugs with fillna across chunk boundaries
PUBDEV-4151 R client for fillna
PUBDEV-4151 fillna along rows

[PUBDEV-4151] FillNA, fill missing values sequentially for time series

---

h2o-r/h2o-package/R/frame.R

The documentation example was wrong and caused `R CMD` to fail.
This fixes PR #1062

[PUBDEV-4151][HOTFIX] Fix documentation example.

---

h2o-r/tests/testdir_algos/automl/runit_automl_args.R

[HOTFIX] Dummy fix of runit_automl_args.R

---

h2o-core/src/main/java/water/rapids/Env.java
h2o-core/src/main/java/water/rapids/ast/prims/reducers/AstTopN.java
h2o-core/src/test/java/water/rapids/ast/prims/reducers/AstTopNTest.java
h2o-py/h2o/frame.py
h2o-py/tests/testdir_munging/pyunit_top_bottomN_large.py
h2o-r/h2o-package/R/frame.R
h2o-r/tests/testdir_munging/runit_topN_bottomN_large.R
scripts/gen_numerical_data.py

Added top or bottom N function which basically will allow a user to grab the top or bottom N percent of a numerical column.  The return frame contains the original row indices of the top/bottom N percent values extracted in the second column.  Here is what I have done:
1.  Java side:
a. Implemented the AstTopN.java function to carry out the task of grabbing the N% and 
b. registering this function in env.java.
c. Added junit test to make sure this actually works.
2. Python client:
a.  added topN and bottomN function to frame.py
b. added pyunit test to make sure client code works
3. R client:
a. Added topN and bottomN functions to frame.R
b. added runit test to make sure client code works.
Need Tomas help to figure out how to use ChunkVisitor

[PUBDEV-3624] top bottom n

---

h2o-docs/src/product/automl.rst

- Separated parameters into required and optional.
- Updated the paragraph describing its ease of use.
- Updated the default language for stopping_tolerance.

PUBDEV-4562: Documentation improvements to AutoML section

---

h2o-algos/src/test/java/hex/tree/gbm/GBMTest.java
h2o-extensions/xgboost/src/main/java/hex/tree/xgboost/XGBoost.java
h2o-extensions/xgboost/src/main/java/hex/tree/xgboost/XGBoostModel.java
h2o-extensions/xgboost/src/test/java/hex/tree/xgboost/XGBoostTest.java

1.Add early exception to catch predicted NA's
2.Add check that response doesn't contain NA's
3.Add Junit to check the previous check.
4.Add additional Junit to GBM where response has NA's.
5.Add more testing for XGBoost

XGBoost Enhancements

---

h2o-r/h2o-package/R/frame.R

Added the supported aggregate functions for the group_by function. This information is in the Details section of the group_by function.

PUBDEV-4549: Add supported aggregate functions in R

---

h2o-algos/src/main/java/hex/schemas/GLMV3.java
h2o-py/h2o/estimators/glm.py
h2o-r/h2o-package/R/glm.R

In glm.R, updated the description of the alpha parameter.

PUBDEV-4583: Updated description of alpha param

---

h2o-genmodel/src/main/java/hex/genmodel/tools/PredictCsv.java
h2o-py/tests/pyunit_utils/utilsPY.py
h2o-py/tests/testdir_javapredict/pyunit_pubdex_4531_large.py
h2o-r/tests/runitUtils/shared_javapredict.R
h2o-r/tests/testdir_javapredict/runit_pubdev_4531_large.R

Do not review this one.  Only do the master one.

Rel vajda pubdev 4531

---

h2o-algos/src/main/java/hex/glm/GLM.java
h2o-algos/src/test/java/hex/glm/GLMTest.java

removed outdated adaptToTestFrame call which was causing issue with quasibinomial + cross-validation. Updated test for quasibinomial to run with nfolds.

PUBDEV-4594 GLM fix

---

h2o-parsers/h2o-orc-parser/src/main/java/water/parser/orc/OrcParser.java

Minor fix, stream parse was wrong.

PUBDEV-4416: Fixed streamParse in Orc Parser.

---

h2o-r/h2o-package/R/connection.R

https://0xdata.atlassian.net/browse/PUBDEV-4578

PUBDEV-4578: Fixing h2o R package CRAN NOTE

---

h2o-algos/src/main/java/hex/glm/ComputationState.java
h2o-algos/src/main/java/hex/glm/GLM.java
h2o-algos/src/main/java/hex/glm/GLMModel.java
h2o-algos/src/test/java/hex/glm/GLMTest.java

Objective function used in lambda search (objective adjustment for next lambda) wrongly included intercepts in the penalty calculation.

PUBDEV-4597: Fix objective function in multinomial lambda search

---

h2o-genmodel/src/main/java/hex/genmodel/algos/tree/SharedTreeGraph.java
h2o-genmodel/src/main/java/hex/genmodel/algos/tree/SharedTreeNode.java
h2o-genmodel/src/main/java/hex/genmodel/algos/tree/SharedTreeSubgraph.java

Need this change so that custom tree visualization code can be done using existing SharedTreeSubgraph in h2o-genmodel

PUBDEV-4598 make class public for SharedTreeSubgraph for custom tree viz

---

gradle.properties
gradle/publish.gradle

+ replace nexus machine IP by hostname

[BUILD] Trigger publication into nexus only on internal network

---

.gitignore

see https://docs.gradle.org/current/dsl/org.gradle.api.tasks.wrapper.Wrapper.html

Gradle wrapper should not be in git ignore

---

h2o-docs/src/product/faq/general-troubleshooting.rst
h2o-docs/src/product/faq/sparkling-water.rst

Added two new FAQ entries in the FAQ > Sparkling Water section based on ticket #90879.

PUBDEV-4612: FAQs for Sparkling Water

---

h2o-docs/src/product/faq/general-troubleshooting.rst

Added two new FAQs to the User Guide FAQ > General Troubleshooting topic (based on issue #90879)

PUBDEV-4612: Two new FAQs

---

h2o-r/tests/testdir_algos/stackedensemble/runit_stackedensemble_validation_frame.R

https://0xdata.atlassian.net/browse/PUBDEV-4532

PUBDEV-4532: Added runit for validation_frame in h2o.stackedEnsemble in R

---

h2o-py/tests/testdir_algos/stackedensemble/pyunit_stackedensemble_validation_frame.py

https://0xdata.atlassian.net/browse/PUBDEV-4637

PUBDEV-4637: Added pyunit for validation_frame in Stacked Ensemble in Python

---

Changes.md

Updated changes.md for 3.10.5.3.

PUBDEV-4651-relvajda

---

h2o-core/src/main/java/water/api/FindHandler.java

frame variable should of been updated after the Vec to search on was made into a new Frame

PUBDEV-4650 3/Find api search on column bug fix

---

h2o-parsers/h2o-orc-parser/src/main/java/water/parser/orc/OrcParserProvider.java
h2o-persist-hdfs/src/main/java/water/persist/VecFileSystem.java

VecFileSystem creation was wrong, it was in fact using default local file system.

PUBDEV-4611: fix orc creation of VecFileSystem

---

h2o-genmodel/src/main/java/hex/genmodel/algos/tree/SharedTreeNode.java

Need this to get plotting to work, its a blocker for me

make methods public for SharedTreeNode

---

h2o-algos/src/main/java/hex/glrm/GLRM.java
h2o-algos/src/main/java/hex/pca/PCA.java
h2o-algos/src/main/java/hex/svd/SVD.java
h2o-r/tests/testdir_algos/pca/runit_pubdev_3502_pca_hangs_large_NOPASS.R
h2o-r/tests/testdir_algos/pca/runit_pubdev_3947_pca_slow_NOPASS_large.R

copy over changes to master to release branch.  Already gone through approval process.

Rel vajda pubdev 3947 pca slow

---

h2o-r/h2o-package/R/frame.R

Revert "Added package name in front of the function that we want to call for …"

---

h2o-dist/buildinfo.json

Minor updates: https://0xdata.atlassian.net/browse/PUBDEV-4705

PUBDEV-4705: Fixing booklet names on H2O Download pages

---

h2o-docs/src/product/data-science/algo-params/categorical_encoding.rst
h2o-docs/src/product/data-science/xgboost.rst

- Added FAQs from ticket 90942.
- Added that XGBoost is not supported on Windows.
- Added link to blog post for an example of XGBoost.
- Included FAQ from https://stackoverflow.com/questions/44668298/xgboost-vs-h2o-gradient-boosting

PUBDEV-4674: FAQs and improvements for XGBoost documentation

---

h2o-r/ensemble/README.md
h2o-r/ensemble/h2oEnsemble-package/DESCRIPTION
h2o-r/ensemble/h2oEnsemble-package/NEWS
h2o-r/ensemble/h2oEnsemble-package/R/ensemble.R
h2o-r/ensemble/h2oEnsemble-package/R/wrappers.R
h2o-r/ensemble/h2oEnsemble-package/man/h2o.ensemble.Rd
h2o-r/ensemble/h2oEnsemble-package/man/h2oEnsemble-package.Rd
h2o-r/ensemble/h2oEnsemble-package/tests/testthat/test-ensemble-family.R
h2o-r/ensemble/h2oEnsemble-package/tests/testthat/test-ensemble-wrapper-naiveBayes.R
h2o-r/ensemble/h2oEnsemble-package/tests/testthat/test-stack-wrapper-naiveBayes.R

**h2oEnsemble** v0.2.0, now compatible & taking advantage of all the features in the latest stable **h2o** R package.

PUBDEV-4699: h2oEnsemble v0.2.0

---

h2o-core/src/main/java/water/parser/BufferedString.java
h2o-core/src/main/java/water/parser/Categorical.java
h2o-core/src/main/java/water/parser/CsvParser.java
h2o-core/src/main/java/water/parser/ParseSetup.java
h2o-core/src/main/java/water/util/VecUtils.java
h2o-core/src/test/java/water/fvec/CStrChunkTest.java
h2o-core/src/test/java/water/parser/BufferedStringTest.java
h2o-core/src/test/java/water/parser/ParseSetupTest.java
h2o-parsers/h2o-avro-parser/src/test/java/water/parser/ParseTestAvro.java
h2o-parsers/h2o-parquet-parser/src/test/java/water/parser/parquet/ParseTestParquet.java

This is a gentle clean-up of some code that is working with String<->BufferedString conversions.
The intention is to clarify what the methods do and set proper expectations.
Note: This PR doesn't fix anything and it should also not break any existing functionality.

Clean-up and clarification of code related to processing non-UTF-8 strings

---

h2o-docs/src/product/welcome.rst

Support added for HDP 2.6 and CDH 5.10.

PUBDEV-4758: Document new supported hadoop platforms

---

h2o-core/src/main/java/water/api/RapidsHandler.java

This is just cleaning, non-functional change. After I did [PUBDEV-4748] I forgot to remove unnecessary argument.

[PUBDEV-4764] Remove unnecessary argument left after [PUBDEV-4748]

---

h2o-docs/src/product/howto/MOJO_QuickStart.md
h2o-genmodel/src/main/java/overview.html

In the MOJO docs, added definitions of hot and cold scoring.

PUBDEV-4765: Clarify in MOJO docs meaning of hot and cold scoring

---

h2o-r/ensemble/README.md
h2o-r/ensemble/h2oEnsemble-package/DESCRIPTION
h2o-r/ensemble/h2oEnsemble-package/NEWS
h2o-r/ensemble/h2oEnsemble-package/R/ensemble.R
h2o-r/ensemble/h2oEnsemble-package/man/h2oEnsemble-package.Rd

https://0xdata.atlassian.net/browse/PUBDEV-4772

PUBDEV-4772: Fixing bug in h2oEnsemble::h2o.ensemble() with regression

---

h2o-web/bower.json

b204f35 PUBDEV-4584 & PUBDEV-4701: AutoML

PUBDEV-4584, PUBDEV-4701: Upgrade to Flow 0.7.7

---

h2o-extensions/xgboost/src/main/java/hex/schemas/XGBoostV3.java
h2o-extensions/xgboost/src/main/java/hex/tree/xgboost/XGBoostModel.java
h2o-py/h2o/estimators/xgboost.py
h2o-r/h2o-package/R/xgboost.R

* XGBoost max_depth param should use XGBoost default of 6
* XGBoost eta/learning_rate param should use XGBoost default of 0.3
* XGBoost parameter max_bin should be max_bins and default of 256 not 255

PUBDEV-4734, PUBDEV-4732, PUBDEV-4730

---

h2o-docs/src/product/data-science/xgboost.rst
h2o-docs/src/product/flow.rst

Updated the default values of several parameters in the XGBoost documentation based on recent updates.
Added XGBoost options to the Flow section of the User Guide.

PUBDEV-4781: Update default values in XGBoost documentation

---

h2o-docs/src/product/data-science/algo-params/balance_classes.rst
h2o-docs/src/product/data-science/algo-params/weights_column.rst

Updated the description for weights_column in the User Guide Parameters appendix. This information is in response to ticket 90697.

PUBDEV-4427: Explanation of weights_column in DL

---

h2o-r/h2o-package/R/models.R

https://0xdata.atlassian.net/browse/PUBDEV-4761

PUBDEV-4761: Fixing bug in h2o.coef() in R

---

h2o-extensions/xgboost/src/main/java/hex/tree/xgboost/XGBoostModel.java
h2o-py/h2o/estimators/xgboost.py
h2o-r/h2o-package/R/xgboost.R

Simple change of default value: https://0xdata.atlassian.net/browse/PUBDEV-4794

PUBDEV-4794: XGBoost: Set default value for reg_lambda to 0

---

h2o-extensions/xgboost/src/main/java/hex/schemas/XGBoostV3.java
h2o-extensions/xgboost/src/main/java/hex/tree/xgboost/XGBoostModel.java
h2o-py/h2o/estimators/xgboost.py
h2o-r/h2o-package/R/xgboost.R

XGBoost: Rename num_leaves to max_leaves and set default to 0: https://0xdata.atlassian.net/browse/PUBDEV-4793

PUBDEV-4793: XGBoost: Rename num_leaves to max_leaves and set default to 0

---

h2o-docs/src/product/data-science/xgboost.rst

- Added more information describing XGBoost
- Updated the parameters based on recent changes
- Updated the Limitations section
- Added a second reference. 
Additional updates are still required. Those can be made in a future release.

PUBDEV-4600: Documentation improvements for XGBoost

---

h2o-algos/src/main/java/hex/kmeans/KMeans.java
h2o-algos/src/main/java/hex/pca/PCA.java
h2o-py/tests/testdir_jira/pyunit_pubdev_4702_algo_max_runtime_secs_large.py

Pass max_runtime_secs correctly from PCA.java to SVD.java.

Pubdev 4702 maxruntime tests

---

h2o-py/tests/testdir_algos/pca/pyunit_pubdev_3500_max_k_large.py

Shortened pyunit_pubdev_3500_max_k_large.py test

Shortened test.

---

h2o-algos/src/main/java/hex/deeplearning/DeepLearning.java
h2o-algos/src/main/java/hex/glrm/GLRM.java
h2o-algos/src/main/java/hex/kmeans/KMeans.java
h2o-algos/src/main/java/hex/pca/PCA.java
h2o-algos/src/main/java/hex/svd/SVD.java
h2o-algos/src/main/java/hex/word2vec/Word2Vec.java
h2o-py/tests/pyunit_utils/utilsPY.py
h2o-py/tests/testdir_jira/pyunit_pubdev_4702_algo_max_runtime_secs_large.py
h2o-py/tests/testdir_jira/pyunit_pubdev_4802_short_max_runtime_secs.py
h2o-r/tests/testdir_jira/runit_pubdev_4702_algo_max_runtime_secs_large.R

Add PR to release branch.  Already approved for master.

Pubdev 4802 rel weierstrass

---

h2o-docs/src/product/data-munging.rst
h2o-docs/src/product/data-munging/pivot.rst
h2o-docs/src/product/data-science/pca.rst
h2o-docs/src/product/welcome.rst

Added the pivot data munging function to the user guide.
Driveby fixes: Fixed typo in PCA topic and fixed links to Sparkling Water topics (md -> rst)

PUBDEV-4298: Add pivot to data munging

---

h2o-core/src/main/java/water/ExternalFrameUtils.java
h2o-core/src/test/java/water/ExternalFrameWriterClientTest.java

Spark vectors were not properly written into H2OFrame.

[PUBDEV-4822] Fix external backend utilities

---

h2o-r/tests/testdir_golden/runit_km2_4_golden_large.R
h2o-r/tests/testdir_misc/runit_locate_large.R

When stack limit is reached, new error message is found: 
"C stack usage  7970068 is too close to the limit"
Added this new error check to runit_locate_large.R

Added more error message to check in runit_locate_large.R

---

h2o-core/src/main/java/water/ExternalFrameUtils.java
h2o-core/src/main/java/water/ExternalFrameWriterBackend.java
h2o-core/src/test/java/water/ExternalFrameUtilsTest.java
h2o-core/src/test/java/water/ExternalFrameWriterClientTest.java

The vector indices were not properly updated.
This is PR for rel-weirstrass

[PUBDEV-4822] Fix external cluster utilities (round 2)

---

h2o-r/tests/testdir_golden/runit_km2_4_golden_large_NOPASS.R

Modify test to use tryCatch on statements that are likely to fail instead of the whole test.

Change tryCatch to on one execution and not the whole test.

---

h2o-docs/src/product/welcome.rst

Updated the installation instructions for PySparkling based on the info from the download site.

PUBDEV-4833: Documentation updates for PySparkling Install

---

h2o-core/src/test/java/water/rapids/SortTest.java

Parser has problem parsing zip files for some cases.  Removed these test for now and will fix them.

Remove tests that causes parser error.

---

h2o-algos/src/main/java/hex/StackedEnsembleModel.java
h2o-algos/src/main/java/hex/ensemble/StackedEnsemble.java
h2o-algos/src/test/java/hex/ensemble/StackedEnsembleTest.java
h2o-core/src/main/java/hex/Model.java
h2o-py/tests/testdir_algos/stackedensemble/pyunit_stackedensemble_multinomial.py
h2o-r/tests/testdir_algos/stackedensemble/runit_stackedensemble_multinomial.R

* Minor update to Stacked Ensemble Junit
* Add helper to identify multiclass classifiers to `Model.java`
* Add multiclass stacking

PUBDEV-3960: Add multiclass support to Stacking

---

h2o-automl/src/main/java/ai/h2o/automl/AutoML.java
h2o-automl/src/main/java/ai/h2o/automl/UserFeedback.java

AutoML: In some cases the UserFeedback for the new leader doesn't match the leaderboard 
https://0xdata.atlassian.net/browse/PUBDEV-4839

PUBDEV-4839: AutoML: In some cases the UserFeedback for the new leader doesn't match the leaderboard

---

h2o-core/src/main/java/water/rapids/ast/prims/mungers/AstFlatten.java
h2o-py/h2o/frame.py
h2o-py/tests/testdir_jira/pyunit_pubdev_4723.py

[PUBDEV-4723] - empty rows are not being dropped, fixed NPE when accessing NA value of string vec

[PUBDEV-4723] - empty rows are not being dropped (#1414)

---

h2o-r/tests/runitUtils/shared_javapredict.R
h2o-r/tests/testdir_javapredict/runit_pubdex_4457_predict_pojo_large.R

Tomas has fixed the numerical problem of java adding .0000000001 to a number.
Here is the Runit test derived from Nidhi that used to fail but is passing now.  Please review.

PUBDEV-4457: pojo/h2o predict difference.  Added runit test to check.

---

h2o-py/tests/testdir_jira/pyunit_pubdev_4702_algo_max_runtime_secs_large.py

Minor change to pyunit looking for iterations instead of epochs.

PUBDEV-4702: max_runtime_secs.  Minor change to pyunit test.

---

h2o-docs/src/product/howto/MOJO_QuickStart.md
h2o-docs/src/product/howto/POJO_QuickStart.md
h2o-docs/src/product/productionizing.rst
h2o-genmodel/src/main/java/overview.html

Updated Javadoc, User Guide, and markdown files to include Deep Learning in list of MOJO-supported algorithms.
Driveby fix: Updated syntax in POJO quick start.

PUBDEV-4912: Merging updates into rel-weirstrass

---

h2o-core/src/main/java/water/rapids/ast/prims/assign/AstAppend.java
h2o-py/h2o/__init__.py
h2o-py/h2o/expr.py
h2o-py/h2o/expr_optimizer.py
h2o-py/h2o/h2o.py
h2o-py/tests/testdir_misc/pyunit_expr_optimizations.py
h2o-py/tests/testdir_munging/pyunit_count_temps.py

This is a port of @mmalohlava changes to rel-weierstrass.

[Weierstrass port/MM] [PUBDEV-4873] Python client side AST optimization.

---

h2o-genmodel/src/main/java/hex/genmodel/FolderMojoReaderBackend.java
h2o-genmodel/src/main/java/hex/genmodel/ModelMojoReader.java

* PUBDEV-4937: MOJO Reader is not closing open files
* PUBDEV-4937: MojoReaderBackend was never being closed

[Port to Weierstrass] PUBDEV-4937: MOJO Reader is not closing open files

---

h2o-core/src/main/java/water/rapids/SingleThreadRadixOrder.java
h2o-core/src/main/java/water/rapids/SplitByMSBLocal.java
h2o-core/src/main/java/water/util/MRUtils.java
h2o-core/src/test/java/water/fvec/FrameTestUtil.java
h2o-core/src/test/java/water/util/FrameUtilsTest.java
h2o-py/h2o/frame.py
h2o-py/tests/pyunit_utils/utilsPY.py
h2o-py/tests/testdir_munging/pyunit_pubdev_4870_sort_bug.py
h2o-r/tests/testdir_munging/runit_pubdev_4870_sort_bug.R

Three things:
1. Fixed bug in Java backend to properly sort multiple columns;
2. Added Runit/Pyunit tests to sort two columns;
3.  Added client code to enable sorting on real columns.

PUBDEV-4870: Sorting issue with H2O

---

h2o-r/tests/testdir_munging/runit_pubdev_4870_sort_bug.R

Need to shorten the test time for the corresponding Runit, dah!

Reduce test time

---

h2o-bindings/bin/gen_R.py
h2o-core/src/main/java/water/rapids/SingleThreadRadixOrder.java
h2o-core/src/main/java/water/rapids/SplitByMSBLocal.java
h2o-core/src/main/java/water/util/MRUtils.java
h2o-core/src/test/java/water/fvec/FrameTestUtil.java
h2o-core/src/test/java/water/util/FrameUtilsTest.java
h2o-py/h2o/frame.py
h2o-py/tests/pyunit_utils/utilsPY.py
h2o-py/tests/testdir_munging/pyunit_pubdev_4870_sort_bug.py
h2o-py/tests/testdir_parser/pyunit_hexdev_497_import_gzip_airlines_first_header.py
h2o-r/h2o-package/R/deeplearning.R
h2o-r/tests/testdir_algos/gbm/runit_GBMRandomGrid_airlines_large.R
h2o-r/tests/testdir_munging/runit_pubdev_4870_sort_bug.R

Merge my work from master to release branch include fixing the sort bug.

Wendy sort weierstrass

---

docker/Dockerfile
docker/Jenkinsfile-build-docker
docker/Makefile.jenkins
docker/scripts/install_R_version
docker/scripts/install_R_versions
docker/scripts/install_python_versions

Dockerfile with multiple R and Pyhton versions (based on Jeff's work)
Makefile.jenkins which contains targets used by Jenkins jobs to build and execute tests.

Dockerfile with multiple R and Pyhton versions

---

h2o-algos/src/main/java/hex/kmeans/KMeansModel.java
h2o-algos/src/test/java/hex/kmeans/KMeansTest.java
h2o-core/src/main/java/hex/Model.java
h2o-genmodel/src/main/java/hex/genmodel/GenModel.java
h2o-genmodel/src/main/java/hex/genmodel/IClusteringModel.java
h2o-genmodel/src/main/java/hex/genmodel/algos/kmeans/KMeansMojoModel.java
h2o-genmodel/src/main/java/hex/genmodel/easy/EasyPredictModelWrapper.java
h2o-genmodel/src/main/java/hex/genmodel/easy/prediction/ClusteringModelPrediction.java
h2o-genmodel/src/test/java/hex/genmodel/algos/kmeans/KMeansMojoModelTest.java

Goal is to optionally expose cluster distances in k-means POJO/MOJO while maintaining full backwards compatibility.

PUBDEV-4914: Expose distances to cluster centers in k-means POJO & MOJO

---

docker/Makefile.jenkins

New target for python smoke tests

[ITA-8] Added Python smoke target

---

h2o-genmodel/src/main/java/hex/genmodel/GenModel.java
h2o-genmodel/src/main/java/hex/genmodel/algos/deeplearning/ActivationUtils.java
h2o-genmodel/src/main/java/hex/genmodel/easy/EasyPredictModelWrapper.java
h2o-genmodel/src/main/java/hex/genmodel/tools/PredictCsv.java
h2o-py/tests/pyunit_utils/utilsPY.py
h2o-py/tests/testdir_javapredict/pyunit_pubdev_4628_pubdev_4950_deeplearning_mojo_pojo_large.py

Fixed bug to fill array with 0.0 before scoring on each row for categorical columns.

Pubdev 4950 pmojo accuracy check

---

h2o-genmodel/src/main/java/hex/genmodel/GenModel.java
h2o-genmodel/src/main/java/hex/genmodel/algos/deeplearning/ActivationUtils.java
h2o-genmodel/src/main/java/hex/genmodel/easy/EasyPredictModelWrapper.java
h2o-genmodel/src/main/java/hex/genmodel/tools/PredictCsv.java
h2o-py/tests/pyunit_utils/utilsPY.py
h2o-py/tests/testdir_javapredict/pyunit_pubdev_4628_pubdev_4950_deeplearning_mojo_pojo_large.py

Pubdev 4950 rel weierstrass

---

docker/scripts/install_R_versions

glmnet version set to 2.0-2 there are tests which fail on newer versions of this lib

[ITA-14] glmnet version set to 2.0-2

---

docker/Makefile.jenkins

Adds the target which creates test-package-py.zip. This zip contains everything required to execute the python tests

[ITA-12] Target for creating python test package

---

h2o-core/src/main/java/water/Paxos.java

(cherry picked from commit f6c3559c747381bee3753ecc69d387d73aa51146)

[PUBDEV-4964] Don't check md5 for clients

---

h2o-docs/src/product/data-science/algo-params/histogram_type.rst
h2o-docs/src/product/data-science/drf.rst

Updated description for histogram_type in the user guide.

PUBDEV-4946: Clarify histogram_type in docs

---

h2o-hadoop/h2o-mapreduce-generic/src/main/java/water/JettyProxy.java

Fix proxy authorization (we need to pass the actual authenticated username)

---

h2o-genmodel/src/main/java/hex/genmodel/GenModel.java
h2o-genmodel/src/test/java/hex/genmodel/GenModelTest.java

Port to master branch, no review needed

[port:master] PUBDEV-4979: KMeans doesn't properly calculated scaled distance

---

h2o-py/tests/testdir_jira/pyunit_pubdev_4702_algo_max_runtime_secs_large.py

Fixed bug when GLRM return empty epoch list.

---

h2o-genmodel/src/main/java/hex/genmodel/GenModel.java
h2o-genmodel/src/test/java/hex/genmodel/GenModelTest.java

The distance scaling was calculated using integer division.

[HOTFIX] PUBDEV-4979: KMeans doesn't properly calculated scaled distance

---

h2o-r/tests/testdir_golden/runit_km2_4_golden_large.R

PUBDEV-4837: fixed runit_km2_4_golden.R test.  Wrong bracket position. (#1556)

rel-weierstrass-pubdev-4837-golden-test

---

h2o-algos/src/main/java/hex/deeplearning/DeepLearningModel.java
h2o-py/tests/pyunit_utils/utilsPY.py
h2o-py/tests/testdir_javapredict/pyunit_pubdev_4628_pubdev_4950_deeplearning_mojo_pojo_large.py

Fixed bug that assign wrong value to NaN in categorical columns.  Enable the pojo compare to accuracy of 1e-10.

PUBDEV-4962: pojo fix.  

---

Changes.md

Update Changes.md file for 3.14.0.4 release.

PUBDEV-4981-relweierstrass branch: Changes.md file for release

---

Changes.md

Fixed the date of the 3.14.0.4 release.

Change release date in Release Notes

---

h2o-r/tests/testdir_jira/runit_pubdev_4702_algo_max_runtime_secs_large.R

Added na check on statistics and print out warning messages if they are found but not to fail the test.

fix runit_pubdev_4702_algo_max_runtime_secs_large.R

---

h2o-r/tests/testdir_jira/runit_pubdev_4702_algo_max_runtime_secs_large.R

…re found but not to fail the test. (#1605)

Fix maxrun time test in R

---

h2o-core/src/main/java/water/AbstractHTTPD.java
h2o-core/src/main/java/water/JettyHTTPD.java
h2o-hadoop/h2o-mapreduce-generic/src/main/java/water/JettyProxy.java

JettyProxy is now responsible for authorization & handles login form requests
H2O node doesn't receive any requests that were not authenticated by the proxy

HEXDEV-698: Authentication & authorization is fully handled by JettyProxy

---

h2o-core/src/main/java/water/AbstractHTTPD.java
h2o-core/src/main/java/water/JettyHTTPD.java
h2o-hadoop/h2o-mapreduce-generic/src/main/java/water/JettyProxy.java

This reverts commit 33abeb4c27112a491889511d7a00bfe642839037.

[rel-ueno] Revert "Fix proxy authorization (#1598)"

---

Changes.md

Final version here and attached to the jira ticket.

PUBDEV-4981: Release notes for 3.14.0.4

---

h2o-core/src/main/java/water/rapids/ast/prims/reducers/AstAll.java
h2o-core/src/main/java/water/rapids/ast/prims/reducers/AstAny.java
h2o-genmodel/src/main/java/hex/genmodel/utils/ArrayUtils.java
h2o-py/h2o/frame.py
h2o-py/tests/testdir_jira/pyunit_pubdev_4987_any_all.py

Added check to make sure we are deali…ng with boolean columns.  Next added code to count the number of true elements instead of just counting number of non-zeros.
PUBDEV-4987: fix all, any.  Added pyunit test to verify the fix.

PUBDEV-4987: fix any(), all(). 

---

docker/Dockerfile
docker/Jenkinsfile-build-docker
docker/scripts/install_R_version
docker/scripts/install_R_versions

Reformat code
Use any H2O-3 usable nodes with docker to build the image
Install R dependencies inside install_R_version script

[ITA-30] Don't use cache when building the image

---

h2o-docs/src/front/index.html

Links on the doc site now point to the latest SW release.

PUBDEV-4990: Update SW links on doc site

---

CONTRIBUTING.md

Just a few URL fixes on CONTRIBUTING.md.

Fixing broken JIRA links on CONTRIBUTING.md

---

Jenkinsfile
docker/Makefile.jenkins

[ITA-32] PhantomJS jobs.

---

h2o-core/src/main/java/water/Paxos.java
h2o-core/src/test/java/water/ClientJarMD5IgnoreTest.java

(cherry picked from commit c237556a287720f09b76f326c44cb64152711222)

[PUBDEV-4988] Don't check H2O client hash-code ( Fix )

---

Jenkinsfile

- R CMD Check
- R CMD Check as CRAN
- Py Init

[ITA-39] Removed JUnit from jobs

---

Jenkinsfile

Specify hasJUnit only if the arg is false.
Changed filesToArchive for some stages.

[ITA-40] Remove the numToKeep and timeoutUnit args.

---

h2o-docs/src/product/data-munging.rst
h2o-docs/src/product/data-munging/merging-data.rst
h2o-docs/src/product/data-munging/replacing-values.rst
h2o-docs/src/product/data-munging/sortcolumn.rst
h2o-docs/src/product/faq/general-troubleshooting.rst
h2o-py/docs/intro.rst

- Added a topic describing how to use sort/arrange to sort a frame on a column or columns.
- Driveby fixes for issues in other data munging topics (h2o.init in wrong spot, incorrect syntax in replacing-values)
- Driveby fix for link to H2O World
- Fixed typo in troubleshooting FAQ

PUBDEV-4971: Data munging topic for `sort`

---

h2o-docs/src/product/data-science/k-means.rst

- Updated list of model summary statistics that are outputted. This shows total rather than average values.
- Updated its of training metrics that are outputted. This shows total rather than average values.

PUBDEV-5000: Update list of values in K-Means model output

---

scripts/jenkins/groovy/buildTarget.groovy

Fixed the JUnit testResults expression, now it should load test results only from current stage

[ITA-60] Fixed the JUnit testResults expression

---

h2o-docs/src/front/index.html

Added a link to the Driverless AI Webinars on docs.h2o.ai.

PUBDEV-5006: Link to webinars on doc site

---

h2o-py/tests/testdir_apis/Data_Manipulation/pyunit_h2oH2OFrame_day_dayOfWeek_hour_minute_month_second_week_year_moment_mktime_DEP.py

Calculate the diff based on the local timezone.
Added check of the h2o.H2OFrame.moment.

[PUBDEV-5007] Calculate the diff based on the local timezone

---

scripts/jenkins/groovy/buildConfig.groovy
scripts/jenkins/groovy/executeTestStages.groovy
scripts/jenkins/groovy/prepareH2O3.groovy
scripts/jenkins/groovy/setJobProperties.groovy
scripts/jenkins/jenkinsfiles/Jenkinsfile-Master
scripts/jenkins/jenkinsfiles/Jenkinsfile-Nightly
scripts/jenkins/jenkinsfiles/Jenkinsfile-PR
scripts/jenkins/jenkinsfiles/Jenkinsfile-PR-Testing

[ITA-17] Option to rerun only failed stages

---

h2o-py/tests/testdir_apis/Data_Manipulation/pyunit_h2oH2OFrame_kurtosis.py

Increased number of rows to 30 000.

[PUBDEV-5009] Modify the h2oH2OFrame_kurtosis test

---

docker/Jenkinsfile-build-docker
scripts/jenkins/groovy/buildTarget.groovy

[ITA-70] Added the noCache param

[ITA-71] Set correct JAVA_HOME

---

h2o-core/src/main/java/hex/ScoreKeeper.java
h2o-py/tests/testdir_misc/pyunit_pubdev_4697_early_stop_gbm.py

move from master to here for early stop.

PUBDEV-4697: early stop.  Added pyunit test from user example. (#1606)

---

h2o-core/src/main/java/water/fvec/Frame.java
h2o-core/src/main/java/water/rapids/RadixCount.java
h2o-core/src/main/java/water/rapids/ast/prims/mungers/AstMerge.java
h2o-core/src/test/java/water/rapids/RapidsTest.java
h2o-py/h2o/frame.py
h2o-py/tests/pyunit_utils/utilsPY.py
h2o-py/tests/testdir_jira/pyunit_PUBDEV_3567_merge_stall_large.py
h2o-r/h2o-package/R/frame.R
h2o-r/tests/runitUtils/utilsR.R
h2o-r/tests/testdir_jira/runit_PUBDEV_3567_merge_stall_large.R
h2o-r/tests/testdir_misc/runit_mergecat.R
h2o-r/tests/testdir_munging/runit_merge.R
scripts/gen_numerical_data.py

move from master to rel-weierstrass

PUBDEV_3567: merge.  Added pyunit and runit tests.

---

h2o-r/demos/rdemo.chicago.crime.large.R

Add method="hash" to all the h2o.merge calls.

Added method=hash to merge calls.

---

docker/Makefile.jenkins
scripts/jenkins/groovy/buildConfig.groovy
scripts/jenkins/groovy/buildH2O3.groovy
scripts/jenkins/groovy/executeTestStages.groovy
scripts/jenkins/groovy/insideDocker.groovy

[ITA-77] Remove cd from test-package-r target
[ITA-74] Overwrite existing files when unzipping the test-package

[ITA-78] Docker image tag constant specified in buildConfig

---

docker/Dockerfile
docker/Jenkinsfile-build-docker
docker/Makefile.jenkins
h2o-core/src/test/java/water/UnknownHeartbeatTest.java
scripts/jenkins/groovy/buildConfig.groovy
scripts/jenkins/groovy/buildH2O3.groovy
scripts/jenkins/groovy/buildTarget.groovy
scripts/jenkins/groovy/executeTestStages.groovy
scripts/jenkins/groovy/insideDocker.groovy

Create the jenkins user in docker, tests won't pass otherwise

[ITA-31] JUnit

---

h2o-core/src/main/java/water/H2O.java

We need to calculate the node indexes once we have CLOUD set up. 
This fixes the issue where the logs couldn't be obtained from the client node.

[PUBDEV-5002] Fix obtaining the logs from the client node

---

h2o-core/src/main/java/water/H2O.java

(cherry picked from commit 631a74ace371259a1edcbc50c9b80b6e42f49c8e)

[PUBDEV-5002] Fix obtaining the logs from the client node (#1646)

---

h2o-web/bower.json

[PUBDEV-4853] Flow - Project Name

---

scripts/jenkins/groovy/buildTarget.groovy

Post-process the test results xml files and remove the `&#6;` (backspace) strings

[ITA-88] Post-process the test results xml files

---

h2o-py/tests/testdir_misc/pyunit_time_comparisons.py

Wrap the value so we are comparing two Timestamps

[ITA-89] Modify pyunit_time_comparisons

---

h2o-core/src/main/java/water/api/LogsHandler.java

(cherry picked from commit 0d41b1677f6589453aecc4c0eee0375563c2534d)

[PUBDEV-5040] HTTP logs can't be obtained in Flow UI

---

h2o-core/src/main/java/water/util/Log.java
h2o-py/tests/testdir_hdfs/index.list
h2o-py/tests/testdir_hdfs/pyunit_INTERNAL_HADOOP_download_logs.py

As per our Slack communication, reverting the changes done the logging.

[PUBDEV-5037] Fix obtaining logs on hadoop

---

docker/Jenkinsfile-build-docker
scripts/jenkins/groovy/executeTestStages.groovy
scripts/jenkins/jenkinsfiles/Jenkinsfile-PR
scripts/jenkins/jenkinsfiles/Jenkinsfile-PR-Testing

Forgot to enable JUnits on g machines, when the AWS Credentials issue was resolved.

[ITA-85] Build PRs and docker image on mr-0xg* nodes

---

h2o-core/src/main/java/water/fvec/NewChunk.java
h2o-core/src/test/java/water/fvec/FrameTest.java

Please see inline comments for explanation of the change.

PUBDEV-5033: Fix sparse string chunks

---

docker/Makefile.jenkins

[ITA-93] WIP INFO Check with 1G, should fail

[ITA-93] INFO Check with more memory

---

h2o-docs/src/product/data-science/stacked-ensembles.rst

Just updating the Stacked Ensemble user guide to reflect that we support multiclass ensembles now.

PUBDEV-4878: Updated Stacked Ensemble user guide for multiclass

---

h2o-docs/src/product/data-science/stacked-ensembles.rst

- Updating Stacked Ensemble user guide to reflect this change: https://0xdata.atlassian.net/browse/PUBDEV-4824
- Some other minor updates to Stacked Ensemble user guide page.

PUBDEV-4824: Adding docs on feature subsets in Stacked Ensembles

---

scripts/jenkins/jenkinsfiles/Jenkinsfile-Master
scripts/jenkins/jenkinsfiles/Jenkinsfile-Nightly
scripts/jenkins/jenkinsfiles/Jenkinsfile-PR-Testing

[ITA-104] Don't build master and nightly on mr-0xc10 - docker issues
[ITA-104] Enable checkouts on mr-0xc3 - GitHub issues should be resolved now

[ITA] Infrastructure hotfix

---

docker/Makefile.jenkins

[ITA-112]Invoke JUnits using the `./gradlew test`.
[ITA-113] Removed the `build/h2o.jar` from test-package-java

[ITA] Invoke JUnits using the 'gradlew test'. Remove h2o.jar from test-package-java

---

docker/scripts/install_R_version

Explicitly specify the uuid lib although it's already installed

[ITA-121] Add optparse lib to docker image.

---

docker/Makefile.jenkins
scripts/jenkins/groovy/benchmarkStage.groovy
scripts/jenkins/groovy/buildConfig.groovy
scripts/jenkins/groovy/buildH2O3.groovy
scripts/jenkins/groovy/buildTarget.groovy
scripts/jenkins/groovy/defaultStage.groovy
scripts/jenkins/groovy/executeTestStages.groovy
scripts/jenkins/groovy/insideDocker.groovy
scripts/jenkins/groovy/prepareH2O3.groovy
scripts/jenkins/groovy/stageNameToDirName.groovy
scripts/jenkins/jenkinsfiles/Jenkinsfile-Master
scripts/jenkins/jenkinsfiles/Jenkinsfile-Nightly
scripts/jenkins/jenkinsfiles/Jenkinsfile-PR
scripts/jenkins/jenkinsfiles/Jenkinsfile-PR-Testing

Goal of the PR is to create a benchmarking toolset. This toolset should provide a convenient way to invoke custom benchmarking scripts inside docker containers.

[ITA-102] Benchmarking stages

---

h2o-algos/src/main/java/hex/StackedEnsembleModel.java
h2o-algos/src/main/java/hex/ensemble/StackedEnsemble.java
h2o-algos/src/main/java/hex/schemas/StackedEnsembleV99.java
h2o-bindings/bin/gen_R.py
h2o-py/h2o/estimators/estimator_base.py
h2o-py/h2o/estimators/stackedensemble.py
h2o-py/tests/testdir_algos/stackedensemble/pyunit_stackedensemble_nfolds.py
h2o-r/h2o-package/R/stackedensemble.R
h2o-r/tests/testdir_algos/stackedensemble/runit_stackedensemble_nfolds.R

~Work in progress.~  Ready for review.

PUBDEV-3971: Add cross-validation to Stacked Ensemble

---

scripts/jenkins/groovy/executeTestStages.groovy

[ITA-99] For RUnit Small (90 -> 110) and RUnit Small Client Mode (120 -> 140)
[ITA-124] For Py2.7 Demos (15 -> 30)

[ITA-99] Increase timeouts

---

h2o-web/bower.json

[PUBDEV-4719] Flow - Ignored columns in AutoML.

---

h2o-docs/src/product/data-science/stacked-ensembles.rst

Documentation for new Stacked Ensemble args from this ticket: https://0xdata.atlassian.net/browse/PUBDEV-3971

PUBDEV-5085: Adding xval args to Stacked Ensemble user guide

---

h2o-docs/src/product/data-science/stacked-ensembles.rst

Should wait until this PR is merged: https://github.com/h2oai/h2o-3/pull/1761

PUBDEV-5092: Added metalearner_algorithm to Stacked Ensemble user guide

---

h2o-docs/src/product/automl.rst

Added grid search parameters to AutoML section.

PUBDEV-5014 - Grid parameters and hard-coded models in AutoML (WIP)

---

h2o-algos/src/main/java/hex/tree/DHistogram.java
h2o-algos/src/main/java/hex/tree/ScoreBuildHistogram2.java
h2o-py/tests/testdir_algos/gbm/pyunit_pubdev_5005_residual_deviance_gbm.py
h2o-r/tests/testdir_algos/gbm/runit_pubdev_5005_residual_deviance_gbm.R

Added Pyunit and Runit tests to show how to access the mean residual deviance for GBM.

PUBDEV-5005 GBM residual deviance

---

h2o-docs/src/product/productionizing.rst
h2o-genmodel/src/main/java/overview.html

In the User Guide and Javadoc MOJO Quick Starts, added Stacked Ensembles to list of algos that support MOJOs.

PUBDEV-5097: MOJOs supported for Stacked Ensembles

---

h2o-r/h2o-package/R/frame.R
h2o-r/tests/testdir_munging/runit_pubdev_5072_merge_duplicate.R

Need to use the merge method radix:
h2o.merge(h2o.asfactor(test3), h2o.asfactor(test4), by = "NAME", all.x = TRUE, method="radix")
For details checkout the runit test.

PUBDEV-5072: merge duplicate.  

---

h2o-web/bower.json
h2o-web/package.json

[PUBDEV-5077] Increase marked to version 0.3.6
[PUBDEV-5043] Expose nfolds argument for AutoML in Flow
Increase Flow version

[PUBDEV-5077-5043] AutoML args in Flow

---

h2o-web/bower.json

[PUBDEV-5093] Upgrade uglify-js

---

h2o-core/src/main/java/water/network/SecurityUtils.java

Internal SSL files (ssl.properties and the jks key) are created in temp dirs and cleaned up on JVM exit.
Adding also @jakubhava as a reviewer b/c the original bug report was about PySpark.
To repro the original bug:
1) build Spark (with current master h2o-3)
2) `./sparkling-shell --conf "spark.ext.h2o.internal_secure_connections=true"` (or pysparkling)
3)
```
import org.apache.spark.h2o._
val h2o = H2OContext.getOrCreate(spark)
```
3) shutdown shell, repeat step 2 and 3
This should fail with `java.lang.IllegalStateException: A file under the location h2o-internal.jks already exists. Please delete it first.`.
Spark bundled with this h2o-3 version should not complain about this.

Fixes HEXDEV-699 Internal SSL file creation

---

h2o-algos/src/main/java/hex/deeplearning/DeepLearningModel.java
h2o-algos/src/main/java/hex/tree/SharedTreeModel.java
h2o-algos/src/test/java/hex/tree/gbm/GBMTest.java
h2o-core/src/main/java/hex/Model.java

https://0xdata.atlassian.net/browse/PUBDEV-5082

PUBDEV-5082: Disallow MOJOs/POJOs for non-default categorical_encoding

---

h2o-automl/src/main/java/ai/h2o/automl/AutoML.java
h2o-docs/src/product/automl.rst

* Change names of SE models built in AutoML to names that convey what each ensemble actually does/contains.

PUBDEV-5109: Change SE names in AutoML

---

scripts/jenkins/groovy/defaultStage.groovy
scripts/jenkins/groovy/executeTestStages.groovy

[ITA-131] Purge the stage dir in executeTestStages.
[ITA-131] Pass the stage dir in stageConfig.

[ITA-131] Purge the stage dir in executeTestStages

---

h2o-docs/src/booklets/v2_2015/source/SparklingWaterBooklet.tex
h2o-docs/src/booklets/v2_2015/source/sw/sections/deployment.tex

* [PUBDEV-5111] Additional updates to Sparkling Water Booklet
(cherry picked from commit 7aff924672c7c7aa63ce6a4ac0c888d509b6bc2c)

[PUBDEV-5111] Additional updates to Sparkling Water Booklet (#1780)

---

scripts/jenkins/groovy/benchmarkStage.groovy
scripts/jenkins/groovy/buildConfig.groovy
scripts/jenkins/groovy/defaultStage.groovy
scripts/jenkins/groovy/emailContent.groovy
scripts/jenkins/groovy/executeTestStages.groovy
scripts/jenkins/groovy/prepareH2O3.groovy
scripts/jenkins/jenkinsfiles/Jenkinsfile-Master
scripts/jenkins/jenkinsfiles/Jenkinsfile-Nightly
scripts/jenkins/jenkinsfiles/Jenkinsfile-PR
scripts/jenkins/jenkinsfiles/Jenkinsfile-PR-Testing

* [ITA-126] Stash pipeline scripts instead of archiving them
* [ITA-127] Null branch name in nightly builds
* [ITA-128] Increased timeouts
* [ITA-129] NonCPS annotation for emailContent.
* [ITA-126] Stash pipeline scripts instead of archiving them
* [ITA-127] Null branch name in nighlty build
* [ITA-129] Add the NonCPS annotation for emailContent. Explicitly define testResultsAction.
[ITA-129] Removed NonCPS annotation (#1791)
[ITA-128] Increase timeouts (#1792)
[ITA-131] Remove stage dir before stage start. (#1793)
[ITA-131] Purge the stage dir in executeTestStages. Pass the stage dir in stageConfig. (#1796)
[ITA-133] Add the folderName parameter to s3 path for benchmark results (#1798)

[ITA] Jenkins updates from master

---

h2o-core/src/main/java/water/HeartBeat.java
h2o-core/src/main/java/water/Paxos.java

* remove side effect of the check method
(cherry picked from commit 01b8ab7256529c2edc7fce431e8d11ea48c484d8)

[PUBDEV-5117] Improve print of jar mismatch warning (#1789)

---

Changes.md

Updated changes.md for 3.16.0.2 release.

PUBDEV-5132: Release Notes for 3.16.0.2

---

.gitignore
h2o-bindings/build.gradle

(cherry picked from commit 30677a4f4fe264623f18f98c04b97c6e6218b5e3)

[PUBDEV-5139] Get correct python also in h2o-bindings (#1822)

---

h2o-py/conda/h2o/meta.yaml

(cherry picked from commit 938aef0193ec35995a9b97f1d71e1603a017abee)

[PUBDEV-5157] Fix conda release

---

h2o-docs/src/front/index.html

This change is for nightly releases.

Adding link to DAI release notes on the docs.h2o.ai site

---

docker/Jenkinsfile-build-docker
scripts/jenkins/groovy/emailContentHelpers.groovy
scripts/jenkins/groovy/pipelineEmailContent.groovy
scripts/jenkins/groovy/sendEmail.groovy
scripts/jenkins/groovy/setJobProperties.groovy
scripts/jenkins/jenkinsfiles/Jenkinsfile-Master
scripts/jenkins/jenkinsfiles/Jenkinsfile-Nightly
scripts/jenkins/jenkinsfiles/Jenkinsfile-test

Revert "[ITA-100] Per stage commit check for H2O-3 Pipeline (#1816)" (#1821)
[ITA-140] Use Multibranch for nightly builds of H2O-3. (#1829)
[ITA-138] Per stage commit check for H2O-3 Pipeline (#1830)
[ITA-143] Don't use the intermediary tag when building runtime image (#1834)
[ITA-145] Refactoring of pipeline emails creation. (#1843)
[ITA-142] Execute nighlty build for rel- branches once per night (#1847)

[ITA] Jenkins related updates from master

---

scripts/jenkins/groovy/benchmarkStage.groovy
scripts/jenkins/groovy/benchmarksEmailContent.groovy
scripts/jenkins/groovy/buildConfig.groovy
scripts/jenkins/groovy/compareBenchmarksStage.groovy
scripts/jenkins/groovy/emailContentHelpers.groovy
scripts/jenkins/groovy/pipelineEmailContent.groovy

1. Get the latest and previous benchmark results

[ITA-137] Check that benchmark results are inside specified interval.

---

scripts/jenkins/groovy/buildConfig.groovy
scripts/jenkins/groovy/buildH2O3.groovy
scripts/jenkins/groovy/buildSummary.groovy
scripts/jenkins/groovy/executeTestStages.groovy
scripts/jenkins/groovy/prepareH2O3.groovy

[ITA-152] BuildSummary class responsible for collecting stage information.
[ITA-152] Passing relevant information to BuildSummary for each stage.

[ITA-152] Build Summary screen for job/build

---

h2o-core/src/main/java/water/jdbc/SQLManager.java

[PUBDEV JIRA TICKET](https://0xdata.atlassian.net/browse/PUBDEV-4965)

Pubdev 4965: Support netezza jdbc driver

---

CONTRIBUTING.md

Adding some more instruction about how to name branches and PRs for outside contributors.

Added info about branch/PR naming to CONTRIBUTING.md

---

scripts/jenkins/groovy/benchmarkStage.groovy
scripts/jenkins/groovy/benchmarksEmailContent.groovy
scripts/jenkins/groovy/buildConfig.groovy
scripts/jenkins/groovy/buildH2O3.groovy
scripts/jenkins/groovy/buildSummary.groovy
scripts/jenkins/groovy/compareBenchmarksStage.groovy
scripts/jenkins/groovy/emailContentHelpers.groovy
scripts/jenkins/groovy/executeTestStages.groovy
scripts/jenkins/groovy/pipelineEmailContent.groovy
scripts/jenkins/groovy/prepareH2O3.groovy

[ITA-137] Check that benchmark results are inside specified interval, send email notification if not. (#1820)
[ITA-147] Use ls to get exact path to benchmark result csv (#1854)
[ITA-147] Prefix path to benchmarks results with stage dir

[ITA] Update rel-wheeler

---

h2o-r/h2o-package/R/models.R
h2o-r/tests/testdir_jira/runit_pubdev_4897.R

(cherry picked from commit b89a017)

PUBDEV-4897 - PDP use different order of categorical (rel-wheeler)

---

h2o-py/h2o/expr.py
h2o-py/tests/testdir_jira/pyunit_pubdev_5180.py

(cherry picked from commit a7a136d)

PUBDEV-5180 Python 2 timestamp interpreted as two tokens

---

h2o-core/src/main/java/water/H2O.java
h2o-core/src/main/java/water/Paxos.java
h2o-core/src/main/java/water/init/AbstractEmbeddedH2OConfig.java
h2o-hadoop/h2o-mapreduce-generic/src/main/java/water/hadoop/MapperToDriverMessage.java
h2o-hadoop/h2o-mapreduce-generic/src/main/java/water/hadoop/h2odriver.java
h2o-hadoop/h2o-mapreduce-generic/src/main/java/water/hadoop/h2omapper.java
h2o-py/tests/testdir_hdfs/index.list
h2o-py/tests/testdir_hdfs/pyunit_INTERNAL_HDFS_hexdev_700_gbm_reproducibility.py

This change makes sure that the node users will connect to on Hadoop is chosen deterministically.
This change is only targeted to fix release. The stable release might introduce a breaking change in the API.
@mmalohlava Will need a change in SW as well.

HEXDEV-700: Hadoop driver chooses deterministically the node to connect to

---

h2o-docs/src/product/data-science/aggregator.rst

Fixed the User Guide to indicate that categorical columns are supported. Provided info about how exactly Aggregator handles each categorical column.

PUBDEV-5196: Document categorical column support in Aggregator

---

h2o-py/tests/pyunit_utils/utilsPY.py

Wait for test to pass before pushing to master.

changed utilsPY.py to accept new function.

---

h2o-py/tests/pyunit_utils/utilsPY.py
h2o-py/tests/testdir_algos/gbm/pyunit_PUBDEV_4090_grid_model_seeds.py

Exclude last training_rmse in our comparison.

Fix pyunit_PUBDEV_4090_grid_model_seeds.py

---

h2o-py/tests/pyunit_utils/utilsPY.py
h2o-py/tests/testdir_algos/gbm/pyunit_PUBDEV_4090_grid_model_seeds.py
h2o-py/tests/testdir_hdfs/pyunit_INTERNAL_HDFS_hexdev_700_gbm_reproducibility.py

Enable cross-validation when testing for GBM reproducibility.

hex-700-enable-cross-validation

---

h2o-algos/src/main/java/hex/aggregator/Aggregator.java
h2o-algos/src/main/java/hex/aggregator/AggregatorModel.java
h2o-algos/src/main/java/hex/schemas/AggregatorModelV99.java
h2o-algos/src/main/java/hex/schemas/AggregatorV99.java
h2o-algos/src/test/java/hex/util/AggregatorTest.java
h2o-py/h2o/estimators/aggregator.py
h2o-r/h2o-package/R/aggregator.R

Includes:
- Unit test to check the length of mapping and a test to trigger mapping
- Add a unit test to check for unique values of exemplarar in mapping file and the internal vector
- Incorporated review comments
(cherry picked from commit 7cb025ddf240df366056d12434b95e8ff8ff240b)

[PUBDEV-5171] Aggregator to create mapping frame

---

h2o-algos/src/main/java/hex/aggregator/Aggregator.java
h2o-algos/src/main/java/hex/aggregator/AggregatorModel.java
h2o-algos/src/main/java/hex/schemas/AggregatorModelV99.java
h2o-algos/src/main/java/hex/schemas/AggregatorV99.java
h2o-algos/src/test/java/hex/util/AggregatorTest.java
h2o-py/h2o/estimators/aggregator.py
h2o-r/h2o-package/R/aggregator.R

Fix for:  https://0xdata.atlassian.net/browse/PUBDEV-5171

PUBDEV-5171: Aggregator to create mapping frame when flag is set

---

scripts/jenkins/groovy/compareBenchmarksStage.groovy
scripts/jenkins/jenkinsfiles/Jenkinsfile-Nightly
scripts/jenkins/jenkinsfiles/Jenkinsfile-Release

[ITA-182-183-186] Nightly and release pipeline fixes, updated expected benchmark values

[ITA-REL_WHEELER] Nightly and release pipeline fixes, updated expected benchmark values

---

h2o-automl/src/main/java/ai/h2o/automl/AutoML.java

* Disable for now as support for Deep Water is low.

PUBDEV-5210: Disable Deep Water from AutoML

---

h2o-core/src/main/java/water/H2O.java

[PUBDEV-5212] Wrong java check in checkUnsupportedJava

---

h2o-dist/buildinfo.json

- Pull request specifically for rel-wheeler.

PUBDEV-5216: (rel-wheeler) Updated SW README link on the download page

---

h2o-core/src/main/java/water/rapids/ast/prims/string/AstStrDistance.java
h2o-core/src/main/java/water/rapids/ast/prims/string/algorithms/H2OJaroWinklerComparator.java
h2o-core/src/main/java/water/rapids/ast/prims/string/algorithms/LevenshteinDistanceComparator.java
h2o-core/src/test/java/water/rapids/ast/prims/string/algorithms/LevenshteinDistanceComparatorTest.java
h2o-py/tests/testdir_jira/pyunit_pubdev_4593.py

https://0xdata.atlassian.net/browse/PUBDEV-4593
One "integration" test to prove the original case has been fixed and to complement a standard unit test.
Related master branch PR: https://github.com/h2oai/h2o-3/pull/1911

PUBDEV-4593 - Levenstein Distance Normalization Error

---

h2o-r/tests/testdir_algos/gbm/runit_gbm_quasibinomial.R

Added print out to find good and bad machine eps in order to fix the eps value.

Add debug printout of machine eps to find the bad ones.

---

h2o-bindings/bin/gen_python.py
h2o-py/h2o/estimators/estimator_base.py
h2o-py/h2o/estimators/word2vec.py
h2o-py/tests/testdir_jira/pyunit_pubdev_5112.py

(cherry picked from commit 242b97a)

PUBDEV-5112: Word2Vec Python API for Pretrained Model Requires Training Frame (rel-wheeler)

---

scripts/jenkins/groovy/insideDocker.groovy

[ITA-132] Added the --init flag (#1794)

[ITA-132] Added the --init flag

---

h2o-algos/src/main/java/hex/aggregator/AggregatorModel.java

This fixes the issue while creating the mapping frame in the Aggregator

PUBDEV-5220: Populate the mapping frame correctly

---

h2o-core/src/main/java/water/H2O.java
h2o-core/src/main/java/water/Paxos.java
h2o-core/src/main/java/water/UDPClientEvent.java
h2o-core/src/main/java/water/init/NetworkInit.java

This solution also ensures that joining client does not trigger cloud locking

[PUBDEV-5206] Fix client deadlock issues

---

h2o-core/src/main/java/water/H2O.java
h2o-core/src/main/java/water/Paxos.java
h2o-core/src/main/java/water/UDPClientEvent.java
h2o-core/src/main/java/water/init/NetworkInit.java

(cherry picked from commit bd9c97971f60ea229b1b5b42e11044709dc04c87)

[PUBDEV-5206] Fix client deadlock issues (#1919)

---

h2o-docs/src/product/data-science/xgboost.rst

Added info about XGBoost multicore support with OpenMP.

PUBDEV-5221: XGBoost multicore support

---

h2o-r/tests/testdir_algos/gbm/runit_gbm_quasibinomial.R

Fixed neg.eps to 0.000000000000002 and this seems to fix the problem.

Pubdev 5208 fix quasibinomial test fail

---

ec2/h2o-cluster-launch-instances.py

Signed-off-by: Ubuntu <ubuntu@ip-172-31-29-56.ap-northeast-1.compute.internal>

Fix ec2 instances list

---

h2o-py/h2o/estimators/estimator_base.py

Related to https://github.com/h2oai/h2o-3/pull/1962
Closes https://0xdata.atlassian.net/browse/PUBDEV-5236

Do not raise an error if y argument is given to transform() of an unsupervised model

---

docker/Dockerfile
docker/Jenkinsfile-build-docker
docker/scripts/install_python_versions
docker/scripts/install_xgboost
scripts/jenkins/groovy/buildConfig.groovy

Create virtualenvs for specified Python versions with built XGBoost installed.

[ITA-187-wheeler] Integrate XGBoost to Jenkins docker image (#1934)

---

scripts/jenkins/groovy/buildH2O3.groovy
scripts/jenkins/groovy/defaultStage.groovy
scripts/jenkins/groovy/defineTestStages.groovy
scripts/jenkins/jenkinsfiles/Jenkinsfile
scripts/jenkins/jenkinsfiles/Jenkinsfile-Benchmarks
scripts/jenkins/jenkinsfiles/Jenkinsfile-Hadoop
scripts/jenkins/jenkinsfiles/Jenkinsfile-Nightly

[ITA-201] Remove rerun functionality. Enter stage before entering node (#1974)

[ITA-201] Enter stage before entering docker container

---

h2o-r/tests/testdir_algos/aggregator/runit_aggregator_num_exemplars.R

Explicitly set failure message in runit_aggregator_num_exemplars #1977

[ITA-202-Wheeler] Explicitly set failure message in runit_aggregator_num_exemplars

---

h2o-assemblies/main/build.gradle

The build fails if it encounters a dependency without a known license

Generate dependency report in a CSV format

---

h2o-docs/src/product/data-science/algo-params/interaction_pairs.rst
h2o-docs/src/product/data-science/algo-params/interactions.rst
h2o-docs/src/product/data-science/glm.rst
h2o-docs/src/product/flow.rst
h2o-docs/src/product/parameters.rst
h2o-r/h2o-package/docs/reference/as.vector.H2OFrame.html
h2o-r/h2o-package/docs/reference/h2o-package.html
h2o-r/h2o-package/docs/reference/h2o.abs.html
h2o-r/h2o-package/docs/reference/h2o.automl.html
h2o-r/h2o-package/docs/reference/h2o.glm.html

- Added interaction_pairs to the GLM, Flow, and Parameters topics.
- Updated parameters index to include this new entry.
- Built R so that this would appear in the online help. As a result, some additional HTML topics were also automatically updated.

PUBDEV-5242: Document new interaction_pairs parameter in GLM

---

docker/Dockerfile
docker/scripts/install_R_version
scripts/jenkins/Makefile.jenkins
scripts/jenkins/groovy/defaultStage.groovy
scripts/jenkins/groovy/defineTestStages.groovy
scripts/jenkins/groovy/makeTarget.groovy

Add R packages usethis, hadley/pkgdown.
Add pandoc.
Add Rd files to test-package-r.zip
Add Makefile target and stage. Archive the produced html files

[PUBDEV-5273] Add R docs generation stage to pipeline

---

h2o-algos/src/main/java/hex/glm/GLMModel.java
h2o-algos/src/test/java/hex/glm/GLMBasicTestMultinomial.java

https://0xdata.atlassian.net/browse/PUBDEV-5254

PUBDEV-5254 - GLM Multinomial is not working properly.

---

h2o-core/src/main/java/water/Scope.java
h2o-py/tests/testdir_jira/pyunit_pubdev_5229.py

https://0xdata.atlassian.net/browse/PUBDEV-5229
A frame may potentially have a null key. If there is a Frame with a null key (just a container for vecs), we should no try to track a null key.

PUBDEV-5229 - Null Pointer/ Assertion on export weights

---

h2o-docs/src/product/data-science/algo-params/metalearner_algorithm.rst
h2o-docs/src/product/data-science/algo-params/metalearner_params.rst
h2o-docs/src/product/data-science/stacked-ensembles.rst
h2o-docs/src/product/flow.rst
h2o-docs/src/product/parameters.rst

- Added metalearner_params to list of options in Stacked Ensembles topic
- Created parameter appendix entries for metalearner_algorithm and metalearner_parmas

PUBDEV-5283: Document new metalearner_params option

---

h2o-dist/buildinfo.json

Added a link to H2O-R HTML docs on the download site.

PUBDEV-5311: Doc update for building.json

---

h2o-algos/src/test/java/water/ModelSerializationTest.java
h2o-core/src/main/java/hex/Model.java
h2o-core/src/main/java/water/api/ModelsHandler.java

@ledell I changed the suggested names of the utility functions to import/export. It better matches the corresponding endpoints in the REST API.

PUBDEV-5296: Add import/export utility functions in Java

---

gradle.properties
h2o-core/build.gradle
h2o-core/src/main/java/org/eclipse/jetty/plus/jaas/spi/LdapLoginModule.java
h2o-core/src/main/java/water/AbstractHTTPD.java
h2o-core/src/main/java/water/DelegatingAuthenticator.java
h2o-core/src/main/java/water/JettyHTTPD.java
h2o-core/src/test/java/water/api/CustomHttpFilterTest.java
h2o-docs/src/product/security.rst
h2o-extensions/authsupport/build.gradle
h2o-extensions/authsupport/src/main/java/ai/h2o/org/eclipse/jetty/jaas/spi/LdapLoginModule.java
h2o-hadoop/driverjar.gradle
h2o-hadoop/h2o-mapreduce-generic/build.gradle
h2o-hadoop/h2o-mapreduce-generic/src/main/java/water/JettyProxy.java
h2o-hadoop/h2o-mapreduce-generic/src/main/java/water/ProxyStarter.java

(cherry picked from commit 256d1cc41e03bd4e07ff6fbba55472c3efbf707a)
This PR is for rel-wheeler!

[PUBDEV-4447] Update Jetty to the latest one possible

---

h2o-algos/src/main/java/hex/StackedEnsembleModel.java
h2o-algos/src/main/java/hex/ensemble/Metalearner.java
h2o-algos/src/main/java/hex/ensemble/StackedEnsemble.java
h2o-algos/src/main/java/hex/schemas/StackedEnsembleV99.java
h2o-bindings/bin/gen_R.py
h2o-docs/src/product/data-science/algo-params/metalearner_params.rst
h2o-docs/src/product/data-science/algo-params/seed.rst
h2o-docs/src/product/data-science/stacked-ensembles.rst
h2o-py/h2o/estimators/stackedensemble.py
h2o-py/tests/testdir_algos/stackedensemble/pyunit_stackedensemble_seed.py
h2o-r/h2o-package/R/stackedensemble.R
h2o-r/tests/testdir_algos/stackedensemble/runit_stackedensemble_seed.R

* Add `seed` parameter to SE, which will be passed down to the metalearner algorithm for reproducibility purposes.
* Question: What should we do if a user passes in `seed` as a part of the `metalearner_params argument`? I could always do a check like this:
```
if(metaDeepLearningBuilder._parms._seed == -1) {//Seed is not set in metalearner_params
metaDeepLearningBuilder._parms._seed = _metalearnerSeed;
}
```
Thoughts? This will always honor the a `seed` from `metalearner_params` if provided.

PUBDEV-5224: Add seed parameter to Stacked Ensemble

---

docker/xgb/centos/Dockerfile-centos-gpu
docker/xgb/common/sbin/create_jenkins_user
docker/xgb/ubuntu/Dockerfile-ubuntu-gpu

jenkins user has different UID and GID on GPU and regular machines

[ITA-233] Add second jenkins user to GPU images

---

h2o-extensions/xgboost/src/main/java/hex/tree/xgboost/XGBoost.java
h2o-extensions/xgboost/src/main/java/hex/tree/xgboost/XGBoostUtils.java
h2o-extensions/xgboost/src/main/java/hex/tree/xgboost/rabit/RabitTrackerH2O.java
h2o-extensions/xgboost/src/main/java/hex/tree/xgboost/rabit/util/LinkMap.java
h2o-extensions/xgboost/src/test/java/hex/tree/xgboost/rabit/util/LinkMapTest.java

https://0xdata.atlassian.net/browse/PUBDEV-5301
Fixes 2 bugs in creating the node dependency graph in Rabit tracker used by Rabit workers for communication.
Did not test yet on the exact use case from the JIRA (on it shortly) but seems to be fixing a smaller sized test case which was failing with the same exception.

PUBDEV-5301

---

h2o-docs/src/product/data-science/algo-params/categorical_encoding.rst
h2o-docs/src/product/data-science/xgboost.rst

PUBDEV-5313: doc update for categorical_encoding in xgboost

---

h2o-docs/src/product/data-science/algo-params/categorical_encoding.rst
h2o-docs/src/product/data-science/xgboost.rst

PUBDEV-5313: Update categorical_encoding for xgboost

---

h2o-web/bower.json

Fix metalearner_fold_column.
Add exclude_algos to AutoML.
Moved Run AutoML to the top of the Model menu.

[PUBDEV-5102-5274-5344] Update Flow to 0.7.17

---

h2o-core/src/main/java/water/JettyHTTPD.java

Fix CustomHttpFilterTest (#2074)

[WOL-PUBDEV-5343] Fix CustomHttpFilterTest (#2074)

---

h2o-web/bower.json

[PUBDEV-5102-5274-5344] Update Flow to 0.7.17 (#2080)
Fix metalearner_fold_column.
Add exclude_algos to AutoML.
Moved Run AutoML to the top of the Model menu.

[WOL-PUBDEV-5102-5274-5344] Update Flow to 0.7.17

---

scripts/jenkins/jenkinsfiles/Jenkinsfile-Release

This should also fix the bug related to first build of new branch

[ITA-236] Parameter to control whether latest links should be updated

---

scripts/jenkins/jenkinsfiles/Jenkinsfile-Release

Parameter to control whether latest links should be updated (#2091)
* [ITA-236] Parameter to control whether latest links should be updated or not.
* [ITA-236] Bugfix: env variables should be now set correctly during first build of a branch
* [ITA-236] Do not update any of the stable links

[WOL-ITA-236] Parameter to control whether latest links should be updated

---

h2o-genmodel/src/main/java/hex/genmodel/easy/EasyPredictModelWrapper.java
h2o-genmodel/src/main/java/hex/genmodel/easy/error/VoidErrorConsumer.java
h2o-genmodel/src/test/java/hex/genmodel/easy/EasyPredictModelWrapperTest.java

Same as PR for master, only for rel-wolpert.

PUBDEV-5324 - Make  POJO log error messages for all wrong data types

---

h2o-core/src/main/java/water/H2OConstants.java
h2o-core/src/main/java/water/fvec/NewChunk.java
h2o-core/src/test/java/water/TestUtil.java
h2o-parsers/h2o-parquet-parser/src/main/java/water/parser/parquet/ChunkConverter.java
h2o-parsers/h2o-parquet-parser/src/test/java/water/parser/parquet/ParseTestParquet.java
h2o-parsers/h2o-parquet-parser/testMultiNode.sh

REL-WOLPERT version of 5330 PR

PUBDEV-5330: Parquet Ingest Error when having too many characters/strings

---

scripts/jenkins/groovy/benchmarkStage.groovy
scripts/jenkins/groovy/buildConfig.groovy
scripts/jenkins/groovy/buildH2O3.groovy
scripts/jenkins/groovy/compareBenchmarksStage.groovy
scripts/jenkins/groovy/defaultStage.groovy
scripts/jenkins/groovy/defineTestStages.groovy
scripts/jenkins/groovy/healthChecker.groovy
scripts/jenkins/groovy/insideDocker.groovy
scripts/jenkins/jenkinsfiles/Jenkinsfile
scripts/jenkins/jenkinsfiles/Jenkinsfile-Hadoop
scripts/jenkins/jenkinsfiles/Jenkinsfile-Nightly
scripts/jenkins/jenkinsfiles/Jenkinsfile-Release
scripts/jenkins/jenkinsfiles/Jenkinsfile-XGB

[WOL-ITA-242] Don't pull docker image, if the image is present on host and has expected SHA. (#2108)

[WOL-ITA-242] Don't pull docker image, if the image is present on host and has expected SHA.

---

scripts/jenkins/jenkinsfiles/Jenkinsfile-Release

[ITA] Revert tmp changes to release pipeline. 
[ITA-248] Do not upload stable links by default.

[ITA] Revert tmp changes to release pipeline. Do not upload stable links by default.

---

h2o-core/src/main/java/water/jdbc/SQLManager.java

[PUBDEV-5367 JIRA](https://0xdata.atlassian.net/browse/PUBDEV-5367)

PUBDEV-5367 - SQLManager import breaks on cluster with over 100 nodes
