h2oai/h2o-3

- scripts/jenkins/jenkinsfiles/Jenkinsfile-Release
[ITA-247] Longer timeout for S3 stage. (#2138)
> [ITA-247] Longer timeout for S3 stage.

- h2o-core/src/main/java/water/FailedNodeWatchdogExtension.java
- h2o-core/src/main/java/water/H2O.java
- h2o-core/src/main/java/water/H2ONode.java
Additional log messages for the Watchdog client
> [PUBDEV-5364] More logging regarding the WatchDog client

- h2o-core/src/main/java/water/FailedNodeWatchdogExtension.java
- h2o-core/src/main/java/water/H2O.java
- h2o-core/src/main/java/water/H2ONode.java
(cherry picked from commit 1fd698173096d54f92040829bb9bb3ccf6257129)
> [PUBDEV-5364] More logging regarding the WatchDog client (#2093)

- h2o-algos/src/main/java/hex/glm/GLMModel.java
- h2o-algos/src/main/java/hex/glm/GLMScore.java
- h2o-algos/src/test/java/hex/glm/GLMBasicTestOrdinal.java
- h2o-genmodel/src/main/java/hex/genmodel/algos/glm/GlmOrdinalMojoModel.java
- h2o-py/tests/pyunit_utils/utilsPY.py
- h2o-py/tests/testdir_javapredict/pyunit_pubdev_5008_ordinal_glm_mojo_pojo_large.py
Found problem with mojo/pojo prediction.  The numerical columns are offset by number of categorical columns.  However, it was accessed as from 0 to _num-1.  Tests will pass with all numerical columns but will fail with enums columns.
Changed junit tests to work with random datasets.
> Fixed mojo/pojo tests.  Changed Junit test to work with random datasets.

- h2o-algos/src/main/java/hex/glm/GLMModel.java
- h2o-algos/src/main/java/hex/glm/GLMScore.java
- h2o-algos/src/test/java/hex/glm/GLMBasicTestOrdinal.java
- h2o-genmodel/src/main/java/hex/genmodel/algos/glm/GlmOrdinalMojoModel.java
- h2o-py/tests/pyunit_utils/utilsPY.py
- h2o-py/tests/testdir_javapredict/pyunit_pubdev_5008_ordinal_glm_mojo_pojo_large.py
…ts. (#2142)
Fixed bug in pojo generation.
Incorporate Michalk code review.
> Moved ordinal mojo/pojo fix from master to wolpert

- h2o-algos/src/test/java/hex/glm/GLMBasicTestMultinomial.java
- h2o-genmodel/src/main/java/hex/genmodel/algos/glm/GlmMultinomialMojoModel.java
- h2o-py/tests/testdir_javapredict/pyunit_pubdev_5303_multinomial_glm_mojo_pojo_large.py
- h2o-r/tests/runitUtils/utilsR.R
- h2o-r/tests/testdir_javapredict/runit_PUBDEV_5303_multinomial_glm_mojo_large.R
1. Fixed bug in pojo generation and mojo predict.
2. Added Junit/Runit/Pyunit tests.
> PUBDEV-5303: Fixed multinomial pojo and mojo bug

- h2o-algos/src/test/java/hex/glm/GLMBasicTestBinomial.java
- h2o-py/tests/pyunit_utils/utilsPY.py
- h2o-py/tests/testdir_javapredict/pyunit_pubdev_5355_binomial_glm_mojo_pojo_large.py
- h2o-r/tests/runitUtils/utilsR.R
- h2o-r/tests/testdir_javapredict/runit_PUBDEV_5355_binomial_glm_mojo_large.R
Added pyunit test for binomial.
Added runit test for binomial glm mojo/pojo.
> PUBDEV-5355: Added java mojo/pojo test for binomial glm

- h2o-algos/src/test/java/hex/glm/GLMBasicTestBinomial.java
- h2o-algos/src/test/java/hex/glm/GLMBasicTestMultinomial.java
- h2o-genmodel/src/main/java/hex/genmodel/algos/glm/GlmMultinomialMojoModel.java
- h2o-py/tests/pyunit_utils/utilsPY.py
- h2o-py/tests/testdir_javapredict/pyunit_pubdev_5303_multinomial_glm_mojo_pojo_large.py
- h2o-py/tests/testdir_javapredict/pyunit_pubdev_5355_binomial_glm_mojo_pojo_large.py
- h2o-r/tests/runitUtils/utilsR.R
- h2o-r/tests/testdir_javapredict/runit_PUBDEV_5303_multinomial_glm_mojo_large.R
- h2o-r/tests/testdir_javapredict/runit_PUBDEV_5355_binomial_glm_mojo_large.R
move fixes for glm multinomial/binomial over from master to rel-wolpert
> Rel wolpert fix mojo glm

- h2o-algos/src/main/java/hex/DataInfo.java
- h2o-algos/src/test/java/hex/DataInfoTest.java
- h2o-core/src/main/java/hex/Model.java
- h2o-core/src/main/java/water/fvec/InteractionWrappedVec.java
- h2o-core/src/test/java/water/fvec/InteractionWrappedVecTest.java
- h2o-r/tests/testdir_algos/coxph/runit_coxph_strata_inter.R
This change of DataInfo will only affect CoxPH, GLM will not use the feature.
> [PUBDEV-5398] CoxPH: Use "all factor levels" for certain interactions

- h2o-hadoop/h2o-mapreduce-generic/src/main/java/water/hadoop/h2odriver.java
(cherry picked from commit 4b9dcdbffdf47bd195e87da0368b85ef19e0e2e3)
> [PUBDEV-5403] Fix wrong comment in h2odriver

- h2o-automl/src/main/java/ai/h2o/automl/Leaderboard.java
This fixes: https://0xdata.atlassian.net/browse/PUBDEV-5402
> PUBDEV-5402: Do not cast error metrics as string in automl leaderboard (#2153)

- gradle.properties
- h2o-core/build.gradle
- h2o-core/src/main/java/org/eclipse/jetty/plus/jaas/spi/LdapLoginModule.java
- h2o-core/src/main/java/water/AbstractHTTPD.java
- h2o-core/src/main/java/water/DelegatingAuthenticator.java
- h2o-core/src/main/java/water/JettyHTTPD.java
- h2o-core/src/test/java/water/api/CustomHttpFilterTest.java
- h2o-docs/src/product/security.rst
- h2o-extensions/authsupport/build.gradle
- h2o-extensions/authsupport/src/main/java/ai/h2o/org/eclipse/jetty/jaas/spi/LdapLoginModule.java
- h2o-hadoop/driverjar.gradle
- h2o-hadoop/h2o-mapreduce-generic/build.gradle
- h2o-hadoop/h2o-mapreduce-generic/src/main/java/water/JettyProxy.java
- h2o-hadoop/h2o-mapreduce-generic/src/main/java/water/ProxyStarter.java
> [PUBDEV-4447] Update Jetty to Jetty 9

- scripts/jenkins/groovy/buildConfig.groovy
- scripts/jenkins/groovy/buildH2O3.groovy
- scripts/jenkins/groovy/defaultStage.groovy
- scripts/jenkins/groovy/makeTarget.groovy
- scripts/jenkins/groovy/pipelineUtils.groovy
- scripts/jenkins/groovy/xgbGPUStage.groovy
- scripts/jenkins/jenkinsfiles/Jenkinsfile-Release
* [ITA-253] Remove test-package-*.zip from archived files.
Remove *prediction*.csv from archived files.
Remove h2o-dist and target/*.zip after successful release.
* [ITA-251] Nightly build updates the latest pointer of the master branch in S3.
(cherry picked from commit 448b423ac247f5bc8a93428fa306dfdcbc3d81eb)
> [ITA-253] Reduce size of archived files (#2164)

- scripts/jenkins/groovy/buildConfig.groovy
[ITA-254] Fix detection change in pipelines. (#2173)
(cherry picked from commit 2573f59344032df8b5890a47c1cdadeb1f62aff2)
> [ITA-254] Fix detection change in pipelines.

- h2o-py/h2o/automl/autoh2o.py
Ticket: https://0xdata.atlassian.net/browse/PUBDEV-5411
This is similar to what's been done in R https://github.com/h2oai/h2o-3/commit/f7dd5e0294b9928588dff64325df5f3124a5b5b5.
> [PUBDEV-5411] Remove additional progress bar from AutoML in Python

- h2o-algos/src/test/java/hex/util/AggregatorTest.java
- h2o-core/src/main/java/water/fvec/NewChunk.java
If the original frame in UUID column is NA, populate NA even in the aggregated frame.Donot throw an exception.
> PUBDEV-5384: If the original frame in UUID column is NA, populate NA in aggregated frame

- h2o-docs/src/product/checkpointing-models.rst
- h2o-docs/src/product/data-science/algo-params/checkpoint.rst
- h2o-docs/src/product/index.rst
- Added more information about how checkpointing works include a couple of scenarios.
- Updated list of parameters not allowed with checkpointing in Deep Learning
> PUBDEV-5164: Add more info to checkpoint parameter in docs

- docker/hadoop/cdh/Dockerfile
- docker/hadoop/cdh/conf/core-site.xml
- docker/hadoop/cdh/conf/yarn-site.xml
- docker/hadoop/cdh/scripts/startup/00_hdfs_start
- docker/hadoop/cdh/scripts/startup/30_yarn_start
- docker/hadoop/common/hive-scripts/00_create_airlines.hql
- docker/hadoop/common/sbin/install_hive.sh
- docker/hadoop/common/sbin/test_hive.sh
- docker/hadoop/common/startup/10_hdfs_setup
- docker/hadoop/common/startup/20_hdfs_create_jenkins_home
- docker/hadoop/common/startup/40_hive_start
- docker/hadoop/hdp/Dockerfile
- docker/hadoop/hdp/conf/core-site.xml
- docker/hadoop/hdp/conf/yarn-site.xml
- docker/hadoop/hdp/scripts/startup/00_hdfs_start
- docker/hadoop/hdp/scripts/startup/30_yarn_start
- scripts/jenkins/groovy/hadoopStage.groovy
> [ITA-250] Add Hive 2.2.0 to hadoop images.

- h2o-py/test-requirements.txt
- scripts/jenkins/groovy/buildConfig.groovy
> [ITA-257] Update twine to 1.10.0

- h2o-core/src/main/java/water/H2O.java
- h2o-core/src/main/java/water/Paxos.java
- h2o-core/src/main/java/water/UDPHeartbeat.java
This is the initial draft of the internal documentation of H2O clouding process.
I also did some small code changes when writing this, but we can always remove them from this PR
> [PUBDEV-5217] Small refactoring in clouding and client discovery

- h2o-core/src/main/java/water/H2O.java
- h2o-core/src/main/java/water/Paxos.java
- h2o-core/src/main/java/water/UDPHeartbeat.java
(cherry picked from commit bd9529424b92ee58a36eac270496bd4b6db2c99c)
> [PUBDEV-5217] Small refactoring in clouding and client discovery (#1981)

- h2o-algos/src/test/java/hex/util/AggregatorTest.java
- h2o-core/src/main/java/water/fvec/NewChunk.java
If the original frame in UUID column is NA, populate NA even in the aggregated frame.Donot throw an exception.
> PUBDEV-5384: Rel-wheeler - If the original frame in UUID column is NA, populate NA even in the aggregator

- scripts/jenkins/groovy/defineTestStages.groovy
(cherry picked from commit b2daf11ebd2c77113a731c18b2228f5228a611ec)
> [WOL-ITA-261] Increase timeout for R Demos Medium-Large by 20 minutes.

- h2o-core/src/main/java/water/parser/CsvParser.java
- h2o-core/src/test/java/water/parser/ParserTest2.java
https://0xdata.atlassian.net/browse/PUBDEV-5409
> PUBDEV-5409 - Take care of quotes inside quoted string. 

- h2o-core/src/main/java/water/parser/CsvParser.java
- h2o-core/src/test/java/water/parser/ParserTest2.java
Fix for: https://0xdata.atlassian.net/browse/PUBDEV-5409
> PUBDEV-5409: Rel-wheeler - Take care of quotes inside quoted string.

- h2o-docs/src/product/automl.rst
- h2o-docs/src/product/data-science/algo-params/histogram_type.rst
- h2o-docs/src/product/data-science/drf.rst
Defined XRT in the DRF chapter and in the parameters appendix. Pointed to these in the AutoML chapter.
> PUBDEV-5416: Doc update for XRTs

- h2o-core/src/main/java/water/ClientDisconnectCheckThread.java
- h2o-core/src/main/java/water/FailedNodeWatchdogExtension.java
- h2o-core/src/main/java/water/H2O.java
- h2o-core/src/main/java/water/H2ONode.java
- h2o-core/src/main/java/water/Paxos.java
@michalkurka This PR is fixing the client reconnections issues consistetly acros flatfile and multicast mode. Please see the comments as it was easier to comment relevant parts of the code directly
> [PUBDEV-4865] Fix several issues affecting H2O client reconnection

- scripts/jenkins/Makefile.jenkins
(cherry picked from commit f0f784e3e41d7095b1151fb91c2d2fb69faa3f59)
> [WOL-ITA-265] Move the sed of the test*Node.sh to method in Makefile.jenkins.

- h2o-py/h2o/utils/shared_utils.py
- h2o-r/h2o-package/R/kvstore.R
- h2o-r/h2o-package/R/predict.R
- h2o-r/tests/testdir_javapredict/runit_mojo_predict.R
Adds two functions:
1. `h2o.mojo_predict_csv`
2. `h2o.mojo_predict_df`
Should mirror the functionality from Python -> #2076
> [PUBDEV-5424] MOJO scoring on a CSV or data frame in R.

- h2o-core/src/main/java/water/api/schemas3/ModelSchemaBaseV3.java
(cherry picked from commit 776301c0551ee439d69c8e9bc19b40cbbad231ee)
> [WOL-PUBDEV-5451] Populate have_pojo and have_mojo fields of ModelSchemaBaseV3.

- h2o-core/src/main/java/water/parser/CsvParser.java
- h2o-py/tests/testdir_jira/pyunit_pubdev_5441.py
Commits from https://github.com/h2oai/h2o-3/pull/2242 cherry-picked for rel-wheeler.
> Pavel pubdev 5441 rel wheeler

- h2o-r/scripts/h2o-r-test-setup.R
- scripts/run.py
(cherry picked from commit 47f85c80d716384b688b88daffcf477095caf680)
> [WOL-ITA-267] Param to enable REST API logging. Disabled by default.

- scripts/jenkins/groovy/benchmarkStage.groovy
- scripts/jenkins/groovy/buildConfig.groovy
- scripts/jenkins/groovy/compareBenchmarksStage.groovy
- scripts/jenkins/groovy/defineTestStages.groovy
- scripts/jenkins/groovy/insideDocker.groovy
- scripts/jenkins/groovy/pipelineContext.groovy
- scripts/jenkins/jenkinsfiles/Jenkinsfile-Benchmarks
[ITA-269] Update benchmark image SHA
[ITA-269] Mount whole 0xdiag.
[ITA-273] Redirect output of docker inspect to /dev/null
[ITA-269] Add expected values for xgb and vanilla xgb.
Add vanilla xgb benchmark.
[ITA-269] Update expected values
> [ITA-269] Add XGB Benchmark stage.

- scripts/jenkins/jenkinsfiles/Jenkinsfile-Release
(cherry picked from commit cb6d5c2c70f4d7b2a6bbda56f5ccd35a5b098b4a)
> [ITA-275] Check Conda package from s3 (#2279)

- h2o-core/build.gradle
- h2o-extensions/jython-cfunc/build.gradle
(cherry picked from commit 0fcc48bafdad848c1e64d7c04bc88101223335e8)
> [PUBDEV-5460] Update mockito library (#2270)

- scripts/jenkins/jenkinsfiles/Jenkinsfile-Release
(cherry picked from commit cb6d5c2c70f4d7b2a6bbda56f5ccd35a5b098b4a)
> [ITA-275] Check Conda package from s3

- scripts/jenkins/groovy/benchmarkStage.groovy
- scripts/jenkins/groovy/buildConfig.groovy
- scripts/jenkins/groovy/compareBenchmarksStage.groovy
- scripts/jenkins/groovy/defineTestStages.groovy
- scripts/jenkins/groovy/insideDocker.groovy
- scripts/jenkins/groovy/pipelineContext.groovy
- scripts/jenkins/jenkinsfiles/Jenkinsfile-Benchmarks
(cherry picked from commit b0032c2a5b5e25ab5714d8acba4bf82f5b8b4abe)
> [WOL-ITA-269] Add XGB Benchmark stage. (#2266) [WOL-ITA-273] Redirect output of docker inspect to /dev/null

- h2o-core/src/main/java/water/H2O.java
- h2o-core/src/main/java/water/util/JCodeGen.java
(cherry picked from commit 11c4d7f21094c21cf40708b5cfaa9bd888fca0c2)
> [WOL-PUBDEV-4956] Changes required to run with Java 9. (#2316)

- h2o-automl/src/main/java/ai/h2o/automl/AutoML.java
Tiny change. It was confusing as I was looking for column `predictionis` however the column was `prediction`
> [PUBDEV-5500] Fix warning messages in automl

- h2o-automl/src/main/java/ai/h2o/automl/AutoML.java
(cherry picked from commit 46e20f0b756605cace511a882596ad194fc266a5)
> [PUBDEV-5500] Fix warning messages in automl (#2328)

- h2o-automl/src/main/java/ai/h2o/automl/Leaderboard.java
- h2o-py/tests/testdir_algos/automl/binomial/pyunit_automl_prostate.py
- h2o-py/tests/testdir_algos/automl/multinomial/pyunit_automl_iris.py
- h2o-py/tests/testdir_algos/automl/pyunit_automl_leaderboard.py
- h2o-py/tests/testdir_algos/automl/regression/pyunit_automl_australia.py
- h2o-r/tests/testdir_algos/automl/runit_automl_leaderboard.R
* For binomial problems add mean_per_class_error, rmse, and mse
* For multinomial problems add logloss, rmse, and mse
* For regression add mse
> PUBDEV-5499 Add more metrics to AutoML leaderboard

- h2o-docs/src/product/automl.rst
Same as this: https://github.com/h2oai/h2o-3/pull/2300 PR but now on master.
> PUBDEV-5227: AutoML user guide updates

- h2o-bindings/bin/gen_R.py
- h2o-r/.gitignore
- h2o-r/h2o-package/R/models.R
- h2o-r/h2o-package/R/stackedensemble.R
https://0xdata.atlassian.net/browse/PUBDEV-5462
Example output:
```
> ensemble@model$model_summary
Summary of Base Learners:
algorithm number_of_trees number_of_internal_trees model_size_in_bytes min_depth max_depth mean_depth
1       gbm              10                       10                1619         3         3          3
2       drf              50                       50              943609        20        20         20
min_leaves max_leaves mean_leaves
1          8          8        8.00
2       1402       1583     1496.52
Summary of Metalearners:
Metalearner algorithm: glm
Metalearners cross-validation fold assignment:
Fold assignment scheme: Random
Number of folds: 2
Fold column: NULL
```
> [PUBDEV-5462] Add model summary in Stacked Ensemble

- h2o-extensions/xgboost/src/main/java/ml/dmlc/xgboost4j/java/XGBoostUpdateTask.java
The idea of this PR is to avoid repeated serialization/deserialization of Booster in single node setups.
We defer serialization to the latest possible moment.
Perf measurements on "Szilard 10m":
- h2o.gbm: 182.873s, auc: 0.7763285
- xgboost(native): 124.497s, auc: 0.7551197 
- lightgbm 50.727s, auc: 0.7739303 
- h2o.xgboost: **174s**, auc: 0.7556783; before fix: **1134s**
> PUBDEV-5477: Avoid serializing XGBooster in single-node setups

- h2o-genmodel/src/main/java/hex/genmodel/utils/ParseUtils.java
- h2o-genmodel/src/test/java/hex/genmodel/utils/ParseUtilsTest.java
Added parseLong to ParseUtils.java for improved accuracy reading long variables.
> Added parseLong to ParseUtils.java

- h2o-py/h2o/backend/__init__.py
* [PUBDEV-5507] More robust check for Colorama version
(cherry picked from commit c027546f615e31a331c01bbeb2fdac85f9cd2c18)
> [PUBDEV-5507] More robust check for colorama  version (#2342)

- h2o-r/h2o-DESCRIPTION.template
- Properly attribute copyright
- Make sure H2O is in single quotes in DESCRIPTION
> Correct R package metadata

- h2o-core/src/main/java/water/api/schemas3/KeyV3.java
Get rid of KeyV1 in comments and error messages as we are using KeyV3
> [PUBDEV-5527] Replacae KeyV1 by KeyV3 in KeyV3 class

- h2o-core/src/main/java/water/api/schemas3/KeyV3.java
(cherry picked from commit 98a8ee24215fee34f554786447d1d0c984f4e4e0)
> [PUBDEV-5527] Replacae KeyV1 by KeyV3 in KeyV3 class (#2362)

- h2o-core/src/main/java/hex/ModelBuilder.java
- h2o-core/src/main/java/water/ExtensionManager.java
- h2o-core/src/test/java/hex/ModelBuilderTest.java
> [wolpert] PUBDEV-5290: Add a little bit more information when ALGO is not found in MB

- h2o-web/bower.json
Updates Flow to 0.7.22.
Contributed by Tapad, see https://github.com/h2oai/h2o-flow/pull/63
> [PUBDEV-5540] Expose Import SQL in Flow.

- scripts/jenkins/groovy/buildH2O3.groovy
- scripts/jenkins/groovy/defineTestStages.groovy
- scripts/jenkins/groovy/hadoopStage.groovy
[ITA-291] Run on micro nodes only.
[ITA-291] Remove wildcards from HDP related env vars.
[ITA-291] Increase build timeout to 50 minutes for hadoop build.
(cherry picked from commit a84a6159dfdec360549d841e002ed28fed1c0b88)
> [WOL-ITA-291] Add standalone tests for H2O + Hadoop. (#2376)

- h2o-core/src/main/java/water/ExternalFrameWriterBackend.java
- h2o-core/src/test/java/water/ExternalFrameWriterClientTest.java
(cherry picked from commit 56761bd9f1cc4f66a7ffff3315a5384caab290b5)
> [PUBDEV-5544] External Backend stored sparse vector values incorrectly

- gradle.properties
- h2o-algos/build.gradle
- h2o-core/build.gradle
- h2o-parsers/h2o-orc-parser/build.gradle
- h2o-parsers/h2o-parquet-parser/build.gradle
- h2o-persist-hdfs/build.gradle
(cherry picked from commit dee6964e610372f6efe0e9861da4bd1b160dbac8)
for rel-wolpert
> [PUBDEV-5464] Fix issue preventing to load h2o libraries in DBC

- h2o-r/h2o-package/R/frame.R
> fix cran test failure

- h2o-py/scripts/verify_requirements.py
(cherry picked from commit 2f2937077ea2d884d861342b56de6d27616004b1)
> [WOL-PUBDEV-5486] Fix build when using pip 10.0.0. (#2337)

- scripts/jenkins/groovy/buildH2O3.groovy
- scripts/jenkins/groovy/defineTestStages.groovy
(cherry picked from commit 042111e0dbfe2e06a5c3e669af2f583fa171dd1e)
> [WOL-ITA-293] Remove withCustomCommitStates. Stages are now reported automatically.

- h2o-core/src/main/java/hex/ModelBuilder.java
Time type is completely valid in response column, yet it is forbidden now.
Should also create a PR for rel-Wolpert.
> Time allowed in Response variable

- h2o-core/src/main/java/hex/ModelBuilder.java
Rel-wolpert version of https://github.com/h2oai/h2o-3/pull/2390
> Response variable time type allowed (wolpert)

- scripts/jenkins/Makefile.jenkins
- scripts/jenkins/groovy/buildH2O3.groovy
- scripts/jenkins/groovy/defineTestStages.groovy
(cherry picked from commit 96d103edc6edbda2c0a76ca160ce9322b6bc8d54)
> [WOL-ITA-294] Move AutoML related tests to separate stages.

- scripts/jenkins/jenkinsfiles/Jenkinsfile-Release
Do not ignore twine related errors.
Remove check PyPI stage.
(cherry picked from commit 4d7347dc136fed90a7549f49cf1111ecc60c9df0)
> [ITA-295] Fix PyPI release stage.

- h2o-algos/src/main/java/hex/coxph/CoxPH.java
- h2o-algos/src/main/java/hex/coxph/CoxPHModel.java
- h2o-r/tests/testdir_algos/coxph/runit_coxph_offset.R
Minor changes to enable offset_column in CoxPH
> Fix issues with offset_column in CoxPH

- h2o-automl/src/main/java/ai/h2o/automl/AutoML.java
* A quick pass on cleaning up comments in AutoML class.
> Minor cleanup to AutoML class

- h2o-algos/src/main/java/hex/coxph/CoxPH.java
This saves us a little bit of time in CoxPHTask. This lays ground work
for future improvements.
> CoxPH: refactoring - time is discretized

- h2o-docs/template/index.html
- h2o-docs/template/rest-api-reference.html
(cherry picked from commit 5843a718ade794b7504f3dc05f25ec09e3963a01)
> [PUBDEV-5568] Remove GA from docs page. (#2418)

- h2o-algos/src/main/java/hex/coxph/CPHBaseTask.java
- h2o-algos/src/main/java/hex/coxph/CoxPH.java
- h2o-algos/src/main/java/hex/coxph/EfronMethod.java
- h2o-algos/src/test/java/hex/coxph/EfronDJKTermTaskTest.java
- h2o-r/tests/testdir_algos/coxph/runit_coxph_strata2.R
The important change is in https://github.com/h2oai/h2o-3/pull/2409/files#diff-24001238d1504e72344b594ac99bb031R142, rest of the PR is refactoring.
> CoxPH: optimize vector-vector multiplication (result is symmetric)

- h2o-docs/template/index.html
- h2o-docs/template/rest-api-reference.html
(cherry picked from commit 5843a718ade794b7504f3dc05f25ec09e3963a01)
> [PUBDEV-5568] Remove GA from docs page.

- h2o-web/bower.json
> [PUBDEV-5567] Remove GA from Flow.

- h2o-dist/index.html
(cherry picked from commit 05bf2884b00acd0852891f90151fe43c184bf07d)
> [WOL-PUBDEV-5580] Remove forgotten trackLinks() from index.html. (#2430)

- h2o-dist/index.html
(cherry picked from commit 05bf2884b00acd0852891f90151fe43c184bf07d)
> [WHEELER-PUBDEV-5580] Remove forgotten trackLinks() from index.html.

- h2o-docs/src/front/index.html
this is for users who bookmarked the “release” doc site
> make built front page match docs site

- scripts/jenkins/groovy/buildH2O3.groovy
- scripts/jenkins/groovy/buildSummary.groovy
- scripts/jenkins/groovy/makeTarget.groovy
* [ITA-300] Do not archive jars, whls etc.
Only archive files, when the stage failed.
* [ITA-300] Don't display Arficats link for successful stages.
(cherry picked from commit 8934c5e2338bc5846b3237ff5804d6f2d0dd861c)
> [ITA-300] Do not archive jars, whls etc. Only archive files, when the stage failed.

- h2o-dist/index.html
(cherry picked from commit 25ba51f21c0f3849712b8cf36f3ae1f6cbe7d728)
> [ITA-302] Fix download link.

- scripts/jenkins/groovy/buildConfig.groovy
- scripts/jenkins/groovy/buildH2O3.groovy
(cherry picked from commit 384ddace90842496250a953fcccc583b100aff94)
> [ITA-270] Always stash basic packages (R, Python).

- scripts/jenkins/groovy/buildConfig.groovy
(cherry picked from commit 200daf67632f0008838b4fb0aa17cf7a1505510b)
> [ITA] Fix changes detection. (#2451)

- h2o-r/h2o-package/R/frame.R
Someone was confused on Stack Overflow, so I created an example and copied to R docs: https://stackoverflow.com/questions/50476210/how-to-order-levels-of-a-factor-in-r-h2o/50476348#50476348
> Adding R example for h2o.relevel()

- h2o-genmodel/src/main/java/hex/genmodel/algos/gbm/GbmMojoModel.java
- h2o-genmodel/src/main/java/hex/genmodel/algos/tree/SharedTreeMojoModel.java
- h2o-genmodel/src/main/java/hex/genmodel/easy/EasyPredictModelWrapper.java
- h2o-genmodel/src/main/java/hex/genmodel/easy/prediction/BinomialModelPrediction.java
- h2o-genmodel/src/main/java/hex/genmodel/easy/prediction/MultinomialModelPrediction.java
- h2o-genmodel/src/main/java/hex/genmodel/easy/prediction/RegressionModelPrediction.java
- h2o-genmodel/src/main/java/hex/genmodel/tools/PredictCsv.java
- h2o-py/demos/README.md
- h2o-py/tests/pyunit_utils/utilsPY.py
- h2o-py/tests/testdir_javapredict/pyunit_PUBDEV_5529_leaf_node_DRF_mojo.py
- h2o-py/tests/testdir_javapredict/pyunit_PUBDEV_5529_leaf_node_GBM_mojo.py
- h2o-r/tests/runitUtils/utilsR.R
- h2o-r/tests/testdir_javapredict/runit_PUBDEV_5529_leaf_node_assign_drf_mojo.R
- h2o-r/tests/testdir_javapredict/runit_PUBDEV_5529_leaf_node_assign_gbm_mojo.R
1.  Added backend code to add leaf node assignment to DRF, GBM mojo
2.  Added Pyunit tests
3.  Added Runit tests
> PUBDEV-5529 add leaf node assignment to DRF, GBM mojo

- h2o-hadoop/h2o-mapreduce-generic/src/main/java/water/hadoop/h2odriver.java
tested with
-jks
/Users/mkurka/git/h2o/mykeystore.jks
-jks_pass
h2oh2o
-proxy
-jks
/Users/mkurka/git/h2o/mykeystore.jks
-jks_pass
h2oh2o
-pam_login
-login_conf
/Users/mkurka/git/h2o/pam.conf
> PUBDEV-5598: -proxy does not work in the h2odriver.args file

- scripts/jenkins/groovy/hadoopStage.groovy
@michal-raska proxy mode doesn't support `-disown` - hence the for loop
> PUBDEV-5611: Use proxy mode in Hadoop tests

- h2o-py/tests/testdir_algos/pca/pyunit_wideDataset_Rotterdam_large.py
Fix the rare case failure when the difference falls to 1.2e-5.
> more tolerance setting to one place and relax it from 1e-6 to we-5.

- h2o-web/bower.json
(cherry picked from commit 17fb9c534fffacb3c1b460318fe0c95ef9c12b06)
> [WRI-FLOW-PUBDEV-5621] Add balance classes related args to AutoML.

- scripts/jenkins/groovy/defineTestStages.groovy
(cherry picked from commit 0f648a21640e9d3c35571a1765afa6d01b083525)
> [WRI-ITA] Remove benchmark image.

- scripts/jenkins/Makefile.jenkins
- scripts/jenkins/groovy/defineTestStages.groovy
- tests/pyunitSingleNodeList
* [ITA-309] Single node PyUnit tests.
* [ITA-309] Add Single Node tests for Py3.5 and Py 3.6.
(cherry picked from commit 8390fa04913af2a0215f5f70783d22e2b32c5bcd)
> [ITA-309] Single node PyUnit tests.

- h2o-core/src/main/java/hex/PartialDependence.java
- h2o-r/h2o-package/R/models.R
This PR adds standard error of the mean to PDP
Standard error of mean versus standard deviation:
In scientific and technical literature, experimental data are often summarized either using the mean and standard deviation of the sample data or the mean with the standard error. This often leads to confusion about their interchangeability. However, the mean and standard deviation are descriptive statistics, whereas the standard error of the mean is descriptive of the random sampling process. The standard deviation of the sample data is a description of the variation in measurements, while the standard error of the mean is a probabilistic statement about how the sample size will provide a better bound on estimates of the population mean, in light of the central limit theorem.
Put simply, the …
> PUBDEV-5637 Add Standard Error of Mean (SEM) to PDP

- h2o-core/build.gradle
- h2o-core/src/main/java/water/jdbc/SQLManager.java
- h2o-core/src/test/java/water/jdbc/SQLManagerTest.java
https://0xdata.atlassian.net/browse/PUBDEV-5590
> PUBDEV-5590 - Argument to limit number of sessions for import_sql_table

- h2o-r/h2o-DESCRIPTION.template
https://0xdata.atlassian.net/browse/PUBDEV-5542
> PUBDEV-5542: Update description of h2o in R package

- h2o-r/h2o-DESCRIPTION.template
rel-wright version of this: https://github.com/h2oai/h2o-3/pull/2520
> PUBDEV-5542: Update description of h2o in R package 

- h2o-algos/src/main/java/hex/coxph/EfronMethod.java
- h2o-algos/src/test/java/hex/coxph/EfronDJKTermTaskTest.java
We don't want to send too much data over the wire
> CoxPH: Only send the required input to EfronDJKTermTask

- h2o-py/h2o/frame.py
- h2o-r/h2o-package/R/frame.R
[PUBDEV-5672](https://0xdata.atlassian.net/browse/PUBDEV-5672)
@angela0xdata Please correct me if I should have generated html docs as well.
> PUBDEV-5672 - h2o-r : correct r docs for h2o.sum

- h2o-core/src/jmh/java/water/NewChunkBench.java
- h2o-core/src/test/java/water/fvec/NewChunkSpeedTest.java
Added NewChunkSpeedTest.java to test the time taken to create integer/long/double vectors.
> Pubdev 5650 newchunk timing test

- h2o-algos/src/main/java/hex/glrm/GLRMModel.java
- h2o-docs/src/product/mojo-quickstart.rst
- h2o-genmodel/src/main/java/hex/genmodel/tools/PredictCsv.java
- h2o-py/tests/pyunit_utils/utilsPY.py
Three things:
1. Added documentation to show users how to obtain the X coefficients for archetypes and to obtain the reconstructed input row.
2. Changed GLRM mojo test to make it more robust. 
3. Fixed one line bug to use the frame.checksum() to distinguish frames instead of relying on the frame key.
> PUBDEV-5678: added GLRM mojo documentation.  

- h2o-core/src/main/java/water/jdbc/SQLManager.java
- h2o-core/src/test/java/water/jdbc/SQLManagerTest.java
java -Dsys.ai.h2o.sql.jdbc.driver.testdb=com.mycompany.MyDbDriver -cp h2o.jar:mydb.jar water.H2OApp
> PUBDEV-5696: Add option to use a user-specified JDBC driver

- h2o-core/src/main/java/water/H2O.java
- h2o-hadoop/h2o-mapreduce-generic/src/main/java/water/ProxyStarter.java
- h2o-hadoop/h2o-mapreduce-generic/src/main/java/water/hadoop/h2odriver.java
> PUBDEV-5680: Report proxy hostname in h2odriver output instead of the IP

- h2o-core/src/main/java/water/api/schemas3/ModelMetricsBinomialV3.java
- h2o-py/tests/testdir_jira/pyunit_pubdev_5665_pr_auc.py
- h2o-py/tests/testdir_misc/pyunit_metric_json_check.py
- h2o-r/tests/testdir_jira/runit_pubdev_5665_pr_auc.R
* PUBDEV-5665: added pr_auc to ModelMetricsBinomialV3.java.
PUBDEV-5665: Added pyunit test.
PUBDEV-5665: added runit test to access pr_auc for all binomial classifiers.
* Added pr_auc to expected field.
> PUBDEV-5665: expose pr_auc to R/Python/Flow clients (#2565)

- h2o-r/h2o-DESCRIPTION.template
https://0xdata.atlassian.net/browse/PUBDEV-5662
> [wright] PUBDEV-5662: Capitalize algo names in R pkg description

- h2o-r/h2o-DESCRIPTION.template
https://0xdata.atlassian.net/browse/PUBDEV-5662
> PUBDEV-5662: Capitalize algo names in R pkg description

- h2o-docs/src/product/data-munging/groupby.rst
Replaced “NumberOfFlights” with “Month” in the R example. Also added ending “)” to that line.
> PUBDEV-5711-relwright: Fix group_by R example

- h2o-docs/src/booklets/v2_2015/source/GLMBooklet.tex
- h2o-docs/src/product/data-science/glm.rst
For Poisson family, add note about deviance being the negative log of
the likelihood
> PUBDEV-5702-relwright: Updated description of function

- h2o-core/src/main/java/hex/ScoringInfo.java
rel-wright version of https://github.com/h2oai/h2o-3/pull/2541
> Pavel pubdev 5576 bad scoring history rel wright

- h2o-web/bower.json
[PUBDEV-5707] Enable Switching between edit and command mode on Scala cells. PUBDEV-5572 Improve Confusion Matrix UI.
> [FLOW] Update to 0.7.31

- h2o-web/bower.json
[PUBDEV-5707] Enable Switching between edit and command mode on Scala cells. PUBDEV-5572 Improve Confusion Matrix UI.
(cherry picked from commit 420e4e460b1d9fa1633e24ca30880b2635bd3d2d)
> [WRI-FLOW] Update to 0.7.31

- h2o-py/h2o/frame.py
- h2o-r/h2o-package/R/frame.R
(cherry picked from commit fa1968e)
rel-wright version of https://github.com/h2oai/h2o-3/pull/2553
> PUBDEV-5672 - h2o-r : correct r docs for h2o.sum (#2553)

- h2o-r/h2o-package/R/connection.R
> PUBDEV-5681: add docs to config parameter in h2o.connect

- h2o-core/src/test/java/hex/ScoringInfoTest.java
(cherry picked from commit 2262eac)
> ScoringInfoTest timestamp asserts respects timezone

- h2o-docs/src/front/index.html
- Updated links for Enterprise Steam and Steam downloads
- Added AutoML to list of algos
- Added RStudio cheat sheet
> Updated front page for docs site

- h2o-docs/src/front/index.html
- Updated links for Enterprise Steam and Steam downloads
- Added AutoML to list of algos
- Added RStudio cheat sheet link
> Updated front page for docs site (master)

- h2o-algos/src/main/java/hex/tree/SharedTree.java
- h2o-core/src/main/java/hex/AUC2.java
- h2o-core/src/main/java/hex/ModelMetricsBinomial.java
- h2o-core/src/main/java/hex/ScoreKeeper.java
- h2o-core/src/main/java/hex/ScoringInfo.java
- h2o-core/src/main/java/water/api/SchemaServer.java
- h2o-core/src/main/java/water/api/schemas3/ModelMetricsBinomialV3.java
- h2o-core/src/test/java/hex/ScoringInfoTest.java
- h2o-py/h2o/model/metrics_base.py
- h2o-py/tests/testdir_jira/pyunit_pubdev_5665_pr_auc.py
- h2o-r/h2o-package/R/classes.R
- h2o-r/h2o-package/R/glm.R
- h2o-r/h2o-package/R/models.R
- h2o-r/tests/testdir_jira/runit_pubdev_5665_pr_auc.R
pr-auc was added to model_json.  However, users may not be aware of it.  Hence, it is added to all places that AUCs are, in scoring_history, model summary and h2o.pr_auc() in R.
> Pubdev 5722 expose pr auc

- h2o-py/demos/H2O_tutorial_eeg_eyestate.ipynb
https://0xdata.atlassian.net/browse/PUBDEV-5737
> PUBDEV-5737: Fixing bug in EEG eyestate python demo

- h2o-bindings/bin/gen_python.py
- h2o-py/h2o/estimators/stackedensemble.py
- h2o-py/h2o/model/model_base.py
- h2o-py/tests/testdir_jira/pyunit_pubdev_5023_rm_metalearner.py
Metalearner belongs to stackensemble and not the other algos.
- removed metalearn() method from model_base.py 
- added pyunit test to make sure it is GONE.
> PUBDEV-5023-remove-metalearner

- h2o-py/tests/testdir_misc/pyunit_partial_plots.py
* This PR updates `pyunit_partial_plots.py` by ensuring PDP calculations for mean, standard deviation, and standard error of the mean are correct against a manual PDP computation.
>  Update pyunit for pdp to ensure mean, standard deviation, & standard error of the mean are correct

- h2o-core/src/test/java/hex/AUC2Test.java
- h2o-extensions/xgboost/src/main/java/hex/tree/xgboost/XGBoostModel.java
- h2o-extensions/xgboost/src/main/java/ml/dmlc/xgboost4j/java/XGBoostScoreTask.java
- h2o-extensions/xgboost/src/test/java/hex/tree/xgboost/XGBoostTest.java
https://0xdata.atlassian.net/browse/PUBDEV-5720
> Pavel pubdev 5720 xgboost cross validation

- h2o-web/bower.json
> [FLOW-PUBDEV-5555] Fix incorrect clipping of tooltip.

- h2o-web/bower.json
Update Flow to 0.7.32
(cherry picked from commit f7bec461151936dc5b690dfcdacd329766afaa4c)
> [WRI-FLOW-PUBDEV-5555] Fix incorrect clipping of tooltip.

- .gitignore
- h2o-py/h2o/__init__.py
- h2o-py/h2o/utils/shared_utils.py
- h2o-py/tests/testdir_misc/pyunit_mojo_predict.py
> PUBDEV-5739: Expose mojo_predict_csv() and mojo_predict_pandas() as top level h2o functions

- .gitignore
- h2o-py/h2o/__init__.py
- h2o-py/h2o/utils/shared_utils.py
- h2o-py/tests/testdir_misc/pyunit_mojo_predict.py
* Expose mojo_predict_csv() and mojo_predict_pandas() as top level h2o functions
* [PUBDEV-5739] Modify imports in test.
> PUBDEV-5739: Expose mojo_predict_csv() and mojo_predict_pandas() as top level h2o functions (#2651)

- h2o-algos/src/main/java/hex/StackedEnsembleModel.java
- h2o-py/tests/testdir_algos/stackedensemble/pyunit_stackedensemble_multinomial_large.py
- h2o-r/tests/testdir_algos/stackedensemble/runit_stackedensemble_multinomial_large.R
- Fixes: https://0xdata.atlassian.net/browse/PUBDEV-5814
- Also adds XGBoost, Naive Bayes, Deep Learning and GLM to the multinomial Stacked Ensemble runit and pyunit tests (now we have 100% test coverage for all base learners in the multinomial case).
> PUBDEV-5814: Multinomial Stacked Ensemble fails with either XGBoost or Naive Bayes base model

- h2o-algos/src/main/java/hex/StackedEnsembleModel.java
- h2o-py/tests/testdir_algos/stackedensemble/pyunit_stackedensemble_multinomial_large.py
- h2o-r/tests/testdir_algos/stackedensemble/runit_stackedensemble_multinomial_large.R
rel-wright version of this PR: https://github.com/h2oai/h2o-3/pull/2714
> PUBDEV-5814: Multinomial Stacked Ensemble fails with either XGBoost or Naive Bayes base model 

- h2o-docs/src/product/flow/packs/test-small/automl_prostate.flow
- h2o-docs/src/product/flow/packs/test-small/index.list
Adds a simple AutoML test for Flow. ~Test is failing, which is correct, since #2710 hasn't been merged yet. After merge of #2710 and rebase, test should be green.~
> [WRI-PUBDEV-5813] Add AutoML test for Flow.

- h2o-algos/src/main/java/hex/deeplearning/DeepLearningModel.java
- h2o-algos/src/main/java/hex/tree/SharedTree.java
- h2o-automl/src/main/java/ai/h2o/automl/AutoML.java
- h2o-automl/src/main/java/ai/h2o/automl/AutoMLBuildSpec.java
- h2o-automl/src/main/java/ai/h2o/automl/Leaderboard.java
- h2o-automl/src/main/java/ai/h2o/automl/UserFeedback.java
- h2o-automl/src/main/java/water/automl/api/schemas3/AutoMLBuildSpecV99.java
- h2o-core/src/main/java/hex/ModelBuilder.java
- h2o-core/src/main/java/hex/grid/GridSearch.java
- h2o-core/src/main/java/water/Job.java
- h2o-core/src/main/java/water/util/ArrayUtils.java
- h2o-py/tests/testdir_algos/automl/pyunit_automl_args.py
- h2o-r/tests/testdir_algos/automl/runit_automl_args.R
https://0xdata.atlassian.net/browse/PUBDEV-5613
- in AutoML:
- check for search limits before starting any training or hyperparameter search.
- StackedEnsemble also included in those checkings.
- in ModelBuilder:
- ensure we don't manipulate incomplete model after interrupting CV.
- always let the final scoring happen in CV if the main model completed.
> PUBDEV-5613: AutoML (and all models) should respect max_runtime_secs

- h2o-core/src/main/java/water/FailedNodeWatchdogExtension.java
- h2o-core/src/main/java/water/H2O.java
Explanation of the issue provided at https://0xdata.atlassian.net/browse/PUBDEV-5819
> [PUBDEV-5819] Fix Client Disconnection Timeout in context of External Backend

- h2o-docs/src/product/flow/packs/test-small/automl_prostate.flow
- h2o-docs/src/product/flow/packs/test-small/index.list
(cherry picked from commit 0d99cadc227144c4ce7b572e4c0a5ee4963cb29b)
> [FLOW-PUBDEV-5813] Add AutoML test for Flow.

- h2o-web/bower.json
> [FLOW-PUBDEV-5793] Fix ignored columns in AutoML.

- scripts/jenkins/Makefile.jenkins
- scripts/jenkins/groovy/defineTestStages.groovy
(cherry picked from commit 56a3aa07898b30e1a979c91ec0d1a014c250ee45)
> [WRI-ITA-327] Add mojo-compatibility stage.

- h2o-algos/src/main/java/hex/glrm/GLRM.java
- h2o-py/tests/pyunit_utils/utilsPY.py
- h2o-py/tests/testdir_algos/glrm/pyunit_pubdev_5493_glrm_seed.py
Fixed bug in GLRM so that it will return the same model ran with same parameter setting, training dataset.
Added pyunit test to make sure this fix is working.
> PUBDEV-5493-glrm-repeatability

- h2o-docs/src/product/data-science/stacked-ensembles.rst
- Also increased the “Example” heading level
> PUBDEV-4590: Add Scala example to Stacked Ensemble chapter

- h2o-algos/src/main/java/hex/tree/CompressedTree.java
- h2o-algos/src/main/java/hex/tree/DTree.java
- h2o-algos/src/main/java/hex/tree/SharedTreeModel.java
- h2o-algos/src/main/java/hex/tree/drf/DrfMojoWriter.java
- h2o-algos/src/main/java/hex/tree/gbm/GbmMojoWriter.java
- h2o-algos/src/test/java/hex/tree/CompressedTreeTest.java
- h2o-core/src/main/java/hex/Model.java
- h2o-genmodel/src/main/java/hex/genmodel/algos/tree/SharedTreeGraph.java
- h2o-genmodel/src/main/java/hex/genmodel/algos/tree/SharedTreeMojoModel.java
- h2o-genmodel/src/main/java/hex/genmodel/algos/tree/SharedTreeSubgraph.java
- h2o-genmodel/src/main/java/hex/genmodel/easy/EasyPredictModelWrapper.java
- h2o-genmodel/src/main/java/hex/genmodel/easy/prediction/BinomialModelPrediction.java
- h2o-genmodel/src/main/java/hex/genmodel/easy/prediction/MultinomialModelPrediction.java
- h2o-genmodel/src/main/java/hex/genmodel/easy/prediction/RegressionModelPrediction.java
- h2o-genmodel/src/test/java/hex/genmodel/algos/gbm/GbmMojoModelTest.java
This PR changes code that is on the critical path in GBM/DRF model training. It should be carefully reviewed.
> PUBDEV-5812: Add terminal node ids to model outputs in MOJO

- scripts/jenkins/Makefile.jenkins
- scripts/jenkins/groovy/defaultStage.groovy
- scripts/jenkins/groovy/defineTestStages.groovy
Do not install R package for this stage.
Modify the test-package-r.zip
> [ITA-322] Fix R Docs.

- scripts/jenkins/Makefile.jenkins
- scripts/jenkins/groovy/defaultStage.groovy
- scripts/jenkins/groovy/defineTestStages.groovy
Do not install R package for this stage.
Modify the test-package-r.zip
(cherry picked from commit 275dd9a041316735431df8401dd0bc6f10b0ef63)
> [WRI-ITA-322] Fix R Docs.

- h2o-core/src/main/java/water/jdbc/SQLManager.java
- h2o-core/src/test/java/water/jdbc/SQLManagerTest.java
https://0xdata.atlassian.net/browse/PUBDEV-5780
Added support for Teradata database; 
refactored SQL generation code;
added tests for SQL generation;
> PUBDEV-5780 Adds support for importing Teradata using JDBC interface

- h2o-bindings/src/main/java/water/bindings/examples/Example.java
- h2o-core/src/main/java/water/api/FramesHandler.java
- h2o-core/src/main/java/water/api/schemas3/FramesListV3.java
- h2o-core/src/main/java/water/api/schemas3/FramesV3.java
- h2o-core/src/main/resources/META-INF/services/water.api.Schema
(cherry picked from commit baa2ff0433c488cdab3d966d0bb1467b0d421311)
> [PUBDEV-5724] Expose full frame into in Java H2ORestAPI (#2639)

- h2o-genmodel-extensions/xgboost/build.gradle
- h2o-genmodel-extensions/xgboost/src/main/java/hex/genmodel/algos/xgboost/XGBoostJavaMojoModel.java
* [PUBDEV-5845] Use ai.h2o:xgboost-predictor:0.3.1
* [PUBDEV-5845] Update comment in XGBoostJavaMojoModel
(cherry picked from commit 9bd265e2e50b3c9124e15a513fdda56166366107)
> [PUBDEV-5845] Use ai.h2o:xgboost-predictor:0.3.1

- h2o-algos/src/test/java/hex/tree/TreeHandlerTest.java
In some cases, it is valid not to have any direction for NAs. In some cases it is not.
- The split on the very same column had been done earlier in the path and NAs went ELSEWHERE (not in the path this very node is on)
-In other cases, there MUST be a split for the feature either to the left or right.
This PR introduces test for both conditions.
> PUBDEV-5735 - NA direction handling in tree serialization tests

- h2o-bindings/src/main/java/water/bindings/examples/Example.java
- h2o-core/src/main/java/water/api/FramesHandler.java
- h2o-core/src/main/java/water/api/schemas3/FramesListV3.java
- h2o-core/src/main/java/water/api/schemas3/FramesV3.java
- h2o-core/src/main/resources/META-INF/services/water.api.Schema
- py/h2o.py
(cherry picked from commit 94d046777357bd1d4e05950a99824a7083f0c876)
> [PUBDEV-5724] Expose full frame into in Java H2ORestAPI (#2639) (#2758)

- h2o-core/src/main/java/water/rapids/ast/prims/mungers/AstFillNA.java
- h2o-core/src/test/java/water/rapids/ast/prims/advmath/AstFillNATest.java
https://0xdata.atlassian.net/browse/PUBDEV-5851
> PUBDEV-5851 - AstFillNA Rapids expression should throw H2O.unimp() on backward method

- h2o-docs/src/product/cross-validation.rst
- Added Python examples to the cross-validation topic. Make those similar to the R examples.
> PUBDEV-5756: Add Python example to cross-validation topic

- h2o-r/h2o-package/pkgdown/_pkgdown.yml
https://0xdata.atlassian.net/browse/PUBDEV-5735
> PUBDEV-5735 - Registered h2o.getModelTree in _pkgdown.yml (rel-wright)

- h2o-r/h2o-package/pkgdown/_pkgdown.yml
https://0xdata.atlassian.net/browse/PUBDEV-5735
> PUBDEV-5735 - Registered h2o.getModelTree in _pkgdown.yml (master)

- h2o-py/tests/testdir_javapredict/pyunit_pubdev_5826_glrm_predict_large.py
since the number of iteration has reduced, need to reduce accuracy of comparison.
> Relaxed comparison threshold since iteration number has dropped.

- h2o-r/h2o-package/R/automl.R
- h2o-r/h2o-package/R/frame.R
- h2o-r/tests/testdir_algos/automl/runit_automl_multiple_runs.R
- h2o-r/tests/testdir_misc/runit_as.h2o.R
https://0xdata.atlassian.net/browse/PUBDEV-5848
- R API: avoid naming conflicts when creating destination frame for automl leaderboard.
> PUBDEV-5848: error when manipulating previous AutoML leaderboard after multiple runs

- h2o-py/tests/testdir_javapredict/pyunit_pubdev_5826_glrm_predict_large.py
Fixed the order to compare data rows.
> Fixed row order in comparison.

- h2o-py/h2o/estimators/estimator_base.py
- h2o-py/tests/testdir_misc/pyunit_common_algo_params.py
- ensure max_runtime_secs is not overridden when not set in train() method
> PUBDEV-5880: max_runtimes_secs was ignored in some cases when training algo from Python API

- h2o-core/src/main/java/water/api/schemas3/ModelMetricsBinomialV3.java
- h2o-py/tests/testdir_misc/pyunit_metric_json_check.py
Related to https://github.com/h2oai/h2o-flow/pull/87
> [WRI-PUBDEV-5748] Expose CM for binomial as well.

- h2o-core/src/main/java/water/api/schemas3/ModelMetricsBinomialV3.java
- h2o-py/tests/testdir_misc/pyunit_metric_json_check.py
(cherry picked from commit b6170955edd2f792b907a33d39d559ecc352cfa1)
> [PUBDEV-5748] Expose CM for binomial as well.

- h2o-core/src/main/java/water/H2O.java
@michal-raska please use this property in H2O-3 smoke tests under Java 11-ea
> ITA-337: System property can disable Java version check

- h2o-core/src/main/java/water/H2O.java
https://0xdata.atlassian.net/browse/PUBDEV-5900
> PUBDEV-5900: Fix Java version in error message

- h2o-web/bower.json
> [FLOW-PUBDEV-5748] Generate CM for predictions.

- h2o-web/bower.json
> [WRI-FLOW-PUBDEV-5748] Generate CM for predictions.

- h2o-py/demos/README.md
- h2o-py/demos/tree_demo.ipynb
- h2o-py/h2o/demos.py
- h2o-py/h2o/tree/tree.py
https://0xdata.atlassian.net/browse/PUBDEV-5902
> PUBDEV-5902 - Python tree traversal demo

- h2o-py/demos/README.md
- h2o-py/demos/tree_demo.ipynb
- h2o-py/h2o/demos.py
- h2o-py/h2o/tree/tree.py
https://0xdata.atlassian.net/browse/PUBDEV-5902
> PUBDEV-5902 - Python tree traversal demo (#2835) (master)

- h2o-extensions/xgboost/src/test/java/hex/tree/xgboost/XGBoostTest.java
https://0xdata.atlassian.net/browse/PUBDEV-5906
> PUBDEV-5906 - XGBoost Sparsity detection test is non-deterministic

- h2o-extensions/xgboost/src/test/java/hex/tree/xgboost/XGBoostTest.java
https://0xdata.atlassian.net/browse/PUBDEV-5906
> PUBDEV-5906 - XGBoost Sparsity detection test is non-deterministic (#2840) (master)

- h2o-algos/src/test/java/hex/pdp/PartialDependenceTest.java
- h2o-core/src/main/java/hex/PartialDependence.java
- h2o-core/src/main/java/water/api/schemas3/PartialDependenceV3.java
- h2o-core/src/main/java/water/util/FrameUtils.java
- h2o-core/src/test/java/water/TestUtil.java
- h2o-core/src/test/java/water/util/FrameUtilsTest.java
- h2o-py/h2o/model/model_base.py
- h2o-py/tests/pyunit_utils/utilsPY.py
- h2o-py/tests/testdir_misc/pyunit_pubdev_5761_pdp_NA.py
- h2o-r/h2o-package/R/models.R
- h2o-r/tests/testdir_misc/runit_pubdev_5761_partialPlot_NA.R
1. Added java code to support partial dependency with weights specified by user;
2. Added java code to insert missing values (NA) to feature if user enable missing value insertion and there are missing values in the dataset.
3. Added Junit tests to verify all java changes.
4. Added Python API to support addition of two new features and Pyunit tests.
5. Added R API to support addition of two new features and R unit tests.
> PUBDEV-5761: enable weight and missing values to partialplots.

- h2o-core/src/main/java/hex/PartialDependence.java
- h2o-core/src/main/java/water/api/schemas3/PartialDependenceV3.java
- h2o-py/h2o/model/model_base.py
- h2o-py/tests/pyunit_utils/utilsPY.py
- h2o-py/tests/testdir_misc/pyunit_pubdev_5706_usersplits_pdp.py
- h2o-r/h2o-package/R/models.R
- h2o-r/tests/runitUtils/utilsR.R
- h2o-r/tests/testdir_misc/runit_pubdev_5706_usersplits_pdp.R
1 Added backend support to allow users use their own split points for partial plots.
2 Added Python API and Pyunit test.
3. Added R API and R unit test.
> PUBDEV 5706 user splits to partial plots.

- h2o-algos/src/test/java/hex/pdp/PartialDependenceTest.java
- h2o-core/src/main/java/hex/PartialDependence.java
- h2o-core/src/main/java/water/api/schemas3/PartialDependenceV3.java
- h2o-core/src/main/java/water/util/FrameUtils.java
- h2o-core/src/test/java/water/TestUtil.java
- h2o-core/src/test/java/water/util/FrameUtilsTest.java
- h2o-py/h2o/model/model_base.py
- h2o-py/tests/pyunit_utils/utilsPY.py
- h2o-py/tests/testdir_misc/pyunit_pubdev_5706_usersplits_pdp.py
- h2o-py/tests/testdir_misc/pyunit_pubdev_5761_pdp_NA.py
- h2o-r/h2o-package/R/models.R
- h2o-r/tests/runitUtils/utilsR.R
- h2o-r/tests/testdir_misc/runit_pubdev_5706_usersplits_pdp.R
- h2o-r/tests/testdir_misc/runit_pubdev_5761_partialPlot_NA.R
move from master to rel-wright branch
1. pdp with weight and missing value
2. pdp with user-split points
> rel-wright-pdp-all

- scripts/jenkins/groovy/buildConfig.groovy
- scripts/jenkins/groovy/insideDocker.groovy
- scripts/jenkins/jenkinsfiles/Jenkinsfile-Release
(cherry picked from commit 5743dad31cf40f401db883b44373ed3a8fcca955)
Using AWS CLI is in master for a few days and it looks OK so far. I checked with @angela0xdata and also from docs perspective everything looks good.
> [WRI-ITA-333] Use AWS CLI for release upload to S3.

- h2o-py/h2o/estimators/estimator_base.py
https://0xdata.atlassian.net/browse/PUBDEV-5922
> PUBDEV-5922: Renaming x to X in sklearn fit wrapper

- h2o-core/src/main/java/hex/PartialDependence.java
- h2o-core/src/main/java/water/util/FrameUtils.java
- h2o-core/src/test/java/water/util/FrameUtilsTest.java
- h2o-py/h2o/model/model_base.py
- h2o-py/tests/pyunit_utils/utilsPY.py
- h2o-py/tests/testdir_misc/pyunit_pubdev_5921_na_prints_large.py
- h2o-r/h2o-package/R/communication.R
- h2o-r/h2o-package/R/models.R
- h2o-r/tests/runitUtils/utilsR.R
- h2o-r/tests/testdir_misc/runit_pubdev_5761_partialPlot_NA.R
- h2o-r/tests/testdir_misc/runit_pubdev_5921_na_prints_large.R
- h2o-r/tests/testdir_misc/runit_pubdev_5928_printNA_H2OTable.R
Move PR from master to rel-wright for fix release.
> Move pdp work PUBDEV-5921, PUBDEV-5928 from master to rel-wright.

- h2o-py/h2o/model/model_base.py
- h2o-r/h2o-package/R/models.R
This is causing cran errors according to Michal Raska.  Thank you.
> Added definition for new parameter user_splits for R.  

- scripts/jenkins/groovy/defineTestStages.groovy
(cherry picked from commit 222f672fc85788f191a092627be9e6d205bc685f)
> [WRI-ITA-342] Test different Python version in nightly only.

- scripts/jenkins/jenkinsfiles/Jenkinsfile-Release
(cherry picked from commit 0457fda98594a72aca24d06e8c3622d45bd545d2)
> [ITA] Fix release pipeline.

- h2o-py/tests/testdir_algos/gbm/pyunit_ecology_gbm.py
**Blocked by #2882**
After update of `numpy`, the test is broken. Use of `pandas` instead of `numpy` shouldn't make any difference in context what the test is testing.
> [PUBDEV-5932] Use pandas in pyunit_ecology_gbm.py

- h2o-algos/src/main/java/hex/glrm/GLRMModel.java
- h2o-py/tests/testdir_algos/glrm/pyunit_pubdev_5930_load_glrm_bug.py
This PR completes the work for JIRA: https://0xdata.atlassian.net/browse/PUBDEV-5930.
The main fix is to try to load the x-factor frame.  If that fails, in the catch, we will call GLRMGenX to generate a new x-factor.
A pyunit test was written to make sure the fix works.
> Pubdev 5930 glrm load error

- h2o-web/bower.json
> [FLOW-PUBDEV-5954] Update lodash.

- h2o-core/src/main/java/water/init/HostnameGuesser.java
- h2o-core/src/main/java/water/util/LinuxProcFileReader.java
- h2o-core/src/main/java/water/util/OSUtils.java
Fixes issue on Ubuntu-on-windows where "-ip localhost" flag doesn't work.
> PUBDEV-5967: Added isWsl() capability.

- h2o-docs/src/product/data-science/stacked-ensembles.rst
- h2o-r/ensemble/README.md
Same as https://github.com/h2oai/awesome-h2o/pull/6 ;-)
> Hyperlink DOIs against preferred resolver

- gradle.properties
- h2o-assemblies/main/build.gradle
- h2o-bindings/build.gradle
- h2o-docs/build.gradle
- h2o-py/build.gradle
- h2o-r/build.gradle
- h2o-web/build.gradle
Fix dependencies between modules. It's possible to now build with `--parallel` flag, although not enabled by default.
> [ITA-343] Fix build deps.

- h2o-r/h2o-package/R/communication.R
- h2o-r/h2o-package/R/constants.R
- h2o-r/h2o-package/R/locate.R
- h2o-r/h2o-package/R/models.R
- h2o-r/h2o-package/R/parse.R
> PUBDEV-5904: Some (internal) R functions are not properly documented

- h2o-r/h2o-package/R/communication.R
> PUBDEV-5904: fixing typos in communication.R

- h2o-core/src/main/java/hex/ModelBuilder.java
- h2o-core/src/main/java/water/H2O.java
- h2o-core/src/main/java/water/api/AlgoAbstractRegister.java
https://0xdata.atlassian.net/browse/PUBDEV-5988
Simple version of https://github.com/h2oai/h2o-3/pull/2944
> PUBDEV-5988 Add experimental feature flag to the launch option

- h2o-docs/src/product/automl.rst
- h2o-py/h2o/automl/autoh2o.py
- h2o-r/h2o-package/R/automl.R
- h2o-r/tests/testdir_algos/automl/runit_automl_leaderboard.R
https://0xdata.atlassian.net/browse/PUBDEV-6001
> PUBDEV-6001: Add runit for XGBoost option in exclude_algos and update documentation in AutoML

- h2o-py/tests/pyunit_utils/utilsPY.py
https://0xdata.atlassian.net/browse/PUBDEV-6002
> PUBDEV-6002: Fix Py test utility relying on model build index extracting from grid naming convention

- scripts/jenkins/jenkinsfiles/Jenkinsfile-Release
Fixes PyPI build and upload.
Adds option to build conda packages, upload them to S3 but without publishing them to anaconda.org.
Adds h2o.init to conda package check.
> [BUILD] Fix PyPI, minor changes.

- h2o-py/docs/tree.rst
(cherry picked from commit d464545c30bf688fc5946bcfd12380248901c06a)
> [XIA-PUBDEV-5949] Third attempt at adding Tree to python docs.

- h2o-py/h2o/estimators/estimator_base.py
- h2o-py/h2o/frame.py
move from master to release branch.
Removed dependency on numpy and pandas for frame.py
> Remove pandas/numpy as dependencies for frame.py. (#2986)

- h2o-docs/src/product/data-science/algo-params/categorical_encoding.rst
- h2o-docs/src/product/data-science/xgboost.rst
This defaults to one_hot_internal
> PUBDEV-5313: Update categorical_encoding default value in XGBoost

- h2o-docs/src/product/data-science/algo-params/categorical_encoding.rst
- h2o-docs/src/product/data-science/xgboost.rst
This defaults to one_hot_internal
> PUBDEV-5313-relxia: Update categorical_encoding default value in XGBoost

- h2o-docs/src/front/index.html
Bolded DAI UG and added a link to Python craigslist tutorial.
> Update docs site with recent changes - rel-xia

- h2o-docs/src/front/index.html
Bolded DAI UG and added a link to Python craigslist tutorial.
> Update docs site with recent changes

- README.md
- also add note on expected build time on regular machine
> Add missing step of installing python packages to README.md

- README.md
- h2o-web/README.md
- some more changes to main readme as well (missing python packages fro OSX)
> Update flow readme (rename STEAM to Flow)

- h2o-parsers/h2o-orc-parser/src/main/java/water/parser/orc/OrcParser.java
- h2o-parsers/h2o-orc-parser/src/test/java/water/parser/ParseTestORCCSV.java
- h2o-py/tests/testdir_hdfs/index.list
- h2o-py/tests/testdir_hdfs/pyunit_INTERNAL_HDFS_PUBDEV_5705_drop_columns_parser_orc_large.py
- h2o-py/tests/testdir_parser/pyunit_NOFEATURE_PUBDEV_5705_drop_columns_parser_orc_large.py
- h2o-r/tests/testdir_parser/runit_PUBDEV_5705_drop_columns_parser_orc_NOFEATURE_large.R
This PR covers work for JIRA: https://0xdata.atlassian.net/projects/PUBDEV/issues/PUBDEV-5705?filter=myopenissues
Added skipped column support to Orc parser.
Added Java/Python/R unit tests to verify correct operation.
> PUBDEV-5705: add skipped column support to ORC parser

- h2o-py/tests/testdir_algos/automl/pyunit_automl_args.py
Some flaky tests are making too many assumptions on the leaderboard: "grepping" this one instead to pick a non-SE model
> AutoML: Fixing pyunit tests relying on position of SE in leaderboard to pick the right model

- h2o-web/bower.json
> [FLOW-PUBDEV-6050] Swap precision and recall.

- h2o-r/h2o-package/R/parse.R
- h2o-r/tests/runitUtils/utilsR.R
- h2o-r/tests/testdir_parser/runit_PUBDEV_5705_drop_columns_parser_column_names_types_large.R
shortened R tests.
fixed bug in R API for column name and column type assignments.
> fixed bug in parser skipped columns

- h2o-py/h2o/backend/connection.py
- h2o-py/h2o/backend/server.py
- h2o-py/h2o/h2o.py
- h2o-py/tests/testdir_apis/H2O_Module/pyunit_h2oinit.py
- h2o-r/h2o-package/R/classes.R
- h2o-r/h2o-package/R/communication.R
- h2o-r/h2o-package/R/connection.R
Cherry picked from `master` (https://github.com/h2oai/h2o-3/commit/fbf3699f16aa8669bce30f654ad49e95ad89b2eb and https://github.com/h2oai/h2o-3/commit/cc0536848136f683625e7ee470c25c045f885992) so it can go to the next release.
Should I tag this with any more labels? Or do anything more? @michalkurka @Pscheidl
> Python/R name and log_dir/level parameters

- h2o-automl/src/main/java/ai/h2o/automl/Leaderboard.java
- h2o-automl/src/main/java/ai/h2o/automl/UserFeedback.java
- h2o-automl/src/test/java/ai/h2o/automl/LeaderboardTest.java
https://0xdata.atlassian.net/browse/PUBDEV-6065
> PUBDEV-6065: Leaderboard throws ArrayIndexOutOfBoundsException if sort_metric is specified but no model was built

- h2o-py/tests/testdir_algos/deeplearning/pyunit_offset_init_train_deeplearning.py
- h2o-py/tests/testdir_algos/gbm/pyunit_offset_init_train_gbm.py
- h2o-py/tests/testdir_algos/glm/pyunit_offset_init_train_glm.py
Fix tests to pass in Python 2.7 too.  Change dataset and deeplearning model setting test to be reproducible.
> PUBDEV-6036 fix pyunit tests.

- h2o-algos/src/main/java/hex/schemas/GLMModelV3.java
- h2o-core/src/main/java/water/api/schemas3/TwoDimTableV3.java
- h2o-py/tests/testdir_algos/glm/pyunit_PUBDEV_6062_multinomial_coeffNames.py
- h2o-r/tests/testdir_algos/glm/runit_GLM_PUBDEV_6062_cat_coeff_names.R
Move from Master to release branch
> PUBDEV-6062: fixed coefficient names to include actual class name.

- h2o-py/tests/pyunit_utils/utilsPY.py
- h2o-py/tests/testdir_algos/gbm/pyunit_PUBDEV_4090_grid_model_seeds.py
- h2o-py/tests/testdir_javapredict/pyunit_pubdev_4628_pubdev_4950_deeplearning_mojo_pojo_large.py
- h2o-r/tests/testdir_parser/runit_PUBDEV_5705_drop_columns_parser_gz.R
The following tests have been failing:
pyunit_PUBDEV_4090_grid_model_seeds.py
pyunit_pubdev_4628_pubdev_4950_deeplearning_mojo_pojo_large.py.
Also, I fix the h2o-r/tests/testdir_parser/runit_PUBDEV_5705_drop_columns_parser_gz.R which set skipp_columns to all columns and hence encounter the error. I make sure the skipped_columns will never contain all the column indices.
Incorporate Seb's suggestion to fix them.
> Fix two intermittent tests

- h2o-py/tests/testdir_algos/gbm/pyunit_grid_carsGBM.py
@maurever, please confirm validity of changes
> Build Stability: Fixing UT failing when picking multinomial distribution

- h2o-docs/src/product/data-science/if.rst
- h2o-docs/src/product/data-science/xgboost.rst
- h2o-docs/src/product/flow.rst
Do not merge until https://github.com/h2oai/h2o-3/pull/3073 is merged.
> PUBDEV-6086: Add monotone_constraints to XGBoost chapter

- h2o-py/tests/testdir_algos/automl/pyunit_automl_args.py
- h2o-r/tests/testdir_algos/automl/runit_automl_args.R
improving Build pipeline stability
> ensure all automl tests checking model properties are never picking a SE model

- h2o-core/src/main/java/water/JettyHTTPD.java
- h2o-core/src/main/java/water/server/ServletUtils.java
- needed for Flow UI development (UI server on different port than back-end)
- also removed some dead code
> [HEXDEV-724] add headers for cross-origin AJAX requests

- h2o-py/tests/testdir_javapredict/pyunit_pubdev_5058_glrm_mojo_pubdev_5470_load_model_large.py
Fix the test pyunit_pubdev_5058_glrm_mojo_pubdev_5470_load_model_large.py by
1. fixed the seed in dataframe generation;
2. fixed the seed in model generation.
> fix seeds for data generation and model building.

- README.md
- docker/Dockerfile.dev
- docker/jenkins-images/Dockerfile-build-base
- docker/jenkins-images/Dockerfile-python-base
- docker/jenkins-images/Dockerfile-r-base
- docker/setup-h2o-dev.sh
- h2o-web/bower.json
- h2o-web/build.gradle
- h2o-web/package.json
- scripts/jenkins/Makefile.jenkins
- scripts/jenkins/groovy/buildConfig.groovy
- scripts/jenkins/groovy/defineTestStages.groovy
- scripts/run.py
- remove instalation of phantomjs (not used anymore)
- update run.py to use basic node launcher
> [HEXDEV-724] build updates and cleanup

- h2o-py/tests/testdir_javapredict/pyunit_pubdev_5058_glrm_mojo_pubdev_5470_load_model_large.py
Fixed GLRM mojo/pojo intermittent test.
> fix seeds for data generation and model building. (#3086)

- h2o-py/tests/testdir_javapredict/pyunit_pubdev_4628_pubdev_4950_deeplearning_mojo_pojo_large.py
Incorporate Michal K code review comments to check error message is related to unstable model only.  For other error messages, an exception will be raised.
> Fixed DL mojo test by surrounding DL autoencoder mode with try/except.

- h2o-py/tests/testdir_algos/gbm/pyunit_gbm_PUBDEV_3847.py
- h2o-r/tests/testdir_jira/runit_pubdev_3847.R
I added a new test to check if a `gbm` model still fails with `java.lang.AssertionError: Coldata xxx out of range`.
> PUBDEV-3847 add new test defined in issue

- h2o-web/bower.json
- includes PUBDEV-6109 - fix window.open url
- and other minor webpack related bugfixes
> [FLOW] bump version to get latest fixes

- h2o-core/src/main/java/water/H2O.java
- h2o-core/src/main/java/water/init/NetworkInit.java
- h2o-core/src/main/java/water/webserver/H2OHttpViewImpl.java
- h2o-docs/src/product/api-reference.rst
- h2o-docs/src/product/security.rst
- h2o-jetty-8/src/main/java/water/webserver/jetty8/Jetty8DelegatingAuthenticator.java
- h2o-jetty-8/src/main/java/water/webserver/jetty8/Jetty8Helper.java
- h2o-jetty-9/src/main/java/water/webserver/jetty9/Jetty9DelegatingAuthenticator.java
- h2o-jetty-9/src/main/java/water/webserver/jetty9/Jetty9Helper.java
- h2o-py/h2o/auth.py
- h2o-py/h2o/h2o.py
- h2o-py/requirements.txt
- h2o-py/setup.py
- h2o-webserver-iface/src/main/java/water/webserver/iface/H2OHttpConfig.java
- h2o-webserver-iface/src/main/java/water/webserver/iface/LoginType.java
back end part done, working on Python API support
> [HEXDEV-717] enable SPNEGO authentication

- build.gradle
- gradle/apt.gradle
- h2o-core/src/main/java/water/api/SchemaServer.java
(cherry picked from commit 4a0904a25abd1d5575c2c9459a79ea379f94eecc)
> Remove unused auto-service (also bringing guava dependency)

- h2o-algos/src/main/java/hex/tree/SharedTreeModel.java
This improves performance of the multinomial case, we can install
the compressed trees into DKV asynchronously without waiting in each class.
> SharedTree improvement: install the compressed trees asynchronously

- h2o-r/demos/rdemo.NOFEATURE.xgbvarimp.R
Demonstrates the variable importance is consistant with the native xgboost
> H2O XGBoost variable importance demo

- h2o-automl/src/main/java/ai/h2o/automl/AutoML.java
- h2o-docs/src/product/automl.rst
- h2o-py/h2o/automl/autoh2o.py
- h2o-r/h2o-package/R/automl.R
https://0xdata.atlassian.net/browse/PUBDEV-6079
> PUBDEV-6079: Removing auto-creation of validation frame in AutoML

- h2o-docs/src/product/data-science/aggregator.rst
- h2o-docs/src/product/data-science/algo-params/categorical_encoding.rst
- h2o-docs/src/product/data-science/drf.rst
- h2o-docs/src/product/data-science/gbm.rst
- h2o-docs/src/product/data-science/xgboost.rst
Noted that for enum_limited, T=1024
See https://github.com/h2oai/h2o-3/blob/master/h2o-algos/src/main/java/hex/util/LinearAlgebraUtils.java#L457
> PUBDEV-6105: Doc update for enum_limited

- gradle.properties
- h2o-jetty-8/build.gradle
Updated Jetty 8 to latest fix version.
> PUBDEV-6097 - Jetty 8 updated to version 8.1.21.v20160908

- h2o-algos/src/test/java/hex/tree/gbm/GBMTest.java
- h2o-core/src/main/java/hex/Model.java
- h2o-genmodel/src/main/java/hex/genmodel/algos/gbm/GbmMojoModel.java
- h2o-genmodel/src/main/java/hex/genmodel/algos/tree/SharedTreeMojoModel.java
- h2o-genmodel/src/main/java/hex/genmodel/easy/EasyPredictModelWrapper.java
- h2o-genmodel/src/main/java/hex/genmodel/easy/prediction/AnomalyDetectionPrediction.java
- h2o-genmodel/src/main/java/hex/genmodel/easy/prediction/BinomialModelPrediction.java
- h2o-genmodel/src/main/java/hex/genmodel/easy/prediction/MultinomialModelPrediction.java
- h2o-genmodel/src/main/java/hex/genmodel/easy/prediction/RegressionModelPrediction.java
Expose prediction contributions from each tree from MOJO to `EasyPredictModelWrapper`.
JIRA: https://0xdata.atlassian.net/browse/PUBDEV-6106
> PUBDEV-6106 propagate staged probabilities to mojo

- h2o-web/bower.json
> [PUBDEV-6147] Fix download links.

- h2o-extensions/xgboost/src/main/java/hex/tree/xgboost/XGBoostModel.java
- h2o-extensions/xgboost/src/test/java/hex/tree/xgboost/XGBoostTreeConverterTest.java
[JIRA PUBDEV-6107](https://0xdata.atlassian.net/browse/PUBDEV-6107)
> PUBDEV-6107 - Regression XGBoost tree retrieval no-class validation fixed

- h2o-genmodel/src/main/java/hex/genmodel/algos/tree/SharedTreeMojoModel.java
- h2o-genmodel/src/main/java/hex/genmodel/algos/tree/SharedTreeNode.java
Tree inconsistencies will be fixed in another issue, that is a bigger effort https://0xdata.atlassian.net/browse/PUBDEV-6140
> PUBDEV-6098: Allow to visualize MOJO Trees even when they are incosistent

- h2o-core/src/main/java/water/rapids/ast/prims/advmath/AstDistance.java
- h2o-core/src/test/java/water/rapids/RapidsTest.java
[PUBDEV-6111](https://0xdata.atlassian.net/browse/PUBDEV-6111)
Simple fix of missing `Math.sqrt()` in euclidean distance. Originally reported by community.
> PUBDEV-6111 Fixed euclidean distance formula in AstDistance rapids expression

- h2o-automl/src/main/java/ai/h2o/automl/AutoML.java
https://0xdata.atlassian.net/browse/PUBDEV-6152
> PUBDEV-6152: adding readable key for cloned training frame

- docker/hadoop/cdh/Dockerfile
- docker/hadoop/cdh/scripts/sbin/install_hive.sh
- docker/hadoop/common/kerberos/00_kerberos_init
- docker/hadoop/common/startup/50_hive_start
- docker/hadoop/hdp/Dockerfile
- docker/hadoop/hdp/scripts/sbin/add_hdp_repo.sh
- docker/hadoop/hdp/scripts/sbin/generate-mapred-site
- docker/hadoop/hdp/scripts/sbin/generate-yarn-site
- docker/hadoop/hdp/scripts/sbin/install_hive.sh
- docker/hadoop/hdp/scripts/startup/40_yarn_start
- h2o-dist/buildinfo.json
- h2o-hadoop-3/h2o-hdp3.0-assembly/build.gradle
- h2o-hadoop-3/h2o-hdp3.1-assembly/build.gradle
- make-dist.sh
- scripts/jenkins/groovy/buildConfig.groovy
- scripts/jenkins/groovy/defineTestStages.groovy
- scripts/jenkins/groovy/hadoopStage.groovy
- scripts/jenkins/groovy/pipelineUtils.groovy
- settings.gradle
[PUBDEV-6146](https://0xdata.atlassian.net/browse/PUBDEV-6146)
> PUBDEV-6146 - HDP 3.0 & HDP 3.1

- h2o-web/bower.json
> [FLOW-PUBDEV-6147] Download links.

- Changes.md
- Moved rel-xia 3.20.0.4 release to below 3.22.1.1 release.
> Reordered last two releases

- docker/Jenkinsfile-build-docker
- docker/Jenkinsfile-build-hadoop-docker
- docker/Jenkinsfile-build-xgb-docker
- docker/Makefile
- docker/jenkins-images/Dockerfile-build
- docker/jenkins-images/Dockerfile-build-base
- docker/jenkins-images/Dockerfile-build-hadoop
- docker/jenkins-images/Dockerfile-jdk-8-base
- docker/jenkins-images/Dockerfile-jdk-others
- docker/jenkins-images/Dockerfile-jdk-others-base
- docker/jenkins-images/Dockerfile-python
- docker/jenkins-images/Dockerfile-python-base
- docker/jenkins-images/Dockerfile-r
- docker/jenkins-images/Dockerfile-r-base
- docker/jenkins-images/Dockerfile-release
- docker/xgb/centos/common/sbin/install_java
- docker/xgb/centos/common/sbin/install_packages
- docker/xgb/common/sbin/install_python
- docker/xgb/ubuntu/common/sbin/install_java
- docker/xgb/ubuntu/common/sbin/install_packages
- scripts/jenkins/groovy/buildConfig.groovy
* [BUILD] Move to harbor.
* [BUILD] Migrate docker/Makefile.
* [BUILD] Fix XGB Smoke images.
(cherry picked from commit 3801d4c619d1ca376da4e0aa79594f28761892a8)
> [BUILD] Move to harbor.

- docker/Jenkinsfile-build-docker
- docker/jenkins-images/Dockerfile-build-base
- docker/jenkins-images/Dockerfile-jdk-others-base
- docker/jenkins-images/Dockerfile-python-base
- docker/jenkins-images/Dockerfile-r-base
- docker/jenkins-images/Dockerfile-release
- scripts/jenkins/groovy/buildConfig.groovy
- scripts/jenkins/groovy/pipelineUtils.groovy
There are some missing deps (for Flow). R base image is not building. There is a change needed in Flow as well, update of Flow will be part of another PR.
Bump version to 7.
> [BUILD] Fix docker images

- h2o-web/bower.json
> [FLOW-PUBDEV-6192] Fix frame split.

- h2o-core/src/main/java/water/H2O.java
- h2o-core/src/main/java/water/init/AbstractBuildVersion.java
Example:
H2O_COMMIT=$(java -cp build/h2o.jar water.init.BuildVersion lastCommitHash)
LAST_COMMIT=$(git rev-parse HEAD)
if [ $LAST_COMMIT == $H2O_COMMIT ]; then
echo "h2o.jar was built using the latest commit"
else
echo "h2o.jar is not built from the latest commit"
exit 1
fi
> A simple way to get git hash out of H2O without running it

- h2o-algos/src/main/java/hex/tree/TreeHandler.java
- h2o-algos/src/test/java/hex/tree/TreeHandlerTest.java
[PUBDEV-6178](https://0xdata.atlassian.net/browse/PUBDEV-6178)
> PUBDEV-6178 - Missing split column of root node in array with descriptions in Tree API

- h2o-core/src/main/java/water/AutoBuffer.java
- h2o-core/src/main/java/water/ClientDisconnectCheckThread.java
- h2o-core/src/main/java/water/ClientRandomDisconnectThread.java
- h2o-core/src/main/java/water/H2O.java
- h2o-core/src/main/java/water/H2ONode.java
- h2o-core/src/main/java/water/MRTask.java
- h2o-core/src/main/java/water/Paxos.java
- h2o-core/src/main/java/water/RPC.java
- h2o-core/src/main/java/water/TCPReceiverThread.java
- h2o-core/src/main/java/water/UDPClientEvent.java
- h2o-core/src/main/java/water/UDPHeartbeat.java
- h2o-core/src/main/java/water/init/NetworkInit.java
- h2o-core/src/main/java/water/util/JStackCollectorTask.java
- h2o-core/src/test/java/water/ClientJarMD5IgnoreTest.java
- h2o-core/src/test/java/water/ClientReconnectSimulationTest.java
- h2o-core/src/test/java/water/ExternalFrameReaderClientTest.java
- h2o-core/src/test/java/water/ExternalFrameWriterClientTest.java
- h2o-core/src/test/java/water/UnknownHeartbeatTest.java
- h2o-py/h2o/tree/tree.py
- h2o-py/tests/testdir_tree/pyunit_tree_irf.py
- scripts/jenkins/Makefile.jenkins
- scripts/jenkins/groovy/defineTestStages.groovy
[PUBDEV-6177](https://0xdata.atlassian.net/browse/PUBDEV-6177)
The root cause will be solved in: https://0xdata.atlassian.net/browse/PUBDEV-6140
> PUBDEV-6177 - Python API no longer fails on empty/unfilled categorical levels.

- h2o-web/bower.json
> [FLOW] Multiple bugfixes.

- h2o-algos/src/test/java/hex/tree/gbm/GBMTest.java
Add test case to test last staged probability and prediction are the same.
The tests exist for Python and R API, however, it is useful to test it also in the  GBMTest.java.
> PUBDEV-6106 Add test case to test last staged probability and prediction

- h2o-automl/build.gradle
- h2o-automl/src/main/java/ai/h2o/automl/AutoML.java
- h2o-automl/testMultiNode.sh
- h2o-automl/testSingleNode.sh
- scripts/jenkins/Makefile.jenkins
- scripts/jenkins/groovy/defineTestStages.groovy
> Adds a new stage for AutoML Junit tests

- h2o-web/bower.json
This resolves following issues:
- https://0xdata.atlassian.net/projects/ITA/issues/ITA-366
- https://0xdata.atlassian.net/projects/PUBDEV/issues/PUBDEV-6222
- https://0xdata.atlassian.net/projects/PUBDEV/issues/PUBDEV-6207
Updates Flow to 0.9.7.
> [FLOW] Do not render big CM. Monotone constraints UI. Fix Flow tests.

- h2o-mapreduce-generic/src/main/java/water/hadoop/HiveTokenGenerator.java
- h2o-mapreduce-generic/src/main/java/water/hadoop/h2odriver.java
- h2o-mapreduce-generic/src/main/java/water/hadoop/h2omapper.java
> PUBDEV-6216 - always show hive token generator logs

- h2o-core/src/main/java/water/jdbc/SQLManager.java
- this improves user exprience when using thin hive jdbc driver jar
> PUBDEV-6186 - handle NoClassDefFoundError when intializing JDBC connection

- h2o-py/tests/testdir_javapredict/pyunit_pubdev_4628_pubdev_4950_deeplearning_mojo_pojo_NOPASS.py
- h2o-py/tests/testdir_javapredict/pyunit_pubdev_4628_pubdev_4950_deeplearning_mojo_pojo_autoencoder.py
Michalk reported that this test has been failing.
I have broken this test into two parts:
1. pyunit_pubdev_4628_pubdev_4950_deeplearning_mojo_pojo_autoencoder.py that only tests the autoencoder mode and this test has been passing.
2.  pyunit_pubdev_4628_pubdev_4950_deeplearning_mojo_pojo_NOPASS.py that only tests the deeplearning network.  It has been failing consistently.
> Fix pyunit_pubdev_4628_pubdev_4950_deeplearning_mojo_pojo_large.py failure

- h2o-core/src/test/java/water/rapids/ast/prims/time/AstAsDateTest.java
https://0xdata.atlassian.net/browse/PUBDEV-6189
The original issue is closed, as it was Excel showing different formatting. However, I wrote myself those two little tests :) Shall we keep them ?
> PUBDEV-6189- as_date tests

- h2o-py/h2o/targetencoder.py
- h2o-py/tests/testdir_algos/automl/target_encoding/pyunit_automl_gbm_target_encoding.py
- h2o-py/tests/testdir_algos/automl/target_encoding/pyunit_automl_target_encoding.py
1) added support for using indices for column-related parameters
2) renamed parameter for blending ( deprecated previous one)
> PUBDEV-6129 Added support for using indices when specifying column-related parameters of target encoding(Python API)

- h2o-py/h2o/targetencoder.py
Test was failing on Py2.7 stage.
> PUBDEV-5980: Fix for the test which is checking deprecation warning

- h2o-algos/src/main/java/hex/schemas/StackedEnsembleV99.java
- h2o-py/h2o/estimators/stackedensemble.py
- h2o-r/h2o-package/R/stackedensemble.R
https://0xdata.atlassian.net/browse/PUBDEV-6180
> PUBDEV-6180: fixed output of SE blending frame for rendering in Flow

- h2o-mapreduce-generic/src/main/java/water/hadoop/DelegationTokenRefresher.java
- h2o-mapreduce-generic/src/main/java/water/hadoop/DriverToMapperMessage.java
- h2o-mapreduce-generic/src/main/java/water/hadoop/EmbeddedH2OConfig.java
- h2o-mapreduce-generic/src/main/java/water/hadoop/HiveTokenGenerator.java
- h2o-mapreduce-generic/src/main/java/water/hadoop/h2odriver.java
- h2o-mapreduce-generic/src/main/java/water/hadoop/h2omapper.java
- when keytab and hive credentials are available periodically refresh hive token
> [PUBDEV-6216] - hive delegation token refresh

- h2o-web/bower.json
Update to Flow 0.9.8.
Flow PR: https://github.com/h2oai/h2o-flow/pull/128
> [FLOW-PUBDEV-6180] fixed rendering of SE base models ids.

- h2o-mapreduce-generic/src/main/java/water/hadoop/DelegationTokenRefresher.java
- h2o-mapreduce-generic/src/main/java/water/hadoop/h2odriver.java
- h2o-mapreduce-generic/src/main/java/water/hadoop/h2omapper.java
- distributed cache is not good to use since it requires the file to be on hdfs
- use our internal mechanism for distributing security files to mappers
> [PUBDEV-6274] fix hive auth keytab distribution

- h2o-docs/src/product/data-munging.rst
- h2o-docs/src/product/data-munging/tokenize.rst
- h2o-docs/src/product/data-science/word2vec.rst
- Added a data munging topic for Tokenize
- Refer to this topic in the Word2Vec section
> PUBDEV-6199: Add data munging topic for Tokenize

- h2o-core/src/main/java/hex/Model.java
- h2o-extensions/xgboost/src/main/java/hex/tree/xgboost/XGBoostModel.java
- h2o-extensions/xgboost/src/main/java/ml/dmlc/xgboost4j/java/XGBoostScoreTask.java
- h2o-extensions/xgboost/src/main/java/ml/dmlc/xgboost4j/java/XGBoostSetupTask.java
- h2o-extensions/xgboost/src/test/java/hex/tree/xgboost/XGBoostTest.java
Exposes approximate contributions to Java API audience.
These are not Tree SHAP values, these are values that are returned by XGBoost when `approx_contribs = TRUE`
> XGBoost: Java backend can calculate approximate contributions

- h2o-algos/src/main/java/hex/glm/GLM.java
- h2o-algos/src/main/java/hex/glm/GLMMetricBuilder.java
- h2o-algos/src/main/java/hex/glm/GLMModel.java
- h2o-algos/src/main/java/hex/glm/GLMMojoWriter.java
- h2o-algos/src/main/java/hex/glm/GLMScore.java
- h2o-algos/src/main/java/hex/glm/GLMTask.java
- h2o-algos/src/main/java/hex/schemas/GLMV3.java
- h2o-algos/src/test/java/hex/glm/GLMBasicTestNegativebinomial.java
- h2o-core/src/main/java/hex/Model.java
- h2o-py/h2o/estimators/glm.py
- h2o-py/tests/testdir_algos/glm/pyunit_link_functions_negbinomial_glm.py
- h2o-r/h2o-package/R/glm.R
- h2o-r/tests/testdir_algos/glm/runit_GLM_link_functions_negbinomial.R
This PR completes the tasks in JIRA: https://0xdata.atlassian.net/projects/PUBDEV/issues/PUBDEV-5925?filter=myopenissues
I have completed the following:
1. Added Negative binomial to Java backend and associated calculations;
2. Added Python/R API for negative binomial.
3. Benchmark with R;
4. Benchmark with Python;
5. Java tests to 
a. check correct gradient/hessian implementation and 
b. compare and ensure that the model/mojo/pojo predicts are equal.
> PUBDEV-5929: Added negative binomial to GLM family

- h2o-mapreduce-generic/src/main/java/water/hadoop/DelegationTokenRefresher.java
- h2o-mapreduce-generic/src/main/java/water/hadoop/HiveTokenGenerator.java
when the token acquisition fails log it and do not try to distribute credentials to other nodes
> [PUBDEV-6274] improve hive token acquisition error handling

- h2o-algos/src/main/java/hex/ensemble/Metalearner.java
- h2o-core/src/main/java/water/Job.java
- h2o-core/src/main/java/water/jdbc/SQLManager.java
- h2o-core/src/test/java/water/JobTest.java
+ improve progress reporting - Job will have info about what
is happening on the backend
> Make SQL ingest including setup fully asynchronous

- h2o-3-DESCRIPTION.template
- h2o-r/h2o-package.template
- h2o-r/h2o-package/docs/reference/h2o-package.html
- scripts/validate_r_cmd_check_output.R
Just cleaning up some files that still have Tom's email address for the package maintainer.
> Fixing R pkg maintainer name/email

- h2o-docs/src/product/performance-and-prediction.rst
- Added this under the Classification subsection of Model Metrics.
> PUBDEV-6301: Add description of AUCPR to the User Guide

- h2o-docs/src/product/automl.rst
Updates to AutoML user guide that reflect the auto partitioning changes made in this PR: https://github.com/h2oai/h2o-3/pull/3273
> PUBDEV-6254: AutoML user guide updates for auto-partitioning

- h2o-mapreduce-generic/src/main/java/water/hadoop/DelegationTokenRefresher.java
- h2o-mapreduce-generic/src/main/java/water/hadoop/HiveTokenGenerator.java
- h2o-mapreduce-generic/src/main/java/water/hadoop/h2odriver.java
- fix driver failing to start when hive driver is not on classpath (mapr)
- improve hive config acquisition of refresher-only scenario
- minor code cleanups
> [PUBDEV-6298] fixes and improvements to Hive tokens

- h2o-core/src/main/java/water/persist/PersistManager.java
- h2o-core/src/test/java/water/persist/PersistManagerTest.java
- h2o-web/bower.json
JIRA: 
https://0xdata.atlassian.net/browse/PUBDEV-6300
Depends on changes in Flow:
https://github.com/h2oai/h2o-flow/pull/130
> PUBDEV-6300 Flows throws error on an empty path while performing 'Import Files' operation

- h2o-docs/src/product/grid-search.rst
Changed
'max_depth': range(2,11),
to
'max_depth': list(range(2,11)),
> PUBDEV-6314: Fixed max_depth setting in Python Random Grid Search example

- h2o-automl/src/main/java/ai/h2o/automl/AutoML.java
- h2o-automl/src/test/java/ai/h2o/automl/AutoMLTest.java
https://0xdata.atlassian.net/browse/PUBDEV-6313
back porting fix included in PUBDEV-6254 (was required to get blending working).
added more UTs.
**Note: this will create conflicts during daily auto-merge rel-xu -> master**
> PUBDEV-6313: AutoML: missing validation frame if not provided by user when cross-validation is disabled

- scripts/jenkins/groovy/defineTestStages.groovy
- scripts/jenkins/jenkinsfiles/Jenkinsfile-Benchmarks
Execute benchmarks in separate job.
> [BUILD] Do not run benchmarks for every commit.

- h2o-docs/src/product/aws.rst
- h2o-docs/src/product/cloud-integration/ec2-and-s3.rst
- h2o-docs/src/product/howto/H2O-DevS3Creds.md
https://0xdata.atlassian.net/browse/PUBDEV-6347
The examples are re-formatted from my blogpost: https://www.pavel.cool/h2o-3/h2o-s3-credentials-change/
> PUBDEV-6347 - Update S3 documentation for 3.22.x

- h2o-py/tests/testdir_algos/glm/pyunit_PUBDEV_6349_negbinomial_gridsearch.py
This PR completes the work in JIRA: https://0xdata.atlassian.net/projects/PUBDEV/issues/PUBDEV-6349?filter=allopenissues .
I added a pyunit test to make sure GLM negative binomial family works.
> PUBDEV-6349: added gridsearch example for GLM negative binomial family.

- h2o-algos/src/main/java/hex/glm/ComputationState.java
- h2o-py/tests/testdir_algos/glm/pyunit_PUBDEV_6349_negbinomial_gridsearch.py
This PR fix the bug described in JIRA: https://0xdata.atlassian.net/browse/PUBDEV-6349?filter=myopenissues
Fixed unknown family issue when using gridsearch and lambda_search = True for GLM negative binomial.
> Pubdev 6349 glm negbinomial gridsearch

- h2o-automl/src/main/java/ai/h2o/automl/Algo.java
- h2o-automl/src/main/java/ai/h2o/automl/AutoML.java
- h2o-automl/src/main/java/ai/h2o/automl/AutoMLBuildSpec.java
- h2o-automl/src/main/java/water/automl/api/schemas3/AutoMLBuildSpecV99.java
- h2o-automl/src/test/java/ai/h2o/automl/AutoMLTest.java
- h2o-docs/src/product/automl.rst
- h2o-py/h2o/automl/autoh2o.py
- h2o-py/tests/testdir_algos/automl/pyunit_automl_args.py
- h2o-r/h2o-package/R/automl.R
- h2o-r/tests/testdir_algos/automl/runit_automl_args.R
https://0xdata.atlassian.net/projects/PUBDEV/issues/PUBDEV-6196
this is a client-only feature
> PUBDEV-6196: expose include_algos parameter to AutoML Py+R clients

- h2o-hadoop-common/tests/python/pyunit_gbm_on_hive.py
- h2o-hadoop-common/tests/python/pyunit_hive_jdbc_import.py
- scripts/jenkins/Makefile.jenkins
- scripts/jenkins/groovy/buildConfig.groovy
- scripts/jenkins/groovy/defineTestStages.groovy
- scripts/jenkins/groovy/hadoopCommands.groovy
- scripts/jenkins/groovy/hadoopStage.groovy
- scripts/jenkins/groovy/kerberosCommands.groovy
- scripts/jenkins/jenkinsfiles/Jenkinsfile-Kerberos
remove KRB testing from hadoop-smoke-job, only test these cases on some hadoop builds
add tests for hadoop driver on kerberos
> [PUBDEV-6269] Test for kerberized hive + kerberos test refactor

- h2o-algos/src/main/java/hex/ensemble/StackedEnsemble.java
- h2o-algos/src/test/java/hex/ensemble/StackedEnsembleTest.java
https://0xdata.atlassian.net/browse/PUBDEV-6208
applying fix from https://github.com/h2oai/h2o-3/pull/3350 to rel-xu
> PUBDEV-6208: SE Model deletion can lead to removal of shared vecs (rel-xu port)

- h2o-mapreduce-generic/src/main/java/water/hadoop/HiveTokenGenerator.java
[PUBDEV-6363](https://0xdata.atlassian.net/browse/PUBDEV-6363)
- it never really worked for hiveHost (the config value used does something else)
> [PUBDEV-6363] remove support for getting hive config from hive-site.xml

- h2o-extensions/xgboost/src/main/java/hex/tree/xgboost/XGBoostModel.java
- h2o-extensions/xgboost/src/test/java/biz/k11i/xgboost/tree/XgbPredictContribsTest.java
- h2o-genmodel-extensions/xgboost/build.gradle
- h2o-genmodel-extensions/xgboost/src/main/java/hex/genmodel/algos/xgboost/XGBoostMojoModel.java
- h2o-genmodel/build.gradle
- h2o-genmodel/src/main/java/hex/genmodel/algos/tree/TreeSHAP.java
This is not surfaced in public APIs yet
> Add the experimental TreeSHAP implementation to genmodel

- h2o-r/tests/testdir_algos/automl/runit_automl_args.R
https://0xdata.atlassian.net/browse/PUBDEV-6196
> PUBDEV-6196: activating and fixing R UTs

- h2o-algos/src/test/java/hex/tree/gbm/GBMPredictContribsTest.java
- h2o-algos/src/test/java/hex/util/NaiveTreeSHAP.java
- h2o-extensions/xgboost/build.gradle
- h2o-extensions/xgboost/src/test/java/biz/k11i/xgboost/tree/NaiveTreeSHAP.java
- h2o-extensions/xgboost/src/test/java/biz/k11i/xgboost/tree/XgbPredictContribsTest.java
- h2o-genmodel/src/main/java/hex/genmodel/algos/tree/SharedTreeNode.java
- h2o-genmodel/src/main/java/hex/genmodel/algos/tree/SharedTreeSubgraph.java
@Pscheidl this is not exposed to the users just yet - only internal implementation at this point.
> PUBDEV-6056: TreeSHAP for GBM Trees

- docker/hadoop/common/hive-scripts/01_create_test_tables.hql
- h2o-core/src/main/java/water/api/ImportSQLTableHandler.java
- h2o-core/src/main/java/water/api/schemas3/ImportSQLTableV99.java
- h2o-core/src/main/java/water/jdbc/SQLManager.java
- h2o-core/src/test/java/water/jdbc/SQLManagerIntegTest.java
- h2o-core/src/test/java/water/jdbc/SQLManagerTest.java
- h2o-core/src/test/java/water/parser/ImportSQLTest.java
- h2o-hadoop-common/tests/R/runit_hive_jdbc_import.R
- h2o-hadoop-common/tests/python/pyunit_hive_jdbc_import.py
- h2o-py/h2o/h2o.py
- h2o-r/h2o-package/R/import.R
- scripts/jenkins/Makefile.jenkins
- scripts/jenkins/groovy/buildConfig.groovy
- parameter to disable temporary table creation
- paramtere to specify temporary table name
> [PUBDEV-6358] add ability to drive JDBC import temporary table via API

- h2o-bindings/build.gradle
rebased https://github.com/h2oai/h2o-3/pull/2942 from @Sloug onto current master
> PUBDEV-5993 - updated Retrofit and okHttp dependecies

- h2o-automl/src/main/java/ai/h2o/automl/AutoML.java
- h2o-automl/src/main/java/ai/h2o/automl/AutoMLBuildSpec.java
- h2o-automl/src/main/java/ai/h2o/automl/UserFeedback.java
- h2o-automl/src/main/java/water/automl/api/AutoMLBuilderHandler.java
- h2o-automl/src/main/java/water/automl/api/schemas3/AutoMLBuildSpecV99.java
- h2o-automl/src/main/resources/META-INF/services/water.api.Schema
- h2o-automl/src/test/java/ai/h2o/automl/AutoMLTest.java
- h2o-core/src/main/java/hex/grid/HyperSpaceSearchCriteria.java
- h2o-core/src/main/java/water/util/Countdown.java
- h2o-docs/src/product/automl.rst
- h2o-py/h2o/automl/autoh2o.py
- h2o-py/tests/testdir_algos/automl/pyunit_automl_args.py
- h2o-r/h2o-package/R/automl.R
- h2o-r/tests/testdir_algos/automl/runit_automl_args.R
https://0xdata.atlassian.net/browse/PUBDEV-5809
also see PR https://github.com/h2oai/h2o-3/pull/3218 for core changes required to ensure that each individual model will respect this time constraint, especially when doing cross-validation.
> PUBDEV-5809: AutoML expose max_runtime_per_model property

- h2o-core/src/main/java/water/parser/ParseDataset.java
- h2o-py/tests/testdir_parser/pyunit_PUBDEV_6368_parser_svmlight_large.py
This PR fixes the bug in JIRA: https://0xdata.atlassian.net/browse/PUBDEV-6368?filter=-1
Fixed the bug in ParseDataset.java.
Added pyunit test to make sure my fix works.
> PUBDEV-6368: Fixed null pointer error in parseDataset.java

- h2o-core/src/main/java/water/fvec/CategoricalWrappedVec.java
- h2o-core/src/test/java/water/fvec/CategoricalWrappedVecTest.java
https://0xdata.atlassian.net/browse/PUBDEV-6379
ensure BAD Vecs are adapted to another bad Vec
> PUBDEV-6379: fixed CategoricalWrapperVec handling of BAD state.

- h2o-algos/src/main/java/hex/DataInfo.java
- h2o-extensions/xgboost/src/main/java/hex/tree/xgboost/XGBoostModel.java
- h2o-extensions/xgboost/src/main/java/hex/tree/xgboost/XGBoostUtils.java
- h2o-extensions/xgboost/src/main/java/ml/dmlc/xgboost4j/java/XGBoostModelInfo.java
- h2o-extensions/xgboost/src/main/java/ml/dmlc/xgboost4j/java/XGBoostScoreTask.java
- h2o-extensions/xgboost/src/main/java/ml/dmlc/xgboost4j/java/XGBoostSetupTask.java
- h2o-extensions/xgboost/src/test/java/hex/tree/xgboost/XGBoostTest.java
https://0xdata.atlassian.net/browse/PUBDEV-6357
> PUBDEV-6357: Categorical value out of bounds error when calling model using Python

- h2o-core/src/main/java/water/parser/ParseDataset.java
- h2o-docs/src/product/data-science/generic.rst
- h2o-py/tests/testdir_parser/pyunit_PUBDEV_6368_parser_svmlight_large.py
JIRA: [https://0xdata.atlassian.net/browse/PUBDEV-6378](https://0xdata.atlassian.net/browse/PUBDEV-6378)
JIRA: [PUBDEV-6136](https://0xdata.atlassian.net/browse/PUBDEV-6136)
GitHub PullRequest: https://github.com/h2oai/h2o-3/pull/3274
> PUBDEV-6378 - Generic model release notes (PUBDEV-6136)

- scripts/jenkins/Makefile.jenkins
- R does not support kerberos authentication used in this mode
> [BUILD] do not run R tests in kerberos-standalone

- h2o-py/h2o/frame.py
- h2o-py/tests/testdir_jira/pyunit_pubdev_6360.py
- remove blocks catching and ignoring errors
- add test for the behavior
> [PUBDEV-6360] improve error message when df manipulation fails

- h2o-docs/src/product/performance-and-prediction.rst
Also added a small section for staged_predict_proba.
> PUBDEV-6375: Add section for predict contributions in Predict topic

- h2o-py/h2o/model/metrics_base.py
- h2o-py/tests/testdir_misc/pyunit_make_metrics.py
- h2o-r/h2o-package/R/models.R
- h2o-r/tests/testdir_misc/runit_make_metrics.R
https://0xdata.atlassian.net/browse/PUBDEV-6350
> PUBDEV-6350: fixed rendering of multiple Confusion Matrices when using Py and R clients

- docker/hadoop/common/conf-hive-kerberos/hive-site.xml
- docker/hadoop/common/conf-hive/hive-site.xml
- docker/hadoop/hdp/scripts/sbin/install_hive.sh
- scripts/jenkins/groovy/buildConfig.groovy
- on 2.2 issues with access righhts, disable hive impersonation everywhere
- on 2.3,4,5 the classpath for hive jdbc is missing xerces impl add it manually
> [BUILD] fix hadoop tests on some hdp2.x builds

- h2o-docs/src/product/automl.rst
- h2o-docs/src/product/data-science/algo-params/blending_frame.rst
https://0xdata.atlassian.net/browse/PUBDEV-6254
> PUBDEV-6254: AutoML adding blending_frame param to doc

- h2o-core/src/main/java/water/AbstractH2OExtension.java
- h2o-core/src/main/java/water/ExtensionManager.java
- h2o-core/src/main/java/water/H2O.java
- h2o-core/src/main/java/water/init/NetworkInit.java
- h2o-core/src/main/java/water/util/Log.java
- h2o-extensions/xgboost/src/main/java/hex/api/xgboost/RegisterRestApi.java
- h2o-extensions/xgboost/src/main/java/hex/tree/xgboost/XGBoostExtension.java
Fixes a race condition - logging sometimes starts before the port is known, this results in very confusing output on some deployments
> PUBDEV-6372: Logging fixes and improvements

- h2o-mapreduce-generic/src/main/java/water/hadoop/h2omapper.java
This affects logs and other temporary file H2O is using.
> PUBDEV-6409: Make sure H2O Hadoop writes only to its container directory

- h2o-extensions/xgboost/src/test/java/hex/tree/xgboost/DMatrixDemoTest.java
There is no need to iterate over the whole matrix, the main diagonal is sufficient.
> Walking only the main diagonal when creating identity matrix.

- h2o-core/src/test/java/water/TestUtil.java
- h2o-core/src/test/java/water/fvec/TestFrameBuilder.java
- h2o-extensions/xgboost/src/main/java/hex/tree/xgboost/XGBoostUtils.java
- h2o-extensions/xgboost/src/test/java/hex/tree/xgboost/XGBoostUtilsTest.java
[JIRA - PUBDEV-6377](https://0xdata.atlassian.net/browse/PUBDEV-6377)
Please also visit [Benchmarks](http://mr-0xc1:8080/view/H2O-3/job/h2o-3-benchmark-pipeline/job/pavel_pubdev-6377/) to see the performance impact of these changes.
> PUBDEV-6377 - Filling of sparse DMatrix data

- h2o-core/src/test/java/water/TestUtil.java
A simple pull request making the documentation of TestUtil method I created earlier more precise. The contract was not defined that precisely :)
> More precise JavaDoc for compareFrames method in TestUtil class

- h2o-automl/src/main/java/ai/h2o/automl/targetencoding/TargetEncoder.java
- h2o-core/src/main/java/water/rapids/ast/prims/mungers/AstGroup.java
AstGroup is a singleton and mutating and field on the instance can lead
to unpredicteable crashes.
> PUBDEV-6433: Running concurrent Group-By operations can lead to errors

- h2o-web/package.json
> [flow] update fiction npm to latest

- make-dist.sh
> fixed md5 generation for h2o.jar for cran

- h2o-py/test-requirements.txt
(security vulnerability found in urllib < 1.24.2)
> Update version urllib to 1.24.2

- h2o-algos/src/main/java/hex/DataInfo.java
- h2o-algos/src/main/java/hex/svm/IncompleteCholeskyFactorization.java
- h2o-algos/src/main/java/hex/svm/Kernel.java
- h2o-algos/src/test/java/hex/DataInfoTest.java
- h2o-algos/src/test/java/hex/svm/IncompleteCholeskyFactorizationTest.java
- h2o-algos/src/test/java/hex/svm/KernelTest.java
- h2o-core/src/main/java/water/H2O.java
- h2o-core/src/test/java/water/ScopeTracker.java
- h2o-core/src/test/java/water/TestFrameCatalog.java
- h2o-core/src/test/java/water/TestUtil.java
Implementation of row-based Incomplete Cholesky Factorization based on paper https://static.googleusercontent.com/media/research.google.com/en//pubs/archive/34638.pdf
This is a pre-processing step for the future implementation of distributed SVM
> Incomplete Cholesky Factorization

- Changes.md
- rel-vapnik was previously an unannounced release
- Adding this change to master branch so that Erin can link to master in her paper.  I can cherry-pick this into rel-yates
- minor fixes to other noticeable issues
> PUBDEV-6444: Add rel-vapnik entry to changes.md file

- h2o-py/tests/testdir_jira/pyunit_pubdev_6431_deleted_key.py
- h2o-r/tests/testdir_jira/runit_pubdev_6431_deleted_key.R
> [PUBDEV-6431] fix python test

- h2o-algos/src/test/java/hex/tree/gbm/GBMTest.java
- h2o-core/src/main/java/hex/Model.java
- h2o-genmodel/src/main/java/hex/genmodel/GenModel.java
- h2o-genmodel/src/main/java/hex/genmodel/IGenModel.java
- h2o-genmodel/src/main/java/hex/genmodel/ModelDescriptor.java
- h2o-genmodel/src/main/java/hex/genmodel/MojoPipelineWriter.java
- h2o-genmodel/src/main/java/hex/genmodel/descriptor/ModelDescriptorBuilder.java
> PUBDEV-6450: Method for getting a list of features from a trained model

- h2o-py/h2o/__init__.py
- h2o-py/h2o/h2o.py
- h2o-py/tests/testdir_generic_model/pyunit_mojo_import.py
- h2o-r/h2o-package/R/models.R
- h2o-r/tests/testdir_algos/generic/runit_generic_mojo_convenience.R
https://0xdata.atlassian.net/browse/PUBDEV-6435
Goals of this PR: 
- Offer convenience methods to import MOJO and create a Generic model out of it
- Make upload from local filesystem available
- Print details about the imported model (there might not be much available right now, if anything, being solved in other PRs)
- Python & R
- Write tests
> PUBDEV-6435 - MOJO import convenience methods

- h2o-core/src/main/java/water/util/GetLogsFromNode.java
This PR simplifies the directory structure of logs within downloaded zip archives.
Before:
```
Archive:  node0_172.17.0.2_54321.zip
Length      Date    Time    Name
---------  ---------- -----   ----
13101  2019-04-29 12:41   /var/lib/hadoop-yarn/cache/yarn/nm-local-dir/usercache/jenkins/appcache/application_1556530619959_0010/container_1556530619959_0010_01_000002/tmp/h2ologs/h2o_172.17.0.2_54321-3-info.log
631  2019-04-29 12:40   /var/lib/hadoop-yarn/cache/yarn/nm-local-dir/usercache/jenkins/appcache/application_1556530619959_0010/container_1556530619959_0010_01_000002/tmp/h2ologs/h2o_172.17.0.2_54321-httpd.log
0  2019-04-29 12:36   /var/lib/hadoop-yarn/cache/yarn/nm-local-dir/usercache/jenkins/appcache/application_1556530619959_0010/container_1556530619959_0010_01_000002/tmp/h2ologs/h2o …
```
> PUBDEV-6419: Flatten out h2o-3 logs directory structure

- h2o-core/src/main/java/water/util/GetLogsFromNode.java
This PR simplifies the directory structure of logs within downloaded zip archives.
Before:
```
Archive:  node0_172.17.0.2_54321.zip
Length      Date    Time    Name
---------  ---------- -----   ----
13101  2019-04-29 12:41   /var/lib/hadoop-yarn/cache/yarn/nm-local-dir/usercache/jenkins/appcache/application_1556530619959_0010/container_1556530619959_0010_01_000002/tmp/h2ologs/h2o_172.17.0.2_54321-3-info.log
631  2019-04-29 12:40   /var/lib/hadoop-yarn/cache/yarn/nm-local-dir/usercache/jenkins/appcache/application_1556530619959_0010/container_1556530619959_0010_01_000002/tmp/h2ologs/h2o_172.17.0.2_54321-httpd.log
0  2019-04-29 12:36   /var/lib/hadoop-yarn/cache/yarn/nm-local-dir/usercache/jenkins/appcache/application_1556530619959_0010/container_1556530619959_0010_01_000002/tmp/h2ologs/h2o …
```
> PUBDEV-6419: [rel-yates] Flatten out h2o-3 logs directory structure

- h2o-core/build.gradle
This version of Javassist fixes a race condition on Java 11
> Upgrade Javassist to 3.25.0-GA

- h2o-extensions/xgboost/src/main/java/hex/tree/xgboost/XGBoost.java
For the most common use case - backend=auto and gpu_id=0 (default)
If we find out GPU 0 is not present blacklist it and never try to detect
its availablity again.
> XGBoost: Avoid repeated detection of (default) GPU

- h2o-core/src/main/java/water/H2O.java
- h2o-core/src/test/java/water/TestUtil.java
- h2o-extensions/xgboost/src/main/java/hex/tree/xgboost/BoosterParms.java
- h2o-extensions/xgboost/src/test/java/hex/tree/xgboost/XGBoostParamsTest.java
https://0xdata.atlassian.net/browse/PUBDEV-6471
My proposal for a fix. I remember fixing this issue long time ago, long before this method was introduced (October last year is what git says). Looks like this new piece of code broke it again.
> PUBDEV-6471 - XGBoost Error: Some trailing characters could not be parsed

- h2o-r/tests/runitUtils/utilsR.R
I added more print out to check test progress and hope this can shed some light on the test failure.
> Investigate runit_PUBDEV_5705_drop_columns_parser_arff_large.R failure

- h2o-r/tests/testdir_algos/coxph/runit_coxph_heart.R
Related change in the survival package:
https://github.com/therneau/survival/blame/d38f2d104383b280f6fc74838a0605f4845062d4/R/print.summary.coxph.S#L44
> Fix expected output of CoxPH summary

- h2o-extensions/xgboost/src/main/java/hex/tree/xgboost/XGBoostUtils.java
Added a change requested in
https://github.com/h2oai/h2o-3/pull/3508#discussion_r285330006
> XGBoostUtils: Incorporate @pscheidl code review comment to #3508

- h2o-genmodel-extensions/xgboost/build.gradle
https://github.com/h2oai/xgboost/pull/72
> Upgrade to XGBoost 0.82.20 - compatibility release with Java 12 [rel-yates]

- h2o-automl/src/main/java/ai/h2o/automl/Algo.java
- h2o-automl/src/main/java/ai/h2o/automl/AutoML.java
- h2o-automl/src/test/java/ai/h2o/automl/AutoMLTest.java
https://0xdata.atlassian.net/browse/PUBDEV-6512
ensure that Java UTs take into consideration the fact that algos are enabled or not
> PUBDEV-6512: Fix and reenable AutoML Java UT in multinode env

- h2o-docs/src/product/getting-data-into-h2o.rst
- also document fetch_mode option
> [PUBDEV-6358] add new import_sql_select options to docs

- h2o-core/src/main/java/water/fvec/Frame.java
- h2o-core/src/test/java/water/fvec/FrameTest.java
Please let me know if you have better name for the methods, to fit nicer into the h2o. Thanks!
> [PUBDEV-6519] Add a user friendly helper function for column type conversion

- h2o-r/h2o-package/R/targetencoder.R
- h2o-r/tests/testdir_misc/runit_target_encode_java.R
This PR is supposed to improve user experience of R Target Encoding API by validation of parameters and providing meaningful errors and warnings
> PUBDEV-6508: Added validation of parameters for R Target Encoding API

- h2o-py/h2o/targetencoder.py
- h2o-py/tests/testdir_algos/automl/target_encoding/pyunit_automl_target_encoding.py
Purpose of this PR is to match changes in R's client validation
> PUBDEV-6527: Improved user's experience with Target Encoding in Python.

- h2o-r/h2o-package/R/targetencoder.R
- h2o-r/tests/testdir_misc/runit_target_encode_java.R
For now I've set default values to the ones that DAI is using but I'm waiting for an update from @meganjkurka about the values.
@angela0xdata this PR if merged will require some changes in docs
> PUBDEV-6525: Set default values for R's API of Target Encoding

- h2o-web/bower.json
> [PUBDEV-6533] fix NaN undefined in flow cluster status

- scripts/jenkins/groovy/buildConfig.groovy
> [PUBDEV-6528] do not test xgboost on ubuntu 14 GPU

- h2o-extensions/xgboost/src/main/java/hex/tree/xgboost/XGBoost.java
- h2o-extensions/xgboost/src/main/java/hex/tree/xgboost/XGBoostUtils.java
- h2o-extensions/xgboost/src/main/java/hex/tree/xgboost/matrix/DenseMatrixFactory.java
- h2o-extensions/xgboost/src/main/java/hex/tree/xgboost/matrix/SparseMatrixFactory.java
- h2o-extensions/xgboost/src/main/java/hex/tree/xgboost/util/FeatureScore.java
- h2o-extensions/xgboost/src/test/java/hex/tree/xgboost/XGBoostTest.java
- h2o-extensions/xgboost/src/test/java/hex/tree/xgboost/XGBoostUtilsTest.java
just moving code around, no changes done
> [PUBDEV-6510] further refactor xgboost utils

- h2o-algos/src/test/java/hex/pdp/PartialDependenceTest.java
- h2o-core/src/main/java/hex/PartialDependence.java
- h2o-core/src/main/java/water/api/schemas3/PartialDependenceV3.java
- h2o-py/h2o/model/model_base.py
- h2o-py/tests/testdir_misc/pyunit_partial_plots.py
- h2o-r/h2o-package/R/models.R
- h2o-r/tests/testdir_misc/runit_partialPlot.R
* This PR introduces a `row_index` parameter to PDP, which would allow partial dependence to be calculated for a row, i.e., Individual Conditional Expectation (ICE: https://arxiv.org/abs/1309.6392).
* TODO:
> PUBDEV-6543: Add row_index parameter to PDP

- h2o-core/src/main/java/water/rapids/ast/prims/mungers/AstAsFactor.java
- h2o-core/src/main/java/water/util/VecUtils.java
- h2o-py/h2o/h2o.py
- h2o-py/tests/testdir_jira/pyunit_pubdev_6534_missing_values_rbind.py
- conversion to string is straigt forward as the code already supports it
- conversion to enum done via tostring->toenum
I am sure I am missing something why this is not a good idea (other than toEnum(toString()) being inefficient). Am I?
> [PUBDEV-6534] allow vec type conversion from T_BAD

- h2o-extensions/xgboost/src/main/java/hex/tree/xgboost/XGBoostUtils.java
- h2o-extensions/xgboost/src/main/java/hex/tree/xgboost/matrix/MatrixFactoryUtils.java
- h2o-extensions/xgboost/src/main/java/hex/tree/xgboost/matrix/SparseMatrixFactory.java
continuation of https://github.com/h2oai/h2o-3/pull/3567/files
checked, no measurable impact on performance
> [PUBDEV-6552] small improvements to xgboost parallel matrix population

- h2o-core/src/test/java/water/fvec/TestFrameBuilder.java
https://0xdata.atlassian.net/browse/PUBDEV-6550
Error message fix for otherwise approved JIRA.
> PUBDEV-6550 Fixed TestFrameBuilder BAD vec error message

- h2o-r/tests/testdir_algos/glm/runit_GLM_interactions_valid_large.R
relaxed error threshold from 0.01 to 0.1
> fix_interactions_valid_large_error

- scripts/jenkins/groovy/buildConfig.groovy
http://mr-0xc1:8080/view/H2O-3/job/docker-images/job/h2o-3-hadoop-docker-build/194/ all green :vertical_traffic_light: 
The tests with version 64 of the image: http://mr-0xc1:8080/view/H2O-3/job/h2o-3-hadoop-smoke-pipeline/job/pavel%252Fpubdev-6556-hdp-docker/1/
> PUBDEV-6556 - Hadoop docker version

- h2o-py/tests/testdir_apis/H2O_Module/pyunit_h2oremove_all.py
https://0xdata.atlassian.net/browse/PUBDEV-6562
> PUBDEV-6562 - Use method inspection compatible with Py 2&3 when inspecting h2o.removeAll()

- h2o-docs/src/product/starting-h2o.rst
Added a new section that includes suggestions for best practices when starting H2O.
> PUBDEV-6392: Best practices when starting H2O

- h2o-py/h2o/targetencoder.py
- h2o-py/tests/testdir_algos/automl/target_encoding/pyunit_automl_target_encoding.py
This PR is a cherry-pick from a [PR](https://github.com/h2oai/h2o-3/pull/3440) that was already merged into master.
> PUBDEV-6432 Added support for single te column as string or index in Py TE API

- h2o-core/src/main/java/water/server/ServletUtils.java
https://0xdata.atlassian.net/browse/PUBDEV-6584
> PUBDEV-6584: Fixing XSS headers, raising errors in Flow

- h2o-algos/src/main/java/hex/DataInfo.java
- h2o-algos/src/main/java/hex/FrameTask.java
- h2o-algos/src/main/java/hex/api/RegisterAlgos.java
- h2o-algos/src/main/java/hex/schemas/SVMModelV3.java
- h2o-algos/src/main/java/hex/schemas/SVMV3.java
- h2o-algos/src/main/java/hex/svm/IncompleteCholeskyFactorization.java
- h2o-algos/src/main/java/hex/svm/Kernel.java
- h2o-algos/src/main/java/hex/svm/LLMatrix.java
- h2o-algos/src/main/java/hex/svm/PrimalDualIPM.java
- h2o-algos/src/main/java/hex/svm/SVM.java
- h2o-algos/src/main/java/hex/svm/SVMModel.java
- h2o-algos/src/main/java/hex/svm/SupportVector.java
- h2o-algos/src/main/resources/META-INF/services/water.api.Schema
- h2o-algos/src/test/java/hex/svm/PrimalDualIPMTest.java
- h2o-algos/src/test/java/hex/svm/SVMTest.java
- h2o-bindings/bin/gen_R.py
- h2o-bindings/bin/gen_python.py
- h2o-core/src/main/java/hex/ModelBuilder.java
- h2o-core/src/main/java/water/util/ArrayUtils.java
- h2o-genmodel/src/main/java/hex/genmodel/algos/h2osvm/KernelParameters.java
- h2o-genmodel/src/main/java/hex/genmodel/algos/h2osvm/KernelType.java
- h2o-genmodel/src/main/java/hex/genmodel/algos/h2osvm/ScorerFactory.java
- h2o-genmodel/src/main/java/hex/genmodel/algos/h2osvm/SupportVectorScorer.java
- py/testdir_multi_jvm/test_rest_api.py
@wendycwong still WIP; but more or less in the shape I want it to be
This PR is not the last one, missing features and missing py/r client integration will come later.
> PUBDEV-6134: Adding SVM as a Model

- h2o-algos/src/test/java/hex/mojo/PredictCsvTest.java
- h2o-genmodel/src/main/java/hex/genmodel/tools/PredictCsv.java
https://0xdata.atlassian.net/browse/PUBDEV-6547
Example output for `pyunit_mojo_predict`:
```
Performing Regression Prediction using MOJO @... /tmp/tmpgq6plyzm
There were 1 missing columns found in the input data set: {CAPSULE}
Detected 7 unused columns in the input data set: {VOL,GLEASON,RACE,DCAPS,DPROS,AGE,PSA}
Prediction result: [OrderedDict([('predict', '0.8767707217617102')])]
gbm Model Build progress: |███████████████████████████████████████████████| 100%
gbm prediction progress: |████████████████████████████████████████████████| 100%
Binomial prediction: p0: 0.06610005816876963
Binomial prediction: p1: 0.9338999418312304
Downloading MOJO @... /tmp/tmpgq6plyzm
=> /tmp/tmpgq6plyzm/prostate_gbm_model.zip  (70196 bytes)
Time taken = 0.074s
=> /tmp/tmpgq6plyzm/prostate_gbm_model.zip …
```
> PUBDEV-6547 - Provide warning when using MOJO prediction and test/validation dataset has missing columns

- h2o-dist/index.html
Added Conda installation instructions to the downloads page
> PUBDEV-6582: Added Conda installation instructions for download

- h2o-algos/src/main/java/hex/svm/MetricBuilderSVM.java
- h2o-algos/src/main/java/hex/svm/SVMModel.java
- h2o-algos/src/test/java/hex/svm/SVMTest.java
- h2o-core/src/main/java/hex/AUC2.java
- h2o-core/src/test/java/hex/AUCBuilderTest.java
- h2o-core/src/test/java/hex/ConfusionMatrixTest.java
SVM doesn't generate probabilities, we provide a custom builder to make it
fit into H2O's framework and re-use existing code base
> SVM Metric Builder

- h2o-core/src/main/java/water/api/FramesHandler.java
- h2o-core/src/main/java/water/api/schemas3/FramesV3.java
- h2o-core/src/main/java/water/fvec/Frame.java
- h2o-core/src/main/java/water/util/CompressionFactory.java
- h2o-core/src/main/java/water/util/FrameUtils.java
- h2o-core/src/test/java/org/python/apache/commons/compress/compressors/bzip2/BZip2CompressorOutputStream.java
- h2o-core/src/test/java/org/xerial/snappy/SnappyOutputStream.java
- h2o-core/src/test/java/water/util/CompressionFactoryTest.java
- h2o-hadoop-common/tests/python/pyunit_export_compressed.py
- h2o-py/h2o/h2o.py
- h2o-py/tests/testdir_misc/pyunit_export_gzip.py
- h2o-r/h2o-package/R/export.R
- h2o-r/tests/testdir_misc/runit_export_file_gzip.R
https://0xdata.atlassian.net/browse/PUBDEV-6530
> PUBDEV-6530: Add an option to export CSV compressed by gzip

- h2o-extensions/xgboost/src/test/java/hex/tree/xgboost/DefaultMojoImplTest.java
- h2o-genmodel-extensions/xgboost/build.gradle
- update to latest xgboost
- uncomment test
> [PUBDEV-6387] fix gblinear segfault in XGBoost

- h2o-genmodel/src/main/java/hex/genmodel/ModelDescriptor.java
- h2o-genmodel/src/main/java/hex/genmodel/descriptor/ModelDescriptorBuilder.java
- h2o-genmodel/src/main/java/hex/genmodel/descriptor/Table.java
- h2o-genmodel/src/main/java/hex/genmodel/descriptor/VariableImportances.java
Removed several unused imports.
> Removed unused Serializable imports from GenModel

- h2o-algos/src/jmh/java/hex/svm/SupportVectorScorerBench.java
- h2o-algos/src/jmh/java/water/fvec/C8DVolatileChunkHelper.java
- h2o-algos/src/main/java/hex/schemas/SVMModelV3.java
- h2o-algos/src/main/java/hex/schemas/SVMV3.java
- h2o-algos/src/main/java/hex/svm/BulkScorerFactory.java
- h2o-algos/src/main/java/hex/svm/BulkSupportVectorScorer.java
- h2o-algos/src/main/java/hex/svm/SVM.java
- h2o-algos/src/main/java/hex/svm/SVMModel.java
- h2o-algos/src/main/java/hex/svm/psvm/PrimalDualIPM.java
- h2o-algos/src/test/java/hex/svm/SVMTest.java
- h2o-algos/src/test/java/hex/svm/psvm/PrimalDualIPMTest.java
- h2o-py/h2o/estimators/svm.py
- h2o-py/h2o/model/model_base.py
- h2o-py/tests/testdir_algos/svm/pyunit_svm_airlines.py
- h2o-py/tests/testdir_algos/svm/pyunit_svm_smoke.py
- h2o-py/tests/testdir_algos/svm/pyunit_svm_svmguide1.py
- h2o-py/tests/testdir_algos/svm/pyunit_svm_svmguide3.py
To avoid predicting with models that are too large
> SVM: Calculating training metrics is disabled by default

- h2o-bindings/bin/gen_python.py
- h2o-py/h2o/automl/autoh2o.py
- h2o-py/h2o/estimators/aggregator.py
- h2o-py/h2o/estimators/deeplearning.py
- h2o-py/h2o/estimators/deepwater.py
- h2o-py/h2o/estimators/estimator_base.py
- h2o-py/h2o/estimators/gbm.py
- h2o-py/h2o/estimators/generic.py
- h2o-py/h2o/estimators/glm.py
- h2o-py/h2o/estimators/glrm.py
- h2o-py/h2o/estimators/isolation_forest.py
- h2o-py/h2o/estimators/kmeans.py
- h2o-py/h2o/estimators/naive_bayes.py
- h2o-py/h2o/estimators/pca.py
- h2o-py/h2o/estimators/random_forest.py
- h2o-py/h2o/estimators/stackedensemble.py
- h2o-py/h2o/estimators/svd.py
- h2o-py/h2o/estimators/word2vec.py
- h2o-py/h2o/estimators/xgboost.py
- h2o-py/h2o/frame.py
- h2o-py/tests/testdir_algos/automl/pyunit_automl_args.py
- h2o-py/tests/testdir_algos/stackedensemble/pyunit_stackedensemble_blending_frame.py
- h2o-py/tests/testdir_algos/stackedensemble/pyunit_stackedensemble_validate_frames.py
https://0xdata.atlassian.net/browse/PUBDEV-6576
To REVIEWERS:
many changed files, but mostly generated ones.
Please pay mainly attention to:
- `frame.py`, `gen_py.py`, `estimator_base.py` and `autoh2o.py`
- tests
> PUBDEV-6576: Py client API broken when passing frames to constructor

- h2o-algos/src/test/java/hex/pdp/PartialDependenceTest.java
- h2o-core/src/main/java/hex/PartialDependence.java
- h2o-core/src/main/java/water/api/schemas3/PartialDependenceV3.java
- h2o-py/h2o/model/model_base.py
- h2o-py/tests/testdir_misc/pyunit_pubdev_6438_2D_pdp.py
- h2o-r/h2o-package/R/models.R
- h2o-r/tests/testdir_misc/runit_PUBDEV_6438_2D_pdp.R
This PR completes JIRA: https://0xdata.atlassian.net/browse/PUBDEV-6438?filter=-1
I have completed the following:
1. Added Java backend to support 2d pdp;
2. Added Junit test to make sure both 1d and 2d pdp works;
3. Added python client side to support specifying 2d pdp.
4. Added pyunit test;
5. Added R client side support to allow 2d pdp
6. Added Runit test.
7. plot 3d graph instead of 2d for both R and Python
> PUBDEV-6438: Implement 2D partial dependency plots

- h2o-py/h2o/estimators/estimator_base.py
@honzasterba FYI: merging now as it breaks new PRs
> fixed estimator_base.py merge that broke some tests

- h2o-automl/src/main/java/ai/h2o/automl/AutoML.java
https://0xdata.atlassian.net/browse/PUBDEV-6359
> PUBDEV-6359: AutoML, ensure that no additional model get trained after job cancellation

- h2o-docs/src/product/automl.rst
- h2o-docs/src/product/data-science/algo-params/stopping_metric.rst
- h2o-docs/src/product/data-science/algo-params/stopping_rounds.rst
- h2o-docs/src/product/data-science/algo-params/stopping_tolerance.rst
- h2o-docs/src/product/data-science/deep-learning.rst
- h2o-docs/src/product/data-science/drf.rst
- h2o-docs/src/product/data-science/gbm.rst
- h2o-docs/src/product/data-science/if.rst
- h2o-docs/src/product/data-science/xgboost.rst
"Isolation Forest" added to list of available algorithms for stopping_rounds, stopping_metric, and stopping_tolerance.
https://0xdata.atlassian.net/browse/PUBDEV-6613
*Do not merge until https://github.com/h2oai/h2o-3/pull/3619 has been merged
> PUBDEV-6613: Add stopping parameters to Isolation Forest

- h2o-py/h2o/utils/shared_utils.py
- h2o-py/tests/testdir_misc/pyunit_pubdev_6617_setInvNumNA.py
- h2o-r/h2o-package/R/predict.R
- h2o-r/tests/testdir_javapredict/runit_pubdev_6617_setInvNumNA.R
This PR finishes the work in : https://0xdata.atlassian.net/browse/PUBDEV-6617?filter=-1
Work done:
Added to R/Python client to be able to set setInvNumNA
Added R/Python unit tests.
> PUBDEV-6617: add setInvNumNA to R/Python clients

- h2o-genmodel/src/main/java/hex/genmodel/easy/DomainMapConstructor.java
- h2o-genmodel/src/main/java/hex/genmodel/easy/EasyPredictModelWrapper.java
- h2o-genmodel/src/main/java/hex/genmodel/easy/RowToRawDataConverter.java
- h2o-genmodel/src/test/java/hex/genmodel/easy/DomainMapConstructorTest.java
- h2o-genmodel/src/test/java/hex/genmodel/easy/RowToRawDataConverterTest.java
- h2o-genmodel/src/test/java/hex/genmodel/easy/stub/TestMojoModel.java
These changes were extracted from my  [TE Mojo Support PR](https://github.com/h2oai/h2o-3/pull/3282/files) to make it easier to merge both PRs.
> PUBDEV-6637: Refactored out RowToRawDataConverter 

- h2o-py/tests/testdir_algos/gbm/pyunit_PUBDEV_4076_custom_distribution.py
Fix inheritance for python 2.7 in custom distribution test.
> PUBDEV-4076 fix inheritance python 2.7

- h2o-algos/src/main/java/hex/tree/SharedTreeModelWithContributions.java
- h2o-algos/src/main/java/hex/tree/gbm/GBMModel.java
* Follow up from https://github.com/h2oai/h2o-3/pull/3628
> PUBDEV-6647: ScoreContributionsTask should not be abstract

- h2o-genmodel/src/main/java/hex/genmodel/algos/drf/DrfMojoModel.java
- h2o-genmodel/src/main/java/hex/genmodel/algos/gbm/GbmMojoModel.java
- h2o-genmodel/src/main/java/hex/genmodel/algos/tree/SharedTreeMojoModelWithContributions.java
* Follow up from https://github.com/h2oai/h2o-3/pull/3628
> PUBDEV-6646: Create SharedTreeMojoModelWithContributions class to have central location of contribs for DRF and GBM MOJO

- h2o-py/h2o/display.py
- h2o-py/h2o/frame.py
also fix some bugs in frame.show/summary
> [PUBDEV-6627] setup special formatting for Zeppelin

- h2o-extensions/xgboost/src/main/java/hex/tree/xgboost/XGBoostModel.java
- set updater value to one supported by gblinear
> [XGBOOST] fix gblinear with GPU backend

- h2o-genmodel/src/main/java/hex/genmodel/algos/gbm/GbmMojoReader.java
Fix NPE in old version MOJO where no link function value.
> PUBDEV-6661 FIX link function NPE in MOJO

- h2o-automl/src/test/java/ai/h2o/automl/AutoMLTest.java
- h2o-r/h2o-package/R/classes.R
https://0xdata.atlassian.net/browse/PUBDEV-6590
> PUBDEV-6590: Fixing build issues

- h2o-r/h2o-package/R/connection.R
- h2o-r/tests/testdir_jira/h2o.init_test_HOQE-16.R
- scripts/jenkins/Makefile.jenkins
We need to pass the property to JVM in order to have effect
> Fix test of h2o.init in R on Java 7

- h2o-py/h2o/model/model_base.py
- h2o-py/tests/testdir_misc/pyunit_pubdev_6672_2D_pdp_fix.py
Honza has found this bug for me: https://0xdata.atlassian.net/browse/PUBDEV-6672
I have fixed the bug if Python when no figure is plotted.  I added his test as the python unit test.
However, I am still working on refractoring the partial plot into separate functions.  Please start the review though.
> PUBDEV-6672: fixed bug in python client code when no figure is plotted.

- h2o-docs/src/product/data-science/algo-params/base_models.rst
- h2o-docs/src/product/data-science/algo-params/beta_constraints.rst
- h2o-docs/src/product/data-science/algo-params/blending_frame.rst
- h2o-docs/src/product/data-science/algo-params/build_tree_one_node.rst
- h2o-docs/src/product/data-science/algo-params/categorical_encoding.rst
- h2o-docs/src/product/data-science/algo-params/max_runtime_secs.rst
- h2o-docs/src/product/data-science/algo-params/pred_noise_bandwidth.rst
- h2o-docs/src/product/data-science/algo-params/prior.rst
- h2o-docs/src/product/data-science/algo-params/sample_size.rst
- h2o-docs/src/product/data-science/algo-params/seed.rst
- h2o-docs/src/product/data-science/algo-params/ties.rst
Edits made for uniformity in "Related Parameters" section
Minor driveby fixes (see max_runtime_secs.rst and ties.rst)
> parameters71219: Minor changes to parameters in the parameters appendix

- h2o-docs/src/product/productionizing.rst
Adding small documentation for a publishing a new AMI on AWS.
> H2oamidoc pratap

- h2o-docs/src/product/data-science/algo-params/base_models.rst
- h2o-docs/src/product/data-science/algo-params/custom_distribution_func.rst
- h2o-docs/src/product/data-science/algo-params/upload_custom_distribution.rst
- h2o-docs/src/product/data-science/gbm.rst
- h2o-docs/src/product/parameters.rst
Support has been added for a custom distribution function for GBM.
upload_custom_distribution has been added to the Parameters Appendix.
Minor driveby fixes included.
https://0xdata.atlassian.net/browse/PUBDEV-6554
> [WIP] PUBDEV-6554: Add "upload_custom_distribution" to Parameters Appendix

- h2o-py/h2o/h2o.py
Removes logger.basicConfig: interferes with application loggers
Adds option to silence show_status init h2o.init()
> Fixes logger and adds verbose option to init

- h2o-algos/src/main/java/hex/generic/GenericModelOutput.java
- h2o-bindings/bin/gen_R.py
- h2o-bindings/bin/gen_python.py
- h2o-genmodel/src/main/java/hex/genmodel/attributes/ModelAttributes.java
- h2o-genmodel/src/main/java/hex/genmodel/attributes/metrics/MojoModelMetricsAnomaly.java
- h2o-py/h2o/estimators/generic.py
- h2o-py/tests/testdir_generic_model/pyunit_generic_model_mojo_irf.py
- h2o-r/h2o-package/R/generic.R
- h2o-r/h2o-package/R/models.R
- h2o-r/tests/testdir_algos/generic/runit_generic_model_mojo_irf.R
https://0xdata.atlassian.net/browse/PUBDEV-6682
These metrics are only for the IRF MOJO.
> PUBDEV-6682 - Model metrics for IRF MOJO

- h2o-bindings/bin/gen_python.py
- h2o-py/h2o/estimators/generic.py
Discovered and fixed by @seb-h2o 
The condition could never be true. We only wanted to verify two of the arguments. Backend checks are present as well.
> Fixed argument check for Generic model in Python

- h2o-algos/src/test/java/hex/tree/gbm/GBMTest.java
GBMTest failed here:  http://mr-0xc1:8080/view/H2O-3/job/h2o-3-nightly-pipeline/job/master/2912/testReport/junit/hex.tree.gbm/GBMTest/Java_11_JUnit___testQuasibinomial_1__gbm_EmulateConstraints__/
I relaxed the tolerance from 2e-3 to 2e-2 and 1e-3 to 1e-2.
> Change seed value for GBMTest.testQuasiBinomial

- h2o-core/src/test/java/water/util/NonBlockingHashMapTest.java
Done in investigation of PUBDEV-6319
> PUBDEV-6319: Demonstrates how NBHM#putIfAbsesent works with keys

- h2o-automl/src/main/java/ai/h2o/automl/targetencoding/TargetEncoder.java
- h2o-automl/src/test/java/ai/h2o/automl/targetencoding/TargetEncodingLeaveOneOutStrategyTest.java
- h2o-automl/src/test/java/ai/h2o/automl/targetencoding/TargetEncodingTest.java
Reverting unnecessary performed revert
> Revert of revert "PUBDEV-6593: Get rid of dependency on response column from Target Ecnoder

- h2o-r/h2o-DESCRIPTION.template
- h2o-r/tests/runitUtils/utilsR.R
- h2o-r/tests/testdir_algos/glm/runit_GLM_tweedie_PUBDEV_6561.R
This PR finishes the work in PUBDEV-6561 and we added a tweedie glm test to ensure that the dispersion factor is tested.
> PUBDEV-6561 add back r tweedie glm test

- h2o-docs/src/product/performance-and-prediction.rst
Added a topic after Prediction Threshold called Predict Feature Frequency.
https://0xdata.atlassian.net/browse/PUBDEV-6671
> [WIP] PUBDEV-6671: Add `feature_frequencies` to Performance and Prediction section

- h2o-docs/src/product/automl.rst
- h2o-docs/src/product/data-science/aggregator.rst
- h2o-docs/src/product/data-science/algo-params/export_checkpoints_dir.rst
- h2o-docs/src/product/data-science/coxph.rst
- h2o-docs/src/product/data-science/deep-learning.rst
- h2o-docs/src/product/data-science/drf.rst
- h2o-docs/src/product/data-science/gbm.rst
- h2o-docs/src/product/data-science/glm.rst
- h2o-docs/src/product/data-science/glrm.rst
- h2o-docs/src/product/data-science/if.rst
- h2o-docs/src/product/data-science/k-means.rst
- h2o-docs/src/product/data-science/naive-bayes.rst
- h2o-docs/src/product/data-science/pca.rst
- h2o-docs/src/product/data-science/stacked-ensembles.rst
- h2o-docs/src/product/data-science/word2vec.rst
- h2o-docs/src/product/data-science/xgboost.rst
- h2o-docs/src/product/parameters.rst
Added export_checkpoints_dir to H2O-3's parameters appendix.
See: https://0xdata.atlassian.net/browse/PUBDEV-6706
> PUBDEV-6706: Create Parameters Appendix entry for export_checkpoints_dir

- h2o-algos/src/main/java/hex/tree/SharedTree.java
This doesn't fix anything - it should just show with column is `null`, having a vec=null would cause an exception like observed in PUBDEV-6686.
06-24 18:18:17.745 127.0.0.1:54321       11855  FJ-1-93   ERRR: java.lang.NullPointerException
06-24 18:18:17.745 127.0.0.1:54321       11855  FJ-1-93   ERRR:         at water.fvec.Frame.<init>   (Frame.java:168)
06-24 18:18:17.745 127.0.0.1:54321       11855  FJ-1-93   ERRR:         at water.fvec.Frame.<init>(Frame.java:138)
> PUBDEV-6686: Debugging code to find out what is causing NPE in DRF training

- h2o-algos/src/main/java/hex/ensemble/StackedEnsemble.java
- h2o-algos/src/test/java/hex/ensemble/StackedEnsembleTest.java
- h2o-bindings/bin/gen_python.py
- h2o-py/h2o/estimators/stackedensemble.py
https://0xdata.atlassian.net/browse/PUBDEV-6112
> PUBDEV-6112

- h2o-algos/src/main/java/hex/tree/SharedTree.java
- h2o-docs/src/product/data-science/algo-params/distribution.rst
- h2o-extensions/xgboost/src/main/java/hex/tree/xgboost/XGBoost.java
- h2o-py/tests/testdir_algos/gbm/pyunit_PUBDEV_4076_custom_distribution.py
JIRA: https://0xdata.atlassian.net/projects/PUBDEV/issues/PUBDEV-6693
> PUBDEV-6693 Do not show deviance scoring history if custom distribution is set

- h2o-core/src/main/java/water/api/RequestServer.java
https://0xdata.atlassian.net/browse/PUBDEV-6587
In Jetty's `ServletHandler` class, in `doHandle` method, there is this piece of code:
```
request.setAttribute(RequestDispatcher.ERROR_EXCEPTION_TYPE,th.getClass());
request.setAttribute(RequestDispatcher.ERROR_EXCEPTION,th);
if (!response.isCommitted())
{
if (th instanceof UnavailableException)
{
UnavailableException ue = (UnavailableException)th;
if (ue.isPermanent())
response.sendError(HttpServletResponse.SC_NOT_FOUND);
else
response.sendError(HttpServletResponse.SC_SERVICE_UNAVAILABLE);
}
else
response.sendError(HttpServletResponse.SC_INTERNAL_SERVER_ERROR);
}
```
If the response is not yet committed, it will send error via `sendError` method. As the exception attribute is set, the `getMessage` is used internally to extract details about …
> PUBDEV-6587 - Provide detailed stacktrace to Jetty's sendError

- h2o-py/h2o/model/model_base.py
- h2o-py/tests/testdir_jira/pyunit_pubdev_6709_pr_auc_call.py
This PR completes the work in JIRA: https://0xdata.atlassian.net/browse/PUBDEV-6709?filter=-1.
Work done:
1. I have added the pr_auc() call to python model_base.py so that users can call it.
2. Added pyunit test to make sure it can be called.
> PUBDEV-6709: add pr_auc() call to Python client

- h2o-automl/src/main/java/ai/h2o/automl/targetencoding/TargetEncoder.java
Note: this is just for master now, not ready to be released tomorrow in 3.26.0.2
> PUBDEV-6319: TE doesn't the workaround for GroupBy anymore

- h2o-bindings/bin/gen_python.py
- h2o-py/h2o/estimators/svd.py
- h2o-py/tests/testdir_golden/pyunit_svd_1_golden.py
- Set correct rest version parameter (from 3 to 99)
- Enhance `pyunit_svd_1_golden.py` test
JIRA: https://0xdata.atlassian.net/browse/PUBDEV-6143
> PUBDEV-6143 Initialization H2OSingularValueDecompositionEstimator 

- h2o-docs/src/product/data-science/algo-params/monotone_constraints.rst
- h2o-docs/src/product/data-science/gbm.rst
- h2o-docs/src/product/data-science/xgboost.rst
- h2o-docs/src/product/parameters.rst
Added Parameters Appendix entry for monotone_constraints.
See: https://0xdata.atlassian.net/browse/PUBDEV-6707
> PUBDEV-6707 Create Parameters Appendix entry for monotone_constraints

- h2o-docs/src/product/productionizing.rst
Bringing this change from "master" to "rel-yau" 
Related to this:
https://github.com/h2oai/h2o-3/pull/3712
> changes to usage of AMI

- h2o-bindings/bin/gen_java.py
- h2o-bindings/src/main/java/water/bindings/examples/retrofit/GBM_Example.java
https://github.com/h2oai/h2o-3/pull/3773 was mistakenly targeted against master, thus a separate PR to merge into rel-yates is required.
> PUBDEV 6732 - Cannot export model using java-rest-bindings (#3773)

- h2o-core/src/main/java/water/rapids/ast/prims/mungers/AstGroup.java
Old times:
Time taken to perform groupby is 129.045972824
Time taken to perform groupby is 139.069935083
Time taken to perform groupby is 136.047094822
New times:
Time taken to perform groupby is 119.699327946
Time taken to perform groupby is 120.479716063
Time taken to perform groupby is 120.498818874
> Parallelize group-by's (final) reduce step on each node

- h2o-bindings/bin/gen_python.py
- h2o-py/h2o/estimators/pca.py
- h2o-py/h2o/estimators/svd.py
- h2o-py/h2o/transforms/decomposition.py
- h2o-py/tests/testdir_algos/pca/pyunit_arrestsPCA.py
- h2o-py/tests/testdir_golden/pyunit_svd_1_golden.py
- h2o-py/tests/testdir_pipeline/pyunit_scale_pca_rf.py
- h2o-py/tests/testdir_pipeline/pyunit_scale_svd_rf.py
- h2o-py/tests/testdir_scikit_grid/pyunit_scal_pca_rf_grid.py
- h2o-py/tests/testdir_scikit_grid/pyunit_scal_svd_rf_grid.py
- add init_for_pipeline method to `H2OSingularValueDecompositionEstimator`
- fix default value for `H2OSingularValueDecompositionEstimator` `transform` parameter to `"NONE"`
- add tests for `Sklearn.Pipeline` and `Sklearn.RandomSearch`
- refactor also PCA tests a little bit
JIRA: https://0xdata.atlassian.net/browse/PUBDEV-6725
> PUBDEV-6725 fix svd transform pipeline

- h2o-py/h2o/model/regression.py
This reverts commit 31a69370f3338fea92d06ce69fc6fca44d0c36b7.
> Fix indentation issue causing test failures

- h2o-hadoop-common/tests/python/pyunit_PUBDEV_6758_glrm.py
This PR completes task in JIRA: https://0xdata.atlassian.net/browse/PUBDEV-6758?filter=-1
After talking to Honza, we have decided to add a GLRM test to hadoop smoke test.
> PUBDEV-6758: added glrm to hadoop smoke test

- gradle/java.gradle
- h2o-algos/src/test/java/hex/ensemble/StackedEnsembleTest.java
- h2o-assemblies/genmodel/build.gradle
- h2o-genmodel-extensions/xgboost/build.gradle
- h2o-genmodel/build.gradle
- h2o-hadoop-2/assemblyjar.gradle
- h2o-hadoop-3/assemblyjar.gradle
- h2o-hive/build.gradle
- h2o-mapreduce-generic/build.gradle
- scripts/jenkins/groovy/defineTestStages.groovy
- settings.gradle
Functionality for MOJO-scoring stays Java 7 compatibile
> Switch to Java 8 as a target for all modules except genmodel

- h2o-py/h2o/model/model_base.py
- h2o-py/tests/testdir_misc/pyunit_pubdev_6775_2D_pdp_xgboost.py
- h2o-r/h2o-package/R/models.R
- h2o-r/tests/testdir_misc/runit_PUBDEV-6775-2D-pdp.R
This PR fixes the problem inhttps://0xdata.atlassian.net/browse/PUBDEV-6775.
Honza:
I referred to variables without checking if they are null first.  Added the null pointer check in R and Python with unit tests.  Thank you, Wendy
> PUBDEV-6775: added null pointer check to Python and R clients.

- h2o-core/src/main/java/hex/ModelBuilder.java
- h2o-core/src/main/java/water/util/MathUtils.java
- h2o-py/tests/testdir_jira/pyunit_pubdev_6413_cv_sd_fix.py
This PR fix the bug in https://0xdata.atlassian.net/projects/PUBDEV/issues/PUBDEV-6413?filter=myopenissues&orderby=priority%20DESC.
Fix the variance calculation (and hence standard deviation) in MathUtils.BasicStats.  I added a Pyunit test to make sure the calculation is correct.
> PUBDEV-6413: fixed variance calculation over cross-validation metrics

- multiNodeUtils.sh
- implement more robust approach
> [build] multinode host detection sometimes failed on mac

- h2o-core/src/main/java/water/ExternalBackendRequestType.java
- h2o-core/src/main/java/water/ExternalFrameHandler.java
- h2o-core/src/main/java/water/ExternalFrameReaderClient.java
- h2o-core/src/main/java/water/ExternalFrameWriterBackend.java
- h2o-core/src/main/java/water/ExternalFrameWriterClient.java
- h2o-core/src/test/java/water/ExternalFrameWriterClientTest.java
Preparation for https://0xdata.atlassian.net/browse/SW-1530
> [PUBDEV-6802] Move initFrame and finalizeFrame to ExternalFrame API

- h2o-docs/src/product/data-science/algo-params/custom_distribution_func.rst
- h2o-docs/src/product/data-science/gbm.rst
Links for the updated custom distribution and custom loss function demos have been added to the docs.
See: https://0xdata.atlassian.net/browse/PUBDEV-6703
> PUBDEV-6703: Add links to custom distribution and custom loss function demos

- h2o-algos/src/main/java/hex/DataInfo.java
- h2o-algos/src/main/java/hex/glm/GLM.java
- h2o-algos/src/main/java/hex/glm/GLMModel.java
- h2o-algos/src/main/java/hex/glm/GLMMojoWriter.java
- h2o-algos/src/main/java/hex/glm/GLMTask.java
- h2o-algos/src/main/java/hex/glrm/GLRM.java
- h2o-algos/src/main/java/hex/pca/PCA.java
- h2o-algos/src/main/java/hex/schemas/GLMV3.java
- h2o-algos/src/main/java/hex/svd/SVD.java
- h2o-algos/src/main/java/hex/util/LinearAlgebraUtils.java
- h2o-algos/src/test/java/hex/glm/GLMBasicTestBinomial.java
- h2o-algos/src/test/java/hex/glm/GLMBasicTestMultinomial.java
- h2o-algos/src/test/java/hex/glm/GLMBasicTestRegression.java
- h2o-algos/src/test/java/hex/glm/GLMPlugValuesTest.java
- h2o-algos/src/test/java/hex/glm/GLMTest.java
- h2o-automl/src/main/java/ai/h2o/automl/AutoML.java
- h2o-core/src/main/java/water/fvec/InteractionWrappedVec.java
- h2o-py/h2o/estimators/glm.py
- h2o-py/tests/testdir_algos/glm/pyunit_glm_plugvalues.py
- h2o-r/h2o-package/R/glm.R
- h2o-r/tests/testdir_algos/glm/runit_GLM_grid_cars.R
- h2o-r/tests/testdir_algos/glm/runit_GLM_plug_values.R
Just use means but add another field to represent it, should pass all tests
> PUBDEV-5504  Another mode to treat missing values: plug values

- h2o-py/tests/testdir_algos/gbm/pyunit_grid_f2_f0point5_metrics_PUBDEV-6753.py
Use numeric comparison instead of string/unicode
> PUBDEV-6753: Make sure test for PUBDEV-6753 passes on Python 2.7

- h2o-automl/src/main/java/ai/h2o/automl/AutoML.java
This PR is an attempt to digest bigger PR https://github.com/h2oai/h2o-3/pull/3183 by smaller pieces.
> PUBDEV-6824: Small tidying up in AutoML class

- docker/Jenkinsfile-build-xgb-build-docker
- docker/Jenkinsfile-build-xgb-docker
- docker/xgb_build/Dockerfile-gpu-centos
- docker/xgb_build/Dockerfile-gpu-ubuntu
- docker/xgb_build/scripts/Setup.dist.patched
- docker/xgb_build/scripts/install_python_version_centos
- docker/xgb_build/scripts/install_python_version_ubuntu
lets have all docker infrastrucure at one place
> [xgboost] move docker images for xgb build into this repo

- h2o-algos/src/main/java/hex/pca/PCA.java
- h2o-algos/src/main/java/hex/pca/PCAModel.java
- h2o-algos/src/main/java/hex/pca/PCAMojoWriter.java
- h2o-algos/src/test/java/hex/pca/PCATest.java
- h2o-genmodel/src/main/java/hex/genmodel/ModelMojoFactory.java
- h2o-genmodel/src/main/java/hex/genmodel/algos/pca/PCAMojoModel.java
- h2o-genmodel/src/main/java/hex/genmodel/algos/pca/PCAMojoReader.java
- h2o-genmodel/src/main/java/hex/genmodel/easy/EasyPredictModelWrapper.java
- h2o-genmodel/src/main/java/hex/genmodel/easy/prediction/DimReductionModelPrediction.java
- h2o-genmodel/src/main/java/hex/genmodel/tools/PredictCsv.java
- h2o-py/tests/pyunit_utils/utilsPY.py
- h2o-py/tests/testdir_javapredict/pyunit_pubdev_5351_pca_mojo.py
- h2o-py/tests/testdir_jira/pyunit_pubdev_4711_supported_export_formats.py
- h2o-r/tests/runitUtils/utilsR.R
- h2o-r/tests/testdir_javapredict/runit_pubdev_5351_pca_mojo_large.R
- h2o-r/tests/testdir_jira/runit_pubdev_4711_supported_export_formats.R
This PR completes the work in JIRA: https://0xdata.atlassian.net/browse/PUBDEV-5351?filter=-1
I have completed the following:
1. add PCAMojoWriter, PCAMojoReader, PCAMojoModel and other backend support
2. added junit test
3. added python unit test
4. added R unit test.
> PUBDEV-5351: implement PCA Mojo

- h2o-extensions/target-encoder/src/main/java/ai/h2o/targetencoding/TargetEncoderBuilder.java
- h2o-extensions/target-encoder/src/main/java/ai/h2o/targetencoding/TargetEncoderModel.java
- h2o-extensions/target-encoder/src/main/java/hex/schemas/TargetEncoderV3.java
- h2o-py/h2o/estimators/targetencoder.py
- h2o-r/h2o-package/R/targetencoder.R
- h2o-web/bower.json
https://0xdata.atlassian.net/browse/PUBDEV-6837
[![](http://img.youtube.com/vi/l_pCeT9AyUY/0.jpg)](http://www.youtube.com/watch?v=l_pCeT9AyUY "")
> PUBDEV-6837 - Support for Target Encoding in Flow (H2O-3 part)

- h2o-algos/src/main/java/hex/pca/PCA.java
- h2o-algos/src/main/java/hex/pca/PCAModel.java
- h2o-algos/src/main/java/hex/pca/PCAMojoWriter.java
- h2o-algos/src/test/java/hex/pca/PCATest.java
- h2o-extensions/target-encoder/src/main/java/ai/h2o/targetencoding/TargetEncoderBuilder.java
- h2o-extensions/target-encoder/src/main/java/ai/h2o/targetencoding/TargetEncoderModel.java
- h2o-extensions/target-encoder/src/main/java/hex/schemas/TargetEncoderV3.java
- h2o-genmodel/src/main/java/hex/genmodel/ModelMojoFactory.java
- h2o-genmodel/src/main/java/hex/genmodel/algos/pca/PCAMojoModel.java
- h2o-genmodel/src/main/java/hex/genmodel/algos/pca/PCAMojoReader.java
- h2o-genmodel/src/main/java/hex/genmodel/easy/EasyPredictModelWrapper.java
- h2o-genmodel/src/main/java/hex/genmodel/easy/prediction/DimReductionModelPrediction.java
- h2o-genmodel/src/main/java/hex/genmodel/tools/PredictCsv.java
- h2o-py/h2o/estimators/targetencoder.py
- h2o-py/tests/pyunit_utils/utilsPY.py
- h2o-py/tests/testdir_javapredict/pyunit_pubdev_5351_pca_mojo.py
- h2o-py/tests/testdir_jira/pyunit_pubdev_4711_supported_export_formats.py
- h2o-r/h2o-package/R/targetencoder.R
- h2o-r/tests/runitUtils/utilsR.R
- h2o-r/tests/testdir_javapredict/runit_pubdev_5351_pca_mojo_large.R
- h2o-r/tests/testdir_jira/runit_pubdev_4711_supported_export_formats.R
- h2o-web/bower.json
Resolving conflicts due to changes in TE in rel-yau right before the previous manual merge (https://github.com/h2oai/h2o-3/pull/3847)...
> YAMM: Yet Another Manuel Merge rel-yau -> master

- h2o-mapreduce-generic/src/main/java/water/hadoop/h2odriver.java
- h2o-mapreduce-generic/src/test/java/water/hadoop/CallbackManagerTest.java
- h2o-mapreduce-generic/src/test/java/water/hadoop/EmbeddedH2OConfigTest.java
also resolved some intellij warnings/suggestions
This is a preparation to introduce a new clouding mechanism
> h2odriver - clean-up: move some global state to CallbackManager

- h2o-core/src/main/java/water/api/schemas3/ModelMetricsBinomialV3.java
- h2o-py/h2o/grid/metrics.py
- h2o-py/h2o/model/binomial.py
- h2o-py/h2o/model/metrics_base.py
- h2o-py/tests/testdir_misc/pyunit_make_metrics.py
- h2o-r/h2o-package/R/models.R
- h2o-r/tests/testdir_misc/runit_make_metrics.R
https://0xdata.atlassian.net/browse/PUBDEV-6366
> PUBDEV-6366: fixed broken metrics (e.g. no thresholds) on clients

- h2o-automl/src/main/java/ai/h2o/automl/Algo.java
- h2o-genmodel-extensions/xgboost/build.gradle
- scripts/jenkins/groovy/buildConfig.groovy
- scripts/jenkins/groovy/defaultStage.groovy
Includes https://0xdata.atlassian.net/browse/PUBDEV-6502
> Upgrade to xgboost 0.90

- h2o-extensions/xgboost/src/test/java/hex/tree/xgboost/XGBoostPredictImplComparisonTest.java
- add relative precision checking for gblinear predictions
> XGBoost: improve reliability of smoke tests

- h2o-py/h2o/model/binomial.py
- h2o-py/h2o/model/clustering.py
- h2o-py/h2o/model/multinomial.py
Please let me know if anything else should be updated.
> PUBDEV-6872: Update the default value lines in the Model Categories section

- h2o-py/h2o/model/binomial.py
- h2o-py/h2o/model/model_base.py
- h2o-py/tests/testdir_algos/glm/pyunit_PUBDEV_6853_glm_plot.py
This PR fix the bug reported here: https://0xdata.atlassian.net/browse/PUBDEV-6853
I fixed the Python plot for GLM model and added a Pyunit test to make sure it works.
> PUBDEV-6853: fix glm plot error

- h2o-automl/src/main/java/ai/h2o/automl/Leaderboard.java
https://0xdata.atlassian.net/browse/PUBDEV-6896
> PUBDEV-6896: fix potential deadlock issue with AutoML leaderboard

- docker/hadoop/cdh/Dockerfile
- docker/hadoop/cdh/scripts/sbin/mysql_configure.sh
- scripts/jenkins/groovy/buildConfig.groovy
inspired by https://github.com/h2oai/h2o-3/pull/3494/files
> XDH6.3: fix smoke tests, add same fix as for 6.2

- h2o-core/src/main/java/water/ExternalFrameWriterClient.java
https://0xdata.atlassian.net/browse/PUBDEV-6904
> [PUBDEV-6904] Fix issue with missing chunk on external backend

- h2o-py/tests/pyunit_utils/utilsPY.py
- the frame comparison fucntions would always pass with success for 1 row frames because tha last row was ignored
> Fix frame comparison in python which would ingore last row

- h2o-core/src/main/java/water/fvec/ChunkVisitor.java
- h2o-core/src/main/java/water/fvec/Frame.java
- h2o-core/src/main/java/water/rapids/Env.java
- h2o-core/src/main/java/water/rapids/Val.java
- h2o-core/src/main/java/water/rapids/ast/params/AstNumList.java
- h2o-core/src/main/java/water/rapids/ast/params/AstStrList.java
- h2o-core/src/main/java/water/rapids/ast/prims/mungers/AstMelt.java
- h2o-core/src/main/java/water/rapids/vals/ValStr.java
- h2o-core/src/main/java/water/rapids/vals/ValStrs.java
- h2o-core/src/test/java/water/fvec/FrameTest.java
- h2o-core/src/test/java/water/rapids/RapidsTest.java
- h2o-py/h2o/frame.py
- h2o-py/tests/testdir_misc/pyunit_melt.py
- h2o-r/h2o-package/R/frame.R
- h2o-r/tests/testdir_munging/runit_melt.R
https://0xdata.atlassian.net/browse/PUBDEV-6780
> PUBDEV-6780: Add equivalent of Pandas Melt

- h2o-core/src/main/java/hex/LinkFunctionFactory.java
- h2o-extensions/xgboost/src/main/java/hex/tree/xgboost/XGBoost.java
- h2o-extensions/xgboost/src/main/java/hex/tree/xgboost/XGBoostModel.java
- h2o-extensions/xgboost/src/main/java/hex/tree/xgboost/XGBoostPojoWriter.java
- h2o-extensions/xgboost/src/main/java/ml/dmlc/xgboost4j/java/PredictorFactory.java
- h2o-genmodel-extensions/xgboost/build.gradle
- h2o-genmodel-extensions/xgboost/src/main/java/hex/genmodel/algos/xgboost/XGBoostMojoModel.java
- h2o-genmodel/build.gradle
- h2o-genmodel/src/main/java/hex/genmodel/algos/tree/SharedTreeGraph.java
- h2o-py/tests/testdir_algos/xgboost/pyunit_xgboost_pojo.py
GBTree POJO example:
```/*
Licensed under the Apache License, Version 2.0
http://www.apache.org/licenses/LICENSE-2.0.html
AUTOGENERATED BY H2O at 2019-09-24T12:06:23.128+02:00
3.26.0.99999
Standalone prediction code with sample test data for XGBoostModel named XGBoost_model_python_1569319545135_2
How to download, compile and execute:
mkdir tmpdir
cd tmpdir
curl http://192.168.59.167:54321/3/h2o-genmodel.jar > h2o-genmodel.jar
curl http://192.168.59.167:54321/3/Models.java/XGBoost_model_python_1569319545135_2 > XGBoost_model_python_1569319545135_2.java
javac -cp h2o-genmodel.jar -J-Xmx2g -J-XX:MaxPermSize=128m XGBoost_model_python_1569319545135_2.java
(Note:  Try java argument -XX:+PrintCompilation to show runtime JIT compiler behavior.)
*/
import java.util.Map;
import …
```
> PUBDEV-6863: XGBoost POJO

- h2o-docs/src/product/automl.rst
- h2o-docs/src/product/data-science/xgboost.rst
- h2o-docs/src/product/faq/general.rst
- Updated GPU FAQ to include GPU support for XGBoost
- Added "GPU Support" section to XGBoost chapter
- Added AutoML FAQ to general FAQ and to AutoML FAQ
Driveby fix: Fixed heading levels in AutoML chapter
> PUBDEV-6861: Add info about GPU support for XGBoost

- h2o-docs/src/product/data-science/algo-params/rate.rst
- h2o-docs/src/product/data-science/algo-params/rate_annealing.rst
- h2o-docs/src/product/data-science/algo-params/rate_decay.rst
- h2o-docs/src/product/data-science/deep-learning.rst
- h2o-docs/src/product/parameters.rst
- Fixed equation for rate_decay
- Added parameter appendix entries for rate, rate_decay, and rate_annealing
> PUBDEV-6913: Doc updates for deep learning "learning rate" params

- h2o-docs/src/product/pojo-quickstart.rst
- h2o-genmodel/src/main/java/overview.html
POJO support added for XGBoost. The docs have been updated to reflect this.
See: https://0xdata.atlassian.net/browse/PUBDEV-6914
> PUBDEV-6914: POJO support added for XGBoost

- h2o-py/tests/testdir_algos/xgboost/pyunit_H2OXGBoost_native_XGBoost_enum_binomial_compare_sparse_singleNode.py
- h2o-py/tests/testdir_algos/xgboost/pyunit_H2OXGBoost_native_XGBoost_enum_multinomial_compare_sparse_singleNode.py
- h2o-py/tests/testdir_algos/xgboost/pyunit_H2OXGBoost_native_XGBoost_mixed_binomial_compare_large_dense_singleNode.py
- h2o-py/tests/testdir_algos/xgboost/pyunit_H2OXGBoost_native_XGBoost_mixed_binomial_compare_large_sparse_singleNode.py
- h2o-py/tests/testdir_algos/xgboost/pyunit_H2OXGBoost_native_XGBoost_mixed_multinomial_compare_large_dense_singleNode.py
- h2o-py/tests/testdir_algos/xgboost/pyunit_H2OXGBoost_native_XGBoost_mixed_multinomial_compare_large_sparse_singleNode.py
- h2o-py/tests/testdir_algos/xgboost/pyunit_H2OXGBoost_native_XGBoost_mixed_regression_compare_large_dense_singleNode.py
- h2o-py/tests/testdir_algos/xgboost/pyunit_H2OXGBoost_native_XGBoost_mixed_regression_compare_large_sparse_singleNode.py
- h2o-py/tests/testdir_algos/xgboost/pyunit_H2OXGBoost_native_XGBoost_numerical_binomial_compare_sparse_singleNode.py
- h2o-py/tests/testdir_algos/xgboost/pyunit_PUBDEV_5777_XGBoost_dense_comparisons.py
- h2o-py/tests/testdir_algos/xgboost/pyunit_PUBDEV_5777_XGBoost_sparse_comparisons.py
- h2o-py/tests/testdir_algos/xgboost/pyunit_PUBDEV_6117_xgboost_compare.py
- h2o-py/tests/testdir_algos/xgboost/pyunit_higgs_random_seeds_large_singleNode.py
- h2o-py/tests/testdir_algos/xgboost/pyunit_native_comparison.py
- h2o-py/tests/testdir_algos/xgboost/pyunit_xgboost_zero_nan_handling_native_comparison.py
...xgboost python lib is not supported on py2 anymore
> PUBDEV-6884: Disable XGBoost native comparison tests on py2

- h2o-extensions/xgboost/src/test/java/hex/tree/xgboost/XGBoostPredictImplComparisonTest.java
https://github.com/dmlc/xgboost/issues/4919
> XGBoost/tests: reduce required precision for gblibear predicions

- h2o-core/src/main/java/water/api/RequestServer.java
- h2o-core/src/main/java/water/server/ServletUtils.java
- h2o-core/src/main/java/water/webserver/H2OHttpViewImpl.java
- h2o-core/src/test/java/water/webserver/H2OHttpViewImplTest.java
- h2o-hadoop-common/tests/python/pyunit_trace.py
- h2o-jetty-8/src/main/java/water/webserver/jetty8/Jetty8ServerAdapter.java
- h2o-jetty-9/src/main/java/water/webserver/jetty9/Jetty9Helper.java
- h2o-jetty-9/src/main/java/water/webserver/jetty9/Jetty9ServerAdapter.java
- h2o-py/h2o/backend/connection.py
- h2o-webserver-iface/src/main/java/water/webserver/iface/H2OHttpView.java
https://0xdata.atlassian.net/browse/PUBDEV-6948
> PUBDEV-6948: Disable HTTP TRACE Method

- README.md
Found out you three are missing and should definitely be there. WDYT ?
> Update the list of contributors

- h2o-core/src/test/java/water/fvec/VecTest.java
The original test cannot run reliably in multi-node
> Fix testChunkIdxWithDeletedVec

- h2o-extensions/target-encoder/build.gradle
- h2o-extensions/target-encoder/src/main/java/ai/h2o/targetencoding/TargetEncoder.java
- h2o-extensions/target-encoder/src/test/java/ai/h2o/targetencoding/TEMojoIntegrationTest.java
See details in https://0xdata.atlassian.net/browse/PUBDEV-6941
> PUBDEV-6941: Added blending of posterior and prior during imputation of unseen values

- h2o-docs/src/product/data-science/xgboost.rst
- h2o-extensions/xgboost/src/main/java/hex/tree/xgboost/XGBoostModel.java
- h2o-extensions/xgboost/src/test/java/hex/tree/xgboost/XGBoostPredictImplComparisonTest.java
- set updater for gblinear when running on CPU to coord_descent to get rid of indeterminism
> XGBoost: make gblinear deterministic

- h2o-algos/src/main/java/hex/ensemble/Metalearner.java
- h2o-docs/src/product/data-science/stacked-ensembles.rst
- h2o-py/tests/pyunit_utils/utilsPY.py
- h2o-py/tests/testdir_algos/stackedensemble/pyunit_stackedensemble_with_poor_models.py
https://0xdata.atlassian.net/browse/PUBDEV-6874
Issue explained in details in ticket above, as well as investigation and results.
The fix consists in disabling standardization for GLM metalearner in AUTO mode: user who wants to use explicit GLM metalearner will still have the default GLM params.
> PUBDEV-6874 StackedEnsemble bad predictions due to one bad model in the stack

- h2o-py/h2o/automl/__init__.py
- h2o-py/h2o/automl/autoh2o.py
https://0xdata.atlassian.net/browse/PUBDEV-6928
adding alias and use the occasion to raise a better Error if instance doesn't exist (was previously raising uncaught error)
> PUBDEV-6928: expose get_automl from `h2o.automl` module

- h2o-bindings/bin/custom/python/gen_naivebayes.py
- h2o-py/h2o/estimators/naive_bayes.py
Original Jira disappeared (Pubdev-6958); still operating off of that git branch--new jira is https://0xdata.atlassian.net/browse/PUBDEV-6962
> PUBDEV-6958: Python Docs: Add examples to NaiveBayes

- build.gradle
- gradle/ubench.gradle
- h2o-core/src/jmh/java/water/util/IcedHashMapBench.java
- h2o-core/src/main/java/water/util/IcedHashMap.java
- h2o-core/src/main/java/water/util/IcedHashMapBase.java
- h2o-core/src/test/java/water/util/IcedHashMapTest.java
https://0xdata.atlassian.net/browse/PUBDEV-6969
added support for numeric and primitive arrays to IcedHashMapBase and tis implementation.
Rewrote the logic for clarity and easier future extensibility.
Also created UTs as there was none for this core component..
> PUBDEV-6969: added support for numeric arrays to IcedHashMap

- scripts/jenkins/groovy/buildConfig.groovy
- scripts/jenkins/groovy/defineTestStages.groovy
- adding gpu as a testComponent triggered downloadind a non-existent -gpu stash
> XGBoost - fix benchmarks

- docker/Jenkinsfile-build-hadoop-docker
- docker/Jenkinsfile-build-xgb-build-docker
- docker/Jenkinsfile-build-xgb-docker
- scripts/jenkins/jenkinsfiles/Jenkinsfile
- scripts/jenkins/jenkinsfiles/Jenkinsfile-Benchmarks
- scripts/jenkins/jenkinsfiles/Jenkinsfile-Coverage
- scripts/jenkins/jenkinsfiles/Jenkinsfile-Hadoop
- scripts/jenkins/jenkinsfiles/Jenkinsfile-Kerberos
- scripts/jenkins/jenkinsfiles/Jenkinsfile-Nightly
- scripts/jenkins/jenkinsfiles/Jenkinsfile-Single-Test
- scripts/jenkins/jenkinsfiles/Jenkinsfile-XGB
> Do not schedule H2O jobs to micro nodes - leave them to SW

- h2o-py/h2o/frame.py
- h2o-py/tests/testdir_misc/pyunit_drop.py
https://0xdata.atlassian.net/browse/PUBDEV-7010
> PUBDEV-7010: Python, H2OFrame.drop should not modify params

- h2o-core/src/main/java/water/AutoBuffer.java
https://0xdata.atlassian.net/browse/PUBDEV-6847
Should we also include the documentation link ? http://docs.h2o.ai/h2o/latest-stable/h2o-docs/data-science/mojo_import.html
> PUBDEV-6847 - Show MOJO Import possibility when importing model from a different version

- h2o-extensions/xgboost/src/main/java/hex/tree/xgboost/XGBoostModel.java
- fix the name of max_bin native param
- properly handle hist tree method
> PUBDEV-6982: improve xgboost updater/tree-method configuration

- h2o-py/h2o/estimators/random_forest.py
- h2o-r/h2o-package/R/randomforest.R
The original PR is here: https://github.com/h2oai/h2o-3/pull/3843#discussion_r340637856 
I found out there are some documentation changes originating from this commit by using git bisect. Can we please have a look at it and either merge this PR or take some other actions ?
> PUBDEV-6831 - Generated R & Py docs

- docker/hadoop/cdh/Dockerfile
- docker/hadoop/hdp/Dockerfile
- scripts/jenkins/groovy/buildConfig.groovy
- scripts/jenkins/groovy/defineTestStages.groovy
- scripts/jenkins/groovy/hadoopStage.groovy
unstashing centrally built hadoop jars takes up to 40 minutes for each distro, remove the stashing and build locally
> Jenkins: build hadoop jars in parallel for each distro

- h2o-extensions/target-encoder/src/main/java/ai/h2o/targetencoding/TargetEncoder.java
- h2o-extensions/target-encoder/src/main/java/hex/schemas/TargetEncoderTransformParametersV3.java
- h2o-extensions/target-encoder/src/main/java/hex/schemas/TargetEncoderV3.java
- h2o-extensions/target-encoder/src/test/java/ai/h2o/targetencoding/TargetEncodingTest.java
- h2o-py/h2o/estimators/targetencoder.py
- h2o-r/h2o-package/R/targetencoder.R
https://0xdata.atlassian.net/browse/PUBDEV-6995
> PUBDEV-6995: Swapped default TE blending params to be consistent with clients' defaults

- h2o-core/src/main/java/water/util/ArrayUtils.java
JIRA: https://0xdata.atlassian.net/projects/PUBDEV/issues/PUBDEV-6959
> PUBDEV-6959 add more info into asserts

- h2o-genmodel/src/main/java/hex/genmodel/attributes/ModelJsonReader.java
https://0xdata.atlassian.net/browse/PUBDEV-7036
Continuation of https://github.com/h2oai/h2o-3/pull/4054.
> PUBDEV-7036 - Use stderr instead of stdout to show warnings in MojoReader

- h2o-docs/src/product/flow/packs/test-small/grid_search_test.flow
Please note, that bug is reproducible on master / not on rel-yau.
> PUBDEV-7058: test suite extended to cover the bug case

- h2o-extensions/target-encoder/src/main/java/ai/h2o/targetencoding/strategy/AllCategoricalTEApplicationStrategy.java
- h2o-extensions/target-encoder/src/main/java/ai/h2o/targetencoding/strategy/TEApplicationStrategy.java
- h2o-extensions/target-encoder/src/main/java/ai/h2o/targetencoding/strategy/ThresholdTEApplicationStrategy.java
- h2o-extensions/target-encoder/src/test/java/ai/h2o/targetencoding/strategy/AllCategoricalTEApplicationStrategyTest.java
- h2o-extensions/target-encoder/src/test/java/ai/h2o/targetencoding/strategy/ThresholdTEApplicationStrategyTest.java
Added two TE application strategies:
1) All categorical
2) Threshold strategy, meaning categorical columns with number of levels higher than threshold will be subjects for TE encoding
> PUBDEV-6970: introduced AllCategorical and Threshold TE application strategies

- scripts/jenkins/groovy/defineTestStages.groovy
- scripts/jenkins/groovy/hadoopCommands.groovy
- scripts/jenkins/groovy/kerberosCommands.groovy
- too mum xmx causes hive tasks to wait forever
- cleanup memory in hadoop tests
> Jenkins: fix hdp-krb tests timeouts

- h2o-core/src/main/java/water/H2O.java
- h2o-core/src/main/java/water/network/SSLProperties.java
- h2o-core/src/main/java/water/network/SSLSocketChannelFactory.java
- h2o-core/src/test/java/water/network/SSLPropertiesTest.java
- h2o-core/src/test/java/water/network/SSLSocketChannelFactoryTest.java
@jakubhava just an idea - this is not backward compatible
> Interpret paths in security config relative to the config itself.

- h2o-automl/src/main/java/ai/h2o/automl/AutoMLBuildSpec.java
- h2o-automl/src/main/java/ai/h2o/automl/Leaderboard.java
- h2o-automl/src/main/java/ai/h2o/automl/ModelingStep.java
- h2o-automl/src/main/java/water/automl/api/schemas3/AutoMLBuildSpecV99.java
- h2o-automl/src/test/java/ai/h2o/automl/AutoMLTest.java
- h2o-core/src/main/java/hex/ModelMetricsBinomial.java
- h2o-core/src/main/java/hex/ScoreKeeper.java
- h2o-core/src/main/java/hex/ScoringInfo.java
- h2o-core/src/main/java/hex/schemas/HyperSpaceSearchCriteriaV99.java
- h2o-core/src/main/java/water/api/EnumValuesProvider.java
- h2o-core/src/main/java/water/api/SchemaMetadata.java
- h2o-core/src/main/java/water/api/schemas3/ModelParameterSchemaV3.java
- h2o-core/src/main/java/water/api/schemas3/ModelParametersSchemaV3.java
- h2o-core/src/main/java/water/api/schemas3/ModelParamsValuesProviders.java
- h2o-py/tests/testdir_algos/automl/pyunit_automl_leaderboard.py
https://0xdata.atlassian.net/browse/PUBDEV-6940
And added support for `AUCPR` in AutoML.
> PUBDEV-6940: fix list of metrics exposed in Flow

- h2o-py/h2o/backend/connection.py
- h2o-py/tests/testdir_jira/pyunit_pubdev_7062-cacerts.py
> PUBDEV-7062: Allow CACERT to be speficied in a configuration object

- h2o-core/src/main/java/water/H2O.java
- h2o-core/src/main/java/water/UDPClientEvent.java
Not causing any bugs, but it is a dead code, not used anywhere
> [PUBDEV-7099] Remove dead code in UDPClientEvent

- h2o-core/src/main/java/water/util/EnumUtils.java
- h2o-core/src/main/java/water/util/PojoUtils.java
- h2o-py/h2o/automl/autoh2o.py
- h2o-py/tests/testdir_algos/automl/pyunit_automl_args.py
- h2o-py/tests/testdir_algos/automl/regression/pyunit_automl_australia.py
- h2o-r/h2o-package/R/automl.R
- h2o-r/h2o-package/R/models.R
- h2o-r/tests/testdir_algos/automl/runit_automl_args.R
- h2o-r/tests/testdir_algos/randomforest/runit_RF_early_stopping.R
https://0xdata.atlassian.net/browse/PUBDEV-4986
https://0xdata.atlassian.net/browse/PUBDEV-6184
> PUBDEV-4986: ensure case-insensitivity of stopping+sort metrics

- h2o-docs/src/booklets/v2_2015/source/GBM_Vignette_code_examples/gbm_gridsearch_random.py
`rel-yau`'s version of https://github.com/h2oai/h2o-3/pull/4116
> prevent possibility for random gbm search to select max_depth=0

- h2o-mapreduce-generic/src/main/java/water/hadoop/h2odriver.java
- scripts/jenkins/groovy/hadoopCommands.groovy
> [PUBDEV-7106] Report full flatfile in h2odriver

- h2o-algos/src/test/java/hex/CrossValidFoldAssignmentsTest.java
- h2o-algos/src/test/java/hex/deeplearning/DeepLearningReproducibilityTest.java
- h2o-algos/src/test/java/hex/ensemble/StackedEnsembleTest.java
- h2o-algos/src/test/java/hex/glrm/GLRMTest.java
- h2o-algos/src/test/java/hex/pca/PCATest.java
- h2o-algos/src/test/java/hex/tree/gbm/GBMTest.java
- h2o-core/src/test/java/hex/createframe/OriginalCreateFrameRecipeTest.java
- h2o-core/src/test/java/water/OOMTest.java
- h2o-core/src/test/java/water/TestUtil.java
- h2o-core/src/test/java/water/fvec/ExportTest.java
- h2o-core/src/test/java/water/fvec/FrameTest.java
- h2o-core/src/test/java/water/fvec/RebalanceDatasetTest.java
- h2o-core/src/test/java/water/parser/ClientParserZipGzipTest.java
- h2o-core/src/test/java/water/parser/ParseCompressedAndXLSTest.java
- h2o-core/src/test/java/water/parser/ParseFolderTest.java
- h2o-core/src/test/java/water/parser/ParseFolderTestBig.java
- h2o-core/src/test/java/water/parser/ParserTestARFF.java
- h2o-core/src/test/java/water/rapids/MungingTest.java
- h2o-core/src/test/java/water/rapids/RapidsTest.java
- h2o-core/src/test/java/water/rapids/SortTest.java
- h2o-core/src/test/java/water/rapids/ast/prims/advmath/AstFillNATest.java
- h2o-core/src/test/java/water/rapids/ast/prims/mungers/AstFillNATest.java
- h2o-core/src/test/java/water/rapids/ast/prims/mungers/AstMergeTest.java
- h2o-core/src/test/java/water/rapids/ast/prims/reducers/AstTopNTest.java
- h2o-extensions/target-encoder/src/test/java/ai/h2o/targetencoding/TargetEncoderBuilderTest.java
- h2o-extensions/target-encoder/src/test/java/ai/h2o/targetencoding/TargetEncodingImmutabilityTest.java
- h2o-parsers/h2o-orc-parser/src/test/java/water/parser/orc/ParseTestMultiFileOrc.java
- h2o-parsers/h2o-orc-parser/src/test/java/water/parser/orc/ParseTestORCCSV.java
- h2o-parsers/h2o-parquet-parser/src/test/java/water/parser/parquet/ParseTestParquet.java
- h2o-persist-http/src/test/java/water/persist/PersistHTTPTest.java
- convert it to assert
- add message conveying what comparison failed
- fix references (some tests were already using it as an assert)
> [testing] improve isIdenticalUpToRelTolerance

- h2o-algos/src/test/java/hex/grid/GridTest.java
- h2o-core/src/main/java/hex/grid/GridSearch.java
- h2o-core/src/main/java/hex/grid/HyperSpaceSearchCriteria.java
- h2o-core/src/main/java/hex/grid/HyperSpaceWalker.java
https://0xdata.atlassian.net/browse/PUBDEV-7121
Target branch is `master` as we now are not allowed to merge to rel-yau
> [PUBDEV-7121] Parallel grid search does not handle max_runtime_secs == 0 for unlimited search

- h2o-core/src/main/java/water/H2O.java
Useful for debugging when nodes are crashing
> Add process id to H2O startup logs

- h2o-algos/src/main/java/hex/tree/TreeHandler.java
- h2o-algos/src/test/java/hex/tree/TreeHandlerTest.java
https://0xdata.atlassian.net/browse/PUBDEV-7137
> PUBDEV-7137 - Categorical node split description generation - NullPointerException

- h2o-algos/src/test/java/hex/tree/PrintMojoTreeTest.java
- h2o-algos/src/test/resources/hex/tree/categorical.json
- h2o-algos/src/test/resources/hex/tree/categoricalOneHot.json
- h2o-algos/src/test/resources/hex/tree/gbmProstate.json
- h2o-genmodel/src/main/java/hex/genmodel/ModelMojoReader.java
- h2o-genmodel/src/main/java/hex/genmodel/MojoModel.java
- h2o-genmodel/src/main/java/hex/genmodel/algos/isofor/IsolationForestMojoModel.java
- h2o-genmodel/src/main/java/hex/genmodel/algos/tree/SharedTreeGraph.java
- h2o-genmodel/src/main/java/hex/genmodel/algos/tree/SharedTreeMojoModel.java
- h2o-genmodel/src/main/java/hex/genmodel/algos/tree/SharedTreeNode.java
- h2o-genmodel/src/main/java/hex/genmodel/algos/tree/SharedTreeSubgraph.java
- h2o-genmodel/src/main/java/hex/genmodel/algos/tree/TreeBackedMojoModel.java
- h2o-genmodel/src/main/java/hex/genmodel/descriptor/ModelDescriptorBuilder.java
- h2o-genmodel/src/main/java/hex/genmodel/tools/PrintMojo.java
- h2o-genmodel/src/main/java/hex/genmodel/utils/GenmodelBitSet.java
- h2o-genmodel/src/test/java/hex/genmodel/algos/tree/SharedTreeGraphTest.java
- h2o-py/h2o/__init__.py
- h2o-py/h2o/h2o.py
- h2o-py/tests/testdir_misc/pyunit_print_mojo.py
- necessary to convert GBM models to ONNX
> PUBDEV-7057: add JSON option of PrintMojo

- h2o-algos/src/main/java/hex/kmeans/KMeans.java
- h2o-algos/src/test/java/hex/kmeans/KMeansTest.java
- h2o-r/tests/testdir_algos/kmeans/runit_kmeans_parameters.R
JIRA: https://0xdata.atlassian.net/browse/PUBDEV-6966
_train parameter has no key by default, _parms.train() has key
> PUBDEV-6966 kmeans compute training metrics on dataset from parms

- h2o-core/src/main/java/water/H2O.java
- h2o-core/src/test/java/water/TestUtil.java
- h2o-extensions/target-encoder/testMultiNode.sh
- h2o-extensions/target-encoder/testSingleNode.sh
- h2o-extensions/xgboost/src/test/java/hex/tree/xgboost/XGBoostParamsTest.java
For details see https://0xdata.atlassian.net/browse/PUBDEV-7095
> [PUBDEV-7095] Allocate more time for clouding to fix Cloud 1 under 4 issue

- h2o-extensions/xgboost/src/main/java/hex/tree/xgboost/XGBoostModel.java
- h2o-extensions/xgboost/src/test/java/hex/tree/xgboost/XGBoostTreeConverterTest.java
- h2o-py/tests/testdir_tree/pyunit_xgboost_tree.py
https://0xdata.atlassian.net/browse/PUBDEV-7078
> PUBDEV-7078 - Tree API requires tree class to be specified for XGBoost in case of binomial

- h2o-py/docs/conf.py
- h2o-py/h2o/tree/tree.py
- [PUBDEV-7088](https://0xdata.atlassian.net/browse/PUBDEV-7088)
- [Support portal ticket 95917](https://support.h2o.ai/a/tickets/95917)
----------------
- Mentioned that our representation is based on Scikit directly.
- Explained how can the information about each node be accessed (using it's ID as an index)
- Added bits and pieces from my blogpost.
- Changed the constructor used in examples to explicitely name the parameters.
Do you think it is good enough ? Shall I add more ? Shall I create a dedicated section in the docs.h2o.ai ?
Thank you for your reviews and comments.
> PUBDEV-7088 - Tree Class documentation is difficult to interpret. Add examples.

- h2o-core/src/test/java/water/rapids/RapidsTest.java
- h2o-core/src/test/java/water/runner/CheckKeysTask.java
- h2o-core/src/test/java/water/runner/CleanAllKeysTask.java
- h2o-core/src/test/java/water/runner/CloudSize.java
- h2o-core/src/test/java/water/runner/CollectInitKeysTask.java
- h2o-core/src/test/java/water/runner/H2ORunner.java
- h2o-core/src/test/java/water/runner/H2ORunnerAfters.java
- h2o-core/src/test/java/water/runner/H2ORunnerBefores.java
- h2o-core/src/test/java/water/runner/LocalTestRuntime.java
https://0xdata.atlassian.net/browse/PUBDEV-6542
Second attempt, pre-approved. Interferes with AAA_precloudlock - resolving this problem is the goal of this PR.
> PUBDEV-6542 - Improve leak detection in JUnit tests

- h2o-docs/src/product/performance-and-prediction.rst
Driveby fixes: Fixed typo and heading underlining
> PUBDEV-7155: Clarify Max F1 threshold for performance() and predict()

- h2o-hadoop-common/tests/python/pyunit_gcs_import.py
http://mr-0xc1:8080/blue/organizations/jenkins/h2o-3-rel-branch-merge/detail/h2o-3-rel-branch-merge/371/pipeline
> Jenkins automatic merge failure 01/07/2020

- h2o-core/src/main/java/water/H2O.java
https://0xdata.atlassian.net/browse/TN-16
> Added info about what "GC (Allocation Failure)" means

- h2o-core/src/main/java/water/DKVManager.java
DO NOT MERGE - Custom code for our customer.
https://0xdata.atlassian.net/projects/PUBDEV/issues/PUBDEV-7069?filter=myopenissues&orderby=priority%20DESC
> PUBDEV-7069 - Protection against non-valid(BAD) types in DKVClearTask

- h2o-docs/src/booklets/v2_2015/source/GLMBooklet.tex
- h2o-docs/src/product/data-science/glm.rst
The GLM booklet has been updated with information about support for HGLM.
See: https://0xdata.atlassian.net/browse/PUBDEV-7159
> PUBDEV-7159: GLM booklet update - HGLM

- h2o-docs/src/product/api-changes.rst
https://0xdata.atlassian.net/browse/PUBDEV-7215
> PUBDEV-7215: update documentation about API changes in AutoML since 3.28

- h2o-algos/src/test/java/hex/tree/drf/DRFConcurrent2Test.java
- h2o-core/src/main/java/water/fvec/Vec.java
Credit goes to https://github.com/SimonSchmid who found reported the issue and provided a reproducer. Thank you!
> PUBDEV-7193: Fix a race condition in addVec

- h2o-automl/src/main/java/ai/h2o/automl/AutoML.java
- h2o-automl/src/main/java/ai/h2o/automl/events/EventLogEntry.java
- h2o-py/tests/testdir_algos/automl/pyunit_automl_args.py
https://0xdata.atlassian.net/browse/PUBDEV-7194
> PUBDEV-7194: warn user if validation frame is set with CV enabled

- h2o-automl/src/main/java/ai/h2o/automl/ModelingStep.java
- h2o-automl/src/main/java/ai/h2o/automl/modeling/StackedEnsembleStepsProvider.java
- h2o-automl/src/test/java/ai/h2o/automl/AutoMLTest.java
- h2o-py/tests/testdir_algos/automl/pyunit_automl_memory_cleanup.py
- h2o-py/tests/testdir_algos/automl/pyunit_automl_model_selection.py
- h2o-py/tests/testdir_algos/automl/pyunit_automl_reruns.py
- h2o-r/tests/testdir_algos/automl/runit_automl_args.R
- h2o-r/tests/testdir_algos/automl/runit_automl_model_selection.R
https://0xdata.atlassian.net/browse/PUBDEV-7196
> PUBDEV-7196: do not train BestOfFamily Ensemble if there's only 1 family.

- h2o-r/h2o-DESCRIPTION.template
- h2o-r/h2o-package/R/connection.R
Fix needed ASAP to remain on CRAN: https://0xdata.atlassian.net/browse/PUBDEV-7220
> PUBDEV-7220: Update Java requirement in R package DESCRIPTION file

- h2o-extensions/xgboost/src/main/java/hex/tree/xgboost/XGBoost.java
- fixes issue for SW caused in PUBDEV-7164
> Use cloud lock status to determine if its time to start detecting xgb back-end

- scripts/benchmark_time_analysis.R
- scripts/jenkins/groovy/compareBenchmarksStage.groovy
> [PUBDEV-7047] update expected benchmark times to match the current status

- h2o-genmodel-extensions/xgboost/src/main/java/hex/genmodel/algos/xgboost/XGBoostMojoModel.java
- h2o-genmodel/src/main/java/hex/genmodel/GenModel.java
- h2o-genmodel/src/main/java/hex/genmodel/easy/EasyPredictModelWrapper.java
this is a quick and dirty solution and I dont like it, WDYT?
> [PUBDEV-7246] make EasyPredictModelWrapper support xgboost with offset

- docker/hadoop/common/hive-scripts/00_create_airlines.hql
- docker/hadoop/common/hive-scripts/00_create_chicago.hql
- h2o-hive/src/main/java/water/hive/HiveTableImporterImpl.java
- scripts/jenkins/groovy/buildConfig.groovy
- checked and this seems to be the only scalar type we are not supporting
> [HEXDEV-749] add support for hive bigint type

- scripts/jenkins/groovy/hadoopMultinodeStage.groovy
- also make hadoop jobs of multinode tests better identifiable
> [TEST] improve cleanup of multinode tests

- h2o-extensions/xgboost/src/main/java/hex/schemas/XGBoostV3.java
- h2o-extensions/xgboost/src/main/java/hex/tree/xgboost/XGBoostModel.java
- h2o-py/tests/testdir_algos/xgboost/pyunit_synonym_params_xgboost.py
- also remove n_estimators param since it was not exposed to clients
> [PUBDEV-7258] add test for synonymous XGBoost params

- build.gradle
- docker/hadoop/cdh/Dockerfile
- docker/hadoop/hdp/Dockerfile
- gradle/java.gradle
- gradle/publish.gradle
- gradle/scala.gradle
- gradle/wrapper/gradle-wrapper.properties
- h2o-assemblies/genmodel/build.gradle
- h2o-hadoop-2/assemblyjar.gradle
- h2o-hadoop-3/assemblyjar.gradle
- h2o-hadoop-3/h2o-cdp7.0-assembly/build.gradle
- h2o-test-integ/build.gradle
- scripts/jenkins/groovy/buildConfig.groovy
Also use older version of dev images (18)
Gradle 5.x doesn't support Java 13
> Revert back to Gradle 4

- h2o-core/src/main/java/water/AutoBuffer.java
- h2o-core/src/main/java/water/TimeLine.java
- h2o-core/src/test/java/water/AutoBufferTest.java
Test water.api.APIThrPriorTest is hanging on call to '/3/Timeline'
> Revert "PUBDEV-6818: Fix Unsupported Exception"

- h2o-py/h2o/model/metrics_base.py
- h2o-r/h2o-package/R/models.R
https://0xdata.atlassian.net/browse/PUBDEV-7272
> PUBDEV-7272: sensitivity aliased to wrong metric in Python (and for some methods in R)

- docker/scripts/install_R_version
- scripts/jenkins/groovy/buildConfig.groovy
- also make sure that when R package install fails, we know about it
> [DOCKER] fix R 3.3 installation

- docker/hadoop/common/hive-scripts/01_create_test_tables.hql
- h2o-hive/src/main/java/water/hive/JdbcHiveMetadata.java
- h2o-hive/tests/python/pyunit_hive_import.py
- scripts/jenkins/groovy/buildConfig.groovy
> [PUBDEV-7270] use prepared statements for parametrized SQL when getting partition metadata

- h2o-docs/src/product/data-science/aggregator.rst
The bug probably caused by copying the text from the GBM model.
JIRA: https://0xdata.atlassian.net/projects/PUBDEV/issues/PUBDEV-7298
> PUBDEV-7298 fix aggregator page

- h2o-extensions/xgboost/src/main/java/hex/tree/xgboost/XGBoost.java
- h2o-extensions/xgboost/src/test/java/hex/tree/xgboost/XGBoostMultiNodeTest.java
- h2o-extensions/xgboost/src/test/java/hex/tree/xgboost/XGBoostUtilsTest.java
> [PUBDEV-7279] exact tree method not supported in multinode

- h2o-algos/src/test/java/hex/glm/GLMBasicTestHGLM.java
Veronika: 
I looked at the url test link you sent me and was not able to figure out why the test failed.  I added a print statement at the end of the test to make sure it runs to completion.  Hope this can convince you of my diagnosis of test time out instead of something run with the test.
I realize this won't fix the time out problem but will confirm my diagnosis.
> fix testSemiconductorHGLM test

- h2o-r/h2o-package/R/frame.R
- h2o-r/h2o-package/R/models.R
Need to remove these because it's causing warnings on CRAN.  https://0xdata.atlassian.net/browse/PUBDEV-7309
> PUBDEV-7309: Removing undocumented ellipses from R docs

- h2o-docs/src/product/mojo-quickstart.rst
- h2o-docs/src/product/pojo-quickstart.rst
Updated FAQs for MOJOs and POJOs to indicate that all MOJOs/POJOs are thread safe except for Deep Learning
> PUBDEV-6964: Add to docs that MOJOs and POJOs are threadsafe

- h2o-docs/src/product/grid-search.rst
- h2o-docs/src/product/mojo-quickstart.rst
- h2o-docs/src/product/pojo-quickstart.rst
- h2o-docs/src/product/welcome.rst
- include minor updates to grid search and welcome topics
> Doc updates for PUBDEV-6964 into master

- h2o-algos/src/test/java/hex/DKVManagerTest.java
- h2o-core/src/main/java/water/DKVManager.java
- h2o-core/src/main/java/water/fvec/Frame.java
https://0xdata.atlassian.net/browse/PUBDEV-7271
> PUBDEV-7271 - Per-node sequential DKV manager

- h2o-py/tests/testdir_jira/pyunit_pubdev_6603.py
> Revert "PUBDEV-6603 - Test of frame deletion in Python is failing on assertion (#4342)"

- h2o-persist-s3/src/main/java/water/persist/IcedS3Credentials.java
- h2o-persist-s3/src/main/java/water/persist/PersistS3.java
- h2o-persist-s3/src/main/java/water/persist/PersistS3CredentialsV3.java
- h2o-persist-s3/src/main/java/water/persist/PersistS3Handler.java
- h2o-persist-s3/src/test/java/water/persist/PersistS3Test.java
- h2o-py/h2o/persist/persist.py
- h2o-py/tests/testdir_persist/pyunit_persistence.py
- h2o-r/h2o-package/R/import.R
https://0xdata.atlassian.net/browse/PUBDEV-7312
Marked for `3.28.0.4`
> PUBDEV-7312 - AWS Auth with session tokens

- h2o-py/docs/frame.rst
- h2o-py/h2o/targetencoder.py
https://0xdata.atlassian.net/browse/PUBDEV-7325
> PUBDEV-7325: Fixing Data Manipulation section in Py doc

- h2o-bindings/bin/gen_python.py
- h2o-py/docs/modeling.rst
- h2o-r/h2o-package/pkgdown/_pkgdown.yml
https://0xdata.atlassian.net/browse/PUBDEV-7323
see attachment in ticket above for new doc rendering
> PUBDEV-7323: Adding missing global functions to Py+R documentation

- h2o-core/src/main/java/water/H2ONode.java
Removing remaining references for external backend of Sparkling Water from H2O code base to keep it up-to-date
> [PUBDEV-7327][FollowUp] Remove code for external backend from H2O

- scripts/benchmark_time_analysis.R
- scripts/jenkins/groovy/compareBenchmarksStage.groovy
- continued effort to make bechmark builds green again
- take results from last two monts and update the calculation of expected results again
> [BENCH] update based on results from last two monts

- h2o-core/src/main/java/water/H2O.java
- h2o-persist-hdfs/src/main/java/water/persist/PersistHdfs.java
example:
java -jar h2o.jar -hdfs_config core-site.xml -hdfs_config hdfs-site.xml
> PUBDEV-7371: Add an option to specify multiple Hadoop config files

- h2o-r/tests/testdir_algos/deeplearning/runit_deeplearning_weights_and_biases.R
@Michalk pointed out that R CMD Check and R CRAN check have been failing.
From the error message, it looks like that it does not like F and insist on using FALSE.  I went to the file and changed all T to TRUE and F to FALSE.
> fix R CMD Check failure

- h2o-core/src/main/java/water/fvec/ByteVec.java
- h2o-core/src/main/java/water/fvec/FileVec.java
- h2o-core/src/main/java/water/fvec/FileVecUtils.java
- h2o-core/src/main/java/water/fvec/HDFSFileVec.java
- h2o-core/src/main/java/water/parser/ParseDataset.java
- h2o-core/src/main/java/water/persist/Persist.java
- h2o-core/src/main/java/water/persist/PersistManager.java
- h2o-core/src/test/java/water/fvec/FileVecUtilsTest.java
- h2o-hadoop-common/tests_multinode/R/runit_parquet_pubdev7293.R
- h2o-parsers/h2o-orc-parser/src/main/java/water/parser/orc/OrcParserProvider.java
- h2o-parsers/h2o-parquet-parser/src/main/java/water/parser/parquet/ParquetParserProvider.java
- h2o-parsers/h2o-parquet-parser/src/main/java/water/parser/parquet/VecParquetReader.java
- h2o-parsers/h2o-parquet-parser/src/main/java/water/parser/parquet/VecReaderEnv.java
- h2o-parsers/h2o-parquet-parser/src/test/java/water/parser/parquet/VecReaderEnvTest.java
- h2o-persist-hdfs/src/main/java/water/persist/PersistHdfs.java
- h2o-persist-hdfs/src/test/java/water/persist/PersistHdfsTest.java
https://0xdata.atlassian.net/browse/PUBDEV-7293
> PUBDEV-7293: Make sure we don't overload first node when parsing 40k+ Parquet files

- h2o-core/src/main/java/water/H2O.java
- h2o-core/src/test/java/water/TestUtil.java
- h2o-extensions/target-encoder/testMultiNode.sh
- h2o-extensions/target-encoder/testSingleNode.sh
- h2o-extensions/xgboost/src/test/java/hex/tree/xgboost/XGBoostParamsTest.java
transferring https://github.com/h2oai/h2o-3/pull/4097 to release branch
Aside from increasing timeout we also reduce number of clouds for multinode testing.
Note: check that auto-merge to master is fine
> PUBDEV-7373: Allocate more time for clouding to fix Cloud 1 under 4 issue

- h2o-algos/src/main/java/hex/generic/Generic.java
- h2o-algos/src/main/java/hex/generic/GenericModelOutput.java
- h2o-algos/src/test/java/hex/generic/GenericModelTest.java
- h2o-core/src/main/java/hex/ModelMetricsBinomialGLMGeneric.java
- h2o-core/src/main/java/hex/ModelMetricsBinomialGeneric.java
- h2o-core/src/main/java/hex/ModelMetricsMultinomialGLMGeneric.java
- h2o-core/src/main/java/hex/ModelMetricsMultinomialGeneric.java
- h2o-core/src/main/java/hex/ModelMetricsOrdinalGLMGeneric.java
- h2o-core/src/main/java/hex/ModelMetricsOrdinalGeneric.java
- h2o-core/src/main/java/hex/ModelMetricsRegressionGeneric.java
- h2o-core/src/main/java/water/api/schemas3/ModelMetricsMultinomialGLMGenericV3.java
- h2o-core/src/main/java/water/api/schemas3/ModelMetricsOrdinalGLMGenericV3.java
- h2o-core/src/main/java/water/api/schemas3/ModelMetricsOrdinalGenericV3.java
- h2o-core/src/main/java/water/api/schemas3/ModelMetricsRegressionGenericV3.java
- h2o-genmodel/src/main/java/hex/genmodel/algos/deeplearning/DeeplearningMojoReader.java
- h2o-genmodel/src/main/java/hex/genmodel/algos/tree/SharedTreeMojoModel.java
- h2o-genmodel/src/main/java/hex/genmodel/attributes/DeepLearningModelAttributes.java
- h2o-genmodel/src/main/java/hex/genmodel/attributes/SharedTreeModelAttributes.java
- h2o-genmodel/src/main/java/hex/genmodel/attributes/VariableImportances.java
- h2o-py/tests/testdir_generic_model/pyunit_generic_model_mojo_deeplearning.py
- h2o-r/h2o-package/R/classes.R
- h2o-r/tests/testdir_algos/generic/runit_generic_model_mojo_deeplearning.R
https://0xdata.atlassian.net/browse/PUBDEV-7167
- Enabled Deep Learning Mojo to be importable as Generic model, as it is thread safe already.
- Tested importability, scoring and saveability by means of JUnit
- Tested model metrics and model description output to be the same as original's in both Python and R
- Fixed a small bug in R, where R-squared was not shown for DeepLearning models.
<details>
<summary>Output of Original algorithm</summary>
```
[1] "Model Details:"                                                                                                                                                              
[2] "==============" …
```
> PUBDEV-7167 - DeepLearning MOJO support in Generic Model

- h2o-algos/src/main/java/hex/tree/SharedTreeModel.java
- h2o-algos/src/test/java/hex/tree/gbm/GBMTest.java
- h2o-genmodel/src/main/java/hex/genmodel/CategoricalEncoding.java
- h2o-genmodel/src/main/java/hex/genmodel/easy/EnumEncoderColumnMapper.java
- h2o-genmodel/src/main/java/hex/genmodel/easy/EnumLimitedEncoder.java
- h2o-genmodel/src/main/java/hex/genmodel/easy/EnumLimitedEncoderColumnMapper.java
- h2o-genmodel/src/main/java/hex/genmodel/easy/EnumLimitedEncoderDomainMapConstructor.java
- h2o-genmodel/src/test/java/hex/genmodel/easy/EnumLimitedColumnMapperTest.java
- h2o-genmodel/src/test/java/hex/genmodel/easy/EnumLimitedDomainMapConstructorTest.java
- h2o-genmodel/src/test/java/hex/genmodel/easy/EnumLimitedEncoderTest.java
https://0xdata.atlassian.net/browse/PUBDEV-7304
> PUBDEV-7304: Add GBM POJO support for SortByResponse and EnumLimited encodings

- h2o-algos/src/test/java/hex/generic/GenericModelTest.java
- Predictions of generic models are compared with original model predictions as well, not only with pure GenModel/Mojo via testJavaScoring.
- Manual DKV management of each Keyed entry has been replaced by Scope management for every test method.
**No new functionality added in this PR.** Only test refactoring and enhancement.
> Generic model predictions are compares with original model predictions. Scope management used test-wide.

- h2o-py/tests/testdir_jira/pyunit_pubdev_4702_algo_max_runtime_secs_large.py
- h2o-r/tests/testdir_jira/runit_pubdev_4702_algo_max_runtime_secs_large.R
OMG:  I forgot to add seed to the appropriate algos.
> Added seed for algos when applicable.

- h2o-bindings/bin/custom/R/gen_coxph.py
- h2o-bindings/bin/custom/R/gen_drf.py
- h2o-bindings/bin/custom/R/gen_isolationforest.py
- h2o-bindings/bin/custom/R/gen_psvm.py
- h2o-bindings/bin/custom/R/gen_word2vec.py
- h2o-bindings/bin/custom/R/gen_xgboost.py
- h2o-r/h2o-package/R/communication.R
- h2o-r/h2o-package/R/coxph.R
- h2o-r/h2o-package/R/export.R
- h2o-r/h2o-package/R/frame.R
- h2o-r/h2o-package/R/isolationforest.R
- h2o-r/h2o-package/R/kvstore.R
- h2o-r/h2o-package/R/models.R
- h2o-r/h2o-package/R/psvm.R
- h2o-r/h2o-package/R/randomforest.R
- h2o-r/h2o-package/R/w2vutils.R
- h2o-r/h2o-package/R/word2vec.R
- h2o-r/h2o-package/R/xgboost.R
https://0xdata.atlassian.net/browse/PUBDEV-7387
> PUBDEV-7387: Fixing all the problematic R examples 

- h2o-core/src/main/java/water/H2O.java
- h2o-core/src/main/java/water/util/Log.java
- h2o-core/src/test/java/water/util/LogTest.java
- h2o-py/h2o/backend/server.py
- h2o-py/h2o/h2o.py
Keep `RollingFileAppender`
Make size configurable
Add test
JIRA: https://0xdata.atlassian.net/projects/PUBDEV/issues/PUBDEV-7171
> PUBDEV-7171 "Unlimited" log file size update

- h2o-algos/src/main/java/hex/glm/ComputationState.java
- h2o-algos/src/main/java/hex/glm/GLM.java
- h2o-algos/src/main/java/hex/glm/GLMMetricBuilder.java
- h2o-algos/src/main/java/hex/glm/GLMModel.java
- h2o-algos/src/main/java/hex/glm/GLMScore.java
- h2o-algos/src/main/java/hex/glm/GLMTask.java
- h2o-algos/src/main/java/hex/schemas/GLMModelV3.java
- h2o-algos/src/main/java/hex/schemas/GLMV3.java
- h2o-algos/src/test/java/hex/glm/GLMBasicTestBinomial.java
- h2o-algos/src/test/java/hex/glm/GLMTest.java
- h2o-genmodel/src/main/java/hex/genmodel/GenModel.java
- h2o-genmodel/src/main/java/hex/genmodel/algos/glm/GlmMojoModel.java
- h2o-py/h2o/estimators/glm.py
- h2o-py/tests/testdir_algos/glm/pyunit_pubdev_6037_fractionalbinomial_pojo_mojo.py
- h2o-r/h2o-package/R/glm.R
- h2o-r/tests/testdir_algos/glm/runit_PUBDEV_6037_fractionalbinomial_mojo.R
This PR completes the work for this JIRA: https://0xdata.atlassian.net/browse/PUBDEV-6037?filter=-1.
Work done:
1. added java backend code to support fractional binomial family.
2. correct model implementation with model metrics, scoring
3. pojo/mojo scoring. 
4. added Java/Python/R unit tests.
> PUBDEV-6037: add fractional binomial to GLM family supported.

- h2o-py/h2o/backend/cluster.py
- h2o-py/tests/testdir_apis/H2O_Module/pyunit_h2ocluster_status.py
https://0xdata.atlassian.net/projects/PUBDEV/issues/PUBDEV-7234
> PUBDEV-7234_return_cluster_info_in_2D_table

- h2o-py/h2o/backend/server.py
Fix failing pyunit tests due to max_log_file_size check.
> PUBDEV-7171 fix max_log_file_size check

- h2o-docs/src/product/performance-and-prediction.rst
Add more information about ohw labels are calculated for binary and multiclass classification problems
> PUBDEV-7407: Doc updates to performance and prediction section

- h2o-py/h2o/backend/cluster.py
remove [].copy() as not supported in Py2.7., use comprehensions to improve 2D iterations readability
> PUBDEV-7234: fix for Py 2.7

- h2o-bindings/bin/custom/R/gen_targetencoder.py
- h2o-r/h2o-package/R/targetencoder.R
https://0xdata.atlassian.net/browse/PUBDEV-7406
Used the example provided by @ledell in the JIRA.
> PUBDEV-7406 - Target Encoding R example code is broken

- h2o-py/tests/testdir_algos/automl/pyunit_automl_model_selection.py
removing algos from the runtime exploitation test
> PUBDEV-6293: test fix

- h2o-docs/src/product/automl.rst
- h2o-docs/src/product/faq/general.rst
https://0xdata.atlassian.net/browse/PUBDEV-7416
> PUBDEV-7416: Added citation section to AutoML User Guide page

- h2o-docs/src/product/data-science/gam.rst
- h2o-docs/src/product/flow.rst
Changed:
- k > num_knots
- knots_keys > knot_ids
- save_gam_cols > keep_gam_cols
Updated description fo some parameters.
Fixed examples after testing.
> Docs: Updated GAM parameters names

- h2o-hive/src/main/java/water/hive/DelegationTokenRefresher.java
- h2o-hive/src/main/java/water/hive/HiveTokenGenerator.java
- h2o-mapreduce-generic/src/main/java/water/hadoop/h2odriver.java
- scripts/jenkins/groovy/defineTestStages.groovy
- scripts/jenkins/groovy/hadoopCommands.groovy
- scripts/jenkins/groovy/hadoopStage.groovy
- scripts/jenkins/groovy/kerberosCommands.groovy
feature aimed mainly at steam and sw
> [PUBDEV-7421] ability to prepare hive token before h2o submit

- h2o-docs/src/product/data-science/aggregator.rst
- h2o-docs/src/product/data-science/algo-params/sample_size.rst
- h2o-docs/src/product/data-science/coxph.rst
- h2o-docs/src/product/data-science/deep-learning.rst
- h2o-docs/src/product/data-science/drf.rst
- h2o-docs/src/product/data-science/gam.rst
- h2o-docs/src/product/data-science/gbm.rst
- h2o-docs/src/product/data-science/glm.rst
- h2o-docs/src/product/data-science/glrm.rst
- h2o-docs/src/product/data-science/if.rst
- h2o-docs/src/product/data-science/k-means.rst
- h2o-docs/src/product/data-science/naive-bayes.rst
- h2o-docs/src/product/data-science/pca.rst
- h2o-docs/src/product/data-science/stacked-ensembles.rst
- h2o-docs/src/product/data-science/svm.rst
- h2o-docs/src/product/data-science/word2vec.rst
- h2o-docs/src/product/data-science/xgboost.rst
Original PUBDEV-7372 (https://github.com/h2oai/h2o-3/pull/4422)  for 3.28.1.x.
> PUBDEV-7372: Create an Example section for each algo topic

- h2o-py/docs-requirements.txt
- scripts/jenkins/groovy/buildConfig.groovy
Confirmed that other requirements listed here are also compatible.
> Use a version of sphinx and sphinx_substitution_extensions that support Py3.5

- h2o-algos/build.gradle
- h2o-core/build.gradle
- h2o-webserver-iface/build.gradle
- uprade servlet-api dep to 3.0 works around the issue
> [build] fix running unit tests in IDEA

- h2o-genmodel/src/main/java/hex/genmodel/tools/PrintMojo.java
merged this to master, so cherry-picking to release
> PUBDEV-7089 Add info message instead of NPE in case of wrong usage of PrintMojo

- h2o-docs/src/product/automl.rst
https://0xdata.atlassian.net/browse/PUBDEV-7461
> PUBDEV-7461: Add information about the h2o.get_leaderboard function to the AutoML User Guide page

- h2o-algos/src/main/java/hex/gam/GAM.java
- h2o-algos/src/main/java/hex/gam/GAMModel.java
- h2o-algos/src/main/java/hex/gam/MatrixFrameUtils/AddGamColumns.java
- h2o-algos/src/main/java/hex/gam/MatrixFrameUtils/GamUtils.java
- h2o-algos/src/main/java/hex/glm/ComputationState.java
- h2o-algos/src/main/java/hex/glm/GLM.java
- h2o-algos/src/main/java/hex/glm/GLMTask.java
- h2o-algos/src/main/java/hex/glm/GLMUtils.java
- h2o-algos/src/main/java/hex/gram/Gram.java
- h2o-algos/src/test/java/hex/gam/GamTestPiping.java
- h2o-py/tests/testdir_algos/gam/pyunit_PUBDEV_7181_check_model_scoring.py
- h2o-py/tests/testdir_algos/gam/pyunit_PUBDEV_7181_compare_R.py
- h2o-py/tests/testdir_algos/gam/pyunit_PUBDEV_7460_gam_accuracy_others.py
- h2o-py/tests/testdir_algos/gam/pyunit_PUBDEV_7460_gam_hit_ratios_others_large.py
The work in this PR is for JIRA: https://0xdata.atlassian.net/projects/PUBDEV/issues/?filter=myopenissues
Apart from verifying that all the associated metrics work for GAM, I have also done the following:
1. Fixed bug in adaptedTestforTrain.
2.  Fixed standardized coefficients to be sorted in decreasing order of magnitudes.
3. Added support/test for validation frame.
4. Tests are added in Python and Java to make sure that my addition works.
I was not able to add the cross-validation in here but has opened an JIRA to make sure this one will make be installed.
> PUBDEV-7460: Added pyunit test to double check on various modelmetrics.

- h2o-docs/src/product/save-and-load-model.rst
- h2o-py/tests/testdir_generic_model/pyunit_mojo_import.py
- h2o-r/h2o-package/R/export.R
- h2o-r/h2o-package/R/models.R
- h2o-r/tests/testdir_algos/generic/runit_generic_mojo_convenience.R
- h2o-r/tests/testdir_misc/runit_saveMojo.R
https://0xdata.atlassian.net/browse/PUBDEV-7470
> PUBDEV-7470 - Document and test upload/download and import/save MOJO in pairs.

- h2o-bindings/bin/custom/python/gen_targetencoder.py
- h2o-docs/src/product/data-munging.rst
- h2o-docs/src/product/data-munging/target-encoding.rst
- h2o-extensions/target-encoder/src/main/java/ai/h2o/targetencoding/TargetEncoder.java
- h2o-py/h2o/estimators/targetencoder.py
- h2o-py/tests/testdir_algos/automl/target_encoding/pyunit_automl_gbm_target_encoding.py
- h2o-py/tests/testdir_algos/automl/target_encoding/pyunit_old_te_performance_docs_demo_titanic.py
- h2o-py/tests/testdir_algos/automl/target_encoding/pyunit_target_encoding_model.py
- h2o-py/tests/testdir_algos/automl/target_encoding/pyunit_te_performance_docs_demo_titanic.py
- h2o-r/tests/testdir_algos/targetencoder/runit_old_targetencoder_model_docs_demo.R
- h2o-r/tests/testdir_algos/targetencoder/runit_targetencoder_model_docs_demo.R
See PR https://github.com/h2oai/h2o-3/pull/4474, which was already merged into master.
> PUBDEV-7020: Merging changes from PR 4474 into rel-zahradnik

- h2o-hive/src/main/java/water/hive/DelegationTokenPrinter.java
- h2o-hive/src/main/java/water/hive/DelegationTokenRefresher.java
- h2o-hive/src/main/java/water/hive/GenerateHiveToken.java
- h2o-hive/src/main/java/water/hive/HiveTokenGenerator.java
- scripts/jenkins/Makefile.jenkins
- scripts/jenkins/groovy/hadoopCommands.groovy
- scripts/jenkins/groovy/hadoopStage.groovy
- scripts/jenkins/groovy/kerberosCommands.groovy
> [PUBDEV-7484] test for token refresh working in supported scenarios

- h2o-algos/src/main/java/hex/ensemble/StackedEnsemble.java
- h2o-algos/src/main/java/hex/ensemble/StackedEnsembleModel.java
- h2o-algos/src/main/java/hex/schemas/StackedEnsembleV99.java
- h2o-algos/src/test/java/hex/ensemble/StackedEnsembleTest.java
- h2o-py/h2o/estimators/stackedensemble.py
- h2o-r/h2o-package/R/stackedensemble.R
https://0xdata.atlassian.net/browse/PUBDEV-7463
This PR consists of two changes:
- Parallel scoring of base models
- Optionally using random subset of training data to calculate training metrics
- I created `training_scoring_subsample_size` property so user can specify what size (s)he wants to use. -1 uses the whole training frame.
N.B. `training_scoring_subsample_size` probably isn't the best name so if you have better ideas I will be happy to change it I just can't think of anything better right now.
> PUBDEV-7463: Speed up training and prediction of Stacked Ensemble

- h2o-r/h2o-package/R/models.R
- h2o-r/h2o-package/pkgdown/_pkgdown.yml
JIRA: https://0xdata.atlassian.net/browse/PUBDEV-7509
> PUBDEV-7509 Add h2o.reset_threshold and h2o.upload_mojo to the R doc list

- h2o-algos/src/main/java/hex/ensemble/StackedEnsembleModel.java
Influences SE only when the SE doesn't use any base model for
prediction, e.g., GLM metalearner uses intercept as the only predictor.
> Fix issue introduced in PUBDEV-7463 that causes some SE related tests to fail

- scripts/jenkins/groovy/defineTestStages.groovy
Per instruction from @michalk, I have added merge as a stage in our benchmarking.
> Add merge to ml-benchmark algorithms to check.

- scripts/jenkins/groovy/defineTestStages.groovy
> Add sort stage to ml-benchmark

- h2o-r/h2o-package/R/automl.R
- h2o-r/tests/testdir_algos/automl/runit_automl_demo_for_api_documentation.R
see https://0xdata.atlassian.net/browse/PUBDEV-7103
Prostate dataset shows that ensemble is winning. We may consider another dataset to put as an example ( without a need to factorise response for example).
> PUBDEV-7103:  changed examples for AutoML's R api

- gradle/publish.gradle
> [build] Gradle conditional signing only for public release.

- build.gradle
- gradle/scala.gradle
- temporary work-around, will be removed in master
> [build] fix publishing of scaladoc jars

- h2o-r/h2o-package/R/automl.R
- h2o-r/h2o-package/R/frame.R
https://0xdata.atlassian.net/browse/PUBDEV-7549
Tested locally, but I am not sure if it's worth it to make an automated test for this change since I would probably need to install/uninstall packages during the test and the test itself would be more complex than the actual change.
> PUBDEV-7549: Suppress data.table warning messages inside h2o.automl() in R

- h2o-py/tests/pyunit_utils/utilsPY.py
This PR completes the task in JIRA: https://0xdata.atlassian.net/browse/PUBDEV-7562
In Python pyunit_utils.py, the compare_frames will ask for frame elements one entry at a time from Java backend, this is not efficient.  I have changed the following methods to grab whole chunks of data from h2o backend instead of one entry at a time
-compare_numeric_frames : deleted
-compareOneNumericColumn: deleted
-compareOneStringColumn: deleted
-compare_frames: call compare_one_column_local method now
> PUBDEV-7562 consolidate compare frame to one method

- h2o-core/src/main/java/water/rapids/Env.java
- h2o-core/src/main/java/water/rapids/Merge.java
- h2o-core/src/main/java/water/rapids/ast/prims/filters/dropduplicates/AstDropDuplicates.java
- h2o-core/src/main/java/water/rapids/ast/prims/filters/dropduplicates/CollectChunkBorderValuesTask.java
- h2o-core/src/main/java/water/rapids/ast/prims/filters/dropduplicates/ColumnIndicesParser.java
- h2o-core/src/main/java/water/rapids/ast/prims/filters/dropduplicates/DropDuplicateRows.java
- h2o-core/src/main/java/water/rapids/ast/prims/filters/dropduplicates/DropDuplicateRowsTask.java
- h2o-core/src/main/java/water/rapids/ast/prims/filters/dropduplicates/KeepOrder.java
- h2o-core/src/test/java/water/rapids/ast/prims/filters/dropduplicates/AstDropDuplicatesTest.java
- h2o-core/src/test/java/water/rapids/ast/prims/filters/dropduplicates/ColumnIndicesParserTest.java
- h2o-core/src/test/java/water/rapids/ast/prims/filters/dropduplicates/DropDuplicateRowsTest.java
- h2o-py/h2o/frame.py
- h2o-py/tests/testdir_filter/pyunit_drop_duplicates.py
- h2o-py/tests/testdir_filter/pyunit_drop_duplicates_pandas.py
- h2o-r/h2o-package/R/frame.R
- h2o-r/tests/testdir_filters/runit_drop_duplicates.R
https://0xdata.atlassian.net/browse/PUBDEV-3292
> PUBDEV-3292 - Drop duplicate observations

- h2o-docs/src/product/api-changes.rst
- h2o-docs/src/product/conf.py
Driveby fixes:
- fixed some formatting
- rearranged so that newer api changes appear first
> PUBDEV-7585: Minor doc update. Add the removed XGBoost params to API-related Changes

- h2o-docs/src/product/flow.rst
- h2o-docs/src/product/performance-and-prediction.rst
- In the Flow chapter, noted that PDPs can be returned for binary or multiclass classification
- In the Performance and Prediction chapter, noted that PDPs can be returned for multiclass classification and added a link to the pdp for multiclass ipynb demo. Also added an example showing how to retrieve 2dim pdps. 
Driveby fix: formatting fix in Prediction section.
> PUBDEV-7576: Doc updates to PDP topics

- h2o-core/src/main/java/water/rapids/ast/prims/filters/dropduplicates/DropDuplicateRows.java
- h2o-core/src/test/java/water/rapids/ast/prims/filters/dropduplicates/AstDropDuplicatesTest.java
- h2o-core/src/test/java/water/rapids/ast/prims/filters/dropduplicates/DropDuplicateRowsTest.java
Only reproducible on multinode.
> Fix leaking vec in DropDuplicateRows

- h2o-automl/src/main/java/ai/h2o/automl/modeling/StackedEnsembleStepsProvider.java
- h2o-automl/src/test/java/ai/h2o/automl/ModelingStepRegistryTest.java
- h2o-py/tests/testdir_algos/automl/pyunit_automl_interpretability.py
Fix for bad name introduced in https://github.com/h2oai/h2o-3/pull/4627
jira: https://0xdata.atlassian.net/browse/PUBDEV-7547
> Rename monotonic SE from PUBDEV-7547

- Changes.md
This PR assumes the release date is today, but will update that if the release is pushed back.
> PUBDEV-7583: Release notes for 3.30.0.4 release

- h2o-r/tests/runitUtils/utilsR.R
- h2o-r/tests/testdir_javapredict/runit_PUBDEV_5058_PUBDEV_5723_glrm_mojo_large.R
I changed the enum columns to numeric columns before calling compareFrame.
> Fix runit_PUBDEV_5058_PUBDEV_5723_glrm_mojo failure

- h2o-algos/src/main/java/hex/api/MakeGLMModelHandler.java
- h2o-py/tests/testdir_algos/glm/pyunit_glm_makeGLMModel_PUBDEV_5442.py
- h2o-py/tests/testdir_algos/glm/pyunit_glm_makeGLMModel_PUBDEV_5442_gaussian.py
This PR fixes the bug in JIRA: https://0xdata.atlassian.net/browse/PUBDEV-5442?filter=-1
I have added a check to make sure the coefficients passed to makeGLMModel equals to the coefficients length of the GLM model.
> PUBDEV-5442-check makeGLMModel coefficients

- docker/public/Dockerfile-h2o-release
- scripts/jenkins/Makefile.jenkins
- scripts/jenkins/jenkinsfiles/Jenkinsfile-Nightly
- scripts/jenkins/jenkinsfiles/Jenkinsfile-Release
https://0xdata.atlassian.net/browse/PUBDEV-7586
> PUBDEV-7586 - Create official Docker hub image

- h2o-py/h2o/__init__.py
https://0xdata.atlassian.net/browse/PUBDEV-7593
> PUBDEV-7593 h2o version fix when running from whl

- h2o-mapreduce-generic/src/main/java/water/hadoop/h2odriver.java
- scripts/jenkins/groovy/hadoopMultinodeStage.groovy
- also test it in multinode env
> [PUBDEV-7599] fix allow_insecure_xgboost on hadoop

- h2o-py/tests/testdir_algos/aggregator/pyunit_aggregator_mapping_frame.py
S3 contains now the `smalldata/wine/winequality-redwhite-no-BOM.csv`.
> Fix pyunit_aggregator_mapping_frame

- h2o-algos/src/main/java/hex/deeplearning/DeepLearning.java
- h2o-algos/src/main/java/hex/deeplearning/DeepLearningModel.java
- h2o-algos/src/main/java/hex/tree/Score.java
- h2o-algos/src/test/java/hex/deeplearning/DeepLearningTest.java
- h2o-core/src/main/java/hex/Model.java
- h2o-core/src/main/java/hex/ModelBuilder.java
- h2o-core/src/main/java/hex/ModelMetricsRegression.java
https://0xdata.atlassian.net/browse/PUBDEV-7573
> PUBDEV-7573 DeepLearning cross validation fix for distribution AUTO representing Huber

- h2o-algos/src/test/java/hex/tree/drf/DRFTest.java
- h2o-genmodel/src/main/java/hex/genmodel/algos/tree/SharedTreeMojoModel.java
https://0xdata.atlassian.net/browse/PUBDEV-7590
> PUBDEV-7596: Make leaf node assignment work for tree-depths >= 31

- h2o-algos/src/main/java/hex/api/MakeGLMModelHandler.java
- h2o-algos/src/main/java/hex/glm/GLMModel.java
- h2o-algos/src/test/java/hex/glm/GLMTest.java
- h2o-core/src/main/java/water/util/ArrayUtils.java
- h2o-py/h2o/model/model_base.py
- h2o-py/tests/testdir_algos/glm/pyunit_PUBDEV_6424_multinomial_makeGLMModel.py
- h2o-py/tests/testdir_algos/glm/pyunit_PUBDEV_6424_negbinomial_makeGLMModel.py
- h2o-py/tests/testdir_algos/glm/pyunit_PUBDEV_6424_ordinal_makeGLMModel.py
This PR completes the task in JIRA: https://0xdata.atlassian.net/browse/PUBDEV-6424?filter=-1
I have added the capability to make a GLM multinomial model to makeGLMModel and a test to go with it.
> PUVDEV-6424 add multinomial makeGLMModel

- h2o-algos/src/main/java/hex/glm/GLM.java
- h2o-algos/src/main/java/hex/glm/GLMModel.java
- h2o-algos/src/test/java/hex/glm/GLMBasicTestBinomial.java
- h2o-algos/src/test/java/hex/glm/GLMBasicTestMultinomial.java
- h2o-algos/src/test/java/hex/glm/GLMBasicTestRegression.java
- h2o-algos/src/test/java/hex/glm/GLMTest.java
https://0xdata.atlassian.net/browse/PUBDEV-7444
> PUBDEV-7444 add AUTO option for the family parameter of GLM

- h2o-core/src/main/java/hex/Model.java
- h2o-genmodel/src/main/java/hex/ModelCategory.java
- h2o-genmodel/src/main/java/hex/genmodel/algos/klime/KLimeMojoModel.java
- h2o-genmodel/src/main/java/hex/genmodel/algos/klime/KLimeMojoReader.java
- h2o-genmodel/src/main/java/hex/genmodel/easy/EasyPredictModelWrapper.java
- h2o-genmodel/src/main/java/hex/genmodel/easy/prediction/KLimeModelPrediction.java
* This PR ports d26422b5fcc6796c30ae84ee59de069bfbe4676e to `rel-zahradnik`
> k-LIME genmodel
