h2o-py/h2o/connection.py

output for sys.platform on windows is 'win32' not 'windows'.
https://docs.python.org/2/library/sys.html#sys.platform

fixed sys.platform for windows os.

---

h2o-py/h2o/connection.py
h2o-py/h2o/h2o.py

I was just at h2o-world and was having trouble connecting to h2o (in Python) through my company proxy. Here's a (really) rough spike adding a proxy parameter to the h2o connection that requests already supports. My hand testing suggests that it works for at least initialization and simple model builds.

Add proxy support

---

h2o-r/h2o-package/R/models.R

replaced \code{link{}} with \code{\link{}} to get correct links.

fixed links in help of predict function

---

h2o-r/h2o-package/R/models.R

When h2o.performance is used with plot.H2OBinomialMetrics then there can be both x@on_train and x@on_valid FALSE. Then it is just confusing when (on valid) is displayed.

Fix on valid message when h2o.performance is used

---

h2o-py/h2o/frame.py
h2o-py/h2o/utils/shared_utils.py
h2o-py/tests/testdir_jira/pyunit_pubdev_2891.py

Hello! 
This commit fixes bug PUBDEV-2891 (the test for it is currently set to NOPASS). It also fixes another bug that did not respect the header argument for python objects. Both fixes are tested in pyunit_pubdev_2891.py.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/h2oai/h2o-3/41)

PUBDEV-2891 & respect header=1 for python_obj

---

h2o-core/src/main/java/water/nbhm/NonBlockingHashMap.java
h2o-core/src/main/java/water/parser/BufferedString.java
h2o-core/src/main/java/water/parser/CsvParser.java
h2o-core/src/test/java/water/parser/ParserTest.java

Parser column heuristic was getting fooled if 1st 2 rows had unequal col counts, plus also equal counts of blanks.
String hashcode varies by 1 for strings which vary by last character; NBHM hash spreader did not spread the low bits; runs of strings that just walk up the alphabet turn into sequential slots in NBHM, which then degrades to a linear scan.  Provoked an O(n^2) bug in parser enum unification.  Hot BufferedString.hashCode was obfuscated with accessors (and showed up in all profiles because was being called O(n^2) times).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/h2oai/h2o-3/43)

Fix real bugs, perf bugs in parser, nbhm hashcode,

---

h2o-r/README.md
h2o-r/build.gradle
h2o-r/h2o-DESCRIPTION.template

h2o-r/README.md:
h2o-r/build.gradle:
h2o-r/h2o-DESCRIPTION.template:
---
Tested on latest H2O and R 3.3.0 using [this](https://github.com/jangorecki/dockerfiles/blob/master/h2o-dev/Dockerfile) image. There was no R 3.3.0 related code used so should pass R 3.2.2 tests in jenkins.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/h2oai/h2o-3/48)

h2o-r: simpler install and minor fixes

---

h2o-core/src/test/java/water/parser/ParserTest.java

allow external testers to easily build custom parsable strings
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/h2oai/h2o-3/49)

make test utility public for external users

---

h2o-py/h2o/connection.py
h2o-r/h2o-package/R/connection.R

allows to avoid hardcoding ip and port in R scripts.
Useful for automation by configuring cluster details in bash.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/h2oai/h2o-3/51)

dynamic default of cluster connection in h2o.init

---

h2o-core/src/main/java/water/fvec/NewChunk.java
h2o-core/src/test/java/water/fvec/NewChunkTest.java

1st bug: after flipping to sparse after adding 16 0 cat's, the 17th (and later) 0 cat was not added sparsely.
2nd bug: in a column with mixed sparse 0's and non-sparse 0's, the cat type was lost even if only ever "NewChunk.addCategorical") was called, and the chunk was declared numeric... and the non-sparse 0 cat's got converted to NA's.  Later the whole column could still be declared categorical.  Effect was to convert a bunch of 0's to NA's.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/h2oai/h2o-3/53)

bugfix with sparse categoricals

---

h2o-core/src/test/java/water/parser/ParseTimeTest.java

Bunch of tests in ParseTimeTest is failing in EST timezone because they rely on PST timezone. These tests were added recently (2016-05-24).
The fix is to make tz adjustments in the expected time represented by ms since start of the epoch.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/h2oai/h2o-3/61)

Fix timezone handling in ParseTimeTest. Tests were failing in EST tz

---

h2o-persist-s3/src/main/java/water/persist/PersistS3.java

The ProfileCredentialsProvider reads configuration from ~/.aws/credentials.properties.
The way used by MarkC's customer.
Critical for release.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/h2oai/h2o-3/63)

[PUBDEV-3180] ProfileCredentialsProvider appended to auth chain for S3 access

---

h2o-core/src/main/java/water/api/FramesHandler.java
h2o-core/src/main/java/water/api/schemas3/FramesV3.java
h2o-core/src/main/java/water/fvec/Frame.java
h2o-core/src/main/java/water/persist/Persist.java
h2o-core/src/main/java/water/persist/PersistFS.java
h2o-core/src/main/java/water/persist/PersistManager.java
h2o-core/src/main/java/water/util/FrameUtils.java
h2o-core/src/test/java/water/fvec/ExportTest.java
h2o-persist-hdfs/src/main/java/water/persist/PersistHdfs.java
h2o-r/h2o-package/R/constants.R
h2o-r/h2o-package/R/export.R
h2o-r/tests/testdir_misc/runit_export_file.R

@tomasnykodym This is an initial implementation of parallel CSV export.
Parallel export is exposed in
- REST API,
- R API.
Support for Python and Flow will be handled separately.
This PR also provides considerable speed-up of non-parallel CSV Export and CSV Download.
I tested the code on airlines/allyears.1987.2013.csv (approx 15GB data, hex compressed 5GB) running on 4-node H2O cluster.
4 tests were performed:
1. Original H2O implementation v3.8.3.4: 50 minutes
2. PR implementation, export to single file: 10 minutes
3. PR implementation, export to multiple parts (automatically determined): 1 minute
4. PR implementation, export to multiple parts (given number, num_parts = 7): 3 minutes.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" …

PUBDEV-3201: Implementation of parallel CSV export

---

h2o-core/src/main/java/water/fvec/NewChunk.java
h2o-core/src/test/java/water/fvec/NewChunkTest.java

New Chunk was not clearing bitset with NAs markers when switching to sparse (compressing to the left) which resulted into non-NA values being turned into NAs.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/h2oai/h2o-3/88)

Simple fix in the new chunk + added test.

---

h2o-core/src/main/java/water/rapids/ast/prims/advmath/AstCorrelation.java
h2o-core/src/main/java/water/util/ArrayUtils.java
h2o-r/h2o-package/R/frame.R
h2o-r/tests/testdir_munging/unop/runit_cor_matrix.R

Modified docstring to show `uses` in h2o.var() and h2o.cor()
Modified calculation of Pearson Correlation Coefficient:
- Removed CorTaskCompleteObs and now use CorTask as main worker in calculating correlation.
- Removed CorTaskCompleteObsMean and now use CorMean to get mean across Vecs/columns.
- Added another runit for h2o.cor(). Matches base R implementation. 
- This new implementation is simpler and achieves the same results. 
- Previously this had issues across multiple chunks. Does not seem to be the issue anymore.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/h2oai/h2o-3/87)

Updating Correlation Calculation (Making it more simpler and robust)

---

h2o-algos/src/test/java/hex/glm/GLMTest.java
h2o-core/src/main/java/water/H2OError.java
h2o-core/src/main/java/water/H2OModelBuilderError.java
h2o-core/src/main/java/water/Job.java
h2o-core/src/main/java/water/TypeMap.java
h2o-core/src/main/java/water/api/FindHandler.java
h2o-core/src/main/java/water/api/RequestServer.java
h2o-core/src/main/java/water/api/Schema.java
h2o-core/src/main/java/water/api/SchemaMetadata.java
h2o-core/src/main/java/water/api/schemas3/H2OErrorV3.java
h2o-core/src/main/java/water/api/schemas3/ModelOutputSchemaV3.java
h2o-core/src/main/java/water/exceptions/H2OAbstractRuntimeException.java
h2o-core/src/main/java/water/exceptions/H2OCategoricalLevelNotFoundArgumentException.java
h2o-core/src/main/java/water/exceptions/H2OColumnNotFoundArgumentException.java
h2o-core/src/main/java/water/exceptions/H2OIllegalArgumentException.java
h2o-core/src/main/java/water/exceptions/H2OIllegalValueException.java
h2o-core/src/main/java/water/exceptions/H2OKeyNotFoundArgumentException.java
h2o-core/src/main/java/water/exceptions/H2OKeyWrongTypeArgumentException.java
h2o-core/src/main/java/water/exceptions/H2OKeysNotFoundArgumentException.java
h2o-core/src/main/java/water/exceptions/H2OModelBuilderIllegalArgumentException.java
h2o-core/src/main/java/water/util/IcedHashMap.java
h2o-core/src/main/java/water/util/IcedHashMapGeneric.java
h2o-core/src/test/java/water/IcedHasMapGenericTest.java

Fixes the issue with H2O* Exception/Error serialization.
There was a bug in IcedHashMapSerialization(when reading it failed to recognize mode 5 as having String key so it would try to read String as Freezable). Fixed that.
Furthermore, IcedHashMap is not really suitable for the use, since it has restrictions on Key Value pairs: all have to be the same mode (e.g. ALL Freezable -> Freezable, or ALL String -> Freezable[]) and also only String,Freezable and Freezable[] is allowed as value. H2OExceptions used it with general objects.
Added IcedHashMapGeneric and a test.
IcedHashMapgeneric does not have restriction on the same K/V mode plus allows any java serializable as value (not sure this is a good idea).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" …

HEXDEV-608 

---

h2o-algos/src/test/java/hex/deeplearning/DeepLearningTest.java
h2o-core/src/main/java/hex/ModelMetricsRegression.java

Added observation weights for MAE
Added MAE to Cross-Validation Metrics Summary
Modified `testCategoricalEncodingRegressionHuber()` to account for MAE being in the CV Metrics Summary (moved everything down in the table and thus changes indexes)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/h2oai/h2o-3/96)

PUBDEV-3237 & PUBDEV-3238

---

h2o-py/h2o/utils/compatibility.py
h2o-py/h2o/utils/typechecks.py
h2o-py/tests/testdir_misc/pyunit_typechecks.py

I'm fishing out the source code of the lambda expression, so that if the user passes a bad value we can show him which constraint it actually violated (instead of saying it was some unknown "<lambda>").
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/h2oai/h2o-3/97)

Improve error messages generated for lambda- types

---

h2o-core/src/main/java/water/Futures.java
h2o-core/src/test/java/water/FuturesTest.java

Fix Futures to prevent them from swallowing exceptions.
Futures are eagerly removing finished (exceptionally or not) tasks from the queue.
Tasks are eagerly removed if
a) they are completed before being added to the list
b) they are completed at the time of futures resize (internal array resize).
Since the finished tasks were not tested for exceptional completion, any exceptions from the eagerly removed tasks were lost.
Made two changes to the Futures:
1) check for exception when eagerly removing tasks (call get()).
and store any potential exceptions and re-throw them later when blockForPending() is called.
2) wait for all the tasks to finish before re-throwing any exceptions in blockForPending.
+ Added test.
---
This change is [<img src="https://reviewable.io/review_button.svg" …

PUBDEV-3246

---

h2o-algos/src/main/java/hex/kmeans/KMeans.java
h2o-algos/src/main/java/hex/kmeans/KMeansModel.java
h2o-algos/src/main/java/hex/schemas/KMeansModelV3.java
h2o-algos/src/main/java/hex/util/ClusteringUtils.java
h2o-core/src/main/java/hex/ClusteringModel.java

Trying to wrap Spark clustering algorithms (starting with Gaussian Mixture, then LDA, then PIC) and could use the `createCenterTable` from `KMeans`.
Pretty simple change:
* Moved `createCenterTable` to a util class
* Made it generic by accepting `ClusteringModel.ClusteringOutput`
* Moved `_size` to `ClusteringModel.ClusteringOutput` 
Adding for review @st-pasha as last commiter, @mmalohlava as the SW guy
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/h2oai/h2o-3/101)

[SWPRIVATE-14] Move a method creating center table to a util class.

---

h2o-py/h2o/frame.py
h2o-py/tests/testdir_munging/pyunit_categories.py

- Currently, `unique()` returns all unique levels of a factor column, but if you convert it to Python object it will return a list of lists, which can be hard to deal with for some users.  
- This PR will take in a factor column from a H2OFrame and return all unique levels as a Pythonic list and remedy the above problem.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/h2oai/h2o-3/108)

PUBDEV-3264: Return unique values of a categorical column as a Pythonic list

---

h2o-r/h2o-package/R/communication.R

If the user connects to an H2O cluster that doesn't have the `build_too_old` field, using a newer (3.10.*+) version of the H2O R API, an error occurs.  If the field is not available, we set `build_too_old` to TRUE and `build_age` to "PREHISTORIC".
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/h2oai/h2o-3/112)

PUBDEV-2958: Fixing R error in build_too_old

---

h2o-py/demos/kmeans_aic_bic_diagnostics.ipynb

It was calling `len(model.centers()[0])`, which returns the length of the first cluster definition (i.e. the number of variables), rather than `len(model.centers())` which returns the number of centers.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/h2oai/h2o-3/109)

Fix bug in diagnostics function

---

h2o-docs/src/product/faq.rst
h2o-docs/src/product/welcome.rst

Added libcurl requirement for R users on Linux. This is in response to
the following question:
http://stackoverflow.com/questions/38972111/error-in-installing-h2o-ai-r
-package-in-biginsights-cluster-in-bluemix
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/h2oai/h2o-3/104)

PUBDEV-3248

---

h2o-core/src/main/java/water/rapids/ast/prims/advmath/AstHist.java

Currently, hist() and h2o.hist() will fail with a ZeroDivisionError when it encounters a constant numeric column. This PR adds a better exception message for the user.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/h2oai/h2o-3/111)

PUBDEV-3086: hist() fails for constant numeric columns

---

h2o-py/h2o/model/model_base.py

Currently, `self.params` & `self.full_parameters` in `model_base.py` return very messy output about model parameters (actual & default) that can be hard to decipher for users. This PR adds two methods that can extract actual and default parameters and produce a nice dictionary of these values.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/h2oai/h2o-3/114)

PUBDEV-3098: Add methods to get actual and default parameters of a model

---

h2o-core/src/test/java/water/TestUtil.java
h2o-parsers/h2o-orc-parser/src/test/java/water/parser/ParseTestMultiFileOrc.java

1. Changed ParseTestMultiFileOrc.java.
private String[] csvDirectories = {"bigdata/laptop/parser/orc/pubdev_3200/air05_csv",
"bigdata/laptop/parser/orc/milsongs_orc_csv", "smalldata/synthetic_perfect_separation"};
private String[] orcDirectories = {"bigdata/laptop/parser/orc/pubdev_3200/air05_orc",
"bigdata/laptop/parser/orc/milsongs_orc", "smalldata/parser/orc/synthetic_perfect_separation"};
Removed datasets in bigdata/laptop.  For gradle_tests we do not want to do long tests.
private String[] csvDirectories = {"smalldata/synthetic_perfect_separation"};
private String[] orcDirectories = {"smalldata/parser/orc/synthetic_perfect_separation"};
2. Changed TestUtil.java to check for null pointer and print out better error messages.
From:
assert folder.isDirectory();
To:
ssert folder != null …

[HOTFIX] ORC Parser Junit 

---

h2o-py/h2o/frame.py
h2o-py/tests/testdir_misc/pyunit_drop.py

* drop() now handles a single int index or a single str column name or a list of column indexes/names to drop
* To drop a row or a set of rows one passes in a list of indexes, i.e., [1] or [1,4,5]
* Column names and types are modified after the drop
* A pyunit is added to test these functionalities
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/h2oai/h2o-3/129)

PUBDEV-3276: H2OFrame.drop() leaves the frame in inconsistent state

---

h2o-core/src/main/java/hex/Model.java

Need to override it in Sparkling Water for their SVM to use user chosen threshold.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/h2oai/h2o-3/121)

Drop final from defaultThreshold() Model method for Sparkling Water

---

h2o-parsers/h2o-orc-parser/src/main/java/water/parser/orc/OrcParserProvider.java
h2o-py/tests/pyunit_utils/utilsPY.py
h2o-py/tests/testdir_hdfs/index.list
h2o-py/tests/testdir_hdfs/pyunit_INTERNAL_HDFS_airlines_orc.py
h2o-py/tests/testdir_hdfs/pyunit_INTERNAL_HDFS_baddata_orc.py
h2o-py/tests/testdir_hdfs/pyunit_INTERNAL_HDFS_hexdev_29_import_types_orc.py
h2o-py/tests/testdir_hdfs/pyunit_INTERNAL_HDFS_import_folder_airline_05_orc_large.py
h2o-py/tests/testdir_hdfs/pyunit_INTERNAL_HDFS_import_folder_orc.py
h2o-py/tests/testdir_hdfs/pyunit_INTERNAL_HDFS_iris_import_types_orc.py
h2o-py/tests/testdir_hdfs/pyunit_INTERNAL_HDFS_milsongs_orc_large.py
h2o-py/tests/testdir_hdfs/pyunit_INTERNAL_HDFS_orc_parser.py
h2o-py/tests/testdir_hdfs/pyunit_INTERNAL_HDFS_prostate_orc.py
h2o-py/tests/testdir_hdfs/pyunit_INTERNAL_HDFS_timestamp_date_orc.py
h2o-py/tests/testdir_hdfs/pyunit_NOFEATURE_INTERNAL_HDFS_import_folder_air_csv_milsongs_orc.py
h2o-py/tests/testdir_hdfs/pyunit_NOFEATURE_INTERNAL_HDFS_import_folder_csv_milsongs_air.py
h2o-py/tests/testdir_hdfs/pyunit_NOFEATURE_INTERNAL_HDFS_import_folder_csv_orc_same_milsongs.py
h2o-py/tests/testdir_hdfs/pyunit_NOFEATURE_INTERNAL_HDFS_import_folder_milsongs_orc_air_csv.py
h2o-py/tests/testdir_hdfs/pyunit_NOFEATURE_INTERNAL_HDFS_import_folder_orc_csv_same_milsongs.py
h2o-py/tests/testdir_hdfs/pyunit_NOFEATURE_INTERNAL_HDFS_import_folder_orc_milsongs_air.py

Summary:
Mainly added/modified HDFS tests and test harness to detect when a user's hive-exec version is too old.  We have Jenkins tests for Hadoop versions:
CDH 5.7 (Done)
CDH 5.3.5 (Done)
HDP 2.2 (Done)
HDP 2.4 (In progress)
Should not conflict with other people's changes I hope.
PUBDEV-1612: orc parser.  Remove all other tests but focused on the one that failed.
PUBDEV-1612: orc parser.  Fixed bug in test HDFS_import_folder_airline_05_orc_large.py
PUBDEV-1612: orc parser.  Fixed another bug in test pyunit_INTERNAL_HDFS_import_folder_airline_05_orc_large.py
PUBDEV-1612: orc parser.  Added the last two failing tests in HDFS.
PUBDEV-1612: orc parser.  The h2o.import_file takes different arguments under HDFS.  Put this into our test infrastructure for orc parser.
PUBDEV-1612: orc parser. …

PUBDEV-1612: orc parser.  Added airline_05 test to HDFS.

---

h2o-docs/src/product/welcome.rst

PUBDEV 1612 introduces ORC parsing support. I was going to add this to the list of supported file formats in the User Guide, but I needed to create that list first.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/h2oai/h2o-3/132)

PUBDEV-3288: ORC file format now supported

---

h2o-core/src/main/java/water/H2O.java
h2o-core/src/main/java/water/MultiReceiverThread.java
h2o-core/src/main/java/water/Paxos.java
h2o-core/src/main/java/water/TypeMap.java
h2o-core/src/main/java/water/UDP.java
h2o-core/src/main/java/water/UDPClientEvent.java
h2o-core/src/main/java/water/init/NetworkInit.java

Before this fix, the client was required to provide a flatfile with a list
of all nodes it would like to speak with (in fact all nodes in the cluster).
This fix changes the behaviour in the following way:
- an H2O client needs only a subset of all nodes to list in the flatfile, but at least a single node
- a regular H2O node which receives a heartbeat from a client node, adds it into a list of multicasted nodes and also
sends a message to all visible nodes with information about client connection (which contains address of client).
- when a regular node receives this event about client connection, it appends the received client information into
the list of nodes for multicast. Hence, the node is going send hearbeats to the client as well (not only the first node which was
contacted by the …

[PUBDEV-3173] Client does not need to provide full flatfile anymore to connect to the flatfile-based cluster.

---

h2o-r/h2o-package/R/deeplearning.R
h2o-r/h2o-package/R/gbm.R
h2o-r/h2o-package/R/glm.R
h2o-r/h2o-package/R/naivebayes.R
h2o-r/h2o-package/R/randomforest.R

- If parameters x is not provided, then use all columns (except response) as predictors.
- If y is numeric, then take the `setdiff()` of column indexes and y.
- If y is a character, then take the `setdiff()` of columns names and y.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/h2oai/h2o-3/141)

PUBDEV-3296: In R, allow x to be missing (meaning take all columns except y) for all supervised algo's	

---

h2o-hadoop/h2o-mapreduce-generic/src/main/java/water/hadoop/h2odriver.java

This change adds support to use Kerberos login in hadoop driver directly (without using the indirect way of passing options to H2O using the '-J' option).
It also allows user to omit the kerberos config file (if the user is comfortable with the default).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/h2oai/h2o-3/140)

Expose Kerberos login in Hadoop driver + added convenience not to specify krb.conf

---

h2o-docs/src/product/downloading.rst
h2o-docs/src/product/starting-h2o.rst

For El Capitan users, added note stating that the --user flag is
required when starting H2O from command line or python.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/h2oai/h2o-3/103)

PUBDEV-3198

---

h2o-hadoop/assemblyjar.gradle

This change enables the h2odriver to be used for local Hadoop development on OS X.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/h2oai/h2o-3/161)

h2odriver can be used on OS X (for local Hadoop development)

---

h2o-core/src/main/java/water/fvec/ByteVec.java
h2o-core/src/main/java/water/parser/ParseDataset.java
h2o-core/src/main/java/water/parser/Parser.java

Parse fixes:
1) Fix stream parse. Stream parse branch used for non-parallel parse was broken,  replaced it with unimpl.
2) Parallel Stream parse branch does not require data to be compressed, removed it from the condition.
3) added call to available() to ByteVecStream to initialize it.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/h2oai/h2o-3/159)

PUBDEV-3315

---

build.gradle
h2o-assembly/build.gradle
h2o-core/src/main/java/water/parser/FVecParseReader.java
h2o-hadoop/assemblyjar.gradle
h2o-parsers/h2o-parquet-parser/build.gradle
h2o-parsers/h2o-parquet-parser/src/main/java/org/apache/parquet/hadoop/VecParquetReader.java
h2o-parsers/h2o-parquet-parser/src/main/java/water/parser/parquet/ParquetParser.java
h2o-parsers/h2o-parquet-parser/src/main/java/water/parser/parquet/ParquetParserProvider.java
h2o-parsers/h2o-parquet-parser/src/main/java/water/parser/parquet/VecDataInputStream.java
h2o-parsers/h2o-parquet-parser/src/main/java/water/parser/parquet/VecFileSystem.java
h2o-parsers/h2o-parquet-parser/src/main/java/water/parser/parquet/compat/AvroUtil.java
h2o-parsers/h2o-parquet-parser/src/main/resources/META-INF/services/water.parser.ParserProvider
h2o-parsers/h2o-parquet-parser/src/test/java/water/parser/parquet/ParseTestParquet.java
h2o-parsers/h2o-parquet-parser/src/test/java/water/parser/parquet/VecDataInputStreamTest.java
h2o-parsers/h2o-parquet-parser/testMultiNode.sh
h2o-py/tests/pyunit_utils/utilsPY.py
h2o-py/tests/testdir_parser/pyunit_parquet_parser_simple.py
h2o-r/tests/testdir_parser/runit_parquet_parser_simple.R
h2o-web/bower.json
settings.gradle

The idea is to rely on Avro-compatibility layer in the first version. I purposefully copied few classes from Avro parser (and modified some of them). I don't want to introduce direct dependency on avro-parser.
The goal for the final version is to get rid of avro compatibility layer.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/h2oai/h2o-3/136)

Initial implementation of Parquet Support

---

h2o-core/src/main/java/water/rapids/ast/prims/reducers/AstMedian.java
h2o-py/tests/testdir_misc/pyunit_space_headers.py
h2o-py/tests/testdir_munging/unop/pyunit_median.py
h2o-r/h2o-package/R/frame.R
h2o-r/tests/testdir_docexamples/runit_Rdoc_median.R
h2o-r/tests/testdir_munging/unop/runit_median.R

Median now returns a list of medians for each column of a frame.
Relevant unit tests are added.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/h2oai/h2o-3/170)

PUBDEV-3329: median() should return a list of medians from an entire frame

---

h2o-docs/src/product/security.rst

Now that java options can be placed in the config file, using the kerberos login is alot cleaner. Docs now reflect this.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/h2oai/h2o-3/177)

kerb doc edit where java options are now in kerb.conf

---

h2o-py/h2o/frame.py
h2o-py/tests/testdir_munging/slice/pyunit_concat.py

This PR allows rbind/cbind on multiple frames.
Also, it will keep an alias function called `concat()` to adhere to Pandas. Python users will most likely look for this function rather than `rbind` or `cbind`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/h2oai/h2o-3/172)

PUBDEV-3334: Conduct rbind and cbind on multiple frames

---

h2o-parsers/h2o-parquet-parser/src/test/java/water/parser/parquet/ParseTestParquet.java

The Parquet parse test is executed as multi-node test but waits only for cloud of size 1. The test can be executed on a partially formed cloud (3 instead of 5) which results in killing of the cluster and a test failure.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/h2oai/h2o-3/183)

Fix Parquet Parse test, wait for cloud size 5

---

h2o-docs/src/front/index.html
h2o-docs/src/product/faq.rst
h2o-docs/src/product/welcome.rst

Currently, the h2o.ai/docs page includes a link to “What is H2O?” This link points to a single sentence in the FAQ. I added some text to the
beginning of the UG that includes a larger description of H2O, and I
removed the tiny FAQ. Finally, I changed the “What is H2O?” link on the h2o.ai/docs page to point to the new Welcome text instead of the FAQ.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/h2oai/h2o-3/186)

Added description/overview of H2O

---

.gitignore
gradle/java.gradle
gradle/multiNodeTesting.gradle
h2o-algos/build.gradle
h2o-algos/src/test/java/hex/AAA_PreCloudLock.java
h2o-algos/src/test/java/hex/ModelParametersChecksumTest.java
h2o-algos/src/test/java/hex/deeplearning/DeepLearningAutoEncoderTest.java
h2o-algos/src/test/java/hex/deeplearning/DeepLearningCheckpointReporting.java
h2o-algos/src/test/java/hex/glrm/GLRMCategoricalTest.java
h2o-algos/src/test/java/hex/grep/GrepTest.java
h2o-algos/src/test/java/hex/kmeans/KMeansTest.java
h2o-algos/src/test/java/hex/util/AggregatorTest.java
h2o-algos/testMultiNode.sh
h2o-algos/testSingleNode.sh

#
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/h2oai/h2o-3/189)
**Before:** All h2o-algos JUnits run in distributed mode.  There's one 5-node H2O cluster.  Took about 40 minutes on a dual-Xeon server.
11:14:06 Running h2o-algos junit tests...
11:53:15 h2o-algos junit tests PASSED
11:53:15 :h2o-algos:testMultiNode took 2349.323 secs
**Now:** All h2o-algos JUnits run first in single-node mode, and if that passes, then they all run again in distributed mode (4 JVMs). For both cases, there's 5 H2O clusters in parallel.  Takes less than 15 minutes for both.
16:58:16 :h2o-algos:testSingleNode
16:58:16 Running h2o-algos junit tests...
17:01:29 h2o-algos junit tests PASSED
17:01:29 …

Reduce runtime of h2o-algos JUnits by running 5 H2O clusters in parallel. Also run them in single-node mode.

---

h2o-genmodel/src/main/java/hex/genmodel/RawModel.java

gson serialization didn't work on raw models because of a duplicate field and a circular reference. This fixes that.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/h2oai/h2o-3/194)

PUBDEV-3394 Fix gson serialization of raw models

---

h2o-docs/src/product/hadoop.rst

Simple fix to list CDH 5.8.0 as a supported Hadoop version.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/h2oai/h2o-3/198)

Add CDH 5.8.0 to list of support Hadoop versions

---

h2o-py/h2o/frame.py

Currently, we provide a chunk summary in the Python API when `.describe()` is called on a frame. This is not necessary for a user.
I suggest we suppress this information and only bring up when explicitly called upon.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/h2oai/h2o-3/210)

PUBDEV-3418: Suppress chunk summary in describe()

---

h2o-py/h2o/exceptions.py
h2o-py/h2o/job.py
h2o-py/h2o/utils/debugging.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/h2oai/h2o-3/218)

[PUBDEV-3428] Do not show stack trace when the user cancels a running job

---

h2o-docs/src/booklets/v2_2015/source/PythonBooklet.tex

Continued updates to expanding the acronym for GBM as “Gradient
Boosting Machine” (PUBDEV-3388). This fix is now in the Python booklet.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/h2oai/h2o-3/212)

Fixed description of GBM in python booklet

---

h2o-core/src/main/java/water/parser/Parser.java
h2o-core/src/main/java/water/parser/ZipUtil.java
h2o-core/src/test/java/water/parser/ParserTest.java

Makes sure that we call streamParseWriter.nextChunk anytime the source stream reads a new chunk and that the resulting Vec will have the same number of chunks as the source ByteVec.
The bug was that for a specific input we didn't call nextChunk on the StreamParseWriter when the rollover to the next source chunk happened in is.available() method in the last processed chunk.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/h2oai/h2o-3/211)

PUBDEV-3401: Make sure parsed Vec has the same #chunks as source Vec

---

h2o-docs/src/front/index.html

Fixed links in header and footer of the documentation site. Also, the sparkling water readme is a developer doc, so I removed it from the getting started section.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/h2oai/h2o-3/229)

Documentation site topnav links

---

h2o-docs/src/front/index.html

Documentation site now includes Steam. Removed unused CSSes.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/h2oai/h2o-3/239)

Updates to include Steam

---

h2o-py/h2o/h2o.py
h2o-py/h2o/utils/config.py

This creates facility for reading settings from the .h2oconfig file. Currently defined keys are: `{"init.check_version", "init.proxy", "init.url", "init.cluster_id"}`.
For example, if the user creates file .h2oconfig in his/her user/project directory with the following content:
```
[init]
check_version = false
url = https://example.com:5555
```
then the `strict_version_check()` on startup will be effectively disabled, and `h2o.init()` without parameters will connect to the example.com server on port 5555 over https.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/h2oai/h2o-3/226)

[PY-3] Implement config file reader

---

h2o-py/h2o/h2o.py

(but not in `h2o.import_file()` which is supposed to import server-side datafiles)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/h2oai/h2o-3/252)

[PUBDEV-565] allow ~ to be used in paths in h2o.upload_file()

---

h2o-core/src/main/java/water/TypeMap.java
h2o-core/src/main/java/water/Weaver.java
h2o-core/src/test/java/water/WeaverPoolTest.java

Hello,
This commit allows classes defined at runtime to be loaded/reloaded. For reloading classes, the GOLD array of Icers in TypeMap needs to be mutated (so that Icer's will be regen'd for the same classname). If Class C is being reloaded, its type id (this is the int that the leader node first assigned C) remains the same, but the Icer associated with this id is invalidated, along with any supporting Class definitions from Weaver's ClassPool.
This commit does away with the need for a getter for Weaver's _pool member (as all manipulation can simply be done within the class itself).
There are at least two potential uses of Weaver.loadDynamic, one of them being loop-fused Rapids calls.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" …

Dynamic Load/Reload Classes

---

h2o-parsers/h2o-parquet-parser/src/main/java/water/parser/parquet/ChunkConverter.java
h2o-parsers/h2o-parquet-parser/src/test/java/water/parser/parquet/ParseTestParquet.java

The existing tests for NAs worked only because FVecParseWriter handles missing value at the tail of the row itself. The parser was fixed in order to correctly mark also inner missing values.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/h2oai/h2o-3/246)

HEXDEV-634: Fixes handling of NAs in Parquet Parser

---

h2o-docs/src/product/grid-search.rst

Removed `max_hit_ratio_k` from list of hyper parameters in the Grid
Search topic. This was listed under the Shared Tree Hyperparemeters and Deep Learning Hyperparameters sections.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/h2oai/h2o-3/259)

PUBDEV-3446

---

h2o-py/h2o/utils/shared_utils.py
h2o-py/tests/pyunit_utils/utilsPY.py
h2o-py/tests/testdir_jira/pyunit_pubdev_2891.py
h2o-py/tests/testdir_misc/pyunit_small_py_objects.py
h2o-py/tests/testdir_munging/pyunit_to_H2OFrame.py

Previously `H2OFrame([1, 2, 3, 4, 5])` would have created a frame with 5 columns; now it instead creates a frame with 1 column and 5 rows.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/h2oai/h2o-3/247)

[PUBDEV-3412] Fix list -> frame constructor

---

h2o-core/src/main/java/water/rapids/ast/AstRoot.java
h2o-core/src/main/java/water/rapids/ast/prims/mungers/AstColumnsByType.java
h2o-py/h2o/frame.py
h2o-py/tests/testdir_misc/pyunit_columns_by_type.py
h2o-r/h2o-package/R/frame.R
h2o-r/tests/testdir_misc/runit_columns_by_type.R

Retrieve indexes of columns that are of a certain type,i.e., numeric,categorical, etc. This way one can subset a frame with columns of certain data types. 
Example
```
fr = as.h2o(iris)
fr2 = fr[h2o.filter_type(fr,type="categorical")]
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/h2oai/h2o-3/253)

PUBDEV-3422: Create Method to Return Columns of Specific Type

---

h2o-r/h2o-package/R/connection.R

Fix Java search on Windows and remove JDK requirement (JRE suffices)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/h2oai/h2o-3/271)

PUBDEV-3477: R - Unnecessary JDK requirement on Windows	

---

h2o-core/src/main/java/water/fvec/Frame.java
h2o-core/src/main/java/water/persist/PersistManager.java
h2o-core/src/main/java/water/util/FrameUtils.java

PUBDEV-3402, PUBDEV-3431: fixes multi-part export, if the nodes are using local filesystem.
It checks that the directories either don't exist or are empty on all nodes.
More improvements:
- stops export if the export job was cancelled
- in single file-export preserves locality of the data: the file is exported to filesystem of the node that was asked to do the export
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/h2oai/h2o-3/238)

Improves single & multi-part files export on non-distributed filesystems

---

h2o-docs/src/product/welcome.rst

Pull request 12 adds support for Parquet file type. Including this in
the documentation. Driveby fix: Changed XLST to XLSX to match  types in
src/ext/components/parse-input.coffee.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/h2oai/h2o-3/260)

Add parquet to list of supported file types

---

h2o-r/h2o-package/R/models.R

Suggested package mlbench properly escaped in examples, it wasn't spotted as those examples need to run with `--run-donttest`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/h2oai/h2o-3/280)

proper usage suggested dep in examples

---

h2o-r/h2o-package/R/frame.R

fixes
```
* checking R code for possible problems ... NOTE
h2o.str: no visible global function definition for ‘str’
Undefined global functions or variables:
str
Consider adding
importFrom("utils", "str")
to your NAMESPACE file.
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/h2oai/h2o-3/281)

fix NOTE when testing with _R_CHECK_CODE_USAGE_WITH_ONLY_BASE_ATTACHED_

---

h2o-r/h2o-package/R/frame.R

`h2o.head` was already handled in f581d03f1de8d7fc9bdef2af1ef3af94f5a5503a, this updates `h2o.tail` and docs on `...` to reflect the actual state.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/h2oai/h2o-3/221)

order h2o.tail args, docs update, closes PUBDEV-3439

---

h2o-core/src/main/java/water/network/SSLProperties.java
h2o-core/src/main/java/water/network/SecurityUtils.java
h2o-core/src/test/java/water/network/SSLSocketChannelFactoryTest.java
h2o-core/src/test/java/water/network/SecurityUtilsTest.java

* Set TLSv1 as default for Java6 env
* Remove `StandardCharsets` from test (since Java 7)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/h2oai/h2o-3/283)

[HEXDEV-639] Remove Java7+ specific code/config

---

h2o-algos/src/test/java/hex/splitframe/ShuffleSplitFrameTest.java
h2o-core/src/main/java/water/fvec/Frame.java
h2o-core/src/main/java/water/parser/SVMLightFVecParseWriter.java
h2o-core/src/main/java/water/util/ArrayUtils.java
h2o-core/src/test/java/water/TestUtil.java
h2o-core/src/test/java/water/fvec/FrameTest.java
h2o-core/src/test/java/water/util/ArrayUtilsTest.java

Added more remove() versions, for a bunch of primitives
Changed one of Frame.remove()s so it uses ArrayUtils.remove() (others to follow)
Addedd a test for this Frame.remove()
Blocked a couple of NPEs in SVMLightFVecParseWriter (they were happening)
in Frame.get() added a better exception message for the case index is out of bounds (happens in a sparse example, will have to investigate it carefully)
Fixed a bunch of smart intellij warnings.
Fixed a line that caused Michal's concern, in ArrayUtils.
This is take 3; for some reason every rebase bumps the diffs.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/h2oai/h2o-3/278)

Fixed ArrayUtils (remove() was broken)

---

h2o-algos/src/main/java/hex/glrm/GLRMModel.java
h2o-algos/src/main/java/hex/glrm/ModelMetricsGLRM.java
h2o-algos/src/main/java/hex/pca/ModelMetricsPCA.java
h2o-algos/src/main/java/hex/svd/SVDModel.java
h2o-core/src/main/java/hex/ModelMetricsAutoEncoder.java
h2o-core/src/main/java/hex/ModelMetricsClustering.java
h2o-core/src/main/java/hex/ModelMetricsUnsupervised.java

which solves several warnings in the downstream classes. Also rename GLRMModelMetrics => GlrmModelMetricsBuilder, because otherwise it was too easy to confuse with ModelMetricsGLRM class
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/h2oai/h2o-3/293)

Make MetricBuilderUnsupervised class generic (as its parent), 

---

h2o-core/src/main/java/water/H2ONode.java
h2o-core/src/main/java/water/Paxos.java
h2o-core/src/main/java/water/init/NetworkInit.java

Quick fix to prevent endless attempted sends to nodes which are present in flat file but not in the active cloud. 
At the time of the cloud lock, deactivate any dead flat file nodes. Deactivating nodes will prevent them from being included in the multicast sends and will stop udp sender thread for the node.
There is still and open question what to do with clients (same situation can occur with disconnected client) but this issue needs a fix asap.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/h2oai/h2o-3/297)

PUBDEV-3305 - fixed flat file to deactivate dead nodes

---

h2o-core/src/main/java/water/fvec/NewChunk.java
h2o-core/src/test/java/water/fvec/NewChunkTest.java

UUIDs currently do not support sparse. If the column starts with bunch of NAs it is stored as na-sparse numbers initially.
It is flipped to uuids after hitting first non-na uuid value, however, at this point, the parse was not cancelled.
This lead to unsupported state where part of data was stored sparse while the rest was dense -> lead to AIOB.
Fixed by cancelling the sparse when flipping to UUIDs.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/h2oai/h2o-3/279)

PUBDEV-3505 Fixed handling of (na) sparse uuid columns, added test.

---

h2o-core/src/main/java/water/rapids/ast/prims/assign/AstRectangleAssign.java
h2o-core/src/test/java/water/rapids/ast/prims/assign/AstRectangleAssignTest.java

Don't allow assigning to a categorical column with a different domain than the source column
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/h2oai/h2o-3/292)

PUBDEV-3488: Don't allow assigning to a categorical column if domain differs

---

h2o-algos/src/main/java/hex/DataInfo.java
h2o-algos/src/main/java/hex/glm/ComputationState.java
h2o-algos/src/main/java/hex/glm/GLM.java
h2o-algos/src/main/java/hex/glm/GLMModel.java
h2o-algos/src/test/java/hex/glm/GLMBasicTestMultinomial.java
h2o-algos/src/test/java/hex/glm/GLMTest.java
h2o-core/src/main/java/water/util/ArrayUtils.java

Fixes handling of max_active_predictors and and max_iterations parameters in glm + added test.
Both params were dropped in the last update and were never used. 
Slightly changed behavior of max_active_predictors - used to stop the computation when the max number was reached, now it continues the computation taking only up to the max_actove_predictors predictors into the model (pick the ones with highest absolute gradient).
No effect if there is fewer active predictors.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/h2oai/h2o-3/298)

Tomas pubdev 3455

---

h2o-r/h2o-package/R/models.R
h2o-r/tests/testdir_misc/runit_partialPlot.R

Added partial dependence plots to R as h2o.partialPlot. There is still a notable difference between how other tools calculate the partial dependence on classification models vs H2O, but the difference is explained in the documentation.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/h2oai/h2o-3/307)

PUBDEV-563

---

h2o-docs/src/product/welcome.rst

Noted in the Requirements section that Java 9 is not yet supported.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/h2oai/h2o-3/306)

Update to the H2O Requirements

---

h2o-docs/src/product/data-science/pca.rst

Removed a paragraph in the PCA section that described how to retrieve Scree and Variance plots. These are not available. This paragraph will be added back in after PUBDEV-2788 is resolved.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/h2oai/h2o-3/291)

PCA-doc-fix: Scree and cumulative variance plots

---

h2o-docs/src/booklets/v2_2015/source/DeepLearningBooklet.tex
h2o-docs/src/booklets/v2_2015/source/GBMBooklet.tex
h2o-docs/src/product/data-science/deep-learning.rst
h2o-docs/src/product/data-science/drf.rst
h2o-docs/src/product/data-science/gbm.rst

Added categorical_encoding option to DRF, GBM, and DeepLearning
sections in the User Guide.
GBM/DRF: Specify one of the following encoding schemes for handling
categorical features:
- ``auto``: Allow the algorithm to decide (default)
- ``enum``: 1 column per categorical feature
- ``one_hot_explicit``: N+1 new columns for categorical features with
N levels
- ``binary``: No more than 32 columns per categorical feature
- ``eigen``: *k* columns per categorical feature, keeping projections
of one-hot-encoded matrix onto *k*-dim eigen space only
Deep Learning: Specify one of the following encoding schemes for
handling categorical features:
- ``auto``: Allow the algorithm to decide
- ``one_hot_internal``: On the fly N+1 new cols for categorical
features with N levels (default)
- …

PUBDEV-3481: Add new categorical_encoding option to docs

---

h2o-docs/src/booklets/v2_2015/source/DeepLearningBooklet.tex

Grid Search examples are available for Python now. Remove sentence
indicating that the Python Grid Search API is still in development.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/h2oai/h2o-3/319)

Deep Learning booklet update

---

h2o-persist-s3/src/main/java/water/persist/PersistS3.java

The fix:
- exposes system property "sys.ai.h2o.persist.s3.endPoint" which can override default
S3 connection end point. For example, `java -Dsys.ai.h2o.persist.s3.endPoint="https://localhost:9000" -jar h2o.jar`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/h2oai/h2o-3/164)

[PUBDEV-3321] Allow arbitrary S3 connection end point/region.

---

h2o-r/tests/testdir_misc/runit_partialPlot.R

*This PR is a potential fix for `runit_partialDependence.R` failing in the Jenkins PR build.
*Essentially, I changed the path of the prostate dataset and now pull it from `smalldata`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/h2oai/h2o-3/320)

[HOTFIX] Fix path in partial dependence plot unit test

---

h2o-py/h2o/frame.py
h2o-py/h2o/h2o.py
h2o-py/h2o/utils/shared_utils.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/h2oai/h2o-3/332)

[PUBDEV-3035] always append session_id for all temporary frame ids used in rapids

---

h2o-core/src/main/java/water/parser/ParseTime.java
h2o-core/src/main/java/water/parser/PreviewParseWriter.java
h2o-core/src/test/java/water/parser/ParseTimeTest.java

Test for surrounding quotes or not around time strings.
Force test to have 1 col, or unquoted embedded spaces trick it into
thinking there are more columns.  Test handles unquoted dates like
24-MAR-16 06.10.48 PM.
Parser string heuristic, given 1 string (a broken time parse) and 18
times, will pick time now instead of string.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/h2oai/h2o-3/308)

Support another time format, more time tests

---

h2o-docs/src/booklets/v2_2015/source/DeepLearningBooklet.tex
h2o-docs/src/product/data-science/deep-learning.rst

In Deep Learning (booklet and user guide), removed “one_hot_explicit”
as an option to use with the categorical_encoding parameter.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/h2oai/h2o-3/327)

Remove one_hot_explicit option

---

h2o-core/src/main/java/water/fvec/C16Chunk.java
h2o-core/src/main/java/water/fvec/Chunk.java
h2o-core/src/main/java/water/fvec/NewChunk.java
h2o-core/src/main/java/water/parser/BufferedString.java
h2o-core/src/main/java/water/parser/FVecParseWriter.java
h2o-core/src/main/java/water/parser/ParseUUID.java
h2o-core/src/main/java/water/util/MRUtils.java
h2o-core/src/test/java/water/fvec/C16ChunkTest.java
h2o-core/src/test/java/water/fvec/NewChunkTest.java
h2o-core/src/test/java/water/parser/ParseUUIDTest.java

C16Chunk - code deduplication; added a uuid setter (two longs); some encapsulation (replacing exporting _LO_NA, _HI_NA with method isNA())
Chunk - added addUUID() methods, one takes a UUID. Checking if UUID has a valid value.
NewChunk - implemented behavior for UUID
BufferedString - fixed an exception in toString()
FVecParseWriter, ParseUUID - switched from long[] to UUID for representing uuids
MRUtils.sampleFrame - checking value for a NA (or else it can throw)
Added test cases for illegal uuids.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/h2oai/h2o-3/337)

Making sure all uuids in C16Chunk and NewChunk are legit.

---

h2o-core/src/main/java/water/fvec/Vec.java

Use case: create a T_TIME vec
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/h2oai/h2o-3/352)

Adding override Vec.makeCon(double value, byte type) allowing one to create vecs of the specified type

---

h2o-py/h2o/frame.py

the docs indicate these are all accepted and the code that later handles
this handles the full range.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/h2oai/h2o-3/329)

py: accept full range of na_strings formats

---

h2o-algos/src/main/java/hex/deepwater/DeepWater.java
h2o-algos/src/main/java/hex/deepwater/DeepWaterModel.java
h2o-algos/src/main/java/hex/deepwater/DeepWaterTask.java
h2o-algos/src/main/java/hex/deepwater/DeepwaterMojoWriter.java
h2o-algos/src/main/java/hex/schemas/DeepWaterV3.java
h2o-algos/src/test/java/hex/deepwater/DeepWaterAbstractIntegrationTest.java
h2o-core/src/main/java/hex/ModelMetricsBinomial.java
h2o-core/src/main/java/water/util/MRUtils.java
h2o-genmodel/src/main/java/hex/genmodel/algos/deepwater/DeepwaterMojoModel.java
h2o-genmodel/src/main/java/hex/genmodel/algos/deepwater/DeepwaterMojoReader.java
h2o-py/h2o/estimators/deepwater.py
h2o-py/tests/testdir_algos/deepwater/pyunit_custom_regression_lending_deepwater.py

* add balance_classes, max_after_balance_size and class_sampling_factors (same as for GBM/DRF/DL)
* fix stratified sampling for string chunks
* use the same gpu and device_id as in training for MOJO scoring (by default) - this fixes the imageURLs test (CPU vs GPU was the difference)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/h2oai/h2o-3/362)

Add support for balance_classes to Deep Water

---

h2o-core/src/main/java/water/fvec/Frame.java
h2o-core/src/main/java/water/fvec/RollupStats.java
h2o-core/src/main/java/water/fvec/Vec.java
h2o-core/src/test/java/water/rapids/RapidsTest.java

There is a race condition when there is a running computation of RollupStats
and the Vec is being removed at the same time. This can result into
leakage of RollupStats. To prevent this we mark the Vec as mutating
before we start removing the vec from DKV.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/h2oai/h2o-3/357)

HEXDEV-641: Prevent leakage of RollupStats

---

h2o-core/src/main/java/water/parser/Parser.java

My fix of PUBDEB-3401 was most likely accidentally reverted by commint 8188c1106ab6221945d0f730bcd95dd4e30a6007
@wendycwong please review
@tomasnykodym was the original reviewer of fix for PUB-3401
Tests will fail without this fix: http://172.16.2.161:8080/job/h2o_master_DEV_runit_small/20451/
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/h2oai/h2o-3/382)

Brings back fix of PUBDEV-3401 that was reverted by incorrect merge

---

h2o-py/clean.sh
h2o-py/conda/h2o/bld.bat
h2o-py/conda/h2o/build.sh
h2o-py/conda/h2o/meta.yaml
h2o-py/h2o/backend/server.py
h2o-py/h2o/utils/progressbar.py
h2o-py/package_upload_steps.txt
h2o-py/setup.py

Currently we put h2o.jar into the h2o_jar folder at the root of python libraries folder (i.e. outside the `h2o` package folder). This makes installation very fragile: sometimes h2o.jar is hard to find, or the wrong h2o.jar is used (especially on Windows machines), or it doesn't work at all with certain virtual environments, etc.
This change tries to mitigate the issue by putting h2o.jar into the h2o/backend/bin folder within the h2o package.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/h2oai/h2o-3/389)

[PUBDEV-3558] [PUBDEV-3413] [PUBDEV-3370] [PUBDEV-3115] Relocating h2o.jar distributed with the h2o python package

---

h2o-r/h2o-package/R/deeplearning.R

we are getting `R CMD check` warning now:
```
* checking Rd files ... WARNING
checkRd: (7) h2o.deeplearning.Rd:268-276: Tag \donttest not recognized
```
this will fix it.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/h2oai/h2o-3/402)

fix missing @examples keyword, partially closes PUBDEV-3597

---

h2o-algos/src/test/java/hex/deeplearning/DeepLearningProstateTest.java
h2o-core/src/main/java/water/nbhm/NonBlockingHashMap.java
h2o-core/src/main/java/water/util/StringUtils.java
h2o-core/src/test/java/water/util/StringUtilsTest.java

1. NonBlockingHashMap.hashCode now checks the value before producing its hashCode.
2. DeepLearningProstateTest was not checking if the exception message is null, so it was throwing an NPE.
For convenience, added StringUtil.join that concatenates strings. There was one for arrays; this one takes an iterable.
Added a missing class StringUtilsTest.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/h2oai/h2o-3/407)

Fixed a couple of possible NPEs.

---

h2o-docs/src/front/index.html

Download links are now yellow background, similar to the “Download” page.
Top-level internal hyperlinks are now orange, also similar to the “Download” page.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/h2oai/h2o-3/408)

Cosmetic updates

---

h2o-py/docs/conf.py

The Python API documentation showed “Copyright 2015, H2O.ai” in the footer. Updated this to include 2016 because updates continued this year. Also added the “last updated” tag to the footer.
Python docs built successfully on my local machine after these changes.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/h2oai/h2o-3/414)

Python documentation footer

---

h2o-r/h2o-DESCRIPTION.template
h2o-r/h2o-package/R/communication.R
h2o-r/h2o-package/R/models.R

Removed packages that are not used in h2o R package.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/h2oai/h2o-3/403)

remove redundant R dependencies, closes HEXDEV-650

---

h2o-docs/src/booklets/v2_2015/source/GBMBooklet.tex
h2o-docs/src/product/data-science/drf.rst
h2o-docs/src/product/data-science/gbm-params/fold_assignment.rst
h2o-docs/src/product/data-science/gbm-params/gbm-params.rst
h2o-docs/src/product/data-science/gbm.rst

Removed random-split-points option from GBM and DRF sections of the
user guide. Also removed this option from the GBM booklet.
Driveby fixes: Fixed typo in fold_assignment description. Alphabetized current list of parameters in the appendix. Created links to the current parameters in the appendix from the GBM section of the user guide.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/h2oai/h2o-3/422)

PUBDEV-3610: Remove random-split-points

---

h2o-core/src/main/java/water/fvec/RollupStats.java

Vec size was not accounting for string domain size, nor count of chunks.
Vecs with either large string domains or high chunk counts (of small
chunks) would get seriously under represented in size - I was commonly
seeing 2x or more.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/h2oai/h2o-3/411)

Fix bug in Vec size calc

---

h2o-algos/src/test/java/hex/deeplearning/DeepLearningProstateTest.java

AssertionError was being intercepted together with other Throwables.
Actually, in a test, it's better to keep an AE (and rethrow), so a test assertion failure is clearly visible.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/h2oai/h2o-3/445)

Isolating AssertionError

---

h2o-r/h2o-package/R/frame.R
h2o-r/tests/testdir_munging/runit_cumsum_cumprod_cummin_cummax.R

- This PR adds an API endpoint for cumsum, cumprod, cummin, and cummax for the R API.
- We don't need to overload to the R namespace as we have an extra argument, `axis`, which indicates if the operation should be done down a column or across a row.
- Relevant Runit is attached (This is the same as the Pyunit for completeness)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/h2oai/h2o-3/428)

PUBDEV-3621: Add R endpoint for cumsum, cumprod, cummin, and cummax

---

h2o-r/h2o-DESCRIPTION.template
h2o-r/h2o-package/R/frame.R
h2o-r/tests/testdir_misc/runit_as.h2o_sparse.R

PR makes `as.h2o` a generic method, and adds methods: `default`, `data.frame`, `Matrix`, `H2OFrame`.
Also:
- `Matrix` is optional dependency, it is R package among _recommended_ pkgs (since 2.9.0), and those are shipped together with R, so it isn't really _new_ dependency. It was added to have an example of usage `as.h2o` on sparse matrix.
-  new `is.h2o` function - used in examples where number of characters in line matter for CRAN check, short name of function like this will also make examples more readable.
- data type R-java dictionary has been moved to own _container_, a function `h2o.class.map`, not exported
- There are lot of lines related to `destination_frame` handling, this could be eventually simplified after PUBDEV-3608.
- `sparse` argument has been removed as it is related to …

as.h2o generic, closes PUBDEV-3588

---

h2o-r/demos/rdemo.citi.bike.large.R
h2o-r/demos/rdemo.citi.bike.small.R

The `data` arg was deprecated in `h2o.performance` in favor of `newdata`.  This PR updates these tests to use `newdata` instead.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/h2oai/h2o-3/455)

Updating deprecated arg in citibike R demos

---

h2o-r/h2o-package/R/glm.R

rename argument in docs to fix warning in R check
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/h2oai/h2o-3/448)

fix doc-mismatch R check warning, closes PUBDEV-3643

---

h2o-r/h2o-package/R/models.R

*This PR ensures the `plot()` method can take in an uppercase argument for `metric` (e.g. "AUC" vs. "auc")
*Also, I have taken out `AUTO` in the exception  message. This is not seen by the user and only used to specify a default metric, i.e., plot(`model_object`)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/h2oai/h2o-3/447)

PUBDEV-3633: plot.H2OModel in R no longer supports metrics with uppercase names (e.g. AUC)

---

h2o-core/src/test/java/water/fvec/TestFrameBuilder.java
h2o-core/src/test/java/water/fvec/TestFrameBuilderTest.java

Test frame builder which can be used in tests to create small frames.
Example usage:
```
final Frame testFrame = new TestFrameBuilder()
.withName("frameName")
.withColNames("ColA", "ColB")
.withVecTypes(Vec.T_NUM, Vec.T_STR)
.withDataForCol(0, ard(Double.NaN, 1, 2, 3, 4, 5.6, 7))
.withDataForCol(1, ar("A", "B", "C", "E", "F", "I", "J"))
.withChunkLayout(2, 2, 2, 1)
.build();
```
If frame name is not set, it is created automatically.
if col names are not set, they are created automatically.
if chunk layout is not set, then only 1 chunk will be created
I just separated the code from the other branch where I was using it and improved it a bit. Didn't test it properly though yet.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" …

Create test frame builder

---

h2o-core/src/main/java/water/nbhm/NonBlockingHashMap.java

Bug would trigger endless growth of NBHM if seeing a high Key churn rate
- which effectively keeps dead Keys around indefinitly leading to a
memory leak.  Seeing 100M dead keys being kept alive, at 100b each
leading to a 10G total leak.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/h2oai/h2o-3/412)

Bug in NBHM resize heuristic

---

h2o-core/src/main/java/water/rapids/ast/prims/advmath/AstCorrelation.java
h2o-r/h2o-package/R/frame.R
h2o-r/tests/testdir_munging/unop/runit_cor_matrix.R

* Omit NA rows across X and Y when called before calculating sigma of the X and Y frames. 
* This way we only really need one method to get the covariance and we can apply that to all cases.
* Ensured we call `stats::cor` in `frame.R` so we don't conflict with R's namespace.
* Unit test passes and is the same results as R for all possible cases.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/h2oai/h2o-3/460)

Modify correlation matrix

---

h2o-r/demos/rdemo.citi.bike.large.R
h2o-r/demos/rdemo.citi.bike.small.R

* Both of the citibike R demos need to be updated. They try to extract logloss from regression models so they don't end up reporting any metrics. We should extract rmse instead of logloss.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/h2oai/h2o-3/449)

PUBDEV-3642: Fix citibike R demo

---

h2o-docs/src/product/hadoop.rst

Added a note in the Hadoop section `-disown` option for Qubole users.
This provides a workaround if their cluster dies right after launch.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/h2oai/h2o-3/466)

PUBDEV-3656

---

h2o-py/h2o/frame.py
h2o-py/h2o/h2o.py
h2o-py/h2o/utils/shared_utils.py
h2o-py/tests/testdir_jira/pyunit_hexdev_29_additional_parameters.py

This brings stringent restrictions on the possible IDs for data frames. These restrictions are guided by several considerations:
* It should be possible to use the id anywhere within the Rapids language, and there should be no chance of accidentally confusing it with any other token.
* It should be possible to use the id in a REST API url (such as `GET /3/Frames/{frame_id}`) without having to escape it.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/h2oai/h2o-3/420)

[PUBDEV-3614] Do not allow the user to create frames with invalid IDs

---

h2o-core/src/main/java/water/parser/ParseTime.java
h2o-core/src/test/java/water/parser/ParseTimeTest.java

One branch of execution was not properly guarded against IAOB exception.
The exception can be triggered by trying to parse a string of form
XXXXNNNN (where X are arbitrary characters and N are numbers).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/h2oai/h2o-3/476)

PUBDEV-3675: Fix IAOB in ParseTime

---

h2o-py/h2o/frame.py
h2o-py/h2o/model/regression.py
h2o-py/h2o/transforms/preprocessing.py
h2o-py/h2o/utils/config.py
h2o-py/h2o/utils/shared_utils.py
h2o-py/scripts/h2o-py-test-setup.py

* [PUBDEV-3484] Fix backward compatibility of Python mean function.
The change of Python API `Frame#mean` method introduced in PR-359 was partially reverted:
- the method returns list as it was returning before
- it accepts optional argument `return_frame` which forces new behavior (returning H2OFrame)
- there's also a global config variable `general.allow_breaking_changes` which also forces new behavior (has lower precedence than the `return_frame` argument)
This commit porting the fix from rel-turing release branch back to master:
(cherry picked from commit 54716cf96f99b22d70f77b70e0d70560a45bc697)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/h2oai/h2o-3/480)

[PUBDEV-3484] Fix backward compatibility of Python mean function. (#472)

---

h2o-docs/src/product/welcome.rst

The Welcome page of the user guide included links that no longer worked
as a result of the website redesign. Updated these links to match.
Driveby fix: Added “/MOJO” to the section that described POJOs.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/h2oai/h2o-3/479)

Fixing links on the Welcome page

---

h2o-docs/src/product/data-science/k-means.rst

Added missing parameters to the KMeans section in the user guide (under Defining a Model).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/h2oai/h2o-3/477)

PUBDEV-3677 - KMeans parameters

---

h2o-docs/src/product/data-science/naive-bayes.rst

Added missing parameters to the “Defining a Naive Bayes Model” section in the user guide.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/h2oai/h2o-3/475)

PUBDEV-3648 - missing Naive-Bayes params

---

h2o-algos/src/main/java/hex/schemas/GBMV3.java
h2o-algos/src/main/java/hex/tree/DHistogram.java
h2o-algos/src/main/java/hex/tree/DTree.java
h2o-algos/src/main/java/hex/tree/ScoreBuildHistogram.java
h2o-algos/src/main/java/hex/tree/ScoreBuildHistogram2.java
h2o-algos/src/main/java/hex/tree/SharedTree.java
h2o-algos/src/main/java/hex/tree/drf/DRF.java
h2o-algos/src/main/java/hex/tree/gbm/GBM.java
h2o-algos/src/main/java/hex/tree/gbm/GBMModel.java
h2o-algos/src/test/java/hex/tree/gbm/GBMTest.java
h2o-core/src/main/java/water/DTask.java
h2o-core/src/main/java/water/LocalMR.java
h2o-core/src/main/java/water/MrFun.java
h2o-core/src/main/java/water/fvec/Vec.java
h2o-core/src/main/java/water/util/ArrayUtils.java
h2o-core/src/main/java/water/util/DistributedException.java
h2o-core/src/main/java/water/util/VecUtils.java
h2o-core/src/test/java/water/LocalMRTest.java

Improves gbm performance on multi-cpu systems by avoiding CAS. 
Added a new histogram building task (ScoreBuildHistogram2) which allows use of private copies of histogram instead of shared data + CAS to reduce the memory overhead it parallelizes by columns first and only generates limited number of threads (limited number of copies) per column.
Early benchmarking  shows speedup of 0 - 300%, depending on the dataset and machine. I.e. is at least as fast as the previous version, can be up to 4x faster. It's turned on only for GBM for now as it is not tested with DRF (or deep trees), it might be better to do the sharing+CAS in some cases.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" …

Speed up GBM for multi-CPU systems

---

h2o-algos/src/main/java/hex/tree/DHistogram.java

Temporary fix (better than throwing an assertion/AIIOB).
Ignore ill-conditioned columns which do not work with our current histogram building based on base and step.
Should do something smarter in the future - i.e. bin badly behaved columns into integers first.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/h2oai/h2o-3/503)

HEXDEV-643

---

h2o-core/src/main/java/water/rapids/ast/prims/timeseries/AstIsax.java

hotfix for isax notation syntax
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/h2oai/h2o-3/508)

PUBDEV-3693 isax notation bug

---

scripts/detect_branch_changes.py

This script should be executed as a first step in Jenkins PR pipeline. It checks which files were changed by the PR, and based on that tries to decide which jobs should be run.
It signals its conclusions creating a set of empty files of the form H2O_RUN_PY_TESTS and similar (we wanted to use environment variables first, but couldn't quite make it to work).
The Jenkins job then can be configures to test the presence of each of this file, and run a corresponding job or set of jobs. For example, if it sees the H2O_RUN_PY_TESTS file, then it knows to run all pyunit* jobs.
This is the initial version, proof-of-concept. It can be further refined to support more groups of tests: documentation-only changes, algo-specific changes, etc.
---
This change is [<img …

Simple script to limit scope of Jenkins tests according to files modified

---

h2o-core/src/main/java/water/api/ModelBuildersHandler.java

Java7 compiler translates `try-catch` block if you are using new syntax (`catch (FirstExceptionType | AnotherExceptionType e)`) and replaces it by a shared  parent  (`catch (RuntimeException e)`) - in our case one of commit introduced dependency on common parent `ReflectiveOperationException` which was only available in Java7 and not in Java6 - hence our rest api registration was failing.
It is tricky, but I hope we will get rid of Java6 soon…
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/h2oai/h2o-3/514)

[HOTFIX] :fire: REST API registration failure under Java6

---

h2o-py/h2o/backend/server.py
h2o-r/h2o-package/R/connection.R

Very basic solution for PUBDEV-3534, as it became a blocker for PUBDEV-3689.
This PR allows to use custom defined h2o.jar in R and py packages. Path is controlled by `H2O_JAR_PATH` env var.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/h2oai/h2o-3/499)

allow to use arbitrary h2o.jar, closes PUBDEV-3534

---

h2o-r/h2o-package/R/connection.R
h2o-r/tests/testdir_jira/h2o_init_pubdev2801.R

- Currently the H2O R package does not pass the ip and port parameters from `h2o.init()` to `.h2o.startJar()`
- This PR passes the given IP and port from `h2o.init()` to `.h2o.startJar()`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/h2oai/h2o-3/401)

PUBDEV-2801: Starting H2O server from R ignores IP and port parameters

---

h2o-core/src/main/java/hex/schemas/HyperSpaceSearchCriteriaV99.java
h2o-core/src/main/java/water/api/schemas3/ModelParametersSchemaV3.java
h2o-py/h2o/estimators/deeplearning.py
h2o-py/h2o/estimators/deepwater.py
h2o-py/h2o/estimators/gbm.py
h2o-py/h2o/estimators/random_forest.py
h2o-r/h2o-package/R/deeplearning.R
h2o-r/h2o-package/R/deepwater.R
h2o-r/h2o-package/R/gbm.R
h2o-r/h2o-package/R/randomforest.R

* This PR will add RMSE, MAE, RMSLE, and lift_top_group as stopping metrics for all algos.
* The Python bindings were generated upon build while the R bindings for GBM and Random Forest were manually added.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/h2oai/h2o-3/515)

PUBDEV-3700: Add RMSE, MAE, RMSLE, and lift_top_group as stopping metrics

---

h2o-r/h2o-package/R/frame.R
h2o-r/tests/testdir_munging/unop/runit_mean_axis.R

* This PR updates the mean calculation in R.
* It provides a `return_frame` argument. Default is set to false to ensure we are not returning a frame, but instead returning a list (old behavior).
* If a user sets `return_frame` to TRUE, then they can utilize the `axis` argument. Otherwise, the `axis` argument is ignored.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/h2oai/h2o-3/534)

PUBDEV-3719: Update h2o.mean in R to match Python API

---

h2o-core/src/main/java/water/H2O.java
h2o-core/src/test/java/water/MRTaskTest.java

We were launching all our low priority ForkjoinPools (i.e. all our MrTasks) in async mode, which I believe is a bug.
The default FJ behavior is for worker thread private queues to be LIFO, unless async flag is set, in which case they are FIFO.
This matters especially for MrTasks:
An internal node in MrTask’s tree forks right, then proceeds to compute left;
Leaf node invokes map() and attempts to call reduce() if sibling is already computed.
Thus the thread running MrT does depth first dive into its leftmost leaf.
The next task is then taken from the thread’s private queue.
We want to pick the task added last - our sibling - compute it and then reduce.
Taking the task added first (current behavior) means going back to the top of the tree and start expanding the right subtree.
Leads, at the …

Fix FJ pool async flag setting.

---

h2o-algos/src/main/java/hex/tree/DHistogram.java
h2o-algos/src/main/java/hex/tree/DTree.java
h2o-algos/src/main/java/hex/tree/Sample.java
h2o-algos/src/main/java/hex/tree/ScoreBuildHistogram.java
h2o-algos/src/main/java/hex/tree/ScoreBuildHistogram2.java
h2o-algos/src/main/java/hex/tree/SharedTree.java
h2o-algos/src/main/java/hex/tree/drf/DRF.java
h2o-algos/src/main/java/hex/tree/gbm/GBM.java
h2o-algos/src/main/java/hex/tree/gbm/GBMModel.java
h2o-algos/src/test/java/hex/tree/gbm/GBMTest.java
h2o-core/src/main/java/water/H2O.java
h2o-core/src/main/java/water/LocalMR.java
h2o-core/src/main/java/water/MRTask.java
h2o-core/src/main/java/water/MemoryManager.java
h2o-core/src/main/java/water/fvec/C4FVolatileChunk.java
h2o-core/src/main/java/water/fvec/C4VolatileChunk.java
h2o-core/src/main/java/water/fvec/C8DVolatileChunk.java
h2o-core/src/main/java/water/fvec/Chunk.java
h2o-core/src/main/java/water/fvec/RollupStats.java
h2o-core/src/main/java/water/fvec/Vec.java
h2o-core/src/main/java/water/util/ArrayUtils.java
h2o-core/src/main/java/water/util/IcedBitSet.java
h2o-core/src/main/java/water/util/VecUtils.java

Couple of changes further improving performance of GBM/DRF:
1. DRF now uses ScoreBuildHistogram2.
2. Added "volatile" vecs/chunks to store temporary values which are written into frequently.
The intention is to keep these directly in double[]/int[]/float[] arrrays, currently no support for sending to remote, work only locally. Also MRTask are expected to write into volatile vecs by default (arrays are directly exposed, can't keep track of who actually writes).
3. Use new volatile vecs for all temp vecs made during gbm (leaf assignment, response)
4. Removed notion of column block in ScoreBuildHistogram. now always parallelize over single column (there is no more per-row-of-chunks work).
5. improved paralelization of histogram computation 
now launches LocalMR task over columns which …

Further GBM/DRF performance update.

---

h2o-core/src/main/java/water/AutoBuffer.java
h2o-core/src/main/java/water/ExternalFrameHandler.java
h2o-core/src/main/java/water/ExternalFrameHandlerThread.java
h2o-core/src/main/java/water/ExternalFrameReaderBackend.java
h2o-core/src/main/java/water/ExternalFrameReaderClient.java
h2o-core/src/main/java/water/ExternalFrameUtils.java
h2o-core/src/main/java/water/ExternalFrameWriterBackend.java
h2o-core/src/main/java/water/ExternalFrameWriterClient.java
h2o-core/src/main/java/water/H2ONode.java
h2o-core/src/main/java/water/TCPReceiverThread.java
h2o-core/src/main/java/water/fvec/ChunkUtils.java
h2o-core/src/test/java/water/ExternalFrameReaderClientTest.java
h2o-core/src/test/java/water/ExternalFrameWriterClientTest.java

This commit add support to add and get frames from non-h2o environment - for example from Spark executors.
It is implemented by new channel type ( 3 ) which is used for communication with external h2o nodes. It is always expected that before reading/writing the frame is in the DKV ( before writing just empty frame )
It is needed in order to make stable sparkling water architecture work
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/h2oai/h2o-3/100)

Add support for adding/fetching frames from/to non-h2o environment

---

h2o-core/src/main/java/water/Scope.java
h2o-core/src/main/java/water/rapids/Rapids.java
h2o-core/src/main/java/water/rapids/ast/params/AstNumList.java
h2o-core/src/main/java/water/rapids/ast/prims/assign/AstTmpAssign.java
h2o-core/src/test/java/water/rapids/RapidsTest.java
h2o-core/src/test/java/water/rapids/ast/prims/assign/AstTmpAssignTest.java
h2o-core/src/test/java/water/rapids/ast/prims/reducers/AstCumuTest.java

See [PUBDEV-3615](https://0xdata.atlassian.net/browse/PUBDEV-3615)
This also adds a unit test for the functionality created; as well as fixes several minor bugs in Rapids discovered while making the tests. Finally I improve slightly the `RapidsTest` unit test (so that those bugs can be tested too), and move the `testCumu` out of RapidsTest into a separate class `TestAstCumu` so that it can be more easily discovered.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/h2oai/h2o-3/553)

[PUBDEV-3615] Assigning to frame the same id as it currently has should be a noop instead of failing

---

h2o-core/src/main/java/water/H2O.java
h2o-core/src/main/java/water/JettyHTTPD.java
h2o-core/src/main/java/water/api/RequestServer.java
h2o-core/src/main/resources/www/perfbar.js

Necessary for Steam's proxy to work with multiple H2O clusters. Allows the user to append a path to H2O URI i.e. 127.0.0.1:54321/h2o-1
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/h2oai/h2o-3/512)

[PUBDEV-3756] Allows to set a custom jetty context path.

---

h2o-core/src/main/java/water/rapids/ast/prims/math/AstUniOp.java
h2o-py/h2o/frame.py
h2o-py/tests/testdir_misc/pyunit_uniop_colname_domain.py
h2o-r/tests/testdir_misc/runit_uniop_colname_domain.R

* This PR ensures that column names & domains are preserved after a uniop is applied to an H2O frame. 
* Previous behavior would produce column names such as `C1, C2, ...` after an operation was applied to a frame.
* Also, a unit test is added. Only uses `asin()` as the function of choice since all `uniop` operations extend `AstUniOp.java`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/h2oai/h2o-3/546)

PUBDEV-3730: H2OFrame overwrite column name when some methods are applied

---

h2o-web/bower.json

Difference between 0.4.51 and 0.4.54 includes:
33fd5304 Release 0.4.54
6d2286fa Merge pull request #16 from h2oai/MD_context_path
61394c2d Merge pull request #21 from h2oai/micahstubbs-patch-1
24aba5de make localhost flow link clickable
70489a47 Merge pull request #20 from h2oai/micahstubbs-patch-1
4779b68e remove link from terminal command
718808d6 Make the context path work with old H2O core, simplify URL creation
d9b9a0f4 Release 0.4.53
ca3ff53e Add StackedEnsemble Model.Output handling.
37a91a80 Merge pull request #19 from h2oai/micahstubbs-patch-4
f918eb52 put gitter button above the header
922adcf2 Merge pull request #5 from gitter-badger/gitter-badge
e6b29ef9 Release 0.4.52
9d5d8014 Merge pull request #13 from h2oai/MD_svm_ROC
8d14d713 Merge branch 'MD_svm_ROC' of …

Upgrade to Flow 0.4.54

---

h2o-core/src/main/java/water/H2O.java
h2o-core/src/main/resources/www/perfbar.js

Fixes:
- hierarchical context path is now accepted by perfbar
- fix visibility of perf bar if no context path is specified
- "/" context path passed as h2o parameter is ignored
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/h2oai/h2o-3/573)

[HOTFIX][PUBDEV-3757] Fix perfbar visibility

---

h2o-core/src/main/java/water/rapids/Env.java
h2o-core/src/main/java/water/rapids/ast/prims/reducers/AstSumAxis.java
h2o-core/src/test/java/water/rapids/ast/prims/reducers/AstSumAxisTest.java
h2o-py/h2o/frame.py
h2o-py/tests/pyunit_utils/utilsPY.py
h2o-py/tests/testdir_misc/pyunit_empty_strings.py
h2o-py/tests/testdir_munging/unop/pyunit_frame_reducers.py
h2o-py/tests/testdir_munging/unop/pyunit_frame_reducers2.py
h2o-r/h2o-package/R/frame.R
h2o-r/tests/testdir_munging/unop/runit_sum_axis.R

* Now it returns a ValFrame of sums per column or row instead of the sum for an entire frame, also added axis parameter (0 = column wise sum and 1 = row wise sum), and improved documentation. 
* Added AstSumTest junit, as well. 
* By default this function will return a list to ensure backward compatibility (assuming users were looping through columns and getting sums for each column).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/h2oai/h2o-3/527)

Improvements to AstSum rapids function

---

h2o-r/h2o-DESCRIPTION.template
h2o-r/h2o-package/R/config.R
h2o-r/h2o-package/R/connection.R
h2o-r/scripts/h2o-r-test-setup.R
h2o-r/tests/testdir_misc/runit_h2oconfig.R

* This PR adds a config file reader for the R-API. Current fields supported are the following: "init.check_version", "init.proxy","init.cluster_id", "init.verify_ssl_certificates", "init.cookies" which correspond to their respective counterparts in the R API.
An explanation of how it works is below:
* File `.h2oconfig` is searched first in the current working directory, then in all parents up to the root, and finally in the user's home directory `~/.h2oconfig`. The first file found is used, the search does not continue.
* If a config file is found, it is parsed line-by-line, where each line can be:
1) empty or a comment starting with `#` -- these lines are ignored
2) a section name, of the form `[section]`
3) a key-value pair of the form `key = value` or `prefix:key = value`. The `key` is …

Add config file reader for R

---

h2o-r/h2o-package/R/models.R

Right now the output of `h2o.coef` and `h2o.coef_norm` has little value.
```R
library("h2o")
h2o.init()
data(mtcars)
mtcars$gear <- as.factor(mtcars$gear)
mt_train <- as.h2o(mtcars, destination_frame = "mt_train")
model <- h2o.glm(y = "mpg", 
x = c("cyl", "disp", "hp", "drat", "wt", "gear"),
training_frame = mt_train, 
family = "gaussian")
h2o.coef(model)
```
Having the coefficient names is important. Right now the user has to inspect the model object to find them. This change sets a `names` attribute for `h2o.coef` and `h2o.coef_norm`.
```R
> h2o_coef(model)
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/h2oai/h2o-3/574)

Add name attribute to h2o.coef output

---

h2o-docs/src/product/flow.rst

Removed note that said PDPs for categorical features were not supported.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/h2oai/h2o-3/575)

Remove categorical note in PDP section

---

h2o-r/h2o-package/R/config.R

* This PR looks for a config file in a Windows OS (`C:/` & `D:/` drives). If not found, then it just returns.

[HOTFIX]: Add search for config in Windows OS

---

h2o-docs/src/product/data-science/pca.rst

Fixed issue with math display in PCA Algorithm section of the UG. Two
math equations were missing the beginning “\”.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/h2oai/h2o-3/571)

Minor PCA doc fix

---

h2o-docs/src/product/hadoop.rst

The download site now shows only 2 digits for the supported Hadoop
versions. Updated the Hadoop topic to mirror this change. Also, fixed a
typo (redundant “file”), and fixed a broken link to the older download
site.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/h2oai/h2o-3/552)

Updated Hadoop section in the User Guide

---

h2o-algos/src/main/java/hex/glm/ComputationState.java
h2o-algos/src/main/java/hex/glm/GLM.java
h2o-algos/src/test/java/hex/glm/GLMBasicTestBinomial.java

Few more minor fixes in GLM.
1. Multinomial with L1 penalty was selecting L_BFGS as default solver even if it did not have to (low count of active predictors).
2. Fix coordinate descent multinomial - can not skip classes with 0 active coefficients, intercept still needs to be adjusted.
3. fix some races in a test for illegal argument exceptions..

Tomas glm fixes 2

---

h2o-r/h2o-package/R/config.R
h2o-r/h2o-package/R/connection.R

1.Do not change working directory when searching for config file
2.Account for Windows OS when searching for config, i.e., account for various Windows drivers (`C:\`, `D:\`, etc)
3.Make function to search for config more generic by changing name to `.find.files()` and passing a file name as an argument.

Modify search for config

---

h2o-r/h2o-package/R/config.R

* This PR ensures that variables are allocated before reference (even though R creates them during the creation of a data frame).
* This will help with the CRAN Note check.

[HOTFIX]: Need to assign variables used down the .parse.config() function to avoid R CMD issues

---

h2o-r/h2o-package/R/connection.R

* When you start H2O on default port it will get closed when quitting R. However, it will not close on a custom port. This PR fixes this problem.

Call on proper port when exiting R/detaching package, which will cause H2O to shutdown properly

---

h2o-docs/src/booklets/v2_2015/source/GLMBooklet.tex
h2o-docs/src/product/data-science/glm.rst

PUBDEV-3482 adds “quasi_binomial” family option in GLM. Added this to the GLM section of the UG and to the GLM booklet.
Driveby fixes: Added several parameters that were missing from the GLM booklet. Also added “multinomial” to list of link options.

Documentation: Added quasi_binomial family option in GLM

---

h2o-docs/src/product/grid-search.rst

Nidhi noticed that the listed GLM grid search parameters were actually
GLRM parameters (whoops). Fixed that heading and added the actual GLM parameters. Also reviewed the list in the other algos and updated where appropriate.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/h2oai/h2o-3/562)

PUBDEV-3753: Add GLM grid search parameters

---

h2o-docs/src/product/data-science/algo-params/distribution.rst

Updated the description of the `distribution` parameter in the Appendix to clarify which options can be used for regression and classification, and also added the expected response column type for each option.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/h2oai/h2o-3/561)

PUBDEV-3751: distribution option clarification

---

h2o-docs/src/product/data-science/algo-params/stopping_metric.rst
h2o-docs/src/product/data-science/deep-learning.rst
h2o-docs/src/product/data-science/drf.rst
h2o-docs/src/product/data-science/gbm.rst

Added rmse, mae, rmsle, and lift_top_group options to the
stopping_metric parameter description in GBM, DRF, Deep Learning, and in the appendix.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/h2oai/h2o-3/560)

PUBDEV-3709: Add new stopping_metric options

---

h2o-py/h2o/frame.py

With the current implementation, `frame.hist()` produces bar plot with overlapping bars. The problem was caused by incorrect parameter usage in `myplotlib.pyplot.bar()`. This PR fixes those issues, as well as:
* streamlining the code so that it uses vector operations instead of looping over the vec (which is highly inefficient)
* typechecks all parameters

[PUBDEV-3747] fix frame.hist() in python

---

h2o-r/h2o-package/R/connection.R

* This pr calls `.h2o.jar.env` explicitly when detaching the H2O R package. Cannot use environment,i.e., `e`.

Need to refer to .h2o.jar.env in .onDetach()

---

h2o-core/src/main/java/water/rapids/ast/prims/mungers/AstIsNa.java
h2o-py/h2o/frame.py
h2o-py/tests/testdir_munging/pyunit_isna.py

Similarly to uniops, now `frame.isna()` produces column names of the form `col1` => `isNA(col1)`

[PUBDEV-3796] correct column names in frame.isna()

---

h2o-core/src/main/java/water/rapids/Env.java
h2o-core/src/main/java/water/rapids/ast/prims/math/AstNot.java

The old name (`!!`) still remains as a synonym. The reason for the rename is (1) to make python's `frame.logical_negation()` to work; and (2) so that the produced column names are reasonable. Previously the columns would be named `!!(C1)`, `!!(C2)`, etc, which is confusing. Now the produced names are `not(C1)`, `not(C2)` which is much clearer.

[PUBDEV-3749] Make AstNot to bear name 'not'

---

h2o-algos/src/main/java/hex/glrm/GLRMModel.java
h2o-core/src/main/java/hex/ModelMetrics.java
h2o-r/tests/testdir_algos/glrm/runit_glrm_PUBDEV_3778_constant_col_err.R

When the constant columns are removed, the frame_checksum is changed.  The model metrics for GLRM stored the new changed frame_checksum.  However, when we ask for the model metrics again, the model metrics was built with the original frame_checksum.  Hence, when the model is fetched, the handler will compare the model checksum and the frame_checksum.  If either one is different, no model metric is fetched.  That is why we are getting the null model metric back in this case.
I forced the GLRM model metrics to store the original frame_checksum instead and this solves the issue.

Pubdev 3778 glrm constant col error

---

h2o-algos/src/main/java/hex/glrm/GLRM.java
h2o-algos/src/main/java/hex/glrm/GLRMModel.java
h2o-core/src/main/java/hex/ModelMetrics.java
h2o-r/tests/testdir_algos/glrm/runit_glrm_PUBDEV_3778_constant_col_err.R
h2o-r/tests/testdir_algos/glrm/runit_glrm_PUBDEV_3788_loss_by_col_err.R

Added code to assign glrm loss by columns only to columns that have not been deleted by say remove constant columns actions and others.
Included Runit test from Megan Kurba to check correct implementation.
The only files that are changed are GLRM.java and the unit test.
This branch is based off PUBDEV-3778.

Pubdev 3788 glrm loss by col error

---

h2o-py/h2o/frame.py

* This PR adds parameters from `upload_python_object` to the the constructor of `H2OFrame`.
* This allows a user to call `h2o.H2OFrame()` on a python object with desired parameters. 
* Before, `h2o.H2OFrame` only allowed a conversion of Python -> H2O but a user could not specify things such as column names, column types, etc upon conversion.

PUBDEV-3803: Add parameters from _upload_python_object to H2OFrame constructor

---

h2o-core/src/main/java/water/ExternalFrameReaderBackend.java

There is a bug in the current code that if the data in the chunk is NA, we send the NA to the client but with a wrong type ( since we don't have there expectedTypes[selectedColumnsIndeces[i]]]
Since this would need to be fixed I decided to improve the code a little bit and ensure sparkling-water side can be simpler.
Instead of sending expected types for all columns ( even for those we don't need ) we now send expected types just for the columns we need. The expected types has to be in the same order as the selected columns - so lets say selected columns are [2,1,0] then expected columns should be[expectedFor[2], expectedFor[1], expectedFor[0]]

[SW-178] Fix bug and improve External Frame Reader Backend

---

h2o-docs/src/product/data-science/drf.rst
h2o-docs/src/product/data-science/gbm-faq/missing_values.rst
h2o-docs/src/product/data-science/gbm-faq/splitting.rst
h2o-docs/src/product/data-science/gbm.rst

Fixed a text issue in the GBM>FAQ>Splitting topic. Added a small paragraph about GBM parallel performance.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/h2oai/h2o-3/550)

Minor doc fixes

---

h2o-r/h2o-package/R/communication.R
h2o-r/h2o-package/R/kvstore.R

* This PR utilizes `getBinaryURL()` with a list of curl options for binary(MOJO) downloads and uses a safe GET call for MOJO/POJO/genmodel downloads
* Also, this PR creates an alias, `curlFxn`, that changes based on input (`getBinary`). Default is set to `curlPerform` (matches previous behavior).

PUBDEV-3799: Use safe GET calls in MOJO/POJO downloads

---

h2o-docs/src/front/index.html

The links for the RSparkling README now point to
https://github.com/h2oai/rsparkling instead of
https://github.com/h2oai/sparkling-water/blob/rel-2.0/r/README.md.
Note that while this is a change in Sparkling Water, the doc site is
still maintained under the h2o repo.

Documentation site update for RSparkling readme

---

h2o-algos/src/main/java/hex/DataInfo.java
h2o-algos/src/main/java/hex/glrm/GLRM.java
h2o-algos/src/main/java/hex/svd/SVD.java
h2o-algos/src/main/java/hex/util/LinearAlgebraUtils.java
h2o-genmodel/src/main/java/hex/genmodel/algos/glrm/GlrmLoss.java
h2o-py/tests/testdir_algos/glrm/pyunit_glrm_PUBDEV_3728_binary_numeric.py
h2o-r/tests/testdir_algos/glrm/runit_glrm_PUBDEV_3728_binary_numeric.R

1. Added code to support using logistic loss for binary columns read in as either categorical or numeric for GLRM.
2. Added pyunit tests to check that our new addition works for all init modes.  In addition, we compare the glrm singular values calculated when the binary columns are read in as categorical and numerical to make sure I have implemented the change correctly.
3.  Added Runit test from Megan/User to make sure we have fixed their problem.
Truly appreciate any help/comments you may have.
-- Wendy

Pubdev 3728 glrm binary loss numeric

---

h2o-py/tests/testdir_algos/glrm/pyunit_glrm_PUBDEV_3765_hinge_numeric.py

Added routines to calculate the hinge loss and gradient calculation when binary columns are imported as numeric. 
Added pyunit test to make sure implementation is correct.  It is very similar to the logistic loss for GLRM
I only changed two files, Glrmloss.java and added the unit test.  This branch is built off the glrm binary loss branch.

Pubdev 3765 glrm hinge loss

---

scripts/validate_r_cmd_check_output.py

validation was disabled for a while, and recently enabled again, thus require minor update

new whitelist items in R check validation in py, related to PUBDEV-3302

---

h2o-bindings/bin/gen_R.py
h2o-r/h2o-package/R/gbm.R
h2o-r/h2o-package/R/glm.R
h2o-r/h2o-package/R/randomforest.R

In-built line wrap function currently splits line after 120 characters which resulted in malformed URL. Using manual split instead of line wrap for '@return' docs in R API auto-gen code.

PUBDEV-3818: fix line wrap issue for url

---

h2o-docs/src/product/hadoop.rst

Added HDP 2.5 as a supported Hadoop platform.

PUBDEV-3826: Document support for HDP 2.5 in UG

---

h2o-docs/src/product/grid-search.rst
h2o-py/h2o/grid/grid_search.py
h2o-r/h2o-package/R/grid.R

Added more info in the get grid (Python and R) function indicating that the output can vary based on whether the grid search was performed using cross validation, validation frame, and the nfolds value. Also added this to the User Guide.
Driveby fix: Fixed the topic ordering in the User Guide Grid Search section. The list of hyper parameters is no longer between the REST API description and REST API example.

PUBDEV-3809 - Documentation for get_grid

---

h2o-bindings/bin/gen_R.py
h2o-r/h2o-package/R/deeplearning.R
h2o-r/h2o-package/R/deepwater.R
h2o-r/h2o-package/R/gbm.R
h2o-r/h2o-package/R/glm.R
h2o-r/h2o-package/R/glrm.R
h2o-r/h2o-package/R/kmeans.R
h2o-r/h2o-package/R/naivebayes.R
h2o-r/h2o-package/R/pca.R
h2o-r/h2o-package/R/randomforest.R
h2o-r/h2o-package/R/svd.R

When we run `./gradlew build`, it auto-generates R API but based on the machine architecture, the precision of float values (especially, Math.MAX_VALUE) is different. This was discussed [here](https://h2oai.slack.com/archives/dev/p1482018838000511). In order to make it consistent, we will be restricting upto a precision of 10. This is also consistent with Python API [change](https://github.com/h2oai/h2o-3/pull/490/files)

Generate consistent float values for R API

---

h2o-docs/src/product/data-science/algo-params/distribution.rst
h2o-docs/src/product/data-science/algo-params/family.rst
h2o-docs/src/product/data-science/algo-params/gradient_epsilon.rst
h2o-docs/src/product/data-science/algo-params/interactions.rst
h2o-docs/src/product/data-science/algo-params/intercept.rst
h2o-docs/src/product/data-science/algo-params/lambda_search.rst
h2o-docs/src/product/data-science/algo-params/link.rst
h2o-docs/src/product/data-science/algo-params/missing_values_handling.rst
h2o-docs/src/product/data-science/algo-params/nlambdas.rst
h2o-docs/src/product/data-science/algo-params/objective_epsilon.rst
h2o-docs/src/product/data-science/algo-params/remove_collinear_columns.rst
h2o-docs/src/product/data-science/algo-params/solver.rst
h2o-docs/src/product/data-science/algo-params/standardize.rst
h2o-docs/src/product/data-science/glm.rst
h2o-docs/src/product/parameters.rst

Added detailed descriptions and examples of the remaining GLM parameters for the Appendix section.
Driveby fixes: Fixed typos in glm.rst file and the in “epsilon” and nlambdas parameters. Added a note in the lambda_search parameter that GLM will calculate the minimum lambda value unless a lambda is specified. Fixed alphabetized list for the distribution parameter.

PUBDEV-3703: Documentation for GLM Parameters

---

h2o-r/h2o-package/R/frame.R

Further improvements to as.h2o after PUBDEV-2844. Timings below includes `data.table::fwrite` improvement and `colnames` improvement. It is important to note that this speedup highly depends on data. On numerical columns only `colnames` fix does not make difference.
```r
library(h2o)
h2o.init(nthreads=-1)
h2o.no_progress()
N=1e7; K=100
set.seed(1)
DF <- data.frame(
id1 = sample(sprintf("id%03d",1:K), N, TRUE),      # large groups (char)
id2 = sample(sprintf("id%03d",1:K), N, TRUE),      # large groups (char)
id3 = sample(sprintf("id%010d",1:(N/K)), N, TRUE), # small groups (char)
id4 = sample(K, N, TRUE),                          # large groups (int)
id5 = sample(K, N, TRUE),                          # large groups (int)
id6 = sample(N/K, N, TRUE),                        # small groups …
```

speed-up as.h2o by fixing colnames, part of PUBDEV-3821

---

h2o-docs/src/product/data-munging.rst
h2o-docs/src/product/data-science/algo-params/seed.rst
h2o-docs/src/product/data-science/algo-params/weights_column.rst
h2o-docs/src/product/data-science/algo-params/y.rst
h2o-docs/src/product/parameters.rst

Added info on how to get the smalldata folder to the Data Manipulation and Parameter sections.
Driveby fixes for parameters:
- seed: added Deep Learning to the list of “available in”
- weights_column: Fix the second-level bulleted list in the Notes section. All items were in a single paragraph.
- y: Currently shows required response column type for GBM and DL distribution. Added a similar section for GLM family. Also, add a
Related Parameter for family.

PUBDEV-3828: Document in addl places how to get smalldata

---

h2o-core/src/main/java/water/api/Handler2.java
h2o-core/src/main/java/water/api/RapidsHandler.java
h2o-core/src/main/java/water/api/RegisterV4Api.java
h2o-core/src/main/java/water/api/RequestServer.java
h2o-core/src/main/java/water/api/RestApiHandler.java
h2o-core/src/main/java/water/api/Route.java
h2o-core/src/main/java/water/api/schemas4/SessionIdV4.java

The idea is to make an endpoint more discoverable. Thus, instead of writing `registerEndpoint(SomeHandler.class, "methodName")` and forcing the method to be located via reflection later on, I would rather write `registerEndpoint(SomeHandler.SomeMethod.class)`. The latter version allows me to jump to SomeHandler.SomeMethod directly in IntelliJ, and not having to suppress "Unused" warnings all the time (which makes it hard to find out when something is truly unused...)

Handler2: a simple extension on top of Handler

---

h2o-r/h2o-package/R/communication.R
h2o-r/h2o-package/R/kvstore.R
h2o-r/tests/testdir_misc/runit_mojo.R
h2o-r/tests/testdir_misc/runit_pojo.R

- Safe GET calls for POJO/MOJO/genmodel
- Always return binary data when doing a REST call in R API
- Convert raw vector of output from curlPerfom() to character if non-binary payload is desired (default behavior). If MOJOs/genmodel are called upon, then a raw vector is returned
- If a HTTP exception is raised (status !=200), then ensure payload is of type character. Otherwise a conversion to JSON cannot happen with a raw vector, which is produced when payload is binary data

Safe GET calls for POJO/MOJO/genmodel. 

---

gradle/timing.gradle

This reduces the amount of noise in the gradlew build output

Do not report timing for gradle tasks that take less than 1 s

---

h2o-docs/src/front/index.html
h2o-docs/src/product/conf.py
h2o-py/docs/conf.py

Added “2017” to the copyright year in the footer of the H2O UG and H2O Python docs. Also updated the footer in the docs.h2o.ai site.

PUBDEV-3855: Update copyright year in documentation

---

h2o-core/build.gradle
h2o-core/src/main/java/water/api/RequestUri.java

Remove package `com.google.code.regexp` from the list of dependencies, in order to reduce the size of h2o jar.

Remove h2o-core's dependency on external regex library

---

h2o-bindings/src/main/java/water/bindings/examples/Example.java
h2o-bindings/src/main/java/water/bindings/examples/retrofit/GBM_Example.java
h2o-bindings/src/main/java/water/bindings/examples/retrofit/ImportPatternExample.java
h2o-bindings/src/main/java/water/bindings/examples/retrofit/Merge_Example.java
h2o-bindings/src/test/java/water/bindings/examples/retrofit/ImportPatternExampleTest.java
h2o-core/src/main/java/water/api/ImportFilesHandler.java
h2o-core/src/main/java/water/api/schemas3/ImportFilesV3.java
h2o-core/src/main/java/water/persist/Persist.java
h2o-core/src/main/java/water/persist/PersistFS.java
h2o-core/src/main/java/water/persist/PersistManager.java
h2o-core/src/main/java/water/persist/PersistNFS.java
h2o-persist-hdfs/src/main/java/water/persist/PersistHdfs.java
h2o-persist-s3/src/main/java/water/persist/PersistS3.java
h2o-py/h2o/frame.py
h2o-py/h2o/h2o.py
h2o-r/h2o-package/R/import.R
h2o-r/h2o-package/R/parse.R

* This PR adds support for importing files by supplying a pattern argument
* Some examples of this are: 
- `h2o.importFolder(paste0(getwd(),"/test"),pattern="/A/.*/iris_.*")` -> Import all files that have the pattern `/A/.*/iris_.*` in the directory`test/`
- `h2o.importFolder(paste0(getwd(),"/test"),pattern="/A/iris_.*")`  -> Import all files that have the pattern `/A/iris_.*` in the directory `test/`
- `h2o.importFolder(paste0(getwd(),"/test"),pattern="/A/B/iris_.*")` -> Import all files that have the pattern `/A/B/iris_.*` in the directory `test/`
- `h2o.importFolder(paste0(getwd(),"/test"),pattern="iris_.*")` -> Import all files that have the pattern `iris_.*` in the directory `test/`

PUBDEV-3864: Import files by pattern

---

h2o-core/src/main/java/water/persist/PersistManager.java

The `URI.create()` call does not accept windows URI and it needs to be handled via `File` API.

[PUBDEV-3876][HOTFIX] :fire: Handle windows path correctly.

---

h2o-core/src/test/java/water/TestUtil.java

Right now, DOONLY/IGNORE flags can contain only prefix name instead of full test name.

DONLY and IGNORE flags for junit runner reimplemented.

---

h2o-algos/src/main/java/hex/tree/SharedTree.java
h2o-algos/src/main/java/hex/tree/gbm/GBM.java

This PR converts all MRTasks used within the GBM class into static classes. The problem with the non-static classes is that they pull the entire model class into their serialization, which can be quite large and expensive to pass around the nodes. Making every MRTask static and passing only minimal required information avoids this overhead, which should result in faster GBM training times.

GBM efficiency improvements

---

h2o-docs/src/product/data-science/gbm-faq/missing_values.rst

Added a note indicating that GBM does not treat missing numerical values in the same way as GLM.

PUBDEV-3891: Documentation - handling of numerical missing values

---

h2o-core/src/main/java/water/rapids/ast/prims/operators/AstBinOp.java
h2o-py/h2o/frame.py
h2o-py/h2o/h2o.py
h2o-py/h2o/utils/typechecks.py
h2o-py/tests/testdir_misc/pyunit_time_comparisons.py
h2o-py/tests/testdir_munging/pyunit_count_temps.py

This actually fixes 2 separate issues (but reported simultaneously):
1) binary comparisons did not work properly with time columns.
2) python module understood only native python `datetime` types, but not Pandas / numpy datetime objects. By supporting those we improve interoperability between our h2o module and pandas (numpy)

[PUBDEV-3894] [PUBDEV-3895] Fix binary comparisons on time columns

---

h2o-docs/src/product/data-science/algo-params/solver.rst
h2o-docs/src/product/data-science/glm.rst

- Added more info describing how GLM selects the solver when
solver=AUTO.
- Fixed typo in Solver subtopic, and added a bullet about COD providing
better results when lambda_search is enabled.

PUBDEV-3890: Documentation for GLM Solver

---

h2o-docs/src/product/data-science/algo-params/col_sample_rate_change_per_level.rst
h2o-docs/src/product/data-science/algo-params/estimate_k.rst
h2o-docs/src/product/data-science/algo-params/init.rst
h2o-docs/src/product/data-science/algo-params/k.rst
h2o-docs/src/product/data-science/algo-params/user_points.rst
h2o-docs/src/product/data-science/k-means.rst
h2o-docs/src/product/grid-search.rst
h2o-docs/src/product/parameters.rst

- Added documentation or 4 unique K-Means parameters.
- Updated parameters.rst file to include links to these parameter descriptions.
- Fixed the K-Means algorithm section in the K-Means topic to match the list of init options. (User was missing, and numbering was off.)
- Added k to list of grid search ;arameters.
- Driveby fix: Removed hanging “*” from col_sample_rate_change_per_level topic.

PUBDEV-3838: Documentation for K-Means parameters

---

h2o-py/tests/testdir_hdfs/index.list

Removed pyunit_INTERNAL_HDFS_timestamp_date_orc.py from index.list for now.
Open JIRA to fix this:
https://0xdata.atlassian.net/browse/PUBDEV-3938

Remove failed HDFS test for now.

---

h2o-docs/src/product/data-science/gbm-faq/about_the_data.rst
h2o-docs/src/product/data-science/gbm-faq/missing_values.rst

- Changed the title of this topic
- Add a sub-section that provides a summary/overview of missing values
handling
- Fixed the “What loss function was used” question. Also added links to
the about_the_data file (and added a reference tag in that file).
Driveby change: Added a link to the `distribution` parameter in the
about_the_data file.

PUBDEV-3942 - Updated and fixed the GBM Missing Values FAQ

---

h2o-py/build.gradle
h2o-r/build.gradle
h2o-web/build.gradle

The most serious offender was the `:h2o-r:genPDF`, which generates >2000 lines of complaints (they may be useful, but they will be more useful in a separate file). This change makes it somewhat easier to read Jenkins log files.

[PUBDEV-3137] declutter output of ./gradlew build by redirecting output of some noisy tasks to log files

---

h2o-py/build.gradle

* This PR adds a check for a Windows OS in the gradle task `makeOutputDir`. 
* Previously, this was causing build failures for various Windows unit test suites as it was not creating a valid output directory.

:fire: [HOTFIX] Change command line path in h2o-py/build.gradle if Windows OS

---

.gitignore

On Jenkins machine: If GRADLE_HOME is configured to point to the directory with source code, Jenkins CI is complaining about additional files. This fix puts gradle caches into Git ignore list.

[HOTFIX] :fire: Remove gradle caches.

---

h2o-docs/src/product/data-science/glm.rst

Added links to the GLM Full Regularization Path examples for R and Python that are available in the h2o-3 repo.

PUBDEV-3811: GLM Full Regularization Path examples in UG

---

h2o-r/h2o-package/R/frame.R
h2o-r/tests/testdir_jira/runit_pubdev_3111.R

* This PR fix's a bug in R's h2o.interaction() in which the destination_frame argument was not recognized.

PUBDEV-3111: R API's h2o.interaction() does not use destination_frame argument

---

h2o-docs/src/product/data-science/algo-params/categorical_encoding.rst
h2o-docs/src/product/data-science/algo-params/distribution.rst
h2o-docs/src/product/data-science/algo-params/max_depth.rst
h2o-docs/src/product/data-science/algo-params/nfolds.rst
h2o-docs/src/product/data-science/algo-params/standardize.rst
h2o-docs/src/product/data-science/algo-params/user_points.rst
h2o-docs/src/product/data-science/deep-learning.rst
h2o-docs/src/product/data-science/drf.rst
h2o-docs/src/product/data-science/gbm.rst
h2o-docs/src/product/data-science/k-means.rst
h2o-docs/src/product/grid-search.rst

Added clarification for categorical_encoding default values and what happens when user selects categorical_encoding=auto.
Also some driveway fixes:
- Updated descriptions for k and user_points in K-Means section.
- Parameter for distribution: Make headings consistent: “For Regression
problems” and “For Classification Problems”
- Parameters for nfolds: The python example has comment folds=10, but
the example shows folds=5
- Parameters for standardize: gridable=true for K-means and Deep
Learning. gridable value is absent for GLM, but specify this as “yes”.
Also add “standardize” to list of GLM hyper parameters in the grid
search topic.
- in GBM/DRF description for checkpoint, removed the hyphens in
“previously trained” and “previously generated”.
- In the max_depth parameter (appendix), …

PUBDEV-3784 - Document default values for categorical_encoding

---

h2o-algos/src/main/java/hex/ensemble/StackedEnsemble.java

This fix is for rel-tverberg release and need to be cherry-picked into master.

[HOTFIX][StackedEnsemble] :fire: Do not show StackedEnsemble model builder in Flow UI

---

h2o-docs/src/product/data-science/algo-params/distribution.rst
h2o-docs/src/product/data-science/gbm-faq/missing_values.rst

- Updated GBM Missing Values faqs for “What happens when you try to predict on a categorical level not seen during training?”
- Driveby fix: In the distribution option, added clarification describing the method that the algorithm performs when the distribution is AUTO.

PUBDEV-3983: GBM FAQ updates

---

h2o-algos/src/main/java/hex/gram/Gram.java
h2o-algos/src/main/java/hex/pca/PCA.java
h2o-py/tests/testdir_algos/pca/pyunit_pubdev_3916_pca_hangs.py
h2o-r/tests/testdir_algos/pca/runit_pubdev_3916_pca_hangs.R

Added Pyunit and RUNIT test to make sure PCA runs the car.arff.txt data fast and not hanged as reported in JIRA-PUBDEV-3916.
Added one more check to make sure that user parameter k is lower than the number of rows in dataset after removing NAs.

Pubdev 3916 pca hangs car c

---

h2o-core/src/main/java/water/ExternalFrameHandler.java
h2o-core/src/main/java/water/ExternalFrameHandlerThread.java
h2o-core/src/main/java/water/ExternalFrameReaderBackend.java
h2o-core/src/main/java/water/ExternalFrameUtils.java
h2o-core/src/main/java/water/ExternalFrameWriterBackend.java
h2o-core/src/main/java/water/H2ONode.java
h2o-core/src/main/java/water/H2OSecurityManager.java
h2o-core/src/main/java/water/TCPReceiverThread.java
h2o-core/src/main/java/water/network/SocketChannelFactory.java

The external cluster communication was using unencrypted sockets even if the internal security parameter was passed. This PR fixes this problem. More changes might be necessary depending on the state of the SW communication.

[SW-316] Encryption for external cluster communication

---

h2o-docs/src/product/data-science/naive-bayes.rst

In the “Defining a Naive-Bayes Model” section of the UG, added links from the parameters to the parameter descriptions in the Appendix.

PUBDEV-3943: Naive-Bayes parameter links

---

Changes.md

Indicated that 3.10.2.3 hotfix did not completely remove stacked
ensembles from Flow. Users can train SE models in Python and R, and then view the SE models in Flow.

README changes

---

Changes.md

Indicated that 3.10.2.3 hotfix did not completely remove stacked ensembles from Flow. Users can train SE models in Python and R, and then view the SE models in Flow.

README updates from rel-tverberg

---

h2o-docs/src/product/welcome.rst

Added info about starting h2o demos in the Python example of the New User Quick Start.
Added info on how to install Anaconda.
Driveby fix: indented quick start steps to be justified/aligned with the step instead of the step number.

PUBDEV-3998: Updates to New Users Quick Start

---

h2o-algos/src/main/java/hex/glrm/GLRM.java
h2o-algos/src/main/java/hex/kmeans/KMeans.java
h2o-algos/src/main/java/hex/kmeans/KMeansModel.java
h2o-algos/src/test/java/hex/kmeans/KMeansTest.java
h2o-core/src/main/java/hex/ClusteringModel.java
h2o-core/src/main/java/hex/Model.java
h2o-core/src/main/java/hex/ModelMetricsClustering.java
h2o-genmodel/src/main/java/hex/genmodel/GenModel.java
h2o-r/tests/runitUtils/kmeansR.R
h2o-r/tests/testdir_algos/kmeans/runit_kmeans_scoring.R

- Fixed imputation of NA for numeric and categorical columns
- Fixed discrepancy caused by different method for preprocessing data with shared Kmeans_preprocess function.
- Re-score at end of model build instead of using Lloyd's Task Output
- Added runit for k-means scoring.

PUBDEV-3932 K-Means Training and Validation Metrics did not match on same data

---

h2o-web/build.gradle

This PR uses the [drift](https://github.com/micahstubbs/drift) flow.js bundle to add a new top-level Plot menu to Flow

use drift flow.js bundle to add new top-level Plot menu to Flow

---

h2o-docs/src/front/index.html

- Changed Ensembles (Stacking) to Stacked Ensembles
- Removed Tutorials link
- Updated “Reference” link. This now points to the Stacked Ensembles section in the User Guide.
- Changed “Ensemble R Package Readme” to “h2oEnsemble R Package Readme”
Note: Did not change “Readme” to “Homepage.” Let if for now for consistency with other readme files on the site.

PUBDEV-4006: Doc site updates for Stacked Ensembles

---

build.gradle
buildSrc/build.gradle
gradle/debug.gradle
gradle/s3sync.gradle
gradle/scala.gradle

Wrong version of Download Task Plugin was used for new gradle version causing
```
java.lang.NoClassDefFoundError: Lorg/gradle/logging/ProgressLogger
```
The fix:
- upgrade version of download-task-plugin
- fix collision of buildscript dependencies by updating minio version and forcing http-client version to 4.5.2
- minor update in `gradle/s3sync.gradle` script to include dependencies directly in the script instead of top-level script

[PUBDEV-4017][HOTFIX] :fire: Fix the build dependencies.

---

h2o-docs/src/front/index.html

H2O.ai doc site now has a title.

Add a title to the documentation page

---

h2o-docs/src/product/faq.rst
h2o-docs/src/product/welcome.rst

Added FAQ to the Data section regarding native sparse support.
Driveby fix: Changed “SVMLite” to “SVMLight” in Supported File Formats section of the UG.

PUBDEV-3781: Sparse data support

---

h2o-r/h2o-package/R/connection.R

`h2o.clusterInfo()` in R used to print:
```
Version: 3.11.0.99999 
Cloud name: H2O_started_from_R_me_jox289 
Cloud size: 1 
Cloud is locked
```
But this PR changes it to:
```
Version: 3.11.0.99999 
Cluster name: H2O_started_from_R_me_jox289 
Cluster size: 1 
Cluster is locked
```
This should have been updated a long time ago when we stopped using the term "cloud" and started using the term "cluster."

Updated cloud to cluster in h2o.clusterInfo() printout

---

h2o-core/src/main/java/water/parser/ParseDataset.java
h2o-core/src/main/java/water/parser/ParserInfo.java
h2o-parsers/h2o-parquet-parser/src/main/java/water/parser/parquet/ParquetParserProvider.java

Parquet Parser doesn't support stream parsing (it relies on random seeks in a file). H2O's parse switches to stream parse if the parsed files are too small and there is too many of them. This causes an issue to the parquet parser.

Parser Hotfix, do not use stream parse for Parquet, it doens't support it

---

h2o-web/bower.json
h2o-web/build.gradle

This PR reverts the version of Flow shipped with `h2o-3` to version `0.5.2` to resolve regressions with: 
- passing null pointer exception errors from backend `h2o-3` to the user in Flow
- viewing model output for for Word2Vec and custom algos not specified in `_schemaHacks`

PUBDEV-4039 revert flow to version 0.5.2

---

h2o-algos/src/test/java/hex/deeplearning/DeepLearningCheckpointReporting.java

In DeepLearningCheckpointReporting:
1) run(hex.deeplearning.DeepLearningCheckpointReporting)
java.lang.AssertionError: Duration must be smooth

Improved error message regarding the continuity of time

---

h2o-docs/src/product/data-science/stacked-ensembles.rst

Fixed code typos which were causing errors in executing the Python example.

PUBDEV-4066: fixed Typos in Stacked Ensemble Python H2O User Guide code

---

h2o-r/h2o-package/R/grid.R

The description and title in the R docs for `h2o.getGrid` were joined and duplicated due to a missing linebreak in the `grid.R` file.

Updating R docs for h2o.getGrid

---

h2o-bindings/bin/gen_python.py
h2o-py/docs/modeling.rst
h2o-py/h2o/estimators/stackedensemble.py

This fixes a [previous merged PR](https://github.com/h2oai/h2o-3/pull/866) which didn't properly fix the docstring.  The docstring for Stacked Ensemble in Python is now properly edited in the `./h2o-bindings/bin/gen_python.py`.  It also moves Stacked Ensemble from the "unsupervised" to "supervised" section of the Python module docs.

PUBDEV-4041: Fixing python docstring for stackedensemble

---

h2o-py/docs/modeling.rst

This extra line might have been breaking the python docs build.

Removing a blank line in the h2o-py/docs/modeling.rst file

---

h2o-core/src/main/java/hex/grid/HyperSpaceWalker.java
h2o-py/tests/pyunit_utils/utilsPY.py
h2o-py/tests/testdir_algos/gbm/pyunit_gbm_random_grid_large.py

1. fix random grid search backend so that we will copy over the parameters in search_criteria into model params when appropriate.
2. fixed pyunit_gbm_random_grid_large.py to check and verify stopping conditions are met properly.  Changed the assertion from len(air_grid)==5 into 3 stopping condition checks:
search_criteria directs how to do grid search.
1). grid search can stop early if the early stopping conditions specified by
stopping_metric/stopping_tolerance/stopping_rounds
2). grid search will stop if it takes longer than max_runtime_secs
3). grid search will stop if it has collected max_models in its array.
grid search stops correctly if any of the three conditions are satisfied

Pubdev 4065 fix random grid search and pyunit_gbm_random_grid_large.py

---

h2o-core/src/main/java/hex/grid/HyperSpaceWalker.java
h2o-py/tests/pyunit_utils/utilsPY.py
h2o-py/tests/testdir_algos/gbm/pyunit_PUBDEV_4090_grid_model_seeds.py

1. Added code in HyperSpaceWalker.java to enable the following parameter seed setup:
If the user sets a search seed, and the user hasn’t set the base model seed parameter to a non -1 value, then the random search sets the model seed to the search seed + the model number (0, 1, 2) for this search.
2.  Add h2o-3/h2o-py/tests/testdir_algos/gbm/pyunit_PUBDEV_4090_grid_model_seeds.py to verify that grid search building repeatability implemented in 1.

PUBDEV-4090 enable random seed gridsearch

---

scripts/run.py

The current error log reports the following message for a Non healthy cluster:
10:30:00 Node <__main__.H2OCloud object at 0x26ebc50> NOT HEALTHY
Made changes to the log to report the actual node IP and port.

Added port and ip details to the error logs for h2o cloud

---

h2o-algos/src/main/java/hex/aggregator/Aggregator.java
h2o-algos/src/main/java/hex/aggregator/AggregatorModel.java
h2o-algos/src/main/java/hex/schemas/AggregatorV99.java
h2o-algos/src/test/java/hex/util/AggregatorTest.java

added target_num_exemplars parameter (defaults to 5000), removed radius_scale
returns a frame with a number of exemplars that is within 50% of the target value (50%-150%).
takes about 1 min to aggregate 116M rows (airline) to 5000 exemplars on my laptop.
NOTE: we could make the 50% a parameter for more or less "picky" users, but maybe we don't need to do that just yet - ideas/thoughts?

[PUBDEV-4125] - Automatic radius selection for Aggregator - add target_num_exemplars parameter, remove radius_scale

---

h2o-core/src/main/java/hex/DMatrix.java
h2o-core/src/main/java/hex/ModelMojoWriter.java
h2o-core/src/main/java/water/AutoBuffer.java
h2o-core/src/main/java/water/JettyHTTPD.java
h2o-core/src/main/java/water/Key.java
h2o-core/src/main/java/water/Value.java
h2o-core/src/main/java/water/api/NanoResponse.java
h2o-core/src/main/java/water/api/RequestServer.java
h2o-core/src/main/java/water/fvec/Frame.java
h2o-core/src/main/java/water/fvec/NewChunk.java
h2o-core/src/main/java/water/init/NetworkInit.java
h2o-core/src/main/java/water/init/NodePersistentStorage.java
h2o-core/src/main/java/water/parser/BufferedString.java
h2o-core/src/main/java/water/parser/Categorical.java
h2o-core/src/main/java/water/parser/CsvParser.java
h2o-core/src/main/java/water/parser/ParseTime.java
h2o-core/src/main/java/water/util/GetLogsFromNode.java
h2o-core/src/main/java/water/util/StringUtils.java
h2o-core/src/test/java/water/KeyToString.java
h2o-core/src/test/java/water/fvec/FVecTest.java
h2o-core/src/test/java/water/network/SSLSocketChannelFactoryTest.java
h2o-core/src/test/java/water/parser/ParserTest.java
h2o-core/src/test/java/water/parser/ParserTest2.java
h2o-hadoop/h2o-mapreduce-generic/src/main/java/water/hadoop/AbstractMessage.java
h2o-hadoop/h2o-mapreduce-generic/src/main/java/water/hadoop/h2odriver.java
h2o-parsers/h2o-avro-parser/src/test/java/water/parser/ParseTestAvro.java
h2o-parsers/h2o-orc-parser/src/main/java/water/parser/orc/OrcParser.java
h2o-parsers/h2o-parquet-parser/src/main/java/water/parser/parquet/ChunkConverter.java

Moved them into a `StringUtils` method.
The thing is, repeating "udf, udf" everywhere looks kind of too repetitive.
Using default encoding means we depend on whatever settings a server has,
and the server can be something in Japan (and another in Russia, and yet another in China), so we can't seriously rely on everything being UTF-8.
So there.
A method `toBytes()` is added to apply to whatever object comes up.
Tests passed on my machine.

Moved out all "string to bytes" transformations

---

h2o-py/tests/testdir_munging/unop/pyunit_vec_math_ops.py

Relax error bound for pyunit_vec_math_ops.py for tan(), acosh(), gamma(), digamma() until Tomas fixed this for good.

PUBDEV_4142_intermittent_pyunit_vec_math_ops_temp_fix, temporary

---

h2o-core/src/main/java/water/rapids/Env.java
h2o-core/src/main/java/water/rapids/ast/prims/mungers/AstPivot.java
h2o-core/src/test/java/water/rapids/ast/prims/mungers/AstPivotTest.java
h2o-py/h2o/frame.py
h2o-py/tests/testdir_misc/pyunit_pivot_medium.py
h2o-r/h2o-package/R/frame.R
h2o-r/tests/testdir_munging/runit_pivot.R

This is a much improved version of Pivot.  First does a sort by index.  Then pivots locally within Chunks, collapsing rows sequentially as the index is ordered.
The cleanup mrtask then merges identical indexes and crosses Chunk boundaries.  Checks to see if the current Chunk has a run that continues from the previous Chunk.
This method scales with column cardinality much better than the previous method.
Limitation is that all rows of a single index value needs to fit on one node 
and max rows for a single index value and column label is Chunk size * Chunk size
Todo: More thorough checking on the pyunit.  Clean up some comments in AstPivot.java

Pubdev 2535 Pivot v2

---

h2o-core/src/main/java/water/H2O.java

Prevents adding a value to the array of arguments if the intended syntax is the existence of a flag.

[PUBDEV-4171] Check for empty system property

---

h2o-docs/src/product/docker.rst

Dot in image name was missing and was expected in next steps.

Fix typo in docker image building command

---

h2o-core/src/main/java/water/H2O.java
h2o-core/src/main/java/water/api/RequestServer.java

Adds `Access-Control-Allow-Origin: *` header behind a dev parameter of `debug.cors`. This allows the frontend and backend to be decoupled - easing development of Flow.

[PUBDEV-4168] Enable cors option for debugging

---

h2o-docs/src/product/data-science/algo-params/distribution.rst
h2o-docs/src/product/data-science/algo-params/offset_column.rst
h2o-docs/src/product/data-science/gbm.rst

- Removed (in 3 locations) documentation that stated offset_column must be less than 1 for bernoulli distributions. Note that the bernoulli case was not documented in the GBM booklet, so there was nothing to change.
- Added tip to pass in a column of predicted values when specifying an offset_column.

PUBDEV-4164: offset_column updates

---

README.md

There were missing block-quote marks in `README.md`, which messed up the formatting for next several sections.

Add block-quote marks in README.md:166-167

---

h2o-docs/src/product/data-science/gbm-faq/about_the_data.rst
h2o-docs/src/product/data-science/gbm-faq/histograms_and_binning.rst
h2o-docs/src/product/data-science/glm.rst
h2o-docs/src/product/data-sources.rst

Added a section in GLM about the coefficients table. Included R and Python examples.
Driveby fixes: Fixed some issues (commented text) in GBM FAQ.

PUBDEV-4183: Document Coefficient Tables in GLM

---

h2o-algos/src/main/java/hex/schemas/GBMV3.java
h2o-algos/src/main/java/hex/tree/SharedTree.java
h2o-algos/src/test/java/hex/kmeans/KMeansRandomTest.java
h2o-algos/src/test/java/hex/tree/gbm/GBMTest.java
h2o-core/src/main/java/hex/Model.java
h2o-core/src/main/java/hex/ModelBuilder.java
h2o-core/src/main/java/water/api/schemas3/ModelParametersSchemaV3.java
h2o-core/src/main/java/water/util/FrameUtils.java
h2o-core/src/main/java/water/util/VecUtils.java
h2o-py/h2o/estimators/aggregator.py
h2o-py/h2o/estimators/deeplearning.py
h2o-py/h2o/estimators/deepwater.py
h2o-py/h2o/estimators/gbm.py
h2o-py/h2o/estimators/kmeans.py
h2o-py/h2o/estimators/random_forest.py
h2o-r/h2o-package/R/deeplearning.R
h2o-r/h2o-package/R/deepwater.R
h2o-r/h2o-package/R/gbm.R
h2o-r/h2o-package/R/kmeans.R
h2o-r/h2o-package/R/randomforest.R

For DRF/GBM, we now sort all categorical columns with more than nbins_cats factors, to allow the <= split to be useful and to reduce the effective number of factors in the child nodes. Otherwise, it would quite likely never split on this feature, and the bitset magic would never occur. Now, we get higher (over)fitting ability.

Add SortByResponse and LabelEncoding categorical_encoding schemes.

---

h2o-docs/src/product/welcome.rst

Removed Anaconda package from list of hard requirements and placed it into a separate section, indicating that it is only required if you are using H2O on the Anaconda Cloud. Also added a link to the conda site.

PUBDEV-4184: Anaconda support for 2.7 and 3.5 repo

---

h2o-docs/src/front/assets/stylesheets/style.css
h2o-docs/src/front/assets/vendor/bootstrap.min.css
h2o-docs/src/front/index.html

- Increased the weight of the H2O User Guide link.
- That entry is a "p" style so that I could add text after the link without wrapping. (The "a" tag adds a return at it’s closing "a".)
- To avoid line wrapping, changed the box padding to 4px. (6px worked in Chrome and Firefox, but not Safari.) Also changed main font size from 1em to .94em.

PUBDEV-4045: Doc site - Make H2O User Guide more prominent

---

h2o-core/src/main/java/water/rapids/Env.java
h2o-core/src/main/java/water/rapids/ast/prims/search/AstWhichFunc.java
h2o-core/src/main/java/water/rapids/ast/prims/search/AstWhichMax.java
h2o-core/src/main/java/water/rapids/ast/prims/search/AstWhichMin.java
h2o-py/h2o/frame.py
h2o-py/tests/testdir_munging/pyunit_whichmaxmin.py
h2o-r/h2o-package/R/constants.R
h2o-r/h2o-package/R/frame.R
h2o-r/tests/testdir_munging/exec/runit_whichmaxmin.R

* This PR adds `which.max` & `which.min` to the R API and `idxmax()` & `idxmin()` to the Python API through Rapids.
* The main use of these functions are finding the index of the maximum/minimum value in a column/row.

PUBDEV-4105: Add which.max, which.min support for R H2OFrame & PUBDEV-4104: Add support for idxmax, idxmin in Python H2OFrame

---

buildSrc/src/main/java/H2OBuildVersion.java
h2o-py/build.gradle
h2o-py/h2o/__init__.py

The change:
- generates build info into `h2o/__init__.py` file
- print generated info if build number is `99999`

[BUILD] Include build info into python package build

---

Dockerfile

It is considered a best practice to combine multiple `RUN` commands when possible. There are no functional changes to this file beside this. These small changes to the Dockerfile will produce a Docker image that is about 410MB smaller (1.55 GB vs 1.59 GB)  
https://docs.docker.com/engine/userguide/eng-image/dockerfile_best-practices/#run

Optimize build docker image

---

h2o-hadoop/h2o-mapreduce-generic/src/main/java/water/hadoop/h2odriver.java

This PR is designed to support PAM authentication on top of Hadoop.
Scenario:
1. User logs in with his own account to the Hadoop edge node.
2. Starts hadoop driver with a client mode enabled.
3. User is provided a URL to connect to the H2O client running inside the driver. H2O's web interface is disabled on Hadoop nodes.
It lets me run a client inside a Hadoop driver with PAM authentication like this:
hadoop jar h2odriver.jar -mapperXmx 4g -nodes 1 -output nowhere -internal_secure_connections -client -pam_login -login_conf pam.conf -jks keystore.jks
where pam.conf is:
pamloginmodule {
de.codedo.jaas.PamLoginModule required
service = sshd;
};
(sshd just because you probably have it on your Mac)
PAM will work out-of-the box without additional changes because the process of the H2O Hadoop …

h2odriver, add support for using H2O client (and disabling web on Hadoop)

---

h2o-r/h2o-package/R/models.R

This PR fixes a [bug](https://0xdata.atlassian.net/projects/PUBDEV/issues/PUBDEV-3711) in `h2o.coef` & `h2o.coef_norm` in the R API when dealing with multinomial GLM.

PUBDEV-3711: h2o.coef in R not functional for multinomial models

---

h2o-core/src/main/java/water/rapids/ast/prims/mungers/AstGroup.java
h2o-docs/src/booklets/v2_2015/source/R_Vignette_code_examples/r_glm_demo.R

* `nrow` operation in GroupBy does not need a column name appended since its only a count of rows per group.

PUBDEV-4143: Improve the Python group_by option count column name

---

h2o-py/demos/word2vec_craigslistjobtitles.ipynb
h2o-py/h2o/frame.py
h2o-py/h2o/model/word_embedding.py

* This PR adds the following word2vec utility functions:  `h2o.tokenize`, `h2o.grep`, & `h2o.transform`.
* Also, a  word2vec demo to show an end-end example of word2vec in Python.

PUBDEV-4147: Expose word2vec in Python API

---

h2o-py/h2o/h2o.py
h2o-py/h2o/model/model_base.py
h2o-r/h2o-package/R/kvstore.R

* This PR adds a new parameter to `download_pojo`/`download_mojo` functions that will allow a custom name for the `genmodel.jar`.

PUBDEV-4072: Supporting h2o-genmodel.jar name change into download_pojo function

---

h2o-r/h2o-package/R/frame.R
h2o-r/tests/testdir_misc/runit_as.h2o_sparse.R

This fix is needed for release 3.10.4.4.

PUBDEV-4081: Sparse matrix cannot be converted to H2O

---

h2o-py/h2o/backend/cluster.py

* This PR allows the Python API to fetch information about a particular node in the H2O Cluster.

PUBDEV-4238: Fetch node info from H2O Cluster

---

h2o-py/h2o/model/model_base.py

* This PR adds a method (`rotation()`) that will fetch the principal component matrix for a PCA model.

PUBDEV-2807: PCA Rotations not displayed in Python API

---

h2o-docs/src/product/data-science/word2vec.rst

- Removed the note that Word2vec is not supported under python.
- Added subsection on Finding Synonyms
- Added demo info for python craigslist demo
- Removed R example. This is available in the demo, and additional examples will be available when the parameters section is updated.

PUBDEV-4232: Document that Word2vec is supported under python

---

h2o-docs/src/product/hadoop.rst

Added HDP 2.6 to list of supported Hadoop versions.

PUBDEV-4253: Documentation - HDP 2.6

---

h2o-algos/src/main/java/hex/glrm/GLRM.java
h2o-algos/src/main/java/hex/glrm/GLRMModel.java
h2o-algos/src/main/java/hex/pca/PCA.java
h2o-algos/src/main/java/hex/schemas/AggregatorV99.java
h2o-algos/src/main/java/hex/schemas/GLRMV3.java
h2o-algos/src/main/java/hex/schemas/PCAV3.java
h2o-algos/src/main/java/hex/schemas/SVDV99.java
h2o-docs/src/product/data-science/glrm.rst
h2o-py/h2o/estimators/glrm.py
h2o-py/h2o/estimators/pca.py
h2o-py/h2o/estimators/svd.py
h2o-py/tests/testdir_algos/glrm/pyunit_PUBDEV_4246_pro_var.py
h2o-r/h2o-package/R/glrm.R
h2o-r/h2o-package/R/pca.R
h2o-r/h2o-package/R/svd.R

1. Fixed code to make sure proportional variances do not exceed 1.
2. Added pyunit test to check and make sure 
- that the eigenvalues generated from PCA specifying GLRM as the PCA method and that from 
calling GLRM directly are the same.
- maximum proportional variance (first element) does not exceed 1.

PUBDEV-4246: proportional of variance.

---

h2o-r/h2o-package/R/connection.R
h2o-r/h2o-package/R/kvstore.R
h2o-r/h2o-package/R/logging.R
h2o-r/h2o-package/R/models.R

* This PR will set `nthreads` in `h2o.init()` to `-1` by default and set `nthreads` in `h2o.init()` to `-2` for R examples to comply with CRAN.

PUBDEV-4267: Change default nthreads to -1 in R API h2o.init()

---

h2o-docs/src/product/data-munging/combining-columns.rst
h2o-docs/src/product/data-munging/combining-rows.rst
h2o-docs/src/product/data-munging/groupby.rst
h2o-docs/src/product/data-munging/importing-data.rst
h2o-docs/src/product/data-munging/importing-files.rst
h2o-docs/src/product/data-munging/imputing-data.rst
h2o-docs/src/product/data-munging/merging-data.rst
h2o-docs/src/product/data-munging/replacing-values.rst
h2o-docs/src/product/data-munging/slicing-columns.rst
h2o-docs/src/product/data-munging/slicing-rows.rst
h2o-docs/src/product/data-munging/splitting-datasets.rst
h2o-docs/src/product/data-munging/uploading-data.rst
h2o-docs/src/product/data-science/algo-params/eps_prob.rst
h2o-docs/src/product/data-science/algo-params/min_prob.rst
h2o-docs/src/product/data-science/glm.rst
h2o-docs/src/product/data-science/stacked-ensembles.rst
h2o-docs/src/product/downloading.rst
h2o-docs/src/product/faq/r.rst
h2o-docs/src/product/grid-search.rst
h2o-docs/src/product/starting-h2o.rst
h2o-docs/src/product/welcome.rst

Remove nthreads=-1 from examples in the User Guide. This is now the default value, so it is not required.
Driveby fix: Fixed formatting for R examples in the min_prob and eps_prob parameter topics.

PUBDEV-4268: Documentation for nthreads

---

h2o-py/h2o/h2o.py
h2o-r/h2o-package/R/connection.R

* Please see JIRA for description

PUBDEV-4248: Add a parameter that ignores the config file reader when h2o.init() is called

---

h2o-algos/src/main/java/hex/api/RegisterAlgos.java
h2o-algos/src/main/java/hex/word2vec/Word2VecModel.java
h2o-algos/src/main/java/water/rapids/prims/word2vec/AstWord2VecToFrame.java
h2o-algos/src/main/resources/META-INF/services/water.rapids.ast.AstPrimitive
h2o-algos/src/test/java/hex/word2vec/Word2VecTest.java
h2o-core/src/main/java/water/rapids/Env.java
h2o-core/src/main/java/water/rapids/PrimsService.java
h2o-core/src/main/java/water/rapids/Val.java
h2o-core/src/main/java/water/rapids/vals/ValModel.java
h2o-py/h2o/expr.py
h2o-py/h2o/model/word_embedding.py
h2o-py/tests/testdir_algos/word2vec/pyunit_word2vec_to_frame.py
h2o-r/h2o-package/R/w2vutils.R
h2o-r/tests/testdir_algos/word2vec/runit_word2vec_to_frame.R

This PR introduces support for converting word2vec model into a Frame.
It uses algo-specific rapids and introduces a new rapids discovery mechanism. Rapids now support working with models
eg.:
fr <- .newExpr("word2vec.to.frame", w2v.model@model_id)
would convert a word2vec model to an H2O frame

PUBDEV-4266: Adds support for converting word2vec model to a Frame

---

h2o-dist/buildinfo.json
h2o-dist/index-old.html
h2o-docs/src/booklets/v2_2015/source/RBooklet.tex
h2o-docs/src/product/hadoop.rst
h2o-docs/src/product/howto/FAQ.md
h2o-docs/src/product/howto/H2O-DevHadoop.md
h2o-docs/src/product/welcome.rst
h2o-hadoop/h2o-mapr3.1-assembly/build.gradle
h2o-hadoop/h2o-mapr3.1/build.gradle
h2o-hadoop/h2o-mapreduce-generic/src/main/java/water/hadoop/h2odriver.java
make-dist.sh
py2/testdir_single_jvm/test_parse_covtype_2_maprfs.py
settings.gradle

This PR adds user manipulation control to the h2o hadoop drivers. This was primarily done for Steam (and any other H2O managing software) so as to avoid using root level privileges to impersonate users at the execution level.
Flags can be set to `-keytab <path> -principal <kerberos principal>` or `-run_as_user <valid user>` where the valid user must be a user in the hadoop environment.
(Note: using run as user implies the hadoop cluster doesn't have kerberos and is therefore already insecure)

PUBDEV-4288: Set hadoop user from h2odriver

---

h2o-docs/src/product/hadoop.rst

Added new set of Hadoop launch parameters that allow users to avoid using root level privileges to impersonate users at the execution level.

PUBDEV-4289: Documentation for new Hadoop launch parameter

---

h2o-docs/src/product/welcome.rst

Added information about the new -principal and -run_as_user Hadoop launch parameters. This was added to the hadoop.rst file for 3.10.4.4. In 3.10.5.1, this topic is moved to the welcome.rst file.

PUBDEV-4290: New Hadoop launch parameters in 3.10.5.1 documentation

---

h2o-docs/src/product/data-science/deep-learning.rst

- Removed the Deep Learning Algorithm section.
- Moved the information about computing deviance for a regression model to the FAQ.
- Added a link to the Deep Learning Booklet under the “References” section.

PUBDEV-4294: Documentation updates for Deep Learning

---

h2o-docs/src/product/logs.rst
h2o-py/h2o/h2o.py
h2o-r/h2o-package/R/logging.R

R, Python, and User Guide now all remind customers that the file name for downloading logs must include the .zip extension.

PUBDEV-4211: Documentation clarification for downloading logs

---

h2o-docs/src/product/data-science/pca.rst

- correct formula for :math:`C_{y}`
- use :math:`\times` for matrix dimensions
- correct formula for eigenvector
- fix :math:`\over` with :math:`\frac{}{}`
- replace :math:`\sum` with :math:`\Sigma`
- fix missing ')' and misplaced '`' in 'SVD (locally)'
- add missing '='
- remove redundant parentheses for left singular vectors

Fix (mathematical) typos in PCA documentation

---

h2o-docs/src/front/index.html

Adding word2vec to also list on the docs.h2o.ai site. Added this as a separate block with a Miscellaneous heading.
Driveby fix: removed “Community” link from list of resources.

PUBDEV-4194: Added "word2vec" to list of algorithms on doc site

---

h2o-core/src/main/java/water/JettyHTTPD.java
h2o-core/src/main/java/water/api/PostFileServlet.java

This PR removes `validKeyName()` from `JettyHTTPD.java` and `PostFileServlet.java` as it put a constraint on destination frame id, which causes issues for `h2o.uploadFile` (see referenced JIRA).

PUBDEV-4265: Problem with h2o.uploadFile on Windows

---

h2o-algos/src/main/java/hex/DataInfo.java
h2o-algos/src/main/java/hex/deeplearning/DeepLearning.java
h2o-algos/src/main/java/hex/glm/GLM.java
h2o-algos/src/main/java/hex/glm/GLMScore.java
h2o-algos/src/main/java/hex/glm/GLMTask.java
h2o-algos/src/test/java/hex/glm/GLMBasicTestMultinomial.java

YMUTask shared with deep learning was expecting response to be expanded into #classes binary vectors in multinomial case, but glm does not do that => caused AIIOB in case YMUTask was computing response mean/sigma (either got weights or missing value handling == skip) and there were more classes than predictor columns (unexpanded).
Added a flag to state whether response is expanded (true for DL, false for GLM).

PUBDEV-4339 GLM fix. 

---

h2o-algos/src/main/java/hex/DataInfo.java
h2o-algos/src/main/java/hex/glm/GLMTask.java
h2o-algos/src/main/java/hex/glrm/GLRM.java
h2o-algos/src/test/java/hex/glm/GLMTest.java

Filled in value was off by 1 if the missing value handling was set on skip.

PUBDEV-4319 Fix in unseen categorical levels handling in GLM scoring.

---

h2o-docs/src/front/index.html

On the docs.h2o.ai site, replaced SW 1.6 documentation links with SW 2.1. This now matches the SW download page, which only includes 2.0 and 2.1.

PUBDEV-4360: Add links for SW 2.1 docs on documentation site

---

h2o-algos/src/main/java/hex/glm/GLM.java
h2o-algos/src/main/java/hex/glm/GLMTask.java
h2o-algos/src/test/java/hex/glm/GLMTest.java

Even though zero columns should be filtered up front before the algorithm is even run, they can happen due to e.g. categorical level never occurring in the given fold. When this happens, coefficient should be removed on the fly and set to 0. However, this does not quite work for multinomial - there is too much complexity in working with subset of coefficients at a given time. Since multinomial is currently only implemented via coordinate descent over classes, it should be run with regularization and so zeroed predictors are not a problem.
Fix: 1) do not remove zeroed predictors if family==multinomial.
2) refined zeroed column detection - require both XtX and XtY to be zeroes for the given column. Zero XtX can happen in case of e.g. running binomial and given predictor turning prediction …

PUBDEV-4315

---

h2o-core/src/main/java/water/fvec/C0DChunk.java
h2o-core/src/test/java/water/fvec/NewChunkTest.java

C0DChunk with con==NaN should behave as all NA chunk, even for strings.
E.g. following should work, but it throws "Not a String" exception in master right now.
NewChunk nc = new NewChunk(...);
nc.addNa();
Chunk c = nc.compress();
assert c.atStr(new BufferedString(),0) == null; // instead get a "Not a String" Exception here.

PUBDEV-4363 Made C0DChunk with NaN con work with strings.

---

h2o-docs/src/product/getting-data-into-h2o.rst

Added a section about using a JDBC driver to import data into H2O. This section also describes the import_sql_table and import_sql_select functions, with R and Python examples.

HEXDEV-561: Documentation for JDBC Databases

---

h2o-docs/src/product/faq/r.rst

Added an FAQ to the FAQ > R topic describing how to resolve the following error: “Server error - server 127.0.0.1 is unreachable at this moment.”

PUBDEV-4397: Documentation addition - new FAQ entry for R

---

h2o-algos/src/main/java/hex/schemas/DRFV3.java
h2o-algos/src/main/java/hex/schemas/GBMV3.java
h2o-algos/src/main/java/hex/schemas/SharedTreeV3.java
h2o-algos/src/main/java/hex/tree/SharedTree.java
h2o-algos/src/main/java/hex/tree/SharedTreeModel.java
h2o-algos/src/test/java/hex/tree/gbm/GBMTest.java
h2o-core/src/main/java/hex/Model.java
h2o-core/src/main/java/hex/ModelBuilder.java
h2o-py/h2o/estimators/gbm.py
h2o-py/h2o/estimators/random_forest.py
h2o-r/h2o-package/R/gbm.R
h2o-r/h2o-package/R/randomforest.R
h2o-r/tests/testdir_algos/gbm/runit_GBM_calibration_binomial.R

GBM/DRF: Support for calibrating output probabilities using Platt Scaling.
Platt Scaling tutorial: http://danielnee.com/tag/platt-scaling/
Implemented as a post-processing step in the SharedTree[Model]. Calibrated probabilities are appended to the frame with original prediction. This is done in a separate scoring task. Combining tree scoring & glm scoring into the same task is challenging because the tree scoring logic doesn't expect the extra columns reserved for calibrated probabilities. This is the main reason why it is implemented in post-processing.

PUBDEV-3840: Implements Platt Scaling to GBM and DRF (binomial models)

---

h2o-docs/src/product/data-science/glm.rst

GLM can now supports multinomial classification models.
Driveby: For PUBDEV-4258, added two FAQs to the GLM topic describing why H2O’s glm differs from R’s and how to get the two to match.

PUBDEV-4396: GLM documentation updates

---

h2o-algos/src/main/java/hex/schemas/SharedTreeV3.java
h2o-py/h2o/estimators/gbm.py
h2o-py/h2o/estimators/random_forest.py
h2o-r/h2o-package/R/gbm.R
h2o-r/h2o-package/R/randomforest.R

`sample_rate_per_class` does not currently have a clear definition. This PR clarifies any potential confusion (see JIRA: https://0xdata.atlassian.net/browse/PUBDEV-4350?filter=-1)

PUBDEV-4350: Update R/Py docs about sample_rate_per_class

---

h2o-algos/src/main/java/hex/api/LeaveOneCovarOutHandler.java
h2o-algos/src/main/java/hex/api/RegisterAlgos.java
h2o-algos/src/main/java/hex/mli/loco/LeaveOneCovarOut.java
h2o-algos/src/main/java/hex/schemas/LeaveOneCovarOutV3.java
h2o-algos/src/test/java/hex/mli/LeaveOneCovarOutTest.java
h2o-core/src/main/java/water/ParallelizationTask.java
h2o-py/h2o/model/model_base.py
h2o-py/tests/testdir_algos/loco/pyunit_loco_binomial.py
h2o-py/tests/testdir_algos/loco/pyunit_loco_multinomial.py
h2o-py/tests/testdir_algos/loco/pyunit_loco_regression.py
h2o-r/h2o-package/R/models.R
h2o-r/scripts/h2o-r-test-setup.R
h2o-r/tests/runitUtils/locoR.R
h2o-r/tests/testdir_algos/loco/runit_loco_binomial.R
h2o-r/tests/testdir_algos/loco/runit_loco_multinomial.R
h2o-r/tests/testdir_algos/loco/runit_loco_regression.R

Leave One Covariate Out (LOCO):
Calculates row-wise variable importance's by re-scoring a trained supervised model and measuring the impact of setting each variable to missing or it’s most central value(mean or median & mode for categorical's)
What will be returned from LOCO?
An H2OFrame displaying the base prediction (model scored with all predictors) and the difference in predictions when variables are dropped/replaced. The difference displayed is the base prediction substracted from the new prediction (when a variable is dropped/replaced with mean/median/mode) for binomial classification and regression problems. For multinomial problems, the sum of the absolute value of differences across classes is calculated per column dropped/replaced.

Add Leave One Covariate Out (LOCO)

---

ec2/README.md
ec2/h2o-cluster-launch-instances.py

This PR modifies the ec2 helper scripts to allow requesting Spot instances, which can significantly lower the cost of large, long-running clusters.
In particular, this adds a new `spotBid` variable that, if set to anything other than `None`, will request that the desired instances be spun up through Spot. For more background on Spot, [see AWS](https://aws.amazon.com/ec2/spot/).
I needed Spot support for work, so I figured I might as well try to get up merged upstream.

Add support for requesting Spot instances

---

h2o-core/src/main/java/water/H2O.java
h2o-core/src/main/java/water/HeartBeat.java
h2o-core/src/main/java/water/Paxos.java

This simple change ensures that when multiple nodes from different clusters are started on the same physical node they don't collide. 
Any comments welcome!

[PUBDEV-4392] Verify cluster name also in flat-file cloud-up mode

---

h2o-algos/src/main/java/hex/klime/KLime.java
h2o-r/tests/testdir_algos/klime/runit_klime_titanic.R

k-LIME ignored order of columns imposed by GLM. GLM internally reorders columns to have categorical columns first, this was not affected in k-LIME which preserved the original order of columns.
The idea of the fix is to first compute the global GLM and use its order of columns for both k-means clustering and cluster-local GLMs.

PUBDEV-4389: k-LIME misinterprets order of categorical columns

---

h2o-docs/src/product/starting-h2o.rst

- Added a new “Authentication Options” section to Starting H2O > From the Command Line. This includes the new -form_auth and -session_timeout options as well as others that were previously undocumented.
- Added missing H2O starting options.

PUBDEV-4230: Documentation for -form_auth and -session_timeout

---

h2o-py/h2o/automl/autoh2o.py
h2o-py/tests/testdir_algos/automl/binomial/pyunit_automl_prostate.py
h2o-py/tests/testdir_algos/automl/multinomial/pyunit_automl_iris.py
h2o-py/tests/testdir_algos/automl/pyunit_automl_args.py
h2o-py/tests/testdir_algos/automl/pyunit_automl_ignore_cols.py
h2o-py/tests/testdir_algos/automl/regression/pyunit_automl_australia.py

* Change `get_leaderboard()` and `get_leader()`in `H2OAutoML` methods to properties called `.leader` and `.leaderboard`.

PUBDEV-4414: Change get_leaderboard() and get_leader() in Py API to Python properties

---

h2o-algos/src/main/java/hex/klime/KLime.java
h2o-algos/src/main/java/hex/klime/KLimeModel.java
h2o-algos/src/main/java/water/api/ModelMetricsKLimeV3.java
h2o-algos/src/test/java/hex/klime/KLimeTest.java
h2o-core/src/main/java/hex/ModelMetricsRegression.java
h2o-py/h2o/model/metrics_base.py
h2o-r/tests/testdir_algos/klime/runit_klime_titanic.R

Improvement of k-LIME: model performance metrics are reported for each cluster.
It also lays groundwork for improving overall k-LIME performance, in next PR we will compare R2 of GLM on a cluster with R2 of global GLM calculated from only the data that belong to the cluster.

k-LIME, report metrics for cluster-local models

---

h2o-docs/src/product/flow.rst
h2o-docs/src/product/save-and-load-model.rst

The “Saving and Loading a Model” section for Flows now points to this topic in the Flow section. Previously, this included steps for saving and loading Flows rather than models. Additionally, all of the information about saving flows from that topic is duplicated in the Flow section.

PUBDEV-4403: Documentation for saving and loading flows

---

README.md
h2o-hadoop/h2o-mapreduce-generic/src/main/java/water/hadoop/h2odriver.java

Per discussion with Steam team, this PR should support secure user impersonation for the h2odriver against a kerberized Hadoop cluster.  This is intended to support user impersonation from command-line invocation of the h2odriver.  Steam will need to make necessary changes to support "impersonation" in this way, passing a user principal and keytab of a configured proxy user with the `-run_as_user` arg set to the user to be impersonated.  (greater details in updated README).
Also updated README with information on secure impersonation, how to configure the proxy user, and how to run the h2odriver when impersonation is configured.  It's not apparent from the doc, but even when impersonation is enabled users can still use h2o from the command line as normal.
The code was 90% there - just …

[PUBDEV-4436] Steam hadoop user impersonation

---

h2o-docs/src/product/data-science/algo-params/compute_metrics.rst
h2o-docs/src/product/data-science/algo-params/k.rst
h2o-docs/src/product/data-science/pca.rst

Adding links from PCA parameters to the Parameters appendix. Added PCA to “Available in” section for k and compute_metrics parameters.

PUBDEV-4335: PCA documentation - add links to Parameters

---

h2o-hadoop/driverjar.gradle
h2o-hadoop/h2o-mapreduce-generic/src/main/java/org/apache/hadoop/mapreduce/v2/app/H2OMRAppMaster.java
h2o-hadoop/h2o-mapreduce-generic/src/main/java/water/hadoop/mapred/H2OYARNRunner.java
h2o-hadoop/h2o-mapreduce-generic/src/main/java/water/hadoop/mapred/H2OYarnClientProtocolProvider.java
h2o-hadoop/h2o-mapreduce-generic/src/main/resources/META-INF/services/org.apache.hadoop.mapreduce.protocol.ClientProtocolProvider

The h2odriver can specify H2O specific application master.
The application master is still based on standard MRAppMaster, however
it overrides default application type to 'H2O'.
The is an optional feature! To enable it, a launcher needs to override
default MRAppMaster by specifying the following parameter:
```
-Dmapreduce.framework.name=h2o-yarn
```
For example:
```
hadoop jar h2odriver.jar -Dmapreduce.framework.name=h2o-yarn -nodes 1 -mapperXmx 4G -output -ichal_1
```

[PUBDEV-4331][SW-311] Override default MapReduce type to H2O type

---

h2o-automl/src/main/java/ai/h2o/automl/AutoML.java
h2o-automl/src/main/java/ai/h2o/automl/AutoMLBuildSpec.java
h2o-automl/src/main/java/ai/h2o/automl/Leaderboard.java
h2o-automl/src/main/java/water/automl/api/schemas3/AutoMLBuildSpecV99.java
h2o-docs/src/product/automl.rst
h2o-py/h2o/automl/autoh2o.py
h2o-py/tests/testdir_algos/automl/binomial/pyunit_automl_prostate.py
h2o-py/tests/testdir_algos/automl/multinomial/pyunit_automl_iris.py
h2o-py/tests/testdir_algos/automl/pyunit_automl_args.py
h2o-py/tests/testdir_algos/automl/pyunit_automl_ignore_cols.py
h2o-py/tests/testdir_algos/automl/regression/pyunit_automl_australia.py
h2o-r/h2o-package/R/automl.R
h2o-r/tests/testdir_algos/automl/runit_automl_binomial_leaderboard_higgs.R

After feedback from the team, we decided it's probably best to change the name `test_frame` to `leaderboard_frame`.
Notes: `test_frame` should be called `leaderboard_frame` (or similar), because people didn’t like the idea of evaluating models on a “test set” and then choosing the best model from that. It really should be referred to as a validation/holdout set rather than a “test set”, but we already used the `validation_frame` to tune individual models via early stopping, so to be clear that this is used only for creating the leaderboard, we will change the name to `leaderboard_frame`.  This frame will only be used to generate the leaderboard metrics. Someone also mentioned that they'd prefer to use the `validation_frame` for the leaderboard metrics because they doesn’t want to split …

PUBDEV-4422: Change argument name test_frame to leaderboard_frame in AutoML

---

h2o-automl/src/main/java/ai/h2o/automl/AutoML.java

* This PR changes the logic in GLM grid in AutoML. Currently, if the outcome is 0/1, the GLM grid will assume it is a classification problem. However, other algorithms in AutoML will read this as a regression, which will cause a collision. 
* The solution is to ensure the outcome is binary and NOT numeric for classification in GLM grid.

PUBDEV-4452: AutoML regression task gives error related to mean_residual_deviance

---

h2o-hadoop/h2o-mapreduce-generic/src/main/java/water/hadoop/h2omapper.java

This reduces junk logs for long jobs by a ratio of 1:6.
Note the default timeout before action is taken by the jobtracker is 10 minutes, so this is now a 1 minute ping.

PUBDEV-4465: Change jobtracker progress interval from 10 seconds to 60 seconds

---

h2o-docs/src/product/faq/general.rst

Updated an FAQ in the user guide to state that H2O now supports GPUs. Added links to the product page on the main h2o site and to a Deep Learning + Tensorflow + AWS tutorial.

PUBDEV-4467: Updated FAQ in user guide

---

h2o-py/h2o/automl/autoh2o.py
h2o-py/tests/testdir_algos/automl/binomial/pyunit_automl_prostate.py
h2o-py/tests/testdir_algos/automl/features/pyunit_automl_fold_assignment.py
h2o-py/tests/testdir_algos/automl/multinomial/pyunit_automl_iris.py
h2o-py/tests/testdir_algos/automl/pyunit_automl_args.py
h2o-py/tests/testdir_algos/automl/pyunit_automl_ignore_cols.py
h2o-py/tests/testdir_algos/automl/regression/pyunit_automl_australia.py

* Moved the remainder of the build_control args to the top-level user API in Python, so that they are properly documented and more accessible and easy to use.
* `build_control` params moved to top-level:
1. max_runtime_secs
2. max_models
3. stopping_metric
4. stopping_tolerance
5. stopping_rounds
6. seed
* Updated tests to account for new parameters

PUBDEV-4459: AutoML: Move the rest of build_control args to top-level in Python API

---

h2o-docs/src/front/index.html

“Partners” is now available on main doc site, making this more consistent with the h2o.ai site.
Driveby fix: Removed unnecessary “style” tag that was mid-line. Font shows up correctly in all tested browsers.

PUBDEV-4470: Added Partners to top banner

---

h2o-core/src/main/java/hex/ModelMetricsBinomial.java

If response has NA, we have an invalid at8() access in biomial model metrics.

PUBDEV-4372: Minor NA check fix.

---

h2o-core/src/main/java/hex/ConfusionMatrix.java

The confusion matrix header now reads:
```
> h2o.confusionMatrix(model)
Confusion Matrix: Row labels: Actual class; Column labels: Predicted class
setosa versicolor virginica  Error      Rate
setosa         50          0         0 0.0000 =  0 / 50
versicolor      0         48         2 0.0400 =  2 / 50
virginica       0          1        49 0.0200 =  1 / 50
Totals         50         49        51 0.0200 = 3 / 150
```

PUBDEV-4250: Updated confusion matrix header to be more clear

---

h2o-algos/src/main/java/hex/deeplearning/DeepLearning.java
h2o-algos/src/main/java/hex/deeplearning/DeepLearningModel.java
h2o-algos/src/main/java/hex/deeplearning/DeepLearningModelInfo.java
h2o-algos/src/test/java/hex/deeplearning/DeepLearningTest.java
h2o-py/h2o/estimators/deeplearning.py
h2o-py/tests/testdir_algos/deeplearning/pyunit_iris_no_hidden.py
h2o-r/h2o-package/R/deeplearning.R
h2o-r/h2o-package/R/kvstore.R
h2o-r/tests/testdir_algos/deeplearning/runit_deeplearning_no_hidden.R

Allow training of deeplearning models without a hidden layer.
TODO:
* DONE Add workaround everywhere where hidden[i] is accessed. (e.g., variable importances)
* DONE Check that POJO works
* DONE (was there already) Add support for a single bias term ("intercept")
* DONE Test classification and regression, should compare to GLM
* DONE Add R/Py/JUnits
* DONE Check Flow
* Update docs

PUBDEV-4364 - Support for DL models without hidden layers (and always compute varimp)

---

h2o-r/h2o-package/R/import.R
h2o-r/tests/testdir_algos/kmeans/runit_kmeans_getModel.R
h2o-r/tests/testdir_algos/kmeans/runit_kmeans_prostate.R

- Removed h2o.importURL deprecated function from import.R
- Removed commented references from runit_kmeans tests
- JIRA here: https://0xdata.atlassian.net/browse/PUBDEV-4481

[PUBDEV-4481] Removed deprecated h2o.importURL function from R API

---

h2o-docs/src/product/automl.rst
h2o-docs/src/product/data-science/algo-params/max_runtime_secs.rst
h2o-docs/src/product/data-science/algo-params/seed.rst
h2o-docs/src/product/data-science/algo-params/stopping_metric.rst
h2o-docs/src/product/data-science/algo-params/stopping_rounds.rst
h2o-docs/src/product/data-science/algo-params/stopping_tolerance.rst
h2o-docs/src/product/data-science/algo-params/training_frame.rst
h2o-docs/src/product/data-science/algo-params/validation_frame.rst
h2o-docs/src/product/data-science/algo-params/y.rst
h2o-docs/src/product/flow.rst

Added the following parameters to the AutoML section of the user guide:
- max_models
- stopping_metric
- stopping_tolerance
- stopping_rounds
- seed
- project_name
Linked parameters to the Parameters Appendix (where available).
Renamed the max_models parameter in the Flow section of the User Guide.

PUBDEV-4502: Add new parameters to AutoML documentation

---

h2o-docs/src/product/data-science/stacked-ensembles.rst
h2o-docs/src/product/save-and-load-model.rst
h2o-py/h2o/h2o.py
h2o-r/h2o-package/R/export.R
h2o-r/h2o-package/R/import.R

- In User Guide, updated the FAQ that previously indicated users could save and load stacked ensemble models
- In R docs, added a note to loadModel and saveModel indicating that users can save and load ensemble binary models
- In Python docs, added a note to load_model and save_model indicating that users can save and load ensemble binary models
- Driveby fix: Fixed the R example in Saving and Loading a model. Highlighting is no longer skipped.

PUBDEV-4494: Saving and Loading Ensemble Binary Models

---

h2o-docs/src/product/data-science/algo-params/impute_missing.rst
h2o-docs/src/product/data-science/algo-params/k.rst
h2o-docs/src/product/data-science/algo-params/pca_method.rst
h2o-docs/src/product/data-science/algo-params/transform.rst
h2o-docs/src/product/data-science/algo-params/use_all_factor_levels.rst
h2o-docs/src/product/data-science/pca.rst
h2o-docs/src/product/parameters.rst

- Added impute_missing, transform, pca_method, and use_all_factor_levels to Parameters appendix. Updated the index to include these parameters.
- Added a PCA-specific description for the k parameter.
- Added impute_missing to the list of parameters in the PCA section (where it was missing).

PUBDEV-4336: Documenting PCA parameters

---

h2o-bindings/bin/gen_R.py

This was never functional in the R API because it was not properly exported to the namespace.
Now it will say:
```r
> h2o.deepwater.available()
[1] "Cannot build a Deep Water model - no backend found."
[1] FALSE
```
It still needs to be tested against a system with a valid Deep Water backend.

PUBDEV-4499: Export h2o.deepwater.available function in R API

---

h2o-docs/src/product/data-science/algo-params/categorical_encoding.rst

Added series of available Aggregator categorical_encoding options and included the new enum_limited option. Also indicated that categorical_encoding options are gridable (which was missing).

PUBDEV-4513: Documentation for new categorical_encoding option

---

h2o-web/package.json

This PR resolves the NPM warning:
`npm WARN h2o-web@0.0.0 license should be a valid SPDX license expression`
that currently prints every time someone builds **h2o-3**
more signal, less noise 😄 
[JIRA PUBDEDV-4181](https://0xdata.atlassian.net/browse/PUBDEV-4181)

PUBDEV-4181 use valid spdx license expression for h2o-web package.json

---

h2o-algos/src/test/java/hex/DataInfoTest.java
h2o-algos/src/test/java/hex/glm/GLMBasicTestBinomial.java
h2o-core/src/main/java/water/parser/CsvParser.java
h2o-core/src/main/java/water/parser/ParseDataset.java
h2o-core/src/main/java/water/parser/ParseSetup.java
h2o-core/src/main/java/water/parser/Parser.java
h2o-core/src/main/java/water/parser/PreviewParseWriter.java
h2o-core/src/main/java/water/parser/SVMLightParser.java
h2o-core/src/main/java/water/parser/StreamParseWriter.java
h2o-core/src/main/java/water/parser/XlsParser.java
h2o-core/src/test/java/water/TestUtil.java
h2o-core/src/test/java/water/parser/ParserTestARFF.java
h2o-parsers/h2o-orc-parser/src/main/java/water/parser/orc/OrcParser.java
h2o-parsers/h2o-orc-parser/src/test/java/water/parser/ParseTestMultiFileOrc.java
h2o-parsers/h2o-orc-parser/src/test/java/water/parser/ParseTestOrc.java

1. Parser.setupLocal was not called when doing stream parse
2. Orc does not read from passed input stream, it reads data via ORC libraries -> needs its own streamParse loop
3. There was a strange behavior in h2o where streamParse did something different from streamParseZip and in fact streamParseZip was being used for actual parsing even fro non-zipped data.

PUBDEV-4416 - fix ORC stream parse

---

h2o-py/h2o/automl/autoh2o.py

* Currently, fold_column and weights_column only work if we don't include an `x` argument. If `x` is specified, it throws an error. This can be fixed on the client side. The cause of this is how we calculate the `ignored_columns` arg from the difference between all columns and (x, y).

PUBDEV-4509: AutoML fails when fold_column or weights_column and x are both specified in Python

---

h2o-automl/src/main/java/ai/h2o/automl/AutoML.java
h2o-automl/src/main/java/ai/h2o/automl/AutoMLBuildSpec.java
h2o-automl/src/main/java/ai/h2o/automl/EckoClient.java
h2o-automl/src/main/java/ai/h2o/automl/Leaderboard.java
h2o-automl/src/main/java/water/automl/RegisterRestApi.java
h2o-automl/src/main/java/water/automl/api/LeaderboardsHandler.java
h2o-automl/src/main/java/water/automl/api/schemas3/AutoMLBuildSpecV99.java
h2o-automl/src/main/java/water/automl/api/schemas3/AutoMLV99.java
h2o-automl/src/main/java/water/automl/api/schemas3/AutoMLsV99.java
h2o-automl/src/main/java/water/automl/api/schemas3/LeaderboardV99.java
h2o-automl/src/main/java/water/automl/api/schemas3/LeaderboardsV99.java
h2o-py/h2o/automl/autoh2o.py
h2o-r/h2o-package/R/automl.R

* We use project_name in the AutoML R/Py APIs, so we should change the name on the backend (Java) as well for consistency. The R and Python APIs will also need a small change – they send project_name to the build_control$project / build_control['project'] , so that will require a small edit.

PUBDEV-4496: Change project to project_name in AutoML backend

---

h2o-docs/src/product/automl.rst
h2o-docs/src/product/data-science/algo-params/categorical_encoding.rst
h2o-docs/src/product/data-science/algo-params/fold_column.rst
h2o-docs/src/product/data-science/algo-params/weights_column.rst
h2o-docs/src/product/faq/general.rst

- Added fold_column and weights_column parameters to the AutoML topic.
- Added “AutoML” as a supported algo for each of these parameters in the Appendix.
- Changed the default sort metric for regression problems to be deviance.
Driveby fix: Fixed bulleted list in FAQ > General topic.
Adding @ledell in the case of any additional updates.

PUBDEV-4529: Added new parameters to AutoML topic

---

h2o-r/h2o-package/R/automl.R
h2o-r/h2o-package/R/models.R

* Currently, we must do this:
`pred <- h2o.predict(aml@leader, test)`
* But we want to also be able to do this:
`pred <- h2o.predict(aml, test) `
or
`pred <- predict(aml, test)`

PUBDEV-4428: Add ability to predict on an H2OAutoML object directly in R

---

h2o-core/src/main/java/water/util/Log.java

Log.info method internally used method which did not do the log initialisation which is against the design of our logging. This PR ensures that we call the correct method which eventually initialise the correct logging

[PUBDEV-4542] Fix bug with Log.info method bypassing handling of buffered messages

---

h2o-r/tests/testdir_algos/automl/runit_automl_args.R

* This is a hot fix for `runit_automl_args.R`.
* The test needs to ensure that it is not trying to fetch fold/weights columns for Stacked Ensembles as these do not exist for this model type.

[HOTFIX]: Ensure `runit_automl_args.R` has proper model to fetch fold/weight column

---

h2o-algos/src/main/java/hex/StackedEnsembleModel.java
h2o-algos/src/main/java/hex/ensemble/StackedEnsemble.java
h2o-algos/src/test/java/hex/ensemble/StackedEnsembleTest.java
h2o-py/tests/testdir_algos/stackedensemble/pyunit_stackedensemble_regression.py

* This PR cleans up stacked ensembles by getting rid of unnecessary frames, vecs, & models that are produced when compiled.
* Added a Junit to confirm.

PUBDEV-4490: Ensure Stacked Ensemble cleans up frames/base models/metalearner/vecs. Add Junit

---

h2o-docs/src/front/index.html

- Changed “Launch Deep Water AMI” button link to point to https://github.com/h2oai/deepwater#pre-release-amazon-aws-image
- Changed the recommended machine on the launch button to be p2.xlarge
instead of h2.2xlarge.
- Added a link to the docker image at https://github.com/h2oai/deepwater#pre-release-docker-image

PUBDEV-4551: Documentation updates for Deep Water on docs.h2o.ai

---

h2o-docs/src/product/welcome.rst

Removed CDH 5.2, 5.3, and HDP 2.1 from documentation.
Added IOP 4.2 to list of supported Hadoop platforms.

PUBDEV-4552: Documentation update for supported Hadoop platforms

---

build.gradle
h2o-assemblies/genmodel/build.gradle
h2o-assemblies/main/build.gradle

in assembly jar file
Custom ShadowJar task had to be created as it does not have public API to add files from somewhere else. The `append` method is used for a bit different thing, see https://github.com/johnrengelman/shadow/issues/180
However this gives us a better control of what goes into shadow jar and we can specify additional files to go inside easily.
This change downloads licence for each used dependency and put the reported xml file into the META-INF directory of the generated jar as part of the build process

[PUBDEV-4536] Provides a file which contains a list of licenses for each H2O dependency

---

h2o-algos/src/main/java/hex/StackedEnsembleModel.java
h2o-algos/src/main/java/hex/schemas/StackedEnsembleV99.java
h2o-automl/src/main/java/ai/h2o/automl/AutoML.java
h2o-docs/src/product/data-science/stacked-ensembles.rst
h2o-py/h2o/estimators/stackedensemble.py
h2o-py/tests/testdir_algos/gbm/pyunit_gbm_random_grid.py
h2o-py/tests/testdir_algos/gbm/pyunit_gbm_random_grid_large.py
h2o-py/tests/testdir_algos/stackedensemble/pyunit_stackedensemble_binomial.py
h2o-py/tests/testdir_algos/stackedensemble/pyunit_stackedensemble_gaussian.py
h2o-py/tests/testdir_algos/stackedensemble/pyunit_stackedensemble_grid_binomial.py
h2o-py/tests/testdir_algos/stackedensemble/pyunit_stackedensemble_grid_gaussian.py
h2o-py/tests/testdir_algos/stackedensemble/pyunit_stackedensemble_regression.py
h2o-r/h2o-package/R/stackedensemble.R
h2o-r/tests/testdir_algos/gbm/runit_GBMGrid_airlines.R
h2o-r/tests/testdir_algos/gbm/runit_GBMRandomGrid_airlines_large.R
h2o-r/tests/testdir_algos/stackedensemble/runit_stackedensemble_binomial.R
h2o-r/tests/testdir_algos/stackedensemble/runit_stackedensemble_gaussian.R
h2o-r/tests/testdir_algos/stackedensemble/runit_stackedensemble_grid_binomial.R
h2o-r/tests/testdir_algos/stackedensemble/runit_stackedensemble_grid_gaussian.R

- Since the `selection_strategy` parameter doesn't do anything, it should be removed. I think it's a bad idea to have a parameter that's not being used in the API.  We also don't have concrete plans for how we might use it in the immediate future, so for now we can keep it out of the API.
- The code has not been removed, it's been commented out so that if we ever decide to implement it in the future, it will be easy to add back in. Since our R and Python APIs are auto-generated, it's best comment it out from the Java code.  Removing it from the backend also automagically removes it from Flow.
- JIRA: https://0xdata.atlassian.net/browse/PUBDEV-4511
Now is our best chance to drop this parameter from the API since it's a major release (3.12).

PUBDEV-4511: Remove selection_strategy argument from Stacked Ensemble

---

h2o-algos/src/main/java/hex/coxph/CoxPH.java
h2o-algos/src/main/java/hex/glm/GLM.java
h2o-algos/src/main/java/hex/glm/GLMMetricBuilder.java
h2o-algos/src/main/java/hex/glm/GLMModel.java
h2o-algos/src/main/java/hex/glm/GLMScore.java
h2o-algos/src/test/java/hex/glm/GLMTest.java
h2o-core/src/main/java/hex/Model.java
h2o-core/src/main/java/water/fvec/CategoricalWrappedVec.java
h2o-core/src/main/java/water/fvec/Vec.java
h2o-core/src/main/java/water/rapids/ast/prims/advmath/AstKFold.java
h2o-core/src/main/java/water/rapids/ast/prims/advmath/AstStratifiedSplit.java
h2o-core/src/main/java/water/rapids/ast/prims/mungers/AstPivot.java
h2o-core/src/main/java/water/util/ArrayUtils.java
h2o-core/src/main/java/water/util/FrameUtils.java
h2o-core/src/main/java/water/util/IcedDouble.java
h2o-core/src/main/java/water/util/IcedLong.java
h2o-core/src/main/java/water/util/VecUtils.java
h2o-core/src/test/java/water/fvec/CategoricalWrappedVecTest.java

1. When training on data in {lb,ub}, set {str(lb),str(ub)} as domain but use actual numeric values during training.
(this means all metrics are calculated with binary response!)
2. Mark quasibinomial model as binomial.
3. Had to fix Vec.adapt and Vec.toCategorical to work with double domain.

 PUBDEV-4484 - Make quasibinomial glm model behave like binomial.

---

h2o-docs/src/product/automl.rst

Updated the AutoML examples and model outputs based on new naming convention AND [now] the output from cited example.
@erin for review.

PUBDEV-4535: Re-Updating AutoML output in docs

---

h2o-algos/src/main/java/hex/DataInfo.java
h2o-algos/src/main/java/hex/glm/ComputationState.java
h2o-algos/src/main/java/hex/glm/GLM.java
h2o-algos/src/main/java/hex/glm/GLMTask.java
h2o-algos/src/main/java/hex/gram/Gram.java
h2o-algos/src/test/java/hex/glm/GLMBasicTestMultinomial.java
h2o-algos/src/test/java/hex/glm/GLMTest.java
h2o-core/src/main/java/water/util/ArrayUtils.java

Gram matrix (XtX) is now cached whenever possible when computing GLM and only incrementally updated (in case there is new columns in the model).
Huge performance impact on gaussian lambda search, noticeable improvement for other families (can save 0 ~ 30% of matrix computation).
Only active for solver==COD.

Added incremental gram computation to GLM.

---

h2o-docs/src/product/data-science/algo-params/model_id.rst
h2o-docs/src/product/data-science/algo-params/stopping_rounds.rst
h2o-docs/src/product/data-science/algo-params/training_frame.rst
h2o-docs/src/product/data-science/algo-params/validation_frame.rst
h2o-docs/src/product/data-science/stacked-ensembles.rst

- In Stacked Ensembles, noted that in R, the base_models parameter can accept models rather than just model IDs.
- Added links from the Stacked Ensembles config options to the parameters section (where available)
- Added “Stacked Ensembles” to the parameters in the Appendix where Stacked Ensembles is supported.
Driveby fix: Added default values to the stopping_rounds option.

PUBDEV 4096: Documentation updates for Stacked Ensembles

---

h2o-core/src/main/java/water/rapids/ast/params/AstNumList.java
h2o-core/src/test/java/water/rapids/RapidsTest.java
h2o-r/tests/testdir_jira/runit_PUBDEV_4438_one_off.R

Two things:
1. Fixed index problem in method index of AstNumList.java.  Given a list of [0,1,2,3, ...], the returned index for 0 and 1 are both 0 and the return index of 2 or more is one less that it should be.  Easy fix: changed 
if (bIdx >= 0) return water.util.ArrayUtils.sum(_cnts, 0, bIdx - 1);
TO
if (bIdx >= 0) return water.util.ArrayUtils.sum(_cnts, 0, bIdx );
2. Add Runit test to make sure the assignment error is gone. 
-------------------------
The reason that you only see this problem if you have more than 1000 elements is because for data with less than 1001 elements, different function calls are made!

Pubdev 4438 one off error

---

h2o-algos/src/main/java/hex/tree/drf/DRF.java
h2o-core/src/main/java/water/util/MathUtils.java
h2o-py/tests/testdir_algos/rf/pyunit_PUBDEV_4456_airline_weights_large.py
h2o-r/tests/testdir_algos/randomforest/runit_PUBDEV_4456_airline_weights_large.R

PUBDEV-4142 causes a numerical issue:
When fs[1] is 1, it is read back as 1.0000000000000002. To get around this error, I just added a tolerance at the end of the bound and changed the assertion to:
assert(fs[1]>=-1e-12 && fs[1] <= 1+1e-12. 
This solves the problem for now.
Added Runit/Pyunit tests to check and make sure the current hack is working.

Pubdev 4456 rf weights problem

---

h2o-docs/src/booklets/v2_2015/source/DeepWaterBooklet.tex
h2o-docs/src/booklets/v2_2015/source/PythonBooklet.tex
h2o-docs/src/booklets/v2_2015/source/RBooklet.tex
h2o-docs/src/booklets/v2_2015/source/sw/sections/apps.tex
h2o-docs/src/booklets/v2_2015/source/sw/sections/deployment.tex
h2o-docs/src/booklets/v2_2015/source/sw/sections/pysparkling.tex
h2o-docs/src/front/index.html

- In the Sparkling Water booklet, removed the sentence that reads “The same command works for Python programs” along with the code sample. Also replaced references of 1.6 with 2.1.
- In the Deep Water booklet, removed XGBoost from list of “Coming Soon”
- In the Python and R booklets, added XGBoost under the list of supervised learning algorithms. Also updated the list of accepted data source file formats in Python.
Driveby fix: On the doc site, updated the links for the Sparkling Water scaladoc pages for 2.0 and 2.1.

PUBDEV-4579: Updates to booklets

---

h2o-r/h2o-package/R/frame.R

Added the supported aggregate functions for the group_by function in R. This information is in the Details section of the group_by function.

PUBDEV-4549-rel-vajda: Aggregate functions in R

---

h2o-docs/src/product/data-science/algo-params/model_id.rst
h2o-docs/src/product/data-science/algo-params/stopping_rounds.rst
h2o-docs/src/product/data-science/algo-params/training_frame.rst
h2o-docs/src/product/data-science/algo-params/validation_frame.rst
h2o-docs/src/product/data-science/stacked-ensembles.rst

- In the documentation for Stacked Ensembles, added that in R, you can specify a list of models in the ``base_models`` parameter.
- Added links from the Stacked Ensembles config options to the parameters section (where available)
- Added “Stacked Ensembles” to the parameters in the Appendix where Stacked Ensembles is supported.
Driveby fix: Added default values to the stopping_rounds option.

PUBDEV-4096-rel-vajda: Updates for Stacked Ensembles docs

---

h2o-docs/src/booklets/v2_2015/source/DeepWaterBooklet.tex
h2o-docs/src/booklets/v2_2015/source/PythonBooklet.tex
h2o-docs/src/booklets/v2_2015/source/RBooklet.tex
h2o-docs/src/booklets/v2_2015/source/sw/sections/apps.tex
h2o-docs/src/booklets/v2_2015/source/sw/sections/deployment.tex
h2o-docs/src/booklets/v2_2015/source/sw/sections/pysparkling.tex
h2o-docs/src/front/index.html

- In the Sparkling Water booklet, removed the sentence that reads “The same command works for Python programs” along with the code sample. Also replaced references of 1.6 with 2.1.
- In the Deep Water booklet, removed XGBoost from list of “Coming Soon”
- In the Python and R booklets, added XGBoost under the list of supervised learning algorithms. Also updated the list of accepted data source file formats in Python.
Driveby fix: On the doc site, updated the links for the Sparkling Water scaladoc pages for 2.0 and 2.1.

PUBDEV-4579-rel-vajda: Updates to booklets

---

h2o-algos/src/main/java/hex/schemas/GLMV3.java
h2o-py/h2o/estimators/glm.py
h2o-r/h2o-package/R/glm.R

Updated the GLMV3.java file with an improved description for the alpha command.
The change to the alpha description has to be made in the GLMV3.java file. Built H2O locally after, and the associated files were also updated. Also, the generated PDF displays the updated description for alpha.
Driveby fix: Fixed capitalization in other GLM parameter descriptions.

PUBDEV-4583: Updated description for Alpha command in R docs

---

h2o-docs/src/product/data-science/algo-params/calibrate_frame.rst
h2o-docs/src/product/data-science/algo-params/calibrate_model.rst
h2o-docs/src/product/data-science/drf.rst
h2o-docs/src/product/data-science/gbm.rst
h2o-docs/src/product/flow.rst
h2o-docs/src/product/parameters.rst

- Added calibrate_frame and calibrate_model to list of parameters in the Appendix.
- Added links to these options in the GBM and DRF topics. Also updated the References section in these topics.
- Added links to these options in the Parameters index
- Updated Flow topic to include these options.
Driveby fix: Cleaned up entries in the Flow topic.

PUBDEV-4523: Documentation for new GBM/DRF params (rel-vajda)

---

h2o-docs/src/product/tutorials/GridSearch.md

/<version>/Grid/<algo_name> is singular, not plural.
https://github.com/h2oai/h2o-3/blob/581a0f2e7f6da916c6b9bbbd015867e46d5192df/h2o-core/src/main/java/water/api/GridSearchHandler.java#L51

Starting a new grid search is Grid endpoint

---

h2o-docs/src/product/data-science/algo-params/balance_classes.rst
h2o-docs/src/product/data-science/algo-params/use_all_factor_levels.rst
h2o-docs/src/product/data-science/deep-learning.rst

- In the `balance_class` parameter entry, added a link to a Harvard paper.
- Added links from the Deep Learning section to the parameters (where available). Added this because the original request regarding balance classes was specifically regarding Deep Learning. This also prepares for the upcoming Deep Learning parameter description task.
Driveby fix: Added Deep Learning as a supported algorithm for the `use_all_factor_levels` option.

PUBDEV-4515: Add link in balance classes for more info

---

h2o-docs/src/product/data-science/algo-params/balance_classes.rst
h2o-docs/src/product/data-science/algo-params/use_all_factor_levels.rst
h2o-docs/src/product/data-science/deep-learning.rst

Updates this time into master:
- In the balance_class parameter entry, added a link to a Harvard paper.
- Added links from the Deep Learning section to the parameters (where
available). Added this because the original request regarding balance
classes was specifically regarding Deep Learning. This also prepares for the upcoming Deep Learning parameter description task.
Driveby fix: Added Deep Learning as a supported algorithm for the
use_all_factor_levels option.

PUBDEV-4515: Documentation updates to balance_classes

---

h2o-docs/src/product/data-science/algo-params/distribution.rst
h2o-docs/src/product/data-science/xgboost.rst

- Removed `laplace`, `quantile`, and `huber` from list of supported distribution options in XGBoost.
- For the `distribution` parameter description, noted that `laplace`, `quantile`, and `huber` are not available in XGBoost.

PUBDEV-4610: Remove unsupported distribution options from XGBoost docs

---

h2o-core/src/main/java/water/Job.java
h2o-core/src/main/java/water/api/ModelBuilderHandler.java
h2o-py/tests/testdir_algos/glm/pyunit_PUBDEV_4959_model_error.py
h2o-r/h2o-package/R/communication.R
h2o-r/tests/testdir_algos/glm/runit_PUBDEV_4595_model_error.R

Four things:
- Added code in backend to replace / with _ in model ID.
- Added warning on bad model_id to job warning which is automatically handled by all clients.
- Fixed bug in R client to allow white spaces in model_id.
- Added Pyunit and Runit tests to capture warnings when bad model_ids are used.

PUBDEV-4595: model error.  Replace / in mode_id with _ and generate a user warning

---

h2o-docs/src/product/data-science/algo-params/balance_classes.rst
h2o-docs/src/product/data-science/algo-params/class_sampling_factors.rst
h2o-docs/src/product/data-science/algo-params/max_after_balance_size.rst
h2o-docs/src/product/data-science/algo-params/max_hit_ratio_k.rst
h2o-docs/src/product/data-science/glm.rst

In the GLM section of the user guide, added parameters for the following:
- balance_classes
- class_sampling_factors
- max_after_balance_size
- max_hit_ratio_k
- max_runtime_secs
In the Parameters Appendix, added “GLM” to the “Available In” section for these parameters.

PUBDEV-4621: Add documentation for missing GLM parameters

---

h2o-docs/src/product/tutorials/GridSearch.md

`Grid` correction seems to have been reverted in https://github.com/h2oai/h2o-3/commit/ed77175a9a2b4e72853270fe7871461b3179b924#diff-deed868a9c728f3ebdc2a862a35ee31b

Fixing Grid endpoint

---

h2o-algos/src/main/java/hex/deeplearning/DeepLearning.java
h2o-algos/src/main/java/hex/glrm/GLRM.java
h2o-algos/src/main/java/hex/kmeans/KMeans.java
h2o-algos/src/main/java/hex/naivebayes/NaiveBayes.java
h2o-algos/src/main/java/hex/pca/PCA.java
h2o-algos/src/main/java/hex/svd/SVD.java
h2o-algos/src/main/java/hex/tree/SharedTree.java
h2o-core/src/main/java/hex/ModelBuilder.java

The target audience is internal QA who can disable the check to make sure
that estimates of model sizes are not inflated (and that the modelling
would actually finishes if the memory check was not present).
See jira PUBDEV-4608 for reference.

PUBDEV-4608: Allows to disable internal memory checks during training

---

h2o-genmodel/src/main/java/hex/genmodel/GenModel.java
h2o-genmodel/src/main/java/hex/genmodel/easy/EasyPredictModelWrapper.java
h2o-genmodel/src/main/java/hex/genmodel/easy/prediction/AutoEncoderModelPrediction.java
h2o-genmodel/src/test/java/hex/genmodel/easy/EasyPredictModelWrapperTest.java

This is a proposal of a barebones interface of AutoEncoderPrediction.
What is missing:
- documentation,
- interface doesn't provide reconstruction error - this is currently hard to do because error is calculated on normalized values and there is no natural way how to get the normalization coefficients from the current GenModel for AutoEncoder

[PUBDEV-3941] Make EasyModelPredictWrapper work for AutoEncoders

---

h2o-automl/src/main/java/ai/h2o/automl/Leaderboard.java

Jenkins was running slowly, built no models, and accidentally tripped over this bug.  I repro'd by temporarily creating an empty leaderboard in AutoML.java.

PUBDEV-4642: AutoML: NPE in leaderboard if there are no models

---

Dockerfile

Java 7 on Ubuntu 14.04 seems to be (at least temporarily) broken.

upgrade dockerfile to run Java 8 on Ubuntu 16.04

---

h2o-py/h2o/h2o.py

* This behavior is expected as you did not parse the dataset. The documentation should be updated to state that it will return a list if parse is set to False.

PUBDEV-4625: h2o.import_file(parse=False) in python api returns list instead of H2OFrame

---

h2o-py/h2o/expr.py
h2o-py/h2o/frame.py

* This PR fixes a bug when printing frames  via `head()` or `tail()` to a Jupyter notebook or a python console.
* Before the number of rows was hard coded to 10. So any call to `head` or `tail` would always print 10 rows if the `rows` argument was > 10. 
* Now these calls will print any specified number of rows that are applicable to the frame.

PUBDEV-4624: Allow to print the complete frame in python API

---

h2o-core/src/main/java/water/parser/FVecParseWriter.java
h2o-core/src/main/java/water/parser/ParseDataset.java
h2o-core/src/main/java/water/parser/ParseWriter.java
h2o-core/src/main/java/water/parser/ParserInfo.java
h2o-core/src/main/java/water/parser/PreviewParseWriter.java
h2o-parsers/h2o-orc-parser/src/main/java/water/parser/orc/OrcParser.java
h2o-parsers/h2o-orc-parser/src/main/java/water/parser/orc/OrcParserProvider.java
h2o-parsers/h2o-orc-parser/src/test/java/water/parser/ParseTestOrc.java
h2o-parsers/h2o-orc-parser/testMultiNode.sh
h2o-parsers/h2o-parquet-parser/build.gradle
h2o-parsers/h2o-parquet-parser/src/main/java/org/apache/parquet/hadoop/VecParquetReader.java
h2o-parsers/h2o-parquet-parser/src/test/java/water/parser/parquet/ParseTestParquet.java
h2o-parsers/h2o-parquet-parser/src/test/java/water/parser/parquet/VecDataInputStreamTest.java
h2o-parsers/h2o-parquet-parser/testMultiNode.sh
h2o-persist-hdfs/src/main/java/water/persist/VecDataInputStream.java
h2o-persist-hdfs/src/main/java/water/persist/VecFileSystem.java

Make ORC use VecFileSystem from Parquet parser implementation (refactored to h2o-persist-hdfs) instead of native hadoop file system.
Two benefits: 
a) consistency with the rest of h2o (data read via standard DKV mechanism)
b) DKV caching
VecFileSystem/VecInputStream refactored to h2o-persist-hdfs

Tomas/pubdev 4611 - Made Orc Parser use VecFilesystem

---

h2o-bindings/bin/gen_R.py
h2o-py/h2o/estimators/estimator_base.py
h2o-py/h2o/job.py
h2o-py/h2o/utils/progressbar.py
h2o-r/h2o-package/R/communication.R
h2o-r/h2o-package/R/deeplearning.R
h2o-r/h2o-package/R/gbm.R
h2o-r/h2o-package/R/models.R
h2o-r/h2o-package/R/randomforest.R
h2o-r/h2o-package/R/xgboost.R

* Add verbose option to display scoring histories as model job is running. 
* Will only apply to gbm, drf, xgboost, and deeplearning (iterative supervised algorithms)
* Examples output for R API:
* Example output for Py API:

PUBDEV-4446: See OUTPUT - SCORING HISTORY part in Flow in R and Python APIs

---

h2o-algos/src/main/java/hex/glrm/GLRM.java
h2o-algos/src/main/java/hex/pca/PCA.java
h2o-algos/src/main/java/hex/svd/SVD.java
h2o-r/tests/testdir_algos/pca/runit_pubdev_3502_pca_hangs_large_NOPASS.R
h2o-r/tests/testdir_algos/pca/runit_pubdev_3947_pca_slow_NOPASS_large.R

1. Fixed bugs in glrm.java when randomized is used as initialization method.
3. Only enable wide dataset method for PCA if the dataset is very wide.  Discovered that generating the gram matrix is much faster than outergram.
3. Added runit test to time the it takes to build pca models.

Pubdev 3947 pca slow

---

h2o-core/src/main/java/hex/PartialDependence.java

* This PR allows PDP to accept a `Job` as input, which can be fed progress from PDP. 
* This is useful when you have nested jobs.

PUBDEV-4687: Allow PDP to accept a Job as input

---

h2o-docs/src/product/data-munging/importing-data.rst
h2o-docs/src/product/data-munging/uploading-data.rst
h2o-docs/src/product/data-science/gbm-faq/scoring.rst
h2o-docs/src/product/getting-data-into-h2o.rst
h2o-docs/src/product/pojo-quick-start.rst
h2o-genmodel/src/main/java/overview.html

Added a note indicating that Hive files can be saved in ORC format and then imported.
Driveby fixes:
- Fixed link to Hive tutorials in the GBM FAQ
- Updated list of POJO and MOJO supported algorithms.

PUBDEV-4656: Documentation for Hive format

---

h2o-docs/src/product/flow.rst
h2o-docs/src/product/getting-data-into-h2o.rst

For topics that indicate we support Avro formatted data, indicate that only 1.8.0 is supported. This is in response to ticket 90937.

PUBDEV-4689: Document that only Avro version 1.8.0 is supported

---

h2o-docs/src/product/automl.rst
h2o-py/h2o/automl/autoh2o.py
h2o-r/h2o-package/R/automl.R

Removed stopping_tolerance default value of 0.001 in AutoML R and Python clients. https://0xdata.atlassian.net/browse/PUBDEV-4690

PUBDEV-4690: Removed default stopping_tolerance in AutoML R/Py

---

install-clients.sh
scripts/install-clients.sh

This is a utility script for H2O developers to use to simplify (re)installing the R and Python clients after running a `./gradlew build`.

PUBDEV-4604: Added script to install the clients after building H2O

---

h2o-docs/src/product/grid-search.rst

In the Grid Search topic, add the list of hyper parameters that AutoML searches over. This is in response to ticket 90933.
Note that this will be merged into master only and not into rel-vajda.

PUBDEV-4660: AutoML Hyperparameters

---

h2o-algos/src/main/java/hex/glm/ComputationState.java
h2o-algos/src/test/java/hex/glm/GLMTest.java
h2o-core/src/main/java/water/util/MathUtils.java

When running with weighted data and columns which are constant after applying weights, glm lambda search would hit aiiob.
The bug was in matrix caching - the matrix is cached for given active columns, but the zero columns were dropped without recording this fact in the matrix cache => next round computation picked up matrix from cache thinking it was full-size but in fact the zero columns were missing.
This is a temporary fix: record the correct active column set in matrix cache. Proper fix would be to remove the constant columns at the global level.

PUBDEV-4724 - glm aioob fix.

---

h2o-docs/src/product/faq/sparkling-water.rst

Updated the FAQ for saving and loading a model in SW.
Driveby fixes: Updated the version number of sparkling-water-core, which was pointing to an older version. Also updated the steps for creating a cloud inside of the Spark cluster. These steps now match the download page.

PUBDEV-4553: Doc updated for saving and loading a model in SW

---

h2o-docs/src/product/faq/sparkling-water.rst

Updated the FAQ for saving and loading a model in SW.
Driveby fixes: Updated the version number of sparkling-water-core, which was pointing to an older version. Also updated the steps for creating a cloud inside of the Spark cluster. These steps now match the download page.

PUBDEV-4553: Doc update for saving and loading a model in SW

---

h2o-py/h2o/estimators/estimator_base.py

* Add `xgboost` algo to Python grid search

PUBDEV-4653: Grid Search not working with the new H2OXGBoostEstimator() & PUBDEV-4704: h2o xgboost: grid in h2o python gives error

---

h2o-docs/src/product/cloud-integration/databricks.rst
h2o-docs/src/product/data-science/algo-params/categorical_encoding.rst
h2o-docs/src/product/howto/MOJO_QuickStart.md
h2o-docs/src/product/howto/POJO_QuickStart.md
h2o-docs/src/product/pojo-quick-start.rst
h2o-docs/src/product/productionizing.rst

In the POJO/MOJO topics, added a description of the h2o-genmodel.jar file.
Driveby fixes: Fixed a typo in Databricks topic. Added more clarification between enum and label_encoder in the categorical_encoding topic.

PUBDEV-4649: Doc clarification for h2o-genmodel.jar

---

h2o-algos/src/main/java/hex/tree/CompressedForest.java
h2o-algos/src/main/java/hex/tree/CompressedTree.java
h2o-algos/src/main/java/hex/tree/DTree.java
h2o-algos/src/main/java/hex/tree/DTreeScorer.java
h2o-algos/src/main/java/hex/tree/ReconstructTreeState.java
h2o-algos/src/main/java/hex/tree/SharedTree.java
h2o-algos/src/main/java/hex/tree/SharedTreeModel.java
h2o-algos/src/main/java/hex/tree/drf/TreeMeasuresCollector.java

This object can later store information shared among all Trees, for
now it just holds the keys of the trees

PUBDEV-4694: Make CompressedTree smaller by storing common metatada elsewhere

---

h2o-core/src/main/java/hex/grid/GridSearch.java

There also was a race condition, the model could get deleted between two DKV calls.

Fixes NPE in gridsearch when there are models in a "weird" state

---

h2o-docs/src/product/faq/general.rst

Fixed incorrect coding samples in the FAQ > General topic for the “How to score using a POJO” question.

PUBDEV-4632: Documentation fix for POJO FAQ

---

h2o-core/src/main/java/water/Job.java
h2o-core/src/main/java/water/parser/ParseWriter.java
h2o-parsers/h2o-parquet-parser/src/main/java/water/parser/parquet/ParquetParser.java
h2o-parsers/h2o-parquet-parser/src/main/java/water/parser/parquet/ParquetParserProvider.java
h2o-parsers/h2o-parquet-parser/src/test/java/water/parser/parquet/ParseTestParquet.java

This will solve PUBDEV-4683 (user overrides type of a Numeric column and forces it to be a String) - this will not be allowed anymore.
It will allow workaround for PUBDEV-4685 - user will be able to specify a String column instead of a Categorical column (unification on the categorical column causes issues).

PUBDEV-4683: Allows overriding a type of a Str/Cat column in a Parquet file

---

README.md
h2o-dist/index.html
h2o-docs/src/product/downloading.rst

- In the H2O-3 README, the list of required Python packages now points to a yaml file, which is a maintained file.
- Added a link to this yaml file in the Downloading and Installing section of the User Guide.
Driveby fix: Added 3.5 as a supported Python version on the download page.

PUBDEV-4522: Update list of required Python packages

---

h2o-docs/src/product/data-science/algo-params/stopping_rounds.rst
h2o-docs/src/product/data-science/algo-params/stopping_tolerance.rst
h2o-docs/src/product/data-science/xgboost.rst
h2o-docs/src/product/flow.rst

- Updated the XGBoost parameters to include default values.
- Compared H2O default values with XGBoost defaults. Created PUBDEV-4751, PUBDEV-4752, and PUBDEV-4573, which describe inconsistencies.
- Added aliases for options that can be used interachangeably. However, the aliases still have different default values. I will update those default values after the defaults are fixed in the code.
Driveby fixes: Updated the default values for stopping_rounds and stopping_tolerance in the Parameters appendix.

PUBDEV-4733: Document default values for XGBoost parameters

---

h2o-py/h2o/frame.py

Fixed missing newline when using default print in IPython. The hack with stacktrace examination was taken from the `__repr__` method of the same class.

[PUBDEV-4688] - added newline when printing H2OFrame in IPython

---

h2o-core/src/main/java/water/rapids/ast/prims/mungers/AstSetDomain.java
h2o-py/h2o/frame.py
h2o-r/h2o-package/R/frame.R
h2o-r/tests/testdir_misc/runit_revalue.R

Note: the fix is actually different for R and Python.
For Python: we treat this as a bug because implementation was not accordance with documentation.
For R: The documentation actually states this behavior and there might be users relying on it (calling h2o.setLevels(...) without using the return value). We therefore introduce a new flag that disables the in-place overwrite

PUBDEV-2767: Copy of factor column in R misses copy-on-write

---

build.gradle
gradle.properties
h2o-app/build.gradle
h2o-extensions/krbstandalone/build.gradle
h2o-extensions/krbstandalone/src/main/java/hex/security/KerberosExtension.java
h2o-extensions/krbstandalone/src/main/resources/META-INF/services/water.AbstractH2OExtension
settings.gradle

User needs to get Kerberos ticket (kinit) and then start H2O instance (Hadoop configuration xml needs to have kerberos enabled).

PUBDEV-4738: Enable access to Kerberized HDFS from standalone H2O

---

h2o-docs/src/product/data-science/deep-learning.rst
h2o-docs/src/product/data-science/drf.rst
h2o-docs/src/product/data-science/gbm.rst

Added the “verbose” option to list of parameters in GBM, DRF, and Deep Learning. Note that this was already added to XGBoost documentation.

PUBDEV-4773: Document new "verbose" option

---

h2o-parsers/h2o-parquet-parser/build.gradle

There were overlapping dependendencies:
- javax.servlet:servlet-api:2.5
- org.eclipse.jetty.orbit:javax.servlet:3.0.0.v201112011016

Fix test dependencies for the Parquet Parser

---

h2o-core/src/main/java/water/api/ParseSetupHandler.java
h2o-core/src/main/java/water/parser/CsvParser.java
h2o-core/src/main/java/water/parser/ParseDataset.java
h2o-core/src/main/java/water/parser/ParseSetup.java
h2o-core/src/main/java/water/parser/ParseWriter.java
h2o-core/src/main/java/water/util/ArrayUtils.java
h2o-core/src/test/java/water/parser/ParserTest.java
h2o-genmodel/src/main/java/hex/genmodel/utils/ParseUtils.java
h2o-parsers/h2o-orc-parser/src/main/java/water/parser/orc/OrcParserProvider.java
h2o-parsers/h2o-orc-parser/src/test/java/water/parser/ParseTestOrc.java
h2o-parsers/h2o-parquet-parser/src/main/java/water/parser/parquet/ParquetParserProvider.java

ORC parser can convert certain types (e.g. any type can be turned into BAD to be essentially ignored, String can be turned into CAT or time), other conversions will be refused and H2O will generate a warning.

[HEXDEV-694] Added more generic handling of type overrides to ORC.

---

h2o-docs/src/product/data-science/xgboost.rst

Removing the lambda_bias parameter from the XGBoost docs.
This should ONLY be merged if PUBDEV-4795 does not make it into 3.14.0.1.

PUBDEV-4799: Removing lambda_bias parameter

---

h2o-docs/src/product/productionizing.rst

- Updated the gitbook in the h2o-tutorials repo to include entries for both the POJO and MOJO examples.
- The productionizing.rst file now includes links for both of these examples.

PUBDEV-4804: Update links to Hive MOJO/POJO examples

---

h2o-docs/src/product/howto/MOJO_QuickStart.md
h2o-docs/src/product/howto/POJO_QuickStart.md
h2o-docs/src/product/productionizing.rst
h2o-genmodel/src/main/java/overview.html

- When compiling and running MOJOs/POJOs, separated out commands between Linux/OS X and Windows because the separate is different (“:” vs “;”)
- Replaced "RACE" with "CAPSULE" for the asfactor column in R examples
- Fixed the R download_mojo function example
- Changed “=“ to “<-“ in R examples

PUBDEV-4811: Updates to MOJO/POJO docs

---

h2o-algos/src/main/java/hex/schemas/GLMV3.java
h2o-docs/src/product/data-science/glm.rst
h2o-py/h2o/estimators/glm.py
h2o-r/h2o-package/R/glm.R

- Added info describing the value of “lambda_max” in the User Guide.
- Update the help string in the GLMV3.java file to include this information.
- Built H2O locally, and the glm.py and glm.R files auto updated. Tested locally that this change shows up in the R docs.

PUBDEV-4816: Clarify GLM's lambda_max value

---

h2o-docs/src/booklets/v2_2015/source/GBMBooklet.tex
h2o-docs/src/product/data-science/drf.rst
h2o-docs/src/product/faq/java.rst
h2o-docs/src/product/starting-h2o.rst
h2o-docs/src/product/welcome.rst

Changed, “since the columns are grouped together…” to “since the factor levels get grouped together…”
Successfully built booklets locally.
Driveby fixes: Minor update in DRF (adding a Flow button name). Fixed link in FAQ > Java. Updated headings in starting-h2o. Updated link to SW example in the Welcome section.

PUBDEV-4810: Clarifications in GBM booklet

---

h2o-algos/src/main/java/hex/StackedEnsembleModel.java
h2o-algos/src/main/java/hex/schemas/DRFV3.java
h2o-algos/src/test/java/hex/ensemble/CheckSumTest.java
h2o-py/h2o/estimators/random_forest.py
h2o-py/tests/testdir_algos/stackedensemble/pyunit_stackedensemble_base_model_training_frame.py
h2o-r/h2o-package/R/randomforest.R
h2o-r/tests/testdir_algos/stackedensemble/runit_stackedensemble_base_model_training_frame.R

* This PR does the following changes to Stacked Ensembles:
1. Avoids passing fold column to stacked ensembles. Not needed.
2. Avoids a check for ignored columns in stacked ensembles. Not needed. Only need this from the first base model to compare to others.
3. No need to check `checksums` of training frames since the number of rows only need to match and the column length can vary.
4. No need to check `domains` of a frame because of point `3` above (training frames can vary)
5. Adds minor comments to the code.
6. Adds a test for check sum consistency in Stacked Ensembles. 
7. This PR also adds the `distribution` argument to random forest, which was found to be missing during these changes.

Changes to Stacked Ensembles

---

h2o-r/tests/testdir_algos/stackedensemble/runit_stackedensemble_base_model_training_frame.R

This fixes a bug where we were including an extra copy of the response column as one of the predictors.

PUBDEV-4820: Fixed bug in stacked ensemble runit

---

h2o-docs/src/front/index.html

- Added links for the Sparkling Water 2.2 release, including links to github repos and scaladocs.
Driveby fix: Added a link to XGBoost documentation under supervised
algorithms.
Tested site in three browsers.

PUBDEV-4729-sw22-release

---

h2o-algos/src/main/java/hex/ensemble/StackedEnsemble.java

* The `prepareValidationLevelOneFrame` method needs to remove the `predict` column in a multinomial case.

HOTFIX: Ensure validation frame is updated in multinomial case for stacked ensembles

---

h2o-core/src/main/java/water/rapids/ast/prims/string/AstReplaceFirst.java
h2o-r/tests/testdir_jira/runit_pubdev_4739.R

There was a missing arg when creating new Frame. I have also added a simple test.

[PUBDEV-4739] - h2o.sub now retains column names

---

h2o-core/src/main/java/water/rapids/ast/prims/string/AstReplaceFirst.java
h2o-r/tests/testdir_jira/runit_pubdev_4739.R

[PUBDEV-4739] 
- h2o.sub now retains column names
- simple test of this behavior

[PUBDEV-4739] - h2o.sub now retains column names (#1444)

---

h2o-algos/src/main/java/hex/StackedEnsembleModel.java
h2o-algos/src/main/java/hex/ensemble/StackedEnsemble.java
h2o-algos/src/main/java/hex/schemas/StackedEnsembleModelV99.java
h2o-algos/src/main/java/hex/schemas/StackedEnsembleV99.java
h2o-algos/src/test/java/hex/ensemble/StackedEnsembleTest.java
h2o-py/h2o/estimators/stackedensemble.py
h2o-py/h2o/model/model_base.py
h2o-py/tests/testdir_algos/stackedensemble/pyunit_stackedensemble_levelone_frame.py
h2o-r/h2o-package/R/stackedensemble.R
h2o-r/tests/testdir_algos/stackedensemble/runit_stackedensemble_levelone_frame.R

* Add a `keep_levelone_frame` argument to Stacked Ensembles. If set to `true`, then the stacked ensemble object has an attribute `level_one_frame_id` and a user can fetch said frame. 
* Added pyunit and runit to test previous.

PUBDEV-4836: Add a `keep_levelone_frame` argument to Stacked Ensembles

---

h2o-hadoop/h2o-mapreduce-generic/src/main/java/water/JettyProxy.java

Fix the way proxy propagates auth headers to H2O Node (avoid duplicates)

---

h2o-algos/src/main/java/hex/glm/GLMModel.java
h2o-algos/src/test/java/hex/glm/GLMTest.java

Wrong handling of missing (replaced by NAs) response, inconsistent counting => AIIOB.
Fixed by removing all NA response prior to GLM scoring, updated test.

PUBDEV-4868 - glm scoring fix 

---

h2o-r/h2o-package/R/communication.R

* `verbose` mode for tree/dl models in R api seems to cause a 404 error when `nfolds` >=2, which is most likely due to the polling happening before the server is ready.
* The solution is to wrap the calls in a `tryCatch()`, which is what is done in the Python API.
https://0xdata.atlassian.net/browse/PUBDEV-4885

PUBDEV-4885: Verbose option for models fails when nfolds >=2

---

h2o-docs/src/product/data-science/algo-params/calibrate_frame.rst
h2o-docs/src/product/data-science/algo-params/y.rst
h2o-docs/src/product/data-science/drf.rst
h2o-docs/src/product/data-science/gbm-faq/missing_values.rst
h2o-docs/src/product/data-science/stacked-ensembles.rst
h2o-docs/src/product/flow.rst

- Added the `keep_levelone_frame` option to the Stacked Ensembles and Flow sections in the User Guide.
Driveby fixes:
- Added `y` to list of options in Stacked Ensembles. (This was missing.)
- Added a note in DRF regarding handling of numeric and categorical missing values.
- In the `calibrate_frame` parameter example, moved the weights column to the model training. It was being ignored in the config. Also updated the predicted output.

PUBDEV-4881: Doc update in Stacked Ensembles

---

h2o-core/src/main/java/water/H2O.java
h2o-core/src/main/java/water/parser/DecryptionTool.java
h2o-core/src/main/java/water/parser/GenericDecryptionTool.java
h2o-core/src/main/java/water/parser/NullDecryptionTool.java
h2o-core/src/main/java/water/parser/ParseDataset.java
h2o-core/src/main/java/water/parser/ParseSetup.java
h2o-core/src/main/java/water/parser/ParserInfo.java
h2o-core/src/main/java/water/parser/ZipUtil.java
h2o-core/src/test/java/water/parser/ParseTestEncrypted.java

This PR lays the ground work for ingesting encrypted datasets into H2O. Implemented is infrastructure that enables parsing encrypted data using Java API.
This can be further extended and full client API can be added.
Decryption can be used on dataset level (for a particular ParseSetup) or globally.
ParseSetup-level is demonstrated in a unit test.
Global level can be configured by specifying option -decrypt_tool <your desired key> and installing the tool in DKV after H2O starts up.

PUBDEV-4845: Adds support for on-the-fly decryption to ParseDataset

---

h2o-py/h2o/backend/server.py

I have changed the server wait time out to 60  (original 10) seconds to match with R timeout.

[PUBDEV-4849] updated server wait time out to 60 seconds

---

h2o-r/tests/testdir_docexamples/runit_Rdoc_anomaly.R

Added tryCatch to runit_Rdoc_anomaly.R to catch the error throw by deeplearning when an unstable model is built.

Fixed intermittent failure of runit_Rdoc_anomaly.R

---

h2o-py/h2o/h2o.py

Before this PR when `h2o.init(ip = "172.16.2.0", strict_version_check=False)` is invoked and there is an issue connecting to H2O server on given IP, local H2O is launched, which is not desired. Modification in this PR throws an exception instead.

[PUBDEV-4871] When using h2o.init() do not fallback to starting local H2O server

---

h2o-docs/src/product/howto/MOJO_QuickStart.md
h2o-docs/src/product/howto/POJO_QuickStart.md
h2o-docs/src/product/productionizing.rst
h2o-genmodel/src/main/java/overview.html

Updated Javadoc, User Guide, and markdown files to include Deep Learning in list of MOJO-supported algorithms.
Driveby fix: Updated syntax in POJO quick start.

PUBDEV-4912: Document MOJO support for Deep Learning

---

gradle/timing.gradle

Inspired by the same stackoverflow thread as the original code
https://stackoverflow.com/questions/13031538/track-execution-time-per-task-in-gradle-script
Without this, the composite build fails with Sparkling Water.

[PUBDEV-4921] Replace deprecated Clock class in timing.gradle

---

build.gradle
h2o-py/build.gradle
h2o-web/build.gradle

In some environment build fails on using wrong python version.
This patch allows users to override default names for Python and Pip.

[PUBDEV-4249] Allow users to override default Python binary

---

h2o-core/src/main/java/water/api/schemas3/ModelParametersSchemaV3.java
h2o-py/h2o/estimators/deeplearning.py
h2o-py/h2o/estimators/deepwater.py
h2o-py/h2o/estimators/gbm.py
h2o-py/h2o/estimators/glm.py
h2o-py/h2o/estimators/random_forest.py
h2o-py/h2o/estimators/xgboost.py
h2o-r/h2o-package/R/deeplearning.R
h2o-r/h2o-package/R/deepwater.R
h2o-r/h2o-package/R/gbm.R
h2o-r/h2o-package/R/glm.R
h2o-r/h2o-package/R/randomforest.R
h2o-r/h2o-package/R/xgboost.R

Added more text to the description of the weights_column parameter to match what exists in the user guide. This is in response to support ticket 91136.

PUBDEV-4889: Updated description of weights_column

---

h2o-py/tests/testdir_munging/pyunit_pubdev_4870_sort_bug.py

Test took 1850s to complete.  Sorry.  Let's reduce the number of elements compared here.

Reduce pyunit_pubdev_4870_sort_bug.py run time.

---

h2o-dist/index.html
h2o-docs/src/product/downloading.rst

- On the download site for R, removed “statmod” from list of packages to download.
- Update the User Guide “Installing in R” topic to match the download site.

PUBDEV-4949: Download packages required for R

---

h2o-core/src/main/java/water/exceptions/H2OUnsupportedDataFileException.java
h2o-core/src/main/java/water/parser/BinaryParserProvider.java
h2o-core/src/main/java/water/parser/DefaultParserProviders.java
h2o-core/src/main/java/water/parser/ParseSetup.java
h2o-core/src/main/java/water/parser/Parser.java
h2o-core/src/main/java/water/parser/ParserProvider.java
h2o-core/src/test/java/water/parser/ParserTest2.java
h2o-parsers/h2o-parquet-parser/src/main/java/org/apache/parquet/hadoop/VecParquetReader.java
h2o-parsers/h2o-parquet-parser/src/main/java/water/parser/parquet/ParquetParser.java
h2o-parsers/h2o-parquet-parser/src/main/java/water/parser/parquet/ParquetParserProvider.java

This PR introduces splits "guess setup" into 2 steps:
1. Determine if a given parser provider can generate a parser for given data based on file's metadata only. Binary parsers can determine file type without any doubt.
2. Finalize the parser setup using data read from the file (eg. guess what is an enumerated value).
The idea is that if step 1 determines the format then a failure in step 2 is reported to the user instead of just trying a next available parser.
This is currently implemented for Parquet Parser.

PUBDEV-4954: If parser fails to parse a valid Parquet file it is parsed a CSV instead

---

h2o-docs/src/product/data-science/word2vec.rst

In response to a stack overflow question, added a note stating that the H2O-3 version is not compatible with other versions written in C++. Also noted that importing models in binary format is not supported.

PUBDEV-4945: Word2vec clarification in docs

---

h2o-py/docs/intro.rst

Just got rid of a small typo in the python docs.

remove typo from intro.rst

---

h2o-r/tests/testdir_golden/runit_km2_4_golden_large.R

runit_km2_4_golden.R tests have been failing intermittently with memory issues.  Fixed bug in the bracket position.

PUBDEV-4837: fixed runit_km2_4_golden.R test.  Wrong bracket position.

---

h2o-genmodel/src/main/java/hex/genmodel/easy/EasyPredictModelWrapper.java

* No reason for ` preamble(), predict(), and fillRawData()` to be private fields. Can just be protected.

PUBDEV-4963: Make preamble(), predict(), and fillRawData() protected in EasyPredictModelWrapper

---

h2o-py/h2o/astfun.py
h2o-py/h2o/frame.py
h2o-py/tests/testdir_jira/pyunit_pubdev_4672.py
h2o-py/tests/testdir_jira/pyunit_pubdev_4673.py
h2o-py/tests/testdir_misc/pyunit_apply.py
h2o-py/tests/testdir_munging/pyunit_count_temps.py

This change correctly parse Python3+ bytecode using
utilities from the dis package. The missing functionality in Python2 is
reimplemented following Python3+ code.
---
TODO:

[PUBDEV-4684] Support of Python 3.6

---

h2o-docs/src/product/faq/java.rst
h2o-docs/src/product/welcome.rst

- Added an entry in FAQ > Java describing how to switch to a supported Java version. This is specifically for Java 9 users.
- Updated the Welcome > Requirements topic to indicate that Java 9 is out, but it’s not supported in H2O.

PUBDEV-4966: FAQ for switching to a supported Java version

---

h2o-docs/src/product/security.rst

Added a small section detailing the steps to make LDAP Authentication work on MapR.

HEXDEV-697: LDAP Authentication on MapR

---

h2o-core/src/main/java/water/rapids/ast/prims/reducers/AstAll.java
h2o-core/src/main/java/water/rapids/ast/prims/reducers/AstAny.java
h2o-genmodel/src/main/java/hex/genmodel/utils/ArrayUtils.java
h2o-py/h2o/frame.py
h2o-py/tests/testdir_jira/pyunit_pubdev_4987_any_all.py

* PUBDEV-4987: fix any(), all().  Added check to make sure we are dealing with boolean columns.  Next added code to count the number of true elements instead of just counting number of non-zeros.
PUBDEV-4987: fix all, any.  Added pyunit test to verify the fix.
* PUBDEV-4987 fix all, any.  Numerical columns are generated if clients check the condition of a column.

PUBDEV-4987: fix any(), all().  (#1616)

---

scripts/validate_r_cmd_check_output.R
scripts/validate_r_cmd_check_output.py

Ignoring additional R CMD check notes regarding size of tarball and large version components. R 3.4 and possibly R 3.3 complains about them.

[PUBDEV-4989] Ignoring additional R CMD check notes

---

docker/Makefile.jenkins

It's not used and it's not working.

[ITA-36] Removed docker build target from docker/Makefile.jenkins

---

h2o-core/src/main/java/water/Paxos.java
h2o-core/src/test/java/water/ClientJarMD5IgnoreTest.java

this PR fixes this PR https://0xdata.atlassian.net/browse/PUBDEV-4964 . In the original one the jar check is checked inside the condition and therefore this change does not have any effect.
Also wrote test for this behaviour.

[PUBDEV-4988] Don't check H2O client hash-code ( Fix )

---

h2o-dist/index.html
h2o-docs/src/product/welcome.rst

- Changed the “3.5+” to “3.5.x” on the Download site for supported python versions.
- Updated the welcome.rst file to indicate that Python 3.6 is not yet supported.

PUBDEV-4996: Note that Python 3.6 is not yet supported

---

h2o-dist/index.html
h2o-docs/src/product/downloading.rst
h2o-docs/src/product/welcome.rst

- The welcome and downloading topics now state support for Python 3.6. This also includes support for the Conda 3.6 repo.
- Updated the Download site to show support for Python 3.6.x

PUBDEV-4931: Updated documentation to show support for Python 3.6

---

gradle/s3sync.gradle

Gradle script contained a bug, which occurred when no positive (smalldata) item was on the truncated list of test datasets. It failed to update [lastKey](https://github.com/h2oai/h2o-3/blob/d869cad60fa165fb1c918d405252083c6344330d/gradle/s3sync.gradle#L71) leading in an infinite loop...

syncSmalldata pagination bug

---

h2o-bindings/bin/gen_python.py
h2o-py/h2o/estimators/estimator_base.py
h2o-py/tests/testdir_algos/aggregator/pyunit_cat_encoding.py
h2o-py/tests/testdir_algos/aggregator/pyunit_num_exemplars.py
h2o-py/tests/testdir_algos/aggregator/pyunit_parameters.py
h2o-py/tests/testdir_jira/pyunit_pubdev_4995.py

Well obviously Aggregator uses schema v99 now, so fixed it manually to that version for now.
Maybe we could parse the schema version from REST and include it in bindings.
Also added simple test, which may be more sophisticated, like comparing rest_version used in python API to the one received from server..

Pubdev 4995

---

h2o-bindings/bin/gen_python.py
h2o-py/h2o/estimators/aggregator.py
h2o-py/tests/testdir_algos/aggregator/pyunit_cat_encoding.py
h2o-py/tests/testdir_algos/aggregator/pyunit_num_exemplars.py

The `H2OAggregatorEstimator` is missing a reference to aggregated frame, so I propose to add it as a readonly property of the model, which returns `None` before training

PUBDEV-4995: Aggregator python api output_frame

---

h2o-docs/src/product/data-science/algo-params/categorical_encoding.rst
h2o-docs/src/product/data-science/deep-learning.rst
h2o-docs/src/product/data-science/drf.rst
h2o-docs/src/product/data-science/gbm.rst
h2o-docs/src/product/data-science/k-means.rst
h2o-docs/src/product/data-science/xgboost.rst

- categorical_encoding=sort_by_response is only valid for supervised learning models. I removed this from the list of options that can be specified in Aggregator.
- Created a separate K-Means section rather than bundling with GBM/DRF. K-Means is unsupervised, so sort_by_response is not supported.
- Noted (for other algorithms) that a response column must be specified
when using this option.

PUBDEV-5011: remove sort by response from Aggregator options

---

h2o-core/src/main/java/hex/ScoreKeeper.java
h2o-py/tests/testdir_misc/pyunit_pubdev_4697_early_stop_gbm.py

Fixed bug in backend to return true when a metric hits zero (which is the smallest it can get), the early_stop should return true since we can no longer improve on it.

Pubdev 4697 early stop

---

h2o-core/src/main/java/water/fvec/Frame.java
h2o-core/src/main/java/water/rapids/RadixCount.java
h2o-core/src/main/java/water/rapids/ast/prims/mungers/AstMerge.java
h2o-core/src/test/java/water/rapids/RapidsTest.java
h2o-py/h2o/frame.py
h2o-py/tests/pyunit_utils/utilsPY.py
h2o-py/tests/testdir_jira/pyunit_PUBDEV_3567_merge_stall_large.py
h2o-r/h2o-package/R/frame.R
h2o-r/tests/runitUtils/utilsR.R
h2o-r/tests/testdir_jira/runit_PUBDEV_3567_merge_stall_large.R
h2o-r/tests/testdir_misc/runit_mergecat.R
h2o-r/tests/testdir_munging/runit_merge.R
scripts/gen_numerical_data.py

PUBDEV-3567: merge.  Change default method auto to either choose radix or hash depending on the contents of the left and right frame.  If there are no string columns in the frames, radix merge will be chosen.  If there are string columns in the right frame, hash merge will be chosen. Thanks to Michal K for the suggestion.
PUBDEV-3567: merge.  Added code to support left join or right join is set to true but not both.
PUBDEV-3567: Added pyunit and runit tests.
PUBDEV-3567: correct runit tests to choose method=hash since it is no longer the default

PUBDEV_3567: merge.  

---

h2o-docs/src/front/index.html
h2o-docs/src/product/getting-data-into-h2o.rst

- Updated the links for the new SW links on docs.h2o.ai.
Driveby fix: Noted in the docs that gzipped files are supported.

PUBDEV-5026: Updated SW links on docs.h2o.ai

---

h2o-docs/src/product/grid-search.rst

- Added an introduction
- Added a linkable index to the different sections of the page
- Added better code examples in R and Python
- Added more info about `search_criteria`
- Moved list of griddable parameters to the bottom
- Shuffled some other sections around

PUBDEV-5016: Major reorg & updates to Grid Search user guide page

---

h2o-algos/src/main/java/hex/StackedEnsembleModel.java
h2o-automl/src/main/java/ai/h2o/automl/AutoML.java
h2o-docs/src/product/automl.rst
h2o-py/tests/testdir_algos/automl/multinomial/pyunit_automl_iris.py
h2o-r/tests/testdir_algos/automl/runit_automl_multinomial.R

- Removing Java code that skips Stacked Ensemble for multinomial
- Fixed a Java bug with Stacked Ensemble for multinomial
- runit & pyunit to check that a Stacked Ensemble is included in the leaderboard for multinomial
- Updated AutoML user guide to indicate that we now do Stacked Ensembles for multinomial

PUBDEV-4957: Allow multiclass stacking in AutoML now that we support it

---

h2o-py/tests/testdir_jira/pyunit_PUBDEV_3567_merge_stall_large.py

Reduce runtime by reducing number of elements to check in frame compare.

Reduce merge_stall runtime in python.

---

h2o-core/src/main/java/water/api/LogsHandler.java

This change unblocks obtaining http logs. They are special kind of logs which are available independently on whatever the current log level is set to.
Before `Log.isLoggingFor(name)` was called with `httpd` as the argument and it always return `false`. We need to handle this as different situation and don't ask if logging is enabled for httpd.

[PUBDEV-5040] HTTP logs can't be obtained in Flow UI

---

h2o-algos/src/main/java/hex/ensemble/StackedEnsemble.java
h2o-py/tests/testdir_algos/stackedensemble/pyunit_stackedensemble_validation_frame.py
h2o-r/tests/testdir_algos/stackedensemble/runit_stackedensemble_validation_frame.R

* Now that we are piping the `validation_frame` through to the GLM metalearner in the Stacked Ensemble algo, we should enable lambda search so that we can make use of this `validation_frame` to get a better GLM fit.
* Since we are also using `non_negative = TRUE`, we should set `early_stopping = false`.
* Also updated unit tests to reflect previous changes.

PUBDEV-4791: Enable lambda search for the GLM metalearner in Stacked Ensemble

---

h2o-automl/src/main/java/ai/h2o/automl/AutoML.java
h2o-automl/src/main/java/ai/h2o/automl/AutoMLBuildSpec.java
h2o-automl/src/main/java/water/automl/api/schemas3/AutoMLBuildSpecV99.java
h2o-docs/src/product/automl.rst
h2o-docs/src/product/cross-validation.rst
h2o-docs/src/product/data-science/algo-params/nfolds.rst
h2o-py/h2o/automl/autoh2o.py
h2o-py/tests/testdir_algos/automl/pyunit_automl_args.py
h2o-r/h2o-package/R/automl.R
h2o-r/tests/testdir_algos/automl/runit_automl_args.R

We now expose the `nfolds` argument field to the user in AutoML.  Changes were made to AutoML Java backend and R and Py clients and docs.
- Added `nfolds` to R and Python AutoML interface with a default value of 5 (not auto-generated).
- Added runit and pyunit to test for `nfolds >=2` and `nfolds = 0`
- Added client-side checking for the `nfolds = 1` case with nice error messages.
- Added `nfolds` to AutoML user guide docs & made some other updates to cross-validation and nfolds user guid pages.

PUBDEV-4882: Expose nfolds argument in the AutoML R/Py clients

---

h2o-docs/src/product/faq/general.rst
h2o-docs/src/product/flow.rst
h2o-docs/src/product/getting-data-into-h2o.rst
h2o-docs/src/product/productionizing.rst
h2o-docs/src/product/save-and-load-model.rst

Added a note to the “Saving and Loading a Model” and “Faq > General” sections describing that models saved in Python, R, or Flow using one version of h2o cannot be loaded in another version. A workaround is to use POJO/MOJO.
Driveby fix: Noted in the “Getting Data into H2O” section that this refers to getting data into your h2o cluster (as opposed to an H2O.ai cloud).

PUBDEV-5056: Binary models not compatible across h2o versions

---

h2o-docs/src/product/data-science/drf.rst
h2o-docs/src/product/data-science/gbm-faq/splitting.rst

Splitting criterion in GBM and DRF trees is identical, but this info was only included in GBM. Added the same FAQs to the DRF section (editing also name when necessary).

PUBDEV-5062: Splitting in DRF is same as GBM

---

h2o-docs/src/product/automl.rst
h2o-docs/src/product/data-science/algo-params/ignored_columns.rst
h2o-docs/src/product/data-science/algo-params/k.rst
h2o-docs/src/product/data-science/algo-params/transform.rst
h2o-docs/src/product/data-science/algo-params/x.rst
h2o-docs/src/product/data-science/deep-learning.rst
h2o-docs/src/product/data-science/drf.rst
h2o-docs/src/product/data-science/gbm.rst
h2o-docs/src/product/data-science/glm.rst
h2o-docs/src/product/data-science/glrm.rst
h2o-docs/src/product/data-science/k-means.rst
h2o-docs/src/product/data-science/naive-bayes.rst
h2o-docs/src/product/data-science/pca.rst
h2o-docs/src/product/data-science/stacked-ensembles.rst
h2o-docs/src/product/data-science/xgboost.rst
h2o-docs/src/product/parameters.rst

- Added x parameter to AutoML section and to the “Defining a Model” section for each algorithm (where it had not been previously documented).
- Added ignored_columns parameter to AutoML section, noting that it is Python only
Driveby fixes: For all algos that use ignored_columns, noted that this parameter is only available in Python and Flow. Also added links to parameters appendix in the GLRM section.

PUBDEV-5057: `x` parameter missing from documentation

---

h2o-bindings/bin/gen_R.py
h2o-core/src/main/java/water/api/schemas3/ModelParametersSchemaV3.java
h2o-py/h2o/estimators/aggregator.py
h2o-py/h2o/estimators/deeplearning.py
h2o-py/h2o/estimators/deepwater.py
h2o-py/h2o/estimators/gbm.py
h2o-py/h2o/estimators/glm.py
h2o-py/h2o/estimators/glrm.py
h2o-py/h2o/estimators/kmeans.py
h2o-py/h2o/estimators/naive_bayes.py
h2o-py/h2o/estimators/pca.py
h2o-py/h2o/estimators/random_forest.py
h2o-py/h2o/estimators/stackedensemble.py
h2o-py/h2o/estimators/svd.py
h2o-py/h2o/estimators/word2vec.py
h2o-py/h2o/estimators/xgboost.py
h2o-r/h2o-package/R/aggregator.R
h2o-r/h2o-package/R/deeplearning.R
h2o-r/h2o-package/R/deepwater.R
h2o-r/h2o-package/R/gbm.R
h2o-r/h2o-package/R/glm.R
h2o-r/h2o-package/R/glrm.R
h2o-r/h2o-package/R/kmeans.R
h2o-r/h2o-package/R/naivebayes.R
h2o-r/h2o-package/R/pca.R
h2o-r/h2o-package/R/randomforest.R
h2o-r/h2o-package/R/stackedensemble.R
h2o-r/h2o-package/R/svd.R
h2o-r/h2o-package/R/word2vec.R
h2o-r/h2o-package/R/xgboost.R

- `training_frame` description says that it's optional.  
- The PR includes some other parameter description cleanup of `x` and `y` as well.

PUBDEV-4172: Correct training_frame description in R

---

h2o-core/src/main/java/water/Paxos.java

This just ensures that we report that client with wrong md5 was connected just in case the md5 doesn't match. Previously it was reporting `client_wrong_md5` to `ListenerService` for each client. Currently it's not affecting anything as this is used just in tests, but this change makes it semantically more correct

[PUBDEV-5067] Wrong reporting of client with wrong md5

---

h2o-algos/src/main/java/hex/glm/GLM.java
h2o-r/tests/testdir_jira/runit_pubdev_5029.R

For the multinomial case we need to consider the total of active
predictors for all classes to pick the correct solver (instead of maximum of the classes).
If total number of active predictors for the first lambda is > 5000
and solver L_BFGS was not auto-selected we will cap the number
of predictors to 5000. This will cause the algorithm to crash for the
next lambda because the number of active predictors is already > 5000
and this will violate the invariant #active < #max.

PUBDEV-5029: GLM crashes whem there are too many active predictors

---

docker/Makefile.jenkins
scripts/jenkins/groovy/executeTestStages.groovy

Use `sed` to modify test*Node.sh files so after a test failure we print only last 400 lines from the logs. The rest of the logs is still accessible from artifacts.

[ITA-118] Fix huge logs in case of JUnit failure

---

h2o-algos/src/main/java/hex/schemas/GLMV3.java
h2o-py/h2o/estimators/glm.py
h2o-r/README.md
h2o-r/h2o-package/R/glm.R

In GLM, the default value for max_active_predictors when solver=IRLSM is now 5000 instead of 7000. Updated the Python and R strings to reflect this change.

PUBDEV-5070: Update R and Python strings for max_active_predictors

---

h2o-docs/src/product/data-science/algo-params/early_stopping.rst
h2o-docs/src/product/data-science/algo-params/max_active_predictors.rst
h2o-docs/src/product/data-science/algo-params/max_runtime_secs.rst
h2o-docs/src/product/data-science/algo-params/score_each_iteration.rst
h2o-docs/src/product/data-science/algo-params/score_tree_interval.rst
h2o-docs/src/product/data-science/algo-params/stopping_metric.rst
h2o-docs/src/product/data-science/algo-params/stopping_rounds.rst
h2o-docs/src/product/data-science/algo-params/stopping_tolerance.rst
h2o-docs/src/product/data-science/common.rst

Added a section in the Algorithms > Common topic (common.rst) describing how users can specify early stopping for models built with supervised learning algorithms (which varies based on the algorithm).
Driveby fix: Set up anchors and use a reference tag to link to the relevant Parameters sections. This is better than using HTML links because they are usable in both the rst file (if a user is in github) and in the html output.

PUBDEV-4895: Documentation for early stopping

---

h2o-algos/src/main/java/hex/StackedEnsembleModel.java
h2o-algos/src/main/java/hex/ensemble/StackedEnsemble.java
h2o-algos/src/main/java/hex/schemas/StackedEnsembleV99.java
h2o-algos/src/test/java/hex/ensemble/StackedEnsembleTest.java
h2o-py/h2o/estimators/stackedensemble.py
h2o-py/tests/testdir_algos/stackedensemble/pyunit_stackedensemble_metalearner.py
h2o-r/h2o-package/R/stackedensemble.R
h2o-r/tests/testdir_algos/stackedensemble/runit_stackedensemble_metalearner.R

* Currently the metalearner is hardcoded as a default H2O GLM with non-negative weights. (`non_negative = TRUE`)
* We need to add a `metalearner_algorithm` argument to allow customization of the metalearning algorithm.
Initially, this argument will take in either "glm" (default), "gbm", "drf", or "deeplearning".
* A user cannot specify the metalearner model hyperparameters at this point. This will be completed with the addition of another argument, e.g. `metalearner_params`
* junit, runit, pyunit for this argument is included

PUBDEV-3743: StackedEnsemble should allow user to pass in metalearner type

---

h2o-automl/src/main/java/ai/h2o/automl/AutoML.java
h2o-docs/src/product/automl.rst
h2o-py/tests/testdir_algos/automl/pyunit_automl_args.py
h2o-r/tests/testdir_algos/automl/runit_automl_args.R

* Grab the "top" model from each algorithm class to create a lean Stacked Ensemble, at the end of the AutoML process. 
* Right now we only train a single ensemble that contains all the models, but we should add a few more ensembles for variety.

PUBDEV-4891: Add another Stacked Ensemble (top model for each algo) to AutoML

---

h2o-algos/src/main/java/hex/pca/PCA.java
h2o-core/src/main/java/water/rapids/ast/prims/mungers/AstGroup.java
h2o-core/src/test/java/water/rapids/GroupByTest.java
h2o-core/src/test/java/water/rapids/ZGroupByMedianTest.java
h2o-py/h2o/group_by.py
h2o-py/tests/testdir_apis/Data_Manipulation/pyunit_h2oH2OFrame_categories.py
h2o-py/tests/testdir_apis/Data_Manipulation/pyunit_h2oH2OFrame_max_mean_median_min_large.py
h2o-py/tests/testdir_apis/Data_Manipulation/pyunit_h2oH2OFrame_sum.py
h2o-py/tests/testdir_munging/pyunit_pubdev_4727_groupby_median_large.py
h2o-r/tests/testdir_misc/runit_pubdev_4727_groupby_median_large.R

PUBDEV-4727: groupby median.  Added client support for groupby median in Python.  Added backend code to AstGroup.java to support median operation.
PUBDEV-4727: groupby median.  Added pyunit and runit tests.
PUBDEV-4727: groupby median.  Fixed use of pyunit_utils.equal_two_arrays.
PUBDEV-4727: h2o groupby median.  Finished junit test.

PUBDEV-4727: GroupBy Median.  Added pyunit and runit tests.

---

h2o-py/tests/pyunit_utils/utilsPY.py
h2o-py/tests/testdir_algos/gbm/pyunit_PUBDEV_4090_grid_model_seeds.py

Fix this intermittent failure by comparing the training_rmse of first iteration only.  Gridsearch with stopping criteria max_runtime_secs may produce models built with different number of iterations due to timing differences between the various threads.

Fix pyunit_PUBDEV_4090_grid_model_seeds.py

---

h2o-docs/src/product/automl.rst

In the Grid Search section, removed the AutoML hyper parameters from the list. This section should just be about grid searches contained within the AutoML run.

remove automl hyperparameters

---

h2o-algos/src/main/java/hex/StackedEnsembleModel.java
h2o-algos/src/main/java/hex/ensemble/StackedEnsemble.java
h2o-algos/src/main/java/hex/schemas/StackedEnsembleV99.java
h2o-docs/src/product/data-science/stacked-ensembles.rst
h2o-py/h2o/estimators/stackedensemble.py
h2o-py/tests/testdir_algos/stackedensemble/pyunit_stackedensemble_nfolds.py
h2o-r/h2o-package/R/stackedensemble.R
h2o-r/tests/testdir_algos/stackedensemble/runit_stackedensemble_nfolds.R

- Adds `metalearner_fold_column` to Stacked Ensemble (defaults to `NULL`)
- If user specifies `nfolds` and `metalearner_fold_column`, the user will receive an error
- If `metalearner_fold_column` is specified, then it's also added to the Level One frame.
- Includes runit, pyunit
- Added parameter to Stacked Ensemble user guide

PUBDEV-5084: Added metalearner_fold_column arg to Stacked Ensemble

---

h2o-automl/src/main/java/ai/h2o/automl/AutoML.java
h2o-py/tests/testdir_algos/automl/pyunit_automl_args.py
h2o-r/tests/testdir_algos/automl/runit_automl_args.R

- Now that we support `metalearner_fold_column` in Stacked Ensemble, we can pipe the AutoML `fold_column` all the way through to Stacked Ensemble (instead of just the base learners). 
- Added a UserFeedback log message to warn user if `fold_column` is set, that `nfolds` value will be ignored.
- Added a check to make sure the user does not try to also specify a non-default `nfolds` value at the same time as `fold_column`.  Will return an error if they do.

PUBDEV-5095: Pipe AutoML fold_column through to Stacked Ensemble

---

h2o-algos/src/main/java/hex/ensemble/StackedEnsembleMojoWriter.java

Changed Mojo version of StackedEnsemble from 1.0 to 1.00.

Fix h2o-mojo-compatibility error

---

h2o-py/tests/testdir_munging/pyunit_pubdev_4727_groupby_median_large.py
h2o-r/tests/testdir_misc/runit_pubdev_4727_groupby_median_large.R

relax comparison threshold of numpy and h2o result from 1e-12 to 1e-10.
This test usually passes with 1e-12 but from time to time, it will fail.

fix intermittent pyunit_pubdev_4727_groupby_median_large.py

---

build.gradle
gradle/components/jython-cfunc.gradle
h2o-core/src/main/java/water/api/ModelMetricsHandler.java
h2o-core/src/main/java/water/udf/CFuncRef.java
h2o-docs/src/dev/custom_functions.md
h2o-extensions/jython-cfunc/build.gradle
h2o-extensions/jython-cfunc/src/main/java/water/udf/JythonCFunc2.java
h2o-extensions/jython-cfunc/src/main/java/water/udf/JythonCFuncLoader.java
h2o-extensions/jython-cfunc/src/main/java/water/udf/JythonObjectFactory.java
h2o-extensions/jython-cfunc/src/main/resources/META-INF/services/water.udf.CFuncLoader
h2o-extensions/jython-cfunc/src/test/java/water/udf/JythonCFuncTest.java
h2o-extensions/jython-cfunc/src/test/java/water/udf/JythonCustomMetricTest.java
h2o-extensions/jython-cfunc/src/test/resources/py/test_cfunc2.py
h2o-extensions/jython-cfunc/src/test/resources/py/test_mae_custom_metric.py
h2o-extensions/jython-cfunc/testMultiNode.sh
h2o-extensions/jython-cfunc/testSingleNode.sh
h2o-py/h2o/__init__.py
h2o-py/h2o/h2o.py
h2o-py/h2o/model/metrics_base.py
h2o-py/h2o/model/model_base.py
h2o-py/h2o/utils/shared_utils.py
h2o-py/tests/pyunit_utils/__init__.py
h2o-py/tests/pyunit_utils/utils_model_metrics.py
h2o-py/tests/testdir_algos/gbm/pyunit_custom_metrics_pubdev_5088.py
h2o-py/tests/testdir_algos/rf/pyunit_custom_metrics_pubdev_5088.py
settings.gradle

This follows PUBDEV-5087 by extending functionality to Python client and bringing ability to pass Python code from client to backend.
**This is PR to `mm/jira/pubdev-5087` branch!**
TODO:

[PUBDEV-5088] Support custom evaluation metrics in Python client

---

h2o-algos/src/main/java/hex/StackedEnsembleModel.java
h2o-algos/src/main/java/hex/ensemble/StackedEnsemble.java
h2o-algos/src/test/java/hex/ensemble/CheckSumTest.java
h2o-algos/src/test/java/hex/ensemble/StackedEnsembleTest.java
h2o-automl/src/main/java/ai/h2o/automl/AutoML.java
h2o-automl/src/main/java/ai/h2o/automl/Leaderboard.java
h2o-core/src/main/java/hex/ModelMetrics.java
h2o-docs/src/product/automl.rst
h2o-r/tests/testdir_algos/automl/runit_automl_args.R
h2o-r/tests/testdir_algos/automl/runit_automl_binomial_leaderboard_higgs.R

- AutoML: Change behavior of auto-generation of validation and leaderboard frames: [PUBDEV-4896](https://0xdata.atlassian.net/browse/PUBDEV-4896)
- AutoML leaderboard should use xval metrics by default: [PUBDEV-5071](https://0xdata.atlassian.net/browse/PUBDEV-5071)
- An runit
- Updated AutoML user guide
This will remove the auto-splitting of the training/validation frame into a leaderboard frame because it's no longer necessary as we can create the leaderboard using xval metrics now (since we can now use cross-validation on Stacked Ensembles, we can now score the leaderboard entirely using cross-validation metrics and we don't need a separate dataset for that anymore).  The new auto-splitting does a 80/20 split of the original training frame if the validation frame is missing (validation …

PUBDEV-4896 & PUBDEV-5071:  AutoML leaderboard using xval metrics

---

h2o-algos/src/main/java/hex/ensemble/StackedEnsemble.java
h2o-algos/src/test/java/hex/ensemble/CheckSumTest.java
h2o-algos/src/test/java/hex/ensemble/StackedEnsembleTest.java
h2o-automl/src/main/java/ai/h2o/automl/AutoML.java

This is a follow-up to the previous PR: https://github.com/h2oai/h2o-3/pull/1782
- Removes the level-one frame key by default in Stacked Ensembles (return to the original functionality).
- Turn on all SE junits again (they are all passing now).
- Sets `keep_levelone_frame = true`  for ensembles in AutoML

PUBDEV-4896: Cleanup levelone key & enable Stacked Ensemble junits

---

h2o-automl/src/main/java/ai/h2o/automl/AutoML.java
h2o-docs/src/product/automl.rst
h2o-r/tests/testdir_algos/automl/runit_automl_binomial_leaderboard_higgs.R

- Bug fixed, `leaderboard_frame` now functional again in AutoML.
- Runit to check for this is now turned back on.
- Updates to AutoML docs related to this and also fixing incorrect statements about early stopping.

PUBDEV-5115: Fixing AutoML leaderboard_frame bug & update AutoML docs

---

h2o-core/src/main/java/water/HeartBeat.java
h2o-core/src/main/java/water/Paxos.java

The second call should not print to stdout as it's for internal use only. It also prints these warnings in sparkling water in case these should be hidden.

[PUBDEV-5117] Improve print of jar mismatch warning

---

h2o-py/h2o/model/metrics_base.py

Occured when looking at result from BinomialGLM:
>>> model._model_json['output']
ModelMetricsBinomialGLM: glm
** Reported on train data. **
MSE: blah
RMSE: blah
LogLoss: blah
Null degrees of freedom: blah
Residual degrees of freedom: blah
Null deviance:blah
Residual deviance: blah
AIC: blah
AUC: blah
Gini: blah
Confusion Matrix (Act/Pred) for max f1 @ threshold = blah:
0       1     Error    Rate
-----  ------  ----  -------  ------------------
0    blah
1     blah
Total  blah
Maximum Metrics: Maximum metrics at their respective thresholds
metric                       threshold    value     idx
---------------------------  -----------  --------  -----
max f1                     blah
max f2                    blah
max f0point5             blah
max accuracy           blah
max precision …

PUBDEV-5128 - show fails with a KeyError

---

h2o-docs/src/product/cloud-integration/ec2-and-s3.rst
h2o-docs/src/product/flow.rst

- Changed “S3N” to “S3” in data import examples
- Added a note that S3 should be used for data ingest and S3N should be used for data export.

PUBDEV-5120: Update docs to remove S3N data ingest examples

---

h2o-r/README.md

Not 100% sure if this is necessary but I am seeing this build failure if not executing this additional command:
```
FAILURE: Build failed with an exception.
* Where:
Script '/Users/terrytangyuan/h2o-3/gradle/dataCheck.gradle' line: 4
* What went wrong:
Execution failed for task ':h2o-algos:smalldataCheck'.
> Please pull the required test data with ./gradlew syncSmalldata
```

Link to build instruction in root directory README

---

h2o-py/conda/h2o/meta.yaml

We can't specify versions in meta.yaml in order to be able to pass them later to conda build command

[PUBDEV-5157] Fix conda release

---

h2o-docs/src/front/index.html

Safari attempts to include all documents on one row rather than wrap the boxes (as other browsers do). Broke these UG boxes into two rows so that all are visible on Safari.

Create two rows for User Guides

---

h2o-docs/src/product/downloading.rst
h2o-docs/src/product/welcome.rst

- Added a note in the Anaconda install section describing that Python 3.6 users must add the condo-forge channel in order to include the required tabulate dependency.
- Updated the Pypi install instructions based on recent changes.
Driveby fix: Sparkling Water section now uses 2.2 in examples.

PUBDEV-5162: Updates to Anaconda and PySparkling with pypi

---

h2o-docs/src/product/data-munging/importing-data.rst
h2o-docs/src/product/data-munging/importing-files.rst
h2o-docs/src/product/data-munging/uploading-data.rst
h2o-docs/src/product/flow.rst
h2o-py/docs/data.rst
h2o-py/docs/intro.rst
h2o-r/h2o-package/R/import.R

Added to User Guide and R/Python docs that when files contain timestamps without a timezone, the parser will set the timezone to UTC (GMT)
Driveby fixes: In python, added additional supported file formats. Also updated the intro with a link to stack overflow.

PUBDEV-5149: Note in docs that missing timestamps are UTC

---

h2o-py/h2o/expr.py
h2o-py/tests/testdir_jira/pyunit_pubdev_5180.py

The conversion itself is done when the expression is 'serialized' into a Rapids expression. When repr2() is invoked using Python2, an 'L' suffix appears to every number with more bits than int is capable of holding. At this place, the suffix is stripped.
This fix only affects integer-like types, not complex types nor rational types.
There is a test written, tested both with Python 2.7 and Python 3.5. Version 3.6 has not been tested yet. Manual testing was done as well. Please see the attached screenshot (debug window in IntelliJ IDEA). The outcoming expression contains Long type correctly represented.

PUBDEV-5180 Python 2 timestamp interpreted as two tokens

---

h2o-r/h2o-package/R/models.R
h2o-r/tests/testdir_jira/runit_pubdev_4897.R

Ticket: https://0xdata.atlassian.net/browse/PUBDEV-4897
Manually tested. After the line proposed has been changed, order of values on X axis is preserved.

PUBDEV-4897 - PDP use different order of categorical

---

h2o-py/tests/testdir_algos/gbm/pyunit_PUBDEV_4090_grid_model_seeds.py

gridsearch model return list of models with seeds in the correct order as specified in the list most of the time.
However, lately, this has changed.  Hence, when I run the gridsearch model with the same seed lists, the models returned in the two lists with arbitrary seed order.
Added seed search before comparing training_rmse to make sure we are comparing two models with the same seed.

Compare two gridsearch models with the same seed

---

h2o-py/tests/testdir_algos/gbm/pyunit_PUBDEV_4090_grid_model_seeds.py

Added print statements to print out the training_rmse from the two grid search models.  This is really strange fail.

Print out training_rmse to make sure they are equal.

---

README.md
h2o-docs/src/product/data-science/algo-params/distribution.rst
h2o-docs/src/product/data-science/algo-params/offset_column.rst
h2o-docs/src/product/data-science/drf.rst
h2o-docs/src/product/data-science/gbm.rst

- In the GBM chapter, added “quasibinomail” to list of options available for the distribution parameter.
- In the parameters appendix for distribution, added quasibinomial to list of options available. Noted that this can only be used in GBM.
Driveby fixes:
- offset_column is not supported in DRF. Removed references to this option in the DRF chapter. Also removed “DRF” from list of “Available In” algos in the offset_column parameter description.

PUBDEV-5190: Add quasibinomial distribution option in GBM docs

---

h2o-docs/src/product/data-science/aggregator.rst

Added a description of the new “save_mapping_frame” option in Aggregator. This can be merged after PUBDEV-5171 is merged.

PUBDEV-5192: Add save_mapping_frame to Aggregator docs

---

h2o-core/src/main/java/water/api/PutKeyServlet.java
h2o-core/src/main/java/water/udf/DkvClassLoader.java
h2o-core/src/test/java/water/udf/DkvClassLoaderTest.java
h2o-extensions/jython-cfunc/src/main/java/water/udf/JythonObjectFactory.java
h2o-py/h2o/h2o.py
h2o-py/tests/pyunit_utils/utils_model_metrics.py
h2o-py/tests/testdir_jira/pyunit_pubdev_5184_custom_func_reloading.py

in Python notebooks, also enables iterative updates of defined  functions.
The existing approach required custom functions to be defined in a
separated Python module. The main reason was that interactive
environments (ipython, python shell) does not preserve source code of
defined classes (which we need to upload to backend).
This change goes
around the limitation by re-assembling class definition from methods
definitions (yes, surprisingly code of method is available). This is
good enough solution for ipython environments, but not sufficient for
standard python shell.
Furthermore, this PR enables iterative updates of function definition by
reloading Jython module to get always fresh module definition.
Includes:
- Test the reload scenario
- Better implementation of DKV classloader.
The …

[PUBDEV-5113][PUBDEV-5184] Allow definition of custom functions directly

---

h2o-py/scripts/verify_requirements.py

Some python versions have pip.get_installed_distributions() with a default parameter skip = ('pip', 'setuptools', 'python', ... ), which means that the h2o3 build fails with the assertion that pip and setuptools don't exist, even though they actually do. 
This change just forces pip.get_installed_distributions() to not skip *any* installed package, especially when h2o3 relies on this script to verify that the appropriate python dependencies are installed.

Set pip.get_installed_distributions param skip to () 

---

h2o-py/tests/testdir_jira/pyunit_pubdev_4818.py

XGBoost estimator cannot be executed when some unknown argument is passed.
This is a ported test from PR #1626 - thanks @johnygomez!
Once this is merged we can close the old PR.

Added test script, which verifies that XGBoost or GridSearch with

---

h2o-algos/testMultiNode.sh
h2o-algos/testSSL.sh
h2o-algos/testSingleNode.sh
h2o-algos/testSingleNodeOneProc.sh
h2o-core/testClientNode.sh
h2o-core/testMultiNode.sh
h2o-parsers/h2o-avro-parser/testMultiNode.sh
h2o-parsers/h2o-orc-parser/testMultiNode.sh
h2o-parsers/h2o-parquet-parser/testMultiNode.sh
h2o-persist-hdfs/testMultiNode.sh
h2o-persist-s3/testMultiNode.sh
h2o-scala/testMultiNode.sh

All JUnit test scripts should now use `$JVM_CLASSPATH` passed from Gradle, instead of defining the classpath by themselves.

[ITA-191] All JUnit test scripts should now use $JVM_CLASSPATH

---

h2o-algos/testMultiNode.sh
h2o-algos/testSSL.sh
h2o-algos/testSingleNode.sh
h2o-algos/testSingleNodeOneProc.sh
h2o-core/testClientNode.sh
h2o-core/testMultiNode.sh
h2o-parsers/h2o-avro-parser/testMultiNode.sh
h2o-parsers/h2o-orc-parser/testMultiNode.sh
h2o-parsers/h2o-parquet-parser/testMultiNode.sh
h2o-persist-hdfs/testMultiNode.sh
h2o-persist-s3/testMultiNode.sh
h2o-scala/testMultiNode.sh

[ITA-191] All JUnit test scripts should now use $JVM_CLASSPATH passed from Gradle. (#1935)

[ITA-191] All JUnit test scripts should now use $JVM_CLASSPATH passed from Gradle

---

h2o-r/h2o-package/R/connection.R

Option `h2o.dev.shutdown.disable` lets developers disable automatic
H2O shutdown in development mode when package is reloaded eg. using
devtools.

Tweak R shutdown in development

---

docker/Dockerfile
docker/Jenkinsfile-build-docker
docker/scripts/install_python_versions
docker/scripts/install_xgboost
scripts/jenkins/groovy/buildConfig.groovy

* add CMake to docker image
* additional parameter for Jenkins job which build the image -> revision of the XGBoost which should be part of the docker image
* create virtualenvs for all python versions which contain all the requirements + XGBoost
* should I create two separate envs for each Python - **one with** and **one without** XGBoost or is **one env with XGBoost** sufficient? cc @michalkurka 
* `docker/scripts/install_xgboost` -> XGBoost build script, please review @mmalohlava I'm not exactly sure I'm building it right
Thanks 🙂

[ITA-187] XGBoost installation inside docker image

---

h2o-r/h2o-package/R/models.R

This fixed failing PUBDEV-4897 test.

Reverted a fix for x-axis ordering in PUBDEV-4897

---

h2o-docs/src/booklets/v2_2015/source/PythonBooklet.tex
h2o-docs/src/booklets/v2_2015/source/python/python_randomized_grid_search.py
h2o-docs/src/booklets/v2_2015/source/python/python_scikit_learn_pipeline.py
h2o-docs/src/booklets/v2_2015/source/python/python_train_pca_model.py
h2o-docs/src/product/data-science/algo-params/impute_missing.rst
h2o-docs/src/product/data-science/algo-params/pca_method.rst
h2o-docs/src/product/data-science/algo-params/transform.rst
h2o-docs/src/product/data-science/algo-params/use_all_factor_levels.rst
h2o-py/demos/H2O_tutorial_medium_NOPASS.ipynb
h2o-py/dynamic_tests/testdir_algos/pca/pyunit_pca_gridsearch_over_all_params_large.py
h2o-py/h2o/h2o.py
h2o-py/tests/pyunit_utils/utilsPY.py
h2o-py/tests/testdir_algos/glrm/pyunit_PUBDEV_4246_pro_var.py
h2o-py/tests/testdir_algos/glrm/pyunit_glrm_PUBDEV_3501_variance_metrics.py
h2o-py/tests/testdir_algos/pca/pyunit_PUBDEV_3827_scoringHistory_importance.py
h2o-py/tests/testdir_algos/pca/pyunit_PUBDEV_4314_varimp.py
h2o-py/tests/testdir_algos/pca/pyunit_arrestsPCA.py
h2o-py/tests/testdir_algos/pca/pyunit_grid_quasar_pca.py
h2o-py/tests/testdir_algos/pca/pyunit_prostatePCA.py
h2o-py/tests/testdir_algos/pca/pyunit_pubdev_3500_max_k_large.py
h2o-py/tests/testdir_algos/pca/pyunit_pubdev_3916_pca_hangs.py
h2o-py/tests/testdir_algos/pca/pyunit_pubdev_4167_pca_NOPASS_OOM.py
h2o-py/tests/testdir_algos/pca/pyunit_scoringPCA.py
h2o-py/tests/testdir_algos/pca/pyunit_wideDataset_Rotterdam_large.py
h2o-py/tests/testdir_jira/pyunit_pubdev_4702_algo_max_runtime_secs_large.py
h2o-py/tests/testdir_jira/pyunit_pubdev_4802_short_max_runtime_secs.py
h2o-py/tests/testdir_misc/pyunit_screeplot.py
h2o-py/tests/testdir_pipeline/pyunit_scale_pca_rf.py
h2o-py/tests/testdir_scikit_grid/pyunit_scal_pca_rf_grid.py

PCA is now an estimator. Previous examples imported using:
`from h2o.transforms.decomposition import H2OPCA`
For this issue, I changed all of these examples to
`from h2o.estimators.pca import H2OPrincipalComponentAnalysisEstimator`
or
`from h2o.estimators.pca import H2OPrincipalComponentAnalysisEstimator
as H2OPCA` (where appropriate)

PUBDEV-5230: Update import statement for PCA

---

h2o-py/h2o/estimators/estimator_base.py
h2o-py/tests/testdir_pipeline/pyunit_scale_pca_rf.py

A push to master caused the following [tests](http://mr-0xc1:8080/job/h2o-3-pipeline/job/master/365/artifact/py2.7-small/h2o-3/h2o-py/tests/results/failed/) to fail.  This fixes at least the grid and sklearn pipeline.  Might need another fix for the javapredict test.
- testdir_algos_pca_pyunit_grid_quasar_pca.py
- testdir_javapredict_pyunit_javapredict_dynamic_data_paramsPCA.py
- testdir_pipeline_pyunit_scale_pca_rf.py 
- testdir_scikit_grid_pyunit_scal_pca_rf_grid.py

[HOTFIX] Fixing PCA Estimator issues

---

h2o-automl/src/main/java/ai/h2o/automl/AutoML.java
h2o-automl/src/main/java/ai/h2o/automl/AutoMLBuildSpec.java
h2o-automl/src/main/java/ai/h2o/automl/Leaderboard.java
h2o-automl/src/main/java/ai/h2o/automl/UserFeedbackEvent.java
h2o-automl/src/main/java/water/automl/api/schemas3/AutoMLBuildSpecV99.java
h2o-automl/src/main/java/water/automl/api/schemas3/AutoMLV99.java
h2o-core/src/main/java/water/util/PojoUtils.java
h2o-docs/src/product/automl.rst
h2o-py/h2o/automl/autoh2o.py
h2o-py/h2o/frame.py
h2o-py/tests/testdir_algos/automl/binomial/pyunit_automl_prostate.py
h2o-py/tests/testdir_algos/automl/pyunit_automl_args.py
h2o-py/tests/testdir_algos/automl/pyunit_automl_leaderboard.py
h2o-r/h2o-package/R/automl.R
h2o-r/tests/testdir_algos/automl/runit_automl_leaderboard.R

AutoML exclude_algos + bugfixes for empty leaderboard and deadlock
Note: This replaces another [PR](https://github.com/h2oai/h2o-3/pull/1867/) which had a bunch of extra commits on it

PUBDEV-4980: Exclude algos from AutoML

---

h2o-bindings/bin/gen_R.py
h2o-r/h2o-package/R/kmeans.R
h2o-r/tests/testdir_jira/runit_pubdev_5129.R

PUBDEV-5129 - Fold column in Kmeans should not be required to be in x

---

h2o-algos/src/main/java/hex/StackedEnsembleModel.java
h2o-algos/src/main/java/hex/ensemble/Metalearner.java
h2o-algos/src/main/java/hex/ensemble/StackedEnsemble.java
h2o-algos/src/main/java/hex/schemas/StackedEnsembleV99.java
h2o-bindings/bin/gen_R.py
h2o-bindings/bin/gen_java.py
h2o-bindings/bin/gen_python.py
h2o-core/src/main/java/water/api/Schema.java
h2o-py/h2o/estimators/stackedensemble.py
h2o-py/tests/testdir_algos/stackedensemble/pyunit_stackedensemble_custom_metalearner.py
h2o-r/h2o-package/R/stackedensemble.R
h2o-r/tests/testdir_algos/stackedensemble/runit_stackedensemble_custom_metalearner_params.R

* Added customized metalearner for stacked ensembles.
* User passes in a dictionary/list of parameters to the argument `metalearner_params`, which are passed to `metalearner_algorithm`.
* Example in R: 
```
#Metalearner params for gbm
gbm_params <- list(ntrees=100, max_depth = 6)
stack_gbm <- h2o.stackedEnsemble(x = x,
y = y,
training_frame = train,
base_models = list(my_gbm, my_rf),
metalearner_algorithm = "gbm",
metalearner_params = gbm_params)
```
* Example in Python:
```
gbm_params = {"ntrees" : 100, "max_depth" : 6}
stack_gbm = H2OStackedEnsembleEstimator(base_models=[my_gbm, my_rf], 
metalearner_algorithm="gbm",
metalearner_params = gbm_params)
```
* Note, the field `metalearner_params` is a `String` field in Java. I convert the string to a map which gets processed in the SE impl.
* …

PUBDEV-5086 Stacked Ensemble should allow user to pass in a customized metalearner

---

README.md

I had some troubles with building H2O and I noticed (correct me if I'm wrong), that building requires a properly set up Python with packages like `requests`. Maybe it would be suitable, if user was explicitly warned about that in the beginning, even before first code block containing the `./gradlew build`.
Thanks :)

Github README update

---

scripts/jenkins/Makefile.jenkins
scripts/jenkins/groovy/defineTestStages.groovy

[ITA-221] Increase timeout for R Small and R Small Client Mode.
[ITA-222] Truncate output from failed JUnit Smoke tests

[ITA-221-222] Increase timeout for R tests. Truncate output of smoke JUnit

---

docker/hadoop/cdh/Dockerfile
docker/hadoop/hdp/Dockerfile
docker/scripts/install_python_versions

H2O_BRANCH="master" is needed to get requirements.txt (to install proper python libraries) - not really necessary for the Hadoop builds

Fix build of Hadoop docker images (no xgboost + specify master for req.txt)

---

h2o-core/src/main/java/hex/grid/GridSearch.java
h2o-core/src/main/java/water/exceptions/H2OConcurrentModificationException.java
h2o-core/src/main/java/water/fvec/RollupStats.java

In GridSearch we are looking at the state of whole DKV and we might try to calculate a checksum on objects (Vecs) that are being modified. We should be able to detect this state and don't fail.

[HOTFIX] PUBDEV-5286: GBM grid failing on some datasets

---

h2o-docs/src/product/data-science/algo-params/categorical_encoding.rst
h2o-docs/src/product/data-science/xgboost.rst

Updated the XGBoost chapter to indicate that multi-node support is available as a Beta feature.
Driveby fix: the Auto option for categorical_encoding in XGBoost runs enum rather than label_encoder.

PUBDEV-5312: Document that multi-node support in XGBoost is beta

---

h2o-py/h2o/automl/autoh2o.py

Now we pull the data directly from the H2OTwoDimTable instead of converting to a pandas DataFrame then H2OFrame.

PUBDEV-5159: Removed pandas dependency from AutoML Python leaderboard

---

h2o-docs/src/booklets/v2_2015/source/GLMBooklet.tex
h2o-docs/src/product/data-science/algo-params/beta_constraints.rst
h2o-docs/src/product/data-science/algo-params/compute_p_values.rst
h2o-docs/src/product/data-science/algo-params/prior.rst
h2o-docs/src/product/data-science/glm.rst
h2o-docs/src/product/parameters.rst

- Added beta_constraints and prior to parameter appendix in the User Guide
- Updated parameters index to include these
- Added links to these topics in the GLM chapter
- For beta_constraints in the GLM booklet, added mean and std_dev to list of beta_constraints options

PUBDEV-5292: Adding beta_constraints and prior to UG parameters

---

h2o-docs/src/booklets/v2_2015/source/GLMBooklet.tex
h2o-docs/src/product/data-science/algo-params/beta_constraints.rst
h2o-docs/src/product/data-science/algo-params/compute_p_values.rst
h2o-docs/src/product/data-science/algo-params/prior.rst
h2o-docs/src/product/data-science/glm.rst
h2o-docs/src/product/parameters.rst

- Added beta_constraints and prior to parameter appendix in the User
Guide
- Updated parameters index to include these
- Added links to these topics in the GLM chapter
- For beta_constraints in the GLM booklet, added mean and std_dev to
list of beta_constraints options

PUBDEV-5292 for rel-wolpert: adding beta_constraints and prior to UG

---

h2o-extensions/xgboost/src/main/java/hex/tree/xgboost/XGBoostModel.java
h2o-py/h2o/estimators/xgboost.py
h2o-r/h2o-package/R/xgboost.R
h2o-r/tests/testdir_algos/xgboost/runit_NOFEATURE_XGBoost_checkpoint_new_category_in_predictor.R
h2o-r/tests/testdir_algos/xgboost/runit_NOFEATURE_XGBoost_checkpoint_remove_all.R
h2o-r/tests/testdir_algos/xgboost/runit_NOFEATURE_XGBoost_ecology_random_noise.R
h2o-r/tests/testdir_algos/xgboost/runit_XGBoost_col_sample_per_tree.R
h2o-r/tests/testdir_algos/xgboost/runit_XGBoost_cup98_01_medium.R
h2o-r/tests/testdir_algos/xgboost/runit_XGBoost_ecology.R
h2o-r/tests/testdir_algos/xgboost/runit_XGBoost_forloop_attack_medium.R
h2o-r/tests/testdir_algos/xgboost/runit_XGBoost_frameslice.R

Second batch of ported tests, and a fix for PUBDEV-5278, which I found via `runit_XGBoost_cup98_01_medium.R`.

PUBDEV-5249: add second batch of Runit tests ported from GBM to XGBoost and fixes for bugs found

---

h2o-extensions/xgboost/src/main/java/hex/tree/xgboost/XGBoostModel.java

Issue: https://0xdata.atlassian.net/browse/PUBDEV-5294
This is a known issue with XGBoost, when the library takes system Locale and uses it to determine decimal separator.
There are many countries with different decimal separator from US/UK decimal point, usually a decimal comma (arabic style). For example Japan shares the same settings with US/UK (one more reason for this to work for the US guys and Mateusz). https://en.wikipedia.org/wiki/Decimal_separator
This issue has been reported many times (e.g. here https://github.com/dmlc/xgboost/issues/2512), however for some uses, this is considered a feature and is unlikely to be fixed soon.
Therefore, fixing this issue on our side by passing localized parameters is the preferred option.

PUBDEV-5294 - XGBoost model in Flow doesn't seem to converge

---

h2o-core/src/main/java/water/parser/ParseTime.java
h2o-core/src/main/java/water/util/Log.java
h2o-core/src/test/java/water/parser/ParseTimeTest.java

Issue link: https://0xdata.atlassian.net/browse/PUBDEV-5326
First problem is the time parsing method is vulnerable to index being out of bounds very quickly. Second problem is the unknown nature of the data our customer used. However, I was exactly able to reproduce the issue with "2011-01-01:" (or other variations for day-first and month-first alternatives...) or ":" for time-only case. 
This above-mentioned case causes time parsing method to try to parse first two digits (hours), when there is none or only one. This very specific case has been handled manually. If the parsing case is not time-only, the date is returned. If the parsing case is time-only, a Long.MIN_VALUE signaling the value could not be parsed as time.
However, there are potentially more cases where an ArrayOutOfBounds …

PUBDEV-5326 - Bug in ParseTime which leads to parse failing

---

h2o-core/src/main/java/water/JettyHTTPD.java

The IE caches the response. Because of that, the first response from `Jobs/` endpoint is cached. All of the following requests are being handled by the cache -> the status bar does not move. This is supported also by provided logs, as there is **only one** request to `Jobs/` 
```
2018-02-01 11:01:16,538   POST    200      25 ms  /3/ModelBuilders/drf
2018-02-01 11:01:16,562   GET     200       0 ms  /3/Jobs/%2403017f00000132d4ffffffff%24_94ca1fffceba56563f1268bbaec14efe
2018-02-01 11:01:37,321   GET     200      31 ms  /3/Models
```
Here is a screen from IE console where the cached requests are recorded:

[PUBDEV-5282] Add Cache-Control=no-cache

---

h2o-core/src/main/java/water/JettyHTTPD.java

* [PUBDEV-5282] Add Cache-Control=no-cache. Otherwise the IE caches the responses and the status bar is not moving when building model.
* [PUBDEV-5282] Set the no-cache for Xhr requests only
Cherry picked from 6b68b49824

[WOL-PUBDEV-5282] Add Cache-Control=no-cache (#2066)

---

h2o-algos/src/main/java/hex/coxph/CoxPH.java
h2o-algos/src/main/java/hex/coxph/CoxPHModel.java
h2o-algos/src/main/java/hex/schemas/CoxPHModelV3.java
h2o-core/src/main/java/water/util/VecUtils.java

We still support only a relatively small amount of discrete events (< 10000), however, events can be specified as floating numbers.
This PR also lowers memory requirements of the algo. Memory is allocated only for time slots which were used as a stop time.

PUBDEV-986: Modify CoxPH to handle float time values

---

h2o-py/h2o/frame.py
h2o-py/tests/testdir_misc/pyunit_colname_rename.py

This is my first PR just to get familiar with the PR process here. Plase take note that I'm not a Python dev.
I added a new method that would have the same functionality as `pandas.DataFrame.rename` for renaming columns. It is just a simple wrapper around `H2OFrame.set_name`
I'm not sure if you wish to deprecate `H2OFrame.set_name` and `H2OFrame.set_names`. Let me know and I can extend this PR.
Test with:
```
df = pandas.DataFrame({'col1': [1, 1, 2], 'col2': ['a', 'b', 'c']})
hf = h2o.H2OFrame(df)
print(hf.col_names)
hf = hf.rename(columns={'col11': 'aa', "col2": "bb"})
print(hf.col_names)
hf = hf.rename(columns={0: "cc"})
print(hf.col_names)
```

[PUBDEV-4968] Add a h2o.H2OFrame.rename method to rename columns in py

---

h2o-algos/src/main/java/hex/schemas/DRFV3.java
h2o-bindings/bin/gen_R.py
h2o-bindings/bin/gen_python.py
h2o-py/h2o/estimators/random_forest.py
h2o-r/h2o-package/R/randomforest.R

* Revert "PUBDEV-5191: removed offset and distribution parameters from distributed random forest algo (#1887)"
This reverts commit 1d5492893e62384d96862381d5cadd9cb1f19516.
* Add deprecation for offset_column and distribution
* Change deprecation docstring
* Remove dup params
* More fixes and add warning if deprecated args are used
* Explicitly set offset_column and distribution for random forest

PUBDEV-5335: Add distribution and offset_column back into Random Forest

---

h2o-algos/src/main/java/hex/glm/GLMModel.java
h2o-core/src/main/java/hex/Model.java
h2o-r/tests/testdir_jira/runit_pubdev_5323_glm_ensemble.R

GLM doesn't support 'balance classes' - however the option is present for backwards compatibility, we should prevent entering the code that attempts to do balancing because the prior distribution is not available in GLM

PUBDEV-5323: GLM doesn't need prediction post-processing

---

h2o-r/h2o-package/R/frame.R

Update the description of `x` so that it is more clear multiple target encodings can occur and interaction target encodings.

PUBDEV-5308 - updates to target encoding documentation

---

h2o-algos/src/main/java/hex/schemas/SharedTreeV3.java
h2o-algos/src/main/java/hex/tree/SharedTree.java
h2o-docs/src/product/data-science/algo-params/col_sample_rate_change_per_level.rst
h2o-docs/src/product/data-science/drf.rst
h2o-docs/src/product/data-science/gbm.rst
h2o-py/h2o/estimators/gbm.py
h2o-py/h2o/estimators/random_forest.py
h2o-py/tests/pyunit_utils/utilsPY.py
h2o-py/tests/testdir_jira/pyunit_pubdev_5334_col_sample_rate_change_per_level.py
h2o-r/h2o-package/R/gbm.R
h2o-r/h2o-package/R/randomforest.R
h2o-r/tests/testdir_jira/runit_pubdev_5334_col_sample_rate_change_per_level.R

Confirmed with Arno that the col_sample_rate_change_per_level parameter must be > 0.0 and <= 2.0.
In our documentation we said something like between 0 and 2 which is not accurate.  I have changed all documentation (I hope) to say instead, > 0 and <= 2.  
Generated R and Py unit tests to make throw errors are thown when this parameter is not set correctly.

PUBDEV-5334: col_sample_rate_change_per_level parameter

---

h2o-docs/src/product/data-science/algo-params/pca_impl.rst
h2o-docs/src/product/data-science/pca.rst
h2o-docs/src/product/parameters.rst
h2o-py/tests/testdir_algos/pca/pyunit_pubdev_4961_pca_implementations.py

- Added pca_impl to list of parameters in the PCA chapter
- Added a pca_impl topic to the parameters appendix
Driveby fix: Updated the PCA import statement in the pac_implementation
python test. This is now from h2o.estimators.pca import
H2OPrincipalComponentAnalysisEstimator as H2OPCA instead of from
h2o.transforms.decomposition import H2OPCA. (Verified that this works
locally.)

PUBDEV-5154: Document new pca_impl parameter

---

h2o-automl/src/main/java/ai/h2o/automl/AutoML.java
h2o-py/tests/testdir_algos/automl/multinomial/pyunit_automl_iris.py
h2o-r/tests/testdir_algos/automl/runit_automl_args.R

* Skip SE if only one model built in AutoML
* Update test as one model in AutoML does not produce a SE
* Fix pyunit test to account for SE not being built if only one model is built in AutoML

PUBDEV-4933: AutoML should not train Stacked Ensemble with only one model (#2125)

---

h2o-core/src/main/java/water/parser/CsvParser.java
h2o-core/src/test/java/water/parser/CsvParserTest.java

[JIRA PUBDEV-5370](https://0xdata.atlassian.net/browse/PUBDEV-5370)
When headers parsing was done, an assumption had been made for each character to only be represented as a single byte. However, there are many characters that are represented by more than 3 bytes.
Instead of feeding a StringBuilder directly, all the bytes are first collected in a ByteArrayOutputStream (A simple growing byte array). The final String is created at the very end. This saves a little memory (StringBuilder vs ByteArrayOutputStream) and is potentially a little bit faster as well.

PUBDEV-5370 - parser cannot handle some utf-8 characters in header

---

h2o-algos/src/main/java/hex/DataInfo.java
h2o-algos/src/main/java/hex/coxph/CoxPH.java
h2o-algos/src/main/java/hex/coxph/CoxPHModel.java
h2o-algos/src/main/java/hex/schemas/CoxPHV3.java
h2o-r/h2o-package/R/coxph.R
h2o-r/tests/testdir_algos/coxph/runit_coxph_strata_inter.R

This workarounds an issue in GLM/DataInfo that cannot handle a mix of InteractionWrappedVec where some of them use all factor levels and some of them don't. This is an issue with numeric-categorical interactions.

[Experimental] CoxPH & GLM: fixes categorical-numerical interactions

---

h2o-genmodel/src/main/java/hex/genmodel/easy/EasyPredictModelWrapper.java
h2o-genmodel/src/main/java/hex/genmodel/easy/error/CountingErrorConsumer.java
h2o-genmodel/src/main/java/hex/genmodel/easy/error/VoidErrorConsumer.java
h2o-genmodel/src/test/java/hex/genmodel/easy/EasyPredictModelWrapperTest.java

JIRA: https://0xdata.atlassian.net/browse/PUBDEV-5324
Example output:
```text
Following columns had NaN values in the predicted dataset: Origin,fDayofMonth
```

PUBDEV-5324 & PUBDEV-5383 - Make  POJO log error messages for all wrong data types

---

h2o-r/h2o-package/R/automl.R
h2o-r/h2o-package/R/communication.R

Traditional R ways of masking output didn't work so I had to use `h2o.no_progress()` and `h2o.show_progress()` to resolve this issue. Note that this call is wrapped in a `tryCatch()` to properly revert back to `h2o.show_progress()` when any failure happens.

PUBDEV-5388: Mask additional progress bar from h2o.automl()

---

h2o-persist-gcs/src/main/java/water/persist/PersistGcs.java

@Pscheidl This PR fixes the cache issue. in `persist-gcs` branch.
Also, some minimal code reformatting is included in the `PersistGcs` class.

Fixing bug with cache usage in gcs-persist; code reformatting

---

h2o-py/h2o/backend/server.py
h2o-py/h2o/utils/__init__.py
h2o-py/h2o/utils/shared_utils.py
h2o-py/tests/testdir_misc/pyunit_mojo_predict.py

The proposed API is following: `h2o_utils.mojo_predict(input_csv, mojo_zip, genmodel_jar, verbose, output_csv)`. Only `input_csv` and `mojo_zip` are required, rest is optional.
- `input_csv` - Path to CSV containing data to score.
- `mojo_zip` - Path to MOJO zip.
- `genmodel_jar` - Path to h2o-genmodel.jar. If None, then we'll look for the `h2o-genmodel.jar` in the same folder where is the `mojo_zip`.
- `output_csv` - Path where CSV with predictions should be saved. If None, then predictions will be saved to `prediction.csv` in the same folder where is the `mojo_zip`.
- `verbose` - If True, prints additional debug output.

[PUBDEV-3901] Python MOJO predictions

---

h2o-genmodel/src/main/java/hex/genmodel/easy/error/CountingErrorConsumer.java
h2o-genmodel/src/test/java/hex/genmodel/easy/EasyPredictModelWrapperTest.java

Today, during a call with customer, I discovered that our `CountingErrorConsumer` is not gathering data per column when it comes to transformation errors.
This quick PR fixes it.

CountingErrorConsumer gathers data transformation errors per column

---

h2o-core/src/main/java/water/rapids/ast/prims/operators/AstBinOp.java
h2o-core/src/main/java/water/rapids/ast/prims/operators/AstEq.java
h2o-py/tests/testdir_jira/pyunit_pubdev_5336.py

* PUBDEV-5336 - h2o python: get wrong ans when run a conditional statement in h2o
(cherry picked from commit 447484d)
* Rename variable with transformed indices
(cherry picked from commit 8ef2130)
* Whitespaces deleted
(cherry picked from commit 935de15)
* Avoided allocation of additional memory by passing arguments in right order beforehand
(cherry picked from commit 75faba1)
* An attempt to quick fix/verify vec type problem
(cherry picked from commit 4e976bd)
* NaN handling. Pre-calculated categorical column conditions.
(cherry picked from commit f6c3cea)
* Testing NAs
(cherry picked from commit e0aeacb)
* NAs in test
(cherry picked from commit f746312)
(cherry picked from commit ba9d1b6)

Pavel pubdev 5336 rel wheeler 

---

h2o-core/src/main/java/hex/Model.java
h2o-core/src/main/java/hex/ScoreKeeper.java
h2o-core/src/main/java/hex/ScoringInfo.java
h2o-core/src/main/java/hex/schemas/HyperSpaceSearchCriteriaV99.java
h2o-core/src/main/java/water/api/schemas3/ModelParametersSchemaV3.java
h2o-py/h2o/estimators/deeplearning.py
h2o-py/h2o/estimators/deepwater.py
h2o-py/h2o/estimators/gbm.py
h2o-py/h2o/estimators/random_forest.py
h2o-py/h2o/estimators/xgboost.py
h2o-py/tests/testdir_jira/pyunit_pubdev_5397_r2_early_stop.py
h2o-r/h2o-package/R/deeplearning.R
h2o-r/h2o-package/R/deepwater.R
h2o-r/h2o-package/R/gbm.R
h2o-r/h2o-package/R/randomforest.R
h2o-r/h2o-package/R/xgboost.R
h2o-r/tests/testdir_jira/runit_pubdev_5397_r2_early_stop.R

Added code in Java backend to enable users to use r2 as a stopping criteria.
Added runit and pyunit tests to make sure clients can specify r2 as a stopping criteria.

PUBDEV 5397: added R2 as an early stopping criteria

---

h2o-extensions/xgboost/src/main/java/hex/tree/xgboost/XGBoostUtils.java

We were getting integer overflows here and there. For 2D matrix case we should use longs.
This branch requires an updated XGBoost version (won't compile with the current one) - https://github.com/h2oai/xgboost/pull/31

[PUBDEV-5366] Fixes AIOOB due to integer overflow

---

h2o-algos/src/main/java/hex/StackedEnsembleModel.java
h2o-algos/src/main/java/hex/ensemble/Metalearner.java
h2o-algos/src/main/java/hex/ensemble/StackedEnsemble.java
h2o-algos/src/main/java/hex/schemas/StackedEnsembleV99.java
h2o-bindings/bin/gen_R.py
h2o-py/h2o/estimators/stackedensemble.py
h2o-r/h2o-package/R/stackedensemble.R

* Keep API the same from R/Python
* Take `metalearner_params` input as a `String` and process as `Model.Parameter` type in backend
* This should help `metalearner` grid search efforts in the future

Utilize model parameter objects for metalearner_params in Stacked Ensemble

---

h2o-core/build.gradle
h2o-extensions/jython-cfunc/build.gradle

InteliJ can't resolve for some reason the original mockito library
If tests pass, this change should be safe

[PUBDEV-5460] Upgrade Mockito library to unblock running tests in Intelij

---

h2o-extensions/xgboost/src/main/java/hex/tree/xgboost/XGBoost.java
h2o-extensions/xgboost/src/main/java/hex/tree/xgboost/XGBoostUtils.java
h2o-extensions/xgboost/src/main/java/ml/dmlc/xgboost4j/java/PersistentDMatrix.java
h2o-extensions/xgboost/src/main/java/ml/dmlc/xgboost4j/java/XGBoostCleanupTask.java
h2o-extensions/xgboost/src/main/java/ml/dmlc/xgboost4j/java/XGBoostSetupTask.java
h2o-extensions/xgboost/src/main/java/ml/dmlc/xgboost4j/java/XGBoostUpdateTask.java

This PR makes sure the training input to XGBoost is created just once instead of in each iteration.
We only fix the training in this PR, scoring issue is not addressed.
Speed-up recorded on the dataset from HEXDEV-714
Before:
```Model    xgboost-c197fbfd-9573-4b36-8ab5-9a168952d311    XGBoost    2018-04-06 20:36:52    2018-04-06 20:51:36    00:14:44.672    DONE```
After:
```Model    xgboost-c197fbfd-9573-4b36-8ab5-9a168952d311    XGBoost    2018-04-09 18:14:25    2018-04-09 18:16:08    00:01:43.449    DONE```

PUBDEV-5459: Create XGBoost training matrix just once

---

h2o-extensions/xgboost/src/main/java/hex/tree/xgboost/XGBoost.java
h2o-extensions/xgboost/src/main/java/hex/tree/xgboost/XGBoostUtils.java
h2o-extensions/xgboost/src/main/java/ml/dmlc/xgboost4j/java/PersistentDMatrix.java
h2o-extensions/xgboost/src/main/java/ml/dmlc/xgboost4j/java/XGBoostCleanupTask.java
h2o-extensions/xgboost/src/main/java/ml/dmlc/xgboost4j/java/XGBoostModelInfo.java
h2o-extensions/xgboost/src/main/java/ml/dmlc/xgboost4j/java/XGBoostScoreTask.java
h2o-extensions/xgboost/src/main/java/ml/dmlc/xgboost4j/java/XGBoostSetupTask.java
h2o-extensions/xgboost/src/main/java/ml/dmlc/xgboost4j/java/XGBoostUpdateTask.java
h2o-genmodel-extensions/xgboost/src/main/java/hex/genmodel/algos/xgboost/XGBoostMojoModel.java
h2o-genmodel-extensions/xgboost/src/main/java/ml/dmlc/xgboost4j/java/BoosterHelper.java

Do not rely on GC to dispose of the XGBoost objects (DMatrix, Booster). We need to explicitly dispose of these object everytime we create a new instance. If we really on GC we can die on OOM because JVM might not see any need to dispose of the object even though the whole process is actually running out of memory (especially on Hadoop where the containers are running in constrained memory).

[HOTFIX] HEXDEV-714: Properly dispose memory of DMatrix in XGB score/train

---

h2o-py/h2o/automl/autoh2o.py
h2o-py/tests/testdir_algos/automl/pyunit_automl_mojo.py
h2o-py/tests/testdir_algos/automl/pyunit_automl_pojo.py
h2o-r/h2o-package/R/kvstore.R
h2o-r/tests/testdir_algos/automl/runit_automl_mojo.R
h2o-r/tests/testdir_algos/automl/runit_automl_pojo.R

* Added ability to download MOJO/POJO for leader model in AutoML directly.
* POJO download will not work for Stacked Ensembles as that is not supported.
* Also fixed R note about undocumented parameter, `genmodel_path` , in `h2o.download_mojo()`

PUBDEV-4991 Add MOJO/POJO support for AutoML

---

h2o-core/src/main/java/water/AutoBuffer.java
h2o-core/src/main/java/water/util/IcedHashMapGeneric.java
h2o-core/src/test/java/water/util/IcedHashMapGenericTest.java
h2o-extensions/xgboost/src/main/java/hex/tree/xgboost/BoosterParms.java
h2o-extensions/xgboost/src/main/java/hex/tree/xgboost/XGBoost.java
h2o-extensions/xgboost/src/main/java/hex/tree/xgboost/XGBoostModel.java
h2o-extensions/xgboost/src/main/java/ml/dmlc/xgboost4j/java/XGBoostScoreTask.java
h2o-extensions/xgboost/src/main/java/ml/dmlc/xgboost4j/java/XGBoostUpdateTask.java
h2o-extensions/xgboost/src/test/java/hex/tree/xgboost/BoosterParmsTest.java

This PR refactors the XGB implementation in order to create the parameters for the Booster just one time (at the beginning of the training).
This produces a little bit nicer logs (no repeated dumps of the parameters) and performs GPU check just one time.

XGBoost: Create Booster parameters just once -> nicer log + single GPU check 

---

h2o-algos/src/main/java/hex/StackedEnsembleModel.java
h2o-automl/src/main/java/ai/h2o/automl/AutoML.java
h2o-automl/src/main/java/ai/h2o/automl/AutoMLBuildSpec.java
h2o-automl/src/main/java/water/automl/api/schemas3/AutoMLBuildSpecV99.java
h2o-core/src/main/java/hex/Model.java
h2o-py/h2o/automl/autoh2o.py
h2o-r/h2o-package/R/automl.R
h2o-r/tests/testdir_algos/automl/runit_automl_args.R

* Added two parameters (`keep_cross_validation_predictions` & `keep_cross_validation_models`) that allows a user to clean up or keep CV prediction frames/models from the DKV after the AutoML process is done. This parameter is `True` by default.
* `keep_cross_validation_predictions` & `keep_cross_validation_models` are placed in `build_control` for AutoML.
* Also added method to delete cross validation predictions for a h2o-3 model

PUBDEV-4939 Add the Option to Save CV Predictions and CV Models in AutoML

---

h2o-extensions/xgboost/src/main/java/hex/tree/xgboost/rabit/RabitTrackerH2O.java

Socket leak discovered as a part of  [#2035](https://github.com/h2oai/h2o-3/pull/2035).
The socket leak has been found on two places. Misallocated ServerSocketChannel.open() may thrown an exception when tried to be bound, but those connections seem to create hanging FDs until closed or garbage collected (or the process is terminated).
Also, if SHUTDOWN_CMD is received, there is no need to keep the connection opened, thus closing it immediately seems like a best option to free resources ASAP.
Last but not least, the thread where final SocketChannel channel = tracker.sock.accept(); is called (in its run method) may be interrupted (by calling this.trackerThread.interrupt(); from RabitTrackerH2O's stop() method. The ServerSocketChannel itself is closed explicitely, but not the accepted …

PUBDEV-5505 - Closing Rabit connection after communication ends

---

h2o-extensions/xgboost/src/main/java/hex/tree/xgboost/rabit/RabitTrackerH2O.java

* PUBDEV-5505 - Closing Rabit connection after communication ends
* Overridden interrupt() method of RabitTrackerH2OThread calls super.interrupt()
* Move socketChannel cleanup logic to RabitTracker's stop method.
* Log level of RabitTracker's startup exception changed from info to err.
(cherry picked from commit c0fb930)

PUBDEV-5505 - Closing Rabit connection after communication ends - rel-wolpert

---

h2o-py/h2o/model/metrics_base.py
h2o-py/h2o/model/model_base.py
h2o-py/tests/testdir_algos/gbm/pyunit_magnus_gbm_empty_metrics.py
h2o-r/h2o-package/R/frame.R
h2o-r/h2o-package/R/models.R
h2o-r/tests/testdir_algos/gbm/runit_GBM_empty_metric_check.R

Corrected empty metric_json problem:
When the response column is not included in the scoring dataset, the metric_json is empty becuase we cannot calculate those metrics without the response column.  
However, instead of crashing, an warning message will be shown to the user.  A pyunit test was added to make sure this fix works.

Prevent scoring crash when response column is absent in scoring dataset

---

h2o-core/src/main/java/hex/ModelBuilder.java
h2o-core/src/test/java/hex/ModelBuilderTest.java

The rebalance logic is modified to consider all CPU cores in the cluster. We are trying to mimic the behavior of ParseDataset and how the Parse allocates chunks. To do that we calculate a virtual size of the Frame as it would take on disk if it was stored in a simple binary format that has no overhead but also doesn't apply any compression. The virtual size is then used to determine how would the Parser parse such dataset (what would be the chunk size). We use the derived number of chunks and if the number of non-empty chunks in the Frame is lower than 0.5 * desired number of chunks we rebalance the dataset (ratio is configurable by a system property).
Defaults to the old behavior which will tend to not rebalance the dataset. Has to be enabled by setting a system property.
This PR works …

PUBDEV-5444: Improve rebalance logic to consider multinode clusters

---

scripts/jenkins/groovy/buildH2O3.groovy
scripts/jenkins/groovy/defineTestStages.groovy
scripts/jenkins/groovy/hadoopStage.groovy

Adds test of standalone H2O jar with various Hadoop distros.
Temporarily runs on micro nodes only, so there is only one node per executor.
Removes wildcards from HDP related env vars.
Increases build timeout to 50 minutes for hadoop build.

[ITA-291] Add standalone tests for H2O + Hadoop.

---

gradle.properties
h2o-algos/build.gradle
h2o-core/build.gradle
h2o-parsers/h2o-orc-parser/build.gradle
h2o-parsers/h2o-parquet-parser/build.gradle
h2o-persist-hdfs/build.gradle

See https://0xdata.atlassian.net/browse/PUBDEV-5464
With this fix, all published H2O artifacts can be loaded via their maven coordinates in Databrics cloud which will also unblock deployment of SW in DBC using maven

[PUBDEV-5464] Fix issues preventing loading of h2o maven artifacts in DBC

---

scripts/jenkins/jenkinsfiles/Jenkinsfile-Release

This PR fixes the failing release into PyPI. After upload to PyPI, we are checking, if `pip install h2o` installs new version. However, because of some delays on side of the PyPI, the new version is propagated after a while (similarly as in case of Maven). Therefore we have removed the check of the version and we are no longer ignoring the potential errors during upload with twine (they should be fixed).

[WOL-ITA-295] Fix PyPI release stage. Do not ignore twine related errors. Remove check PyPI stage.

---

h2o-r/h2o-package/R/frame.R

This should fix the following CRAN check:
```
* checking Rd \usage sections ... WARNING
Undocumented arguments in documentation object 'h2o.rank_within_group_by'
‘group_by_cols’
Documented arguments not in \usage in documentation object 'h2o.rank_within_group_by':
‘groupby_cols’
```

Fix typo in docs in rank_within_group_by.

---

h2o-core/src/main/java/water/fvec/ChunkVisitor.java

Fixes
```
at water.MRTask.getResult(MRTask.java:478) 
at water.MRTask.getResult(MRTask.java:486) 
at water.MRTask.doAll(MRTask.java:390) 
at water.MRTask.doAll(MRTask.java:385) 
at hex.glm.GLM$GLMGradientSolver.getGradient(GLM.java:1705) 
at hex.glm.GLM.init(GLM.java:477) 
at hex.glm.GLM$GLMDriver.computeImpl(GLM.java:1057) 
at hex.ModelBuilder$Driver.compute2(ModelBuilder.java:206) 
at hex.glm.GLM$GLMDriver.compute2(GLM.java:543) 
at water.H2O$H2OCountedCompleter.compute(H2O.java:1263) 
at jsr166y.CountedCompleter.exec(CountedCompleter.java:468) 
at jsr166y.ForkJoinTask.doExec(ForkJoinTask.java:263) 
at jsr166y.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:974) 
at jsr1......ForkJoinTask.java:263) 
at jsr166y.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:974) 
at …
```

Fix for adding Double.NaN to IntAryVisitor via addValue().

---

h2o-web/bower.json

[WOL-PUBDEV-5567] Remove GoogleTagManager from Flow.

---

h2o-web/bower.json

[WHEELER-PUBDEV-5567] Remove GoogleTagManager from Flow.

---

h2o-docs/src/front/index.html
h2o-docs/src/product/api-reference.rst
h2o-docs/src/product/security.rst
h2o-docs/src/product/welcome.rst

Driveby fixes: Adding links to R HTML and to SW API html format,
updated link for What is Sparkling Water on docs site.

PUBDEV-5545-relwolpert: Added section for enforcing system-level command-line arguments in h2odriver

---

h2o-py/h2o/grid/grid_search.py
h2o-py/h2o/grid/metrics.py
h2o-py/tests/testdir_algos/glm/pyunit_ordinal_gridsearch_large.py
h2o-r/tests/testdir_algos/glm/runit_ordinal_glm_gridsearch_large.R

Gridsearch not working with Python.
Fixed the problem by adding the gridsearch class for ordinal regression.
Added pyunit and runit tests to make sure gridsearch worked for both clients.

Fixed gridsearch error for python client

---

h2o-automl/src/main/java/ai/h2o/automl/AutoML.java
h2o-py/h2o/automl/autoh2o.py
h2o-py/tests/testdir_algos/automl/pyunit_automl_get_automl.py
h2o-r/h2o-package/R/automl.R
h2o-r/h2o-package/R/classes.R
h2o-r/h2o-package/pkgdown/_pkgdown.yml
h2o-r/tests/testdir_algos/automl/runit_automl_get_automl.R

* Add functions `h2o.get_automl()/h2o.getAutoML` to Python and R APIs for AutoML
* These functions allow a user to fetch information about an AutoML instance from the H2O cluster
* The information fetched include the automl key, project name, leader model, and leaderboard, which is in par with what is currently returned in R/Python
* Note, the Python function does not return an instance of `H2OAutoML` since a lot of the metadata (stopping_tolerance, max_runtime_secs, etc) is not available via the REST api. So, I figured this is a good first pass as both functions between R and Python do the same thing.

PUBDEV-5177: Add a h2o.get_automl()/h2o.getAutoML function to R/Python APIs

---

h2o-algos/src/main/java/hex/glrm/GLRM.java
h2o-algos/src/main/java/hex/glrm/GLRMGenX.java
h2o-algos/src/main/java/hex/glrm/GLRMModel.java
h2o-algos/src/main/java/hex/glrm/GlrmMojoWriter.java
h2o-algos/src/test/java/hex/glrm/GLRMTest.java
h2o-core/src/main/java/hex/Model.java
h2o-docs/src/product/productionizing.rst
h2o-genmodel/src/main/java/hex/genmodel/algos/glrm/GlrmMojoModel.java
h2o-genmodel/src/main/java/hex/genmodel/algos/glrm/GlrmMojoReader.java
h2o-genmodel/src/main/java/hex/genmodel/easy/EasyPredictModelWrapper.java
h2o-genmodel/src/main/java/hex/genmodel/easy/prediction/DimReductionModelPrediction.java
h2o-genmodel/src/main/java/hex/genmodel/tools/PredictCsv.java
h2o-py/tests/pyunit_utils/utilsPY.py
h2o-py/tests/testdir_javapredict/pyunit_pubdev_5058_glrm_mojo_large.py
h2o-r/tests/runitUtils/utilsR.R
h2o-r/tests/testdir_javapredict/runit_PUBDEV_5058_glrm_mojo_large.R
h2o-r/tests/testdir_javapredict/runit_PUBDEV_5529_leaf_node_assign_drf_mojo.R

GLRM predict can generate different outputs depending on the dataframe you use to perform the prediction on.
If you use the training dataframe, the prediction output will be the multiplication of X*Y where X were stored in representation_key.
If you use a brand new test dataframe, there will be two actions associated with prediction:
1. First, it needs to generate a new X frame from the test dataset and the existing archetype.
2. Second, it will then generate the reconstructed dataframe from Xnew*Y.
Problems with current implementation:
1. Current GLRM scoring will only generate X*Y.  Asking for scoring with different testframe will generate an error.  Need to add capability to our code to enable scoring on brand new dataset.
2. Current GLRM mojo will only generate the new X factor given …

Pubdev 5058 glrm mojo predict

---

h2o-core/build.gradle
h2o-core/src/main/java/org/eclipse/jetty/plus/jaas/spi/LdapLoginModule.java
h2o-core/src/main/java/water/AbstractHTTPD.java
h2o-core/src/main/java/water/DelegatingAuthenticator.java
h2o-core/src/main/java/water/JettyHTTPD.java
h2o-core/src/test/java/water/api/CustomHttpFilterTest.java
h2o-docs/src/product/security.rst
h2o-extensions/authsupport/build.gradle
h2o-extensions/authsupport/src/main/java/ai/h2o/org/eclipse/jetty/jaas/spi/LdapLoginModule.java
h2o-extensions/authsupport/src/main/java/ai/h2o/org/eclipse/jetty/plus/jaas/spi/LdapLoginModule.java
h2o-hadoop/driverjar.gradle
h2o-hadoop/h2o-mapreduce-generic/build.gradle
h2o-hadoop/h2o-mapreduce-generic/src/main/java/water/JettyProxy.java
h2o-hadoop/h2o-mapreduce-generic/src/main/java/water/ProxyStarter.java

This reverts commit 88f081254766fe0321002714c00c9f8fceccacce.
Jetty 9 breaks `-proxy` mode of the h2odriver because Hadoop puts `servlet-api:2.5` on the classpath. Jetty 9 relies on `servlet-api:3.1`

PUBDEV-5611 Jetty 9 breaks h2odriver proxy mode

---

h2o-docs/src/product/productionizing.rst
h2o-genmodel/src/main/java/overview.html

Added to the MOJO example to illustrate how to access the leaf node assignment and GLRM fields.

Added documentation for mojo part for GBM/DRF and GLRM.

---

h2o-automl/src/main/java/ai/h2o/automl/AutoML.java

* Metadata collection in AutoML can be time consuming for no particular reason as this information is not utilized by AutoML in terms of model building, parameter tuning, etc. 
* Metadata information is only logged out to java logs.

PUBDEV-5625 Remove frame metadata calculation from AutoML

---

h2o-automl/src/main/java/ai/h2o/automl/AutoML.java
h2o-automl/src/main/java/water/automl/api/schemas3/AutoMLV99.java

* Remove frame metadata calculation from AutoML (this is not used by AutoML and can decrease runtime)
* 473d815 should help with intermittent NPE's in AutoML Jenkins testing
* Minor comment fixes and removal of an extra import in AutoMLV99

PUBDEV 5625 Remove frame metadata calculation from AutoML/PUBDEV-5623 Intermittent test failures for AutoML

---

h2o-py/h2o/frame.py
h2o-py/h2o/utils/shared_utils.py
h2o-py/tests/testdir_jira/pyunit_pubdev_5560.py

cf. https://0xdata.atlassian.net/browse/PUBDEV-5560
currently with Python client, creation of H2OFrame is inconsistent:
* `fr = h2o.H2OFrame()` > OK, but then `fr.describe/summary()` raises an exception 'NoneType' object is not iterable.
* `fr = h2o.H2OFrame([])` > OK, but then `fr.describe/summary()` raises an exception on iteration.
* `fr = h2o.H2OFrame(())` > same as above.
* `fr = h2o.H2OFrame([[]])` > KO, raises a H2OIllegalArgumentException. 
* `fr = h2o.H2OFrame({})` > KO, raises a H2OIllegalArgumentException.
fixing this for following behaviour:
* `fr = h2o.H2OFrame()` > no change.
* `fr = h2o.H2OFrame([])` > OK, empty frame 0 row, 1 col, `fr.describe/summary()` prints "This H2OFrame is empty."
* `fr = h2o.H2OFrame(())` > same as above.
* `fr = h2o.H2OFrame([[]])` > same as above. …

PUBDEV-5560: handle corner-cases consistently when creating H2OFrame with empty objects in Python

---

h2o-automl/src/main/java/ai/h2o/automl/AutoML.java

* Ensure response column is in validation/leaderboard frame when applicable for AutoML

PUBDEV-5570 AutoML: Informative error message when validation missing response column

---

h2o-py/h2o/automl/autoh2o.py

* Ensure fold/weight columns are in ignored columns before trying to remove in AutoML train() method

PUBDEV-5250 AutoML: specifying x and fold_column does not set ignored columns

---

h2o-docs/src/product/automl.rst
h2o-docs/src/product/data-science/algo-params/calibrate_model.rst
h2o-docs/src/product/data-science/algo-params/calibration_frame.rst
h2o-docs/src/product/data-science/drf.rst
h2o-docs/src/product/data-science/gbm.rst
h2o-docs/src/product/parameters.rst

- Docs now reference ‘calibration_frame’ instead of ‘calibrate_frame’
- Driveby fix: Added missing space after ** in AutoML topic.

PUBDEV-5622: Replace 'calibrate_frame' with 'calibration_frame' in docs

---

h2o-docs/src/product/automl.rst
h2o-docs/src/product/cloud-integration/google-compute.rst
h2o-docs/src/product/data-science/algo-params/calibrate_model.rst
h2o-docs/src/product/data-science/algo-params/calibration_frame.rst
h2o-docs/src/product/data-science/drf.rst
h2o-docs/src/product/data-science/gbm.rst
h2o-docs/src/product/parameters.rst

- Docs now reference ‘calibration_frame’ instead of ‘calibrate_frame’
- Driveby fixes: Added missing space after ** in AutoML topic. Fixed
Python and R commands for starting H2O-3 with Google offering

PUBDEV-5622 rel-wright: Replace 'calibrate_frame' with 'calibration_frame' in docs

---

h2o-automl/src/main/java/ai/h2o/automl/AutoML.java
h2o-automl/src/main/java/ai/h2o/automl/Leaderboard.java
h2o-py/tests/testdir_algos/automl/pyunit_automl_args.py
h2o-py/tests/testdir_algos/automl/pyunit_automl_get_automl.py
h2o-py/tests/testdir_algos/automl/pyunit_automl_ignore_cols.py
h2o-r/tests/testdir_algos/automl/runit_automl_args.R

* This PR ensures AutoML respects the `max_runtime_secs` parameter by always checking the amount of time remaining in every poll of a job, which in this case is a model build.
* This PR also adds in a case for an empty leaderboard, which returns an empty leaderboard that has binomial metrics (we can change the headers to something else if needed)
* This PR also updates each test that uses a small `max_runtime_secs` parameter by always using `max_models` >=2 to avoid issues if the leaderboard is empty due to lack of run time.

PUBDEV-5613 Ensure AutoML respects max_runtime_secs

---

h2o-docs/src/product/cloud-integration/ec2-and-s3.rst
h2o-docs/src/product/faq/clusters.rst
h2o-docs/src/product/faq/general-troubleshooting.rst
h2o-docs/src/product/faq/hadoop.rst
h2o-docs/src/product/howto/FAQ.md
h2o-docs/src/product/howto/H2O-DevHadoop.md
h2o-docs/src/product/howto/H2O-DevS3Creds.md
h2o-docs/src/product/security.rst

Removed references to UDP in the user guide and from markdown files in the howto folder.

PUBDEV-5641: Remove "udp" from H2O-3 UG

---

h2o-py/h2o/expr.py
h2o-py/h2o/frame.py
h2o-py/h2o/utils/shared_utils.py
h2o-py/tests/testdir_jira/pyunit_pubdev_5560.py

cf. https://0xdata.atlassian.net/browse/PUBDEV-5560
currently with Python client, creation of H2OFrame is inconsistent:
fr = h2o.H2OFrame() > OK, but then fr.describe/summary() raises an exception 'NoneType' object is not iterable.
fr = h2o.H2OFrame([]) > OK, but then fr.describe/summary() raises an exception on iteration.
fr = h2o.H2OFrame(()) > same as above.
fr = h2o.H2OFrame([[]]) > KO, raises a H2OIllegalArgumentException.
fr = h2o.H2OFrame({}) > KO, raises a H2OIllegalArgumentException.
this PR is fixing this for following behaviour:
fr = h2o.H2OFrame() > OK, fr.describe/summary() prints "This H2OFrame is empty and not initialized." as it doesn't have any data nor representation on server side.
fr = h2o.H2OFrame([]) > OK, empty frame 0 row, 1 col, fr.describe/summary() prints "This …

PUBDEV-5560[reopen]: handle corner-cases consistently when creating H2OFrame with empty objects in Python

---

h2o-py/tests/pyunit_utils/utilsPY.py
h2o-py/tests/testdir_algos/xgboost/pyunit_H2OXGBoost_native_XGBoost_mixed_binomial_compare_large_dense_NOPASS_multinode.py
h2o-py/tests/testdir_algos/xgboost/pyunit_H2OXGBoost_native_XGBoost_mixed_multinomial_compare_large_dense_NOPASS_multinode.py
h2o-py/tests/testdir_algos/xgboost/pyunit_H2OXGBoost_native_XGBoost_mixed_regression_compare_large_dense_NOPASS_multinode.py

Pavel has noticed that tests failed when categorical levels > 10.  This is caused by sorting order difference between H2OXGBoost and native XGBoost.
I fixed the problem in Python utilsPY.py

PUBDEV-5703: fix bug when enum cardinality > 10.

---

h2o-docs/src/product/data-munging/groupby.rst

Replaced “NumberOfFlights” with “Month” in the R example. Also added ending “)” to that line.

PUBDEV-5711: Fix group_by R example

---

h2o-docs/src/product/data-munging/replacing-values.rst

- R uses 1-based index. Updated the R example in the replacing-values.rst file to state this. Also verified that Python uses 0, so that example is correct.

PUBDEV-5710-relwright: Fix R example for replacing values in a frame

---

h2o-docs/src/product/data-munging/replacing-values.rst

- R uses 1-based index. Updated the R example in the replacing-values.rst file to state this. Also verified that Python uses 0, so that example is correct.

PUBDEV-5710: Fix R example for replacing values in a frame

---

h2o-py/demos/README.md

Header 2 and Header 3's were misformatted due to lack of space. For example,  \##Header was used instead of \## Header.

Update markdown formatting in h2o-3/demos/README.md

---

h2o-core/src/main/java/hex/ScoringInfo.java

[PUBDEV-5576](https://0xdata.atlassian.net/browse/PUBDEV-5576)
The original issue reported was wrong `x-validation AUC`. That was just a symptom however.
In the end, I found the whole process of filling the table from ScoringInfo was buggy. The values filled did not make any sense (especially coefficient of determination being 1.7 in x-validation was suspicious).
-Root mean square error for x-validation was just forgotten to be filled, resulting in all columns to be shifted to left by one since position 14.
- Cross-validation AUC was filled with validation AUC
The following screenshots demonstrate the situation before and after fix.
Also tested other algorithms manually, such as GLM. Added a simple assert at the end to check if number of values in the table (in each row) is the same as …

PUBDEV-5576 - grid search from flow reports wrong cross validation auc

---

h2o-docs/src/product/data-science/algo-params/start_column.rst
h2o-docs/src/product/data-science/algo-params/stop_column.rst
h2o-docs/src/product/data-science/coxph.rst
h2o-docs/src/product/getting-data-into-h2o.rst

- Added Amazon Redshift to list of supported JDBC drivers.
Driveby fix: In CoxPH, stop_column is required.

PUBDEV-5715: Amazon Redshift JDBC support

---

h2o-py/tests/pyunit_utils/utilsPY.py
h2o-py/tests/testdir_algos/xgboost/pyunit_H2OXGBoost_native_XGBoost_enum_binomial_compare_sparse_NOPASS.py
h2o-py/tests/testdir_algos/xgboost/pyunit_H2OXGBoost_native_XGBoost_enum_multinomial_compare_sparse_NOPASS.py
h2o-py/tests/testdir_algos/xgboost/pyunit_H2OXGBoost_native_XGBoost_mixed_binomial_compare_large_dense_NOPASS_multinode.py
h2o-py/tests/testdir_algos/xgboost/pyunit_H2OXGBoost_native_XGBoost_mixed_binomial_compare_large_sparse_NOPASS_multinode.py
h2o-py/tests/testdir_algos/xgboost/pyunit_H2OXGBoost_native_XGBoost_mixed_multinomial_compare_large_dense_NOPASS_multinode.py
h2o-py/tests/testdir_algos/xgboost/pyunit_H2OXGBoost_native_XGBoost_mixed_multinomial_compare_large_sparse_NOPASS_multinode.py
h2o-py/tests/testdir_algos/xgboost/pyunit_H2OXGBoost_native_XGBoost_mixed_regression_compare_large_dense_NOPASS_multinode.py
h2o-py/tests/testdir_algos/xgboost/pyunit_H2OXGBoost_native_XGBoost_mixed_regression_compare_large_sparse_NOPASS_multinode.py
h2o-py/tests/testdir_algos/xgboost/pyunit_H2OXGBoost_native_XGBoost_numerical_binomial_compare_sparse_NOPASS.py

Fixed bug found by Pavel.  Native XGBoost will build only 10 trees.  Need to specify it via num_boost_round if we want to build a different number of trees in our comparison tests.

Fixed bug found by Pavel.  

---

h2o-r/h2o-package/pkgdown/_pkgdown.yml

This is required in order for the functions to appear in the R HTML docs. Verified that they now appear when I build locally.

PUBDEV-5424: Add new functions to _pkgdown.yml file

---

h2o-r/h2o-package/pkgdown/_pkgdown.yml

This is required in order for the functions to appear in the R HTML docs. Verified that they now appear when I build locally.

PUBDEV-5424-relwright: Add new functions to _pkgdown.yml file

---

h2o-genmodel-extensions/xgboost/build.gradle

(cherry picked from commit 110e66f)
This PR is the rel-wright version of https://github.com/h2oai/h2o-3/pull/2613
[PUBDEV-5612](https://0xdata.atlassian.net/browse/PUBDEV-5612)
After recent changes to H2O-XGBoost had been made in https://github.com/h2oai/xgboost/pull/45 (approved, merged), a new release of `ai.h2o:xgboost4j` version `0.7.9` was done.
After release (huge thank you to @michal-raska for setting-up the pipeline), dependency version in H2O were raised to `0.7.9`.
Tried on p3.2xlarge Amazon EC2 machine with one Tesla V100 (the same configuration as reporter). 
- Build H2O.jar with H2O XGBoost version `0.7.9`
- Use this newly generated JAR in the benchmark. This means to put it into the docker, start it and make the `R` benchmark connect to this H2O instance, instead of …

PUBDEV-5612 XGBoost Crashes on Tesla

---

h2o-core/src/main/java/water/persist/PersistNFS.java
h2o-py/h2o/frame.py
py/testdir_multi_jvm/test_gbm_prostate.py

python client converted path with no scheme to local format,  breaking cross-platform interoperability.
also fixed handling of paths with a "file" scheme on import

PUBDEV-5686: cross-platform compatibility when importing files from Python API

---

h2o-core/src/main/java/water/persist/PersistNFS.java
h2o-py/h2o/frame.py

PUBDEV-5686: cross-platform compatibility when importing files from Python API (#2569)
* fix handling of file scheme on file import
* maintain backwards compatibility with old behaviour for now (cf. PUBDEV-5717)
(cherry picked from commit 6f9a95a)

PUBDEV-5686: cross-platform compatibility when importing files using Python API

---

h2o-core/src/main/java/water/rapids/ast/prims/mungers/AstGroup.java
h2o-py/h2o/group_by.py
h2o-py/tests/testdir_munging/pyunit_PUBDEV_5687_groupby_with_stringCols.py
h2o-r/h2o-package/R/frame.R
h2o-r/tests/testdir_misc/runit_PUBDEV_5687_groupby_with_string_columns.R

DO NOT REVIEW THIS ONE.  It duplicates the one for master.
PUBDEV-5687: groupby with string columns.  Fixed Java backend and added pyunit and Runit tests.
PUBDEV-5687: added documentation to remind users that string columns will be skipped.
PUBDEV-5687: added warning statements to Python and R clients per Michalk code review suggestions.

PUBDEV-5687: added groupby with String columns in Java.

---

h2o-algos/src/main/java/hex/glrm/GLRMModel.java

Intermittent failure caused by enum domains mismatched between h2o predict and mojo predict.  This is caused by not calling the right frame in scoring.

Rel-wright-PUBDEV-5727: GLRM bug causing difference between H2O predict and mojo predict

---

h2o-docs/src/product/index.rst
h2o-docs/src/product/welcome.rst

- Added a Resources section to the Overview and included links to the
awesome-h2o repo, blogs, and customer use cases
Driveby: Added missing “)” in welcome section, and added a link to the new RStudio cheat sheet

PUBDEV-5674: Add link to awesome-h2o repo in docs

---

h2o-core/src/main/java/water/api/ImportFilesHandler.java
h2o-core/src/main/java/water/api/RegisterV3Api.java
h2o-core/src/main/java/water/api/schemas3/ImportFilesMultiV3.java
h2o-core/src/main/java/water/persist/PersistManager.java
h2o-core/src/main/resources/META-INF/services/water.api.Schema
h2o-py/h2o/h2o.py
h2o-py/tests/testdir_misc/pyunit_import_multi.py

This change also improves performance of ingest when importing from
large number of source files / directories. Previous implementation
was sequential and resulted in a single request per source. This is
especially bad for HTTP ingest which is done eagerly.
Current implementation does a single request for all the files. Loading
is paralellized on a single node (not distributed - typically not necessary).

PUBDEV-5429: Add support for ingesting from multiple directories + speedup

---

h2o-docs/src/product/mojo-quickstart.rst
h2o-genmodel/src/main/java/overview.html

- Added note to Javadoc and User Guide that when downloading MOJOs, the entire path must be specified and not the relative path.

PUBDEV-5731: Specify entire path when downloading MOJOs

---

h2o-docs/src/front/index.html
h2o-docs/src/product/flow.rst
h2o-docs/src/product/getting-data-into-h2o.rst

- Added info that XLS/XLSX files must be BIFF 8 format. Also noted that support for XLS and XLSX files will eventually be deprecated.
Driveby fix: updated links for RSparkling readme now that RSparkling has moved to Sparkling Water repo.

PUBDEV-5694: Add info about supported version of XLS/XLSX (rel-wright)

---

h2o-docs/src/product/productionizing.rst
h2o-genmodel/src/main/java/overview.html

Added note to Javadoc and User Guide that when downloading MOJOs, the entire path must be specified and not the relative path.

PUBDEV-5731: Specify entire path when downloading MOJOs (rel-wright)

---

h2o-core/src/main/java/water/parser/ParseDataset.java
h2o-core/src/main/java/water/parser/ParseSetup.java
h2o-core/src/main/java/water/parser/Parser.java
h2o-core/src/main/java/water/parser/ParserInfo.java
h2o-core/src/test/java/water/TestUtil.java
h2o-parsers/h2o-orc-parser/src/test/java/water/parser/ParseTestMultiFileOrc.java
h2o-parsers/h2o-parquet-parser/src/main/java/water/parser/parquet/ChunkConverter.java
h2o-parsers/h2o-parquet-parser/src/main/java/water/parser/parquet/ChunkReadSupport.java
h2o-parsers/h2o-parquet-parser/src/main/java/water/parser/parquet/ChunkRecordMaterializer.java
h2o-parsers/h2o-parquet-parser/src/main/java/water/parser/parquet/ParquetParser.java
h2o-parsers/h2o-parquet-parser/src/main/java/water/parser/parquet/ParquetParserProvider.java
h2o-parsers/h2o-parquet-parser/src/main/java/water/parser/parquet/VecParquetReader.java
h2o-parsers/h2o-parquet-parser/src/main/java/water/parser/parquet/WriterDelegate.java
h2o-parsers/h2o-parquet-parser/src/test/java/water/parser/parquet/ParseTestParquet.java

Ingesting large number (= thousands) of Parquet files can be slow because Parquet parser doesn't support stream parse (due to nature of Parquet file format - metadata are at the end). CSV parser can handle this case by switching from a distributed parse to stream parse and distributed the workload on file level instead of block level. Parquet parser doesn't have this option because stream parse method is not available.
In this PR we introduces a new type of parse method - sequential parse. Sequential parse will be an alternative to stream parse and will be used when "local" = (non-distributed) parse is requested.

PUBDEV-5733: Fast ingest of 100s of small Parquet files

---

h2o-docs/src/front/index.html
h2o-docs/src/product/flow.rst
h2o-docs/src/product/getting-data-into-h2o.rst

- Added info that XLS/XLSX files must be BIFF 8 format. Also noted that support for XLS and XLSX files will eventually be deprecated.
Driveby fix: updated links for RSparkling readme now that RSparkling has moved to Sparkling Water repo.

PUBDEV-5694: Add info about supported version of XLS/XLSX

---

h2o-algos/build.gradle
h2o-assemblies/main/build.gradle

This change will get us to 129MB (< 130MB limit of PyPI)
Dependencies removed:
- full aws-sdk (we only need aws-s3-sdk)
- 32 bit versions of netlib libraries

PUBDEV-5730: Reduce size of h2o.jar in order to deploy to PyPI

---

h2o-r/h2o-package/pkgdown/_pkgdown.yml

h2o.pr_auc() will be accessible as a h2o function when user call it after installing it.

Exposed h2o.pr_auc in _pkgdown.yml

---

h2o-genmodel/src/main/java/hex/genmodel/algos/tree/ScoreTree.java
h2o-genmodel/src/main/java/hex/genmodel/algos/tree/ScoreTree0.java
h2o-genmodel/src/main/java/hex/genmodel/algos/tree/ScoreTree1.java
h2o-genmodel/src/main/java/hex/genmodel/algos/tree/ScoreTree2.java
h2o-genmodel/src/main/java/hex/genmodel/algos/tree/SharedTreeMojoModel.java
h2o-genmodel/src/main/java/hex/genmodel/algos/tree/SharedTreeMojoReader.java

Field _mojo_version was declared as Number, comparison `_mojo_version.equals(1.0)`
is harmful because it triggers autoboxing of a constant to an object.
This happens for every scored row.
Microbenchmark results:
- Current (master) version:
Benchmark                             (rows)  Mode  Cnt    Score   Error  Units
GbmMojoScoringBench.measureGbmScore0    1000  avgt   10    5.805 ± 0.044  ms/op
GbmMojoScoringBench.measureGbmScore0  100000  avgt   10  571.884 ± 3.827  ms/op
- This PR:
Benchmark                             (rows)  Mode  Cnt    Score   Error  Units
GbmMojoScoringBench.measureGbmScore0    1000  avgt   10    5.643 ± 0.039  ms/op
GbmMojoScoringBench.measureGbmScore0  100000  avgt   10  555.807 ± 5.626  ms/op
- Optimal version (simplified implementation that assumes single …

PUBDEV-5760: Avoid unnecessary memory allocation in GBM/DRF mojo scoring

---

h2o-core/src/main/java/water/H2O.java
h2o-core/src/main/java/water/H2ONode.java
h2o-core/src/main/java/water/init/NetworkInit.java
h2o-hadoop/h2o-mapreduce-generic/src/main/java/water/hadoop/h2odriver.java

Introduces a new parameter `port_offset`. This parameter lets the user specify the relationship of the API port ("web port") and the internal communication port. Old implementation expected `h2o port = api port + 1`. Because there are assumptions in the code that the h2o port and api port can be derived from each other we cannot fully decouple them. Instead, we let the user specify an offset such that `h2o port = api port + offset`. This enables the user to move the communication port to a specific range which can be firewalled. 
Example:
hadoop jar h2odriver.jar -mapperXmx 64g -nodes 4 -baseport 55000 -port_offset 5000
Port bindings:
java      11186     yarn  249u  IPv4 30424314      0t0  TCP *:55000 (LISTEN)
java      11186     yarn  251u  IPv4 30434363      0t0  TCP …

PUBDEV-5752: H2O API port and the internal port don't have to be adjacent

---

h2o-web/bower.json

There was an issue with the build pipeline (libs and modules were not populated correctly).

[PUBDEV-5794] Fix importSqlTable button in Flow.

---

h2o-web/bower.json

There was an issue with the build pipeline (libs and modules were not populated correctly).
(cherry picked from commit d7e40bcda37d7d3a841d70b495d124c25e890235)

[WRI-FLOW-PUBDEV-5794] Fix importSqlTable button in Flow. (#2704)

---

h2o-web/bower.json

Removes `keep_cross_validation_fold_assignment` from AutoML, which is missing on backend. Caused by a wrong cherry-pick.
[PUBDEV-5793] AutoML not correctly ignoring columns via Flow

[WRI] Update Flow to 0.7.34.

---

h2o-algos/src/main/java/hex/api/RegisterAlgos.java
h2o-algos/src/main/java/hex/schemas/TreeV3.java
h2o-algos/src/main/java/hex/tree/TreeHandler.java
h2o-algos/src/main/resources/META-INF/services/water.api.Schema
h2o-algos/src/test/java/hex/tree/TreeHandlerTest.java
h2o-genmodel/src/main/java/hex/genmodel/algos/tree/SharedTreeNode.java
h2o-r/demos/rdemo.tree.fetch.R
h2o-r/h2o-package/R/models.R
h2o-r/tests/testdir_jira/runit_pubdev_5735.R

* PUBDEV-5735 Tree traversal API
* Made rightChild of SharedTreeNode public (reverted accidental change in this PR).
* Extracting SharedTreeSubgraph from SharedTreeModel's output for a specific tree & class
* Basic tree conversion from SharedTreeSubgraph to scikit format. Tested output tree structure.
* Inclusive levels per node
* Split values and inclusive levels as a description string. Removed unused methods from TreeHandler class.
* Non-static tree format conversion test
* Class with tree properties in TreeHandler named TreeProperties to reflect its purpose
* Splits taken from root node, not currently visited node
* Take included categorical levels split from root. Evade putting a colon at the end of node description for categorical split.
* Avoid sending root node number through the …

PUBDEV-5735 Tree traversal API (#2702) - MASTER

---

h2o-docs/src/product/starting-h2o.rst
h2o-py/h2o/h2o.py

The pydocs for `h2o.init()` did not specify the input type for `max_mem_size` and `min_mem_size`, so I added this.

Adding extra info to pydocs h2o.init max_mem_size param

---

h2o-docs/src/product/mojo-quickstart.rst
h2o-docs/src/product/welcome.rst

- Added a Python example to the Docker Users topic
- Added note reminding Mac users to Docker memory size
- Link for accessing the walkthrough topic is now Walkthrough rather than id5
Driveby fix: Use // for comments in Java example rather than #. This eliminates 2 warnings when building the docs.

PUBDEV-5839: Update "Docker Users" topic in the User Guide

---

h2o-core/src/main/java/water/H2O.java
h2o-r/h2o-package/R/connection.R
h2o-r/tests/testdir_jira/runit_pubdev_5789.R

- removed useless call to curl
- replaced with message suggesting that the user should check Java version used for starting h2o
When the failure occurs, this can be for couple of reasons, including (1) connection problems and (2) problems to start the application. Before this change, the console output always showed the symptom, twice (failure to connect) but did not indicate possible causes.
In the first case, the symptom is already indicated by the message from R output (which anyway seems to be equal to the one from `curl`). Therefore calling curl again (probably meant just to get the error message) does not seem useful.
In the latter case, one of possible causes is, incorrect version of Java. So the user is instructed to check it.
For any other causes, the user can explore the …

PUBDEV-5789: cleaner message after failure to locally start server

---

h2o-core/src/main/java/water/H2O.java
h2o-r/h2o-package/R/connection.R
h2o-r/tests/testdir_jira/runit_pubdev_5789.R

- removed useless call to curl
- before starting h2o, check if the version is ok
- added xref comments to simplify consistent update if the version support rules evolve
- java version checking in R turned into blacklisting of versions 1.2-1.6, and happens on better place
This PR is a `rel-wright` cherry-pick of #2736 from `master`.

PUBDEV-5789: simplified R user experience when facing java version issue

---

h2o-algos/src/main/java/hex/schemas/TreeV3.java
h2o-algos/src/main/java/hex/tree/TreeHandler.java
h2o-r/h2o-package/R/kvstore.R
h2o-r/h2o-package/R/models.R
h2o-r/tests/testdir_jira/runit_pubdev_5735.R

* PUBDEV-5832 - GBM/DRF tree API categorical levels compression
* Added documentation for levels array in R tree API
* Moved column names and column domaines exposed in H2OModel R class into common field columns.
* Added presence of filled categorical levels to the tree traversal structure test.
* An empty array of levels is recognized as a vector of logicals by R. This case needs to be handled explicitely.
* Fixed a typo in tree fetch demo
* Renamed columns variable on model in R API to var.names
* Not storing whole for GBM/DRF tree structure, storing the id instead
* Removed unused ArrayUtils in TreeHandler
* Model categorical domains & column names are not explicitely added to the Model R class, they're just not excluded.
* Only left-side categorical levels are sent by Tree API to the …

PUBDEV-5832 - GBM/DRF tree API categorical levels compression (#2743)

---

h2o-bindings/src/main/java/water/bindings/examples/Example.java
h2o-core/src/main/java/water/api/FramesHandler.java
h2o-core/src/main/java/water/api/schemas3/FramesListV3.java
h2o-core/src/main/java/water/api/schemas3/FramesV3.java
h2o-core/src/main/resources/META-INF/services/water.api.Schema

https://0xdata.atlassian.net/browse/PUBDEV-5724
In Java `H2oAPI` class, `FrameBaseV3` is exposed instead of `FrameV3`, therefore it's not possible to get all the information about the frame.
The cause is that in `FramesV3` schema class we use `FrameBaseV3` as the storage of the frames.
The `BaseFrameV3` is parent of other representations of frames. If we assign child to this field, the Rest API will anyway send the data of the underlying object, therefore we get all information from `FrameV3` via Rest API from browser.
However when using the Java H2O Rest API, the generated class is using `FrameBaseV3` -> therefore that's why we can't see the full result there.
The ideal solution would be to separate handling of operations on a single frame and for example listing all frames. That would …

[PUBDEV-5724] Expose full frame into in Java H2ORestAPI

---

h2o-docs/src/product/data-science/algo-params/solver.rst
h2o-docs/src/product/data-science/glm.rst

- Coordinate Descent cannot be used when family=multinomial.

PUBDEV-5838: Update solver documentation

---

h2o-docs/src/product/data-science/algo-params/solver.rst
h2o-docs/src/product/data-science/glm.rst

- Coordinate Descent cannot be used when family=multinomial.

PUBDEV-5838-relwright: Update solver documentation

---

h2o-r/h2o-package/R/communication.R

Assigning whole header array discards any previously prepared headers.
I think the diff is pretty self-explanatory.
After this fix, the call to automl fails with following exception:
```
ERROR: Unexpected HTTP Status code: 400 Bad Request (url = https://steam.0xdata.loc:9999/ondrej_pk-test/99/AutoMLBuilder)
java.lang.IllegalArgumentException
[1] "java.lang.IllegalArgumentException: Field not found: 'keep_cross_validation_fold_assignment' on object water.automl.api.schemas3.AutoMLBuildSpecV99$AutoMLBuildControlV99@277213f4"
[2] "    water.util.PojoUtils.fillFromMap(PojoUtils.java:653)"                                                                                                                          
[3] "    water.util.PojoUtils.fillFromMap(PojoUtils.java:623)" …
```

PUBDEV-5803 fixed bug in setting http headers

---

h2o-algos/src/main/java/hex/glrm/GLRMGenX.java
h2o-algos/src/main/java/hex/glrm/GLRMModel.java
h2o-genmodel/src/main/java/hex/genmodel/algos/glrm/GlrmMojoModel.java
h2o-genmodel/src/main/java/hex/genmodel/algos/glrm/GlrmMojoReader.java
h2o-genmodel/src/main/java/hex/genmodel/utils/ParseUtils.java
h2o-genmodel/src/test/java/hex/genmodel/utils/ParseUtilsTest.java
h2o-py/tests/pyunit_utils/utilsPY.py
h2o-py/tests/testdir_javapredict/pyunit_pubdev_5826_glrm_predict_large.py

Due to the fact that during training, glrm performs alternating updates between X and Y and during mojo scoring, it only performs updates of X and skipping the Y, the X factors generated are different.
I have implemented a small optimization which will return the X updates with the alpha that produces the best objective function improvement.

Pubdev 5826 glrm predict mojo mismatch

---

h2o-dist/index.html
h2o-docs/src/product/downloading.rst
h2o-docs/src/product/getting-data-into-h2o.rst
h2o-r/h2o-package/pkgdown/_pkgdown.yml

Noted that currently only Hive 2.2 is supported. Will update this when 2.1 support is added.
Driveby fixes:
- Fixed formatting for installing colorama in docs and on the download site.
- alphabetized new r function.

PUBDEV-5836: Doc update to Hive2 JDBC section

---

h2o-dist/index.html
h2o-docs/src/product/downloading.rst
h2o-docs/src/product/getting-data-into-h2o.rst
h2o-r/h2o-package/pkgdown/_pkgdown.yml

Noted that currently only Hive 2.2 is supported. Will update this when 2.1 support is added.
Driveby fixes:
- Fixed formatting for installing colorama in docs and on the download site.
- Alphabetized new r function.

PUBDEV-5836-relwright: Doc update to Hive2 JDBC section (rel-wright)

---

h2o-persist-http/src/main/java/water/persist/PersistHTTP.java
h2o-persist-http/src/test/java/water/persist/PersistHTTPTest.java

We need to make the HEAD request to find out the size of the file with the same headers as when we get the actual data.
The issue was we were getting the compressed size of the file but then reading the uncompressed chunks.

PUBDEV-5847: H2O parses only a part of a file when reading from compressed HTTP

---

h2o-core/src/main/java/water/fvec/NewChunk.java
h2o-core/src/main/java/water/parser/FVecParseWriter.java
h2o-core/src/test/java/water/parser/FVecParseWriterTest.java

Affects binary parsers: Parquet, ORC and Avro

PUBDEV-5792: Parsing large numbers (2E19) can cause the parser to hang

---

h2o-core/src/main/java/water/rapids/ast/prims/mungers/AstFillNA.java
h2o-core/src/test/java/water/rapids/ast/prims/advmath/AstFillNATest.java

https://0xdata.atlassian.net/browse/PUBDEV-5851

PUBDEV-5851: AstFillNA Rapids expression should throw H2O.unimp() on backward method [wright]

---

h2o-algos/src/main/java/hex/tree/TreeHandler.java
h2o-r/h2o-package/R/models.R
h2o-r/tests/testdir_jira/runit_pubdev_5735.R

Note there is one another bug fixed in this PR. Before, when the compression has been introduced, only the left categorical levels were sent. Levels of the other node were guessed by setdiff. This approach is **wrong**. Not the rest of the domain may always go to the other node. Because of earlier splits, some categorical levels may not even appear on this very node.
Temporarily, categorical levels are sent (still in the compressed format) for both nodes when the split is categorical. This is fixable on the client as well, yet the client code needs to be familiar with the path and exclude categorical levels that went elsewhere on the path. This is tightly coupled with tree walking mechanism, so I suggest to do this enhancement with rolling out the tree walker.

PUBDEV-5735 - Descriptions contain information about split on current node and heritage of its parent (master

---

h2o-r/h2o-package/R/automl.R
h2o-r/tests/testdir_algos/automl/runit_automl_multiple_runs.R

https://0xdata.atlassian.net/browse/PUBDEV-5848
- R API: avoid naming conflicts when creating destination frame for automl leaderboard.

PUBDEV-5848: error when manipulating previous AutoML leaderboard after multiple runs

---

h2o-algos/src/main/java/hex/deepwater/DeepWaterModel.java
h2o-core/src/main/java/hex/Model.java
h2o-extensions/xgboost/src/main/java/hex/tree/xgboost/XGBoost.java
h2o-extensions/xgboost/src/main/java/hex/tree/xgboost/XGBoostModel.java
h2o-extensions/xgboost/src/main/java/hex/tree/xgboost/XGBoostMojoWriter.java
h2o-extensions/xgboost/src/main/java/hex/tree/xgboost/XGBoostOutput.java
h2o-extensions/xgboost/src/main/java/hex/tree/xgboost/XGBoostUtils.java
h2o-extensions/xgboost/src/main/java/ml/dmlc/xgboost4j/java/XGBoostModelInfo.java
h2o-extensions/xgboost/src/main/java/ml/dmlc/xgboost4j/java/XGBoostScoreTask.java
h2o-extensions/xgboost/src/main/java/ml/dmlc/xgboost4j/java/XGBoostUpdateTask.java
h2o-extensions/xgboost/src/main/java/ml/dmlc/xgboost4j/java/XGBoostUpdater.java
h2o-genmodel-extensions/xgboost/src/main/java/hex/genmodel/algos/xgboost/XGBoostMojoModel.java
h2o-genmodel-extensions/xgboost/src/main/java/hex/genmodel/algos/xgboost/XGBoostNativeMojoModel.java
h2o-genmodel-extensions/xgboost/src/main/java/ml/dmlc/xgboost4j/java/BoosterHelper.java

This PR reworks Booster's lifecycle in XGBoost training. The previous implementation didn't explicitly dispose of the XGBoost training matrix and allowed to leak the Booster.
With this change: booster is only "live" during training or scoring. There is no native memory allocated after the model training is completed. The booster needs to be deserialized when the users want to predict.
This PR also fixes a hidden issue: when BigScore is used it was scoring per-row - that is super slow! I modified XGBoost to utilize bulk(=per chunk) scoring. This makes scoring CV models faster and allows to use XGBoost efficiently in Stacked Ensembles and AutoML.

PUBDEV-5841: Properly dispose all XGBoost native memory

---

h2o-algos/src/main/java/hex/tree/TreeHandler.java
h2o-algos/src/test/java/hex/tree/TreeHandlerTest.java

https://0xdata.atlassian.net/browse/PUBDEV-5878
TreeHandler class receives a model from the client. The model should be validated to be instance of SharedTreeModel in order to avoid ClassCastException when this method is called on a model that is not backed by a tree.
In R, this will result in 
```R
Error in .h2o.doSafeREST(h2oRestApiVersion = h2oRestApiVersion, urlSuffix = page,  : 
ERROR MESSAGE:
Given model is not tree-based.
```
master: https://github.com/h2oai/h2o-3/pull/2813

PUBDEV-5878 - TreeHandler model validation (rel-wright)

---

h2o-algos/src/main/java/hex/tree/TreeHandler.java
h2o-algos/src/test/java/hex/tree/TreeHandlerTest.java

https://0xdata.atlassian.net/browse/PUBDEV-5878
TreeHandler class receives a model from the client. The model should be validated to be instance of SharedTreeModel in order to avoid ClassCastException when this method is called on a model that is not backed by a tree.
In R, this will result in
```R
Error in .h2o.doSafeREST(h2oRestApiVersion = h2oRestApiVersion, urlSuffix = page,  : 
ERROR MESSAGE:
Given model is not tree-based.
```
rel-wright: https://github.com/h2oai/h2o-3/pull/2812

PUBDEV-5878 - TreeHandler model validation (master)

---

h2o-extensions/xgboost/src/main/java/hex/tree/xgboost/XGBoostModel.java
h2o-extensions/xgboost/src/main/java/ml/dmlc/xgboost4j/java/PredictorFactory.java
h2o-extensions/xgboost/src/main/java/ml/dmlc/xgboost4j/java/XGBoostRegTree.java
h2o-extensions/xgboost/src/test/java/hex/tree/xgboost/XGBoostTest.java
h2o-genmodel-extensions/xgboost/build.gradle
h2o-genmodel-extensions/xgboost/src/main/java/hex/genmodel/algos/xgboost/XGBoostMojoModel.java

This change provides an experimental Java implementation of predict() for XGBoost models.
It uses a modified xgboost-predictor and adds high-perf scoring of RegTrees.
This is a first step. Next steps will be to
- use java scoring for scoring during model training,
- use prediction cache to scoring with each tree exactly once (same way as we do in GBM).

PUBDEV-5888: Use custom implementation to score XGBoost regression trees

---

h2o-automl/src/main/java/ai/h2o/automl/AutoML.java
h2o-py/tests/testdir_algos/automl/pyunit_automl_memory_cleanup.py

https://0xdata.atlassian.net/browse/PUBDEV-5824
- removed previous SEs from the list of Best of Family models to be able to compute new SE model

PUBDEV-5824: AutoML fails training new BestofFamily SE model on multiple runs

---

docker/Dockerfile.jenkins
docker/scripts/install_java_version
h2o-algos/testMultiNode.sh
h2o-algos/testSSL.sh
h2o-algos/testSingleNode.sh
h2o-algos/testSingleNodeOneProc.sh
h2o-core/testClientNode.sh
h2o-core/testMultiNode.sh
h2o-extensions/jython-cfunc/testMultiNode.sh
h2o-extensions/jython-cfunc/testSingleNode.sh
h2o-extensions/xgboost/testMultiNode.sh
h2o-extensions/xgboost/testSingleNode.sh
h2o-parsers/h2o-avro-parser/testMultiNode.sh
h2o-parsers/h2o-orc-parser/testMultiNode.sh
h2o-parsers/h2o-parquet-compat/h2o-parquet-v17-compat/testMultiNode.sh
h2o-parsers/h2o-parquet-parser/testMultiNode.sh
h2o-persist-gcs/testMultiNode.sh
h2o-persist-hdfs/testMultiNode.sh
h2o-persist-http/testMultiNode.sh
h2o-persist-s3/testMultiNode.sh
h2o-scala/testMultiNode.sh
scripts/jenkins/Makefile.jenkins
scripts/jenkins/groovy/buildConfig.groovy
scripts/jenkins/groovy/defineTestStages.groovy

Added new environment variable `ADDITIONAL_TEST_JVM_OPTS` to all `test*Node.sh`. It holds the additional JVM options used when starting the JVM.

[ITA-337] Java 11 Smoke tests.

---

h2o-docs/src/product/productionizing.rst
h2o-genmodel/src/main/java/overview.html

- Added note in User Guide and Javadoc that MOJOs are only supported for categorical that are default or enum.
- In User Guide, moved “Benefits” paragraphs from FAQ into a separate subsection to make it more prominent.

PUBDEV-5910: Doc update to MOJOs (rel-wright branch)

---

h2o-docs/src/product/mojo-quickstart.rst
h2o-genmodel/src/main/java/overview.html

- Added note in User Guide and Javadoc that MOJOs are only supported for categorical that are default or enum.
- In User Guide, moved “Benefits” paragraphs from FAQ into a separate subsection to make it more prominent.

PUBDEV-5910: Doc update to MOJOs

---

h2o-core/src/main/java/water/H2O.java
scripts/jenkins/Makefile.jenkins

We don't want to allow any java version, instead we want to have a whitelist of user-approved java versions.

Explicitly allow just Java 11 in junit builds

---

README.md

If you read README.md top down and already have dependencies installed (like me), you can easily build the project just by reading sections 4.1 and 4.2. (without R hint initial build fails).

PUBDEV-5913: Adding missing R package prerequisites hint to README.md

---

h2o-core/src/main/java/water/parser/BufferedString.java
h2o-core/src/main/java/water/parser/CharSkippingBufferedString.java
h2o-core/src/main/java/water/parser/CsvParser.java
h2o-core/src/main/java/water/parser/Parser.java
h2o-core/src/test/java/water/parser/CharSkippingBufferedStringTest.java
h2o-core/src/test/java/water/parser/CsvParserTest.java
h2o-core/src/test/java/water/parser/ParserTest2.java
h2o-py/tests/testdir_parser/pyunit_csv_parser.py

https://0xdata.atlassian.net/browse/PUBDEV-5855
Started JUNIT testing of CSV parser. Tested the very case reported. The fix is general - there must be a separator or line terminator after a quote to end a string.
In the second commit, there is Python test parsing basic datasets. The test is very quick and gives us the certainty of basic CSV datasets being parsed with correct number of rows.

PUBDEV-5855 - Error when parsing double quotations in a column (rel-wright)

---

h2o-core/src/main/java/water/AbstractHTTPD.java
h2o-core/src/main/java/water/H2O.java

Large requests (>8Kb) are rejected by Jetty response 413: `Request
Entity Too Large: heada`.
This change includes:
- bump request header size from 6k to 32k
- bump request buffer size from 16k to 32k
- enable configuration of request/response headers&buffers via system
properties.

[PUBDEV-5939] Enable configuration of buffers for http/https connection [wright]

---

h2o-py/build.gradle
h2o-py/setup.py
make-dist.sh
scripts/install-clients.sh
scripts/jenkins/Makefile.jenkins
scripts/jenkins/PR_startup_checks.sh
scripts/jenkins/groovy/defaultStage.groovy

Build the Python package inside `h2o-py/build` directory. The idea is to keep the source files intact, and do everything build related in the `build` directory.

[ITA-344] Build Python package under h2o-py/build/.

---

h2o-core/src/main/java/water/AbstractHTTPD.java
h2o-core/src/main/java/water/H2O.java

Large requests (>8Kb) are rejected by Jetty response 413: `Request
Entity Too Large: heada`.
This change includes:
- bump request header size from 6k to 32k
- bump request buffer size from 16k to 32k
- enable configuration of request/response headers&buffers via system
properties.

[PUBDEV-5939] Enable configuration of buffers for http/https connection.

---

h2o-algos/src/main/java/hex/glm/ComputationState.java
h2o-algos/src/main/java/hex/glm/GLM.java
h2o-algos/src/main/java/hex/glm/GLMTask.java
h2o-algos/src/test/java/hex/glm/GLMBasicTestBinomial.java
h2o-algos/src/test/java/hex/glm/GLMBasicTestMultinomial.java
h2o-algos/src/test/java/hex/glm/GLMBasicTestOrdinal.java
h2o-algos/src/test/java/hex/glm/GLMTest.java
h2o-py/tests/pyunit_utils/utilsPY.py

Speed up COD operation by:
- Removed redundant gram.getXX() action.
- separate fitCOD for binomial and multinomial from fitIRLSM.
- in multinomial COD, will not calculate gradients since it is not used.
Added junit
-  to compare GLM COD and theoretically correct (but slow) coefficient update to make sure our approximation is not harmful to performance.
- compare GLM coefficients obtained before my change and against my change.  They should agree.

PUBDEV-5856 GLM multinomial COD implementation check

---

h2o-core/src/main/java/water/parser/ARFFParser.java
h2o-core/src/main/java/water/parser/CsvParser.java
h2o-core/src/main/java/water/parser/DefaultParserProviders.java
h2o-core/src/main/java/water/util/ArrayUtils.java
h2o-core/src/test/java/water/parser/ParserTestARFF.java

https://0xdata.atlassian.net/browse/PUBDEV-5919
- change ARFF guess setup logic to loop through the dataset chunks as soon as the chunk looks like a valid part of the ARFF header and until the @data segment.

PUBDEV-5919: ARFF File Import fails if header is too large (>4MB)

---

h2o-core/src/main/java/water/rapids/BinaryMerge.java
h2o-core/src/main/java/water/rapids/Merge.java
h2o-core/src/test/java/water/rapids/ast/prims/mungers/AstMergeTest.java
h2o-py/tests/pyunit_utils/utilsPY.py
h2o-py/tests/testdir_munging/pyunit_PUBDEV_5924_merge_bug_large.py

This PR fixes JIRA: https://0xdata.atlassian.net/browse/PUBDEV-5924?filter=-1
Andrey found the following merge bug:
If there is a NaN in the right frame merge column, it will be included in the final merged frame.  However, this should not be the case.  Any rows in the right frame that contains NaN in the merge columns should be removed.
In this PR, I fixed this problem by going through the right frame and delete all rows with NaN in the merged columns. 
I have written a Junit unit test to verify that the bug exposed by Andrey is no longer there.
I wrote a longer pyunit test for large datasets to make sure that merge values found in one frame but not the other should be filled with NaN/null.  I checked and made sure that this is true for all.x=True, and all.y=True.

PUBDEV-5924: Fixed merge bug where rows without merge key should be NaN or null

---

h2o-core/src/main/java/water/parser/CsvParser.java
h2o-core/src/test/java/water/parser/CsvParserTest.java
h2o-core/src/test/java/water/parser/ParserTest2.java
h2o-core/src/test/java/water/parser/ParserTestARFF.java

https://0xdata.atlassian.net/browse/PUBDEV-5971
CSV/Arff parser: keep the state machine in POSSIBLE_EMPTY_LINE state until a separator or token is reached

PUBDEV-5971: CSV/ARFF Parser handles blank lines as data lines with NAs

---

h2o-core/src/main/java/water/util/Log.java

The property h2o.log4j.properties allowed to specify location of
log4j.properties, however, it ignored situation when the file is bundled
with application (example, MLI app).
This patch allows to specify location of log4j.properties file which is
in jar-file.
For example:
When i bundle `log4j.properties` in my `my-h2o-app.jar` in directory `conf` and would like
to enable them at runtime, i can point to in the following way:
```
java -cp my-h2o-app.jar -Dh2o.log4j.configuration=conf/log4j.properties water.H2OApp
```

[PUBDEV-5938] Enable loading log4j.properties from classpath

---

h2o-automl/build.gradle
h2o-automl/src/main/java/ai/h2o/automl/Algo.java
h2o-automl/src/main/java/ai/h2o/automl/AutoML.java
h2o-automl/src/main/java/water/automl/api/schemas3/AutoMLBuildSpecV99.java
h2o-automl/src/test/java/ai/h2o/automl/AutoMLTest.java
h2o-core/src/main/java/hex/ModelBuilder.java
h2o-core/src/main/java/water/api/EnumValuesProvider.java
h2o-core/src/main/java/water/util/PojoUtils.java
h2o-docs/src/product/automl.rst
h2o-py/tests/testdir_algos/automl/pyunit_automl_leaderboard.py
h2o-py/tests/testdir_algos/automl/pyunit_automl_memory_cleanup.py
h2o-r/tests/testdir_algos/automl/runit_automl_leaderboard.R
h2o-r/tests/testdir_algos/automl/runit_automl_sort_metric.R

https://0xdata.atlassian.net/browse/PUBDEV-4507
- tuned 3 default XGBoost models for small to larger datasets.
- added them before existing default GBMs.
- added XGBoost hyperparam search before GBM one.
- based on XGBoost, added experimental support for emulated LightGBM (currently disabled as I expected faster perf according to https://lightgbm.readthedocs.io/en/latest/Experiments.html#result)
- orchestration of various hyperparam searches to ensure that one is not monopolising resources (remaining models + time), and ensure we have a balance between XGB, GBM and DL.

PUBDEV-4507: XGBoost integration to AutoML

---

.editorconfig

The codebase contains a lot of java, python and R sources that is often hard to read, for variety of reasons.
One day, it would be nice to prettify, and maybe even refactor these sources, but it's unlikely to happen anytime soon.
But there are still simple ways that have zero cost and can help us with, at least, avoiding some of the problems to *spread and grow*. One such helper is EditorConfig - [read about it here](http://EditorConfig.org).
This tool configures very simple rules telling how code editors should handle files - line endings, trailing spaces, final newline, and primarily: *indentation*.
And yes, current state of indentation is very annoying. When we try to contribute minimalistic changes, and want the new code to be properly indented, and place the new code into something …

added EditorConfig metafile to reduce growth of the indentation mess

---

h2o-algos/src/main/java/hex/tree/CompressedTree.java
h2o-algos/src/main/java/hex/tree/DTree.java
h2o-algos/src/main/java/hex/tree/SharedTreeModel.java
h2o-algos/src/main/java/hex/tree/SharedTreeMojoWriter.java
h2o-algos/src/main/java/hex/tree/TreeVisitor.java
h2o-algos/src/main/java/hex/tree/drf/DRF.java
h2o-algos/src/main/java/hex/tree/gbm/GBM.java
h2o-algos/src/test/java/hex/tree/CompressedTreeTest.java
h2o-genmodel/src/main/java/hex/genmodel/algos/tree/ScoreTree.java
h2o-genmodel/src/main/java/hex/genmodel/algos/tree/ScoreTree0.java
h2o-genmodel/src/main/java/hex/genmodel/algos/tree/ScoreTree1.java
h2o-genmodel/src/main/java/hex/genmodel/algos/tree/ScoreTree2.java
h2o-genmodel/src/main/java/hex/genmodel/algos/tree/SharedTreeMojoModel.java
h2o-genmodel/src/test/java/hex/genmodel/algos/tree/SharedTreeMojoModelTest.java

The `_nclass` field/parameter has no effect during traversal of compressed trees, so this patch eliminates it where possible.
No functionality should be impacted at all. The only goal here is to remove dead code and increase readability. Performance improvement is possible, but unlikely measurable.
As part of these changes, a line like following is removed from all `scoreTree*` methods (and other tree traversals):
```java
...
case 16: ab.skip(nclasses < 256? 1 : 2);  break;  // Small leaf
...
```
In all cases, this line is unreachable - or more precisely, only reachable by traversing invalid binary mojo tree.
To prove this statement, let's see the result of extensive jenkins tests.

PUBDEV-5996: Eliminate unused param "nclasses" from mojo traversal code

---

h2o-core/src/main/java/water/api/ImportSQLTableHandler.java
h2o-core/src/main/java/water/api/schemas3/ImportSQLTableV99.java
h2o-core/src/main/java/water/jdbc/SQLManager.java
h2o-core/src/main/java/water/jdbc/SqlFetchMode.java
h2o-core/src/main/java/water/util/EnumUtils.java
h2o-core/src/test/java/water/jdbc/SQLManagerIntegTest.java
h2o-core/src/test/java/water/parser/ImportSQLTest.java
h2o-hadoop/tests/python/pyunit_gbm_on_hive.py
h2o-py/h2o/h2o.py
h2o-r/h2o-package/R/import.R

Introduces a new mode of data ingests compatible with a vast majority
of JDBC data sources. Instead of trying to do distributed ingest streams
all data through a single H2O node. The source database doesn't need to
support OFFSET-like clauses. The original intent was to support reading
from Hive 1.2.x.
Chunks are compressed and distributed to H2O nodes asynchronously.

PUBDEV-5927: Streaming ingest from JDBC datasources

---

h2o-web/bower.json

[PUBDEV-6005] added XGBoost to list of algos that can be excluded in Flow.

---

h2o-core/src/main/java/water/ExtensionManager.java
h2o-core/src/main/java/water/H2O.java
h2o-core/src/main/java/water/JettyHTTPD.java
h2o-core/src/main/java/water/server/RequestAuthExtension.java

This replaces the ad-hoc code using inner class `ExtensionHandler1` and method `handler1()`.
This is to support the PR #2938 , and is supposed to be merged before it.

PUBDEV-5820: Introduced composition-based extension mechanism for servlet handlers

---

h2o-r/h2o-package/R/connection.R

Custom print at the beginning to demonstrate what was going on in the args really. The print is not part of the committed code.
```
> h2o.init(jvm_custom_args = "-XX:+PrintGCDetails")
H2O is not running yet, starting it now...
[1] "-ea"                 "-XX:+PrintGCDetails"
Note:  In case of errors look at the following log files:
/tmp/RtmpP2Mq4p/h2o_pavel_started_from_r.out
/tmp/RtmpP2Mq4p/h2o_pavel_started_from_r.err
java version "1.8.0_181"
Java(TM) SE Runtime Environment (build 1.8.0_181-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.181-b13, mixed mode)
Starting H2O JVM and connecting: . Connection successful!
R is connected to the H2O cluster: 
H2O cluster uptime:         918 milliseconds 
H2O cluster timezone:       Europe/Prague 
H2O data parsing timezone:  UTC 
H2O cluster …
```

Fixed ignored custom JVM args in R client when starting new JVM.

---

h2o-automl/src/main/java/ai/h2o/automl/AutoML.java
h2o-docs/src/product/automl.rst

https://0xdata.atlassian.net/browse/PUBDEV-6000
This improves the model performance of AutoML in most cases due to the additional training data.  We don't need 20% of the training data just for early stopping purposes.
Includes correponding edits to [AutoML user guide](https://github.com/h2oai/h2o-3/blob/master/h2o-docs/src/product/automl.rst)

PUBDEV-6000: AutoML auto-split frame from 80/20 to 90/10

---

h2o-py/docs/tree.rst

Creating another pull requests. This uses:
Tree Class in H2O
=================
:mod:`H2O Tree Class`
-------------------------------
.. autoclass:: h2o.backened.H2OTree
:members:
:undoc-members:
:show-inheritance:

PUBDEV-5949: Second attempt at adding Tree to python docs

---

h2o-core/src/main/java/water/AutoBuffer.java
h2o-core/src/main/java/water/FetchClazzes.java

Fixes an issue when a model is exported by an H2O node that didn't participate in the model building (typical the client node or a case of a small dataset stored on a single node of a multinode cluster). This node might not have some classes in its TypeMap (eg. CompressedTrees for GBM). We need to use the leader's TypeMap when exporting the model because this TypeMap is always authoritative for the whole cluster.
What happens is: when the client writes the binary model it writes its own TypeMap to the exported file first. Then the keys are being fetched from the nodes and if the client doesn't have the class in its own TypeMap it fetches it from the Leader. So the typemap gets updated on the fly after it was already written to the file. The fix is to fetch the typemap from the leader …

Fix model export issue

---

h2o-core/src/main/java/water/AbstractHTTPD.java
h2o-core/src/main/java/water/DelegatingAuthenticator.java
h2o-core/src/main/java/water/H2O.java
h2o-core/src/main/java/water/JettyHTTPD.java
h2o-core/src/main/java/water/api/DatasetServlet.java
h2o-core/src/main/java/water/api/NpsBinServlet.java
h2o-core/src/main/java/water/api/PostFileServlet.java
h2o-core/src/main/java/water/api/PutKeyServlet.java
h2o-core/src/main/java/water/api/RequestServer.java
h2o-core/src/main/java/water/init/NetworkInit.java
h2o-core/src/main/java/water/server/ServletUtils.java
h2o-core/src/main/java/water/util/FileUtils.java
h2o-core/src/main/java/water/util/JStackCollectorTask.java
h2o-hadoop/h2o-mapreduce-generic/src/main/java/water/JettyProxy.java
h2o-hadoop/h2o-mapreduce-generic/src/main/java/water/ProxyStarter.java

This is part of the effort to isolate support for Jetty 8 and add support for other versions, namely Jetty 9.
In this step, the generic code (= code actually not dependent on Jetty library) is moved to a separate class `ServletUtils`, mostly from class `JettyHTTPD`. The rest of changes is basically fixing references.
The reason is, that isolation of Jetty 8 which originally included this (see #2976) causes mysterious errors in `testMultiNode.sh`. So this is an attempt to make even smaller step, and get some more confidence that the changes are harmless.

PUBDEV-5820: Prepare Jetty-dependent classes for isolation

---

h2o-py/h2o/backend/connection.py
h2o-py/h2o/backend/server.py
h2o-py/h2o/h2o.py
h2o-py/tests/testdir_apis/H2O_Module/pyunit_h2oinit.py
h2o-r/h2o-package/R/classes.R
h2o-r/h2o-package/R/communication.R
h2o-r/h2o-package/R/connection.R

Adds the option to specify `cloud_name` in the `h2o.init()` methods in Python and R. Main motivation is because we are using the `-name` parameter in MLI and would like to move from bootstrapping via `java -jar h2o.jar` to `h2o.init()` calls.
Proposed logic:
* If there is an instance under given address:port with the same cloud name - connect as normal
* If there is an instance with a different cloud name - fail in case of R, in case of Python fail if port passed explicitly and as_port=True passed, otherwise try to bootstrap on consecutive ports
* If no instance then try to start an H2O-3 instance using name as cloud name.
Added also `as_port` to the `kwargs` so the `port` argument acts like the actual `-port` parameter instead of `-base_port`. 
Comments?
I also would like to add the …

Adds name parameter to Python and R init methods

---

h2o-core/build.gradle
h2o-core/src/main/java/water/server/Credentials.java
h2o-hadoop/h2o-mapreduce-generic/src/main/java/water/JettyProxy.java
h2o-hadoop/h2o-mapreduce-generic/src/main/java/water/ProxyStarter.java
h2o-hadoop/h2o-mapreduce-generic/src/main/java/water/hadoop/h2odriver.java

It will later be shared by multiple implementations of the `H2OServletContainerFacade`, i.e. by Jetty 8 and Jetty 9 support.
This is yet another independent piece of the PUBDEV-5820 task, helping to keep the [remaining part]( https://github.com/h2oai/h2o-3/pull/2976) of Jetty 8 isolation change as small as possible.

PUBDEV-5820: extracted class Credentials out of JettyProxy

---

h2o-bindings/src/main/java/water/bindings/examples/Example.java
h2o-core/src/main/java/water/api/ParseHandler.java
h2o-core/src/main/java/water/api/ParseSetupHandler.java
h2o-core/src/main/java/water/api/schemas3/ParseSetupV3.java
h2o-core/src/main/java/water/api/schemas3/ParseV3.java
h2o-core/src/main/java/water/parser/CsvParser.java
h2o-core/src/main/java/water/parser/FVecParseWriter.java
h2o-core/src/main/java/water/parser/ParseDataset.java
h2o-core/src/main/java/water/parser/ParseSetup.java
h2o-core/src/main/java/water/parser/Parser.java
h2o-core/src/main/java/water/parser/SVMLightFVecParseWriter.java
h2o-py/h2o/frame.py
h2o-py/h2o/h2o.py
h2o-py/tests/pyunit_utils/utilsPY.py
h2o-py/tests/testdir_parser/pyunit_PUBDEV_5705_drop_columns_parser_csv_large.py
h2o-r/h2o-package/R/import.R
h2o-r/h2o-package/R/parse.R
h2o-r/tests/runitUtils/utilsR.R
h2o-r/tests/testdir_parser/runit_PUBDEV_5705_drop_columns_parser_csv_large.R

This PR completes part of the work for JIRA: https://0xdata.atlassian.net/projects/PUBDEV/issues/PUBDEV-5705?filter=myopenissues.
I have done the following:
1. added skipped_column support for csv parser;
2. added client interface in R and Python;
3. added R/Python tests.
The most heavy duty work is in CsvParser.java.
=======================================================================
Tips for code review:
To enable skipping columns during parse, introduced two parameters to ParseSetup.java
_skipped_columns (int[] with inputs from user listing column indices to skip)
_parse_columns_indices (int[] representing columns indices to be included in the final frame). Size of this array is number of columns in file minus number of skipped columns.
Added one parameter to parser.java
boolean[] …

PUBDEV-5705: added skipped column to csv parsers

---

build.gradle
h2o-hadoop/assemblyjar.gradle
settings.gradle

We use just the shadow JAR. The `jar` provided by `java` plugin is generated and never used. Less artifacts and should also speed the build a bit

Eliminate generating another extra jar which is not used for each h2o-hadoop

---

h2o-core/src/test/java/water/TestUtil.java
h2o-core/src/test/java/water/parser/ParseFolderTest.java
h2o-core/src/test/java/water/parser/ParserTestARFF.java
h2o-py/h2o/h2o.py
h2o-py/tests/pyunit_utils/utilsPY.py
h2o-py/tests/testdir_parser/pyunit_PUBDEV_5705_drop_columns_high_enums_large.py
h2o-py/tests/testdir_parser/pyunit_PUBDEV_5705_drop_columns_import_folder.py
h2o-py/tests/testdir_parser/pyunit_PUBDEV_5705_drop_columns_parser_arff_large.py
h2o-r/h2o-package/R/parse.R
h2o-r/tests/testdir_parser/runit_PUBDEV_5705_drop_columns_import_folder.R
h2o-r/tests/testdir_parser/runit_PUBDEV_5705_drop_columns_parser_arff_large.R

This PR is related to JIRA: https://0xdata.atlassian.net/browse/PUBDEV-5705?filter=-1
It completes the following:
1. Added tests to verify that columns can be skipped with ARFF files in R and Python.
2. Added skip column capability to parse_test_file in testUtils.java.  This is mainly for testing only.
In addition, more tests are added to:
1. Verify that skipped columns are supported correctly when importing folders in Java/R/Python.
2. Test pyunit_PUBDEV_5705_drop_columns_high_enums_large.py contains columns with cardinality > 10000000.  When the column with high cardinality is skipped, the file was parsed successfully.

PUBDEV-5705: add skip column support to ARFF parser.

---

h2o-parsers/h2o-parquet-parser/src/main/java/water/parser/parquet/ChunkConverter.java
h2o-parsers/h2o-parquet-parser/src/main/java/water/parser/parquet/ChunkReadSupport.java
h2o-parsers/h2o-parquet-parser/src/main/java/water/parser/parquet/ChunkRecordMaterializer.java
h2o-parsers/h2o-parquet-parser/src/main/java/water/parser/parquet/ParquetParser.java
h2o-parsers/h2o-parquet-parser/src/main/java/water/parser/parquet/ParquetParserProvider.java
h2o-parsers/h2o-parquet-parser/src/main/java/water/parser/parquet/VecParquetReader.java
h2o-py/tests/testdir_parser/pyunit_PUBDEV_5705_drop_columns_parser_parquet_large.py
h2o-r/tests/testdir_parser/runit_PUBDEV_5705_drop_columns_parser_parquet_large.R

This PR covers work for JIRA: https://0xdata.atlassian.net/projects/PUBDEV/issues/PUBDEV-5705?filter=myopenissues
Added skip column support to Parquet parser.
Added Java/R/Python unit tests to verify correction operations.

PUBDEV-5705: add skipped column support to Parquet parser

---

h2o-core/src/main/java/hex/AUC2.java
h2o-core/src/main/java/hex/ModelMetrics.java
h2o-core/src/main/java/hex/ModelMetricsBinomial.java
h2o-core/src/test/java/hex/ModelMetricsTest.java

This PR makes sure the AUC2 object is created even in edge cases when the data have 0 total weight. This prevents possible NPEs.

PUBDEV-6046: Failed to get metric: auc from ModelMetrics type BinomialGLM

---

h2o-py/h2o/utils/shared_utils.py

`.as_matrix()` is being deprecated as documented [here](https://pandas.pydata.org/pandas-docs/stable/generated/pandas.DataFrame.as_matrix.html). Use `.values` instead.

PUBDEV-6052: Replace `.as_matrix()` with `.values` in shared_utils.py

---

h2o-core/src/main/java/hex/ScoreKeeper.java
h2o-core/src/main/java/water/api/schemas3/ModelParametersSchemaV3.java
h2o-py/h2o/estimators/deeplearning.py
h2o-py/h2o/estimators/deepwater.py
h2o-py/h2o/estimators/gbm.py
h2o-py/h2o/estimators/random_forest.py
h2o-py/h2o/estimators/xgboost.py
h2o-py/tests/testdir_algos/gbm/pyunit_custom_stopping.py
h2o-r/h2o-package/R/deeplearning.R
h2o-r/h2o-package/R/deepwater.R
h2o-r/h2o-package/R/gbm.R
h2o-r/h2o-package/R/randomforest.R
h2o-r/h2o-package/R/xgboost.R

@angela0xdata the issue with PR is that custom metric is only allowed for DRF/GBM & GLM but I cannot have different early stopping metrics for each algo. That means stopping_criteria = custom is available everywhere even though it is not actually supported.
I will need to add some checks to the source code.
I am adding 2 new stopping criteria:
- custom - for custom metric functions where "less is better", it is expected that the lower bound is 0
- custom_increasing  - for custom metric functions where "more is better"

PUBDEV-5261: Allow custom_metric to be used for early stopping

---

h2o-core/src/test/java/water/jdbc/SQLManagerIntegTest.java
h2o-core/src/test/java/water/jdbc/SQLManagerTest.java

Little cleanup to reduce source tree polution caused by JDBC test execution:
- `derby.log` is now created inside `build` directory
- derby databases are created in a temporary folder, also under `build` directory
- each DB testsuite uses its own database name, to reduce influence between the tests

JDBC test improvement - keep derby tempfiles inside build

---

h2o-r/h2o-package/R/parse.R
h2o-r/tests/runitUtils/utilsR.R
h2o-r/tests/testdir_parser/runit_PUBDEV_5705_drop_columns_parser_column_names_types_large.R

Fixed bug in R API:
- assign column types to all columns.
- shorten test to test either importFile or uploadFile but not both.

Fix PUBDEV_5705_drop_columns_parser_column_names_types_large.R test failure

---

h2o-py/tests/testdir_jira/pyunit_pubdev_5049.py

This PR is supposed to show that user provided validation frame doesn't have an effect on early stopping when cross validation is used to train a GBM model

PUBDEV-5049: Demonstrate effect of validation frame on early stopping in CV

---

h2o-docs/src/product/data-science/algo-params/max_depth.rst
h2o-docs/src/product/data-science/algo-params/sample_size.rst
h2o-docs/src/product/data-science/drf.rst
h2o-docs/src/product/data-science/gbm.rst
h2o-docs/src/product/data-science/if.rst
h2o-docs/src/product/parameters.rst
h2o-r/h2o-package/pkgdown/_pkgdown.yml

Note that the default value for max_depth in Isolation Forest is 8.
Driveby fixes:
- Added defauilt values for sample_size and sample_rate.
- Added a parameter description entry for sample_size.
- Fixed location of isolation_forest in the R HTML documentation (alphabetize).

PUBDEV-6064: Add default value for max_depth in IsoFor

---

h2o-core/src/main/java/hex/Model.java
h2o-core/src/main/java/water/util/FileUtils.java
h2o-extensions/xgboost/src/main/java/hex/tree/xgboost/XGBoost.java
h2o-extensions/xgboost/src/main/java/ml/dmlc/xgboost4j/java/XGBoostUpdater.java
h2o-persist-hdfs/src/main/java/water/persist/PersistHdfs.java

While attempting to reproduce https://0xdata.atlassian.net/browse/PUBDEV-5937, I came across two places in the code where error handling and logging should be more refined.
Goal is to provide better chance in future for us to decrypt errors from logs sent by users.
The first commit is unrelated to the JIRA issue. When saving a feature map, I believe we definitely want to log when closing the file fails, and not fail silently, as resources might hang.
As FileUtils.close() method was used and this particular method closes the file sliently, I changed the existing close() method's name to `closeSilently` and introduced a new one named `close`, which logs the error during the  closing operation. This way, it is even more readable and obvious in the code which method is doing what.
This is …

PUBDEV-5937 - XGBoost error handling changes

---

h2o-algos/src/main/java/hex/schemas/GLMModelV3.java
h2o-core/src/main/java/water/api/schemas3/TwoDimTableV3.java
h2o-py/tests/testdir_algos/glm/pyunit_PUBDEV_6062_multinomial_coeffNames.py
h2o-r/tests/testdir_algos/glm/runit_GLM_PUBDEV_6062_cat_coeff_names.R

This PR completes the work demanded in JIRA: https://0xdata.atlassian.net/browse/PUBDEV-6062?filter=-1.
Work done:
1. In Java backend, force coefficient name to contain the actual class name instead of 0, 1, 2,...
2. Added R/Python unit test to verify correct coefficient names are returned.

PUBDEV-6062: fix multinomial coefficient names

---

h2o-algos/src/test/java/hex/DataInfoTest.java
h2o-extensions/xgboost/src/main/java/hex/tree/xgboost/XGBoost.java
h2o-extensions/xgboost/src/main/java/hex/tree/xgboost/XGBoostModel.java
h2o-extensions/xgboost/src/main/java/ml/dmlc/xgboost4j/java/XGBoostModelInfo.java
h2o-extensions/xgboost/src/test/java/hex/tree/xgboost/XGBoostTest.java

Test runit_XGBoostRandomGrid_airlines_large.R is failing on NPE.
Caused by: java.lang.NullPointerException
at hex.DataInfo.coefNames(DataInfo.java:704)
at hex.tree.xgboost.XGBoostModel.setupBigScorePredictNative(XGBoostModel.java:465)
at hex.tree.xgboost.XGBoostModel.setupBigScorePredict(XGBoostModel.java:459)
at hex.Model$BigScore.setupLocal(Model.java:1572)

Fix NPE when DataInfo#coefNames are accessed in XGBoost on a deserialized instance

---

h2o-core/src/main/java/water/rapids/ast/prims/mungers/AstGroup.java
h2o-py/tests/testdir_munging/pyunit_groupby_types.py

**Problem:** 
The type of group_by column is changed to `int` even though there is `time` type before group by operation. The problem is the new calculated group by vectors are saved in the DKV with default type `int`. The original type is decoded from values in the vector to write it to a schema. But `timestamp` type is `int` by default and can't be easily decoded back to a `timestamp`. 
**Solution:** 
Don't use the default `int` type when the new vectors are created. Group by columns are not changed during calculation so that its type can be preserved.

PUBDEV-6076 keep timestamp format after group_by

---

h2o-core/src/main/java/water/AutoBuffer.java
h2o-core/src/main/java/water/ClientDisconnectCheckThread.java
h2o-core/src/main/java/water/ExternalFrameHandlerThread.java
h2o-core/src/main/java/water/ExternalFrameReaderClient.java
h2o-core/src/main/java/water/ExternalFrameWriterClient.java
h2o-core/src/main/java/water/FailedNodeWatchdogExtension.java
h2o-core/src/main/java/water/H2O.java
h2o-core/src/main/java/water/H2ONode.java
h2o-core/src/main/java/water/MRTask.java
h2o-core/src/main/java/water/Paxos.java
h2o-core/src/main/java/water/RPC.java
h2o-core/src/main/java/water/TCPReceiverThread.java
h2o-core/src/main/java/water/UDPClientEvent.java
h2o-core/src/main/java/water/util/JStackCollectorTask.java
h2o-core/src/test/java/water/AutoBufferTest.java
h2o-core/src/test/java/water/ClientReconnectSimulationTest.java
h2o-core/src/test/java/water/H2OTest.java
h2o-core/src/test/java/water/UnknownHeartbeatTest.java
h2o-extensions/xgboost/src/main/java/hex/tree/xgboost/rabit/communication/XGBoostAutoBuffer.java

This PR is for rel-xia to follow our current PR cycle, from https://github.com/h2oai/h2o-3/pull/3057.
Original comment:
The original issue was that when a client disconnected and connected to the cluster before the cluster discovered the original client is gone, it blocked the connection of the new client because of previously opened connections
This was caused by using the old client entry in the Client hash map as the cluster was still trying to  contact the old client on the old sockets. We need to make sure the new sockets are created.
In order to fix this, we needed to add a new entry the the `AutoBuffer` head. This entry contains the information whether the node is client and the unique id. This entry is of size 2 bytes to minimize to communication overhead. The 1. bit is info …

 [PUBDEV-5959] PySparking client is hanging after re-connecting to the H2O external backend

---

h2o-core/src/main/java/water/api/schemas3/ModelSchemaV3.java
h2o-py/tests/testdir_jira/pyunit_pubdev_5829_get_model_timestamp.py

During fill from implementation `fillFromImpl(...)` method in the ModelSchemaV3, timestamp assignment is missing. 
JIRA: https://0xdata.atlassian.net/browse/PUBDEV-5829

PUBDEV-5829 fix model schema V3

---

h2o-algos/src/test/java/hex/deeplearning/DeepLearningAutoEncoderCategoricalTest.java
h2o-algos/src/test/java/hex/deeplearning/DeepLearningAutoEncoderTest.java
h2o-genmodel/src/main/java/hex/genmodel/algos/deeplearning/DeeplearningMojoModel.java
h2o-genmodel/src/main/java/hex/genmodel/easy/EasyPredictModelWrapper.java
h2o-genmodel/src/main/java/hex/genmodel/easy/prediction/AutoEncoderModelPrediction.java

Edit `EasyPredictModelWrapper` to be able to calculate reconstruction error for autoencoder. Edit `DeepLearningAutoEncoderTest` to test if the error from model and mojo model is the same. 
Cherry pick [commit ](https://github.com/h2oai/h2o-3/pull/3102/commits/915ce9399ecee905ec764eb7b76150e48406a422) of @michalkurka, but find a slightly different solution.
JIRA: https://0xdata.atlassian.net/browse/PUBDEV-6030

PUBDEV-6030 get reconstruction error for auto encoders from easy wrapper

---

h2o-genmodel/src/main/java/hex/genmodel/algos/ensemble/StackedEnsembleMojoModel.java
h2o-genmodel/src/test/java/hex/genmodel/algos/ensemble/StackedEnsembleSerializableMojoTest.java

The `StackedEnsembleMojoModel` has a static inner class `StackedEnsembleMojoSubModel` which is not serializable. This PR fixes the `StackedEnsembleMojoSubModel` implements the `Serializable` interface. 
JIRA: https://0xdata.atlassian.net/browse/PUBDEV-6101

PUBDEV-6101 fix StackedEnsembleMojoSubModel to be serializable

---

h2o-bindings/bin/gen_R.py
h2o-r/h2o-package/R/stackedensemble.R

This is little part of the effort to bring our codebase closer to a canonical state, which will help us in producing minimal diffs. Currently, there is:
- 179 `.java` files,
- 289 `.py` files,
- 422 `.R` files
containing lines with trailing spaces. That's quite a lot, and it makes the chance of nonsenses in diffs pretty high. Before we do any other steps, it's good to start with generated files.

Fix code generators to no longer generate trailing spaces

---

h2o-automl/src/main/java/ai/h2o/automl/Leaderboard.java
h2o-automl/src/test/java/ai/h2o/automl/LeaderboardTest.java

Fix output of rankTsv in Leaderboard. Previously, it tried to print Arrays of metrics directly (`defaultMetricForModel(m)` returns array), however Java arrays don't have readable` toString` method. Just `hashcode` of that array was printed out

[PUBDEV-6115] Fix output of rankTsv in Leaderboard

---

h2o-extensions/xgboost/src/main/java/hex/tree/xgboost/XGBoostModel.java
h2o-extensions/xgboost/src/test/java/hex/tree/xgboost/XGBoostTest.java
h2o-extensions/xgboost/src/test/java/hex/tree/xgboost/XGBoostTreeConverterTest.java
h2o-py/h2o/estimators/xgboost.py
h2o-py/tests/testdir_algos/xgboost/pyunit_H2OXGBoost_native_XGBoost_enum_binomial_compare_sparse_singleNode.py
h2o-py/tests/testdir_algos/xgboost/pyunit_H2OXGBoost_native_XGBoost_enum_multinomial_compare_sparse_singleNode.py
h2o-py/tests/testdir_algos/xgboost/pyunit_H2OXGBoost_native_XGBoost_mixed_binomial_compare_large_dense_singleNode.py
h2o-py/tests/testdir_algos/xgboost/pyunit_H2OXGBoost_native_XGBoost_mixed_binomial_compare_large_sparse_singleNode.py
h2o-py/tests/testdir_algos/xgboost/pyunit_H2OXGBoost_native_XGBoost_mixed_multinomial_compare_large_dense_singleNode.py
h2o-py/tests/testdir_algos/xgboost/pyunit_H2OXGBoost_native_XGBoost_mixed_multinomial_compare_large_sparse_singleNode.py
h2o-py/tests/testdir_algos/xgboost/pyunit_H2OXGBoost_native_XGBoost_mixed_regression_compare_large_dense_singleNode.py
h2o-py/tests/testdir_algos/xgboost/pyunit_H2OXGBoost_native_XGBoost_mixed_regression_compare_large_sparse_singleNode.py
h2o-py/tests/testdir_algos/xgboost/pyunit_H2OXGBoost_native_XGBoost_numerical_binomial_compare_sparse_singleNode.py
h2o-py/tests/testdir_algos/xgboost/pyunit_native_comparison.py
h2o-py/tests/testdir_algos/xgboost/pyunit_xgboost_zero_nan_handling_native_comparison.py
h2o-r/h2o-package/R/xgboost.R
h2o-r/tests/testdir_jira/runit_pubdev_4585.R

Reverts back a mistake that was made to [change the default value](https://0xdata.atlassian.net/browse/PUBDEV-4794).

PUBDEV-6124: Use same default for L2 regularization as native XGBoost

---

h2o-dist/index.html
h2o-docs/src/product/downloading.rst

Removed this from the documentation and from the Install on Hadoop tab of the download site.

Remove -output hdfsOutputDirName when starting Hadoop

---

h2o-py/h2o/frame.py
h2o-py/tests/testdir_algos/xgboost/pyunit_PUBDEV_5777_XGBoost_dense_comparisons.py
h2o-py/tests/testdir_algos/xgboost/pyunit_PUBDEV_5777_XGBoost_sparse_comparisons.py
h2o-py/tests/testdir_algos/xgboost/pyunit_PUBDEV_6117_xgboost_compare.py

This PR fixes the problem in JIRA: https://0xdata.atlassian.net/browse/PUBDEV-6117?filter=-1
Work done:
1.  Added Python test using the dataset provided by Nidhi.
2. Fixed method convert_H2OFrame_2_DMatrix in frame.py to accept any H2O frame and convert it to valid data for native XGBoost.

PUBDEV-6117: fixed python client code to enable XGBoost compare with anyH2O Frame

---

h2o-core/src/main/java/water/MemoryManager.java
h2o-core/src/main/java/water/rapids/BinaryMerge.java
h2o-core/src/main/java/water/rapids/RadixOrder.java
h2o-core/src/main/java/water/rapids/SingleThreadRadixOrder.java
h2o-core/src/main/java/water/rapids/SplitByMSBLocal.java
h2o-core/src/test/java/water/rapids/SortTest.java
h2o-py/tests/testdir_munging/pyunit_PUBDEV_5990_arrange_OOM_large.py

This PR resolves JIRA: https://0xdata.atlassian.net/browse/PUBDEV-5990?filter=-1
Work done:
1. Instead of saving all the rows for a MSB in a RPC call, I have broken down the rows into batches.  Only one batch need to be saved at a time.  This reduces the memory requirement.  However, this can potentially increase the number of batches that need to be fetched from neighboring nodes and increase run time.  The batchsize decision is important in this case.  I will perform experiment to capture this.
2. Added R and Python unit tests to ensure that sorting is done correctly and no OOM message is received.  The datasets are generated from Lauren's parameters.

Rel-xia-PUBDEV-5990-arrange-OOM

---

h2o-core/src/main/java/water/util/IcedBitSet.java
h2o-core/src/test/java/water/util/IcedBitSetTest.java
h2o-core/src/test/java/water/util/IcedBitSetUnitTest.java

Originally, the bit order in POJO generated comments was lowest to highest. The opposite order is correct.

HEXDEV-725: fix bit order in explanatory comments for byte arrays

---

h2o-core/src/main/java/water/fvec/C1SChunk.java
h2o-core/src/main/java/water/fvec/C2SChunk.java
h2o-core/src/main/java/water/fvec/CSChunk.java
h2o-core/src/main/java/water/fvec/NewChunk.java
h2o-core/src/main/java/water/rapids/BinaryMerge.java
h2o-core/src/main/java/water/rapids/RadixOrder.java
h2o-core/src/test/java/water/fvec/C1SChunkTest.java
h2o-core/src/test/java/water/fvec/C2SChunkTest.java
h2o-core/src/test/java/water/fvec/FrameTest.java
h2o-core/src/test/java/water/fvec/NewChunkSpeedTest.java
h2o-core/src/test/java/water/fvec/NewChunkTest.java
h2o-core/src/test/java/water/rapids/SortTest.java
h2o-py/tests/testdir_jira/pyunit_PUBDEV_3567_merge_stall_large.py

fix lossy conversions of longs to doubles:
- add at8_impl's for (C1S/C2S)Chunk
- add new test cases to (C1S/C2S)ChunkTest
- use BigInteger and smarter heueristics to detect "long" overflow

HEXDEV-715: spencer_2309_2310

---

h2o-core/src/main/java/water/fvec/NewChunk.java
h2o-core/src/test/java/water/fvec/NewChunkTest.java

This PR fixes the problem in JIRA: https://0xdata.atlassian.net/browse/PUBDEV-6059
Work done:
- Added testcase for function NewChunk.addNumDecompose()
- Fixed IndexOutOfBound exception when adding spetial double values:
- NaN
- +-Infinity
- Large double with exponential > 1023

[PUBDEV-6059] Fix missing checks of NaN, MaxValue and Infinity for chunk add

---

h2o-py/h2o/estimators/estimator_base.py
h2o-py/h2o/model/model_base.py
h2o-py/tests/testdir_jira/pyunit_pubdev_5829_pubdev_6091_get_model_timestamp.py

* PUBDEV-6091: expose timestamp of a model
* Reverted R API timestamp exposure
* Model training start time, end time and resulting runtime exposed in Python as in R API
(cherry picked from commit cf1e23e0b1b04def9fcfb80edb4adce9bbbd1003)

PUBDEV-6091 - expose timestamp in Python & R API (#3112)

---

h2o-bindings/bin/gen_python.py
h2o-py/h2o/estimators/pca.py
h2o-py/h2o/transforms/decomposition.py
h2o-py/tests/testdir_pipeline/pyunit_scale_pca_rf.py
h2o-py/tests/testdir_scikit_grid/pyunit_scal_pca_rf_grid.py

In the `H2OPrincipalComponentAnalysisEstimator` (`pca.py`) the method `transform` is missing and the `@property transform` was called instead. It caused `None` was returned. The H2OPCA works well because it doesn't have `@property transform` (the parameter `transform` is set in the `init `method and cannot be changed). 
JIRA: https://0xdata.atlassian.net/browse/PUBDEV-5236
**The first idea**
- generate transform method into `pca.py`
- problem: overloading doesn't work even though the tests passed. When the user sets the transform property, a pipeline uses this property method when is running. 
**The second idea**
- rename the  `@property transform` to `@property transformation`
- problem: it is not user-friendly, it breaks all estimators usage, the doc should be changed, etc...
**The …

PUBDEV-5236 add the missing transform method

---

h2o-py/h2o/model/model_base.py
h2o-py/tests/testdir_misc/pyunit_pubdev_5706_usersplits_pdp.py
h2o-r/h2o-package/R/models.R
h2o-r/tests/testdir_jira/runit_pubdev_6122.R

[PUBDEV-6122](https://0xdata.atlassian.net/browse/PUBDEV-6122)
[SUPPORT PORTAL Ticket #93297](https://support.h2o.ai/helpdesk/tickets/93297)
- I rather chose to modify a current test (almost zero slowdown of test pipeline) that constructs PDPs anyway.
- Existing files are overwritten
- PNG output format (unified with R).
Example call:
```python
pdpOrig = gbm_model.partial_plot(data=data,cols=['AGE', 'RACE', 'DCAPS'],server=True, plot=True, save_to_file="/home/pavel/pdps.png")
```
- Saves each plot to a separate file. Automatically adds posfix `${FEATURE_NAME}.png`, where `${FEATURE_NAME}` is obviously name of the feature the plot corresponds to. For `n` plots being generated in R, there are `n` files created.
- Plots can still be seen in R, `dev.copy()` is used.
- Existing files are …

PUBDEV-6122 - Add a parameter to pdp to save the plot

---

h2o-core/src/main/java/water/jdbc/SQLManager.java
h2o-core/src/test/java/water/jdbc/SQLManagerTest.java

https://0xdata.atlassian.net/browse/PUBDEV-6123
fixed import queries, now using following syntax, both fully supported from SQL Server 2012:
for column names retrieval (supported from SQLS 2008):
```sql
select top(1) <columns> from <table>;
```
for data chunks retrieval (supported from SQLS 2012):
```sql
select <columns> from <table> order by row_number() over (order by (select 0)) offset <start> rows fetch next <N> rows only;
```
see ticket comments for testing protocol

PUBDEV-6123: fixed SQLManager import queries for MS SQLServer / Azure SQL

---

h2o-automl/src/main/java/ai/h2o/automl/AutoML.java

https://0xdata.atlassian.net/browse/PUBDEV-6152
reintroduced cloning of training frame in AutoML to keep internal ref. in case of reruns

PUBDEV-6152: NPE when building SE during AutoML reruns in some corner cases

---

h2o-docs/src/product/automl.rst
h2o-docs/src/product/data-science/algo-params/stopping_metric.rst
h2o-docs/src/product/data-science/deep-learning.rst
h2o-docs/src/product/data-science/drf.rst
h2o-docs/src/product/data-science/gbm.rst
h2o-docs/src/product/data-science/xgboost.rst
h2o-docs/src/product/flow.rst

- Added "custom" and "custom_increasing" to list of stopping_metric options in all supported algorithm sections and in flow.
- Added a Python example showing how to use this in the stopping_metric parameter appendix entry.

PUBDEV-6048: New stopping_metric options

---

h2o-py/tests/testdir_algos/xgboost/stress/pyunit_xgboost_airlines_stress.py
scripts/jenkins/groovy/defineTestStages.groovy

[JIRA PUBDEV-6167](https://0xdata.atlassian.net/browse/PUBDEV-6167)
XGBoost stress tests have a time limit of 20 minutes, then those tests are terminated. Sometimes, the environment is slow to start. The stress tests (currently 1 stress test) otherwise take approx. 220 second to complete on a single local node.
There is a cloud of 5 nodes used to stress test XGBoost integration, with a limit of file descriptors to 100. The reason for current stress test is resource leaks detection.
This battery of tests (1 stress test in reality) has limited file descriptor resources.
```groovy
[ // These run with reduced number of file descriptors for early detection of FD leaks
stageName: 'XGBoost Stress tests', target: 'test-pyunit-xgboost-stress', pythonVersion: '3.5', timeoutValue: 40,
component: …
```

PUBDEV-6167 XGBoost stress test timeout

---

h2o-docs/src/product/downloading.rst
h2o-docs/src/product/starting-h2o.rst
h2o-docs/src/product/welcome.rst

driveby fixes: updated H2O version in examples to be 3.22.1.2.

PUBDEV-6165 Docs: Add support for HDP 3.0 and 3.1

---

scripts/jenkins/groovy/makeTarget.groovy

The `summary.txt` contains list of executed tests, with results and timing, which is quite important and takes almost no diskspace. Such information can be used for basic comparison of tests.
Note: merging this is IMHO good by itself, but may be helpful for #3206 and #3212

ITA-362: always archive summary.txt on jenkins jobs

---

h2o-docs/src/product/data-science/k-means.rst

Scoring history graph shows number of iterations vs. within the cluster's sum of squares rather than number of iterations vs. "average" within the cluster's sum of squares.

PUBDEV-6190: Doc update for KMeans

---

h2o-core/src/main/java/water/AutoBuffer.java
h2o-core/src/main/java/water/ClientDisconnectCheckThread.java
h2o-core/src/main/java/water/ClientRandomDisconnectThread.java
h2o-core/src/main/java/water/H2O.java
h2o-core/src/main/java/water/H2ONode.java
h2o-core/src/main/java/water/MRTask.java
h2o-core/src/main/java/water/Paxos.java
h2o-core/src/main/java/water/RPC.java
h2o-core/src/main/java/water/TCPReceiverThread.java
h2o-core/src/main/java/water/UDPClientEvent.java
h2o-core/src/main/java/water/UDPHeartbeat.java
h2o-core/src/main/java/water/init/NetworkInit.java
h2o-core/src/main/java/water/util/JStackCollectorTask.java
h2o-core/src/test/java/water/ClientJarMD5IgnoreTest.java
h2o-core/src/test/java/water/ClientReconnectSimulationTest.java
h2o-core/src/test/java/water/ExternalFrameReaderClientTest.java
h2o-core/src/test/java/water/ExternalFrameWriterClientTest.java
h2o-core/src/test/java/water/UnknownHeartbeatTest.java
scripts/jenkins/Makefile.jenkins
scripts/jenkins/groovy/defineTestStages.groovy

This PR addresses a race condition in the client mode: if a client is detected to be disconnected and at the same time we want to send a message back to the client we can kill the Sending Thread of the H2ONode instance that the sender wants to use to communicate back to the client. This results in NullPointerException.
This PR solves this by combining 2 approaches:
- `H2ONode#sendMessage` is modified to avoid communication using stale instances of Sending Threads
- decommissioned Sending Threads are kept around for a grace period - if the client is not actually disconnected (even though H2O thinks that) we will deliver the currently unsent messages and also any messages added before we realized the client is re-connected again and added back to the cluster. The grace period is 100s by …

PUBDEV-6198: Make sure H2ONode never loses a Sending Thread

---

.gitignore
docker/scripts/build-h2o-3
scripts/jenkins/Makefile.jenkins
scripts/jenkins/groovy/buildH2O3.groovy
scripts/jenkins/groovy/insideDocker.groovy
scripts/jenkins/groovy/makeTarget.groovy
scripts/jenkins/jenkinsfiles/Jenkinsfile-Release

The goal is to maintain the same Makefile behavior in Jenkins and local execution.
This PR solves the problem for all affected targets - many R and python unit tests.
In addition to this, another problem is fixed: some exclusions were implemented by simply deleting certain tests from the filesystem, which is not such a problem on jenkins agents, but would be very dangerous when executed on developer's machine. Instead, cummulative exclussion is used now, see new helper targets `init-tests`, `lookup-*-tests` and usage of `.tests-*.txt` files.

ITA-362: move test lookups into Makefile

---

scripts/jenkins/Makefile.jenkins
scripts/jenkins/groovy/benchmarkStage.groovy
scripts/jenkins/groovy/defineTestStages.groovy
scripts/jenkins/groovy/hadoopStage.groovy
scripts/jenkins/groovy/initPipelineContext.groovy
scripts/jenkins/groovy/insideDocker.groovy
scripts/jenkins/groovy/makeTarget.groovy
scripts/jenkins/groovy/pipelineUtils.groovy
scripts/jenkins/groovy/xgbGPUStage.groovy
scripts/jenkins/jenkinsfiles/Jenkinsfile-Release

[ITA-363](https://0xdata.atlassian.net/browse/ITA-363)
Files matching `**/java*_*.out.txt` are now archived (rather than excluded), but right before archival, we move to zip those bigger than threshold (currently 400k). Extension `.zip` is added to them, and these files are archived, too.
Additionally, this PR comes with very minor improvements in groovy code.
Especially, every `rm` command is now equipped with flag `-v` so that we can see which files have been deleted.

ITA-363: keep huge java logs in Jenkins archive, zipped

---

h2o-py/h2o/estimators/estimator_base.py
h2o-py/tests/testdir_algos/gbm/pyunit_ignored_columns_gbm.py
h2o-py/tests/testdir_algos/kmeans/pyunit_parametersKmeans.py

The parameter `ignored_columns` in train method replace the parameter set in Estimator constructor. 
The similar problem as in PUBDEV-6036 (https://github.com/h2oai/h2o-3/pull/3024). 
JIRA: https://0xdata.atlassian.net/browse/PUBDEV-6197

PUBDEV-6197 assign ignored_columns parameter in train method properly

---

h2o-core/src/main/java/water/fvec/Frame.java

In Sparkling Water, we would like to improve handling of sparse vectors. Ie we would like to use sparse new chunks when converting sparse spark vectors.
We use the `createNewChunks` method from H2O to create chunks. This PR just exposes the sparse option to this method.

Allow to create sparse newchunk

---

h2o-core/src/main/java/water/api/schemas3/ModelParametersSchemaV3.java
h2o-docs/src/product/data-science/algo-params/stopping_metric.rst
h2o-docs/src/product/data-science/drf.rst
h2o-docs/src/product/data-science/gbm.rst
h2o-r/h2o-package/R/gbm.R
h2o-r/h2o-package/R/randomforest.R

- Updated GBM, DRF, and stopping_metric topics in end user documentation with note that custom and custom_increasing are only available in the Python client.
- Updated help string for stopping_metric command to indicate that this option is only available in the Python client.
- Removed custom and custom_increasing from the R documentation.

PUBDEV-6253: Note that stopping_metric=custom,custom_increasing aren't available in R

---

h2o-core/src/main/java/water/fvec/Frame.java

In a PR about a week ago I introduce method which would allow us to create sparse chunks from Sparkling Water. I passed single value for `sparse` however we need to pass array of booleans as different chunks in frame might be sparse and not sparse

Fix the new method allowing us to create sparse chunks from SW

---

h2o-docs/src/booklets/v2_2015/source/GLMBooklet.tex
h2o-docs/src/product/data-science/glm.rst

- Updated the equation for deviance in the Tweedie subsection in the user guide and GLM booklet
- p=3 is Inverse-Gaussian instead of Gaussian in the UG
- Fixed character issue in GLM booklet

PUBDEV-6183: Doc fix for Tweedie deviance equation

---

h2o-docs/src/product/data-science/if.rst
h2o-docs/src/product/performance-and-prediction.rst

- Added this in the Prediction topic, as it applies to predictions in GBM, DRF, XGBoost, and Isolation Forest.
- Added predict_leaf_node_assignment to the current example in the Prediction topic.
- In the Isolation Forest topic, added links to tutorials and blogs. Also added a simple example (in R and Python) showing model building, predict, and predict leaf node assignment.

PUBDEV-6245: Add predict_leaf_node_assignment to User Guide

---

h2o-algos/src/test/java/hex/tree/drf/DRFTest.java
h2o-core/src/main/java/hex/Model.java
h2o-core/src/main/java/hex/ModelBuilder.java

* Currently if a training frame has a constant response column, then an error is thrown based on the below snippet: 
```
if (_response.isConst())
error("_response","Response cannot be constant.");
```
* A good solution for this is to make the above check optional for instances where this behavior is not desired. 
* **NOTE: This is only exposed in Java**

PUBDEV-6277: Make constant response check optional for all models

---

.gitignore
scripts/jenkins/Makefile.jenkins
scripts/jenkins/groovy/hadoopStage.groovy
scripts/jenkins/groovy/makeTarget.groovy
tests/leakCheckKeywords

After each execution of Make target in pipeline additional target `check-leaks` is executed. This new target does the following:
- at first reads the `tests/leakCheckKeywords` which contains restricted keywords
- replace newlines with `|`, so it is usable in `grep` regexp
- check for presence of any of the keywords in files with `*.out`, `*.log` suffices and in files with `out.*` prefix (JUnit logs)
- all matches are logged to `leak-check.out`
- if this file is not empty, make call fails failing the stage

[ITA-372] Check for leaked passwords and usernames in logs.

---

h2o-algos/src/main/java/hex/schemas/DRFV3.java
h2o-algos/src/main/java/hex/schemas/GBMV3.java
h2o-algos/src/main/java/hex/schemas/SharedTreeV3.java
h2o-algos/src/main/java/hex/tree/SharedTreeModel.java
h2o-py/h2o/estimators/gbm.py
h2o-py/h2o/estimators/random_forest.py
h2o-py/tests/testdir_algos/gbm/pyunit_constant_response_gbm.py
h2o-py/tests/testdir_algos/rf/pyunit_constant_response_rf.py
h2o-r/h2o-package/R/gbm.R
h2o-r/h2o-package/R/randomforest.R
h2o-r/tests/testdir_algos/gbm/runit_GBM_constant_response.R
h2o-r/tests/testdir_algos/randomforest/runit_RF_constant_response.R

* Expose `check_constant_response` for DRF and GBM
* This variable is set to `true` by default, which is behavior today, i.e., thrown an exception if response column is a constant value
* Added simple unit tests in R/Python client which basically ensures GBM and DRF respect this argument if set to `false`

PUBDEV-6294: Expose check_constant_response for DRF and GBM

---

h2o-r/h2o-package/R/automl.R
h2o-r/tests/testdir_algos/automl/runit_automl_leaderboard.R

- Fixed a bug on the AutoML R client described in [PUBDEV-6290](https://0xdata.atlassian.net/projects/PUBDEV/issues/PUBDEV-6290)
- Removed the single NA row for empty leaderboards in R
- Added warning for when there's an empty leaderboard
- The `h2o.getAutoML()` function was also not working for empty leaderboards in R (now fixed)
- Fixed unit test for empty leaderboard (was checking for 1 row, now checks for 0 rows)
- There are a lines changed because of deleted spaces (must have been introduced by my editor...)

PUBDEV-6290: Fixing AutoML leader slot in R for single model

---

h2o-algos/src/main/java/hex/ensemble/StackedEnsembleModel.java
h2o-algos/src/test/java/hex/ensemble/StackedEnsembleTest.java
h2o-automl/src/main/java/ai/h2o/automl/AutoML.java
h2o-automl/src/main/java/ai/h2o/automl/AutoMLBuildSpec.java
h2o-automl/src/main/java/ai/h2o/automl/Leaderboard.java
h2o-automl/src/main/java/ai/h2o/automl/UserFeedbackEvent.java
h2o-automl/src/main/java/water/automl/api/schemas3/AutoMLBuildSpecV99.java
h2o-automl/src/main/java/water/automl/api/schemas3/AutoMLV99.java
h2o-automl/src/test/java/ai/h2o/automl/AutoMLTest.java
h2o-core/src/main/java/hex/ModelMetrics.java
h2o-core/src/test/java/water/TestUtil.java
h2o-py/h2o/automl/autoh2o.py
h2o-py/tests/testdir_algos/automl/pyunit_automl_args.py
h2o-r/h2o-package/R/automl.R
h2o-r/tests/runitUtils/utilsR.R
h2o-r/tests/testdir_algos/automl/runit_automl_args.R

https://0xdata.atlassian.net/projects/PUBDEV/issues/PUBDEV-6254
Exposing blending frame in AutoML..: expected behaviour when blending frame is provided, is that we don't enforce some CV-related params necessary for SE otherwise, and SE are still computed if nfolds=0 as we don't use cv predictions to train the SEs in this case.
When CV is disabled (common use-case when using blending for time series), we now force the creation of a validation frame to avoid overfitting of the base models.
Also made small changes to leaderboard so that it can do scoring based on validation metrics then, and not only by scoring the leaderboard frame, making this latter one potentially optional also internally.

PUBDEV-6254: AutoML basic support for blending

---

h2o-docs/src/product/data-science/algo-params/check_constant_response.rst
h2o-docs/src/product/data-science/algo-params/custom_metric_func.rst
h2o-docs/src/product/data-science/deep-learning.rst
h2o-docs/src/product/data-science/drf.rst
h2o-docs/src/product/data-science/gbm.rst
h2o-docs/src/product/data-science/glm.rst
h2o-docs/src/product/data-science/stacked-ensembles.rst
h2o-docs/src/product/flow.rst
h2o-docs/src/product/parameters.rst

- Added check_constant_response to list of parameters in GBM and DRF.
- Added an example of check_constant_response in the Parameters appendix.
- Added check_constant_response to Flow chapter
Driveby fixes:
- Added documentation for custom_metric_func, available in GBM, DRF, and GLM.
- Added export_checkpoints_dir option to DL, DRF, and GBM.
- Updated flow to include export_checkpoints_dir and custom_metric_func.

PUBDEV-6287: Add documentation for check_constant_response in GBM and DRF

---

h2o-core/src/main/java/hex/CreateFrame.java
h2o-core/src/main/java/hex/createframe/recipes/OriginalCreateFrameRecipe.java
h2o-py/tests/testdir_jira/pyunit_pubdev_6304_cat_warn_large.py

This PR completes work required in JIRA: https://0xdata.atlassian.net/browse/PUBDEV-6304?filter=-1 .
H2O allows 10000000 categorical levels.  However, an error message was generated if we have categorical level > 1000000.  We are missing out on a zero here.
Fix:
1. Comparison threshold changed from 1000000 to 10000000.
2. Added pyunit test to make sure correct error message is returned.

PUBDEV-6304: fixed wrong categorical level error message

---

h2o-algos/src/main/java/hex/tree/isofor/IsolationForest.java
h2o-algos/src/main/java/hex/tree/isofor/IsolationForestModel.java
h2o-algos/src/main/java/hex/tree/isofor/ModelMetricsAnomaly.java
h2o-algos/src/main/java/hex/tree/isofor/PathTracker.java
h2o-algos/src/test/java/hex/tree/isofor/IsolationForestTest.java
h2o-algos/src/test/java/hex/tree/isofor/PathTrackerTest.java
h2o-core/src/main/java/hex/ModelMetrics.java
h2o-core/src/main/java/hex/ModelMetricsUnsupervised.java

Fixes case when minimum and maximum path length is not correctly calculated in Isolation Forest when there are no OOB observations (this is an edge case - usually only small subset of records is used to build the trees).

PUBDEV-6271: Isolation Forest - Min-Max path is correctly calculated when OOB is empty

---

h2o-r/h2o-package/R/communication.R
h2o-r/h2o-package/R/connection.R
h2o-r/h2o-package/R/export.R
h2o-r/h2o-package/R/logging.R

- h2o.init now correctly respects context_path when starting new h2o instance
- h2o.downloadAllLogs now respects context_path
- h2o.downloadCSV now respects context_path

[PUBDEV-6305] fix context_path related bugs

---

h2o-algos/build.gradle

When starting Spark with dependencies specified using --packages, such as:
`spark-shell --packages "ai.h2o:h2o-algos:3.22.1.4` ( usually people do `spark-shell --packages "ai.h2o:sparkling-water-package_2.11:2.4.6` ) but the problematic bit were the h2o-algos.
`h2o-algos` is using `com.github.fommil.netlib:core` dependency which has this pom file `http://central.maven.org/maven2/com/github/fommil/netlib/core/1.1.2/core-1.1.2.pom.
We can see that this pom file specifies dependency on `net.sourceforge.f2j:arpack_combined_all` for both jar and javadoc. 
This confuses spark ivy resolver. The solution here is to exclude this dependency and add it manually again, this time without javadoc.
JIRA on Spark side
Spark ivy resolver is confused if the maven coordinates

[PUBDEV-6321] Fix resolution of h2o-algos by Spark ivy resolver

---

h2o-docs/src/product/data-science/xgboost.rst
h2o-docs/src/product/welcome.rst

- Changed 100 to 120 in the XGBoost FAQ for setting the extramempercent value.
- In the Welcome topic, added a recommendation that extramempercent be set to 120 for xgboost.

PUBDEV-5554: Recommend setting extramempercent to 120 for xgboost

---

h2o-core/src/main/java/water/rapids/ast/prims/advmath/AstStratifiedSplit.java
h2o-core/src/test/java/water/util/VecUtilsTest.java
h2o-py/tests/testdir_jira/pyunit_pubdev_6283.py

https://0xdata.atlassian.net/browse/PUBDEV-6283
Original script to reproduce the issue from the JIRA
```python
import h2o
h2o.init()
df_h2o = h2o.import_file("https://s3.amazonaws.com/h2o-public-test-data/smalldata/covtype/covtype.20k.data")
stratified = df_h2o[54].stratified_split()
train = df_h2o[stratified=="train"]
test  = df_h2o[stratified=="test"]
df_h2o['C3'] = df_h2o['C3'].asfactor()
col = 'C3'
split=df_h2o[col].stratified_split(test_frac=0.3)
train=df_h2o[split=='train']
test=df_h2o[split=='test']
print(len(train))
print(train[col].nacnt())
print(train[col].nlevels())
train['C3'].stratified_split(test_frac=0.1)
```

PUBDEV-6283 - Stratified split fails when ran on the same column twice

---

h2o-py/tests/testdir_algos/automl/pyunit_automl_args.py

action after failing test in http://mr-0xc1:8080/job/h2o-3-pipeline/job/rel-xu/93/

increased runtime for an automl UT to ensure SEs are trained at the end

---

h2o-algos/src/main/java/hex/schemas/GLMModelV3.java
h2o-py/h2o/model/model_base.py
h2o-py/tests/testdir_algos/glm/pyunit_pubdev_6292_varimp_check.py
h2o-r/h2o-package/R/models.R
h2o-r/tests/testdir_algos/glm/runit_pubdev_6292_varimp_check.R

This work fixes the problem described in JIRA: https://0xdata.atlassian.net/browse/PUBDEV-6292?filter=-1
Tasked completed:
1. remove the intercept term from the standardized coefficient magnitude calculation from the backend.  The intercept term magnitude is assigned NA anyway.
2. Redirected model.R or model_base.py to look for standardized_coefficient_magnitudes when calculating variable importances.  GLM Binomial and GLM Multinomial have different coefficient fields.
3. Added Runit and pyunit tests to make sure varimp for GLM look the same as for other algos and varimp_plot works.

PUBDEV-6292: remove NA row from GLM varimp

---

h2o-algos/src/main/java/hex/api/MakeGLMModelHandler.java
h2o-algos/src/main/java/hex/deeplearning/DeepLearningModel.java
h2o-algos/src/main/java/hex/ensemble/StackedEnsembleModel.java
h2o-algos/src/main/java/hex/glm/GLMModel.java
h2o-core/src/main/java/hex/Model.java
h2o-core/src/main/java/water/api/schemas3/ModelOutputSchemaV3.java
h2o-extensions/xgboost/src/main/java/hex/tree/xgboost/XGBoostModel.java
h2o-py/tests/pyunit_utils/utilsPY.py
h2o-py/tests/testdir_algos/stackedensemble/pyunit_stackedensemble_regression.py
h2o-py/tests/testdir_algos/xgboost/pyunit_insurance_poisson_small.py
h2o-py/tests/testdir_jira/pyunit_pubdev_5801_add_names_types_model.py

This PR completes the work described in JIRA: https://0xdata.atlassian.net/browse/PUBDEV-5801?filter=-1 .
I have added the Java backend to copy the column types to model output.
I have added a pyunit test to check for all H2O algos that the column names and column types are correct.
For stackedensemble, I added the check to one existing pyunit test: pyunit_stackedensemble_regression.py
For xgboost, I added the check to one existing pyunit test: pyunit_insurance_poisson_small.py

PUBDEV-5801: Added column names and types to model output

---

h2o-docs/src/product/data-science/gbm.rst
h2o-docs/src/product/flow.rst

Noted that in GBM, monotone_constraints can only be used with Gaussian distribution. Add this in the GBM and Flow chapters.

PUBDEV-6337: Add note to docs re monotone_constraints in GBM

---

h2o-algos/src/main/java/hex/tree/DTree.java
h2o-algos/src/main/java/hex/tree/gbm/GBM.java

We currently only support Gaussian distribution which lets us use split node predictions from tree building directly and avoid using values from GammaPass. This fixes rounding errors introduced in GammaPass summation.

Avoid rounding errors in monotone GBMs by using split predictions directly

---

h2o-core/src/main/java/water/fvec/Frame.java

The work in this PR completes the work  requested in JIRA: https://0xdata.atlassian.net/browse/PUBDEV-6334?filter=-1
I corrected the error in Javadoc for Frame.java sort function.  Thanks to Andrey for catching it.
The sorting function itself is implemented in the rapids framework and that is why the sort tests are under the rapids folder as well.
The whole rapids design came about before I joined H2O so I have no idea why things are organized the way it is.
For anything that I have implemented, I made sure to add thorough tests in Java, R and Python clients. I have done the following for sort:
1. enable sorting of doubles;
2. add sorting directions support;
3. allow string columns in the frame as long as we do not sort with it.
4. fixed memory issue with sort when there are many columns …

PUBDEV-6334 update sort javadoc

---

h2o-algos/src/main/java/hex/ensemble/StackedEnsemble.java
h2o-algos/src/main/java/hex/ensemble/StackedEnsembleModel.java
h2o-algos/src/test/java/hex/ensemble/StackedEnsembleTest.java

https://0xdata.atlassian.net/browse/PUBDEV-6208
Not sure it covers the specific use-case mentioned in the ticket, but I was able to reproduce a similar behaviour when deleting a SE after AutoML run in Flow.
Note that AutoML has always `keep_level_one_frame=true`, which is the reason why this issue occurs more often there.

PUBDEV-6208: SE Model deletion can lead to removal of shared vecs

---

h2o-docs/devel/h2o_clouding.rst
h2o-docs/src/booklets/v2_2015/source/RBooklet.tex
h2o-docs/src/booklets/v2_2015/source/sw/sections/backends.tex
h2o-docs/src/booklets/v2_2015/source/sw/sections/deployment.tex
h2o-docs/src/booklets/v2_2015/source/sw/sections/pysparkling.tex
h2o-docs/src/booklets/v2_2015/source/sw/sections/usecase.tex
h2o-docs/src/product/architecture.rst
h2o-docs/src/product/automl.rst
h2o-docs/src/product/data-munging/combining-columns.rst
h2o-docs/src/product/data-science/xgboost.rst
h2o-docs/src/product/faq/java.rst
h2o-docs/src/product/hadoop.rst
h2o-docs/src/product/starting-h2o.rst
h2o-docs/src/product/welcome.rst
h2o-py/docs/intro.rst
h2o-py/h2o/backend/connection.py
h2o-py/h2o/backend/server.py
h2o-py/h2o/h2o.py
h2o-r/h2o-package/R/classes.R
h2o-r/h2o-package/R/connection.R
h2o-r/h2o-package/R/frame.R
h2o-r/h2o-package/R/import.R
h2o-r/h2o-package/R/logging.R
scripts/run.py

Updated User Guide, booklets, R, and Python docs.
Driveby fix: Removed FAQ indicating that Java 9 isn't supported. Fixed combining columns example.

PUBDEV-6362: Replaced "h2o cloud" with "h2o cluster" in end-user docs

---

h2o-r/h2o-package/R/frame.R
h2o-r/tests/testdir_misc/runit_PUBDEV_6346_groupby_multiple_columns.R

This PR fixes the bug in JIRA: https://0xdata.atlassian.net/browse/PUBDEV-6346?filter=-1
Fixed frame.R where it was not able to include multiple columns.
Fixed bug with duplicated columns return when specifying multiple groupby actions.
Fixed bug when user does not provide any action columns.  In this case, we will return actions performed on all elligible actions per proposal from Joe Granados.
Added a Runit test to verify that my fix is working.

PUBDEV-6346: Enable R client to call groupby with multiple columns. 

---

h2o-docs/src/product/automl.rst
h2o-docs/src/product/data-science/algo-params/exclude_algos.rst
h2o-docs/src/product/data-science/algo-params/include_algos.rst
h2o-docs/src/product/data-science/algo-params/max_models.rst
h2o-docs/src/product/data-science/algo-params/max_runtime_secs_per_model.rst
h2o-docs/src/product/data-science/algo-params/sort_metric.rst
h2o-docs/src/product/parameters.rst

- Added examples for include_algos, exclude_algos, max_models, and max_runtime_secs_per_model.
- Added links to these new topics in the AutoML chapter

PUBDEV-6331: Add parameter appendix entries for new AutoML options

---

h2o-core/src/main/java/water/H2O.java
h2o-core/src/main/java/water/server/ServletUtils.java

Example:
java -jarh2o.jar -add_http_header 'Strict-Transport-Security' 'max-age=3600' -jks ../mykeystore.jks

PUBDEV-6374: Allow users to define custom HTTP headers

---

h2o-r/h2o-package/R/models.R

Forgot to refactor `file_path` to `model_file_path`.

Fixed documentation and enhanced examples for h2o.genericModel

---

h2o-py/tests/testdir_jira/pyunit_pubdev_6339.py

Python 2.7 needs a special option to be able to read \r line ends.

PUBDEV-6339 fix pyunit test

---

h2o-algos/src/main/java/hex/glm/GLMModel.java
h2o-algos/src/test/java/hex/ensemble/StackedEnsembleTest.java

https://0xdata.atlassian.net/browse/PUBDEV-6376
ensured that GLM respect computeMetrics parameter when it doesn't have direct access to original frame (like in SE scoring)

PUBDEV-6376: StackedEnsemble prediction fails when applied to a test dataset without response column

---

h2o-docs/src/product/data-science/gbm.rst
h2o-docs/src/product/flow.rst

In the Flow and GBM chapters, added that monotone_constraints can be used when the distribution is set to bernoulli. Previously, this stated that monontone_constraints was only available for gaussian distributions.

PUBDEV-6381: monotone_constraints available with Bernoulli distribution

---

h2o-core/src/test/java/water/DKVTest.java

Accessing deleted frame's vecs is not a good idea at all.

PUBDEV-6324 - Fixed retain nothing test

---

h2o-extensions/xgboost/src/main/java/hex/tree/xgboost/XGBoostMojoWriter.java
h2o-extensions/xgboost/src/test/java/hex/tree/xgboost/DefaultMojoImplTest.java
h2o-extensions/xgboost/src/test/java/hex/tree/xgboost/XGBoostTest.java
h2o-genmodel-extensions/xgboost/src/main/java/hex/genmodel/algos/xgboost/XGBoostMojoModel.java
h2o-genmodel-extensions/xgboost/src/main/java/hex/genmodel/algos/xgboost/XGBoostMojoReader.java

Java predict is now proven and should be used as the default implementation for MOJO scoring. This also gives people access to TreeSHAP by default.

PUBDEV-6386: XGBoost MOJO should use Java predictor by default

---

h2o-bindings/src/main/java/water/bindings/examples/Example.java
h2o-core/src/main/java/water/api/ParseHandler.java
h2o-core/src/main/java/water/api/schemas3/ParseSetupV3.java
h2o-core/src/main/java/water/api/schemas3/ParseV3.java
h2o-core/src/main/java/water/parser/ARFFParser.java
h2o-core/src/main/java/water/parser/CsvParser.java
h2o-core/src/main/java/water/parser/DefaultParserProviders.java
h2o-core/src/main/java/water/parser/ParseSetup.java
h2o-core/src/main/java/water/parser/ParserProvider.java
h2o-core/src/test/java/water/parser/ARFFParserTest.java
h2o-core/src/test/java/water/parser/CsvParserTest.java
h2o-py/h2o/frame.py
h2o-py/h2o/h2o.py
h2o-py/tests/testdir_jira/pyunit_pubdev_6367.py
h2o-r/h2o-package/R/import.R
h2o-r/h2o-package/R/parse.R
h2o-r/tests/testdir_jira/runit_pubdev_6339.R
h2o-r/tests/testdir_jira/runit_pubdev_6367.R

https://0xdata.atlassian.net/browse/PUBDEV-6367
By default, some parsers are skipping lines beginning with some characters. Those defaults are implemented per each parser. The main point of this PR is to fulfill all the following conditions:
1. Make the defaults overridable,
1. Preserve the original behavior(defaults) when non-data line markers are not specified.
As a positive side-effect of this API, I made `CsvParser` and `ArffParser` use the new generic methods passing the whole `ParseSetup` object (reference to it of course), instead of pin-pointing only the necessary stuff. This old method has even been deprecated by @michalkurka some time ago. :)

PUBDEV-6367 - Overridable non-data line markers

---

h2o-r/h2o-package/R/frame.R
h2o-r/tests/testdir_jira/runit_pubdev_6221_get_types.R

Fetch H2oFrame before get the 'types' attribute.

PUBDEV-6221 h2o.getTypes bug

---

h2o-algos/src/test/java/hex/tree/gbm/GBMTest.java
h2o-core/src/main/java/hex/AUC2.java
h2o-core/src/test/java/hex/AUCBuilderTest.java

It sometimes fails to find the first bin to merge when merging per-chunk histograms
because it reuses invalid internal state

PUBDEV-6399: AUCBuilder doesn't always correctly merge histograms

---

h2o-docs/src/product/faq/sparkling-water.rst
h2o-docs/src/product/welcome.rst

- Sparkling Water links now point to the SW user guide.
- Noted that the SW FAQ is deprecated and will be removed, and users should refer to the FAQ in the SW UG.
Driveby fix: Added summary of RSparkling in the welcome topic.

PUBDEV-6401: Fix links to Sparkling Water topics in FAQ

---

h2o-core/src/main/java/hex/Model.java
h2o-core/src/main/java/water/H2O.java
h2o-core/src/main/java/water/TCPReceiverThread.java
h2o-core/src/test/java/water/H2OTest.java
h2o-core/src/test/java/water/NodeLocalEventCollectingListener.java
h2o-core/src/test/java/water/TCPReceiverThreadTest.java

Instead of shutting down logs will have this message:
java.io.IOException: Communication protocol failure (source: '/192.168.1.64'): Missing EOM sentinel     when opening new TCP channel.
at water.TCPReceiverThread.run(TCPReceiverThread.java:98)
04-10 17:27:08.637 192.168.1.64:54321    87637  #P-Accept ERRR: IO error on TCP port 54322:     java.io.IOException: Communication protocol failure (source: '/192.168.1.64'): Missing EOM sentinel     when opening new TCP channel.
The message includes the originator of the request. Users can go ahead and kill the misbehaving H2O.

PUBDEV-6418: H2O shouldn't just shutdown when an older H2O is trying to connect to it

---

h2o-core/src/main/java/water/util/VecUtils.java
h2o-py/tests/testdir_jira/pyunit_pubdev_6393.py

https://0xdata.atlassian.net/browse/PUBDEV-6393
My assumption was that the behavior of `asFactor` should be the same as in `Categorical` class. Rules for conversion to categoricals should be the same.

PUBDEV-6393 - Rapids as.factor operation converts non-ASCII strings to sanitized forms

---

h2o-docs/src/product/welcome.rst
h2o-py/conda/h2o/meta.yaml
h2o-py/h2o/model/model_base.py
h2o-py/tests/pyunit_utils/utilsPY.py
h2o-py/tests/testdir_misc/pyunit_pubdev_5761_pdp_NA.py

Same can be accomplished using our own functions

PUBDEV-6421: Get rid off `six` library from the python client

---

h2o-core/src/main/java/water/api/ModelsHandler.java
h2o-core/src/test/java/water/api/ModelsHandlerTest.java

Messages like
Illegal argument: dir of function: importModel: /path/to/model
Are not helpful, instead include whole exception message

PUBDEV-6411: Improve error message when model fails to load

---

h2o-core/src/main/java/hex/Model.java
h2o-core/src/main/java/water/api/ModelMetricsHandler.java
h2o-r/tests/testdir_jira/runit_pubdev_5595.R

There doesn't seem to be a reason to calculate metrics in pure predict ("h2o.predict"). The metrics for the frame is calculated as a side effect, however, it doesn't seem to be ever used. "h2o.performance" will re-calculate the metrics from scratch, it will not use the old object.
This is an issue when the user provides a response but not weights. H2O complains that it doesn't have the weights column for this frame. Eventhough the metrics are never accessible to the user.

PUBDEV-5595: Do not calculate ModelMetrics for pure predict

---

h2o-py/h2o/targetencoder.py
h2o-py/tests/testdir_algos/automl/target_encoding/pyunit_automl_target_encoding.py

Before there was a support for :
```
teColumns = ["home.dest"]
targetEncoder = TargetEncoder(x= teColumns, y= targetColumnName,blended_avg= True, inflection_point = 3, smoothing = 1)
```
with this PR it will be possible to pass column as string:
```
teColumns = "home.dest"
targetEncoder = TargetEncoder(x= teColumns, y= targetColumnName, blended_avg= True, inflection_point = 3, smoothing = 1)
```
or as index of the column:
```
teColumns = 13
targetEncoder = TargetEncoder(x= teColumns, y= targetColumnName, blended_avg= True, inflection_point = 3, smoothing = 1)
```

[PUBDEV-6432] Added Py API support for single column name or column index for target encoding.

---

h2o-core/src/main/java/water/api/schemas3/JobV3.java
h2o-py/h2o/backend/cluster.py
h2o-py/tests/testdir_jira/pyunit_pubdev_5023_rm_metalearner.py
h2o-py/tests/testdir_jira/pyunit_pubdev_6431_deleted_key.py
h2o-r/h2o-package/R/communication.R
h2o-r/tests/testdir_jira/runit_pubdev_6431_deleted_key.R

- when listing jobs use the actual value type for job result rather than the one stored in the job
- this fixes exception case when one job result is overwritten by another job result of different type

[PUBDEV-6431] fix exception for job list with replaced keys

---

h2o-core/src/main/java/water/fvec/Vec.java
h2o-core/src/main/java/water/rapids/ast/prims/string/AstReplaceAll.java
h2o-core/src/main/java/water/rapids/ast/prims/string/AstReplaceFirst.java
h2o-core/src/main/java/water/util/VecUtils.java
h2o-core/src/test/java/water/rapids/RapidsTest.java
h2o-py/tests/testdir_jira/pyunit_pubdev_6394.py

https://0xdata.atlassian.net/browse/PUBDEV-6394
When applying replacement on parts of categorical string, a duplicate categorical levels might be created, effectively reducing the cardinality of the set.
In this PR, the proposed way to deal with it is to change the categorical mapping (only if cardinality changes !) to the new domain by gathering the categorical ordinals which now map to the same index in string domain levels array.
For example, if the following frame named `originalFrame`, containing one column only with five categoricals and three categorical levels ( `["Ｘ県 Ａ市", "Ｘ県 Ｂ市", "Ｙ県 Ｃ市"]` ): 
```plain
location
-----------
Ｘ県 Ａ市
Ｘ県 Ｂ市
Ｘ県 Ｂ市
Ｙ県 Ｃ市
Ｙ県 Ｃ市
```
and everything after the space was removed/replaced by calling `originalFrame['location'].gsub(' .*', '')`. The result …

PUBDEV-6394 - Rapids replace operations on categoricals do not respect reduced categorical domains

---

h2o-py/h2o/targetencoder.py
h2o-py/tests/testdir_algos/automl/target_encoding/pyunit_automl_gbm_target_encoding.py
h2o-py/tests/testdir_algos/automl/target_encoding/pyunit_automl_target_encoding.py

It will make it easier to access encoding maps on the client side

PUBDEV-6382: Extend Py API for TargetEncoder with convenient method for getting encoding maps

---

h2o-algos/src/main/java/hex/generic/Generic.java
h2o-algos/src/test/java/hex/generic/GenericModelTest.java
h2o-core/src/main/java/hex/Model.java
h2o-core/src/main/java/water/fvec/CategoricalWrappedVec.java
h2o-core/src/test/java/hex/ModelBuilderTest.java
h2o-core/src/test/java/water/fvec/CategoricalWrappedVecTest.java

Instead of using CategoricalWrappedVec: update is more expensive than
wrapping a Vec but the benefit is that it is straightforward to work further
with a materialized Vec. Modifying a CategoricalWrappedVec might not always
work.

Explicitly re-map domains in prediction frames if necessary (PUBDEV-6449)

---

h2o-persist-s3/src/main/java/water/persist/PersistS3.java
h2o-persist-s3/src/test/java/water/persist/PersistS3Test.java

https://0xdata.atlassian.net/browse/PUBDEV-6440
In **S3**, everything is an object. Including folders. Which means H2O was trying to parse folders, as these were not filtered out.
- Filtering folders based on `/` postfix.
- Current logic also walks all the subfolders, This behavior has not been changed.
- Pattern was not taken into account when `importFiles` was invoked. This has been fixed, as users might need to filter the files in the subdirectories (for example).
- Flow tested
Note: This PR is only about S3. S3A has different handling of everything.

PUBDEV-6440 - Unable to parse files from s3 [using s3's directory url with s3 protocol]

---

h2o-extensions/xgboost/src/main/java/hex/tree/xgboost/XGBoost.java
h2o-extensions/xgboost/src/main/java/ml/dmlc/xgboost4j/java/XGBoostUpdateTask.java

Avoid using Rabit.init/shutdown - it is causing slowdown with new XGB

PUBDEV-6476: XGBoost - better (faster) way of extracting booster bytes

---

h2o-r/h2o-package/R/models.R
h2o-r/tests/testdir_jira/runit_pubdev_6475.R

https://0xdata.atlassian.net/browse/PUBDEV-6475
Details are hidden in the support portal, as the model may not be published: https://support.h2o.ai/helpdesk/tickets/94341
It is possible for XGBoost to produce a root-node only decision tree. Our API couldn't handle this case, as it relied on max_depth parameters to be required > 0. This is not the case of XGBoost. 
Submitting `max_depth = 0` to XGBoost is not the only way XGBoost will produce a root-node only graph. The customer used a valid (at first sight) set of arguments (details in the support ticket). Also, there were bugs found in history that made XGBoost produce the same result: https://github.com/dmlc/xgboost/issues/8
**Sample output after the code adjustments:**
```R
> tree@thresholds
[1] NA
> tree@levels
[[1]]
NULL
> tree@nas …
```

PUBDEV-6475 - h2o.getModelTree throws invalid object for slot 'nas'

---

h2o-py/h2o/targetencoder.py
h2o-py/tests/testdir_algos/automl/target_encoding/pyunit_automl_target_encoding.py

The issue was only in Py client. There was an assert that checks that order of columns to encode and order in response from the server are matching. 
Removed unnecessary assertion. As long as we sent to the server column names and frame keys from our encoding map in the same order we don't have to worry about the fact that order is different from what user had passed to the argument x.

PUBDEV-6474: Fix for the issue with more than two columns to encode in Py TargetEncoder

---

h2o-algos/src/main/java/hex/tree/DHistogram.java
h2o-algos/src/main/java/hex/tree/DTree.java
h2o-algos/src/main/java/hex/tree/gbm/GBM.java
h2o-algos/src/test/java/hex/tree/DTreeTest.java
h2o-r/tests/testdir_algos/gbm/runit_gbm_monotone_varimp_large.R

For columns with NAs - this is mainly due to incorrect attribution of squared error improvement for splits "NA vs rest".

PUBDEV-6490: GBM models with monotone constraints inflate variable importance

---

h2o-docs/src/product/faq/hadoop.rst
h2o-docs/src/product/welcome.rst

driveby fix: updated path to airlines file in Hadoop FAQ

PUBDEV-6486: Add support for CDH 6.2 to User Guide

---

h2o-genmodel-extensions/xgboost/build.gradle

This PR incorporates XGBoost version with a patched Rabit module: https://github.com/h2oai/xgboost/pull/71 (this patch improves performance H2OXGBoost on OS X)

PUBDEV-6476: Fix slow XGBoost scoring on OS X

---

h2o-mapreduce-generic/src/main/java/water/hadoop/h2odriver.java

Use case: h2odriver running in a docker contain or somehow isolated from data nodes (data nodes cannot reach the driver node), we need to give an outside IP address to the H2O nodes to use for a callback instead of the one detected in the container/isolated environment.
This would be used in Cloudera Data Science Workbench.
The user run starts the h2odriver in a container and specifies a known external IP for the callback using the `-extdriverif` parameter. It is expected the port doesn't have to be re-mapped like this because the outside port would be known and the container port can be chosen to be the same.
Example (a bit contrived, only for demo purposes):
1. Run ssh tunnel forwarding 172.16.2.204:40000 to 172.16.2.181:40000: `michalk@172.16.2.204:~$ ssh -L \*:40000:localhost:40000 …

PUBDEV-6503: Allow specifying an external IP for h2odriver callback

---

h2o-algos/src/main/java/hex/tree/TreeHandler.java

https://0xdata.atlassian.net/browse/PUBDEV-6489
The "NA only" sentence is indeed confusing. The threshold values are all NA,s which seems to be a valid outcome from the underlying SharedTree* structures.
```R
> tree <- h2o.getModelTree(gbm, tree_number = 1, tree_class = 0)
> tree@thresholds
[1] NA NA NA
```
The logic on backend is here (look into the else block): https://github.com/h2oai/h2o-3/blob/3ae9f57b68d715f4956dc090decdcc2fbe5438b9/h2o-algos/src/main/java/hex/tree/TreeHandler.java#L195
I propose changing the sentence about the split value, otherwise there is not much we can do in Tree API - this is a real valid outcome from the algorithm.

PUBDEV-648 - NA threshold not properly shown in tree node's description

---

h2o-extensions/xgboost/src/main/java/hex/tree/xgboost/XGBoostUtils.java
h2o-extensions/xgboost/src/main/java/ml/dmlc/xgboost4j/java/XGBoostSetupTask.java
h2o-extensions/xgboost/src/test/java/hex/tree/xgboost/XGBoostUtilsTest.java

@Pscheidl I noticed we spend a significant amount of time calculating dimensions of the CSR sparse matrix (see attached screenshot - 4 minutes no progress and the code is just calculating the matrix size) on larger dataset. Only single thread is doing something.
This PR makes the calculation parallel.

XGBoost: Clean-up + speed-up of Sparse Matrix allocation

---

h2o-r/h2o-package/R/models.R
h2o-r/tests/testdir_jira/runit_pubdev_6488.R

https://0xdata.atlassian.net/browse/PUBDEV-6488
There are three commits in this PR, each representing one improvement.
- https://github.com/h2oai/h2o-3/pull/3511/commits/950494734d72c0de4d1ccbd51b21530153817119 Fixes prediction printing in R (Python is OK)
- https://github.com/h2oai/h2o-3/pull/3511/commits/927aa8ce28ae536d5079a1d8342b5abedcf2f7cf Randomized tests for Tree API
- https://github.com/h2oai/h2o-3/pull/3511/commits/a2aa61a9efa3aee4df7b1c80ea6e44e839abdaf0 Protection against NA only arrays being evaluated as logical in R
The last commit unfortunately has no direct test, as we were unable to reproduce. It was the original issue, @meganjkurka managed to force XGBoost to produce a tree with split features all being NA. But we don't have the code to reproduce it. In future, we're …

PUBDEV-6488  h2o.getModelTree failing
