h2oai/h2o-3

- h2o-docs/src/product/performance-and-prediction.rst
PUBDEV-7576 was merged into master only. This needed to be merged into rel-zahradnik.
> Docs: Add info about 2D-PDP and multiclass PDP

- h2o-algos/src/main/java/hex/generic/Generic.java
- h2o-algos/src/main/java/hex/generic/GenericModel.java
- h2o-algos/src/main/java/hex/generic/GenericModelOutput.java
- h2o-algos/src/main/java/hex/glm/GLMModel.java
- h2o-algos/src/main/java/hex/tree/SharedTreeModel.java
- h2o-core/src/main/java/hex/Model.java
- h2o-core/src/main/java/hex/ModelBuilder.java
- h2o-core/src/main/java/water/H2ONode.java
- h2o-core/src/main/java/water/HeartBeat.java
- h2o-core/src/main/java/water/HeartBeatThread.java
- h2o-core/src/main/java/water/api/schemas3/ModelOutputSchemaV3.java
- h2o-core/src/main/java/water/util/ReproducibilityInformationUtils.java
- h2o-extensions/xgboost/src/main/java/hex/tree/xgboost/XGBoostOutput.java
- h2o-genmodel/src/main/java/hex/genmodel/ModelMojoReader.java
- h2o-genmodel/src/main/java/hex/genmodel/MojoModel.java
- h2o-genmodel/src/main/java/hex/genmodel/attributes/ModelJsonReader.java
- h2o-py/tests/testdir_algos/deeplearning/pyunit_mojo_reproducibility_info_dl.py
- h2o-py/tests/testdir_algos/gbm/pyunit_mojo_reproducibility_info_gbm.py
- h2o-py/tests/testdir_algos/glm/pyunit_mojo_reproducibility_info_glm.py
- h2o-py/tests/testdir_algos/isofor/pyunit_mojo_reproducibility_info_isofor.py
- h2o-py/tests/testdir_algos/rf/pyunit_mojo_reproducibility_info_drf.py
- h2o-py/tests/testdir_algos/xgboost/pyunit_mojo_reproducibility_info_xgboost.py
https://0xdata.atlassian.net/projects/PUBDEV/issues/PUBDEV-7452
> PUBDEV-7452 add model reproducibility info to MOJO

- h2o-algos/src/test/java/hex/quantile/QuantileTest.java
- h2o-core/src/main/java/hex/Model.java
- h2o-core/src/main/java/hex/ModelBuilder.java
- h2o-core/src/main/java/hex/quantile/Quantile.java
- h2o-core/src/main/java/water/api/schemas3/ModelSchemaBaseV3.java
Quantile model is internal and is not registered in model builders
> Calling haveMojo/havePojo on Quantile model produces an exception

- h2o-docs/src/product/api-changes.rst
- h2o-scala/README.md
https://0xdata.atlassian.net/browse/PUBDEV-7507
> PUBDEV-7507 - Deprecate h2o-scala module.

- h2o-py/tests/testdir_algos/gam/pyunit_PUBDEV_7367_gridsearch_error.py
- h2o-py/tests/testdir_algos/gam/pyunit_PUBDEV_7367_gridsearch_generic.py
- h2o-py/tests/testdir_algos/gam/pyunit_PUBDEV_7367_gridsearch_specific.py
JIRA: https://0xdata.atlassian.net/browse/PUBDEV-7367
PR adds unit tests to verify GAM grid search functionality in three cases:
1) a general grid search with no GAM specific parameters
2) a grid search using some GAM specific parameters
3) a grid search over a set of values containing exactly one invalid value (lambda = -1)
> PUBDEV-7367: GAM gridsearch unit tests

- h2o-docs/src/product/welcome.rst
- h2o-k8s/README.md
https://0xdata.atlassian.net/browse/PUBDEV-7586
> PUBDEV-7586 - Documentation changes related to the official K8S Docker image

- Changes.md
All issues resolved. Assumes release date of June 18.
> PUBDEV-7624: Release notes for 3.30.0.5 release

- h2o-r/h2o-package/R/classes.R
https://0xdata.atlassian.net/browse/PUBDEV-5025
The print method includes:
- Project name
- Leader model id, algorithm, model summary and cross validation metrics summary
- Top models on leaderboard
> PUBDEV-5025: Add a print method for the H2OAutoML class in R

- h2o-docs/src/product/performance-and-prediction.rst
https://0xdata.atlassian.net/browse/PUBDEV-7629
Fixing some of the terminology, fixed the AUC/AUCPR value and updated one tip.
> PUBDEV-7629: Update metric comparison chart in User Guide

- h2o-r/h2o-package/R/classes.R
Add doc string to R show method for AutoML object
> Fix test-r-cmd-check-as-cran for automl show method

- h2o-r/h2o-package/R/frame.R
https://0xdata.atlassian.net/browse/PUBDEV-7642
> PUBDEV-7642: Broken link in R docs causing CRAN errors on Windows

- h2o-algos/src/main/java/hex/gam/GAM.java
- h2o-algos/src/main/java/hex/gam/GAMModel.java
- h2o-algos/src/main/java/hex/glm/GLMModel.java
- h2o-algos/src/main/java/hex/schemas/GAMV3.java
- h2o-algos/src/main/java/hex/schemas/GLMV3.java
- h2o-algos/src/test/java/hex/gam/GamTestPiping.java
- h2o-py/h2o/estimators/gam.py
- h2o-py/h2o/estimators/glm.py
- h2o-py/tests/testdir_algos/gam/pyunit_PUBDEV_7181_check_model_scoring.py
- h2o-r/h2o-package/R/gam.R
- h2o-r/h2o-package/R/glm.R
https://0xdata.atlassian.net/projects/PUBDEV/issues/PUBDEV-7444
> PUBDEV-7444_make_AUTO_GLMs_default_family

- h2o-algos/src/main/java/hex/glm/GLMModel.java
- h2o-py/tests/testdir_algos/glm/pyunit_PUBDEV_7645_lambda_search_warning.py
This PR finish the work specified in JIRA: https://0xdata.atlassian.net/browse/PUBDEV-7645
I added the warning in init() of GLM and a pyunit test to make sure the warning is there.
> PUBDEV-7645: Added warning if user enable lambda_search and specify lambda-value

- h2o-py/tests/testdir_algos/coxph/pyunit_coxph_smoke_stratify.py
WIP, cc @michalkurka @honzasterba @Pscheidl 
It seems there is an problem with strata in R too :-/ (case 8)
The case #8 should give the same results, shouldn't it?
> PUBDEV-6968 add python test that covers stratification

- h2o-docs/src/product/data-science/algo-params/family.rst
- h2o-docs/src/product/data-science/algo-params/link.rst
- h2o-docs/src/product/data-science/gam.rst
- h2o-docs/src/product/data-science/glm.rst
I also added the AUTO option to the link table in both the link algo-param and glm.rst--please let me know if this looks good or if you would like me to change anything.
> PUBDEV-7648: Update documentation regarding AUTO option for the family parameter of GLM

- h2o-bindings/bin/custom/python/gen_drf.py
- h2o-bindings/bin/custom/python/gen_gbm.py
- h2o-bindings/bin/custom/python/gen_naivebayes.py
- h2o-bindings/bin/custom/python/gen_xgboost.py
- h2o-docs/src/product/data-science/algo-params/gainslift_bins.rst
- h2o-docs/src/product/data-science/drf.rst
- h2o-docs/src/product/data-science/gbm.rst
- h2o-docs/src/product/data-science/naive-bayes.rst
- h2o-docs/src/product/data-science/xgboost.rst
- h2o-docs/src/product/parameters.rst
- h2o-docs/src/product/performance-and-prediction.rst
- h2o-py/h2o/estimators/gbm.py
- h2o-py/h2o/estimators/naive_bayes.py
- h2o-py/h2o/estimators/random_forest.py
- h2o-py/h2o/estimators/xgboost.py
- h2o-py/h2o/model/binomial.py
Added `gainslift_bins` to the parameter appendix
Added example to KS Metric in Python docs
Added examples to `gainslift_bins` in Python docs
> PUBDEV-7655: Add documentation for `gainslift_bins`

- h2o-genmodel/src/main/java/hex/genmodel/algos/klime/KLimeMojoModel.java
* Resolves https://0xdata.atlassian.net/browse/PUBDEV-7627
> PUBDEV-7627: k-LIME easy predict wrapper should use Regression or KLime as a model category instead of just KLime

- h2o-docs/src/product/data-science/glrm.rst
See: https://0xdata.atlassian.net/browse/PUBDEV-7682
> PUBDEV-7682: Docs - GLRM parameter fixes

- h2o-core/src/main/java/water/server/ServletService.java
- h2o-core/src/main/java/water/server/WebsocketMeta.java
- h2o-core/src/main/java/water/webserver/H2OHttpViewImpl.java
- h2o-core/src/test/java/water/webserver/EchoServletProvider.java
- h2o-extensions/steam/src/main/java/hex/steam/SteamWebsocketServlet.java
- h2o-jetty-8/src/main/java/water/webserver/jetty8/Jetty8ServerAdapter.java
- h2o-jetty-8/src/main/java/water/webserver/jetty8/Jetty8WebsocketServlet.java
- h2o-jetty-9/src/main/java/water/webserver/jetty9/Jetty9ServerAdapter.java
- h2o-jetty-9/src/main/java/water/webserver/jetty9/Jetty9WebsocketServlet.java
- h2o-webserver-iface/src/main/java/water/webserver/iface/H2OHttpView.java
- h2o-webserver-iface/src/main/java/water/webserver/iface/H2OWebsocketServlet.java
Websocket name made it confusing with the Jetty's WebSocket interface
> [PUBDEV-7467] fix H2O Websocket interface name

- h2o-r/tests/testdir_algos/coxph/runit_coxph_predict.R
`stratify_by` seems to produce a different result than in R.
> PUBDEV-6119  add tests for predictions with stratification

- h2o-extensions/xgboost/src/main/java/hex/tree/xgboost/remote/SteamExecutorStarter.java
- h2o-extensions/xgboost/src/test/java/hex/tree/xgboost/remote/SteamExecutorStarterTest.java
- fix deadlock when steam requests stop while a cluster is starting
- improve response handling, ignore messages not related to xgboost
> [PUBDEV-7467] improvements in Steam XGBoost integration

- h2o-core/src/main/java/water/H2O.java
- scripts/jenkins/Makefile.jenkins
- scripts/jenkins/groovy/defineTestStages.groovy
http://mr-0xc1:8080/view/H2O-3/job/h2o-3-nightly-pipeline/job/pavel%252Fpubdev-7647/3/
> PUBDEV-7647 - Java 14 Support

- gradle.properties
- h2o-hadoop-3/assemblyjar.gradle
- h2o-hadoop-3/h2o-cdp7.0-assembly/build.gradle
- h2o-hadoop-common/tests/python/pyunit_connect_invalid.py
- h2o-jetty-8/build.gradle
- h2o-jetty-9/build.gradle
- h2o-jetty-9/src/main/java/water/webserver/jetty9/Jetty9Helper.java
- h2o-jetty-9/src/main/java/water/webserver/jetty9/TransparentProxyServlet.java
- h2o-mapreduce-generic/src/main/java/water/ProxyStarter.java
- scripts/jenkins/config/ldap-jetty-8.txt
- scripts/jenkins/config/ldap-jetty-9.txt
- scripts/jenkins/groovy/defineTestStages.groovy
Removed websockets part, as websockets are not in rel-zahradnik.
> HEXDEV-758 - Upgrade Jetty 9 (merge to rel-zahradnik without websockets)

- h2o-docs/src/product/data-science/stacked-ensembles.rst
Based off of this issue: https://0xdata.atlassian.net/browse/PUBDEV-7547
> PUBDEV-7684: Add monotonicity to StackedEnsemble in User Guide

- docker/scripts/install_R_version
- scripts/benchmark_time_analysis.R
- scripts/jenkins/groovy/compareBenchmarksStage.groovy
- scripts/jenkins/groovy/defineTestStages.groovy
- update method for computing by eliminating outliers
- update settings for jenkins
> [BENCH] update bemchmark checking times

- h2o-py/tests/testdir_algos/gbm/pyunit_PUBDEV_4090_grid_model_seeds.py
- h2o-py/tests/testdir_algos/gbm/pyunit_PUBDEV_7578_gbm_reproducibility.py
Set `score_tree_interval` parameter, which has to be set to reproduce GBM on singlenode and multinode too.
JIRA: https://0xdata.atlassian.net/projects/PUBDEV/issues/PUBDEV-7578
> PUBDEV-7578 fix grid model seeds pyunit test

- h2o-docs/src/product/data-science/algo-params/stopping_metric.rst
- h2o-docs/src/product/data-science/algo-params/stopping_rounds.rst
- h2o-docs/src/product/data-science/algo-params/stopping_tolerance.rst
- h2o-docs/src/product/data-science/early_stopping.rst
- h2o-docs/src/product/data-science/gam.rst
- h2o-docs/src/product/data-science/glm.rst
In response to the updates from https://0xdata.atlassian.net/browse/PUBDEV-7611
> PUBDEV-7656: Update GAM and GLM for early stopping support

- h2o-core/src/main/java/hex/PartialDependence.java
- h2o-py/h2o/h2o.py
- h2o-py/h2o/model/model_base.py
- h2o-py/tests/pyunit_utils/utilsPY.py
- h2o-py/tests/testdir_algos/glm/pyunit_pubdev_6999_glm_interaction_NA.py
- h2o-py/tests/testdir_algos/glrm/pyunit_glrm_PUBDEV_3501_variance_metrics.py
- h2o-py/tests/testdir_algos/glrm/pyunit_glrm_fix_categorical_bug.py
- h2o-py/tests/testdir_jira/pyunit_pubdev_7705.py
- h2o-py/tests/testdir_misc/pyunit_pubdev_5761_pdp_NA.py
Rotate xaxis label for categorical values, fix PDP for row_index=0
> PUBDEV-7705 Fix PDP 

- h2o-algos/src/main/java/hex/gam/GAMModel.java
- h2o-py/h2o/estimators/gam.py
- h2o-py/tests/testdir_algos/gam/pyunit_PUBDEV_7708_check_nlambdas.py
- h2o-r/h2o-package/R/gam.R
This PR completed the job in JIRA: https://0xdata.atlassian.net/browse/PUBDEV-7708
Simple PR to add back parameters defined in GAM.V3 back to GAMParameters.
> PUBDEV-7708 Add GAM parameters in GAM.V3 to GAMParameters

- h2o-docs/build.gradle
- fix previous change removing SW booklet
> [DOCS] remove extra booklet task

- Changes.md
Draft of finished jiras (8/7/2020)
> Release notes for 3.30.1.1

- h2o-py/tests/testdir_algos/glm/pyunit_PUBDEV_7481_lambda_search_alpha_array_multinomial_cv.py
I was not able to experience the bug running off my machine.
I added more debug print out to pinpoint when the failure occurs.
> fix pyunit_PUBDEV_7481_lambda_search_alpha_array_multinomial_cv.py failure

- h2o-dist/index.html
https://0xdata.atlassian.net/browse/PUBDEV-7722
Give users the basic YAML to deploy to kubernetes. With placeholders. This one is the one we use for our CLI tool, it already contains parallel pod management and other fancy stuff, yet is kind-of short and simplistic :wink:
> PUBDEV-7722 - Kubernetes basic installation on download page

- h2o-py/tests/testdir_algos/glm/pyunit_PUBDEV_7481_lambda_alpha_array_gaussian_cv.py
- h2o-py/tests/testdir_algos/glm/pyunit_PUBDEV_7575_lambda_null_alpha_array_binomial_cv.py
I am fixing the other tests that also have cross-validation enabled like here:  https://github.com/h2oai/h2o-3/pull/4855
Fix the other cross-validation tests to choose fold_assignment = 'modulo'
> Fix multinomial cv test fail

- h2o-bindings/bin/custom/R/gen_deeplearning.py
- h2o-bindings/bin/custom/R/gen_drf.py
- h2o-bindings/bin/custom/R/gen_gam.py
- h2o-bindings/bin/custom/R/gen_gbm.py
- h2o-bindings/bin/custom/R/gen_glm.py
- h2o-bindings/bin/custom/R/gen_naivebayes.py
- h2o-bindings/bin/custom/python/gen_deeplearning.py
- h2o-bindings/bin/custom/python/gen_drf.py
- h2o-bindings/bin/custom/python/gen_gam.py
- h2o-bindings/bin/custom/python/gen_gbm.py
- h2o-bindings/bin/custom/python/gen_glm.py
- h2o-bindings/bin/custom/python/gen_naivebayes.py
- h2o-docs/src/product/api-changes.rst
- h2o-py/h2o/estimators/deeplearning.py
- h2o-py/h2o/estimators/gam.py
- h2o-py/h2o/estimators/gbm.py
- h2o-py/h2o/estimators/glm.py
- h2o-py/h2o/estimators/naive_bayes.py
- h2o-py/h2o/estimators/random_forest.py
- h2o-r/h2o-package/R/deeplearning.R
- h2o-r/h2o-package/R/gam.R
- h2o-r/h2o-package/R/gbm.R
- h2o-r/h2o-package/R/glm.R
- h2o-r/h2o-package/R/naivebayes.R
- h2o-r/h2o-package/R/randomforest.R
https://0xdata.atlassian.net/browse/PUBDEV-7637
> PUBDEV-7637 deprecate max_hit_ratio_k

- h2o-extensions/xgboost/src/main/java/hex/tree/xgboost/XGBoost.java
https://0xdata.atlassian.net/browse/PUBDEV-7660
> PUBDEV-7660 add categorical encoding validation

- h2o-docs/src/booklets/v2_2015/source/GLMBooklet.tex
- h2o-docs/src/product/data-science/glm.rst
This was my first time updating a booklet, so please let me know if I need to update anything.
> PUBDEV-7726: Add description of cold_start parameter to GLM booklet/user guide.

- scripts/jenkins/groovy/compareBenchmarksStage.groovy
- scripts/jenkins/groovy/defineTestStages.groovy
Add gam to algo section so that ml-benchmark will run with GAM.
> Add GAM to ml-benchmark.

- h2o-docs/src/product/data-science/gbm-faq/reproducibility.rst
Only tweaked a few things from what you sent me--please let me know if that title question fits.
> PUBDEV-7732: Add doc info about new Reproducibility Info for MOJOs

- h2o-r/h2o-DESCRIPTION.template
- h2o-r/h2o-package.template
- h2o-r/h2o-package/R/datasets.R
https://0xdata.atlassian.net/browse/PUBDEV-7738
> PUBDEV-7738: Fix broken URLs in R docs causing CRAN failures

- h2o-docs/src/product/data-science/gam.rst
- h2o-docs/src/product/grid-search.rst
Please let me know if you would like me to change anything.
> PUBDEV-7721: Add documentation for the new GAM hyperparameter: `subspaces`

- h2o-genmodel/src/main/java/hex/genmodel/attributes/ModelJsonReader.java
https://0xdata.atlassian.net/browse/PUBDEV-7746
> PUBDEV-7746 add int array deserialization

- h2o-genmodel/src/main/java/hex/genmodel/ModelMojoFactory.java
* Add k-LIME MOJO reader to ModelMojoFactory in `rel-zeno`
> Add k-LIME MOJO reader to ModelMojoFactory

- h2o-py/h2o/h2o.py
- h2o-py/tests/testdir_misc/pyunit_logger.py
https://0xdata.atlassian.net/browse/PUBDEV-7755
> Let user define logger config for h2o (library mode)

- h2o-docs/src/product/api-changes.rst
@michalkurka I can add a "future removal section" for 3.32 if you would like--I will just need some guidance as to what will be removed.
> PUBDEV-7759: Correct the API UserGuide formatting

- h2o-bindings/bin/custom/R/gen_rulefit.py
- h2o-bindings/bin/gen_R.py
- h2o-r/h2o-package/R/rulefit.R
https://0xdata.atlassian.net/browse/PUBDEV-7762
Hi, pls review whether this is what was intended
> PUBDEV-7762 fix rulefit model_type argument names in R

- h2o-docs/src/product/data-science.rst
- h2o-docs/src/product/data-science/rulefit.rst
https://0xdata.atlassian.net/browse/PUBDEV-7763
> PUBDEV-7763: Add a RuleFit page to the User Guide

- h2o-r/h2o-package/R/connection.R
- h2o-r/h2o-package/R/frame.R
https://0xdata.atlassian.net/browse/PUBDEV-7779
> PUBDEV-7779: use HTTPS for h2o.jar R package download

- h2o-algos/src/test/java/hex/rulefit/RuleFitTest.java
this is the same issue as https://github.com/h2oai/h2o-3/pull/4894 but in testBestPracticeExample(), I need to update fr by DKV.put(fr) after making changes on it.
> PUBDEV-7720 fix TestBestPracticeExample failing on multinode

- h2o-docs/src/product/data-science/rulefit.rst
Fixing a few things left out of this PR: https://github.com/h2oai/h2o-3/pull/4928
> PUBDEV-7763: Updates to RuleFit user guide page

- h2o-r/tests/testdir_algos/automl/runit_automl_multinomial.R
@erin never noticed this one before, until I saw it failing on Jenkins
> H2OAutoML fixed extra slow R automl test

- h2o-r/h2o-package/R/communication.R
- h2o-r/h2o-package/R/connection.R
- h2o-r/h2o-package/R/coxph.R
- h2o-r/h2o-package/R/datasets.R
- h2o-r/h2o-package/R/frame.R
- h2o-r/h2o-package/R/glrm.R
- h2o-r/h2o-package/R/kvstore.R
- h2o-r/h2o-package/R/models.R
- h2o-r/h2o-package/R/svd.R
https://0xdata.atlassian.net/browse/PUBDEV-7787
> PUBDV-7787: Use HTTPS for all URLs in R package

- h2o-docs/src/product/cloud-integration/ibm-dsx.rst
- h2o-docs/src/product/ibm-dsx.rst
- h2o-py/h2o/h2o.py
- h2o-py/tests/testdir_misc/pyunit_init_https.py
- h2o-r/tests/testdir_misc/runit_init_https.R
This commit changes the same URI at other places too to make it
consistent.
Braeking change appeared in 5a2e67c2ecc8b9061658973c847e85a955ca29af in
conection.R
> fix build - http -> https changes were not propagate to tests

- h2o-bindings/bin/custom/R/gen_coxph.py
- h2o-bindings/bin/custom/R/gen_glrm.py
- h2o-bindings/bin/custom/R/gen_svd.py
- h2o-r/h2o-package/R/coxph.R
- h2o-r/h2o-package/R/glrm.R
- h2o-r/h2o-package/R/svd.R
@satai thanks for catching this error earlier: made the changes to the source files this time and built h2o-3
> PUBDEV-7787: Use HTTPS for all URLs in R package

- h2o-bindings/bin/custom/R/gen_rulefit.py
- h2o-py/tests/testdir_algos/rulefit/pyunit_titanic_rulefit.py
- h2o-r/h2o-package/R/rulefit.R
- h2o-r/tests/testdir_algos/rulefit/runit_rulefit_titanic.R
https://0xdata.atlassian.net/browse/PUBDEV-7720
> PUBDEV-7720: RuleFit tests and docs adjustments

- docker/scripts/install_R_version
- scripts/jenkins/groovy/buildConfig.groovy
I am adding 2 packages -  'IRdisplay', 'plotly'.
I also found couple issues with newer packages and R-3.3, so I attempted to fix them and succeeded as far as I can tell.
> R Jenkins image -  add new suggested packages

- h2o-algos/src/main/java/hex/rulefit/Condition.java
- h2o-algos/src/main/java/hex/rulefit/Rule.java
- h2o-algos/src/main/java/hex/rulefit/RuleEnsemble.java
- h2o-algos/src/main/java/hex/rulefit/RuleFit.java
- h2o-algos/src/main/java/hex/rulefit/RuleFitModel.java
- h2o-algos/src/main/java/hex/schemas/RuleFitV3.java
- h2o-algos/src/main/java/hex/tree/TreeHandler.java
- h2o-algos/src/main/java/hex/tree/TreeUtils.java
- h2o-algos/src/test/java/hex/rulefit/RuleFitTest.java
- h2o-algos/src/test/java/hex/rulefit/RuleFitUtilsTest.java
- h2o-py/h2o/estimators/rulefit.py
- h2o-r/h2o-package/R/rulefit.R
- h2o-r/tests/testdir_algos/rulefit/runit_rulefit_titanic.R
https://0xdata.atlassian.net/browse/PUBDEV-7740
> PUBDEV-7740 rulefit represented by set of rules

- h2o-docs/src/product/automl.rst
https://0xdata.atlassian.net/browse/PUBDEV-7804
- Small updates to automl.rst to reference new features in 3.32.
> PUBDEV-7804: Updates to automl.rst - explain & preprocessing

- h2o-r/h2o-package/R/explain.R
There was a bug picking bottom n features instead of top n features.
> Fix order of pdp plots

- h2o-r/h2o-package/R/connection.R
- allows us to set longer timeout
> [r] use RCurl to download jar

- h2o-core/src/main/java/water/fvec/TransformWrappedVec.java
2 threads trying to ini the chunks could end-up in inconsistent state
> Fix race condition in TransformWrappedVec

- h2o-extensions/xgboost/src/main/java/hex/tree/xgboost/XGBoostUtils.java
- h2o-extensions/xgboost/src/main/java/hex/tree/xgboost/task/XGBoostUploadMatrixTask.java
- h2o-extensions/xgboost/src/test/java/hex/tree/xgboost/XGBoostModelTest.java
- h2o-extensions/xgboost/src/test/java/hex/tree/xgboost/XGBoostUtilsTest.java
- h2o-test-support/src/main/java/water/TestUtil.java
https://0xdata.atlassian.net/browse/PUBDEV-7819
> [PUBDEV-7819] fix counting of non zero rows in chunks

- h2o-r/h2o-DESCRIPTION.template
https://0xdata.atlassian.net/browse/PUBDEV-7844
> PUBDEV-7844: Update ggplot2 required version in R package to 3.3.0

- h2o-algos/src/main/java/hex/generic/GenericModelParameters.java
- h2o-algos/src/test/java/hex/generic/GenericModelTest.java
- h2o-algos/src/test/java/water/MojoDeserializationTest.java
- h2o-genmodel/src/main/java/hex/genmodel/attributes/ModelJsonReader.java
- h2o-genmodel/src/main/java/hex/genmodel/attributes/parameters/KeyValue.java
- h2o-test-support/src/main/java/water/TestUtil.java
> [PUBDEV-7793] implement deserialization of monotone constraints

- h2o-core/src/test/java/water/jdbc/SQLManagerKeyOverwiteTest.java
- avoid name collisions on case-insensitive file-systems
> [test] rename SqlManagerTest

- h2o-algos/src/test/java/hex/generic/GenericModelTest.java
- h2o-genmodel/src/main/java/hex/genmodel/attributes/ModelJsonReader.java
- also make MOJO JSON parsing only log errors, not throw exceptions
> [PUBDEV-7866] Fix parsing of GLM.rand_family params in MOJO JSON

- h2o-genmodel/src/main/java/hex/genmodel/ModelMojoReader.java
JIRA: https://h2oai.atlassian.net/jira/software/c/projects/PUBDEV/issues/PUBDEV-7879
> PUBDEV-7879 fix MOJO check version message

- h2o-algos/src/test/java/hex/grid/SequentialWalkerTest.java
- h2o-core/src/main/java/hex/grid/SequentialWalker.java
https://h2oai.atlassian.net/browse/PUBDEV-7876
> PUBDEV-7876: NPE when starting grid with SequentialWalker in AutoML exploitation phase

- h2o-core/src/main/java/water/api/FramesHandler.java
- h2o-core/src/main/java/water/api/schemas3/FramesV3.java
- h2o-core/src/main/java/water/fvec/Frame.java
- h2o-core/src/test/java/water/fvec/FrameTest.java
- h2o-py/h2o/h2o.py
- h2o-py/tests/testdir_misc/pyunit_export_header.py
- h2o-r/h2o-package/R/export.R
- h2o-r/tests/testdir_misc/runit_export_file_header.R
https://h2oai.atlassian.net/browse/PUBDEV-7838
> PUBDEV-7838: Add 'without quotes' option for header to exportFile

- h2o-py/tests/pyunit_utils/utilsPY.py
@honza:  Thank you for catching the mistakes in javapredict tests.
@michalk:  I implemented your suggestion by specifying --decimal in the java_cmd and it works.  Thanks.  Wendy
> Fixed javapredict failure

- h2o-core/src/main/java/water/api/ModelsHandler.java
- h2o-py/h2o/__init__.py
- h2o-py/h2o/h2o.py
- h2o-py/tests/testdir_apis/H2O_Module/pyunit_h2omodels.py
- h2o-r/h2o-package/R/kvstore.R
- h2o-r/tests/testdir_misc/runit_models.R
- some refactors
- getting actual models objects can be expensive, returning only list of IDs seems like the best choice
> [PUBDEV-7887] ability to list all models in the cluster

- h2o-extensions/mojo-pipeline/src/main/java/hex/mojopipeline/MojoPipeline.java
> [MOJO2] Refactor loading of pipeline to load only metadata, not full pipeline.

- h2o-docs/src/product/data-science/gbm.rst
- h2o-docs/src/product/data-science/xgboost.rst
For: https://h2oai.atlassian.net/browse/PUBDEV-7877
> PUBDEV-7877: Add XGB and GBM feature interactions to docs

- h2o-core/src/main/java/water/fvec/persist/FramePersist.java
- h2o-core/src/test/java/water/fvec/persist/FramePersistTest.java
- h2o-py/tests/testdir_misc/pyunit_frame_reload.py
- need to create a VecGroup so other vec creation does not overwrite Frame's vecs
> [PUBDEV-7859] fix frame loading

- h2o-docs/src/product/data-munging.rst
Waiting for https://github.com/h2oai/h2o-3/pull/5124 to merge. Please let me know if you would like the text changed!
> PUBDEV-7898: Add a link to Data Manipulation page leading to W2V & TE

- h2o-docs/src/product/data-science/algo-params/stratify_by.rst
For https://h2oai.atlassian.net/browse/PUBDEV-7888
> PUBDEV-7888: Added missing Python example to `stratify_by` algo page

- h2o-core/src/main/java/water/H2O.java
- h2o-core/src/main/java/water/JavaVersionSupport.java
- h2o-core/src/test/java/water/JavaVersionSupportTest.java
- h2o-genmodel/src/main/java/water/util/JavaVersionUtils.java
- h2o-r/h2o-package/R/connection.R
This change was originally part of https://github.com/h2oai/h2o-3/pull/5110 - Java 15 support. Separated to be mergeable soon. Please note there is no Java 15 support yet. :wink:
> Refactor Java support handling to be testable. Change the user-facig error.

- h2o-algos/src/test/java/hex/rulefit/RuleFitTest.java
- h2o-test-support/src/main/java/water/TestUtil.java
fix until smalldata/rulefit/repro_bad_cols_bug.csv on jenkins is synchronized from s3
> fast fix smalldata sync problem

- Changes.md
Draft of the release notes (with 22* issues done)
* not including https://h2oai.atlassian.net/browse/PUBDEV-7901 in the release notes
> PUBDEV-7899: Release Notes for 3.32.0.2

- h2o-algos/src/main/java/hex/glm/GLM.java
https://h2oai.atlassian.net/browse/PUBDEV-7875
> PUBDEV-7875 - replace System.out with Log

- h2o-algos/src/main/java/hex/glm/GLM.java
- h2o-algos/src/main/java/hex/glm/GLMModel.java
- h2o-core/src/main/java/hex/ModelBuilder.java
- h2o-py/tests/testdir_algos/glm/pyunit_ordinal_gridsearch_large.py
Fixes multiple issues:
- computeParams was not locking and updating the Model instance
- GLM is not releasing lock on Model instance in computeImpl but only in onCompletion, makint the above impossible
Contains also removal of some unnecessary code.
> [GLM] fix bug where GLM model would have null _input_params

- h2o-algos/src/main/java/hex/glrm/GLRMModel.java
- h2o-algos/src/test/java/water/ModelSerializationTest.java
- h2o-core/src/main/java/water/H2O.java
- h2o-core/src/main/java/water/fvec/Frame.java
- h2o-py/tests/testdir_algos/glrm/pyunit_glrm_grid_user_y.py
GLRM model fails to load for multiple reasons:
- asymetric write/load functions
- frame.readAll_impl not working properly
> [GLRM] fix de-serialization of GLRM models

- h2o-docs/src/product/automl.rst
https://h2oai.atlassian.net/browse/PUBDEV-7869
> PUBDEV-7869: Updating AutoML citation in User Guide

- h2o-py/h2o/model/model_base.py
- h2o-py/tests/testdir_misc/pyunit_pubdev_7828_show_NAs_in_numeric_PDP.py
- h2o-r/h2o-package/R/models.R
- h2o-r/tests/testdir_misc/runit_PUBDEV_7828_show_NAs_in_numeric_PDP.R
https://h2oai.atlassian.net/browse/PUBDEV-7828
2D PDPs will be done in a separate PR.
> show missing values in numeric PDPs

- h2o-docs/src/product/data-science/rulefit.rst
For: https://h2oai.atlassian.net/browse/PUBDEV-7922
Thanks for the catch, @neemah2o!
> PUBDEV-7922: RuleFit Python example corrections

- h2o-algos/src/main/java/hex/rulefit/RuleEnsemble.java
- h2o-algos/src/main/java/hex/rulefit/RuleFit.java
- h2o-algos/src/main/java/hex/tree/TreeStats.java
- h2o-algos/src/test/java/hex/tree/TreeStatsTest.java
- h2o-py/tests/testdir_algos/rulefit/pyunit_titanic_rulefit.py
- h2o-r/tests/testdir_algos/rulefit/runit_rulefit_titanic.R
https://h2oai.atlassian.net/browse/PUBDEV-7912
combined model summary information of tree ensemble, rule ensemble and resulting linear model
> PUBDEV-9712: add model_summary to rulefit models

- h2o-algos/src/main/java/hex/gam/GAMModel.java
- h2o-algos/src/main/java/hex/schemas/GAMV3.java
- h2o-py/h2o/estimators/gam.py
- h2o-py/tests/testdir_algos/deeplearning/pyunit_generate_synthetic_DL_data.py
- h2o-py/tests/testdir_algos/gam/pyunit_generate_synthetic_GAM_data.py
- h2o-py/tests/testdir_algos/gbm/pyunit_generate_synthetic_GBM_data.py
- h2o-py/tests/testdir_algos/glm/pyunit_generate_synthetic_GLM_data.py
- h2o-r/h2o-package/R/gam.R
Karthik is starting work on automatic choosing of scale parameter.  Hence I am adding this one for him to be able to generate data for himself.
> Add GAM synthetic generation code in Python.

- h2o-bindings/bin/custom/R/gen_coxph.py
- h2o-bindings/bin/custom/R/gen_gam.py
- h2o-bindings/bin/custom/python/gen_coxph.py
- h2o-bindings/bin/custom/python/gen_gam.py
- h2o-core/src/main/java/hex/Model.java
- h2o-core/src/main/java/hex/ModelBuilder.java
- h2o-core/src/test/java/hex/ModelBuilderTest.java
- h2o-py/h2o/estimators/coxph.py
- h2o-py/h2o/estimators/estimator_base.py
- h2o-py/h2o/estimators/gam.py
- h2o-r/h2o-package/R/coxph.R
- h2o-r/h2o-package/R/gam.R
- h2o-test-support/src/main/java/water/test/dummy/DummyModelParameters.java
- improves flow UX
- makes our REST API easier to use
- is backwards compatible, only eliminates error states
> [PUBDEV-7706] Unignore ignored columns that are used

- h2o-py/h2o/explanation/_explain.py
- h2o-py/h2o/frame.py
- h2o-py/h2o/utils/ext_dependencies.py
Change warning to be more user friendly.
> Fix warning from matplotlib in explain

- h2o-r/tests/runitUtils/utilsR.R
Locally tested, I will merge it if all tests pass.
> Fix failing R tests related to date time handling

- h2o-algos/src/main/java/hex/DataInfo.java
- h2o-algos/src/main/java/hex/glm/GLM.java
- h2o-algos/src/test/java/hex/glm/GLMBetaConstraintsEncoderTest.java
- h2o-algos/src/test/java/hex/glm/GLMTest.java
- h2o-core/src/main/java/water/util/ArrayUtils.java
- h2o-core/src/main/java/water/util/FrameUtils.java
- h2o-py/tests/testdir_algos/glm/pyunit_PUBDEV-7473-allow_beta_constraints_for_categorical_columns.py
- h2o-r/tests/testdir_algos/glm/runit_PUBDEV-7473-allow_beta_constraints_for_categorical_columns.R
https://h2oai.atlassian.net/browse/PUBDEV-7473
> PUBDEV-7473 allow include categorical column name in beta constraints

- h2o-py/src/main/java/water/H2OApp.java
- h2o-r/h2o-package/R/connection.R
- make-dist.sh
I have implemented feedback from Joseph. Only minor changes, I decided to edit hint from h2o.connect() to h2o.connect(ip="hostname", port=number) as @honzasterba suggested in the old PR because h2o.connect() with default setting is more or less the same as h2o.init(). It is better to remind ip and hostname to user in my opinion.
Thank you
https://h2oai.atlassian.net/browse/PUBDEV-7861
> PUBDEV-7861 - Feedback for standalone r client implementation

- h2o-core/src/main/java/water/AutoBuffer.java
- h2o-core/src/main/java/water/persist/PersistFS.java
- fix AutoBufferException to correctly report cause
- fix some formatting issues
> [misc] minor improvements

- h2o-algos/src/main/java/hex/tree/DHistogram.java
- h2o-algos/src/main/java/hex/tree/GlobalQuantilesCalc.java
- h2o-algos/src/main/java/hex/tree/SharedTree.java
- h2o-algos/src/test/java/hex/rulefit/RuleFitUtilsTest.java
- h2o-algos/src/test/java/hex/tree/DHistogramTest.java
- h2o-algos/src/test/java/hex/tree/GlobalQuantilesCalcTest.java
- h2o-algos/src/test/java/hex/tree/drf/DRFTest.java
- h2o-algos/src/test/resources/hex/tree/categorical.json
There is also an issue that the level of freedom is always nbins-1
as opposed to nbins, this is a minor issue in most settings
but it can theoretically change results (=trees will look different).
> Fix histogram type = random for nbins = 2

- h2o-docs/src/product/data-science/rulefit.rst
- h2o-docs/src/product/variable-importance.rst
For https://h2oai.atlassian.net/browse/PUBDEV-7822
So, I shifted the "Tree-Based Algorithms" section down to the bottom of the page so it could be next to the added "Non-Tree-Based Algorithms" (also, if you think of a better name for this, let me know). Please let me know if you would like anything updated!
> PUBDEV-7822: Fill in Variable Importance user guide page with info about non-tree-based models

- h2o-core/src/main/java/water/persist/PersistManager.java
- h2o-core/src/test/java/water/persist/PersistManagerTest.java
https://h2oai.atlassian.net/browse/PUBDEV-7923
> PUBDEV-7923: Ignore metadata files when importing from Delta Lake

- Changes.md
> 3.32.0.3 Release Notes

- templates/gcp/.gitignore
- templates/gcp/h2ocluster/packer/h2o-gcp-image.json
- templates/gcp/h2ocluster/packer/scripts/bootstrap.sh
- templates/gcp/h2ocluster/terraform/h2ocluster.sh
- templates/gcp/h2ocluster/terraform/main.tf
- templates/gcp/h2ocluster/terraform/modules/h2ocluster/main.tf
- templates/gcp/h2ocluster/terraform/modules/h2ocluster/startup.sh
- templates/gcp/h2ocluster/terraform/modules/h2ocluster/variables.tf
- templates/gcp/h2ocluster/terraform/terraform.tfvars
- templates/gcp/h2ocluster/terraform/variables.tf
- templates/gcp/network/modules/service-accounts/main.tf
- templates/gcp/network/modules/workspace/startup.sh
Edited packer image to include Simba JDBC drivers for Bigquery
Creating user ssh key and assigning to h2ocluster instances to ease ssh-ing to them
Validated BQ data pull using the service account associated with the instances of the cluster in Single and Distributed model
> GCP BigQuery connect

- h2o-hadoop-common/tests_multinode/R/runit_kmeans_converge_large.R
JIRA: https://h2oai.atlassian.net/jira/software/c/projects/PUBDEV/issues/PUBDEV-7374
> PUBDEV-7374 Fix Kmeans converge test

- h2o-algos/src/test/java/hex/generic/GenericModelTest.java
- h2o-test-support/src/main/java/water/TestUtil.java
testJavaScoring_mojo_cox_ph_categorical sometimes had small relative differences
of big numbers.
> Fix random error in GenericModelTest

- h2o-algos/src/main/java/hex/gam/GAM.java
- h2o-algos/src/main/java/hex/glm/GLM.java
- h2o-algos/src/main/java/hex/glm/GLMTask.java
- h2o-algos/src/test/java/hex/gam/GamTestPiping.java
- h2o-py/tests/testdir_algos/gam/pyunit_PUBDEV_7181_check_model_scoring.py
- h2o-py/tests/testdir_algos/gam/pyunit_PUBDEV_7932_gam_scale_parameter.py
This PR fixes the bug described in JIRA: https://h2oai.atlassian.net/browse/PUBDEV-7932.
I fixed the bug in the backend and added Junit and Python unit tests to make sure the fix actually works.
> PUBDEV-7932: fixed bug with scale parameter.

- h2o-algos/src/main/java/hex/glm/ComputationState.java
- h2o-algos/src/main/java/hex/glm/GLM.java
Added code to invoke the correct GLMGradientSolver to make sure GAM related variables are not null.
> Fixed NPE by invoking the correct GLMGradientSolver when gam is running.

- h2o-py/tests/testdir_algos/xgboost/pyunit_H2OXGBoost_native_XGBoost_mixed_binomial_compare_large_sparse_singleNode.py
The calculation is sensitive to #CPU cores
> Relax tolerance in comparison of native AUCPR vs h2o AUCPR

- h2o-docs/src/product/explain.rst
https://h2oai.atlassian.net/browse/PUBDEV-7963
> PUBDEV-7963: Fixing bug in Explain user guide code

- h2o-core/src/main/java/hex/Model.java
- h2o-core/src/main/java/water/util/ArrayUtils.java
- h2o-core/src/test/java/water/util/ArrayUtilsTest.java
Idea is to prevent too large messages and to avoid logs flooded with warn messages on datasets having categoricals with large cardinalities.
Example currently (and it's just a tiny sample):
```
01-26 11:36:09.676 127.0.0.1:16629       15633      FJ-1-7  WARN water.default: Test/Validation dataset column 'V56' has levels not trained on: ["10025", "10036", "10104", "10111", "10160", "10212", "1024", "10246", "10251", "10265", "10267", "1027", "10298", "10377", "10394", "1043", "10467", "10608", "10623", "10653", "10689", "10722", "10793", "10795", "1081", "10821", "10852", "10868", "10883", "10893", "10936", "10976", "10992", "11003", "11062", "11121", "11173", "11185", "11191", "11193", "11249", "11252", "11326", "1134", "11371", "11439", "11454", "1155", "11676", "11682", "11773", …
```
> Model validation: don't print all missing levels 

- LICENSE
- h2o-docs/src/product/conf.py
- h2o-py/docs/conf.py
For: https://h2oai.atlassian.net/browse/PUBDEV-7983
> PUBDEV-7983: Updated copyright year

- Changes.md
Draft with 8 issues done
"*" next to "In progress" issues
> PUBDEV-7981: 3.32.0.4 Release Notes

- h2o-algos/src/main/java/hex/coxph/CoxPH.java
- h2o-algos/src/main/java/hex/coxph/CoxPHModel.java
- h2o-core/src/main/java/water/util/ArrayUtils.java
- h2o-core/src/test/java/water/util/ArrayUtilsTest.java
- h2o-r/tests/testdir_algos/coxph/runit_coxph_offset.R
* PUBDEV-7987 test case
* PUBDEV-7987 add offset value to prediction calculation
> PUBDEV-7987 prediction CoxPH with offset_column

- h2o-docs/src/product/data-science/glm.rst
For: https://h2oai.atlassian.net/browse/PUBDEV-7917
> PUBDEV-7917: Add checkpoint description to GLM

- h2o-web/bower.json
> [PUBDEV-7579] upgrade flow

- h2o-algos/src/main/java/hex/deeplearning/DeepLearningModelInfo.java
- h2o-docs/src/product/data-science/deep-learning.rst
https://h2oai.atlassian.net/browse/PUBDEV-8003
Minor documentation issues related to deep learning.
> PUBDEV-8003: Fix notes about learn.h2o.ai

- scripts/jenkins/groovy/defineTestStages.groovy
- python is not available/needed on k8s images
> [test] fix stage config for k8s tests

- h2o-algos/src/main/java/hex/glm/GLM.java
- h2o-algos/src/test/java/hex/glm/GLMBetaConstraintsEncoderTest.java
- h2o-core/src/main/java/water/util/FrameUtils.java
this will help to investigate why https://github.com/h2oai/sparkling-water/blob/master/py/tests/unit/with_runtime_sparkling/test_glm.py#L180 is failing in SW
> [fix] add debug logs during beta constraints encoding

- h2o-py/h2o/explanation/_explain.py
- h2o-py/tests/testdir_misc/pyunit_explain.py
- h2o-r/h2o-package/R/kvstore.R
- h2o-r/tests/testdir_jira/runit_pubdev_8013.R
https://h2oai.atlassian.net/browse/PUBDEV-8013
> PUBDEV-8013: Make model@model$parameters$x report actual features

- h2o-py/h2o/explanation/_explain.py
As explained in the ticket there is no keys for ICE plot:
https://h2oai.atlassian.net/browse/PUBDEV-7998
Not sure if I fixed this in right way but it's working for me. Made it same as PDP plots.
> PUBDEV-7998: Fixed ICE plots keys issue

- Changes.md
With 3 issues completed
(also minor update to previous release date -- updated to 2021)
> PUBDEV-8048: 3.32.0.5 Release Notes

- h2o-r/h2o-DESCRIPTION.template
https://h2oai.atlassian.net/browse/PUBDEV-7894
> PUBDEV-7894: Adding Java constraint to R DESCRIPTION file

- h2o-docs/src/product/data-science/xgboost.rst
for: https://h2oai.atlassian.net/browse/PUBDEV-7988
> PUBDEV-7988: added missing params to xgboost

- h2o-extensions/xgboost/src/test/java/hex/tree/xgboost/XGBoostTest.java
As demonstrated in https://github.com/h2oai/h2o-3/pull/5373/files sigmoid transformation
implemented on GPU gives different result than when running on CPU, therefore we pick a lower tolerance
This doesn't affect production results because native xgboost scoring
is only used in test. For all other scoring java scoring is used.
> Relax XGBoost tolerance on GPU when comparing java and native predictions

- h2o-docs/src/product/logs.rst
For: https://h2oai.atlassian.net/browse/PUBDEV-7992
Closed the original merging into zermelo; now merging into master
> PUBDEV-7992: Add more information about log files in User Guide 

- scripts/jenkins/Makefile.jenkins
Give a fix advice for build-h2o-3 jenkins script
> Build message improvement

- h2o-algos/src/main/java/hex/ensemble/StackedEnsemble.java
- h2o-algos/src/main/java/hex/ensemble/StackedEnsembleModel.java
- h2o-algos/src/main/java/hex/ensemble/StackedEnsembleMojoWriter.java
- h2o-algos/src/main/java/hex/schemas/StackedEnsembleV99.java
- h2o-algos/src/test/java/hex/ensemble/StackedEnsembleTest.java
- h2o-automl/src/main/java/ai/h2o/automl/modeling/StackedEnsembleStepsProvider.java
- h2o-genmodel/src/main/java/hex/genmodel/algos/ensemble/StackedEnsembleMojoModel.java
- h2o-genmodel/src/main/java/hex/genmodel/algos/ensemble/StackedEnsembleMojoReader.java
- h2o-py/h2o/estimators/stackedensemble.py
- h2o-py/tests/testdir_algos/stackedensemble/pyunit_stackedensemble_mojo.py
- h2o-r/h2o-package/R/stackedensemble.R
https://h2oai.atlassian.net/browse/PUBDEV-8032
> PUBDEV-8032: Stacked Ensemble: Take logit of cvpreds before training the metalearner for classification

- h2o-py/h2o/frame.py
- h2o-py/tests/testdir_misc/pyunit_import_upload_singlequoted.py
- h2o-r/h2o-package/R/parse.R
- h2o-r/tests/runitUtils/utilsR.R
- h2o-r/tests/testdir_misc/runit_import_upload_singlequoted.R
https://h2oai.atlassian.net/browse/PUBDEV-7996
> PUBDEV-7996: single_quote parse setup result param not forwarded to parser

- h2o-py/tests/pyunit_utils/utilsPY.py
fallback mechanism to be implemented on all APIs and improved in a future ticket
> for Py tests locate falls back to http call

- h2o-docs/src/product/data-science/algo-params/metalearner_transform.rst
- h2o-docs/src/product/data-science/stacked-ensembles.rst
- h2o-docs/src/product/parameters.rst
Documentation for metalearner transform.
> Add metalearner transform documentation

- h2o-algos/src/main/java/hex/ensemble/Metalearners.java
- h2o-automl/src/main/java/ai/h2o/automl/modeling/DeepLearningStepsProvider.java
- h2o-automl/src/main/java/ai/h2o/automl/modeling/StackedEnsembleStepsProvider.java
- h2o-docs/src/product/automl.rst
https://h2oai.atlassian.net/browse/PUBDEV-8070
Ready for review!
> AutoML optimizations: Fewer neurons in DL grids & Stacked Ensemble metalearner improvements

- h2o-automl/src/main/java/ai/h2o/automl/modeling/DeepLearningStepsProvider.java
- h2o-automl/src/main/java/ai/h2o/automl/modeling/StackedEnsembleStepsProvider.java
https://h2oai.atlassian.net/browse/PUBDEV-8070
> AutoML: Fewer neurons in DL grids and a logit transform for classification models

- h2o-algos/src/main/java/hex/ensemble/Metalearners.java
- h2o-automl/src/main/java/ai/h2o/automl/modeling/DeepLearningStepsProvider.java
- h2o-automl/src/main/java/ai/h2o/automl/modeling/StackedEnsembleStepsProvider.java
PR only for testing purposes (so tests are done if we want/need to merge):
- benchmarking against https://github.com/h2oai/h2o-3/pull/5392
> AutoML experiment with alpha 1.0 metalearner

- Changes.md
> 3.32.1.1 Release Notes

- h2o-py/tests/testdir_algos/glrm/pyunit_glrm_grid_user_y.py
I need to check that the following archetypes are different.  Instead of just looking at one pair, I compare all pairs of archetypes.
> Fix pyunit_glrm_grid_user_y.py failure

- h2o-docs/src/product/data-science/gbm.rst
- h2o-docs/src/product/data-science/xgboost.rst
- h2o-py/h2o/model/model_base.py
- h2o-r/h2o-package/R/models.R
For: https://h2oai.atlassian.net/browse/PUBDEV-8067
Also fixed the spacing for path param in model_base.py.
> PUBDEV-8067: Add info about ability to export xlsx file from new addition .feature_interaction()

- h2o-algos/src/main/java/hex/glm/ComputationState.java
- h2o-algos/src/main/java/hex/glm/GLM.java
- h2o-algos/src/main/java/hex/glm/GLMTask.java
- h2o-algos/src/test/java/hex/glm/GLMBasicTestMultinomial.java
- h2o-py/tests/testdir_algos/glm/pyunit_PUBDEV_8079_rollup_stats.py
This PR fixes the problem in JIRA: https://h2oai.atlassian.net/browse/PUBDEV-8079.
Thanks to @tomasfryda who pinpointed the error relating to added vectors "__glm_ExpC","__glm_ExpNPC" or "__glm_sumExp", "__glm_maxRow" and providing me with a short test example to quickly run and run into the error.
> PUBDEV-8079 fix rollup stats bug

- h2o-core/src/test/java/hex/ModelBuilderTest.java
By using explic number of chunks
> Make ApproximatingHoldoutPredictionCombiner test reproducible

- h2o-core/src/main/java/water/H2O.java
- h2o-core/src/main/java/water/H2ONode.java
- h2o-core/src/main/java/water/Paxos.java
- h2o-core/src/main/java/water/api/CloudHandler.java
- h2o-core/src/test/java/water/H2ONodeTest.java
- h2o-core/src/test/java/water/H2OTest.java
Found by @wendycwong in http://mr-0xg1:8080/job/h2o-3-benchmark-pipeline/job/master/603/artifact/gbm-benchmark-client/h2o-3/h2o-client_gbm-client_1_603.log
> Make sure CloudHandler works in client mode with no members

- h2o-core/src/test/java/water/NodeLocalEventCollectingListener.java
- h2o-core/src/test/java/water/TCPReceiverThreadTest.java
Make sure wait at least 200ms between tests because TCPReceiverTest
has 100ms wait on error
> Fix TCPReceiverThreadTest

- h2o-bindings/src/main/java/water/bindings/examples/Example.java
- h2o-core/src/main/java/water/api/ParseHandler.java
- h2o-core/src/main/java/water/api/schemas3/ParseSetupV3.java
- h2o-core/src/main/java/water/api/schemas3/ParseV3.java
- h2o-core/src/main/java/water/parser/ARFFParser.java
- h2o-core/src/main/java/water/parser/CsvParser.java
- h2o-core/src/main/java/water/parser/DefaultParserProviders.java
- h2o-core/src/main/java/water/parser/ParseSetup.java
- h2o-core/src/main/java/water/parser/Parser.java
- h2o-core/src/test/java/water/parser/CsvParserTest.java
- h2o-py/h2o/frame.py
- h2o-py/h2o/h2o.py
- h2o-py/tests/testdir_misc/pyunit_import_upload_singlequoted.py
- h2o-r/h2o-package/R/import.R
- h2o-r/h2o-package/R/parse.R
- h2o-r/tests/testdir_misc/runit_import_upload_singlequoted.R
https://h2oai.atlassian.net/browse/PUBDEV-8087
> PUBDEV-8087 custom escape character

- h2o-algos/src/main/java/hex/tree/SharedTree.java
- h2o-core/src/main/java/hex/ModelBuilder.java
- h2o-extensions/xgboost/src/main/java/hex/tree/xgboost/XGBoost.java
- h2o-py/tests/pyunit_utils/utilsPY.py
- h2o-py/tests/testdir_algos/glm/pyunit_PUBDEV_7645_lambda_search_warning.py
- h2o-py/tests/testdir_jira/pyunit_pubdev_6249_reproducible_stopping_warn.py
> PUBDEV-6249: Produce a warning if early stopping is not reproducible

- h2o-r/tests/testdir_jira/runit_pubdev_2441_pvalue_w_offset_gaussian.R
- h2o-r/tests/testdir_jira/runit_pubdev_2441_pvalue_w_offset_tweedie.R
Added debug printing to print out
h2o p-values, r p-values for GLM so that we can see what the problem is.
> Fix runit_pubdev_2441_pvalue_w_offset.R failure

- h2o-algos/src/main/java/hex/rulefit/RuleFit.java
- h2o-algos/src/main/java/hex/schemas/RuleFitV3.java
- h2o-algos/src/test/java/hex/rulefit/RuleFitTest.java
- h2o-py/h2o/estimators/rulefit.py
- h2o-py/tests/testdir_algos/rulefit/pyunit_titanic_rulefit.py
- h2o-r/h2o-package/R/rulefit.R
- h2o-r/tests/testdir_algos/rulefit/runit_rulefit_titanic.R
https://h2oai.atlassian.net/browse/PUBDEV-7955
> PUBDEV-7955: rulefit validation

- scripts/jenkins/groovy/buildConfig.groovy
https://h2oai.atlassian.net/browse/PUBDEV-8124
> PUBDEV-8124: Update git jenkins credentials

- h2o-automl/src/main/java/ai/h2o/automl/modeling/StackedEnsembleStepsProvider.java
- h2o-docs/src/product/automl.rst
https://h2oai.atlassian.net/browse/PUBDEV-8118
> PUBDEV-8118: AutoML improvements: add more regularization to GLM metalearner

- Changes.md
> 3.32.1.2 Release notes

- scripts/jenkins/groovy/compareBenchmarksStage.groovy
Also:   java.lang.LinkageError: loader (instance of  org/jenkinsci/plugins/workflow/cps/CpsGroovyShell$CleanGroovyClassLoader): attempted  duplicate class definition for name: "MyEnvClearer"
at java.lang.ClassLoader.defineClass1(Native Method)
at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
at groovy.lang.GroovyClassLoader.access$400(GroovyClassLoader.java:62)
at groovy.lang.GroovyClassLoader$ClassCollector.createClass(GroovyClassLoader.java:500)
> Use simple echo in benchmarks pipeline, old one was crashing Jenkins

- scripts/jenkins/groovy/compareBenchmarksStage.groovy
https://h2oai.atlassian.net/browse/ITA-945
> ITA-945 adjust benchmarks training time expected intervals

- h2o-docs/src/product/api-changes.rst
- h2o-docs/src/product/data-science/algo-params/auc_type.rst
- h2o-docs/src/product/grid-search.rst
- h2o-docs/src/product/security.rst
- h2o-docs/src/product/welcome.rst
For: https://h2oai.atlassian.net/browse/PUBDEV-8119
Two things:
1. The "welcome.rst" python lexing fix is only a possibility. I tried a bunch of different formats and this is the only way I've found that keeps all the information and still lexes properly.
2. I am not entirely sure how to fix the duplicate label warning for the mojo/pojo-quickstarts so any guidance would be greatly appreciated.
> PUBDEV-8119: Local Build formatting fixes

- h2o-automl/src/main/java/ai/h2o/automl/AutoML.java
- h2o-r/h2o-package/R/connection.R
- h2o-r/h2o-package/R/explain.R
- h2o-r/h2o-package/R/zzz.R
https://h2oai.atlassian.net/browse/PUBDEV-8145
> PUBDEV-8145: Fix R package based on CRAN feedback

- h2o-algos/src/main/java/hex/tree/SharedTreeModelWithContributions.java
- h2o-core/src/main/java/hex/Model.java
- h2o-core/src/main/java/water/api/ModelMetricsHandler.java
- h2o-genmodel/src/main/java/hex/genmodel/PredictContributions.java
- h2o-genmodel/src/main/java/hex/genmodel/algos/tree/ContributionComposer.java
- h2o-genmodel/src/main/java/hex/genmodel/algos/tree/ContributionsPredictor.java
- h2o-genmodel/src/main/java/hex/genmodel/easy/EasyPredictModelWrapper.java
- h2o-py/h2o/model/model_base.py
- h2o-py/tests/testdir_algos/gbm/pyunit_gbm_predict_contributions_categorical_sorting.py
- h2o-py/tests/testdir_algos/gbm/pyunit_gbm_predict_contributions_sorting.py
- h2o-py/tests/testdir_algos/gbm/pyunit_gbm_predict_contributions_sorting_large.py
- h2o-py/tests/testdir_algos/rf/pyunit_rf_predict_contributions_sorting_smoke.py
- h2o-r/h2o-package/R/models.R
- h2o-r/tests/testdir_algos/gbm/runit_GBM_predict_contribs_sort.R
- h2o-r/tests/testdir_algos/randomforest/runit_RF_predict_contribs_sort.R
https://h2oai.atlassian.net/browse/PUBDEV-7937
merge after: https://github.com/h2oai/h2o-3/pull/5494
> PUBDEV-7937 - rename parameters

- Changes.md
> PUBDEV-8153: 3.32.1.3 Release Notes

- h2o-genmodel/src/main/java/hex/genmodel/PredictContributions.java
- h2o-genmodel/src/main/java/hex/genmodel/algos/tree/ContributionComposer.java
- h2o-genmodel/src/main/java/hex/genmodel/algos/tree/ContributionsPredictor.java
- h2o-genmodel/src/main/java/hex/genmodel/easy/EasyPredictModelWrapper.java
Hi @sebhrusen, I forgot to rename abs parameter in MOJO and improve the documentation in MOJO and Java. Can you please approve this? It should be the same as https://github.com/h2oai/h2o-3/pull/5493
> PUBDEV-7937 - rename forgoten abs parameter in mojo

- Changes.md
Included missing https://h2oai.atlassian.net/browse/PUBDEV-8145
> PUBDEV-8153: Updated 3.32.1.3 Release notes

- README.md
- h2o-bindings/bin/pyparser.py
- h2o-bindings/bin/pyunit_parser_test.py
- h2o-dist/index.html
- h2o-docs/src/product/downloading.rst
- h2o-docs/src/product/welcome.rst
- h2o-py/conda/h2o/meta.yaml
- h2o-py/docs/intro.rst
- h2o-py/h2o/backend/__init__.py
- h2o-py/h2o/demos.py
- h2o-py/h2o/utils/debugging.py
- h2o-py/h2o/utils/progressbar.py
- h2o-py/requirements.txt
- h2o-py/setup.py
- h2o-py/test-requirements.txt
- h2o-py/tests/testdir_javapredict/pyunit_mojo.py
- scripts/jenkins/jenkinsfiles/Jenkinsfile-Release
https://h2oai.atlassian.net/browse/PUBDEV-8152
> PUBDEV-8152: remove dependency on colorama

- scripts/jenkins/groovy/compareBenchmarksStage.groovy
- scripts/jenkins/groovy/defineTestStages.groovy
We do not use client mode in Sparkling Water anymore
> ITA-0000: GBM-client benchmark is no longer needed

- h2o-docs/src/product/performance-and-prediction.rst
In H2O, the actual results display in the **rows** and the predictions display in the **columns**
> Act/Pred in Confusion Matrix

- h2o-py/h2o/automl/autoh2o.py
- h2o-py/h2o/estimators/estimator_base.py
- h2o-py/tests/testdir_algos/automl/pyunit_automl_model_selection.py
- h2o-py/tests/testdir_algos/automl/pyunit_automl_params_attributes.py
https://h2oai.atlassian.net/browse/PUBDEV-8170
> PUBDEV-8170: expose AutoML args as writeable properties until first call to train

- h2o-py/h2o/sklearn/wrapper.py
- h2o-py/h2o/utils/metaclass.py
- h2o-py/tests/pyunit_utils/utilsPY.py
- h2o-py/tests/testdir_algos/targetencoder/pyunit_te_deprecated_params.py
- h2o-py/tests/testdir_sklearn/pyunit_sklearn_classification_all_estimators.py
- h2o-py/tests/testdir_utils/pyunit_h2oconfig.py
https://h2oai.atlassian.net/browse/PUBDEV-8146
> PUBDEV-8146: fix small Py2 issues after introducing deprecation wrappers.

- h2o-bindings/bin/custom/python/gen_stackedensemble.py
- h2o-py/h2o/automl/autoh2o.py
- h2o-py/h2o/estimators/estimator_base.py
- h2o-py/h2o/estimators/stackedensemble.py
- h2o-py/h2o/grid/grid_search.py
- h2o-py/h2o/utils/metaclass.py
- h2o-py/tests/testdir_algos/automl/pyunit_automl_train.py
- h2o-py/tests/testdir_algos/gbm/pyunit_gbm_train_api.py
- h2o-py/tests/testdir_algos/grid/pyunit_grid_train_api.py
https://h2oai.atlassian.net/browse/PUBDEV-8180
> PUBDEV-8180: uniform Python API to retrieve trained model(s)/leader

- h2o-web/bower.json
https://h2oai.atlassian.net/browse/PUBDEV-8188
> PUBDEV-8188: upgrade flow

- h2o-py/h2o/job.py
- h2o-py/h2o/utils/progressbar.py
- h2o-py/tests/testdir_misc/pyunit_job_progress_custom_widget.py
- h2o-py/tests/testdir_utils/pyunit_progressbar.py
https://h2oai.atlassian.net/browse/PUBDEV-8196
@AakashKumarNain see the tests in this ticket for an example on how to plug your own "widgets".
And please confirm that this is what you need.
> PUBDEV-8196: Custom widgets injection for Python progress bar

- h2o-algos/src/main/java/hex/glm/GLMModel.java
- h2o-algos/src/main/java/hex/glm/GLMScore.java
- h2o-genmodel/src/main/java/hex/genmodel/algos/glm/GlmOrdinalMojoModel.java
- h2o-py/tests/testdir_algos/glm/pyunit_pubdev_8194_ordinal_fail.py
- h2o-py/tests/testdir_javapredict/pyunit_pubdev_5008_ordinal_glm_mojo_pojo_large.py
- h2o-r/tests/runitUtils/utilsR.R
- h2o-r/tests/testdir_algos/glm/runit_PUBDEV_5008_5386_ordinal_glm_nidhi_R.R
- h2o-r/tests/testdir_javapredict/runit_PUBDEV_5058_PUBDEV_5723_glrm_mojo_large.R
- h2o-r/tests/testdir_javapredict/runit_PUBDEV_5355_binomial_glm_mojo_large.R
This PR fixes the bug in JIRA: https://h2oai.atlassian.net/browse/PUBDEV-8194
Found bug in ordinal prediction in class prediction.  Added pyunit test from user who reported this bug.
> PUBDEV-8194 ordinal prediction fail

- h2o-py/tests/pyunit_utils/utilsPY.py
- h2o-py/tests/testdir_misc/pyunit_job_progress_custom_widget.py
- h2o-py/tests/testdir_utils/pyunit_progressbar.py
https://h2oai.atlassian.net/browse/PUBDEV-8196
> PUBDEV-8196: fix widget injection for ProgressBar in Py2

- h2o-core/build.gradle
This fixes race conditions in Icer generators
> PUBDEV-8219: Update to the latest version of Javassist (3.28)

- h2o-docs/src/product/mojo-quickstart.rst
For: https://h2oai.atlassian.net/browse/PUBDEV-8151
I added the note in the MOJO FAQ. Please let me know if anything should be changed!
> PUBDEV-8151: Added C++ support note to productionizing docs

- Changes.md
> 3.32.1.4 Release Notes [nocheck]

- Changes.md
For: https://h2oai.atlassian.net/browse/PUBDEV-8238
Closer to older, more organized format.
> PUBDEV-8238: Update Changelog Format [nocheck]

- h2o-genmodel/src/main/java/hex/genmodel/tools/PredictCsv.java
Its a side-effect enhancement, from your https://h2oai.atlassian.net/browse/PUBDEV-8172.
> PUBDEV-8172 - refactor PredictCsv to use getter for model

- h2o-py/h2o/frame.py
> Fix minor typo

- h2o-algos/src/main/java/hex/glm/ComputationState.java
- h2o-algos/src/main/java/hex/glm/GLM.java
- h2o-algos/src/main/java/hex/glm/GLMModel.java
- h2o-algos/src/main/java/hex/glm/GLMTask.java
- h2o-algos/src/main/java/hex/optimization/OptimizationUtils.java
- h2o-py/tests/testdir_algos/glm/pyunit_pubdev_8190-remove-collinear-columns-multinomial_jeffP.py
This PR address the failure reported in JIRA: https://h2oai.atlassian.net/browse/PUBDEV-8190
Basically, when remove_collinear_columns=True, the dimension of gradient and coefficients change when predictors are removed.  Hopefully, I have taken care of all the confusion.
> PUBDEV-8190 : fix multinomial remove collinear columns failure

- h2o-core/src/main/java/water/fvec/CreateInteractions.java
- h2o-r/tests/testdir_jira/runit_pubdev_8218.R
https://h2oai.atlassian.net/browse/PUBDEV-8218
it was considering some cases as a self-interaction when it was not true
> PUBDEV-8218: fix h2o interaction outcomes

- h2o-py/h2o/h2o.py
- h2o-py/h2o/model/model_base.py
- h2o-py/tests/testdir_misc/pyunit_download_model_filename.py
- h2o-py/tests/testdir_misc/pyunit_download_mojo_filename.py
- h2o-py/tests/testdir_misc/pyunit_save_model_details_filename.py
- h2o-py/tests/testdir_misc/pyunit_save_model_filename.py
- h2o-py/tests/testdir_misc/pyunit_save_mojo_filename.py
- h2o-r/h2o-package/R/export.R
- h2o-r/h2o-package/R/kvstore.R
- h2o-r/tests/testdir_misc/runit_download_model_filename.R
- h2o-r/tests/testdir_misc/runit_download_mojo_filename.R
- h2o-r/tests/testdir_misc/runit_saveModelDetails_filename.R
- h2o-r/tests/testdir_misc/runit_save_model_filename.R
- h2o-r/tests/testdir_misc/runit_save_mojo_filename.R
https://h2oai.atlassian.net/browse/PUBDEV-8221
> PUBDEV-8221 save mojo with custom filename

- h2o-automl/src/main/java/ai/h2o/automl/leaderboard/Leaderboard.java
- h2o-py/h2o/automl/_base.py
- h2o-py/tests/testdir_algos/automl/multinomial/pyunit_automl_iris.py
- h2o-py/tests/testdir_algos/automl/pyunit_automl_leaderboard.py
- h2o-r/h2o-package/R/automl.R
- h2o-r/tests/testdir_algos/automl/runit_automl_leaderboard.R
- h2o-r/tests/testdir_algos/automl/runit_automl_sort_metric.R
https://h2oai.atlassian.net/browse/PUBDEV-8127
> PUBDEV-8127: AutoML: removing auc and aucpr from default leaderboard columns for multinomial

- Changes.md
Release notes draft for 3.32.1.5.
> [DOCS] 3.32.1.5 Release notes draft [nocheck]

- h2o-core/src/main/java/water/AutoBuffer.java
- h2o-core/src/main/java/water/BootstrapFreezable.java
- h2o-core/src/main/java/water/TypeMap.java
- h2o-core/src/main/java/water/TypeMapExtension.java
- h2o-core/src/test/java/water/AutoBufferTest.java
- h2o-core/src/test/resources/META-INF/services/water.TypeMapExtension
- h2o-extensions/xgboost/src/main/java/hex/schemas/XGBoostExecReqV3.java
- h2o-extensions/xgboost/src/main/java/hex/schemas/XGBoostExecRespV3.java
- h2o-extensions/xgboost/src/main/java/hex/tree/xgboost/XGBoostTypeMapExtension.java
- h2o-extensions/xgboost/src/main/java/hex/tree/xgboost/exec/RemoteXGBoostExecutor.java
- h2o-extensions/xgboost/src/main/java/hex/tree/xgboost/exec/XGBoostExecReq.java
- h2o-extensions/xgboost/src/main/java/hex/tree/xgboost/exec/XGBoostHttpClient.java
- h2o-extensions/xgboost/src/main/java/hex/tree/xgboost/matrix/SparseMatrixDimensions.java
- h2o-extensions/xgboost/src/main/java/hex/tree/xgboost/remote/RemoteXGBoostHandler.java
- h2o-extensions/xgboost/src/main/java/hex/tree/xgboost/remote/RemoteXGBoostUploadServlet.java
- h2o-extensions/xgboost/src/main/java/hex/tree/xgboost/task/XGBoostUploadMatrixTask.java
- h2o-extensions/xgboost/src/main/java/hex/tree/xgboost/util/FeatureScore.java
- h2o-extensions/xgboost/src/main/resources/META-INF/services/water.TypeMapExtension
- h2o-extensions/xgboost/src/test/java/hex/tree/xgboost/exec/RemoteXGBoostExecutorTest.java
Instead of Java object serialization
> HEXDEV-0772: Use regular H2O serialization in external XGBoost

- h2o-py/h2o/estimators/coxph.py
- h2o-py/h2o/estimators/deeplearning.py
- h2o-py/h2o/estimators/gam.py
- h2o-py/h2o/estimators/gbm.py
- h2o-py/h2o/estimators/glm.py
- h2o-py/h2o/estimators/random_forest.py
- h2o-py/h2o/estimators/rulefit.py
- h2o-py/h2o/estimators/stackedensemble.py
- h2o-py/h2o/estimators/xgboost.py
This PR fixes the problem in JIRA: https://h2oai.atlassian.net/browse/PUBDEV-8274
During merging from rel-zipf, something goes wrong and the generated python algo apis are messed up.  I am fixing it by adding the correct generated files here.
> PUBDEV-8274: Fix zero weight doc  change error

- h2o-docs/src/product/data-science/eif.rst
- h2o-docs/src/product/data-science/if.rst
- h2o-genmodel/src/main/java/hex/genmodel/easy/prediction/AnomalyDetectionPrediction.java
https://h2oai.atlassian.net/browse/PUBDEV-8241
I added a part about anomaly score in out anomaly detection algorithms
> PUBDEV-8241 if and eif documentation [nocheck]

- Changes.md
With 7 issues done 
-> without PUBDEV-8004 (declined/won't fix)
> PUBDEV-8281: 3.32.1.6 Release Notes [nocheck]

- h2o-algos/src/main/java/hex/tree/SharedTree.java
- h2o-algos/src/test/java/hex/tree/SharedTreeTest.java
- h2o-py/tests/testdir_algos/gbm/pyunit_gbm_PUBDEV_8276.py
JIRA: https://h2oai.atlassian.net/browse/PUBDEV-8276
> PUBDEV-8276 fix NPE when weight_column is not in training frame

- h2o-automl/src/main/java/ai/h2o/automl/modeling/XGBoostSteps.java
- h2o-docs/src/product/explain.rst
https://h2oai.atlassian.net/browse/PUBDEV-8123
> PUBDEV-8123: Fix examples in H2O Explain documentation

- h2o-automl/src/main/java/ai/h2o/automl/modeling/XGBoostSteps.java
- h2o-docs/src/product/explain.rst
- h2o-py/h2o/explanation/_explain.py
- h2o-r/h2o-package/R/explain.R
https://h2oai.atlassian.net/browse/PUBDEV-8205
> PUBDEV-8205: Mention that explain requires supervised models

- docker/jenkins-images/Dockerfile-mojocompat
- docker/scripts/install_R_version
- docker/scripts/install_python_version
- h2o-algos/src/test/java/hex/tree/gbm/GBMTest.java
- h2o-py/test-requirements.txt
- h2o-py/tests/testdir_algos/uplift/pyunit_uplift_causalml_make_uplift_classification_smoke.py
- h2o-py/tests/testdir_algos/uplift/pyunit_uplift_causalml_smoke.py
- scripts/jenkins/groovy/buildConfig.groovy
https://h2oai.atlassian.net/browse/PUBDEV-4940
> PUBDEV-4940 - add causalml libary into the cluster [nocheck]

- h2o-algos/src/test/java/hex/tree/drf/DRFTest.java
- h2o-genmodel/src/main/java/hex/genmodel/algos/deeplearning/DeeplearningMojoReader.java
- h2o-genmodel/src/main/java/hex/genmodel/algos/tree/SharedTreeMojoReader.java
Related to failing MLI test here https://github.com/h2oai/mli-2/pull/442#issuecomment-905106597
> PUBDEV-8298 Fix a potential NPE when _orig_projection_array is "[]"

- h2o-extensions/xgboost/src/main/java/hex/tree/xgboost/XGBoost.java
- h2o-extensions/xgboost/src/main/java/hex/tree/xgboost/XGBoostModel.java
- h2o-extensions/xgboost/src/test/java/hex/tree/xgboost/XGBoostTest.java
- h2o-extensions/xgboost/src/test/java/hex/tree/xgboost/remote/SteamExecutorStarterTest.java
- h2o-py/tests/testdir_algos/xgboost/pyunit_synonym_params_xgboost.py
- h2o-py/tests/testdir_algos/xgboost/pyunit_xgboost_colsample_bylevel.py
JIRA: https://h2oai.atlassian.net/browse/PUBDEV-8266
> PUBDEV-8266 XGBoost alias rewriting

- h2o-docs/src/product/data-science/algo-params/ignored_columns.rst
For: [PUBDEV-8304](https://h2oai.atlassian.net/browse/PUBDEV-8304) -> I removed the set predictors from the example
> PUBDEV-8304: Update ignored_columns example [nocheck]

- h2o-py/tests/testdir_algos/isoforextended/pyunit_isoforextended_grid.py
- h2o-r/h2o-package/R/grid.R
- h2o-r/h2o-package/R/models.R
- h2o-r/tests/testdir_algos/isoforextended/runit_isoforextended_grid.R
https://h2oai.atlassian.net/browse/PUBDEV-7138
I implemented grid search tests for EIF
> PUBDEV-7138 extended isolation forest grid search test 

- h2o-algos/src/main/java/hex/gam/GAM.java
- h2o-algos/src/test/java/hex/gam/GamTestPiping.java
- h2o-r/tests/testdir_algos/gam/runit_PUBDEV_8267_twice_run_npe.R
- scripts/jenkins/groovy/compareBenchmarksStage.groovy
This PR completes the task in JIRA: https://h2oai.atlassian.net/browse/PUBDEV-8308
It cherry-picks two fixes from master over to release branch:
1. fix NPE when gam is called multiple times
2. fix the benchmark time limits for GAM, MERGE and SORT
> PUBDEV-8308 fix benchmark time limits

- h2o-algos/src/main/java/hex/tree/DTree.java
- h2o-algos/src/test/java/hex/tree/gbm/GBMTest.java
- PUBDEV-8310: Add test demonstrating issue of monotone NAvsRest splits
- PUBDEV-8310: Fix predictions for splits NA vs REST with monotone constraints
>  PUBDEV-8310: Fix predictions for splits NA vs REST with monotone constraints

- h2o-algos/src/main/java/hex/generic/GenericModelParameters.java
- h2o-py/tests/testdir_algos/gbm/pyunit_PUBDEV-8309.py
- h2o-py/tests/testdir_generic_model/common.py
https://h2oai.atlassian.net/browse/PUBDEV-8309
> PUBDEV-8309: fix generic model deserialization

- h2o-algos/src/main/java/hex/tree/isoforextended/ExtendedIsolationForest.java
- h2o-r/tests/testdir_algos/isoforextended/runit_isoforextended_smoke.R
seed was not type of long and appear as NA in the R api, Python API is ok with both types..
> PUBDEV-7138 - fix model summary for R

- h2o-automl/src/main/java/ai/h2o/automl/leaderboard/Leaderboard.java
https://h2oai.atlassian.net/browse/PUBDEV-8314
> PUBDEV-8314: ensure that models without metrics are not added to leaderboard

- Changes.md
With 7 issues completed (8308 excluded)
> PUBDEV-8306: 3.32.1.7 Release Notes [nocheck]

- h2o-py/tests/testdir_algos/automl/pyunit_automl_model_selection.py
```
14:22:15.939: Actual modeling steps: [{GLM : [def_1 (1g, 10w)]}, {GBM : [def_5 (1g, 10w)]}, {StackedEnsemble : [best_of_family_1 (1g, 5w)]}, {DRF : [def_1 (2g, 10w)]}, {GBM : [def_2 (2g, 10w), def_3 (2g, 10w), def_4 (2g, 10w)]}, {StackedEnsemble : [best_of_family_2 (2g, 5w), all_2 (2g, 10w)]}, {DRF : [XRT (3g, 10w)]}, {GBM : [def_1 (3g, 10w)]}, {StackedEnsemble : [best_of_family_3 (3g, 5w), all_3 (3g, 10w)]}, {GBM : [grid_1 (4g, 60w)]}, {StackedEnsemble : [best_of_family_4 (4g, 5w), all_4 (4g, 10w)]}, {GBM : [lr_annealing (6g, 10w)]}]
14:22:15.939: AutoML build stopped: 2021.09.02 14:22:15.939
14:22:15.939: AutoML build done: built 21 models
14:22:15.939: AutoML duration: 31.585 sec
Traceback (most recent call last):
File "/home/jenkins/slave_dir_from_mr-0xc1/workspace/h2o-3-pipeline_P …
```
> [nocheck] ensure that the Py exploitation test doesn't fail if jenkins is too slow

- h2o-automl/src/main/java/ai/h2o/automl/ModelingStep.java
- h2o-automl/src/main/java/ai/h2o/automl/ModelingStepsExecutor.java
- h2o-automl/src/test/java/ai/h2o/automl/ModelingStepsExecutorTest.java
It looks like one of the test may be hanging sometimes… probably due to the infinite loop.
> [nocheck] ModelingStepsExecutorTest sometimes hanging on Jenkins?

- h2o-docs/src/product/automl.rst
AutoML user guide updates: 
- https://h2oai.atlassian.net/browse/PUBDEV-8178
- https://h2oai.atlassian.net/browse/PUBDEV-8179
> PUBDEV-8179 & 8178: Added Examine Models section to AutoML user guide

- h2o-algos/src/test/java/hex/tree/TreeHandlerTest.java
this is because this test is from time to time failing on adjusted assert and factor 3 seems not to be big enough for comparision like this
> [nocheck] adjust delta 

- h2o-genmodel/.gitignore
- h2o-genmodel/build.gradle
- h2o-genmodel/src/main/java/hex/genmodel/tools/PrintMojo.java
- h2o-genmodel/src/main/java/water/init/AbstractBuildVersion.java
https://h2oai.atlassian.net/browse/PUBDEV-8203
> PUBDEV-8203: genmodel.jar should output build version

- h2o-r/h2o-package/R/classes.R
- h2o-r/tests/testdir_algos/isofor/runit_isofor_smoke.R
I found that print of IF in R do not report any metrics. I fixed that.
> Print Anomaly Score and Normalized Anomaly Score in R instead of empty output [nocheck]

- h2o-docs/src/product/data-science.rst
- h2o-docs/src/product/data-science/glm.rst
- h2o-docs/src/product/data-science/maxrglm.rst
For: [PUBDEV-8282](https://h2oai.atlassian.net/browse/PUBDEV-8282) / tied with https://github.com/h2oai/h2o-3/pull/5627
Let me know if you would like any updates!
> PUDBDEV-8282: Added documentation for H2O Maximum R Improvements to GLM [nocheck]

- h2o-algos/src/main/java/hex/generic/Generic.java
- h2o-algos/src/main/java/hex/rulefit/RuleFit.java
- h2o-algos/src/main/java/hex/rulefit/RuleFitModel.java
- h2o-algos/src/main/java/hex/rulefit/RuleFitMojoWriter.java
- h2o-algos/src/test/java/hex/generic/GenericModelTest.java
- h2o-algos/src/test/java/hex/rulefit/RuleFitTest.java
- h2o-genmodel/src/main/java/hex/genmodel/ModelMojoFactory.java
- h2o-genmodel/src/main/java/hex/genmodel/algos/rulefit/MojoCondition.java
- h2o-genmodel/src/main/java/hex/genmodel/algos/rulefit/MojoRule.java
- h2o-genmodel/src/main/java/hex/genmodel/algos/rulefit/MojoRuleEnsemble.java
- h2o-genmodel/src/main/java/hex/genmodel/algos/rulefit/RuleFitMojoModel.java
- h2o-genmodel/src/main/java/hex/genmodel/algos/rulefit/RuleFitMojoReader.java
- h2o-py/tests/testdir_algos/rulefit/pyunit_titanic_rulefit.py
https://h2oai.atlassian.net/browse/PUBDEV-8113
> PUBDEV-8113 rulefit mojo

- h2o-docs/src/product/automl.rst
> PUBDEV-8321: Spelling correction [nocheck]

- h2o-r/h2o-package/R/classes.R
Hi @ledell can you please check the installation from this branch, if it is ok now? Thank you :)
https://h2oai.atlassian.net/browse/PUBDEV-8337
> PUBDEV-8337  fix CRAN install

- h2o-automl/src/main/java/ai/h2o/automl/AutoMLSession.java
- h2o-automl/src/main/java/ai/h2o/automl/modeling/StackedEnsembleStepsProvider.java
- h2o-py/tests/pyunit_utils/utilsPY.py
- h2o-py/tests/testdir_algos/automl/pyunit_SMOKE_automl.py
- h2o-py/tests/testdir_algos/automl/pyunit_automl_xgboost_disabled.py
- h2o-py/tests/testdir_algos/automl/regression/pyunit_automl_australia.py
- scripts/jenkins/Makefile.jenkins
- scripts/jenkins/groovy/defineTestStages.groovy
https://h2oai.atlassian.net/browse/PUBDEV-8338
Added a long-running smoke test, and a new Jenkins stage running only AutoML client smoke tests with XGB disabled.
> PUBDEV-8338: NPE if XGB disabled/not available

- h2o-persist-gcs/testMultiNode.sh
- h2o-persist-hdfs/testMultiNode.sh
- h2o-persist-http/testMultiNode.sh
- h2o-persist-s3/testMultiNode.sh
not having cloud size can lead to unexpected states
> Fix testMultiNode.sh scripts that do not specify cloudSize [nocheck]

- h2o-docs/src/product/data-munging/change-column-type.rst
- h2o-py/h2o/frame.py
- h2o-r/h2o-package/R/frame.R
For: https://h2oai.atlassian.net/browse/PUBDEV-8348
Updated the examples in R/Python frame files and the changing a column type in the user guide. Let me know if you would like anything else updated :)
> PUBDEV-8348: Update asfactor procedure documentation to show multiple column use [nocheck]

- h2o-core/src/main/java/hex/grid/Grid.java
https://h2oai.atlassian.net/browse/PUBDEV-8350
> PUBDEV-8350: Fix H2OTable colTypes in Grid's summary table

- h2o-algos/src/main/java/hex/anovaglm/ANOVAGLM.java
- h2o-algos/src/main/java/hex/anovaglm/ANOVAGLMModel.java
- h2o-algos/src/main/java/hex/schemas/ANOVAGLMModelV3.java
- h2o-algos/src/test/java/hex/anovaglm/AnovaGLMBasicTest.java
- h2o-bindings/bin/custom/R/gen_anovaglm.py
- h2o-bindings/bin/custom/python/gen_anovaglm.py
- h2o-py/h2o/estimators/anovaglm.py
- h2o-py/tests/testdir_algos/anovaglm/pyunit_PUBDEV_8088_transformFrame.py
- h2o-py/tests/testdir_algos/anovaglm/pyunit_PUBDEV_8354_anova_table.py
- h2o-r/h2o-package/R/anovaglm.R
- h2o-r/h2o-package/pkgdown/_pkgdown.yml
- h2o-r/tests/testdir_algos/anovaglm/runit_PUBDEV_8088_frame_transform.R
- h2o-r/tests/testdir_algos/anovaglm/runit_PUBDEV_8354_anova_table_frame.R
This PR completes task in JIRA: https://h2oai.atlassian.net/browse/PUBDEV-8345.
I have completed:
1. backend support to convert model summary to H2OFrame
2. java unit test
3. Python api and Python unit test
4.R api and R unit test
@seb:  is this what you are looking for?  Feel free to change names and stuff.
> PUBDEV-8345: make H2O frame out of anova glm model summary

- h2o-algos/src/main/java/hex/glm/GLM.java
- h2o-algos/src/main/java/hex/glm/GLMModel.java
- h2o-algos/src/main/java/hex/glm/GLMMojoWriter.java
- h2o-algos/src/test/java/hex/glm/GLMMojoWithOffsetTest.java
- h2o-genmodel/src/main/java/hex/genmodel/algos/glm/GlmMojoModel.java
- h2o-genmodel/src/main/java/hex/genmodel/algos/glm/GlmMojoModelBase.java
- h2o-genmodel/src/main/java/hex/genmodel/algos/glm/GlmMojoReader.java
- h2o-genmodel/src/main/java/hex/genmodel/algos/glm/GlmMultinomialMojoModel.java
- h2o-genmodel/src/main/java/hex/genmodel/algos/glm/GlmOrdinalMojoModel.java
- h2o-genmodel/src/main/java/hex/genmodel/easy/EasyPredictModelWrapper.java
- h2o-genmodel/src/main/java/hex/genmodel/tools/PredictCsv.java
- h2o-py/tests/pyunit_utils/utilsPY.py
- h2o-py/tests/testdir_javapredict/pyunit_PUBDEV_8330_GLM_mojo_gamma_offset.py
- h2o-py/tests/testdir_javapredict/pyunit_PUBDEV_8330_GLM_mojo_negativebinomial_offset.py
- h2o-py/tests/testdir_javapredict/pyunit_PUBDEV_8330_GLM_mojo_poisson_offset.py
- h2o-r/tests/testdir_javapredict/runit_PUBDEV_8330_fractionalbinomial_glm_MOJO_offset.R
- h2o-r/tests/testdir_javapredict/runit_PUBDEV_8330_quasibinomial_glm_MOJO_offset.R
- h2o-r/tests/testdir_javapredict/runit_PUBDEV_8330_tweedie_glm_MOJO_offset.R
This PR fixes the problem in JIRA: https://h2oai.atlassian.net/browse/PUBDEV-8330.
All done.
Need to fix mojoland
> PUBDEV-8330: Added GLM offset support to GLM Mojo

- h2o-automl/src/main/java/ai/h2o/automl/Models.java
- h2o-automl/src/main/java/water/automl/api/schemas3/SchemaExtensions.java
- h2o-automl/src/main/resources/META-INF/services/water.api.Schema
- h2o-py/h2o/backend/cluster.py
- h2o-r/h2o-package/R/communication.R
https://h2oai.atlassian.net/browse/PUBDEV-8394
> PUBDEV-8394: ensure that all AutoML internal jobs can be monitored without crashing backend

- h2o-automl/src/main/java/ai/h2o/automl/AutoML.java
- h2o-automl/src/main/java/ai/h2o/automl/modeling/XGBoostSteps.java
https://h2oai.atlassian.net/browse/PUBDEV-8283
Todo: ~Decide if it will be part of rel-zizler or 3.36.0.1.~
> PUBDEV-8283: Tune scale_pos_weight param for XGBoost in AutoML

- h2o-hadoop-common/tests/python/pyunit_redirect_relative.py
- h2o-jetty-8/build.gradle
- h2o-jetty-8/src/main/java/org/eclipse/jetty/server/Response.java
- h2o-jetty-8/src/main/java/water/webserver/jetty8/Jetty8Helper.java
- h2o-jetty-8/src/test/java/water/webserver/jetty8/Jetty8HelperTest.java
- h2o-jetty-9-minimal/src/main/java/water/webserver/jetty9/Jetty9Helper.java
- h2o-jetty-9-minimal/src/test/java/water/webserver/jetty9/Jetty9HelperTest.java
- h2o-jetty-9/build.gradle
- h2o-jetty-9/src/main/java/org/eclipse/jetty/server/Response.java
- h2o-jetty-9/src/main/java/water/webserver/jetty9/H2OHttpConfiguration.java
- h2o-jetty-9/src/main/java/water/webserver/jetty9/Jetty9Helper.java
- h2o-jetty-9/src/test/java/water/webserver/jetty9/Jetty9HelperTest.java
- h2o-py/h2o/backend/connection.py
- h2o-webserver-iface/build.gradle
- h2o-webserver-iface/src/main/java/water/webserver/config/ConnectionConfiguration.java
- h2o-webserver-iface/src/test/java/water/webserver/config/ConnectionConfigurationTest.java
- scripts/jenkins/groovy/hadoopCommands.groovy
Includes original source code of Response class from Jetty 9.4.11 and Jetty 8.2.0
> PUBDEV-8386: Enforce relative redirects in Jetty

- h2o-algos/src/main/java/hex/gam/GAM.java
- h2o-algos/src/main/java/hex/gam/GAMModel.java
- h2o-algos/src/main/java/hex/gam/MatrixFrameUtils/GAMModelUtils.java
- h2o-algos/src/main/java/hex/gam/MatrixFrameUtils/GamUtils.java
- h2o-algos/src/test/java/hex/gam/GamCVTest.java
- h2o-py/tests/testdir_algos/gam/pyunit_PUBDEV_7366_gam_cv_all_params_binomial.py
- h2o-py/tests/testdir_algos/gam/pyunit_PUBDEV_8136_check_gamX_saved_serialization.py
- h2o-py/tests/testdir_algos/gam/pyunit_PUBDEV_8163_gam_cv_all_params_binomial_serialization.py
- h2o-py/tests/testdir_algos/gam/pyunit_PUBDEV_8163_gam_cv_fold_column.py
This PR fixed the problem in JIRA: https://h2oai.atlassian.net/browse/PUBDEV-8163
I fixed the bug by having GLM runs the cross-validation and not in GAM.  GAM just need to pick up the information from the GLM runs.
> PUBDEV-8163: fix GAM CV bug

- h2o-docs/src/product/data-science/anova_glm.rst
- h2o-py/h2o/sklearn/__init__.py
- h2o-py/tests/pyunit_utils/utilsPY.py
- h2o-py/tests/testdir_sklearn/pyunit_sklearn_classification_all_estimators.py
- h2o-py/tests/testdir_sklearn/pyunit_sklearn_generic_all_estimators.py
- h2o-py/tests/testdir_sklearn/pyunit_sklearn_regression_all_estimators.py
https://h2oai.atlassian.net/browse/PUBDEV-8344
> PUBDEV-8344: disable sklearn integration for ANOVA GLM and MaxR2 GLM

- h2o-docs/src/product/getting-data-into-h2o.rst
https://h2oai.atlassian.net/browse/PUBDEV-8208
> PUBDEV-8208: update documentation

- h2o-core/src/main/java/hex/AUC2.java
- h2o-core/src/main/java/water/api/schemas3/ModelMetricsBinomialV3.java
- h2o-py/h2o/model/metrics_base.py
- h2o-py/tests/testdir_algos/rf/pyunit_no_oob_prostateRF.py
This is not meant to resolve the jira, just to fix the show method on DRF trained without OOB samples
> PUBDEV-8403: Fix printing DRF when there are no OOB samples

- h2o-algos/src/main/java/hex/gam/GAM.java
- h2o-algos/src/main/java/hex/gam/GAMModel.java
- h2o-algos/src/test/java/hex/gam/GamMetricsTest.java
- h2o-py/tests/testdir_algos/gam/pyunit_PUBDEV_7460_gam_hit_ratios_others_large.py
- h2o-r/tests/testdir_algos/gam/runit_PUBDEV_8407_gam_weight_offset.R
This PR solves the problem in JIRA: https://h2oai.atlassian.net/browse/PUBDEV-8410
Copied over the model metrics from glm model to GAM model.
> PUBDEV-8410 add GAM training/valid metrics

- h2o-docs/src/product/data-science/glm.rst
Added a correct formula to fit page 18 of https://www.h2o.ai/wp-content/uploads/2018/01/GLM-BOOKLET.pdf
> Fixing a formula for multinomial regression on GLM docs

- Changes.md
For: [PUBDEV-8406](https://h2oai.atlassian.net/browse/PUBDEV-8406)
With 20 issues done (1 closed, unreproducible)
> PUBDEV-8406: 3.34.0.4 Release Notes

- h2o-docs/src/product/data-science/gbm-faq/reproducibility.rst
For: [PUBDEV-8242](https://h2oai.atlassian.net/browse/PUBDEV-8424)
Please let me know if anything else needs to be updated or changed :)
> PUBDEV-8424: Add R/Python examples on how to get to reproducibility information

- h2o-algos/src/main/java/hex/rulefit/Condition.java
- h2o-algos/src/main/java/hex/rulefit/RuleFit.java
- h2o-algos/src/main/java/hex/rulefit/RuleFitModel.java
- h2o-algos/src/main/java/hex/rulefit/RuleFitUtils.java
- h2o-algos/src/test/java/hex/rulefit/RuleFitUtilsTest.java
https://h2oai.atlassian.net/browse/PUBDEV-8383
Rulefit returns rules with splits that are unnecessary.  For example, x < 3 & x < 5.
when https://github.com/h2oai/h2o-3/pull/5765 will be merged i will rebase this PR on rel-zizler
> PUBDEV-8383: consolidate rules

- h2o-algos/src/main/java/hex/rulefit/Rule.java
- h2o-algos/src/main/java/hex/rulefit/RuleFit.java
- h2o-algos/src/main/java/hex/rulefit/RuleFitModel.java
- h2o-algos/src/main/java/hex/rulefit/RuleFitUtils.java
- h2o-algos/src/main/java/hex/schemas/RuleFitV3.java
- h2o-algos/src/test/java/hex/rulefit/RuleFitTest.java
- h2o-algos/src/test/java/hex/rulefit/RuleFitUtilsTest.java
- h2o-docs/src/product/data-science/rulefit.rst
- h2o-py/h2o/estimators/rulefit.py
- h2o-py/tests/testdir_algos/rulefit/pyunit_cancer_rulefit.py
- h2o-py/tests/testdir_algos/rulefit/pyunit_credit_rulefit.py
- h2o-r/h2o-package/R/rulefit.R
https://h2oai.atlassian.net/browse/PUBDEV-8176
this will go there, where https://github.com/h2oai/h2o-3/pull/5849 will get merged.
> PUBDEV-8176: deduplicate rules

- h2o-py/tests/testdir_algos/pca/pyunit_PUBDEV_8271_wideDataset_Rotterdam_glrm_large.py
- h2o-py/tests/testdir_algos/pca/pyunit_PUBDEV_8271_wideDataset_Rotterdam_pcapower_large.py
- h2o-py/tests/testdir_algos/pca/pyunit_PUBDEV_8271_wideDataset_Rotterdam_pcarandomized_large.py
This PR fixes the issue in JIRA: https://h2oai.atlassian.net/browse/PUBDEV-8430
I make the tests more predictable by fixing their transfroms apart from fixing the seed values.
> PUBDEV-8430 rotterdam test failure

- h2o-automl/src/main/java/ai/h2o/automl/AutoML.java
- h2o-automl/src/main/java/ai/h2o/automl/ModelingStep.java
- h2o-automl/src/main/java/ai/h2o/automl/events/EventLog.java
- h2o-automl/src/main/java/ai/h2o/automl/events/EventLogEntry.java
- h2o-automl/src/main/java/water/automl/api/schemas3/AutoMLV99.java
- h2o-automl/src/main/java/water/automl/api/schemas3/EventLogEntryV99.java
- h2o-automl/src/main/java/water/automl/api/schemas3/EventLogV99.java
- h2o-automl/src/test/java/ai/h2o/automl/ModelingStepRegistryTest.java
- h2o-automl/src/test/java/ai/h2o/automl/events/EventLogTest.java
- h2o-py/h2o/automl/_base.py
- h2o-py/h2o/automl/_estimator.py
- h2o-py/h2o/frame.py
- h2o-py/h2o/h2o.py
- h2o-py/h2o/schemas/metadata.py
- h2o-py/h2o/two_dim_table.py
- h2o-py/tests/testdir_algos/automl/leaderboard/pyunit_automl_leaderboard.py
- h2o-py/tests/testdir_algos/automl/pyunit_automl_input.py
- h2o-r/h2o-package/R/automl.R
- h2o-r/h2o-package/R/communication.R
- h2o-r/h2o-package/pkgdown/_pkgdown.yml
- h2o-r/tests/testdir_algos/automl/runit_automl_leaderboard.R
https://h2oai.atlassian.net/browse/PUBDEV-8212
As job polling in AutoML also means polling the event_log (that's the part creating all the noise), I also standardized it to use the shared log levels now available with the "new" logger.
> PUBDEV-8212: cleanup + improve efficiency of job polling in AutoML

- scripts/jenkins/groovy/compareBenchmarksStage.groovy
> [nocheck] update rulefit benchmark expected time intervals

- h2o-algos/src/main/java/hex/glm/GLM.java
- h2o-algos/src/main/java/hex/glm/GLMModel.java
- h2o-algos/src/main/java/hex/schemas/GLMModelV3.java
- h2o-py/tests/testdir_algos/glm/pyunit_PUBDEV_6424_multinomial_makeGLMModel.py
- h2o-py/tests/testdir_algos/glm/pyunit_PUBDEV_8421_check_ymu_rank.py
This PR complete the ask in JIRA: https://h2oai.atlassian.net/browse/PUBDEV-8421
Added the fields to GLMModelOutputV3.java and make sure they are copied from ModelOutput.
Added python test to check the fields are properly filled.
> PUBDEV-8421 add model output ymu and rank to GLMModelOutputV3

- h2o-py/tests/testdir_algos/uplift/pyunit_uplift_compare_causalml.py
- h2o-py/tests/testdir_algos/uplift/pyunit_uplift_rf_large.py
- h2o-py/tests/testdir_algos/uplift/pyunit_uplift_rf_saveload.py
- h2o-py/tests/testdir_algos/uplift/pyunit_uplift_rf_smoke.py
JIRA: https://h2oai.atlassian.net/browse/PUBDEV-4940
> PUBDEV-4940 Fix failed UpliftDRF tests on Python 2.7

- h2o-py/tests/testdir_algos/uplift/pyunit_uplift_compare_causalml.py
- h2o-py/tests/testdir_algos/uplift/pyunit_uplift_rf_large.py
JIRA: https://h2oai.atlassian.net/browse/PUBDEV-4940
> PUBDEV-4940 Fix failed Uplift python 2.7 tests again

- h2o-algos/src/test/java/hex/gam/GamGeneralTest.java
- h2o-py/tests/testdir_algos/gam/pyunit_PUBDEV_8426_gam_multiple_model_builds.py
This PR verifies that the problem in JIRA: https://h2oai.atlassian.net/browse/PUBDEV-8426 has been fixed.  Please update to latest H2O.
> PUBDEV-8426: GAM multiple model builds

- h2o-algos/src/main/java/hex/gram/Gram.java
- h2o-algos/src/main/java/hex/tree/FriedmanPopescusH.java
- h2o-algos/src/test/java/hex/gam/GamTestPiping.java
- h2o-algos/src/test/java/hex/tree/FriedmanPopescusHTest.java
- h2o-core/src/main/java/water/util/ArrayUtils.java
Fix incorrect merge in https://github.com/h2oai/h2o-3/pull/5930
> Fix incorrect use of indexOf in FriedmanPopescusH

- h2o-docs/src/product/data-science/maxrglm.rst
For: [PUBDEV-8443](https://h2oai.atlassian.net/browse/PUBDEV-8443)
> PUBDEV-8443: Updated `y` description for maxrglm

- h2o-docs/src/product/data-science/maxrglm.rst
For: [PUBDEV-8432](https://h2oai.atlassian.net/browse/PUBDEV-8432)
> PUBDEV-8432: Update MaxRGLM examples 

- .github/workflows/snyk-scan.yml
This is done as a part of [standardizing/Restructuring the Snyk security vulnerability scanning process](https://github.com/h2oai/h2o-infra/issues/49) across all the products and their main components. GH actions are used for this
**Main Requirements:**
- Run local `Snyk tests` for PRs
- Run `Snyk monitor` for all the main branches/release branches/tags and users can explore the Snyk reports in Snyk UI using provided links in Workflow logs
- Group the components related to one main product (**H2O-3**) in [Snyk UI ](https://app.snyk.io/org/h2oai/projects) 
Please refer to the main issue **https://github.com/h2oai/h2o-infra/issues/49** for more details
> PUBDEV-XXXX: Snyk Security Vulnerability Scanning Integration

- h2o-extensions/steam/build.gradle
- h2o-extensions/steam/testSingleNode.sh
This is needed for proper property propagation (eg. to enable specific java version) and also log and test result collection
> Make sure steam-extension is tested just like everything else [nocheck]

- h2o-mapreduce-generic/src/main/java/water/hadoop/h2odriver.java
- h2o-persist-hdfs/src/main/java/water/persist/security/HdfsDelegationTokenRefresher.java
"-refreshS3ATokens" independent from "-refreshHdfsTokens"
> PUBDEV-8208: improve configurability

- build.gradle
- h2o-assemblies/main/build.gradle
- h2o-assemblies/minimal/build.gradle
- h2o-security/src/main/java/water/network/SecurityUtils.java
- h2o-test-support/build.gradle
- scripts/jenkins/Makefile.jenkins
- scripts/jenkins/groovy/defineTestStages.groovy
- Java 16/17 support: open additional modules (java.util, sun.security.ssl)
- RIP: for testing
> PUBDEV-8341: Java 16/17 support: open additional modules (java.util, sun.security.ssl)

- Changes.md
> PUBDEV-8471: 3.34.0.5 Release Notes

- h2o-core/src/main/java/water/JavaVersionSupport.java
- h2o-core/src/test/java/water/JavaVersionSupportTest.java
- h2o-docs/src/product/welcome.rst
- h2o-r/h2o-DESCRIPTION.template
- scripts/jenkins/Makefile.jenkins
https://h2oai.atlassian.net/browse/PUBDEV-8341
> PUBDEV-8341 - officially support java 17

- h2o-logging/impl-log4j2/build.gradle
> Upgrade to log4j 2.17.0

- h2o-algos/src/main/java/hex/rulefit/Rule.java
- h2o-algos/src/main/java/hex/rulefit/RuleEnsemble.java
- h2o-algos/src/main/java/hex/rulefit/RuleFit.java
- h2o-algos/src/main/java/hex/rulefit/RuleFitModel.java
- h2o-algos/src/main/java/hex/rulefit/RuleFitMojoWriter.java
- h2o-algos/src/main/java/hex/rulefit/RuleFitUtils.java
- h2o-core/src/main/java/water/util/VecUtils.java
- h2o-core/src/test/java/water/util/VecUtilsTest.java
- h2o-genmodel/src/main/java/hex/genmodel/algos/rulefit/MojoRule.java
- h2o-genmodel/src/main/java/hex/genmodel/algos/rulefit/RuleFitMojoReader.java
- h2o-py/tests/testdir_algos/rulefit/pyunit_titanic_rulefit.py
…e are some discrepancies found
https://h2oai.atlassian.net/browse/PUBDEV-8414
> PUBDEV-8414: Add support/rule coverage to RuleFit

- h2o-logging/impl-log4j2/build.gradle
- Upgrade to log4j 2.17.0
- PUBDEV-8415 Extended Isolation Forest - create logging for isolation trees (#5945)
- Revert "PUBDEV-8415 Extended Isolation Forest - create logging for isolation trees (#5945)" (#5976)
> Resolve rel-zizler-master merge 12/21

- Changes.md
> PUBDEV-8478: 3.34.0.7 Release Notes [nocheck]

- h2o-algos/src/main/java/hex/kmeans/KMeans.java
- h2o-core/src/main/java/hex/ClusteringModelBuilder.java
- h2o-core/src/main/java/hex/ModelBuilder.java
- h2o-core/src/main/java/hex/ModelMetrics.java
- h2o-core/src/main/java/hex/ModelMetricsClustering.java
- h2o-docs/src/product/data-science/k-means.rst
- h2o-py/h2o/model/clustering.py
- h2o-py/h2o/model/metrics_base.py
- h2o-py/tests/testdir_algos/kmeans/pyunit_kmeans_cv.py
- h2o-py/tests/testdir_misc/pyunit_metric_accessors.py
- h2o-r/h2o-package/R/classes.R
- h2o-r/h2o-package/R/models.R
- h2o-r/tests/testdir_algos/kmeans/runit_kmeans_cv.R
JIRA: https://h2oai.atlassian.net/browse/PUBDEV-7752
> PUBDEV-7752 Disable centroid stats for CV

- h2o-py/tests/testdir_jira/pyunit_pubdev_5336.py
> Tiny clean-up: fix warning in test found under Python 3.8

- h2o-algos/src/main/java/hex/ensemble/StackedEnsemble.java
- h2o-algos/src/main/java/hex/ensemble/StackedEnsembleModel.java
- h2o-automl/src/main/java/ai/h2o/automl/AutoML.java
- h2o-automl/src/main/java/ai/h2o/automl/AutoMLBuildSpec.java
- h2o-automl/src/main/java/ai/h2o/automl/AutoMLSession.java
- h2o-automl/src/main/java/ai/h2o/automl/ModelingSteps.java
- h2o-automl/src/main/java/ai/h2o/automl/modeling/StackedEnsembleStepsProvider.java
- h2o-automl/src/main/java/water/automl/api/schemas3/AutoMLBuildSpecV99.java
- h2o-automl/src/test/java/ai/h2o/automl/AutoMLTest.java
- h2o-docs/src/product/automl.rst
- h2o-py/h2o/automl/_estimator.py
- h2o-py/tests/testdir_algos/automl/pyunit_automl_memory_cleanup.py
- h2o-py/tests/testdir_algos/automl/pyunit_automl_params_attributes.py
- h2o-r/h2o-package/R/automl.R
- h2o-r/tests/testdir_algos/stackedensemble/runit_stackedensemble_max_runtime_secs.R
Criterium for choosing blending vs 5-fold CV is depicted in the figure below. The figure shows the winning "strategy" (blending vs 5-CV) for individual scenarios.
> PUBDEV-7542: Dynamic stacking strategy for H2OAutoML

- Changes.md
> PUBDEV-8480: 3.36.0.1 Release Notes

- h2o-hadoop-3/h2o-hdp3.1-assembly/build.gradle
Versioning of artifacts changed with introduction of Data Platform 3.1.0.0
> Fix HDP 3.1 public build [nocheck]

- h2o-py/h2o/estimators/estimator_base.py
- h2o-py/tests/testdir_algos/common/pyunit_train_params_validation.py
https://h2oai.atlassian.net/browse/PUBDEV-8483
> PUBDEV-8483: fixed Py warnings before model training

- h2o-algos/src/main/java/hex/generic/Generic.java
- h2o-bindings/bin/custom/python/gen_generic.py
- h2o-core/src/main/java/water/H2O.java
- h2o-core/src/main/java/water/rapids/Env.java
- h2o-core/src/main/java/water/rapids/ast/prims/testing/AstSetReadForbidden.java
- h2o-core/src/main/java/water/rapids/vals/ValNums.java
- h2o-core/src/main/java/water/testing/SandboxSecurityManager.java
- h2o-py/h2o/estimators/generic.py
- h2o-py/h2o/h2o.py
- h2o-py/tests/pyunit_utils/utilsPY.py
- h2o-py/tests/testdir_generic_model/pyunit_mojo_import.py
This PR only fixes the Python side
It also doesn't address issue https://h2oai.atlassian.net/browse/PUBDEV-8489 (that will be its own PR)
> PUBDEV-8481: Fix upload MOJO in Python

- h2o-algos/testMultiNode.sh
This should resolve timeouts in machines with high #cores
> Tests: Limit CPUs visible to JUnit-algos tests [nocheck]

- h2o-core/src/main/java/hex/Model.java
https://h2oai.atlassian.net/browse/PUBDEV-8488
> PUBDEV-8488: Add check before producing a bad Mojo

- h2o-algos/src/main/java/hex/rulefit/RuleEnsemble.java
- h2o-py/tests/testdir_algos/rulefit/pyunit_titanic_rulefit.py
> RuleFit: Fix failing support test [nocheck]

- h2o-r/h2o-package/R/frame.R
- h2o-r/tests/testdir_misc/runit_groupby.R
https://h2oai.atlassian.net/browse/PUBDEV-8507
> PUBDEV-8507: Fix warning in h2o.group_by

- build.gradle
- h2o-jetty-8/src/main/java/water/webserver/jetty8/Jetty8DelegatingAuthenticator.java
- h2o-jetty-8/src/main/java/water/webserver/jetty8/Jetty8Helper.java
- h2o-jetty-8/src/main/java/water/webserver/jetty8/security/FormAuthenticator.java
- h2o-jetty-8/src/test/java/water/webserver/jetty8/Jetty8HelperTest.java
- h2o-jetty-8/src/test/java/water/webserver/jetty8/security/FormAuthenticatorTest.java
- h2o-webserver-iface/src/main/java/water/webserver/config/ConnectionConfiguration.java
- h2o-webserver-iface/src/test/java/water/webserver/config/ConnectionConfigurationTest.java
- Copy Jetty's FormAuthenticator into our code base, original code unmodified
- PUBDEV-8386: Customize FormAuthenticator to use relative redirects
> PUBDEV-8386: Customize FormAuthenticator to use relative redirects

- Changes.md
For: [PUBDEV-8516](https://h2oai.atlassian.net/browse/PUBDEV-8516)
With 2 issues in progress
> PUBDEV-8516: 3.34.0.8 Release notes

- h2o-py/tests/testdir_algos/gam/pyunit_gam_train_metrics.py
We compare training metrics calculated in training and user-calculated
metrics.
> PUBDEV-8455: Add test to show GAM metrics are correct

- h2o-admissibleml/src/main/java/hex/Infogram/InfogramUtils.java
- h2o-admissibleml/src/test/java/hex/Infogram/InfogramPipingTest.java
https://h2oai.atlassian.net/browse/PUBDEV-8519
> PUBDEV-8519 - Infogram support XGboost

- h2o-bindings/bin/custom/python/gen_infogram.py
- h2o-py/h2o/estimators/infogram.py
- h2o-py/h2o/frame.py
- h2o-py/h2o/model/model_base.py
- h2o-py/h2o/utils/ext_dependencies.py
https://h2oai.atlassian.net/browse/PUBDEV-8521
> PUBDEV-8521: Moving _get_numpy function and removing np dependency

- h2o-algos/src/main/java/hex/glm/GLM.java
- h2o-algos/src/main/java/hex/glm/GLMModel.java
- h2o-algos/src/main/java/hex/modelselection/ModelSelection.java
- h2o-algos/src/main/java/hex/modelselection/ModelSelectionModel.java
- h2o-algos/src/main/java/hex/modelselection/ModelSelectionUtils.java
- h2o-algos/src/main/java/hex/schemas/ModelSelectionModelV3.java
- h2o-algos/src/main/java/hex/schemas/ModelSelectionV3.java
- h2o-algos/src/test/java/hex/modelselection/BackwardSelectionTests.java
- h2o-bindings/bin/custom/python/gen_modelselection.py
- h2o-py/h2o/estimators/model_selection.py
- h2o-py/tests/testdir_algos/modelselection/pyunit_PUBDEV_8428_modelselection_backward_binomial_large.py
- h2o-py/tests/testdir_algos/modelselection/pyunit_PUBDEV_8428_modelselection_backward_gaussian_large.py
- h2o-py/tests/testdir_algos/modelselection/pyunit_PUBDEV_8428_modelselection_backward_result_frame_model_id_serialization.py
- h2o-r/h2o-package/R/models.R
- h2o-r/h2o-package/R/modelselection.R
- h2o-r/tests/testdir_algos/modelselection/runit_PUBDEV_8427_modelselection_coeffs_demo.R
- h2o-r/tests/testdir_algos/modelselection/runit_PUBDEV_8428_modelselection_backward_binomial.R
This PR completes the task in JIRA: https://h2oai.atlassian.net/browse/PUBDEV-8428
I completed the following:
1. Java backend to support backward selection
2. Junit tests;
3. Python/R unit tests
4. Add documentation to help team do review for me.
> PUBDEV-8428 backward selection

- h2o-docs/src/product/data-science/algo-params/interaction_constraints.rst
Docs example show interaction_constraints for GBM, but it is only supported for XGBoost
> PUBDEV-7980 : Fix typo interaction_constraints

- Changes.md
For: [PUBDEV-8545](https://h2oai.atlassian.net/browse/PUBDEV-8545)
With 14 issues done (1 duplicate)
> PUBDEV-8545: 3.36.0.2 Release Notes

- h2o-py/h2o/automl/_base.py
- h2o-py/h2o/automl/_estimator.py
- h2o-py/tests/pyunit_utils/utilsPY.py
- h2o-py/tests/testdir_algos/automl/pyunit_automl_event_log.py
- h2o-r/h2o-package/R/automl.R
- h2o-r/tests/testdir_algos/automl/runit_automl_event_log.R
https://h2oai.atlassian.net/browse/PUBDEV-8552
> PUBDEV-8552: AutoML R client doesn't respect verbosity param

- h2o-py/tests/pyunit_utils/utilsPY.py
- h2o-py/tests/testdir_algos/automl/pyunit_automl_event_log.py
https://h2oai.atlassian.net/browse/PUBDEV-8552
follow up to https://github.com/h2oai/h2o-3/pull/6045
Found a better way to capture output:
- not only prints, but all writes are now captured
- easier and more strict testing in Py
- test now works in Py2
> PUBDEV-8552: follow-up, improving testing in Py

- h2o-algos/src/test/java/hex/deeplearning/DeepLearningTest.java
- h2o-algos/src/test/java/hex/tree/gbm/GBMTest.java
- h2o-core/src/main/java/hex/DistributionFactory.java
- h2o-core/src/test/java/hex/DistributionTest.java
- h2o-docs/src/product/data-science/algo-params/distribution.rst
JIRA: https://h2oai.atlassian.net/browse/PUBDEV-8524
> PUBDEV-8524 Fix Huber Distribution bug in deviance

- h2o-docs/src/product/data-science/algo-params/tweedie_power.rst
- h2o-docs/src/product/data-science/deep-learning.rst
- h2o-docs/src/product/data-science/gbm.rst
- h2o-docs/src/product/data-science/xgboost.rst
For: [PUBDEV-8535](https://h2oai.atlassian.net/browse/PUBDEV-8535)
Added the values described in the attachment. Please let me know if anything else needs to be added.
> PUBDEV-8535: Clarify feasible intervals for tweedie power in documentation

- h2o-py/h2o/explanation/_explain.py
- h2o-py/tests/testdir_misc/pyunit_ice_plot.py
- h2o-r/h2o-package/R/explain.R
- h2o-r/tests/testdir_misc/runit_ice_plot.R
https://h2oai.atlassian.net/browse/PUBDEV-8495
TODO: decide whether there will be display_mode ["both", "ice", "pdp"] or show_pdp=true/false based on customer feedback 
-> show_pdp=true/false will be used
examples:
display_mode = 'both':
display_mode  = 'ice':
display_mode  = 'pdp':
> PUBDEV-8495: add option to turn on or off pdp vs ice lines

- h2o-algos/src/main/java/hex/tree/isofor/ModelMetricsAnomaly.java
- h2o-genmodel/src/main/java/hex/genmodel/easy/prediction/AnomalyDetectionPrediction.java
Specify what kind of number should be in the fields
> PUBDEV-8547 - document Anomaly Detection related metrics

- h2o-docs/src/product/welcome.rst
For: [PUBDEV-8466](https://h2oai.atlassian.net/browse/PUBDEV-8466)
I added a Java Requirement note to the Hadoop section of the "Welcome to H2O-3" section of the User Guide. Please let me know if anything else needs to be added/updated.
> PUBDEV-8466: Added java requirement section for Hadoop

- Changes.md
With 11 issues done (1 task not included)
> PUBDEV-8584: 3.36.0.3 Release Notes

- h2o-py/h2o/explanation/_explain.py
- h2o-py/h2o/frame.py
- h2o-py/h2o/model/binomial.py
- h2o-py/h2o/model/dim_reduction.py
- h2o-py/h2o/model/extensions/std_coef.py
- h2o-py/h2o/model/extensions/varimp.py
- h2o-py/h2o/model/model_base.py
- h2o-py/h2o/model/ordinal.py
- h2o-py/h2o/model/regression.py
- h2o-r/h2o-package/R/explain.R
https://h2oai.atlassian.net/browse/PUBDEV-8502
support for effects of numerical variables, behaviour for categorical variables to be clarified
ICEbox (= R package that was done by the authors of ICE paper https://arxiv.org/pdf/1309.6392.pdf) doesn't support ICE for factor attributes at all: https://github.com/kapelner/ICEbox/blob/master/ICEbox/R/ice.R
> PUBDEV-8502: normalize y-axis values option

- h2o-py/h2o/explanation/_explain.py
- h2o-py/tests/testdir_misc/pyunit_ice_plot.py
- h2o-r/h2o-package/R/explain.R
- h2o-r/tests/testdir_misc/runit_ice_plot.R
https://h2oai.atlassian.net/browse/PUBDEV-8497
Option "grouping_variable" to specify a grouping variable to group the data and provide separate sets of plots by grouping variable values.
for example:
py:
R:
> PUBDEV-8497: grouping variable 

- h2o-py/tests/testdir_algos/uplift/pyunit_uplift_rf_smoke.py
Use numpy mean function which is available also for python 2.7.
> Fix uplift smoke test for Python 2.7 [nocheck]

- h2o-algos/src/main/java/hex/ensemble/StackedEnsembleModel.java
- h2o-automl/src/test/java/ai/h2o/automl/preprocessing/TargetEncodingTest.java
- h2o-core/src/main/java/hex/Model.java
- h2o-py/tests/testdir_algos/automl/pyunit_automl_preprocessing.py
https://h2oai.atlassian.net/browse/PUBDEV-8504
this is temporary measure until PUBDEV-7799 is completed
> PUBDEV-8504: disable MOJO creation for models with TE

- h2o-algos/src/main/java/hex/tree/gbm/GBM.java
- h2o-py/tests/testdir_algos/gbm/pyunit_gbm_monotone_quantile_cv.py
Fix leave correction if CV is enabled and quantiles are NaN.
JIRA: https://h2oai.atlassian.net/browse/PUBDEV-8581
> PUBDEV-8581 GBM quantile monotone constraints with CV bug 

- .github/workflows/snyk-scan.yml
Fix Snyk scan due to a deprecated version issue in a python file scanning. Hence the next proceeding steps (eg: Gradle scan, Node scan) were also not executed properly due to the failure of the previous step.
Note: Now newly added Gradle file scans are also available in Snyk
Related Thread: https://h2oai.slack.com/archives/C1Q2M34JG/p1648484786085179
> Fix Snyk scan due to a deprecated version issue in a python file scanning

- h2o-algos/src/main/java/hex/schemas/GBMV3.java
- h2o-docs/src/product/data-science/algo-params/interaction_constraints.rst
- h2o-py/h2o/estimators/gbm.py
- h2o-py/tests/testdir_algos/gbm/pyunit_gbm_interaction_constraints.py
- h2o-r/h2o-package/R/gbm.R
- h2o-r/tests/testdir_algos/gbm/runit_GBM_interaction_constraints.R
JIRA: https://h2oai.atlassian.net/browse/PUBDEV-7980
> PUBDEV-7980 GBM Interaction Constraints - R/Python API, doc

- h2o-extensions/xgboost/src/main/java/hex/tree/xgboost/XGBoost.java
- h2o-extensions/xgboost/src/test/java/hex/tree/xgboost/XGBoostTest.java
https://h2oai.atlassian.net/browse/PUBDEV-8626
@michalkurka can it go to fix release?
> PUBDEV-8626 XGboost validation fix

- h2o-docs/src/product/faq/r.rst
- h2o-r/h2o-package/R/communication.R
- h2o-r/tests/runitUtils/utilsR.R
https://h2oai.atlassian.net/browse/PUBDEV-8633
> PUBDEV-8633: Check curl version and add documentation

- h2o-r/h2o-package/R/config.R
- h2o-r/h2o-package/R/frame.R
- h2o-r/h2o-package/R/grid.R
- h2o-r/h2o-package/R/import.R
- h2o-r/h2o-package/R/kvstore.R
- h2o-r/h2o-package/R/models.R
- h2o-r/tests/runitUtils/utilsR.R
- h2o-r/tests/testdir_munging/binop/runit_binop2_divCol.R
https://h2oai.atlassian.net/browse/PUBDEV-8634
> PUBDEV-8634: Fix R check length == 1 for logic operations

- h2o-extensions/xgboost/src/main/java/hex/tree/xgboost/XGBoost.java
- h2o-extensions/xgboost/src/test/java/hex/tree/xgboost/XGBoostTest.java
- h2o-r/h2o-package/R/config.R
- h2o-r/h2o-package/R/frame.R
- h2o-r/h2o-package/R/grid.R
- h2o-r/h2o-package/R/import.R
- h2o-r/h2o-package/R/kvstore.R
- h2o-r/h2o-package/R/models.R
- h2o-r/tests/runitUtils/utilsR.R
- h2o-r/tests/testdir_munging/binop/runit_binop2_divCol.R
- PUBDEV-8626 - XGBoost do not support Eigen encoding
- PUBDEV-8634: Fix R check length == 1 for logic operations (#6120)
> Resolve merge conflict [nocheck]

- Changes.md
For: [PUBDEV-8642](https://h2oai.atlassian.net/browse/PUBDEV-8642)
With 4 issues done
> PUBDEV-8642: 3.36.0.4 Release Notes

- h2o-automl/src/main/java/ai/h2o/automl/ModelingPlans.java
https://h2oai.atlassian.net/browse/PUBDEV-8614
> PUBDEV-8614: disable SE with XGB metalearner

- h2o-core/src/main/java/water/rapids/Env.java
- h2o-core/src/main/java/water/rapids/ast/prims/mungers/AstRelevelByFreq.java
- h2o-core/src/main/java/water/rapids/vals/ValNum.java
- h2o-core/src/main/java/water/rapids/vals/ValNums.java
- h2o-core/src/main/java/water/util/VecUtils.java
- h2o-core/src/test/java/water/util/VecUtilsTest.java
- h2o-py/h2o/frame.py
- h2o-py/tests/testdir_misc/pyunit_relevel_by_freq.py
- h2o-py/tests/testdir_misc/pyunit_relevel_by_freq_glm.py
- h2o-py/tests/testdir_misc/pyunit_relevel_by_freq_weights.py
- h2o-r/h2o-package/R/frame.R
- h2o-r/tests/testdir_misc/runit_relevel_by_freq.R
The base/reference level will be come the most frequent
> PUBDEV-8573: Reorder frame levels based on their frequencies

- h2o-docs/src/product/save-and-load-model.rst
https://h2oai.atlassian.net/browse/PUBDEV-8604
> PUBDEV-8604 - fix switched columns and add eif to mojos

- h2o-r/h2o-package/R/communication.R
- h2o-r/h2o-package/R/explain.R
- h2o-r/h2o-package/R/kvstore.R
- h2o-r/h2o-package/R/models.R
https://h2oai.atlassian.net/browse/PUBDEV-8649
> PUBDEV-8649: Replace class() with inherits() in R

- h2o-py/h2o/explanation/_explain.py
- h2o-r/h2o-package/R/explain.R
https://h2oai.atlassian.net/browse/PUBDEV-8653
> PUBDEV-8653: Residual calculation is flipped in the Residual Analysis Plot

- h2o-docs/src/product/data-munging/change-column-type.rst
For: [PUBDEV-8595](https://h2oai.atlassian.net/browse/PUBDEV-8595)
I added the information to the data munging [changing column type ](https://docs.h2o.ai/h2o/latest-stable/h2o-docs/data-munging/change-column-type.html) section. Please let me know if anything should be changed!
> PUBDEV-8595: Added information on date columns

- h2o-docs/src/product/faq/hadoop.rst
- h2o-docs/src/product/welcome.rst
For: [PUBDEV-8591](https://h2oai.atlassian.net/browse/PUBDEV-8591)
I added the note on configuring HDFS multiple times to the Hadoop FAQ and added the information on general HDFS configuration to the welcome page. Please let me know if anything needs to be updated!
> PUBDEV-8591: Added information on HDFS configuration

- h2o-docs/src/product/admissible.rst
https://h2oai.atlassian.net/browse/PUBDEV-8590
> PUBDEV-8590: Fix typos in admissible.rst

- h2o-py/h2o/explanation/_explain.py
- h2o-py/tests/testdir_misc/pyunit_explain.py
- h2o-r/h2o-package/R/classes.R
- h2o-r/h2o-package/R/explain.R
- h2o-r/tests/testdir_misc/runit_explain.R
https://h2oai.atlassian.net/browse/PUBDEV-8014
Add ability to limit the number of features shown in the varimp_heatmap.
> PUBDEV-8014: Add num_of_features argument to explain's varimp

- h2o-r/h2o-package/R/explain.R
this fixes weird peaks in R's ice plots + bug when colname has spaces in it
> ICE fixes [nocheck]

- h2o-r/h2o-package.template
- h2o-r/h2o-package/R/frame.R
https://h2oai.atlassian.net/browse/PUBDEV-8644
This is just the code change; I think I'll make a new ticket for improving the R test harness.
> PUBDEV-8644: Fix bad URLs in R package for CRAN check

- h2o-docs/src/product/data-science/upliftdrf.rst
JIRA: https://h2oai.atlassian.net/browse/PUBDEV-8639
Suggestions by @meganjkurka:
> PUBDEV-8639 improve Uplift DRF documentation

- h2o-docs/src/product/additional-resources.rst
For: [PUBDEV-8665](https://h2oai.atlassian.net/browse/PUBDEV-8665)
Let me know if you want anything else updated!
> PUBDEV-8665: Added question section to Additional Resources page

- Changes.md
With 52 issues done
-> two pyunit tests not included
> PUBDEV-8657: 3.36.1.1 Release Notes

- h2o-docs/src/product/data-science/gbm.rst
Corrected the spelling of Prof Trevor Hastie's name.
> Update gbm.rst [nocheck]

- h2o-algos/src/test/java/hex/glm/GLMBasicTestBinomial.java
This PR fixes the problem in JIRA: https://h2oai.atlassian.net/browse/PUBDEV-8667
I removed some error print out to avoid cluttering and reduce the coefficient magnitude to avoid sending prob(y=1) = 0 or 1.
> PUBDEV-8667: fix test failure testStandardErrorBinomial

- h2o-py/h2o/explanation/_explain.py
- h2o-r/h2o-package/R/explain.R
https://h2oai.atlassian.net/browse/PUBDEV-8673
> PUBDEV-8673: Improve efficiency and make rug optional in pd_*_plot and ice_plot

- h2o-py/h2o/model/binomial_uplift.py
- h2o-py/h2o/utils/metaclass.py
- h2o-py/tests/testdir_algos/uplift/pyunit_uplift_rf_api_test_depracated.py
https://h2oai.atlassian.net/browse/PUBDEV-8702
> PUBDEV-8702 Refactor Uplift DRF methods

- h2o-docs/src/booklets/v2_2015/source/GLMBooklet.tex
For: [PUBDEV-8687](https://h2oai.atlassian.net/browse/PUBDEV-8687)
Here is how it looks built:
> PUBDEV-8687: Fix GLM booklet Gamma Family error

- h2o-dist/buildinfo.json
- h2o-hadoop-2/h2o-mapr6.2-assembly/build.gradle
- make-dist.sh
- settings.gradle
- Add assembly for MapR 6.2
- Expose MapR 6.2 in infra code
> PUBDEV-8698: Add support for MapR 6.2

- Changes.md
For: [PUBDEV-8711](https://h2oai.atlassian.net/browse/PUBDEV-8711)
With 14 issues done (one closed, not added)
> PUBDEV-8711: 3.36.1.2 Release Notes

- h2o-core/src/main/java/water/api/FramesHandler.java
- h2o-core/src/main/java/water/api/schemas3/FramesV3.java
- h2o-core/src/main/java/water/fvec/Frame.java
- h2o-core/src/main/java/water/parser/BinaryFormatExporter.java
- h2o-core/src/main/java/water/util/ExportFileFormat.java
- h2o-core/src/main/java/water/util/FrameUtils.java
- h2o-parsers/h2o-parquet-parser-tests/src/main/java/water/parser/parquet/H2OTestNodeStarter.java
- h2o-parsers/h2o-parquet-parser/src/main/java/water/parser/parquet/FrameParquetExporter.java
- h2o-parsers/h2o-parquet-parser/src/main/java/water/parser/parquet/ParquetExporter.java
- h2o-parsers/h2o-parquet-parser/src/main/resources/META-INF/services/water.parser.BinaryFormatExporter
- h2o-py/h2o/h2o.py
- h2o-py/tests/testdir_misc/pyunit_export_parquet_multi.py
- h2o-r/h2o-package/R/export.R
- h2o-r/tests/testdir_misc/runit_export_parquet_multipart.R
https://h2oai.atlassian.net/browse/PUBDEV-8679
> PUBDEV-8679: export to parquet

- h2o-py/tests/testdir_misc/pyunit_dataframe_creation_with_)_present_in_header.py
added test to demonstrate non-reproducibility of issue described in https://h2oai.atlassian.net/browse/PUBDEV-8706
> PUBDEV-8706: repro incorrect data frame creation when ) present in header

- h2o-algos/src/main/java/hex/util/CheckpointUtils.java
- h2o-algos/src/test/java/hex/glm/GLMCheckpointTest.java
- h2o-algos/src/test/java/water/test/util/PojoUtilsTest.java
- h2o-core/src/main/java/water/util/PojoUtils.java
https://h2oai.atlassian.net/browse/PUBDEV-7926
https://h2oai.atlassian.net/browse/PUBDEV-7927
> PUBDEV-7926: validateWithCheckpoint should work with arrays + fix AUTO cases

- h2o-bindings/bin/gen_R.py
- h2o-r/h2o-package/R/extendedisolationforest.R
- h2o-r/h2o-package/R/isolationforest.R
- h2o-r/h2o-package/R/modelselection.R
- h2o-r/h2o-package/R/naivebayes.R
- h2o-r/h2o-package/R/randomforest.R
- h2o-r/h2o-package/R/segment.R
- h2o-r/h2o-package/R/stackedensemble.R
- h2o-r/h2o-package/R/upliftrandomforest.R
- h2o-r/tests/testdir_algos/randomforest/runit_RF_segment.R
https://h2oai.atlassian.net/browse/PUBDEV-8727
IMHO this change should work and it's backwards compatible.
> PUBDEV-8727 - make parameter algorithm of train_segments function in R independet from small/large lettters in algo name

- h2o-web/bower.json
https://h2oai.atlassian.net/browse/PUBDEV-8736
> PUBDEV-8736: After an AutoML job the View button does not work

- h2o-r/h2o-package/R/communication.R
- h2o-r/h2o-package/R/explain.R
- h2o-r/h2o-package/R/frame.R
- h2o-r/h2o-package/R/import.R
- h2o-r/h2o-package/R/models.R
- h2o-r/h2o-package/pkgdown/_pkgdown.yml
https://h2oai.atlassian.net/browse/PUBDEV-8713
> PUBDEV-8713: Export with_h2o_no_progress

- h2o-algos/src/main/java/hex/gam/GAMModel.java
- h2o-algos/src/main/java/hex/gam/MatrixFrameUtils/GamUtils.java
- h2o-r/tests/testdir_algos/gam/runit_PUBDEV_8730_paul_gam_offset_error.R
This PR fixes the problem in JIRA: https://h2oai.atlassian.net/browse/PUBDEV-8730
The offset column was not treated properly in GAM.  I fixed the problem and added the user example to make sure my fix works and it does.
> PUBDEV-8730: GAM offset column not working

- h2o-algos/src/main/java/hex/gam/GAM.java
- h2o-algos/src/main/java/hex/gam/MatrixFrameUtils/GamUtils.java
- h2o-algos/src/test/java/hex/gam/GamCVTest.java
- h2o-r/tests/testdir_algos/gam/runit_PUBDEV_8681_paul_gam_cv_no_cv.R
This PR fixes the bug in JIRA: https://h2oai.atlassian.net/browse/PUBDEV-8681.
There is a bug in my code where the fold column is mistreated as a normal column to score for. 
I added code to make sure the fold column is treated properly.
> PUBDEV-8681 GAM predict failure with fold_column

- h2o-docs/src/product/data-science/algo-params/uplift_metric.rst
- h2o-docs/src/product/data-science/upliftdrf.rst
- h2o-py/demos/uplift_drf_demo.ipynb
https://h2oai.atlassian.net/browse/PUBDEV-8753
The actual implementation is according to this source: https://github.com/h2oai/h2o-3/blob/master/h2o-algos/src/main/java/hex/tree/uplift/Divergence.java#L8
> PUBDEV-8753 Fix the documentation of uplift_metric according to javadoc and actual implementation of Divergence class

- h2o-docs/src/product/data-science/glrm.rst
For: [PUBDEV-8751](https://h2oai.atlassian.net/browse/PUBDEV-8751)
I wasn't sure if "transforming data" was a correct header, so please let me know if that or something else needs to be updated :)
> PUBDEV-8751: Added `transform_frame` to GLRM

- h2o-algos/src/main/java/hex/isotonic/PoolAdjacentViolators.java
- h2o-algos/src/main/java/hex/isotonic/PoolAdjacentViolatorsDriver.java
- h2o-algos/src/main/java/water/rapids/prims/isotonic/AstPoolAdjacentViolators.java
- h2o-algos/src/main/resources/META-INF/services/water.rapids.ast.AstPrimitive
- h2o-algos/src/test/java/hex/isotonic/PoolAdjacentViolatorsDriverTest.java
- h2o-algos/src/test/java/hex/isotonic/PoolAdjacentViolatorsTest.java
- h2o-core/src/main/java/water/fvec/Chunk.java
- h2o-core/src/main/java/water/fvec/RebalanceDataSet.java
- h2o-core/src/test/java/water/fvec/RebalanceDatasetTest.java
- h2o-py/tests/pyunit_utils/utilsPY.py
- h2o-py/tests/testdir_algos/isotonic/pyunit_pava.py
@wendycwong This is step one of Isotonic Regression support - the implemented functions will not be directly used by users and are only available as rapids expressions, not via standalone functions
> PUBDEV-6797: Implements Pool Adjacent Violators for Isotonic Regression

- h2o-py/h2o/model/model_base.py
- h2o-r/h2o-package/R/models.R
For: [PUBDEV-8744](https://h2oai.atlassian.net/browse/PUBDEV-8744)
> PUBDEV-8744: Removed mention of R2 returning NaN for non-linear models

- Changes.md
For: [PUBDEV-8754](https://h2oai.atlassian.net/browse/PUBDEV-8754)
With 19 issues done (sans one bug fix which is a test fix)
> PUBDEV-8754: 3.36.1.3 Release Notes

- h2o-core/src/main/java/hex/PartialDependence.java
- h2o-py/tests/testdir_algos/uplift/pyunit_uplift_rf_api_test.py
https://h2oai.atlassian.net/browse/PUBDEV-8773
> PUBDEV-8773 - disable partial_plot in uplift

- h2o-core/src/main/java/water/api/FramesHandler.java
- h2o-docs/src/product/flow/packs/test-small/export_frame.flow
- h2o-docs/src/product/flow/packs/test-small/index.list
- h2o-persist-hdfs/src/main/java/water/persist/S3AClientFactory.java
- Propagate full exception
- Fix flow export
- Add Flow test to check that export_frame works
> PUBDEV-8783: Export Frame in Flow throws NPE

- h2o-core/src/main/java/water/Scope.java
- h2o-core/src/main/java/water/api/TypeaheadHandler.java
- h2o-core/src/main/java/water/persist/S3ClientFactory.java
- h2o-persist-hdfs/src/main/java/water/persist/S3AClientFactory.java
- h2o-persist-hdfs/src/test/java/water/persist/S3AClientFactoryTest.java
- h2o-persist-s3/build.gradle
- h2o-persist-s3/src/main/java/water/persist/IcedS3Credentials.java
- h2o-persist-s3/src/main/java/water/persist/PersistS3.java
- h2o-persist-s3/src/test/java/water/persist/PersistS3MockTest.java
- h2o-persist-s3/src/test/java/water/persist/PersistS3Test.java
@mn-mikke please see https://h2oai.atlassian.net/browse/PUBDEV-8787 for explanation
> PUBDEV-8787: Make configure_s3_using_s3a usable in any deployment

- Changes.md
For: [PUBDEV-8791](https://h2oai.atlassian.net/browse/PUBDEV-8791)
With 4 issues done
> PUBDEV-8791: 3.36.1.4 Release Notes

- h2o-docs/src/product/data-science/algo-params/transform.rst
Removed 'in the training data'.
> Updated transform.rst file

- h2o-algos/src/main/java/hex/glm/GLM.java
- h2o-algos/src/main/java/hex/glm/GLMModel.java
- h2o-algos/src/main/java/hex/glm/GLMTask.java
- h2o-algos/src/main/java/hex/schemas/GLMV3.java
- h2o-algos/src/test/java/hex/glm/GLMBasicTestBinomial.java
- h2o-algos/src/test/java/hex/glm/GLMBasicTestRegression.java
- h2o-algos/src/test/java/hex/glm/GLMdispersionFactorTest.java
- h2o-py/h2o/estimators/glm.py
- h2o-py/tests/testdir_algos/glm/pyunit_pubdev_8574_dispersion_deviance.py
- h2o-r/h2o-package/R/glm.R
- h2o-r/tests/testdir_algos/glm/runit_pubdev_8574_deviance_dispersion_parameter.R
This PR completes the task in JIRA: https://h2oai.atlassian.net/browse/PUBDEV-8574
For dispersion parameter estimation, apart from ml and pearson mode, I added the deviance mode.
In addition, I added tests in Java, Python and R.
> PUBDEV-8574: added deviance option to calculate p-values

- h2o-docs/src/product/data-science/model_selection.rst
For: [PUBDEV-8806](https://h2oai.atlassian.net/browse/PUBDEV-8806)
Added the two commands to the bottom of each example section along with their respective printouts. Please let me know if anything needs to be updated.
> PUBDEV-8806: Added new commands to ModelSelection

- h2o-py/tests/pyunit_utils/utilsPY.py
- h2o-py/tests/testdir_hstats/pyunit_h_all_algos_train_empty_col.py
- h2o-py/tests/testdir_utils/pyunit_utilsPY.py
> PUBDEV-8768 - fix tests for python 2 [nocheck]

- h2o-docs/src/product/data-science/glm.rst
For: [PUBDEV-8829](https://h2oai.atlassian.net/browse/PUBDEV-8829)
This pr adds the VIF information to the GLM docs. Please let me know if anything needs to be updated.
> PUBDEV-8829: Adding VIF to GLM docs

- h2o-algos/src/main/java/hex/glm/DispersionTask.java
- h2o-algos/src/main/java/hex/glm/DispersionUtils.java
- h2o-algos/src/main/java/hex/glm/GLM.java
- h2o-algos/src/main/java/hex/glm/GLMModel.java
- h2o-algos/src/main/java/hex/glm/GLMTask.java
- h2o-algos/src/main/java/hex/glm/TweedieMLDispersionOnly.java
- h2o-algos/src/main/java/hex/modelselection/ModelSelectionModel.java
- h2o-algos/src/main/java/hex/schemas/GLMV3.java
- h2o-algos/src/test/java/hex/glm/GLMTweedieDispersionOnlyTest.java
- h2o-py/h2o/estimators/glm.py
- h2o-py/tests/testdir_algos/glm/pyunit_pubdev_8685_tweedie_dispersion_factor_exceed2.py
- h2o-py/tests/testdir_algos/glm/pyunit_pubdev_8685_tweedie_dispersion_only_less2.py
- h2o-py/tests/testdir_algos/glm/pyunit_pubdev_8774_fix_dispersion.py
- h2o-r/h2o-package/R/glm.R
- h2o-r/tests/testdir_algos/glm/runit_pubdev_8685_tweedie_dispersion_ml.R
- h2o-test-support/src/main/java/water/TestUtil.java
This PR completes the task in JIRA: https://h2oai.atlassian.net/browse/PUBDEV-8685 .
I have completed the implementation in Java.  
I need to generate tweedie dataset so that I can generate comprehensive tests to make sure the estimated dispersion parameter is correct.
In addition, I need to update the documentation so that reviews are possible.
> PUBDEV-8685 implement tweedie dispersion master estimation using maximum likelihood

- Changes.md
For: [PUBDEV-8839](https://h2oai.atlassian.net/browse/PUBDEV-8839)
These notes contain the fix for the security vulnerability.
> PUBDEV-8839: 3.36.1.5 Release Notes

- Changes.md
For: [PUBDEV-8842](https://h2oai.atlassian.net/browse/PUBDEV-8842)
There are currently 55 issues in this release.
These notes are sans duplicates (8683, 8704)
> PUBDEV-8842: 3.38.0.1 Release Notes

- h2o-algos/src/main/java/hex/gam/GAM.java
- h2o-algos/src/main/java/hex/gam/GAMModel.java
- h2o-algos/src/main/java/hex/gam/MatrixFrameUtils/GamUtils.java
- h2o-algos/src/main/java/hex/gam/MatrixFrameUtils/GenCSSplineGamOneColumn.java
- h2o-algos/src/main/java/hex/gam/MatrixFrameUtils/GenISplineGamOneColumn.java
- h2o-algos/src/main/java/hex/schemas/GAMV3.java
- h2o-algos/src/test/java/hex/gam/GAMISplineTest.java
- h2o-core/src/main/java/water/api/Schema.java
- h2o-py/h2o/estimators/gam.py
- h2o-py/tests/testdir_algos/gam/pyunit_PUBDEV_8849_gam_ispline_increasing.py
- h2o-r/h2o-package/R/gam.R
- h2o-r/tests/testdir_algos/gam/runit_PUBDEV_8849_gam_decreasing_func.R
This PR completes the task in JIRA: https://h2oai.atlassian.net/browse/PUBDEV-8849.
Add coefficient constraints for I-spline to allow coefficients to be zero or negative.  Add new parameter
ispline_non_negative as an array which is the same size as gam_columns.  If true, coefficients will be non-negative, false, coefficients will be non-positive.
Added Java/Python/R tests.
> PUBDEV-8849: Enable GAM I-spline to support increasing and decreasing functions

- h2o-r/tests/testdir_jira/runit_pubdev_1365_likelihood.R
This PR completes the task in JIRA: https://h2oai.atlassian.net/browse/PUBDEV-8863
Add printing random column
> PUBDEV-8863: add printing random column

- Makefile
- README.md
- gradle.properties
- h2o-assemblies/main/build.gradle
- h2o-assemblies/standalone_assembly.gradle
- h2o-bindings/build.gradle
- h2o-py/build.gradle
- h2o-r/build.gradle
Also allows to use minimal/steam assemblies instead of the "main" assembly.
This is useful for algo development - it doesn't need heavyweight Hadoop
dependencies, it builds faster and downloads less stuff from the internet.
> Added a Makefile with shortcuts for convenient building [nocheck]

- h2o-bindings/bin/custom/python/gen_deeplearning.py
- h2o-py/h2o/estimators/deeplearning.py
- h2o-py/tests/testdir_algos/deeplearning/pyunit_autoencoder_works.py
https://h2oai.atlassian.net/browse/PUBDEV-8878
> PUBDEV-8878: Fix DeepLearningEstimator autoencoder bug

- scripts/jenkins/groovy/defineTestStages.groovy
Sometimes there is resource contention on the cluster which results
in failed builds.
> Hadoop multinode run more stable when executed sequentially [nocheck]

- h2o-docs/src/product/data-science/model_selection.rst
For: [PUBDEV-8883](https://h2oai.atlassian.net/browse/PUBDEV-8883)
To emphasize the fastest way to build a model, I added an FAQ.  Please let me know what needs to be updated!
> PUBDEV-8883: Added `build_glm_model` parameter to ModelSelection docs

- Changes.md
For: [PUBDEV-8881](https://h2oai.atlassian.net/browse/PUBDEV-8881)
With 13 issues done.
> PUBDEV-8881: 3.38.0.2 Release Notes

- h2o-dist/README.md
- h2o-dist/local_dev.py
And a convenience script to make it all easier
> Added instructions for making changes in download website [nocheck]

- h2o-dist/index.html
- h2o-docs/src/product/downloading.rst
For: [PUBDEV-8869](https://h2oai.atlassian.net/browse/PUBDEV-8869)
> PUBDEV-8869: Added optional `matplotlib` requirement for plotting in python

- h2o-docs/src/product/data-science/model_selection.rst
For: [PUBDEV-8897](https://h2oai.atlassian.net/browse/PUBDEV-8897)
> PUBDEV-8897: Fixed typo for `build_glm_model` in ModelSelection

- h2o-py/h2o/estimators/estimator_base.py
- h2o-py/h2o/utils/shared_utils.py
- h2o-py/tests/testdir_algos/common/pyunit_train_preparation_perf.py
- h2o-py/tests/testdir_utils/pyunit_shared_utils.py
https://h2oai.atlassian.net/browse/PUBDEV-8876
> PUBDEV-8876: extremely slow Py estimator validation when training model with very wide dataset

- h2o-py/h2o/backend/connection.py
- h2o-py/h2o/utils/shared_utils.py
https://h2oai.atlassian.net/browse/PUBDEV-8908
Discussed on the infogram grid PR: https://github.com/h2oai/h2o-3/pull/6349#discussion_r1010508005
> PUBDEV-8908: Make sure we don't leave open file descriptors from H2OConnection

- h2o-algos/src/main/java/hex/tree/BranchInteractionConstraints.java
- h2o-algos/src/test/java/hex/tree/BranchInteractionConstrainsTest.java
- h2o-algos/src/test/java/hex/tree/gbm/GBMInteractionConstraintsTest.java
- h2o-py/tests/testdir_algos/gbm/pyunit_gbm_interaction_constraints_equal_model.py
- h2o-r/tests/testdir_algos/gbm/runit_GBM_interaction_constraints.R
https://h2oai.atlassian.net/browse/PUBDEV-8901
I fixed the bug and to the best of my knowledge​ interaction constrains behave correctly now. If there is anybody fancy i deeper review of Interaction constrains, feel free to do so.
> PUBDEV-8901 interaction constraints fix

- h2o-py/h2o/explanation/_explain.py
- h2o-py/tests/testdir_misc/pyunit_explain.py
- h2o-r/h2o-package/R/explain.R
- scripts/jenkins/groovy/buildConfig.groovy
https://h2oai.atlassian.net/browse/PUBDEV-8903
There was a bug caused by premature optimization - removing categories that would not be plotted which invalidated the `row_index`.
> PUBDEV-8903: Fix incorrect current value indicator

- h2o-docs/src/product/data-science/gam.rst
For: [PUBDEV-8911](https://h2oai.atlassian.net/browse/PUBDEV-8911)
Waiting for https://github.com/h2oai/h2o-3/pull/6417 to merge.
> PUBDEV-8911: Added M-spline implementation to docs

- Changes.md
For: [PUBDEV-8914](https://h2oai.atlassian.net/browse/PUBDEV-8914)
With 19 issues done
- pubdev-8902 excluded (pyunit fix)
> PUBDEV-8914: 3.38.0.3 Release Notes

- h2o-docs/src/product/blog-releases.rst
For: [PUBDEV-8928](https://h2oai.atlassian.net/browse/PUBDEV-8928)
> PUBDEV-8928: Fixed broken blog internal links

- h2o-docs/src/product/welcome.rst
For: [PUBDEV-8929](https://h2oai.atlassian.net/browse/PUBDEV-8929)
Please let me know if anything should be changed or added.
> PUBDEV-8929: added section on how to force an unsupported java version

- h2o-docs/src/product/data-science/eif.rst
- h2o-docs/src/product/data-science/if.rst
For: [PUBDEV-8924](https://h2oai.atlassian.net/browse/PUBDEV-8924)
Requested to add missing values handling info for Isolation Forest and Extended Isolation Forest. I added an FAQ to IF and EIF and put the information there.
@valenad1 could you please make sure I got it correct? Thanks!
> PUBDEV-8924: Added info on missing values handling for IF and EIF

- h2o-algos/src/main/java/hex/ensemble/StackedEnsemble.java
- h2o-bindings/bin/custom/R/gen_stackedensemble.py
- h2o-r/h2o-package/R/stackedensemble.R
- h2o-r/tests/testdir_algos/stackedensemble/runit_stackedensemble_getModel.R
https://h2oai.atlassian.net/browse/PUBDEV-7807
I modeled the model summary TwoDimTable after what we had in R and added the used models since it can be interesting to see how many base models are actually used.
**Python**
**R**
> PUBDEV-7807: Add SE model summary

- h2o-algos/src/main/java/hex/modelselection/ModelSelection.java
- h2o-algos/src/main/java/hex/modelselection/ModelSelectionUtils.java
- h2o-algos/src/test/java/hex/modelselection/ModelSelectionMaxRSweepTests.java
- h2o-py/tests/testdir_algos/modelselection/pyunit_PUBDEV_8785_maxr_runtime_tests_large.py
- h2o-py/tests/testdir_algos/modelselection/pyunit_PUBDEV_8916_maxrSweep_fix_replacement_large.py
- h2o-py/tests/testdir_algos/modelselection/pyunit_PUBDEV_make_cpm.py
This PR fixes the problems in JIRA: https://h2oai.atlassian.net/browse/PUBDEV-8916
I fixed the replacement bugs over the discrepancies pointed out to me by Karthik.
In addition, I speed up the run time by sweeping only the element corresponding to the last element of the CPM matrix.
> PUBDEV-8916 maxrsweep issues

- h2o-algos/src/main/java/hex/schemas/CoxPHV3.java
- h2o-algos/src/main/java/hex/schemas/GLMV3.java
- h2o-algos/src/main/java/hex/schemas/IsolationForestV3.java
This PR completes the task in JIRA: https://h2oai.atlassian.net/browse/PUBDEV-8935 .
> PUBDEV-8935: Minor change to gridable parameters

- h2o-docs/src/booklets/v2_2015/source/GLMBooklet.tex
- h2o-docs/src/product/data-science/glm.rst
For:[ PUBDEV-8940](https://h2oai.atlassian.net/browse/PUBDEV-8940)
Updated the negative binomial log likelihood for GLM user guide page and booklet.
> PUBDEV-8940: Updated log likelihood for GLM negative binomial

- h2o-algos/src/test/java/hex/tree/drf/DRFPredictContribsTest.java
https://h2oai.atlassian.net/browse/PUBDEV-8936
Only formatting change.
> PUBDEV-8936 - prepare DRFPredictContribsTest for parametrized testing

- h2o-algos/src/main/java/hex/tree/drf/DRFModel.java
- h2o-algos/src/test/java/hex/tree/drf/DRFPredictContribsTest.java
- h2o-core/src/main/java/hex/VarImp.java
- h2o-genmodel/src/main/java/hex/genmodel/algos/drf/DrfMojoModel.java
- h2o-genmodel/src/main/java/hex/genmodel/attributes/VariableImportances.java
- h2o-py/tests/testdir_shapley/pyunit_all_algos_not_used_col_has_zero_contribution.py
https://h2oai.atlassian.net/browse/PUBDEV-8936
> PUBDEV-8936 Shapley bugfix for DRF

- scripts/jenkins/jenkinsfiles/Jenkinsfile-Release
@bilcus requested renaming the docker image.
> [PUBDEV-8943] Rename h2o-steam-k8s docker image to h2o-open-source-k8s-minimal

- h2o-py/tests/testdir_algos/modelselection/pyunit_PUBDEV_8675_modelselection_fail.py
This PR is opened to investigate this: https://h2oai.atlassian.net/browse/PUBDEV-8942
Trying to reproduce this error right now by adding debug printout.
[PUBDEV-8942]: https://h2oai.atlassian.net/browse/PUBDEV-8942?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> PUBDEV-8942 backward mode failure

- h2o-docs/src/product/performance-and-prediction.rst
https://h2oai.atlassian.net/browse/PUBDEV-8921
[PUBDEV-8921]: https://h2oai.atlassian.net/browse/PUBDEV-8921?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> PUBDEV-8921 - Fix typos and make examples work in performance-and-prediction.rst - by xiaochi and valenad1

- h2o-algos/src/main/java/hex/tree/CompressedTree.java
- h2o-algos/src/main/java/hex/tree/Sample.java
- h2o-algos/src/main/java/hex/tree/gbm/GBMModel.java
- h2o-algos/src/test/java/hex/tree/gbm/GBMRowToTreeAssignmentTest.java
- h2o-core/src/main/java/hex/Model.java
https://h2oai.atlassian.net/browse/PUBDEV-8637
Hello, here is the implementation for rowToTreeAssignment output from the GBM model. Java implementation is here.
- Python https://github.com/h2oai/h2o-3/pull/6465
- R https://github.com/h2oai/h2o-3/pull/6466
>  PUBDEV-8637 - row to tree assignments implemented model.rowToTreeAssignment API

- h2o-r/h2o-package/R/models.R
- h2o-r/h2o-package/pkgdown/_pkgdown.yml
- h2o-r/tests/testdir_algos/gbm/runit_GBM_row_to_tree_assignment_api.R
https://h2oai.atlassian.net/browse/PUBDEV-8637
Hello, here is the implementation for rowToTreeAssignment R API.
```
library(h2o)
h2o.init()
prostate_path <- system.file("extdata", "prostate.csv", package = "h2o")
prostate <- h2o.uploadFile(path = prostate_path)
prostate_gbm <- h2o.gbm(4:9, "AGE", prostate, sample_rate = 0.6)
h2o.row_to_tree_assignment(prostate_gbm, prostate)
```
> PUBDEV-8637 - row to tree assignments R API

- h2o-py/tests/pyunit_utils/utilsPY.py
- h2o-py/tests/testdir_algos/gam/pyunit_PUBDEV_8163_gam_cv_fold_column.py
- h2o-py/tests/testdir_algos/gam/pyunit_PUBDEV_8398_gam_cv_fold_column.py
This PR tries to fix the problem in JIRA: https://h2oai.atlassian.net/browse/PUBDEV-8956
Added printout when the coefficients are different among the two models to see what the issue is.
> PUBDEV-8956: pyunit_PUBDEV_8398_gam_cv_fold_column.py

- h2o-algos/src/main/java/hex/tree/SharedTree.java
- h2o-core/src/main/java/hex/ModelBuilder.java
- h2o-extensions/xgboost/src/main/java/hex/tree/xgboost/XGBoost.java
- h2o-extensions/xgboost/src/test/java/hex/tree/xgboost/exec/RemoteXGBoostExecutorTest.java
- h2o-py/tests/testdir_misc/pyunit_actual_params_tree_algos.py
- h2o-r/tests/testdir_misc/runit_actual_params_tree_algos.R
https://h2oai.atlassian.net/browse/PUBDEV-8531
Kudos to @tomasfryda who helped a lot to solve this issue.
> PUBDEV-8531 - fix actual parameters when early stopping is enabled

- h2o-py/h2o/explanation/_explain.py
- h2o-r/h2o-package/R/explain.R
https://h2oai.atlassian.net/browse/PUBDEV-8112
> PUBDEV-8112: Add learning curve plot to explain

- h2o-core/src/main/java/water/H2O.java
- h2o-core/src/main/java/water/api/AboutHandler.java
- h2o-py/h2o/backend/cluster.py
- h2o-py/h2o/h2o.py
- h2o-r/h2o-package/R/communication.R
https://h2oai.atlassian.net/browse/PUBDEV-8363
> PUBDEV-8363: Change tone in warning message about H2O version being too old

- h2o-docs/src/product/automl.rst
- h2o-docs/src/product/data-science/xgboost.rst
https://h2oai.atlassian.net/browse/PUBDEV-8967
> PUBDEV-8967: Adding Apple M1 info to docs

- h2o-docs/src/product/data-science/gbm-faq/reproducibility.rst
https://h2oai.atlassian.net/browse/PUBDEV-8987
> PUBDEV-8987 - highlight information about rebalancing

- Changes.md
For: [PUBDEV-8993](https://h2oai.atlassian.net/browse/PUBDEV-8993)
With 39 issues done
excluded: 
- pyunit fixes: 8958, 8956 
- Snyk upgrade: 8969 
[PUBDEV-8993]: https://h2oai.atlassian.net/browse/PUBDEV-8993?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> PUBDEV-8993: 3.40.0.1 Release Notes

- h2o-r/tests/testdir_misc/runit_actual_params_tree_algos.R
Add debug printout according to Wendy's suggestion
> PUBDEV-8531: add debug printout to runit_actual_params_tree_algos.R test [nocheck]

- h2o-py/h2o/model/extensions/fairness.py
https://h2oai.atlassian.net/browse/PUBDEV-8998
> PUBDEV-8998: Fix numpy in fairness

- h2o-py-cloud-extensions/README.md
- h2o-py-cloud-extensions/examples/h2o_cloud_extensions_example_automl.ipynb
- h2o-py-cloud-extensions/examples/h2o_cloud_extensions_example_estimator.ipynb
- h2o-py-cloud-extensions/examples/h2o_cloud_extensions_example_grid_search.ipynb
- scripts/jenkins/jenkinsfiles/Jenkinsfile-Release
Repointing guide and examples to more stable MLOps environment.
> [PUBDEV-9005] Repoint MLOps Integration to internal.dedicated Environment

- h2o-py/tests/testdir_algos/gbm/pyunit_gbm_reproducibility_variable_importance_different_but_same_model_large.py
https://h2oai.atlassian.net/browse/PUBDEV-8997
> PUBDEV-8997 - GBM ensure same model even though variable importance is different

- h2o-algos/src/main/java/hex/schemas/GBMV3.java
- h2o-algos/src/main/java/hex/tree/gbm/GBM.java
- h2o-core/src/main/java/hex/ModelBuilder.java
- h2o-docs/src/product/data-science/gbm-faq/reproducibility.rst
- h2o-docs/src/product/data-science/gbm.rst
- h2o-py/h2o/estimators/gbm.py
- h2o-py/tests/testdir_algos/gbm/pyunit_gbm_auto_rebalance_api.py
- h2o-r/h2o-package/R/gbm.R
https://h2oai.atlassian.net/browse/PUBDEV-8989
I have exposed auto_rebalance parameter. It is available for testing now.
> PUBDEV-8989 expose auto rebalance parameter

- h2o-py/h2o/debug.py
- h2o-py/tests/testdir_algos/gbm/pyunit_gbm_debug_equal_gbm_model_tree_structure.py
- h2o-py/tests/testdir_algos/gbm/pyunit_gbm_debug_equal_gbm_model_tree_structure_large.py
https://h2oai.atlassian.net/browse/PUBDEV-8997
Now, you can use method:
`from h2o.debug import equal_gbm_model_tree_structure`
to check tree structure of GBM
> PUBDEV-8997 - check GBM reproducibility by looking at tree structure

- h2o-py/h2o/model/extensions/fairness.py
- scripts/jenkins/groovy/defineTestStages.groovy
The newly added parameter was tested manually and the following files were removed.
- fair_pd_plot
- fair_roc_plot
- fair_pr_plot
- fair_shap_plot (save_plot_path_prefix)
> [PUBDEV-9009] Add save_plot_path Parameter to Fairness Plotting Method

- h2o-algos/src/main/java/hex/deeplearning/DeepLearningModel.java
- h2o-algos/src/test/java/hex/deeplearning/DeepLearningGradientCheck.java
- h2o-core/src/main/java/hex/DistributionFactory.java
- h2o-core/src/main/java/hex/LinkFunction.java
- h2o-py/tests/testdir_algos/deeplearning/pyunit_mean_residual_deviance_sklearn.py
- h2o-py/tests_rest_smoke/rest_tests/test_models.py
- h2o-r/tests/testdir_algos/deeplearning/runit_deeplearning_poisson_offset.R
- h2o-r/tests/testdir_algos/deeplearning/runit_deeplearning_poisson_weight.R
- h2o-r/tests/testdir_algos/deeplearning/runit_deeplearning_res_deviance.R
- h2o-r/tests/testdir_algos/gbm/runit_GBM_offset_poisson.R
- h2o-r/tests/testdir_algos/gbm/runit_GBM_res_deviance.R
https://h2oai.atlassian.net/browse/PUBDEV-8708
> PUBDEV-8708: fixing deviance computation for Poisson distribution.

- scripts/jenkins/groovy/defineTestStages.groovy
https://h2oai.atlassian.net/browse/ITA-1509
> ITA-1509 - remove java 16 from nightly and repeated nightly and keep only LTS

- Changes.md
For: [PUBDEV-9034](https://h2oai.atlassian.net/browse/PUBDEV-9034)
11 Issues Done
- excluding 8978 (solved in 8952)
[PUBDEV-9034]: https://h2oai.atlassian.net/browse/PUBDEV-9034?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> PUBDEV-9034: 3.40.0.2 Release Notes

- h2o-docs/src/product/index.rst
- h2o-docs/src/product/mojo-capabilities.rst
> I added mojo-capabilities page about every day basics with MOJOs. I fixed and improve other places in documentation as a side effect.
> 
> > and add method varimp() to MOJO wrapper to get Variable Importance more nicely.
> 
> I made separate PR for new varimp() method here: https://github.com/h2oai/h2o-3/pull/5199
I cherry-picked this PR into multiple separate PRs. Currently PR contain only Mojo capabilities page (Mojo basics) and all other side effect fixes are in https://github.com/h2oai/h2o-3/pull/5979
https://h2oai.atlassian.net/browse/PUBDEV-9036
> PUBDEV-9036 Mojo basics documentation

- h2o-docs/src/product/data-science/deep-learning.rst
For: [PUBDEV-9052](https://h2oai.atlassian.net/browse/PUBDEV-9052) (Sub-task of [PUBDEV-8049](https://h2oai.atlassian.net/browse/PUBDEV-8049))
This PR reorganizes Deep Learning parameters by algorithm-specific, autoencoder-specific, and common.
[PUBDEV-9052]: https://h2oai.atlassian.net/browse/PUBDEV-9052?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> PUBDEV-9052: Deep Learning algorithm parameter reorganization

- h2o-docs/src/product/data-science/rulefit.rst
For: [PUBDEV-9061](https://h2oai.atlassian.net/browse/PUBDEV-9061) (Sub-task of [PUBDEV-8049](https://h2oai.atlassian.net/browse/PUBDEV-8049))
This PR reorganizes Rulefit parameters by algorithm-specific and common.
[PUBDEV-9061]: https://h2oai.atlassian.net/browse/PUBDEV-9061?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> PUBDEV-9061: Rulefit algorithm parameter reorganization

- h2o-docs/src/product/data-science/stacked-ensembles.rst
For: [PUBDEV-9062](https://h2oai.atlassian.net/browse/PUBDEV-9062) (Sub-task of [PUBDEV-8049](https://h2oai.atlassian.net/browse/PUBDEV-8049))
This PR reorganizes Stacked Ensembles parameters by algorithm-specific and common.
[PUBDEV-9062]: https://h2oai.atlassian.net/browse/PUBDEV-9062?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> PUBDEV-9062: Stacked Ensembles algorithm parameter reorganization

- h2o-docs/src/product/data-science/coxph.rst
- h2o-docs/src/product/data-science/deep-learning.rst
- h2o-docs/src/product/data-science/isotonic-regression.rst
For: [PUBDEV-9077](https://h2oai.atlassian.net/browse/PUBDEV-9077)(Sub-task of [PUBDEV-8049](https://h2oai.atlassian.net/browse/PUBDEV-8049))
This PR reorganizes these three algorithms' parameter sections to follow an alphabetical pattern.
[PUBDEV-9077]: https://h2oai.atlassian.net/browse/PUBDEV-9077?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> PUBDEV-9077: Alphabetical reordering of Deep Learning, CoxPH, & Isotonic Regression parameters

- h2o-docs/src/product/data-science/aggregator.rst
For: [PUBDEV-9066](https://h2oai.atlassian.net/browse/PUBDEV-9066) (Sub-task of [PUBDEV-8049](https://h2oai.atlassian.net/browse/PUBDEV-8049))
This PR reorganizes Aggregator parameters by algorithm-specific and common in alphabetical order.
[PUBDEV-9066]: https://h2oai.atlassian.net/browse/PUBDEV-9066?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> PUBDEV-9066: Aggregator algorithm parameter reorganization

- h2o-docs/src/product/data-science/if.rst
For: [PUBDEV-9068](https://h2oai.atlassian.net/browse/PUBDEV-9068) (Sub-task of [PUBDEV-8049](https://h2oai.atlassian.net/browse/PUBDEV-8049))
This PR reorganizes Isolation Forest parameters by algorithm-specific, shared tree-based parameters, and common. 
[PUBDEV-9068]: https://h2oai.atlassian.net/browse/PUBDEV-9068?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> PUBDEV-9068: Isolation Forest algorithm parameter reorganization

- scripts/jenkins/groovy/buildConfig.groovy
- scripts/jenkins/groovy/defineTestStages.groovy
I added a possibility to use custom image version
> PUBDEV-8018 use custom version of image [nocheck]

- scripts/jenkins/Makefile.jenkins
- scripts/jenkins/groovy/defineTestStages.groovy
GH issue: https://github.com/h2oai/h2o-3/issues/6837
Jira ticket: https://h2oai.atlassian.net/browse/PUBDEV-9084
This action should solve a problem with timeouts in R tests.
cc @wendycwong @tomasfryda
> [PUBDEV-9084] Move explain tests as dedicated stages to nightly

- .github/workflows/slack-alerts.yml
Change slack channel name.
JIRA: https://h2oai.atlassian.net/browse/PUBDEV-9091
> PUBDEV-9091 : Change slack channel name

- gradle.properties
- h2o-py/h2o/utils/metaclass.py
The problem that we encounter in tests: https://nedbatchelder.com/blog/201010/surprising_getattr_recursion.html
> [PUBDEV-9081][FOLLOWUP] Fix kerberos and hadoop smoke tests

- scripts/jenkins/groovy/insideDocker.groovy
GH issue: https://github.com/h2oai/h2o-3/issues/15537
JIRA ticket: https://h2oai.atlassian.net/browse/PUBDEV-9098
> [PUBDEV-9098] Remove DNS Configuration from Docker Execution Command

- h2o-r/h2o-DESCRIPTION.template
- h2o-r/h2o-package.template
- h2o-r/h2o-package/R/explain.R
- h2o-r/h2o-package/R/models.R
https://h2oai.atlassian.net/browse/PUBDEV-9096
> PUBDEV-9096: Change R package maintainer

- scripts/jenkins/Makefile.jenkins
JIRA ticket: https://h2oai.atlassian.net/browse/PUBDEV-9102
GH issue: https://github.com/h2oai/h2o-3/issues/15544
Current situation:
```
jenkins@mr-0xc5:~/slave_dir_from_mr-0xc1/workspace/h2o-3-nightly-pipeline_master/r4.0-smoke/h2o-3$ ls -l leak-check.out
-rw-r--r-- 1 jenkins jenkins 0 May 30 06:12 leak-check.out
jenkins@mr-0xc5:~/slave_dir_from_mr-0xc1/workspace/h2o-3-nightly-pipeline_master/r4.0-smoke/h2o-3$ if [ -n `cat leak-check.out` ]; then echo "Non-empty";  fi
Non-empty
```
> [PUBDEV-9102] Fix Leak Check

- h2o-core/src/main/java/water/H2O.java
- h2o-py/tests/pyunit_utils/utilsPY.py
- h2o-py/tests/testdir_algos/glm/pyunit_PUBDEV_9093_technical_notes_warn.py
This PR resolves the issue in JIRA: https://h2oai.atlassian.net/browse/PUBDEV-9093 .
I basically just changed the URL from JIRA to github discussions.
Made a test to make sure the correct warning message is found.
> PUBDEV-9093: change technote URL from JIRA site to github discussions

- docker/prisma/Dockerfile
- docker/prisma/Dockerfile.scanningjars
- scripts/jenkins/jenkinsfiles/Jenkinsfile-PrismaScan
Jenkins Pipeline URL: http://mr-0xg1:8080/job/H2O-3/job/steam-prisma-scan/
Sample run: http://mr-0xg1:8080/job/H2O-3/job/steam-prisma-scan/57/
Notes: Enter the correct branch or tag in the input and run manually.
Parent Issues:
- https://github.com/h2oai/h2o-ops/issues/336
- https://github.com/h2oai/h2o-3/issues/15542
> [PUBDEV-9101][DevOps] Jenkins pipeline for steam prisma scan

- h2o-dist/index.html
- h2o-docs/src/product/tutorials/gbm/gbmTuning.ipynb
- h2o-docs/src/product/welcome.rst
- h2o-py/docs/intro.rst
The future package was removed with the support for python 2.7.
> [PUBDEV-9081][FOLLOWUP] Remove usage of future package from documentaion

- h2o-py/h2o/assembly.py
- h2o-py/tests/testdir_apis/H2OAssembly/pyunit_h2oassembly_download_mojo_col_op_string_conversion.py
- h2o-py/tests/testdir_apis/H2OAssembly/pyunit_h2oassembly_download_mojo_documented_pipeline.py
JIRA ticket: https://h2oai.atlassian.net/browse/PUBDEV-9106
GH issue: https://github.com/h2oai/h2o-3/issues/15550
> [PUBDEV-9106] Document H2OAssembly to MOJO2 Export Functionality

- h2o-hadoop-2/assemblyjar.gradle
- h2o-hadoop-3/assemblyjar_common.gradle
- h2o-parsers/h2o-parquet-parser/build.gradle
- h2o-parsers/h2o-parquet-parser/parquet_dependencies.gradle
Green run: http://mr-0xg1:8080/view/H2O-3/job/h2o-3-kerberos-smoke-pipeline/job/mn%252Ffix-kerberos-parquet-tests5/2/
> [PUBDEV-8985] Fix CDH 6.1 kerberos tests

- h2o-core/src/main/java/water/parser/ARFFParser.java
- h2o-extensions/xgboost/src/main/java/hex/tree/xgboost/XGBoostExtension.java
- h2o-py/tests/testdir_parser/pyunit_parse_single_entry_arff.py
https://github.com/h2oai/h2o-3/issues/15572
> GH-15572: Check if headers were set before setting them to null in single entry ARFF parsing [nocheck]

- scripts/jenkins/groovy/defineTestStages.groovy
This PR will resolve issue in GH: https://github.com/h2oai/h2o-3/issues/15599
I added some jenkin test timeout extension as well as they are still experiencing timeouts.
> GH-15599 hadoop timeouts rel 3.42.0 [nocheck]

- h2o-algos/src/main/java/hex/tree/Score.java
- h2o-automl/src/main/java/ai/h2o/automl/AutoMLBuildSpec.java
- h2o-automl/src/main/java/ai/h2o/automl/ModelingStep.java
- h2o-automl/src/main/java/water/automl/api/schemas3/AutoMLBuildSpecV99.java
- h2o-automl/src/main/java/water/automl/api/schemas3/AutoMLV99.java
- h2o-core/src/main/java/hex/CMetricScoringTask.java
- h2o-core/src/main/java/hex/Model.java
- h2o-core/src/main/java/hex/ModelBuilder.java
- h2o-core/src/main/java/hex/ModelMetrics.java
- h2o-core/src/main/java/hex/leaderboard/Leaderboard.java
- h2o-py/h2o/automl/_estimator.py
- h2o-py/tests/testdir_algos/automl/pyunit_automl_supports_custom_metric.py
- h2o-py/tests/testdir_misc/pyunit_make_leaderboard.py
https://github.com/h2oai/h2o-3/issues/15565
> GH-15565: Add custom metric to automl [nocheck]

- gradle/prCheck.gradle
- scripts/jenkins/groovy/insideDocker.groovy
Closes #15601
The new settings checks:
- PR is linked to an issue (via label and a notion in the description)
- the linked issue must have  an assignee, milestone and GH project.
> [GH-15601] Migrate pr checks to github issues [nocheck]

- h2o-dist/buildinfo.json
- h2o-hadoop-3/h2o-emr6.10-assembly/build.gradle
- make-dist.sh
- settings.gradle
> [GH-15597] Add support for EMR 6.10 [nocheck]

- h2o-docs/src/product/admissible.rst
For: https://github.com/h2oai/h2o-3/issues/6574 for bug
Based on the information in the the ticket, I believe this warning is all that is needed. Please let me know if anything needs changed or updated.
> [GH-6574] Add warning to Infogram about correlated columns [nocheck]

- h2o-py/h2o/frame.py
- h2o-py/h2o/utils/shared_utils.py
- h2o-py/tests/pyunit_utils/utilsPY.py
- h2o-py/tests/testdir_misc/pyunit_gh_15614_polars_2_pandas.py
This PR implements issue in GH: https://github.com/h2oai/h2o-3/issues/15614
Implemented workaround suggested by @meganjkurka  with code snippet from @Bernard-H2O.  Added python test to show that speedup actually occurred.
> GH-15614 enable h2o frame to pandas frame conversion using multi-thread from datatable [nocheck]

- h2o-web/bower.json
Closes: #15626 
The PR upgrades H2O Flow UI with the changes made in: https://github.com/h2oai/h2o-flow/pull/184
> [GH-15626] Upgrade H2O Flow UI

- h2o-docs/src/product/faq/hadoop.rst
> [GH-15629] Fixed typo changed core-sit.xml to core-site.html

- Changes.md
#15648 
With 13 issues Done
Excluded from release notes (internal only):
15608, 15601, 15600, 15599
> [GH-15648] - 3.42.0.2 Release Notes

- h2o-core/build.gradle
- h2o-core/src/main/java/water/rapids/ast/prims/string/AstStrDistance.java
- h2o-genmodel-extensions/mojo-pipeline/src/main/java/hex/genmodel/mojopipeline/transformers/StringPropertiesBinaryTransform.java
- h2o-genmodel/build.gradle
- h2o-genmodel/src/main/java/water/util/comparison/string/ExactComparator.java
- h2o-genmodel/src/main/java/water/util/comparison/string/H2OJaroWinklerComparator.java
- h2o-genmodel/src/main/java/water/util/comparison/string/JaccardIndexComparator.java
- h2o-genmodel/src/main/java/water/util/comparison/string/LevenshteinDistanceComparator.java
- h2o-genmodel/src/main/java/water/util/comparison/string/LongestCommonSubstring.java
- h2o-genmodel/src/main/java/water/util/comparison/string/QGramComparator.java
- h2o-genmodel/src/main/java/water/util/comparison/string/SoundexComparator.java
- h2o-genmodel/src/main/java/water/util/comparison/string/StringComparator.java
- h2o-genmodel/src/main/java/water/util/comparison/string/StringComparatorFactory.java
- h2o-genmodel/src/main/java/water/util/comparison/string/StringUtils.java
Closes: #15687
The PR extracts string comparators https://github.com/larsga/Duke library and makes part of the repository.
> [GH-15687] Extract string comparators from Duke library

- h2o-dist/index.html
- h2o-docs/src/product/downloading.rst
- h2o-docs/src/product/flow.rst
- h2o-docs/src/product/index.rst
- h2o-docs/src/product/quick-start-videos.rst
- h2o-docs/src/product/starting-h2o.rst
- h2o-docs/src/product/welcome.rst
For #15680 
This PR adds a note that by default installation is open and to follow our security guidelines if you want a secure installation.
> [GH-15680] Adding installation disclaimer in documentation

- scripts/jenkins/jenkinsfiles/Jenkinsfile-Release
#15716
Wheel is already created in PUBLISH_STAGE_NAME.
This is the first version - release as part of the Pypi stage.
Second version: #15718
> First version: upload h2o_client in release process [nocheck]

- h2o-py/h2o/model/model_base.py
- h2o-py/tests/testdir_jira/pyunit_pubdev_7353_reset_threshold.py
> GH-15713 Improve default threshold API

- h2o-algos/src/test/java/hex/kmeans/KMeansTest.java
> GH-13859 Improve KMeans tests

- h2o-assemblies/main/build.gradle
- h2o-assemblies/steam/build.gradle
> [GH-15755] Upgrade com.squareup.okio:okio in Main and Steam Standalone jars

- h2o-assemblies/main/build.gradle
- h2o-assemblies/steam/build.gradle
> [GH-15757] Upgrade org.jetbrains.kotlin:kotlin-stdlib in Main and Steam Standalone Jar

- h2o-py/h2o/model/model_base.py
- h2o-r/h2o-package/R/models.R
#15719 
Implemented warnings in python and R for accessing model.negative_log_likelihood()
> GH-15719: glm likelihood warnings

- h2o-py/h2o/utils/shared_utils.py
- h2o-py/tests/testdir_misc/pyunit_gh_15729_datatable_2_pandas.py
- h2o-py/tests/testdir_misc/pyunit_gh_15729_datatable_2_pandas_large.py
GH-15729
This test is failing on our CI for python 3.10
> Gendoc is not available for python 3.10 yet [nocheck]

- gradle/prCheck.gradle
Closes https://github.com/h2oai/h2o-3/issues/15787
> [GH-15787] Allow Issue Links in PR Descriptions

- h2o-py/tests/testdir_misc/pyunit_gh_15729_datatable_2_pandas_large.py
Fix the issue here: https://github.com/h2oai/h2o-3/issues/15789
> GH-15729 fix datatable failure

- Changes.md
Closes #15785 
With 9 issues done:
- without internal items:
#15716
#15736
#15789
> [GH-15785] 3.42.0.4 Release Notes

- h2o-docs/src/product/save-and-load-model.rst
> GH-7008, GH-15556 - add DT to list of mojos and edit uplift Mojo

- h2o-algos/src/test/java/hex/adaboost/AdaBoostTest.java
- h2o-docs/src/product/data-science.rst
- h2o-docs/src/product/data-science/adaboost.rst
- h2o-docs/src/product/data-science/algo-params/ignore_const_cols.rst
- h2o-docs/src/product/data-science/algo-params/ignored_columns.rst
- h2o-docs/src/product/data-science/algo-params/learn_rate.rst
- h2o-docs/src/product/data-science/algo-params/model_id.rst
- h2o-docs/src/product/data-science/algo-params/seed.rst
- h2o-docs/src/product/data-science/algo-params/training_frame.rst
- h2o-docs/src/product/data-science/algo-params/weights_column.rst
- h2o-docs/src/product/data-science/algo-params/x.rst
- h2o-docs/src/product/data-science/algo-params/y.rst
- h2o-docs/src/product/save-and-load-model.rst
> GH-6723 - add AdaBoost documentation [nocheck]

- h2o-algos/src/main/java/hex/ensemble/StackedEnsembleModel.java
> Revert "Fix SE contributions for small data - Put result in DKV and name it properly [NOCHECK]"

- h2o-algos/src/main/java/hex/ensemble/StackedEnsembleModel.java
- h2o-algos/src/test/java/hex/deeplearning/DeepLearningSHAPTest.java
- h2o-algos/src/test/java/hex/ensemble/StackedEnsembleSHAPTest.java
changes:
- threshold (eps) set to 1e-4 for DeepLearning and Stacked Ensemble
- Don't rename the final frame, but create it with the correct key
> Fix shap pt.4

- Changes.md
> Revert "[GH-15842] Add "Known Bug" section to release notes"

- h2o-r/h2o-package/R/models.R
> GH-6579: Fix ROC plot axes labels (rel-3.44.0)

- h2o-core/src/main/java/water/rapids/ast/prims/mungers/AstRelevelByFreq.java
- h2o-core/src/test/java/water/rapids/ast/prims/mungers/AstRelevelByFreqTest.java
- h2o-py/tests/testdir_misc/pyunit_relevel_by_freq.py
- h2o-r/tests/testdir_misc/runit_relevel.R
- h2o-r/tests/testdir_misc/runit_relevel_by_freq.R
- h2o-r/tests/testdir_misc/runit_relevel_by_freq_hair.R
Issue: https://github.com/h2oai/h2o-3/issues/15761
> GH-15761 - Fix relevel_by_frequency bug

- h2o-py/h2o/explanation/_explain.py
- h2o-py/tests/testdir_misc/explain/pyunit_explain.py
- h2o-r/h2o-package/R/explain.R
- h2o-r/tests/testdir_misc/explain/runit_explain.R
> GH-15906: Fix learning_curve_plot for CoxPH with specified metric = 'loglik'

- Changes.md
Closes GH-15903
- Moving release to next day.
- Adding one more item.
> [GH-15903] Update release notes

- scripts/jenkins/jenkinsfiles/Jenkinsfile-Release
Closes GH-15921
Propose the spec that used for nighlty builds and hadoop tests.
> [GH-15921] Change Release Pipeline to Run on Jenkins Worker Nodes

- scripts/jenkins/jenkinsfiles/Jenkinsfile-Release
Reverts h2oai/h2o-3#15922, the change needs to go to `rel-3.44.0`
> Revert "[GH-15921] Change Release Pipeline to Run on Jenkins Worker Nodes"

- h2o-algos/src/main/java/hex/glm/GLMMetricBuilder.java
- h2o-algos/src/test/java/hex/glm/GLMTestAICLikelihood.java
- h2o-r/tests/testdir_algos/glm/runit_PUBDEV_8947_GLM_likelihoods_aic.R
- h2o-r/tests/testdir_algos/glm/runit_gh_15891_tweedie_aic.R
> GH-15891: correct sign in AIC calculation as the negative loglikelihood is used

- h2o-algos/src/main/java/hex/ensemble/Metalearner.java
- h2o-algos/src/main/java/hex/gam/MetricBuilderGAM.java
- h2o-algos/src/main/java/hex/glm/GLMMetricBuilder.java
- h2o-algos/src/main/java/hex/schemas/DeepLearningV3.java
- h2o-algos/src/main/java/hex/schemas/GAMV3.java
- h2o-algos/src/main/java/hex/schemas/GLMV3.java
- h2o-algos/src/main/java/hex/schemas/StackedEnsembleV99.java
- h2o-docs/src/product/data-science/algo-params/gainslift_bins.rst
- h2o-py/h2o/estimators/deeplearning.py
- h2o-py/h2o/estimators/gam.py
- h2o-py/h2o/estimators/glm.py
- h2o-py/h2o/estimators/stackedensemble.py
- h2o-py/tests/testdir_misc/pyunit_gainslift_bins.py
- h2o-r/h2o-package/R/deeplearning.R
- h2o-r/h2o-package/R/gam.R
- h2o-r/h2o-package/R/glm.R
- h2o-r/h2o-package/R/stackedensemble.R
#15937 
Related to https://support.h2o.ai/a/tickets/106905
> GH-15937: Expose parameter `gainslift_bins` for DeepLearning, GAM, GLM, and StackedEnsemble

- h2o-algos/src/main/java/hex/schemas/UpliftDRFV3.java
- h2o-algos/src/main/java/hex/tree/SharedTree.java
- h2o-algos/src/main/java/hex/tree/uplift/UpliftDRF.java
- h2o-algos/src/test/java/hex/tree/uplift/UpliftDRFTest.java
- h2o-bindings/bin/custom/R/gen_defaults.py
- h2o-bindings/bin/custom/R/gen_upliftdrf.py
- h2o-bindings/bin/custom/python/gen_defaults.py
- h2o-bindings/bin/custom/python/gen_upliftdrf.py
- h2o-core/src/main/java/hex/ScoreKeeper.java
- h2o-docs/src/product/data-science/algo-params/stopping_metric.rst
- h2o-docs/src/product/data-science/upliftdrf.rst
- h2o-py/h2o/estimators/uplift_random_forest.py
- h2o-py/tests/testdir_algos/uplift/pyunit_uplift_rf_early_stopping.py
- h2o-r/h2o-package/R/upliftrandomforest.R
- h2o-r/tests/testdir_algos/uplift/runit_uplift_rf_early_stopping.R
> GH-15791 UpliftDRF implement early stopping

- h2o-algos/src/test/java/hex/tree/drf/DRFModelValidatingListener.java
Issue: https://github.com/h2oai/h2o-3/issues/15973
> GH-15973 DRF validation check throws NPE

- Changes.md
W/ 18 done currently
w/o:
- 15956 (test fix), 15950 (test fix), 15921 (internal Jenkins), 15886 (internal Snyk)
> GH-15976: 3.44.0.3 Release Notes

- h2o-docs/src/product/conf.py
- h2o-py/docs/conf.py
> GH-16004: Updated copyright to 2024

- h2o-docs/src/product/data-science/algo-params/custom_metric_func.rst
- h2o-docs/src/product/data-science/deep-learning.rst
- h2o-docs/src/product/data-science/stacked-ensembles.rst
- h2o-docs/src/product/data-science/xgboost.rst
- h2o-extensions/xgboost/src/main/java/hex/schemas/XGBoostV3.java
- h2o-extensions/xgboost/src/main/java/hex/tree/xgboost/XGBoost.java
- h2o-extensions/xgboost/src/main/java/hex/tree/xgboost/XGBoostModel.java
- h2o-extensions/xgboost/src/main/java/hex/tree/xgboost/predict/XGBoostModelMetrics.java
- h2o-extensions/xgboost/src/main/java/hex/tree/xgboost/task/XGBoostScoreTask.java
- h2o-extensions/xgboost/src/test/java/hex/tree/xgboost/XGBoostTest.java
- h2o-py/h2o/estimators/xgboost.py
- h2o-py/tests/pyunit_utils/utils_model_metrics.py
- h2o-py/tests/testdir_algos/deeplearning/pyunit_deeplearning_custom_metric.py
- h2o-py/tests/testdir_algos/xgboost/pyunit_xgboost_custom_metric.py
- h2o-py/tests/testdir_algos/xgboost/pyunit_xgboost_eval_metric_stopping.py
- h2o-r/h2o-package/R/xgboost.R
> GH-15967 - add xgboost custom metrics

- h2o-bindings/bin/gen_R.py
- h2o-r/h2o-package/R/frame.R
- h2o-r/h2o-package/R/gam.R
- h2o-r/h2o-package/R/models.R
- h2o-r/h2o-package/R/randomforest.R
- h2o-r/h2o-package/R/upliftrandomforest.R
There are some issues that I discovered during the tests done before submitting to CRAN. It's mostly documentation.
> [nocheck] Fix R package for CRAN

- h2o-py/h2o/utils/shared_utils.py
- h2o-py/tests/pyunit_utils/utilsPY.py
- h2o-py/tests/testdir_misc/pyunit_gainslift_bins.py
- h2o-py/tests/testdir_misc/pyunit_gh_15729_15936_datatable_polars_2_pandas.py
- h2o-py/tests/testdir_misc/pyunit_gh_15729_15936_datatable_polars_2_pandas_large.py
- h2o-py/tests/testdir_misc/pyunit_gh_15994_datatable2pandas_error.py
- h2o-py/tests/testdir_misc/pyunit_model_calibrate.py
- h2o-py/tests/testdir_misc/pyunit_stratified_kfold_medium.py
This pr resolves this issue: https://github.com/h2oai/h2o-3/issues/15994 .  
I basically added the test to make sure what the customer complaint is resolved.
> GH-15994 : check failed dataset conversion to pandas using datatable

- h2o-genmodel/src/main/java/hex/genmodel/tools/PredictCsv.java
- h2o-py/tests/testdir_javapredict/pyunit_pubdev_4628_pubdev_4950_deeplearning_mojo_pojo_autoencoder_large.py
- h2o-py/tests/testdir_javapredict/pyunit_pubdev_4628_pubdev_4950_deeplearning_mojo_pojo_large.py
> GH-15978 Fix DL Autoencoder MOJO PredictCSV bug

- h2o-core/src/main/java/water/rapids/ast/prims/search/AstMatch.java
Change Double in IcedHashMap to IcedDouble
Issue: https://github.com/h2oai/h2o-3/issues/16036
> GH-16036 Fix AstMatchTest failling

- scripts/jenkins/jenkinsfiles/Jenkinsfile-Release
> [GH-16050] Add git user info into release pipeline

- h2o-algos/src/main/java/hex/tree/DTree.java
- h2o-algos/src/test/java/hex/tree/uplift/UpliftDRFTest.java
- h2o-py/tests/testdir_algos/uplift/pyunit_uplift_rf_smoke.py
- h2o-r/tests/testdir_algos/uplift/runit_uplift_smoke.R
> GH-16052 UpliftDRF Fix find best split point

- h2o-core/src/main/java/hex/PartialDependence.java
- h2o-docs/src/product/data-science/upliftdrf.rst
- h2o-py/tests/testdir_algos/uplift/pyunit_uplift_rf_api_test.py
- h2o-py/tests/testdir_algos/uplift/pyunit_uplift_rf_pdp.py
- h2o-r/tests/testdir_algos/uplift/runit_uplift_rf_pdp.R
> GH-6573  UpliftDRF PDP

- h2o-py/h2o/explanation/_explain.py
- h2o-py/tests/testdir_algos/uplift/pyunit_uplift_rf_explain.py
- h2o-r/h2o-package/R/explain.R
- h2o-r/tests/testdir_algos/uplift/runit_uplit_rf_explain.R
Issue: https://github.com/h2oai/h2o-3/issues/16063
> GH-16063 UpliftDRF - Add error in the explain method

- h2o-extensions/xgboost/src/main/java/hex/tree/xgboost/XGBoostExtension.java
https://github.com/h2oai/h2o-3/issues/16060
> GH-16060 - enhance log message with apple silicon not supported

- h2o-algos/src/main/java/hex/tree/DTree.java
- h2o-algos/src/main/java/hex/tree/SharedTree.java
- h2o-algos/src/main/java/hex/tree/uplift/UpliftDRF.java
- h2o-algos/src/test/java/hex/tree/uplift/UpliftDRFTest.java
- h2o-bindings/bin/custom/python/gen_upliftdrf.py
- h2o-docs/src/product/data-science/upliftdrf.rst
- h2o-py/h2o/estimators/uplift_random_forest.py
- h2o-py/tests/testdir_algos/uplift/pyunit_uplift_rf_varimp.py
- h2o-r/tests/testdir_algos/uplift/runit_uplift_rf_varimp.R
Issue:  #6573 
Here are mentioned two approaches to calculating variable importance: https://pbiecek.github.io/xai_stories/story-uplift-marketing1.html#difference---approach
However, we can also calculate variable importance based on Uplift Gain, calculated for every split. I decided to use this approach as a baseline. In the future, we can implement more approaches. WDYT?
> GH-6573 UpliftDRF Variable Importance

- h2o-assemblies/steam/build.gradle
> [GH-16067] Address CVE-2023-35116 in h2o-steam.jar

- h2o-algos/src/main/java/hex/glm/GLMModel.java
- h2o-algos/src/test/java/hex/grid/GridTest.java
- h2o-algos/src/test/java/hex/grid/SequentialWalkerTest.java
- h2o-automl/src/main/java/ai/h2o/automl/ModelingStep.java
- h2o-automl/src/main/java/ai/h2o/automl/modeling/XGBoostSteps.java
- h2o-core/src/main/java/hex/Model.java
- h2o-core/src/main/java/hex/ModelParametersBuilderFactory.java
- h2o-core/src/main/java/hex/ModelParametersDelegateBuilderFactory.java
- h2o-core/src/main/java/hex/ModelParametersGenericBuilderFactory.java
- h2o-core/src/main/java/hex/faulttolerance/Recovery.java
- h2o-core/src/main/java/hex/grid/Grid.java
- h2o-core/src/main/java/hex/grid/GridSearch.java
- h2o-core/src/main/java/hex/grid/HyperSpaceWalker.java
- h2o-core/src/main/java/hex/grid/SimpleParametersBuilderFactory.java
- h2o-core/src/main/java/hex/pipeline/ModelParametersGenericPipelineBuilderFactory.java
- h2o-core/src/main/java/hex/schemas/GridSearchSchema.java
- h2o-core/src/main/java/water/api/GridSearchHandler.java
- h2o-core/src/main/java/water/util/PojoUtils.java
- h2o-core/src/test/java/hex/HyperSpaceWalkerTest.java
- h2o-extensions/target-encoder/src/test/java/ai/h2o/targetencoding/TargetEncoderRGSTest.java
- h2o-py/tests/testdir_algos/glm/pyunit_PUBDEV_8150_warning_alpha_grid.py
- h2o-test-accuracy/src/test/java/water/TestCase.java
Pipeline support in hyperparameter search: https://github.com/h2oai/h2o-3/issues/15856
> GH-15856: Grid pipeline support

- h2o-docs/src/product/data-science/glm.rst
#15930 
Added missing comma in GLM example.
> GH-15930: Added missing comma in GLM example

- h2o-docs/src/product/data-science/decision-tree.rst
> GH-16000: Fixed decision tree example

- h2o-algos/src/main/java/hex/generic/GenericModel.java
- h2o-core/src/main/java/hex/Model.java
- h2o-core/src/main/java/hex/ModelMetricsBinomial.java
- h2o-core/src/main/java/hex/ModelMetricsMultinomial.java
- h2o-core/src/main/java/hex/ModelMetricsRegression.java
Issue: https://github.com/h2oai/h2o-3/issues/16074
> GH-16074 Improve perRow calculation

- h2o-docs/src/booklets/v2_2015/source/bibliography.bib
This version passed on the image i pulled.
> Fix unknown character in citations for booklets

- h2o-py/tests/testdir_misc/pyunit_ice_plot.py
issue: https://github.com/h2oai/h2o-3/issues/16098
I just make sure the single-threaded as_data_frame is used here.
> GH-16098: Add simple fix to fix pyunit_ice_plot.py error

- h2o-persist-hdfs/build.gradle
> GH-16102 - upgrade nimbus-jose-jwt to 9.37.2 [nocheck]

- scripts/jenkins/groovy/defineTestStages.groovy
> GH-15684 - Extend timeout for LOGGER test [nocheck]

- h2o-core/src/main/java/water/persist/PersistManager.java
> [GH-16110] Check if path is local path when checking denied files

- scripts/jenkins/Makefile.jenkins
- scripts/run.py
> GH-15683 - Fix INFO check - remove new SECURITY_WARNING by adding web_ip parameter [nocheck]

- scripts/jenkins/jenkinsfiles/Jenkinsfile-Release
> GH-16113 Config user for all releases

- h2o-assemblies/main/build.gradle
- h2o-assemblies/steam/build.gradle
> GH-16135 - Fix CVE-2024-29131 by commons-configuration2 upgrade

- h2o-docs/src/product/data-science/algo-params/custom_metric_func.rst
- h2o-py/h2o/model/model_base.py
- h2o-py/tests/pyunit_utils/utils_model_metrics.py
Issue: https://github.com/h2oai/h2o-3/issues/15960
> GH-15960 Improve custom metric doc

- scripts/jenkins/groovy/defineTestStages.groovy
> GH-16154 use image version 44 for vanilla xgb test

- scripts/jenkins/groovy/defineTestStages.groovy
> GH-16154 change timeout value for xgboost smoke and nightly stages that usually fail for timeout

- scripts/jenkins/jenkinsfiles/Jenkinsfile-Benchmarks
- scripts/jenkins/jenkinsfiles/Jenkinsfile-Coverage
- scripts/jenkins/jenkinsfiles/Jenkinsfile-Hadoop
- scripts/jenkins/jenkinsfiles/Jenkinsfile-HadoopMultiNode
- scripts/jenkins/jenkinsfiles/Jenkinsfile-Kerberos
- scripts/jenkins/jenkinsfiles/Jenkinsfile-Nightly
- scripts/jenkins/jenkinsfiles/Jenkinsfile-NightlyRepeated
- scripts/jenkins/jenkinsfiles/Jenkinsfile-PrismaScan
- scripts/jenkins/jenkinsfiles/Jenkinsfile-Public
- scripts/jenkins/jenkinsfiles/Jenkinsfile-Release
- scripts/jenkins/jenkinsfiles/Jenkinsfile-Single-Test
- scripts/jenkins/jenkinsfiles/Jenkinsfile-XGB
GH-16154
Since there is no significant issue after label change on master, I would like to put it on rel-* also.
The build is equally unstable for rel-* and master no matter the labels.
> GH-16154 Change node labels in h2o-3 jenkins (#16124)

- h2o-algos/src/main/java/hex/gam/GAM.java
- h2o-r/tests/testdir_algos/gam/runit_GH_16149_gam_row_error.R
issue: https://github.com/h2oai/h2o-3/issues/16149
Changed the key passed to rebalance dataset to be random to avoid collision.
> GH-16149: fix gam rebalance bug

- h2o-docs/src/product/index.rst
#16180 
This PR updates the Index page of the user guide to follow makersaurus guidelines (basic syntax fixes, link text updates, and spacing updates). 
Please let me know if you have any requested updates.
> GH-16180: Updating user guide page Index to reflect makersaurus guidelines

- h2o-dist/buildinfo.json
> GH-16193 add mapr7.0 to the download page

- h2o-parsers/h2o-parquet-parser/src/main/java/water/parser/parquet/FrameParquetExporter.java
- h2o-py/tests/testdir_misc/pyunit_export_parquet_npe.py
> GH-16161 add comparison to the test & dont write NA

- h2o-py/h2o/display.py
- h2o-py/h2o/plot/_matplotlib.py
- h2o-py/h2o/plot/_plot_result.py
> GH-16274: Fix plotting in explain: FigureCanvasAgg is non-interactive, and thus cannot be shown plt.show()

- h2o-jetty-9-minimal/build.gradle
- h2o-jetty-9-minimal/src/main/java/water/webserver/jetty9/Jetty9ServerAdapter.java
- h2o-jetty-9-minimal/src/main/java/water/webserver/jetty9/Jetty9WebsocketServlet.java
> [GH-16284] Add support for Websockets to steam.jar

- h2o-algos/src/main/java/hex/api/Word2VecHandler.java
- h2o-py/h2o/model/models/word_embedding.py
- h2o-py/tests/testdir_algos/word2vec/pyunit_text8_word2vec_large.py
- h2o-r/h2o-package/R/w2vutils.R
- h2o-r/tests/testdir_algos/word2vec/runit_word2vec_find_synonyms.R
Issue: https://github.com/h2oai/h2o-3/issues/16192
> GH-16192 Fix findSynonyms bug

- h2o-r/tests/testdir_algos/randomforest/runit_RF_bigcat.R
- h2o-r/tests/testdir_algos/randomforest/runit_RF_smallcat.R
Issue: https://github.com/h2oai/h2o-3/issues/16197
I suggested removing the tests, but finally, I just improved them not to use the randomForest library.
> GH-16197 Improve RF tests

- h2o-docs/src/product/data-science/gbm.rst
> GH-16288 gbm example syntax fix

- Changes.md
W/ 11 issues done.
excluding:
- 16284: Added support for Websockets to steam.jar.
- 16281: Improved Random Forest tests to not use the randomForest library.
- 16203: Generated constrained GLM pyunit examples.
- 16179: No changes made for Infogram issue.
> GH-16290: 3.46.0.3 Release Notes

- h2o-docs/src/product/data-munging.rst
- h2o-docs/src/product/data-munging/change-column-type.rst
- h2o-docs/src/product/data-munging/combining-columns.rst
- h2o-docs/src/product/data-munging/combining-rows.rst
- h2o-docs/src/product/data-munging/downloading-data.rst
- h2o-docs/src/product/data-munging/fillnas.rst
- h2o-docs/src/product/data-munging/groupby.rst
- h2o-docs/src/product/data-munging/importing-data.rst
- h2o-docs/src/product/data-munging/importing-files.rst
- h2o-docs/src/product/data-munging/imputing-data.rst
- h2o-docs/src/product/data-munging/merging-data.rst
- h2o-docs/src/product/data-munging/pivot.rst
- h2o-docs/src/product/data-munging/replacing-values.rst
- h2o-docs/src/product/data-munging/slicing-columns.rst
- h2o-docs/src/product/data-munging/slicing-rows.rst
- h2o-docs/src/product/data-munging/sortcolumn.rst
- h2o-docs/src/product/data-munging/splitting-datasets.rst
- h2o-docs/src/product/data-munging/tokenize.rst
- h2o-docs/src/product/data-munging/uploading-data.rst
#16214 
This PR updates the Data manipulation pages to adhere to the style guide.
> GH-16214: Updating user guide pages for Data manipulation to reflect makersaurus guidelines

- h2o-docs/src/product/h2o-client.rst
#16212 
This PR updates the H2O-3 clients page to adhere to the style guide.
> GH-16212: Updating user guide pages for H2O-3 Client to reflect makersaurus guidelines

- h2o-docs/src/product/getting-data-into-h2o.rst
#16213 
This PR updates the Getting data into your H2O-3 cluster page to adhere to the style guide and updates any broken links.
> GH-16213: Updating user guide pages for Getting data into your H2O-3 cluster to reflect makersaurus guidelines

- h2o-assemblies/main/build.gradle
> GH-15748 jackson-databind upgrade in main.jar

- Changes.md
> GH-16322: 3.46.0.4 Release Notes

- h2o-assemblies/main/build.gradle
- h2o-assemblies/steam/build.gradle
Fixes #16349 
* sonatype-2024-0171
> GH-16349 jackson databind upgrade to fix sonatype-2024-0171

- build.gradle
Our public build is red and this changed fix it. It can affect the release though, so I merge it to master first and try nightly release. We will be sure after the major release though.
> Fix public build [nocheck]

- docker/prisma/Dockerfile
- scripts/jenkins/jenkinsfiles/Jenkinsfile-PrismaScan
> GH-16354 Remove Snyk and add Trivy

- h2o-bindings/bin/custom/R/gen_stackedensemble.py
- h2o-docs/src/product/admissible.rst
- h2o-docs/src/product/automl.rst
- h2o-docs/src/product/data-science/algo-params/exclude_algos.rst
- h2o-docs/src/product/data-science/algo-params/include_algos.rst
- h2o-docs/src/product/data-science/algo-params/sort_metric.rst
- h2o-docs/src/product/data-science/stacked-ensembles.rst
- h2o-docs/src/product/grid-search.rst
- h2o-docs/src/product/performance-and-prediction.rst
- h2o-r/ensemble/demos/h2o_ensemble_documentation_example.R
- h2o-r/ensemble/demos/h2o_metalearn_documentation_example.R
- h2o-r/ensemble/demos/h2o_stack_documentation_example.R
- h2o-r/ensemble/demos/higgs_randomgrid_stack.R
- h2o-r/h2o-package/R/stackedensemble.R
- h2o-r/tests/testdir_jira/runit_NOPASS_pub_2800.R
> GH-16348 - remove reference to erin-data and h2o-smalldata 

- h2o-docs/src/product/data-science.rst
- h2o-docs/src/product/data-science/early_stopping.rst
- h2o-docs/src/product/data-science/quantiles.rst
- h2o-docs/src/product/data-science/supported-data-types.rst
#16215 
This PR updates the algorithm main page, supported data types, quantiles, and early stopping pages to adhere to the style guide.
> GH-16215: Updating user guide pages for Algorithm main page through Early Stopping to reflect makersaurus guidelines

- h2o-docs/src/product/index.rst
- h2o-docs/src/product/starting-h2o.rst
#16207 
This PR updates the starting H2O-3 page.
(I also included a fly-by update for the index page changing H2O > H2O-3.)
> GH-16207: Updating user guide pages for Starting H2O-3 to reflect makersaurus guidelines

- h2o-assemblies/main/build.gradle
- h2o-assemblies/minimal/build.gradle
- h2o-assemblies/steam/build.gradle
> GH-16397 - remove sun licence from jar

- h2o-docs/src/product/data-science/adaboost.rst
- h2o-docs/src/product/data-science/aggregator.rst
- h2o-docs/src/product/data-science/coxph.rst
- h2o-docs/src/product/data-science/deep-learning.rst
- h2o-docs/src/product/data-science/drf.rst
- h2o-docs/src/product/data-science/eif.rst
- h2o-docs/src/product/data-science/gbm.rst
- h2o-docs/src/product/data-science/glm.rst
- h2o-docs/src/product/data-science/glrm.rst
- h2o-docs/src/product/data-science/if.rst
- h2o-docs/src/product/data-science/k-means.rst
- h2o-docs/src/product/data-science/naive-bayes.rst
- h2o-docs/src/product/data-science/pca.rst
- h2o-docs/src/product/data-science/stacked-ensembles.rst
- h2o-docs/src/product/data-science/svm.rst
- h2o-docs/src/product/data-science/upliftdrf.rst
- h2o-docs/src/product/data-science/word2vec.rst
- h2o-docs/src/product/data-science/xgboost.rst
- h2o-docs/src/product/training-models.rst
> Code/algorithm motivations [nocheck] [nochecks]

- README.md
> Add Zuzana Olajcova to the committers list [nocheck]

- h2o-bindings/bin/custom/python/gen_rulefit.py
- h2o-py/h2o/estimators/rulefit.py
> GH-15983 (UPDATED) [nochecks] [nocheck]

- h2o-parsers/h2o-avro-parser/build.gradle
> GH-16416 - update avro to fix CVE-2024-47561

- h2o-assemblies/main/build.gradle
- h2o-persist-gcs/build.gradle
- scripts/jenkins/jenkinsfiles/Jenkinsfile-PrismaScan
> GH-16423 upgrade protobuf and fix CVE-2024-7254

- h2o-docs/src/product/welcome.rst
#16412 
I just added a requirement to the welcome page that we can easily pull later, but is front-and-center for users to find right now.
> GH-16412: Adding numpy limitations to the docs [nocheck]

- h2o-core/src/main/java/water/util/Log.java
> GH-16361 allow longer pids by adding sys.ai.h2o.log.max.pid.length [nocheck]

- Changes.md
- SECURITY.md
#16442 
With 20 issues done. Excludes:
- 16440
- 16357
> GH-16442: 3.46.0.6 Release Notes [nocheck]

- h2o-bindings/bin/custom/R/gen_hglm.py
- h2o-r/h2o-package/R/hglm.R
Fix issue: https://github.com/h2oai/h2o-3/issues/16445
> Gh-16445 fix h2o.hglm.rd width [nocheck]

- h2o-algos/src/main/java/hex/api/RegisterAlgos.java
- h2o-algos/src/main/java/hex/generic/GenericModel.java
- h2o-algos/src/main/java/hex/knn/CosineDistance.java
- h2o-algos/src/main/java/hex/knn/EuclideanDistance.java
- h2o-algos/src/main/java/hex/knn/KNN.java
- h2o-algos/src/main/java/hex/knn/KNNDistance.java
- h2o-algos/src/main/java/hex/knn/KNNDistanceTask.java
- h2o-algos/src/main/java/hex/knn/KNNHashMap.java
- h2o-algos/src/main/java/hex/knn/KNNKey.java
- h2o-algos/src/main/java/hex/knn/KNNModel.java
- h2o-algos/src/main/java/hex/knn/KNNScoringTask.java
- h2o-algos/src/main/java/hex/knn/ManhattanDistance.java
- h2o-algos/src/main/java/hex/knn/TopNTreeMap.java
- h2o-algos/src/test/java/hex/knn/KNNDistanceTaskTest.java
- h2o-algos/src/test/java/hex/knn/KNNTest.java
- h2o-algos/src/test/java/hex/knn/TopNTreeMapTest.java
- h2o-core/src/main/java/hex/Model.java
- h2o-core/src/main/java/hex/ModelBuilder.java
- h2o-genmodel/src/main/java/hex/genmodel/MojoPipelineWriter.java
- h2o-genmodel/src/main/java/hex/genmodel/descriptor/ModelDescriptor.java
- h2o-genmodel/src/main/java/hex/genmodel/descriptor/ModelDescriptorBuilder.java
- h2o-test-support/src/main/java/water/TestUtil.java
Issue: #16319 
In this PR, I implement the:
> GH-16319 Implement KNN backend [nocheck]

- gradle.properties
> GH-16482 upgade jetty to 9.4.57

- scripts/jenkins/groovy/insideDocker.groovy
> GH-16484 - fix s3 credentials after migration

- scripts/jenkins/groovy/insideDocker.groovy
> GH-16484 - fix s3 credentials after migration (#16485)

- build.gradle
> GH-16471 replace horton work with private repo

- build.gradle
- h2o-bindings/bin/custom/python/gen_xgboost.py
- h2o-py/h2o/estimators/xgboost.py
- h2o-py/h2o/model/model_base.py
> GH-16484 Merge release branch manually

- .github/workflows/slack-alerts.yml
> GH-16484 merge rel branch manually

- docker/jenkins-images/Dockerfile-base
- docker/jenkins-images/Dockerfile-k8s-test
- docker/prisma/Dockerfile
- docker/xgb/centos/Dockerfile-centos-gpu
- docker/xgb/centos/Dockerfile-centos-minimal
- docker/xgb/ubuntu/Dockerfile-ubuntu-gpu
- docker/xgb/ubuntu/Dockerfile-ubuntu-minimal
- docker/xgb_build/Dockerfile-gpu-centos
update Jenkins dockerfiles to use dynamically get jenkins user id and group id
Sample run: http://jenkins.h2o.local:8080/job/H2O-3/job/h2o-3-nightly-pipeline/job/devops%2Fsandev%2Fparameterized-jenkins-id-arg/1/
> feat(ci): update jenkins-Dockerfiles to parameterized Jenkins userID and groupID

- .github/workflows/slack-alerts.yml
> Merge rel branch manually

- docker/Jenkinsfile-build-hadoop-docker
- docker/Jenkinsfile-build-k8s-test-docker
- docker/Jenkinsfile-build-xgb-build-docker
- docker/Jenkinsfile-build-xgb-docker
- scripts/jenkins/Makefile.jenkins
- scripts/jenkins/groovy/buildConfig.groovy
- scripts/jenkins/groovy/buildH2O3.groovy
- scripts/jenkins/groovy/buildH2O3Public.groovy
- scripts/jenkins/groovy/defaultStage.groovy
- scripts/jenkins/groovy/defineTestStages.groovy
- scripts/jenkins/groovy/insideDocker.groovy
- scripts/jenkins/groovy/pipelineUtils.groovy
- scripts/jenkins/jenkinsfiles/Jenkinsfile
- scripts/jenkins/jenkinsfiles/Jenkinsfile-Benchmarks
- scripts/jenkins/jenkinsfiles/Jenkinsfile-Coverage
- scripts/jenkins/jenkinsfiles/Jenkinsfile-Hadoop
- scripts/jenkins/jenkinsfiles/Jenkinsfile-HadoopMultiNode
- scripts/jenkins/jenkinsfiles/Jenkinsfile-Kerberos
- scripts/jenkins/jenkinsfiles/Jenkinsfile-Nightly
- scripts/jenkins/jenkinsfiles/Jenkinsfile-NightlyRepeated
- scripts/jenkins/jenkinsfiles/Jenkinsfile-Public
- scripts/jenkins/jenkinsfiles/Jenkinsfile-Single-Test
- scripts/jenkins/jenkinsfiles/Jenkinsfile-XGB
> GH-16526 Bring back nightly

- scripts/jenkins/Makefile.jenkins
> GH-16526 Debug nightly

- scripts/jenkins/groovy/insideDocker.groovy
added docker volumes to new mounts
> fix: add docker mounts

- scripts/jenkins/jenkinsfiles/Jenkinsfile-NightlyMerge
Parent Issues:
- https://github.com/h2oai/h2o-3/issues/16530
- https://github.com/h2oai/h2o-infra/issues/769
> [DevOps] Nightly Merge Pipeline

- scripts/jenkins/jenkinsfiles/Jenkinsfile-NightlyMerge
> GH-16530 - change main to master

- scripts/jenkins/groovy/defineTestStages.groovy
> GH-16526 Run test that are ok so far (only not deterministic issues)

- scripts/jenkins/jenkinsfiles/Jenkinsfile-NightlyMerge
> [DevOps] GH-16530 Update Repository Name in Nightly Merge Pipeline

- make-dist.sh
- scripts/jenkins/groovy/buildConfig.groovy
- scripts/jenkins/jenkinsfiles/Jenkinsfile-Release
> GH-16527 Nightly release pipeline

- scripts/jenkins/jenkinsfiles/Jenkinsfile
- https://github.com/h2oai/h2o-infra/issues/769
Part of #16550
> [DevOps] GH-16550 Fix Previous Build Cancellation Issue

- make-dist.sh
- scripts/jenkins/groovy/buildConfig.groovy
- scripts/jenkins/jenkinsfiles/Jenkinsfile-Release
> GH-16527 cherry-pick Nightly release pipeline (#16568)

- scripts/jenkins/jenkinsfiles/Jenkinsfile-Release
> GH-16527 Fix heml chart buckets and git credentials 

- scripts/jenkins/jenkinsfiles/Jenkinsfile-Release
> GH-16527 Fetch after setting new remote

- scripts/jenkins/jenkinsfiles/Jenkinsfile-Release
> GH-16527 cherry pick release changes from master

- scripts/jenkins/jenkinsfiles/Jenkinsfile-Release
update cleanup stage of release pipeline, solved permission errors
> fix(ci): Update cleanup stage - release

- scripts/jenkins/jenkinsfiles/Jenkinsfile-Release
> GH-16527 - Fix cleanup stage also in rel branch

- scripts/jenkins/Makefile.jenkins
- scripts/jenkins/jenkinsfiles/Jenkinsfile-Release
> GH-16527 Fix docker release

- scripts/jenkins/Makefile.jenkins
- scripts/jenkins/jenkinsfiles/Jenkinsfile-Release
> GH-16527 Cherry pick docker release fix

- Changes.md
> Release notes for 3.46.0.7

- docker/public/Dockerfile-h2o-release
> Do not run as root by default in the docker image

- h2o-core/src/main/java/hex/schemas/GridSearchSchema.java
- h2o-docs/src/product/grid-search.rst
- h2o-py/tests/testdir_algos/glm/pyunit_gridsearch_glm.py
> GH-16603 allow to use lambda_ in the GridSearch

- gradle/publish.gradle
- scripts/jenkins/jenkinsfiles/Jenkinsfile-Release
> GH-16638 fix release after migration to Maven central

- scripts/jenkins/jenkinsfiles/Jenkinsfile-VulnerabilityScan
Ports https://github.com/h2oai/h2o-3/pull/16648
> Remove Prisma scan from vulnerability check and leave only Trivy

- h2o-persist-hdfs/build.gradle
> Fix CVE-2025-53864 in nimbus-jose-jwt:9.37.4

- h2o-parsers/h2o-parquet-parser/src/main/java/water/parser/parquet/FrameParquetExporter.java
- h2o-py/tests/testdir_misc/pyunit_export_parquet_date_and_uuid.py
> GH-16652 - Fix for empty values in date type col

- Changes.md
> Release notest for 3.46.0.8

- scripts/jenkins/jenkinsfiles/Jenkinsfile-Release
> GH-16638 - increase timeouts for curl
